### ISSUE TITLE
Runner Missing GITHUB_EVENT_PATH

### ISSUE THREAD

**Issue by onyxhat** [actions/runner#1000]
**Describe the bug**
I'm seeing the following error in several actions we pull in regularly - they work fine with GitHub's runners, but not while using a self-hosted runner **_in a container_** . I've verified that the `/github/workflow` folder exists, but whatever process is supposed to be adding the event.json event data doesn't appear to be happening.

```
GITHUB_EVENT_PATH /github/workflow/event.json does not exist
```

The resolution that others seem to be reaching with similar issues is to just run the actions-runner directly on the VM, instead of in the container, but I'd love to keep running as a container.

**To Reproduce**
I see this issue specifically with the following actions:
- wagoid/commitlint-github-action
- FranzDiebold/github-env-vars-action

The easiest to use is `github-env-vars-action` as all it does is create ENV variables and requires no inputs.

**Expected behavior**
The task runs without error and generates my env variables

## Runner Version and Platform
2.277.1

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
```
GITHUB_EVENT_PATH /github/workflow/event.json does not exist
```

## Job Log Output
```
Run wagoid/commitlint-github-action@v2
  with:
    configFile: ./commitlint.config.js
    firstParent: true
    failOnWarnings: false
    helpURL: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
    token: ***
/usr/bin/docker run --name wagoidcommitlintgithubaction225_42f830 --label c3f261 --workdir /github/workspace --rm -e INPUT_CONFIGFILE -e INPUT_FIRSTPARENT -e INPUT_FAILONWARNINGS -e INPUT_HELPURL -e INPUT_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/tmp/runner_work/_temp/_github_home":"/github/home" -v "/tmp/runner_work/_temp/_github_workflow":"/github/workflow" -v "/tmp/runner_work/_temp/_runner_file_commands":"/github/file_commands" -v "/tmp/runner_work/job-data-updater/job-data-updater":"/github/workspace" wagoid/commitlint-github-action:2.2.5
GITHUB_EVENT_PATH /github/workflow/event.json does not exist
GITHUB_EVENT_PATH /github/workflow/event.json does not exist
Error: error trying to get list of pull request's commits
Not Found
HttpError: Not Found
    at /node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getRangeForEvent (/src/action.js:52:29)
Error: error running commitlint
undefined is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at showLintResults (/src/action.js:122:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Runner and Worker's Diagnostic Logs
NA

**Comment by uded** [comment]
Same here, not sure if this was actually investigated since reported.

**Comment by onyxhat** [comment]
@uded I discovered that some of the paths need to be the same on host as in container; then I didn't have the issue anymore. Some of them also need to match ENV variables being set.

**Comment by uded** [comment]
OK, but since I am using Docker my paths are mapped to a volume and paths should be the same within the container. Not sure what you mean then...

**Comment by math-sasso** [comment]
Same here. Did you find a solution?

**Comment by IdiosApps** [comment]
In the GitHub Actions container, does the latest Runner file at `/home/github/_diag/` say anything about writing out the `event.json` file?

**Comment by onyxhat** [comment]
We ended up finding the issue was that the in the container needed to match the path on the host; it wasn't enough to match the path in container with the `GITHUB_EVENT_PATH` variable alone. We haven't had any issues since - it's possible the issue no longer exists on newer versions of the runner.

**Comment by nikola-jokic** [comment]
I will close this issue. If you experience this issue again, feel free to re-open it, or comment on it and we will re-open it and investigate it further :relaxed:
