### ISSUE TITLE
How to debug in an IDE?

### ISSUE THREAD

**Issue by ba32107** [actions/runner#1013]
Hi,

I am trying to figure out the best way to run & debug the Runner in my IDE. I was able to run it locally using the dev scripts, which produce the final binaries in the `_layout` directory, this works fine. But I would like to run and debug it in my IDE.

I got as far as starting the `Runner.Listener` project. All works good until the Runner attempts to start a worker (`Runner.Worker.exe`), and it's looking for this executable in the `bin` directory of `Runner.Listener`. Because it's not there, the process cannot be started and the job hangs indefinitely.

The build process by the dev scripts copies all the binaries into a single directory, which is why it's working when launching from the `_layout` directory. How can I replicate this behavior when launching from an IDE? I could mess around with the csproj files and/or add extra build scripts, but I'm wondering what's the officially recommended way of doing this. The contributing document doesn't say anything about debugging.

Thanks,
Balazs

**Comment by hross** [comment]
Filed an issue here regarding this behavior. We should make this much easier and have an "official" way: https://github.com/actions/runner/issues/1023
