### ISSUE TITLE
Convert workflow file to AgentJobRequestMessage

### ISSUE THREAD

**Issue by ba32107** [actions/runner#1014]
Hi,

Is there any way to convert a workflow file to an `AgentJobRequestMessage` that the Runner can handle? My understanding is that the Runner [continuously polls](https://github.com/actions/runner/blob/8109c962f09d9acc473d92c595ff43afceddb347/src/Runner.Listener/Runner.cs#L330) GitHub, and whenever there is a new job to be executed, GitHub will return a JSON that is [serialized](https://github.com/actions/runner/blob/8109c962f09d9acc473d92c595ff43afceddb347/src/Runner.Listener/Runner.cs#L416) into a `AgentJobRequestMessage` instance, which contains all the workflow details, such as steps, environment variables, inputs, etc.

My use case is very similar as described in https://github.com/actions/runner/issues/494. Whenever a new job request arrives, I want to check the `github.ref` value, and if it does not equal the main branch of the repo, I want to dynamically "replace" the contents of the workflow with the one from the main branch. This would allow my to protect the workflow file from undesired modifications on the branch.

In order to achieve this, I'd need to modify the `AgentJobRequestMessage` object, but since the JSON is constructed on the GitHub side, there is no easy and obvious way for me to say "pick another workflow file, not this one". So I'd need a logic that "converts" a workflow file into an `AgentJobRequestMessage`.

I could implement this myself, but this wouldn't be a long term sustainable solution. Is there any way of asking GitHub to serialize a given revision of a workflow file into the correct format?

Thanks,
Balazs

**Comment by ChristopherHX** [comment]
> I could implement this myself

Well I did it already some month ago. Here is a part of it to convert jobsteps from a yaml file.
Just replace the steps of AgentJobRequestMessage with the result of ConvertStepsFromYaml. I used as much api as I found in the source code. Do anything what you want with this snipped.

```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using GitHub.DistributedTask.ObjectTemplating;
using GitHub.DistributedTask.ObjectTemplating.Tokens;
using GitHub.DistributedTask.Pipelines;
using GitHub.DistributedTask.Pipelines.ObjectTemplating;

namespace Sample {
    public class Program
    {
        public static IEnumerable<JobStep> ConvertStepsFromYaml(string fileRelativePath) {
            var templateContext = new TemplateContext(){
                CancellationToken = CancellationToken.None,
                Errors = new TemplateValidationErrors(10, 500),
                Memory = new TemplateMemory(
                    maxDepth: 100,
                    maxEvents: 1000000,
                    maxBytes: 10 * 1024 * 1024),
                TraceWriter = new EmptyTraceWriter(),
                Schema = PipelineTemplateSchemaFactory.GetSchema()
            };
            var token = default(TemplateToken);
            // Get the file ID
            var fileId = templateContext.GetFileId(fileRelativePath);
            // Read the file
            var fileContent = System.IO.File.ReadAllText(fileRelativePath);
            using (var stringReader = new StringReader(fileContent))
            {
                var yamlObjectReader = new YamlObjectReader(fileId, stringReader);
                token = TemplateReader.Read(templateContext, "steps", yamlObjectReader, fileId, out _);
            }
            var steps = PipelineTemplateConverter.ConvertToSteps(templateContext, token);

            foreach (var step in steps)
            {
                step.Id = Guid.NewGuid();
            }
            return steps.Cast<JobStep>();
        }

        public static void Main(string[] args)
        {
            var steps = ConvertStepsFromYaml("path/to/yamlfile/with/steps.yml");
        }
    }
}
```

A yaml file with steps
```yaml
- name: Step 1
  run: |
    echo Step 1
- name: Step 2
  run: |
    echo Step 2
```
I hope this helps someone :)

**Comment by hross** [comment]
We don't currently support a way to do this on the runner. We have some work in progress to look into better support for policies like this, but it's a larger project than just the runner. I will provide this feedback to our PMs.
