### ISSUE TITLE
config.sh --replace flag is not working

### ISSUE THREAD

**Issue by FloThinksPi** [actions/runner#1021]
**Describe the bug**
-- replace in config.sh setup script is not working

**To Reproduce**
1. Have a worker named myworker already configured
2. Run `./config.sh  --unattended --url https://mygitserver/myorg --token mytoken --replace  --name myworker`
3. See it failing

**Expected behavior**
Replace flag should make the config script to overwrite the worker currently present in the api.

## Runner Version and Platform
2.277.1
Ubuntu 20.04 X86

## What's not working?
Replace Flag does not behave it should according to `./config.sh --help`
```
...
 --replace              Replace any existing runner with the same name (default false)
...
Examples:
...
Configure a runner non-interactively, replacing any existing runner with the same name:
  ./config.sh --unattended --url <url> --token <token> --replace [--name <name>]
...
```
## Runner and Worker's Diagnostic Logs
```
./config.sh --unattended --url https://mygitserver/myorg --token mytoken --replace  --name myworker

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration




A runner with the name myworker already exists.
```

**Comment by FloThinksPi** [comment]
As far as i can tell one also does not get prompted interactively if one wants to replace the runner.
Additionally the env variable ACTIONS_RUNNER_INPUT_REPLACE=true should have the same behaviour but does not.
(Read this is\was the case in 2020 here https://github.com/actions/runner/issues/323)

**Comment by fhammerl** [comment]
👋  Hi @FloThinksPi, thank you for reporting this.


First,

> As far as i can tell one also does not get prompted interactively if one wants to replace the runner.

Running config.sh with the `--unattended` argument will prevent interactive prompts.


> Steps to reproduce the behavior:

Tried to repro on Ubuntu using version 2.227.1. I downloaded the runner two times and configured them one after the other using the same names. The 2nd runner replaced the 1st one without problem. Does it fail for you on a completely new runner as well?
I.e, simply after following these steps and configuring them?

```bash
# Create a folder
mkdir actions-runner && cd actions-runner
# Download the latest runner package
curl -O -L https://github.com/actions/runner/releases/download/v2.277.1/actions-runner-linux-x64-2.277.1.tar.gz
# Extract the installer
tar xzf ./actions-runner-linux-x64-2.277.1.tar.gz
```

**Comment by FloThinksPi** [comment]
ah yea the i overlooked the unnatteded flag :) 

Not currently in the office so i cannot test it but let me add that we run GH Enterprise Server 2.22.X and we use the runner that is advertised by this github instance. So it might be an issue talking with that specific GH Enterprise Version.

I did download exctly like you have done it but from our GHE i think. Then above output happened telling there is a runner already there when --replace is specified tough.

I may be able to test again in 2 weeks  but since we didnt change something i expect the outcome to be the same ...

**Comment by fhammerl** [comment]
Hi @FloThinksPi, this seems really tricky, let's try to get to the bottom of it. I put together a short script to repro and I tried it on one of our GHES dev machines, but the replace worked all the same. 

When you get a chance, can you confirm the output of the script below? Then we can continue from there.

```bash
#!/bin/bash

# Replace these with own token and url

repoUrl=http://github.localhost/github/hub 
runnerToken=ABCDEFGHJKL1234567890123BGGHJF
runnerName=repro-runner-replace

mkdir actions-runner && cd actions-runner
curl -o actions-runner-linux-x64-2.278.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.278.0/actions-runner-linux-x64-2.278.0.tar.gz
tar xzf ./actions-runner-linux-x64-2.278.0.tar.gz
./config.sh --url $repoUrl --token $runnerToken --name $runnerName --unattended

cd ../ 

mkdir actions-runner-replace && cd actions-runner-replace
curl -o actions-runner-linux-x64-2.278.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.278.0/actions-runner-linux-x64-2.278.0.tar.gz
tar xzf ./actions-runner-linux-x64-2.278.0.tar.gz
./config.sh --url $repoUrl --token $runnerToken --name $runnerName --unattended --replace

```

**Comment by FloThinksPi** [comment]
I tested it again and now it works, but we updated to GHE3 in the meantime. 
```
A runner exists with the same name
√ Successfully replaced the runner
```
Think we can thus close this as i cannot reproduce it further and also seems to be fixed with GHE 3 for us :)

**Comment by f0rkz** [comment]
I don't believe this is actually fixed.

**Comment by kryshac** [comment]
with flag it doesn't work, only with the system variable it works (version: `2.295.0`)

**Comment by albertodebortoli** [comment]
I had encountered the `A runner with the name <running_name> already exists.` error but in my case was because the new runner was not in the same runner group as the previous one.
Replacing in the same runner group showed no problem.

runner app version: 2.303.0

**Comment by Shanie1331** [comment]
Enter name of work folder: [press Enter for _work] it is not making folder
