### ISSUE TITLE
Make Runner Start up and Compile/Debug Friendlier

### ISSUE THREAD

**Issue by hross** [actions/runner#1023]
When you fire up the runner for the first time, we lack some basics that we should improve:

* Standardize compile directories for worker and listener so they can be launched from a solution file
* Add a better debug story/breakpoint for the worker process (maybe a flag to break on debug or something similar)
* Fix SDK standardization, if needed (not sure we really need this)
* Does auto-generated compile file need to be autogenerated? Should we just do this on release?
* Make sure this works in Rider, VS Code, Visual Studio

**Comment by fhammerl** [comment]
- Standardize compile directories for worker and listener so they can be launched from a solution file
  - Will not fix: Decided to focus on VS Code developer experience
- Add a better debug story/breakpoint for the worker process (maybe a flag to break on debug or something similar)
  - Done
- Fix SDK standardization, if needed (not sure we really need this)
  - For now, we keep the SDK source as part of the runner repository
- Does auto-generated compile file need to be autogenerated? Should we just do this on release?
  - Follow up issue: [] Convert BuildConstants.cs to BuildConstants.json
- Make sure this works in Rider, VS Code, Visual Studio
  - Will not fix: Decided to focus on VS Code developer experience
