### ISSUE TITLE
Support serverless runners

### ISSUE THREAD

**Issue by villesau** [actions/runner#1030]
**Describe the enhancement**

The workloads in GHA are ephemeral. Runs does not share state between each others. This would make runners an excellent candidate to run on demand and there shouldn't be a need to let runner sit waiting for work. This could be achieved by calling the runner when ever there is work to do. However, to my understanding the runner needs to be running constantly and longpollig Github in order to accept jobs. This prevents from using e.g google cloud run: https://cloud.google.com/run

Serverless runners would also make deploying and scaling runners much easier.

**Comment by hross** [comment]
This would be a nice thing to think about but it would take a large amount of reimagining of the runner and service. I don't think we would do this in the next 6 months so I am going to close this and provide the feedback to our product team. You could also post on the [community forum](https://github.community/c/code-to-cloud/github-actions/41) for visiblity.

**Comment by villesau** [comment]
@hross you could possibly be able to achieve this without changing the current infra much, but just building an adapter instead, see https://github.com/philips-labs/terraform-aws-github-runner for an example. However, that one is exclusively for AWS which limits it's usability.

**Comment by nelsondani** [comment]
Thu
