### ISSUE TITLE
Not all created self-hosted runners are visible in the GitHub action panel

### ISSUE THREAD

**Issue by sandragryga** [actions/runner#1032]
We're keeping our self-hosted runners as part of AWS autoscaling group. Unfortunately, when adding a large number of instances at once (for example, 70 machines), not all of them become visible as GitHub self-hosted runners. In most cases, the solution to this problem is restarting the invisible machines, but it extends the entire scaling process. Do you know what could be the cause of this problem and how we can solve it?

**Steps to reproduce the behavior:**
Create 100 self-hosted runners at AWS account and check if all of them are visible in the GitHub action panel

**Runner Version and Platform**
Runner version: 2.272.0
Platform: AWS, EC2 instances
OS: Linux

**Comment by hross** [comment]
If the runner is connected and active then it should show up correctly. Do you have [diagnostics logs](https://docs.github.com/en/actions/hosting-your-own-runners/monitoring-and-troubleshooting-self-hosted-runners#reviewing-the-self-hosted-runner-application-log-files) from a runner that did not connect, specifically?

If you can give us the runner and account information it's something we can potentially investigate but the first thing is to check diagnostics for a runner that didn't connect to see why. There are a lot of environmental reasons why a runner might not connect (network, issues on the box, etc) so having specifics on the one you're not seeing would make it something we could investigate further.

**Comment by sandragryga** [comment]
The problem was on our side. Thanks for the quick responce. I'm closing this topic
