### ISSUE TITLE
sections marked with `::group::{title}` should be able to request to not be collapsed

### ISSUE THREAD

**Issue by terencehonles** [actions/runner#1036]
I'm sorry if this is the wrong place to request additional workflow commands, but I'm not sure where to put this.

Using the [`::group::{title}` and `::endgroup::`](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#grouping-log-lines) commands are useful to collapse verbose output or add section "headers" to the logs. However, sometimes after creating the group it is discovered that the group should not be collapsed and that it should be shown to the user.

A good example of this would be after a test fails:

![Screenshot from 2021-04-02 11-57-02](https://user-images.githubusercontent.com/438813/113445338-8d57d880-93aa-11eb-99d2-63267f8aac2f.png)

Obviously a user who has experience with the GitHub actions UI and also `tox` in this situation, would know they should expand the grouped log lines above. In this simple example it is rather obvious which lines should be expanded, but this may not always be the case if the logs are long or the grouping is inconsistent or poorly named.

For this use case it would be great if the workflow author could write something like `::group-expand::` in order to force the UI to expand the log lines. This command could be valid until the `::endgroup::` command is issued, and as it is unlikely that a workflow author would need to change their mind about to show or not to show the group so there would not need to be a `::group-collapse::` command.

If this is not possible, an inferior solution would be to have a `::cancelgroup::` command which would act as the `::endgroup::` command, but remove any log grouping which was previously requested.

**Comment by TingluoHuang** [comment]
This would be some UI work instead of a runner change.
Do you create a feature request at https://github.community/c/code-to-cloud/github-actions/41 ?

**Comment by terencehonles** [comment]
@TingluoHuang I can, is that the expected process?

**Comment by TingluoHuang** [comment]
Yes.

**Comment by terencehonles** [comment]
Ok, thanks. For anyone looking later it's here: https://github.community/t/sections-marked-with-title-should-be-able-to-request-to-not-be-collapsed/176389

**Comment by P1119r1m** [comment]
I was unable to find neither feature request:
- https://github.community/c/code-to-cloud/github-actions/41

nor:
- https://github.community/t/sections-marked-with-title-should-be-able-to-request-to-not-be-collapsed/176389

Can someone share the current status of this request?
It is marked as "Closed". 
What does it means? 
Is it closed, or resolved?

**Comment by terencehonles** [comment]
It means that this was the wrong place and it looks like the place I was told to report it in has now disappeared ...so basically this is going to /dev/null :shrug:

**Comment by jefferyto** [comment]
There is a similar request at https://github.com/orgs/community/discussions/39411.

**Comment by nbhoski** [comment]
Any update on https://github.com/orgs/community/discussions/39411 Its really useful feature
