### ISSUE TITLE
GITHUB_TOKEN permissions for ghcr.io only apply to the default branch

### ISSUE THREAD

**Issue by AllexVeldman** [actions/runner#1039]
**Describe the bug**
When using the `GITHUB_TOKEN` to pull images from our private ghcr.io registry following [these instructions](https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio), it only works on the default branch of each repository with access to the image.

This makes it that I can't use our images as part of a `pull_request` workflow using the `GITHUB_TOKEN`.

**To Reproduce**
1. Push a docker image to an organisation ghcr.io registry
2. Add the repository you want to have read access for to the package `Actions Access` in it's `Package Settings`
3. In that repository define a workflow that triggers on `pull_request` that pulls the image from step 1 using the `GITHUB_TOKEN`
4. Create a PR.

**Expected behavior**
I expect the image to be able to be pulled from any branch in the repository i gave permissions to.

## Runner Version and Platform
Cloud hosted ubuntu-latest

## What's not working?
```
Login Succeeded
Error response from daemon: pull access denied for ghcr.io/<org>/<image>, repository does not exist or may require 'docker login': denied: installation not allowed to Read organization package
```

## Job Log Output

Output when trying to pull as a service:
```
Starting foobar service container
  /usr/bin/docker --config /home/runner/work/_temp/.docker_d81b48f1-4348-4e54-ab6b-a314fb1605f4 login ghcr.io -u AllexVeldman --password-stdin
  /usr/bin/docker --config /home/runner/work/_temp/.docker_d81b48f1-4348-4e54-ab6b-a314fb1605f4 pull ghcr.io/<org>/<image>:latest
  Error response from daemon: pull access denied for ghcr.io/<org>/<image>, repository does not exist or may require 'docker login': denied: installation not allowed to Read organization package
  Warning: Docker pull failed with exit code 1, back off 4.111 seconds before retry.
  /usr/bin/docker --config /home/runner/work/_temp/.docker_d81b48f1-4348-4e54-ab6b-a314fb1605f4 pull ghcr.io/<org>/<image>:latest
  Error response from daemon: pull access denied for ghcr.io/<org>/<image>, repository does not exist or may require 'docker login': denied: installation not allowed to Read organization package
  Warning: Docker pull failed with exit code 1, back off 3.738 seconds before retry.
  /usr/bin/docker --config /home/runner/work/_temp/.docker_d81b48f1-4348-4e54-ab6b-a314fb1605f4 pull ghcr.io/<org>/<image>:latest
  Error response from daemon: pull access denied for ghcr.io/<org>/<image>, repository does not exist or may require 'docker login': denied: installation not allowed to Read organization package
  Error: Docker pull failed with exit code 1
```

Output when run as a step:
```
Run echo "***" | docker login ghcr.io --username AllexVeldman --password-stdin
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
Error response from daemon: pull access denied for ghcr.io/<org>/<image>, repository does not exist or may require 'docker login': denied: installation not allowed to Read organization package
```

**Comment by hross** [comment]
This isn't specific to the runner so I'm going to close this issue but I did add this to an internal issue we have tracking this problem and someone will follow up here when it is fixed (this appears to be a bug).

**Comment by bogdannazarenko** [comment]
Experiencing the same issue. Hope to hear soon about a fix.

**Comment by localheinz** [comment]
@hross 

Anything new here?

This is a bit of a bummer when using Docker containers in combination with Dependabot updates!

**Comment by jamilbk** [comment]
Think I'm getting bitten by this as well:

```
pull access denied for ghcr.io/firezone/centos, repository does not exist or may require 'docker login': denied: permission_denied: read_package
```

And yet, GITHUB_TOKEN allegedly has the following permissions as displayed in the `Set up job` section:

```
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```

**Comment by edude03** [comment]
I'm apparently running into this as well :(

**Comment by piotrekkr** [comment]
AFAIK, you need to first:
1. push image to registry
2. go to package settings and then setup permissions for people and repositories that can access this package

**Comment by jonashackt** [comment]
Getting the same error (see [this log](https://github.com/jonashackt/restexamples/runs/4920400487?check_suite_focus=true)) - is this but stil open @hross ?

**Comment by jonashackt** [comment]
The error seems to be fixed now!

But nevertheless you need to follow the instructions @AllexVeldman mentioned (https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio) and head over to your GitHub (orga) profile's package overview, go to the package/container image you want to build inside Actions, scroll to `Manage Actions access` and add the repo and finally configure Role to `write`. This will make your Actions/Runner be able to read and publish your image to the GitHub Container Registry - also from PR branches (no need for a PAT anymore here also)!

**Comment by piotrekkr** [comment]
> go to the package/container image you want to build inside Actions

@jonashackt  Just to be clear. Actions can only add/update new version of existing packages it will never create new one right?

**Comment by jonashackt** [comment]
@piotrekkr with GitHub Actions you can also create new packages - not only existing ones

**Comment by piotrekkr** [comment]
@jonashackt Ok seems like it is working as you described. Thanks

**Comment by iragsdale** [comment]
I'm seeing this too I think.

**Comment by kirqe** [comment]
Have the same problem `denied: installation not allowed to Write organization package`
But when I pull, change something and then push, it works fine -_-

**Comment by iragsdale** [comment]
This turned out NOT to be my problem. I was actually trying to push to a tag I didn't have access to. The error message looks exactly the same.

**Comment by anboch** [comment]
> Have the same problem `denied: installation not allowed to Write organization package` But when I pull, change something and then push, it works fine -_-

I've faced the same error. Fix it through Settings(for repository) - Actions - General - Workflow permissions - Read and write...

**Comment by BR1PERCENTERS** [comment]
How I solved `denied: installation not allowed to Create organization package`

GitHub profile icon -> Your organizations -> Settings -> Actions -> General -> Enable `Read and write permissions`

Then verify on your repo (Settings -> Actions -> General) that `Read and write permissions` are enabled too.

**Comment by ZitRos** [comment]
> GitHub profile icon -> Your organizations -> Settings -> Actions -> General -> Enable Read and write permissions

For some reason the "Read and write permissions" radio button is disabled. I'm the org admin on a free plan.

<img src="https://github.com/actions/runner/assets/4989256/67e21320-c3e6-4b65-8129-242ba0820b8a" width="200"/>

Does anyone have an idea why? It's not clear from the UI.

<details>
  <summary>P.S.</summary>

Setting permissions in yaml as documented [here](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview) produce another weird error when checking .

```yaml
# example
jobs:
  job-name:
    permissions:
      actions: write
```

<img width="889" alt="image" src="https://github.com/actions/runner/assets/4989256/878d1163-18c0-4137-97ad-c8222b099de2">

</details>

UPD

Saying "write-all" permissions in [workflow yaml](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview) has helped, as I assume all permissions must be explicitly set (for pull too):

```yaml
jobs:
  job-name:
    permissions: write-all
```

**Comment by marklai1998** [comment]
> 

should be the Org setting, not the repo setting
If Org is set to read only the repo one will be disabled as you shown

**Comment by marklai1998** [comment]
> > GitHub profile icon -> Your organizations -> Settings -> Actions -> General -> Enable Read and write permissions
> 
> For some reason the "Read and write permissions" radio button is disabled. I'm the org admin on a free plan.
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/4989256/241705751-67e21320-c3e6-4b65-8129-242ba0820b8a.png">
> Does anyone have an idea why? It's not clear from the UI.
> 
> P.S.
> UPD
> 
> Saying "write-all" permissions in [workflow yaml](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview) has helped, as I assume all permissions must be explicitly set (for pull too):
> 
> ```yaml
> jobs:
>   job-name:
>     permissions: write-all
> ```

You have to set in the Org settings first(not the repo one)
If Org is set to read-only, the repo one will be disabled

**Comment by db0** [comment]
I am having the same issue. When I push from `main` it works, when I push via an PR and my action is triggering like so

```
on:
  push:
    branches:
      - main
```

Then I get this error.  I couldn't find the settings described here https://github.com/actions/runner/issues/1039#issuecomment-1019972535 as I'm not in an org.
