### ISSUE TITLE
Duplicated line number in log

### ISSUE THREAD

**Issue by apupier** [actions/runner#1041]
**Describe the bug**

The line 106 appears 2 times https://github.com/apupier/vscode-extension-tester/runs/2297843615?check_suite_focus=true#step:5:106

![Screenshot from 2021-04-08 16-49-15](https://user-images.githubusercontent.com/1105127/114047965-686fd380-988a-11eb-859c-a38e2f2419dc.png)

**To Reproduce**

no idea

2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by hross** [comment]
This is likely an issue with live logs particularly (I see you filed this while it was still running). We know of some transient errors when looking at live logs (we track those issues in a private repo). I will follow up internally. If you look now that the run is complete you'll see there is only one line so this is not an issue with the runner, but how the UI receives updates and displays them.
