### ISSUE TITLE
"The workflow is not valid" does not result in a failure status

### ISSUE THREAD

**Issue by adrienbernede** [actions/runner#1042]
**Describe the bug**
As a Maintainer, if I introduce a syntax error somewhere in a workflow, the test status for my workflow may remain "success".
Since each job results in an item in the check list, I may not notice that one (or several) are missing and therefore misinterpret the checks as being OK.

I am failing to see a use case where it would make sense to consider and invalid workflow as not being a major failure for the checks. This is why I post this as a bug.

An example of the confusing state is visible here: https://github.com/mfem/mfem/runs/2308014062
There is a small indication of a failure next to `builds-and-tests`, but the global status is "success" and reported as such in the PR.

Note: I am using exclusively composite actions.

**To Reproduce**
1. Go to any projects with 2 workflows running on a push event.
2. Introduce a failure in one of the workflows.
3. See the check status still being "success" while some tests didn't pass.

**Expected behavior**
The error "The workflow is not valid" should result in a failure in the global check status.

## Runner Version and Platform
Online composite actions, independent from the runner.

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?

Annotations
1 error
.github/workflows/builds-and-tests.yml#L162The workflow is not valid. .github/workflows/builds-and-tests.yml (Line: 162, Col: 13): Unrecognized named-value: 'env'. Located at position 1 within expression: env.MFEM_TOP_DIR

**Comment by hross** [comment]
👋 @adrienbernede thank you for this feedback. It is definitely odd behavior that we should look at making way more obvious. We have filed an internal bug (the code that does this on the service isn't external) that tracks this and will follow up there. I'm going to close this issue since it's being tracked elsewhere and this doesn't have anything to do with the runner code base. Really appreciate the feedback, though.

**Comment by adrienbernede** [comment]
Hello @hross. I knew this wasn’t the best place to create this issue, I couldn't find the appropriate one though. I chose this repo because of the issue open on future work for composite actions... but that was far-fetched.

Thank you for not making a fuss about it. I am interested in the right way to report such an issue for the future.

**Comment by radiomix** [comment]
@hross You wrote:
>We have filed an internal bug (the code that does this on the service isn't external) that tracks this and will follow up there. 

Where is this _internal bug_ being filed? Where is your follow up?

>I'm going to close this issue since it's being tracked elsewhere and this doesn't have anything to do with the runner code base. 

Where is this tracked? Where **is** the code to fix the bug?  

**Why**  did you close this *bug*  without referencing any of the undergoing work related to fix it?
