### ISSUE TITLE
failed: Temporary failure in name resolution.

### ISSUE THREAD

**Issue by tbarbette** [actions/runner#1052]
Since a few hours github actions has problem resolving domain names. I don't see any issue currently raised anywhere about that. See https://github.com/tbarbette/fastclick/runs/2379801053?check_suite_focus=true for "framework". 

"wget http://fast.dpdk.org/rel/dpdk-20.11.tar.gz" works great from any computer I have though.

**Comment by TingluoHuang** [comment]
@tbarbette 

https://github.com/actions/virtual-environments would be a better place to report this since this repo is for the runner executable only.

https://github.com/actions/virtual-environments has context on how the Hosted runner VM sets up.

I am going to close this for now. 😆
