### ISSUE TITLE
GITHUB_TOKEN cannot issue /dispatches call with write-all permissions

### ISSUE THREAD

**Issue by benkaiser** [actions/runner#1053]
**Describe the bug**
When taking a GITHUB_TOKEN from a workflow run (while the run is still running, so it isn't yet expired) and trying to call [repository dispatch](https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event) results in a 204 but an action isn't created. Calling that same `dispatches` endpoint with my PAT works correctly.

**To Reproduce**

Reproduction can be seen in this repo: https://github.com/benkaiser/testing-web-action-persistence

1. Create the same repo under your own account
2. Run "Testing Token" (`token.yml`) workflow
3. Grab GITHUB_TOKEN that is output from the node.js file. Note that a hyphen is added as the second character to bust the obfuscation in the logs.
4. An any browser tab (e.g. from a github pages site) run the fetch request in [`examples/request.js`](https://github.com/benkaiser/testing-web-action-persistence/blob/master/examples/request.js) replacing the repo user/name with your repo and the Bearer token with your GITHUB_TOKEN pulled from the previous step (making sure to remove the added hyphen second character).
5. Note that even though you receive a 204 indicating a successful request, the action does not actually start on the repo.

If you run the same `request.js` in step 4 above with a PAT with `workflow` permissions, you'll receive a 204 and the action will successfully fire.

**Expected behavior**
`GITHUB_TOKEN` with all permissions should be able to successfully trigger actions via `/dispatches` endpoint.

## Runner Version and Platform
Version of your runner?
Not sure, check the example repo?

OS of the machine running the runner?
Ubuntu Linux

## What's not working?

Request with GITHUB_TOKEN (now expired obvsiously) returns 204, but workflow run not triggered.
![image](https://user-images.githubusercontent.com/608054/115559219-d8547400-a2f6-11eb-916a-dc9552f7ea0d.png)

## Job Log Output
N/a

## Runner and Worker's Diagnostic Logs
N/a

## Background to issue

I'm trying to achieve a dynamic github pages website via a XHR call to trigger an action that writes data to the repo itself which in-turn updates the github pages website. If I could simply generate a PAT that only had action execution permission to call `/dispatches` on a specific repo, that would also solve my use-case. Even write perms would be fine, so long as I could scope to the single repo so the worst damage a public user could do is to that repo and not all my other repos.

**Comment by TingluoHuang** [comment]
I don't think this is an issue scope to the runner, please report it to the https://github.community/c/code-to-cloud/github-actions/41
