### ISSUE TITLE
Cron runs long

### ISSUE THREAD

**Issue by ZakharYA** [actions/runner#1063]
**Describe the bug**
I have a workflow that runs every hour.
It happens when he performs it in a minute, and it happens that he runs it for 9 minutes, and 15 seconds, the work itself is performed.
This takes a lot of minutes, because my task does not require 9 minutes.

**To Reproduce**
Create a cron task every hour.
Test it, and wait for it to run longer than usual.

**Expected behavior**
Github actions will not spend minutes for running itself.

## Runner Version and Platform
Github Actions

OS of the machine running the runner? 
Linux ubuntu latest (20.04)

## What's not working?
It takes many minutes to launch itself.
![browser_mgjCTGpryb](https://user-images.githubusercontent.com/48249806/115956895-a70fba00-a529-11eb-9374-2d5b364a16d8.png)
![browser_KuoKX2cL3i](https://user-images.githubusercontent.com/48249806/115956899-a8d97d80-a529-11eb-9620-5e8af5965ba9.png)

**Comment by ZakharYA** [comment]
I see that it says "Billable time 15s", but in fact the entire launch time is spent in the tariff.

**Comment by TingluoHuang** [comment]
That time includes all the waiting time, ex: the workflow is queued, but you don't have available runner at that point.

**Comment by ZakharYA** [comment]
That doesn't sound fair, but I'm gonna have to accept it.
