### ISSUE TITLE
CI check runners broken after renaming branch

### ISSUE THREAD

**Issue by Integralist** [actions/runner#1065]
Hello,

I renamed a repository branch from `master` to `main` and subsequently discovered the CI check for macos stopped working with a vague message that simply stated `This check was cancelled` ([example PR](https://github.com/fastly/cli/pull/264), although all PRs for this repo now have broken CI checks because of this issue).

I tried to move from `macos-latest` to `macos-11.0` just to see if there was an issue with 'latest' and what happened instead was that the Ubuntu and Windows 'latest' CI checks (which were working fine) suddenly failed with the `This check was cancelled` error while the macos check changed to `This check failed`. In either case the error message isn't detailed enough for me to make any meaningful progress.

Thanks for any help you give me.

**Comment by TingluoHuang** [comment]
@Integralist which error you are talking about? 
I am seeing all your checks are passed.
![image](https://user-images.githubusercontent.com/1750815/116093536-c0714d00-a674-11eb-9706-2dac07d6cceb.png)

I saw the original error
![image](https://user-images.githubusercontent.com/1750815/116093708-e72f8380-a674-11eb-8aaa-8adfe993b8ad.png)
which normally means something totally busted on the GitHub Actions Service side.

I will try to find people to help me check the server error since it's not scoped to the runner itself. 🙇‍♂️

**Comment by Integralist** [comment]
Thanks @TingluoHuang 

So I _believe_ what has happened here is that my colleague opened a new PR on that repo but modified the `.github/workflows/pr_test.yml` file to not have any platform related checks. Then she added each platform back in one at a time, and we think this might have forced the `actions/cache@v1` to drop any old references it might have had so that when each action step was put back in the runs started working again.

I'm not entirely sure if that's accurate because I had modified the `key` field of the `actions/cache@v1` action prior to her doing so and it had made no difference 🤷🏻 

Feel free to close this issue, unless you would prefer to leave it open a little while longer while you investigate whether there were any underlying problems that still need to be addressed. 

But from my perspective, it appears the CI checks are all running again 🎉 🙂

**Comment by TingluoHuang** [comment]
The service engineer told me that your job got affected by a bug when they turned on a feature flag for macOS hosted pool. The Feature flag has been reverted after they noticed this kind of failure from their telemetry.

I am going to close this issue for now, please reopen if you need more help. 🙇‍♂️
