### ISSUE TITLE
Deploy Nuxt using Github-Action + PM2 then PM2 log not showing

### ISSUE THREAD

**Issue by nhj7** [actions/runner#1068]
**Describe the bug**
Deploy Nuxt using Github-Action + PM2 then PM2 log not showing

**To Reproduce**
1. github action ci.yml run `pm2 reload echosystem.config.js --env production`
2. echosystem.config.js : 
  ........
  script: './node_modules/nuxt/bin/nuxt.js',
  args: 'start',
  ....

https://nuxtjs.org/docs/2.x/deployment/deployment-pm2

3. action runner . workflow run
  - https://github.com/nhj7/cocomon_fe/blob/main/.github/workflows/ci.yml

## Runner Version and Platform
Version of your runner? 
actions-runner-linux-x64-2.278.0

OS of the machine running the runner? OSX/Windows/Linux/...
Linux ubuntu 18

## What's not working?

<pre>
github@ubuntu:/app/actions-runner$ pm2 logs
</pre>

github action start pm2 log
 - empty

manual start pm2 log

![normal](https://user-images.githubusercontent.com/23010726/116343006-8cd22680-a81e-11eb-9eaa-e2be709f2f5f.PNG)

**Comment by TingluoHuang** [comment]
@nhj7 I am not sure whether this is a runner issue or not since the runner just invokes `pm2` and wait for return code 0, you might want to check all your pm2 config file to make sure all logging parameters are setup right.

**Comment by TingluoHuang** [comment]
Closing... no response from the customer.
