### ISSUE TITLE
Required checks will stop to be required if their name later on become shadowed by a faster job in another workflow

### ISSUE THREAD

**Issue by Daskeladden** [actions/runner#1085]
**Describe the bug**
Required checks will stop to be required if their name later on become shadowed by a faster job in another workflow

**To Reproduce**
1. Make a workflow "A" with a job named "Test" and make that job take 1 minute and then always fails
2. Go into GitHub actions branch protection rule and make "Test" required for merge to `master`
3. Make a branch from master and push an empty commit
4. Make a PR
5. See that the PR is blocked from being merged
6. In the branch, add a new workflow "B" and a job called "Test" and make it succeed instantly.
7. Push empty commit to branch
8. Observe that the `Merge button` becomes active and clickable once the job "Test" from workflow B has completed even though the job "Test" from workflow "A" is still running.

**Expected behavior**
PR should be blocked from being merged until all jobs named "Test" have completed successfully.

## Runner Version and Platform
Runner version: 2.278.0
Self hosted runner Linux Ubuntu 20.04

## What's not working?
See above.

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A

**Comment by dominikmeyersap** [comment]
We actually use that to our advantage (bad design, but no other solution) for mono repos to have required jobs per "directory" 🤦🏼‍♂️
The "faster" `exit 0` jobs we  use to exclude tooling folders.

**Comment by nedrebo** [comment]
We are also doing mono repo in GA. Silently allowing shadowing is making it hard to guarantee no regressions in the merge checks.

Another issue that may be relevant: https://github.com/actions/runner/issues/1115

**Comment by nedrebo** [comment]
I have added a reproducer here: https://github.com/nedrebo/github-actions-merge-check-go-green-prematurely/pull/1

As you can see the PR is _now unmergable_.

_However_, when the workflow was running the situation was like this:

![ga-premature-green-merge-button](https://user-images.githubusercontent.com/5791955/130258812-95f80efc-3d5e-4831-ba59-45bd39fcac8d.png)

This can open up for fun times in a system that have merge bots and continuous delivery. I would consider this a critical bug.
