### ISSUE TITLE
Relative File Paths Are Not Supported by ENTRYPOINT in Docker Actions  

### ISSUE THREAD

**Issue by tahteche** [actions/runner#1088]
On my laptop using relative paths with ENTRYPOINT (exec  form) works fine but when I try to run my Docker action in GH Actions I get the following error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "./bin/dreamteam": stat ./bin/dreamteam: no such file or directory: unknown.

Here's the last stage of the Dockerfile which has the issue:

```
FROM adoptopenjdk:11-jdk-hotspot AS execute

WORKDIR /app

# Copy build directory containing build artifacts
COPY --from=build /app/dreamteam-1.0-SNAPSHOT .

RUN pwd \
    && ls -R \
    && ls -l ./bin/dreamteam

# NEVER FORGET TO USE ABSOLUTE PATH!!!
ENTRYPOINT ["./bin/dreamteam"]
```

Using `ls` from within the same working directory to test the exact relative path that failed with `ENTRYPOINT` showed that the file was in the location I expected.
`ls -l ./bin/dreamteam`

After a couple hours 🙁 I changed the relative path to an absolute one and it worked.
`ENTRYPOINT ["./bin/dreamteam"]` -> `ENTRYPOINT ["/app/bin/dreamteam"]`

Like I stated earlier the relative path worked when running Docker locally so I guess this is a bug with GH Actions or at least the difference in behavior should be stated in the [documentation for building Docker actions ](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)

**Comment by TingluoHuang** [comment]
@tahteche can you share some workflow run logs or a link to your workflow run if your repository is public?

**Comment by tahteche** [comment]
Here's the link to the workflow run that failed before I fixed the issue: 
https://github.com/tahteche/springcat/runs/2564064523?check_suite_focus=true

**Comment by TingluoHuang** [comment]
@tahteche thanks. 

we overwrite the workdir with `--workdir /github/workspace`, which is causing your problem, I will file an issue to fix the documentation.

**Comment by Darius1999boop** [comment]
1088

**Comment by nikola-jokic** [comment]
Hi @tahteche, I made a suggestion that is merged to the docs now. Thank you for filing this issue! This also helped us improve the docs so other people don't bump into the same problem. If you have any other suggestions, feel free to comment here, or open another issue.
