### ISSUE TITLE
This check was cancelled

### ISSUE THREAD

**Issue by MaximeBernard** [actions/runner#1092]
**Describe the bug**
I'm getting `This check was cancelled`.

**Expected behavior**
A clear and concise description of the cancellation.

"Who" canceled it?
Why?
Maybe a documentation page to explain a bit what can cause this behavior? 

## Runner Version and Platform
Version of your runner: didn't mention anything in my yml so latest I guess?

OS of the machine running the runner: ubuntu-latest

## Job Log Output
```
GitHub Actions has encountered an internal error when running your job.
```

## Runner and Worker's Diagnostic Logs
_If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here._
=> How do I find those in my current state?

## How to reproduce

If any Github Admin has access to this: https://github.com/kymono/kymdom/actions/runs/842366534

**Comment by TingluoHuang** [comment]
There is an incident going on right now, you can follow up on https://www.githubstatus.com/incidents/plk7zdvpftby
I am going to close this since it's not an issue with the runner itself.
