### ISSUE TITLE
github actions runner : queue ?

### ISSUE THREAD

**Issue by alnhk** [actions/runner#1093]
**Describe the bug**
We would like to know if github actions runners support queuing ? 

**To Reproduce**
1. On top of AWS, we are using github enterprise 2.22 with AWS EKS 1.19 cluster 
2. create a docker image with ephemeral support (usng ./run --once) using similar entrypoint.sh from https://github.com/actions/runner/issues/559
3. Deploy the docker image on AWS EKS 1.19 cluster and able to see one runners registered to github enterprise
4. On the Deployed docker image, enable HPA minPod =1 and MaxPod=15 with cpu-percent=30 (Horizontal Pod Autoscaler) using this link - https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
5. Tetsted on one of the deployed github actions runners and ran some dummy process in order to make CPU load to cross 30% and can confirm that github actions runners scaled up to 5 automatically (replicas=5)
5. from Github Actions, trigger "only" one workflow and this works fine on one github actions runner 
6. Now trigger 5-10 github actions, out of 10 triggered workflows, 1st one completed however remaining 9 failed.

Question :  
- is the queuing supported ? 
- Shouldnt the bunch of  github actions triggered  be queued  and wait for available runners ?

**Comment by TingluoHuang** [comment]
ephemeral runner `run --once` is not fully support yet, we are working on getting it done soon, so this issue should be fixed at that time.

**Comment by thboop** [comment]
ephemeral runners are now released and this should work as expected, please let me know if you see any more issues.
