### ISSUE TITLE
Past run logs etc. being overwritten by Re-run jobs

### ISSUE THREAD

**Issue by cpswan** [actions/runner#1118]
**Describe the enhancement**
Keep and show logs for every re-run, whether it passes or fails.

At present if I have a failed run, which might have valuable stuff in the logs, which I might want to refer to in an issue for an upstream fix or whatever, that gets lost when the job is re-run.

* example [atsign-foundation/at_server_trunk #25](https://github.com/atsign-foundation/at_server/actions/runs/863279637) initially failed due to a missing dependency, but re-run was successful after implementing a local fix, but now there's no way to get the logs showing the original issue.

Similarly if a successful run is re-run and then fails, there's no evidence that there was ever a successful run.

* example [atsign-company/labels #95](https://github.com/atsign-company/labels/actions/runs/852944325) succeeded on its initial run but then failed on re-run.

**Comment by TingluoHuang** [comment]
You might want to report this issue to https://github.community/c/code-to-cloud/github-actions/41
The runner doesn't control how the UI renders the completed job log.

**Comment by cpswan** [comment]
Thanks @TingluoHuang - https://github.community/t/past-run-logs-etc-being-overwritten-by-re-run-jobs/183331
