### ISSUE TITLE
Find a way to remove BuildConstants.cs changes from git diff

### ISSUE THREAD

**Issue by fhammerl** [actions/runner#1129]
Running a build using `dir.proj` generates a file called `BuildConstants.cs` with string constants like version, commit hash and os platform.
We cannot just remove and ignore this file, because the project doesn't compile if it doesn't exist. But every time you make a commit and build, this file changes. Currently, we just ignore it when it shows up in the diff.

(non-trivial) Solution 1: Convert it into a config file so the compiler is not reliant on it

(quick win) Solution 2: Generate (at least a dummy version of) `BuildConstants.cs` in `Runner.Sdk.csproj` using `
  <Target [...] BeforeTargets="Build">`. Now the project can be built without the compiler missing the file.

**Comment by TingluoHuang** [comment]
Fixed.
