### ISSUE TITLE
Podman: support "cgroupManager: systemd" for non-root users

### ISSUE THREAD

**Issue by fauust** [actions/runner#1134]
**Describe the enhancement**
It is impossible at the moment -- or I did not find how -- to start a podman container with systemd without using `sudo`.
It would be very nice to be able to do so for molecule/ansible testing where a container needs to be running in the background to test ansible deployments.

**Code Snippet**
```console
podman run -t --systemd=always fauust/docker-systemd:debian-10
...
Failed to create /system.slice/runner-provisioner.service/init.scope control group: Permission denied
Failed to allocate manager object: Permission denied
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
Error: Process completed with exit code 255.
```

**Additional information**
There seems to be a cgroup permission problem:
```console
podman info | grep cgroup
  cgroupManager: cgroupfs
  cgroupVersion: v1

sudo podman info | grep cgroup
  cgroupManager: systemd
  cgroupVersion: v1
```
Using: `ubuntu-latest` runner

**Comment by TingluoHuang** [comment]
You might want to ask this question in the https://GitHub.com/actions/virtual-environment repo, that repo has context around how the hosted runner vm setup and what user/permission the runner was run under.

This repo is only for the runner executable itself.

**Comment by fauust** [comment]
> You might want to ask this question in the https://GitHub.com/actions/virtual-environment repo, that repo has context around how the hosted runner vm setup and what user/permission the runner was run under.
> 
> This repo is only for the runner executable itself.

Done, it's https://GitHub.com/actions/virtual-environments BTW (typo, plural).

Thanks!

**Comment by ethomson** [comment]
Thanks for opening that issue @fauust - I'm going to close this one.
