### ISSUE TITLE
Stuck on “starting your workflow run”

### ISSUE THREAD

**Issue by thread-liu** [actions/runner#1140]
**Describe the bug**
Stuck on “starting your workflow run" ： [action](https://github.com/RT-Thread/rt-thread/actions/runs/916905930)

**To Reproduce**
1. Push the code and request
2. run ci
3. exception occurs

**Expected behavior**
Stuck on “starting your workflow run"

## Runner Version and Platform
```
Current runner version: '2.278.0'
```

Linux 

## What's not working?
All the workflow is stuck  on “starting your workflow run"

## Job Log Output

```
Starting workflow run
```

## Runner and Worker's Diagnostic Logs

You can see, all workflows struck on “starting your workflow run":

![image](https://user-images.githubusercontent.com/44889940/121118405-5d1a3380-c84c-11eb-9d5e-230bc9e6383f.png)

**Comment by TingluoHuang** [comment]
@thread-liu I have asked internally to check your issue.
Just want to double-check do you have other repositories under the same org that uses all the runners?
You can only run 20 concurrency jobs base on your payment plan (free).

**Comment by thread-liu** [comment]
@TingluoHuang Yes, but another repository is the same phenomenon. Stuck on “starting your workflow run”.  

https://github.com/RT-Thread/packages/runs/2770057733?check_suite_focus=true
https://github.com/RT-Thread/rt-thread/actions/runs/916905930

Both of these repositories are stuck here. 

This repository is a team and should be able to run 60 concurrency jobs.

**Comment by thread-liu** [comment]
@TingluoHuang Thanks for your help! All the jobs have been done.
