### ISSUE TITLE
Job if condition is not evaluated properly

### ISSUE THREAD

**Issue by akphi** [actions/runner#1145]
**Describe the bug**
I want to skip a job when the PR title matches a string, but it seems like my condition expression is not accurately evaluated.

**To Reproduce**
1. Go to https://github.com/finos/legend-studio/pull/246.
2. The job: https://github.com/finos/legend-studio/pull/246/checks?check_run_id=2798751296 is still being executed, despite the fact that in the workflow file, I have the condition

```yml
  if: ${{ github.context.payload.pull_request.title != 'New Release' }} # avoid running this in `New Release` PR
```
Code: https://github.com/finos/legend-studio/blob/b0d00ee02b9d0114943dd8ed298f524e4c4b99cf/.github/workflows/check-plugin-compatibility.yml#L12-L16

**Expected behavior**
I would expect when the PR title is `New Release` the job is skipped.

## Runner Version and Platform
Runner version: 2.278.0

OS of the machine running the runner?
`ubuntu-latest` - Ubuntu 20.04.2 LTS

## What's not working?
As you can see, the job `Plugin Compatibility Check / Run Plugin Compatibility Checks` run

![image](https://user-images.githubusercontent.com/13574879/121615461-edb06980-ca2e-11eb-9fef-0beab5230b2a.png)

**Comment by TingluoHuang** [comment]
Base on the trace:
```
Evaluate condition on phase 'check-plugin-compatibility': Evaluating: (success() && (github.context.payload.pull_request.title != 'New Release'))
Expanded: (true && (null != 'New Release'))
Result: true
```

I think it should be 
```
if: ${{ github.event.pull_request.title != 'New Release' }}
```

**Comment by akphi** [comment]
@TingluoHuang oh I see, I have tried to print out the context in the very first step using [github-script](RelationalPropertyMapping) and I saw my title there. So probably outside the scope of a job, the title of the event is only available like what you just how I suppose.

I will give this a try right now. Thank you so much!

**Comment by akphi** [comment]
@TingluoHuang it works! I'll close the issue now. Again, thank you so much!
