### ISSUE TITLE
Downloading a workflow artifact fails on some machines: ECONNREFUSED

### ISSUE THREAD

**Issue by abelikt** [actions/runner#1153]
**Describe the bug**

Hi, we are having an issue with downloading artifacts from a workflow that seems to be machine dependent.
It works fine on one machine but not on the other, where a GitHub server blocks access.
Both of them are Raspberry Pi’s that are configured as self-hosted runners in GitHub.

Error message:

`"Error: request to ... failed, reason: connect ECONNREFUSED 140.82.121.6:443"`

Tested Actions:
- dawidd6/action-download-artifact@v2
- benday-inc/download-latest-artifact@main

The Raspberry Pi where downloading fails is hosted here in a datacenter: https://www.mythic-beasts.com/order/rpi/

**To Reproduce**

Steps to reproduce:

https://github.com/abelikt/thin-edge.io/blob/continuous_integration/.github/workflows/download_artifact.yml

- Fails: hosted_offsite_dawidd6
- Passes: hosted_onsite_dawidd6
- Fails: hosted-offsite-benday-inc

Executed workflow:

https://github.com/abelikt/thin-edge.io/runs/2817470783?check_suite_focus=true

**Actual behavior**

Access fails when trying to download a workflow artifact: `"failed, reason: connect ECONNREFUSED 140.82.121.6:443"
`
**Expected behavior**

Action (e.g. dawidd6/action-download-artifact@v2) downloads workflow artifact sucessfully.

## Runner Version and Platform

Raspberry Pi OS / Debian 10.8

## What's not working?
See above

## Job Log Output

```
Run dawidd6/action-download-artifact@v2
==> Workflow: build-workflow.yml
==> Repo: abelikt/thin-edge.io
==> Conclusion: success
==> Branch: continuous_integration
Error: request to https://api.github.com/repos/abelikt/thin-edge.io/actions/workflows/build-workflow.yml/runs?branch=continuous_integration&event=&status=success failed, reason: connect ECONNREFUSED 140.82.121.6:443
```

## Runner and Worker's Diagnostic Logs

Mabe related:

Runner_* : 

```
[[2021-06-14 07:15:04Z WARN GitHubActionsService] Authentication failed with status code 401.
WWW-Authenticate: Bearer
Strict-Transport-Security: max-age=2592000
X-TFS-ProcessId: .........
ActivityId: ......
X-TFS-Session: ...
X-VSS-E2EID: ....
X-VSS-SenderDeploymentId: ......
X-TFS-ServiceError: The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27+is+not+authorized+to+access+this+resource.
X-VSS-S2STargetService: 0000005A-0000-8888-8000-000000000000/visualstudio.com
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: C8C..........Ref B: LON04ED........ Ref C: 2021-06-14T07:15:03Z
Date: Mon, 14 Jun 2021 07:15:03 GMT
```

Worker_* : 
`[2021-06-14 07:15:59Z WARN JobExtension] Ignore exception during read process environment variables: Access to the path '/proc/30170/environ' is denied.`

## Additional Info

I also raised tickes here, without success yet:

- https://github.com/actions/virtual-environments/issues/3569
- https://github.community/t/downloading-a-workflow-artifact-is-refused-some-machines/183951
- https://github.com/dawidd6/action-download-artifact/issues/78
- GitHub Support

**Comment by TingluoHuang** [comment]
@abelikt why do you think this is a runner issue? the runner only in charge of starting the action you use and wait for it to finish.

Seems like an Action issue or your environment issue.

Do you mind trying to run `curl https://api.github.com/repos/abelikt/thin-edge.io/actions/workflows/build-workflow.yml/runs?branch=continuous_integration&event=&status=success` in your workflow before the download artifact action?

**Comment by abelikt** [comment]
Hi @TingluoHuang thanks for the reply. I'm not sure if this is a runner issue. I got directed here after creating this issue here: https://github.com/actions/virtual-environments/issues/3569. I also raised a ticket at the action (https://github.com/dawidd6/action-download-artifact/issues/78). Howerver, since to independent actions are failing with the same error, I believe its maybe something else, like a firewall or a network filter.

I added the curl command into the workflow as well (good idea!).
The outcome is here:
https://github.com/abelikt/thin-edge.io/runs/2873466864?check_suite_focus=true
Also here curling works, but the action fails that seems even more odd to me.

**Comment by abelikt** [comment]
Hi @TingluoHuang, do you maybe have an idea what is going wrong?
If not please at least remove the awaiting customer response tag I responded already three weeks ago.

**Comment by TingluoHuang** [comment]
maybe try `curl -v -sS -D - "https://api.github.com/repos/abelikt/thin-edge.io/actions/workflows/build-workflow.yml/runs?branch=continuous_integration&event=&status=success" -o null` to dump more info from curl.

You can also fork the actions you are using and adding more tracing into the HTTP request call.

My gut feeling is you have a proxy server or firewall somewhere inside your network that blocks the request from node.js

**Comment by abelikt** [comment]
Hi, I sent that info to the hoster and asked for confirmation.
Turns out, that the devices there have only IPv6 connection an IPv4 is only used internally.
Workaround for name resolution: Append ipv6 addresses (resolved elsewhere) and queried hostnames to /etc/hosts.
Thanks for the support, I'll close the ticket.
