### ISSUE TITLE
Allow action version selection using tag + hash

### ISSUE THREAD

**Issue by loosebazooka** [actions/runner#1155]
**Describe the enhancement**
Allow runner to accept github actions specified by their **tag** and **commit hash**. This allows the human readable form to be pinned to the version it was intended -- allowing tools like depandabot to suggest upgrades and also allowing a machine to verify that there was no tampering of the tag (since they are technically mutable).

**Code Snippet**
Perhaps a format like `uses: <action>@version#sha`, but I don't really care what it looks like as long as I can specify both
```
- uses: actions/checkout@v2.3.4#5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
```

**Additional information**
none

**Comment by TingluoHuang** [comment]
Can you just use a comment in your workflow file?

```yaml
- uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #version: v2.3.4
```

**Comment by npalm** [comment]
I also prefer the usages of the hash, adding a comment is quick fix. But once using it together with dependabot it does work anymore. Dependabot will update hash to the version. Would help a lot if we can really lock and update actions.

**Comment by loosebazooka** [comment]
I didn't realize that dependabot can update based on hashes (but it wont update the comment). I think this can be closed?
