### ISSUE TITLE
No logging output and job 'stalling' when command line tool asks for user input.

### ISSUE THREAD

**Issue by Danack** [actions/runner#1159]
**Describe the bug**
I setup a CI step that apparently asks for user input. The job doesn't show any output until it is cancelled and it looks like the job 'stalls' on the command that asks for input.

I had added quite a few lines of debug to that action, to try to narrow down what was causing the problem, and I think it may be related to the step `sudo pecl install package.xml || true` asking for user input. 

**To Reproduce**
Trigger a github actions build for this repo - https://github.com/Imagick/imagick/tree/package_testing

Go to the page that shows the action output e.g. https://github.com/Imagick/imagick/runs/2840186682?check_suite_focus=true

Until the job is cancelled, there won't be any output for the step "Perform pecl install".

**Expected behavior**
The output to be shown up until the point where the job 'stalls' waiting for user input.

## Runner Version and Platform
Ubuntu 20.04 Version: 20210606.1

Ubuntu 20.04

## What's not working?

There is no output for the "Perform pecl install" step until the job is cancelled. In the log, the steps after "sudo pecl install package.xml || true" aren't run.

## Job Log Output
![github_action_stalling](https://user-images.githubusercontent.com/1505719/122241189-43b36000-ceba-11eb-99f5-ddbd663e280a.PNG)

## Runner and Worker's Diagnostic Logs
Sorry - I'm not sure where I should be getting these from. There are logs available from the run of https://github.com/Imagick/imagick/runs/2840186682?check_suite_focus=true but apparently that link expires quickly.

But the entries in that log don't seem to match what I'm seeing on the actions log output page. The log file doesn't show any delay in running the command.

Taking an extract from the log - the first two lines are the last expected output from the command "sudo pecl install package.xml || true". After them, I would expect the action runner to move onto the next step in the job.

```
2021-06-16T14:29:50.8613894Z configuration option "php_ini" is not set to php.ini location
2021-06-16T14:29:50.8614927Z You should add "extension=imagick.so" to php.ini
2021-06-16T14:40:47.5095508Z ##[error]The operation was canceled.
```

**Comment by TingluoHuang** [comment]
@Danack the live console log is a fire and forget, you have to watch the build to see any incoming lines.
Ex:
your build started, print out `hello world`, sleep for 10 minutes, and print out `goodbye`

If you landed on the page during the 10 minutes sleep windows, you won't see any output until `goodbye` gets to print.

looks like `sudo pecl install package.xml || true` is hanging, maybe try `sudo pecl -v 3 install package.xml`

**Comment by Danack** [comment]
okay thanks. that explains what I was seeing. I think there might be an issue running that command, but I'll get more info first.
