### ISSUE TITLE
Support for 32-bit Linux

### ISSUE THREAD

**Issue by fjelliott** [actions/runner#1181]
The title says it all. I completely agree with people who say that 64-bit is superior to 32-bit, 64-bit systems can compile 32-bit code, etc. However, some of us just can't wave a wand and convert all of our systems to 64-bit. And compiling .rpm packages for 32-bit systems on a 64-bit system is...tricky. In any case, not allowing a 32-bit system to host an actions runner seems like a fairly easy problem to solve (for the same reasons as above).

I'd also ask for support for 32-bit Windows, but in light of recent news that **might** be rather pointless.

**Comment by TingluoHuang** [comment]
the runner is built on top of dotnet core which doesn't support x86 Linux, so I don't think we can easily achieve this.

I would suggest either try using `qemu` docker container to emulate `x86` environment or SSH into an `x86` environment during the job.

https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md#linux

**Comment by mirabilos** [comment]
32-bit ARM would do…

**Comment by mirabilos** [comment]
https://github.com/marketplace/actions/setup-alpine-linux-environment can do that… it can even do i586 (it calls it `arch: x86`) without qemu, just in a chroot, so that suffices for me right now
