### ISSUE TITLE
add architecture to runner context

### ISSUE THREAD

**Issue by jeremyd2019** [actions/runner#1185]
There is support for `${{ runner.os }}` but it would also be helpful to be able to query `${{ runner.architecture }}` (or maybe `${{ runner.arch }}` for less typing).  I think that's relevant to this repo, as I see 
https://github.com/actions/runner/blob/09821e2169bf0c173658654fc59af2e7ed30c3bd/src/Runner.Worker/JobRunner.cs#L107 appears to set `${{ runner.os }}`.

**Comment by TingluoHuang** [comment]
@fhammerl you want to take this?

**Comment by Awan27091987** [comment]
> There is support for `${{ runner.os }}` but it would also be helpful to be able to query `${{ runner.architecture }}` (or maybe `${{ runner.arch }}` for less typing). I think that's relevant to this repo, as I see
> 
> https://github.com/actions/runner/blob/09821e2169bf0c173658654fc59af2e7ed30c3bd/src/Runner.Worker/JobRunner.cs#L107
> 
> appears to set `${{ runner.os }}`.

I m owner
Help
