### ISSUE TITLE
Runner executing PRE_BUILD_COMMAND after build

### ISSUE THREAD

**Issue by danwritecode** [actions/runner#1200]
**Describe the bug**
Hey all, I have a pre build command that is successfully executing before build. However AFTER the build is complete, I receive the below error:
```
Executing pre-build command...
/tmp/BuildScriptGenerator/1a99291bc4a545debea5078de55439d0/build.sh: line 119: ./scripts/setup-chromium.sh: No such file or directory
```
This exact script executes earlier in the build process. I'm unsure why it is being triggered again and I'm also unsure how there are no path issues pre-build but there are post-build. 

**To Reproduce**
1. Add a PRE_BUILD_COMMAND that is a file path
```
env:
  PRE_BUILD_COMMAND: './scripts/setup-chromium.sh'
```

**Expected behavior**
I expect the pre build command to be executed pre build only. 

## Runner Version and Platform
Running in the hosted environment using "ubuntu-latest". 

## What's not working?
Error message included above but also screenshot below...
![image](https://user-images.githubusercontent.com/41842184/125289517-50767880-e2ed-11eb-8819-ec0adeb19399.png)

## Job Log Output
Screenshot above

**Comment by danwritecode** [comment]
FYI, I removed the file path and placed the build commands directly into the yaml file and the build completed with no issues.

**Comment by danwritecode** [comment]
For added context, here is a gist of the build file. 

https://gist.github.com/danwritecode/e9be2b87316c7f51e7baccb7f70e023c

**Comment by TingluoHuang** [comment]
You can't use a relative path like this since you have no control on what is the working directory when the action is running.
Try `$GITHUB_WORKSPACE/scripts/setup-chromium.sh` which should help it find the right script.

**Comment by nikola-jokic** [comment]
Hi everyone,

Since the answer is provided and with no customer response, I assume that this issue has been resolved, and I will close it now. Please, feel free to re-open it or file another issue if you experience any problems 😊
