### ISSUE TITLE
Fail to install on Debian Bullseye

### ISSUE THREAD

**Issue by zhsj** [actions/runner#1204]
**Describe the bug**

Debian Bullseye/11 only has `libicu67`, however `installdependencies.sh` can only install `libicu66`.

https://packages.debian.org/bullseye/libicu67

**To Reproduce**

Install runner on Debian Bullseye.

**Expected behavior**

runner can run on Debian Bullseye

## Runner Version and Platform
Version of your runner?

2.278.0

OS of the machine running the runner? OSX/Windows/Linux/...

Debian Bullseye

## Job Log Output

```
Libicu's dependencies is missing for Dotnet Core 3.0
Execute sudo ./bin/installdependencies.sh to install any missing Dotnet Core 3.0 dependencies.
```

**Comment by TingluoHuang** [comment]
We might need to update `installdependencies.sh` to looking for `libicu67`
@fhammerl do you want to fix this?
