### ISSUE TITLE
Windows runner report  LLVM ERROR: IO failure on output stream: no space on device

### ISSUE THREAD

**Issue by liya2017** [actions/runner#1209]
**Describe the bug**
Windows runner report  LLVM ERROR: IO failure on output stream: no space on device

**To Reproduce**
run cargo test with caches

**Expected behavior**
cargo run test successful

## Runner Version and Platform
windows-latest

## What's not working?
Windows runner report  LLVM ERROR: IO failure on output stream: no space on device

How can I clean the runner space？

**Comment by TingluoHuang** [comment]
I think the error explains itslef `no space on device`, you are running out of disk space for the runner machine.
I don't think there is anything the runner can do in this case, I am going to close this for now.
Please reopen if need more help. 😄
