### ISSUE TITLE
pipefail not set by default

### ISSUE THREAD

**Issue by mitchcurtis** [actions/runner#1212]
**Describe the bug**
The "Install Qt" step on https://github.com/mitchcurtis/slate/runs/3075356483 should fail due to install-qt.sh not existing, but it doesn't, even though pipefail is apparently set by default:

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions says:

> You can use the following status check functions as expressions in if conditionals. A default status check of success() is applied unless you include one of these functions.

The docs for success say:

> Returns true when none of the previous steps have failed or been canceled.

As suggested in https://github.community/t/future-steps-still-running-after-previous-ones-failed/191164, adding `set -o pipefail` before running the scripts made the rest fail:

https://github.com/mitchcurtis/slate/runs/3115384417

**To Reproduce**
See https://github.com/mitchcurtis/slate/blob/326d6d4d707ed049e79b3995c968873ceecdfe86/.github/workflows/packages.yml.

**Expected behavior**
Pipe failures should cause future steps to fail.

## Runner Version and Platform
Current runner version: '2.278.0'

Operating System
  Ubuntu
  18.04.5
  LTS

**Comment by nikola-jokic** [comment]
Hey @mitchcurtis,

Per the documentation, the default shell should be like you stated, but the current version of a runner does not follow it. We created a [PR](https://github.com/actions/runner/pull/1717) that should fix this problem but can introduce problems for the previous pipelines, so it might take a while until it is shipped. As a suggestion, you might try adding: `shell: bash`. Please, notify me if that solves your problem

**Comment by nikola-jokic** [comment]
Hi @mitchcurtis,

Please refer to [this](https://github.com/actions/runner/issues/353#issuecomment-1067227665) comment. This is working as intended, and we filed an issue to update the docs related to this problem.
