### ISSUE TITLE
Allow using an alternative location for logs

### ISSUE THREAD

**Issue by rviscuso** [actions/runner#1219]
Runner logs go to `_diag` but our company has a standard location for logs under a different directory.

This request is that an option be provided in `config.sh` so another log location can be used.

**Comment by fhammerl** [comment]
Hi 👋 @rviscuso , as a workaround, can you use symlink or junction points? Or is it company policy _not_ to have logs anywhere else but your standard location?

**Comment by rviscuso** [comment]
Thanks @fhammerl , I will give it a try and report back here.

**Comment by rviscuso** [comment]
If I create a symlink pointing _diag somewhere else I get an error when the runner is started:
`The file '/home/prod/actions-runner/_diag' already exists.`

Any ideas?

**Comment by fhammerl** [comment]
That's odd. I ran `ln -s /home/ferenc/dev/runner/_layout/_diag /home/ferenc/_diag`, and the runner runs and writes in the `_diag` folder without issues, `/home/ferenc/_diag` showing the logs too.


I tried deleting `_layout/_diag`, when I start the runner again it creates the folder without any problem.

What's a step by step repro to produce your error? Is it broken like that on a new machine as well?

**Comment by rviscuso** [comment]
Looks like there was something wrong with the link, I tried again with a different test environment and it worked fine, the logs are getting written to my desired location.

So I can confirm the symlink approach is a suitable workaround. 👍 

Thanks for your help!
