### ISSUE TITLE
Actions reports no GitHub hosted runners available in matrix build

### ISSUE THREAD

**Issue by johnae** [actions/runner#1230]
**Describe the bug**
For a day or two now all builds are failing (stalling really) with actions claiming there are no hosted runners available.

**To Reproduce**
1. Basically just run a matrix build in https://github.com/johnae/world

**Expected behavior**
All builds eventually run.

## Runner Version and Platform
Github hosted runners.

OS of the machine running the runner? Linux

## What's not working?
Several jobs just stall claiming no available runners. Since many jobs run to completion though, this seems odd. Especially odd that it happens every single build.

**Comment by jneira** [comment]
We are hitting this issue in https://github.com/haskell/haskell-language-server/actions since 17 hours. So 17 hours without any chance to merge code in our repo. Are there some workaround o way to check the status of runners availability?

**Comment by jneira** [comment]
I've cancelled and reran selectively stalled jobs to see they start to work again

**Comment by johnae** [comment]
This seems to have resolved itself.
