### ISSUE TITLE
is there any way to access github runner(not self hosted)?

### ISSUE THREAD

**Issue by sriedjx** [actions/runner#1236]
I need a requirement which i should able to access current github runner  and troubleshoot issue which related to my application.

* when i run any build on github runner it should run via tmux session which i should able to access that tmux session and see current running build process/logs

**Comment by TingluoHuang** [comment]
You can use actions from marketplace to do this, like: https://github.com/marketplace/actions/debugging-with-tmate

**Comment by sriedjx** [comment]
That looks good, but if any task is running on the runner. how do I see lively on runner by connecting tmux session.

**Comment by TingluoHuang** [comment]
@sriedjx you might want to ask in https://github.com/actions/virtual-environments, they manage all the hosted VM used by Actions.

Or maybe https://github.community/c/code-to-cloud/github-actions/41 since this enhancement is primary for the entire Actions system, not the runner itself.

**Comment by sriedjx** [comment]
Thanks! raised query
https://github.com/actions/virtual-environments/issues/3849
