### ISSUE TITLE
[self-hosted] Linux systemd with user ("sudo ./svc.sh install user") - Deal with environment user variables

### ISSUE THREAD

**Issue by axel3rd** [actions/runner#1242]
### Context

When you are using Self-Hosted Linux runner with many tools customization, you could have too deal with user environment variables.

These user variables could be (often) defined in `.~/profile` like:

```
# Variables about technology usages, like repo endpoints, Jdks, ...
export GOPROXY=http://repository.company.com/go
export GOPRIVATE=github.company.com

# Tools home definition and available on PATH
export AWESOME_TOOLS_HOME=/opt/awesome-tools
export PATH=$AWESOME_TOOLS_HOME/bin:$PATH
```

### Problem

When `./config.sh` is executed, the generated `.env` file contains only a subset of existing environment variables:

https://github.com/actions/runner/blob/3851acd0cf40875351d84d7659d70ce0b0809389/src/Misc/layoutroot/env.sh#L3-L15

**Note**: The `.path` deals correctly with any customization due to be effective on environment when configuration is executed  (`export PATH=$AWESOME_TOOLS_HOME/bin:$PATH` in `~/.profile`, or `$HOME/bin` inclusion of  third-part scripts in this location).

### Describe the enhancement

When runner is started:

```bash
sudo ./svc.sh start
```

Take into account the environment variables of user which has been used in:

```bash
sudo ./svc.sh install user
```

### Possible orientations

1. Out of scope feature
2. Service template update
3. .env improvment

#### Out of scope feature

Hey man, this is not the role of *actions-runner* to deal with user environment variables. Even if it could be executed with a user (ex: `ubuntu`) to reduce potential impact of some modification on system, all context usage should be defined at root level (e.g: move your variables in `/etc/environment`, having all in `~/.profile` is perhaps simple but not sustainable.

**NB**: Perhaps a mention about that in ~[Customizing the self-hosted runner service](https://docs.github.com/enterprise-server/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service#customizing-the-self-hosted-runner-service) could be relevant.

#### Service template update

A trick for taking environment user could be update :

https://github.com/actions/runner/blob/3851acd0cf40875351d84d7659d70ce0b0809389/src/Misc/layoutbin/actions.runner.service.template#L6

in:

```
ExecStart=/bin/sh -l -c 'exec "$@"' _ {{RunnerRoot}}/runsvc.sh
```

But this is perhaps not a beautiful solution, and I didn't evaluate impacts if executed with *root* user.

An other way with service could be used `EnvironmentFile=` configuration ; but when this file contain `PATH` modifications, it could have impact with `svc.sh` *path* definition:

```bash
sudo ./svc.sh start
Aug 04 10:47:52 ip-10-199-16-20 runsvc.sh[17869]: /home/ubuntu/actions-runner/runsvc.sh: line 9: cat: command not found
Aug 04 10:47:52 ip-10-199-16-20 runsvc.sh[17867]: .path=
```

Logic workflow result: 
```
Download action repository 'actions/checkout@v2'
Error: tar: command not found
```

#### .env improvment

Another way could be create an `.env` file correctly with all environment user variables when `./config.sh` is executed.

I'm agree that it is not take "all" variables from `env` command ; perhaps just the one defined in `~/.profile` or `~/.bashrc`.

Manually as workaround, it is (requires `export` prefix usage):

```bash
cat ~/.profile | grep export | grep -v PATH | sed 's/export //g' | sed 's/"//g' | envsubst >> ~/actions-runner/.env
```

**Comment by shakefu** [comment]
As far as I can tell the default bash invocation `bash --noprofile --norcfile ...` will ignore all the usual profile configuration (e.g. including `/etc/environment` and `~/.profile`).

We've had to resort to a really dirty hack to make this work and set our custom environment.

**Comment by ethomson** [comment]
Hi @axel3rd - we do in fact support [a `.env` file](https://github.com/actions/runner/blob/main/src/Runner.Listener/Program.cs#L130) for setting the environment.  We wouldn't want to use `/etc/profile` or `~/.profile` since a general user may be running the listener and need a clean environment (this is something I do during development & testing, I run the runner with my own account and need a clean environment for job executions).

I hope this satisfies you - I'm going to close this issue, and I appreciate your thoughtful query.  Thanks again!

**Comment by fengyuentau** [comment]
Hello @ethomson , I have a similar issue to this one but on macOS. I also need to set some environment variables for my jobs but I do not want to put all those paths in the yaml files. Setting environment variables for GitHub Actions on macOS is quite tricky and none of the methods I googled worked. Is there any documents on how to set environments using the `.env` file and `env.sh`?

**Comment by fengyuentau** [comment]
For anyone who wants to set environment variables and use them in GitHub Actions workflows, what you need to do is:
1. Set environment variables in your host. For example, `export GIT_CACHE=/path/to/git_cache`.
2. Add your custom environment variables into `varCheckList` in `env.sh`.
3. Re-run `config.sh`. In case you have configured a runner previously, you need to remove it and re-run `config.sh` to have environment variables set for your runners.

I wonder if GitHub Actions devs can add a section in the document to introduce this feature and add a command in `config.sh` to reload environment without re-registering runners.
