### ISSUE TITLE
Function `hashFiles` seems to be OS-dependent

### ISSUE THREAD

**Issue by kriegaex** [actions/runner#1246]
I noticed that on Windows the value of `${{ hashFiles('**/pom.xml') }}` always seems to be different than on Linux/MacOS, where it is identical. Is this due to the fact that Git checks out files with CRLF line endings in Windows rather than LF on unixoid systems?

The related comment https://github.com/actions/cache/issues/102#issuecomment-555092357 and https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#hashfiles did not answer this question, unfortunately.

If I am right, is there a way to do some dynamic `dos2unix` kind of transformation on the set of input files before calculating the hash?

**Comment by ethomson** [comment]
> I noticed that on Windows the value of `${{ hashFiles('**/pom.xml') }}` always seems to be different than on Linux/MacOS, where it is identical. Is this due to the fact that Git checks out files with CRLF line endings in Windows rather than LF on unixoid systems?

That's very likely.  If you have git configured to check files out with CRLF, then those would be different on Windows than on macOS or Linux.  (And if you have not explicitly configured git, then it will default to CRLF on Windows.)

> If I am right, is there a way to do some dynamic dos2unix kind of transformation on the set of input files before calculating the hash?

No - we really do need the hashes to match the content.  If we were to dos2unix the files before we were hashing them, then we would sometimes put files in with CRLF and sometimes with LF.  They'd probably flap back and forth.  (Sort of like what happens when you have git's line ending settings wrong on Windows.)

I'd encourage you to either cache your Windows and Unix files separately or turn `* -text` on in your repository's `.gitattributes`.

We're not going to make any changes to `hashFiles` here - it really just needs to respect your line ending configuration in your repository - so I'm going to close this issue.

**Comment by kriegaex** [comment]
@ethomson, exactly that is the problem! By default, POMs will be different on Windows vs. other platforms, simply because the line endings are different. The suggestion to have two caches in that case does not make any sense to me, because the binaries in the Maven repo would be identical and the POMs only linefeed-wise different. That is bloat and a waste of the cache. I worked around that for now by forcing Unix line endings on Windows, too, because there was not reaction for 3+ months here. This is ugly. Caching should work correctly for well-known text file types on different platforms. At least there should be an option, like I suggested. There is not need to make it the default. But it is a bvalid use case. I do not understand why this issue was closed so unceremoniously, even though such an option would mean a substantial improvement for millions of users. Multi-platform builds are normal, and everyone is wasting GitHub resources using duplicate caches where it really does not make any sense.

**Comment by ethomson** [comment]
Right, like I said, you have two choices.  You can either use two caches, which is a bloat, _or_ you can have standardized line endings across your project.  Every tool that reads a POM on Windows can read LF line endings, including `notepad.exe`.  I would encourage you to stop normalizing line endings on those files.

A third option is that you don't _have_ to use `hashFiles` as the key.  You can make the key an arbitrary string of your choosing.  But hashing a file needs to be deterministic.

**Comment by kriegaex** [comment]
> To be more concrete, this is what I suggest adding this to your `.gitattributes`
> 
> `pom.xml -text`
> 
> Now it will be checked out with LF line endings across all platforms, meaning that it will hash identically across all platforms.

That is incorrect, sorry. This Git attribute controls how Git stores the file internally, not how it is checked out. The default (which is a good one) is still to check out text files with the default line ending for the corresponding platform. I had to override that sensible default in my GitHub action, just so as to satisfy the runner's hash method.

**Comment by ethomson** [comment]
> That is incorrect, sorry. This Git attribute controls how Git stores the file internally, not how it is checked out.

CR/LF handling affects both directions.

**Comment by kriegaex** [comment]
No, sorry, that is plain wrong. Please read the documentation:
https://git-scm.com/docs/gitattributes#_text

> `text`
>
> This attribute enables and controls end-of-line normalization. When a text file is normalized, its line endings are converted to LF **in the repository.**
>
> To control what line ending style is used in the **working directory,** use the `eol` attribute for a single file and the `core.eol` configuration variable for all text files. Note that setting `core.autocrlf` to `true` or `input` overrides `core.eol` (see the definitions of those options in `git-config` [1]).

So it is significantly more complicated than that.

**Comment by ethomson** [comment]
Yes, line ending handling in git is complicated indeed.

What I'm saying is that if you have `core.autocrlf` on today, or you have `* text=auto` on today, which you do if you're getting CRLF on Windows and LF on non-Windows, then you have LF in your repository.  By changing that to `* -text`, that means that the file will be written to disk identically as it exists in the repository, so it will have LF line endings.

But when you're _doing_ line ending conversion (with, for example, `text=auto`), then `eol` has a default of your system line endings anyway.  It's not required.

**Comment by kriegaex** [comment]
What I want, in a nutshell, is not to fiddle with Git settings für GitHub Actions, but be able to influence how hash values for selected text files are being calculated. More precisely, of course the hash algorithm is what it is, I simply wish to be able to say: "For this group of files, please dos2unix them before using the hash method." The reason is that for the build itself, I do not need any conversion. I even wish to check if the build works normally with default line endings. Only for the GH-specific cache, I want to make sure that caching is done the way I wish to without unnecessary redundancy.
