### ISSUE TITLE
Failed to resolve action download info

### ISSUE THREAD

**Issue by aggarg** [actions/runner#1247]
**Describe the bug**
We have suddenly started to see this failure:

```
Getting action download info
Failed to resolve action download info. Error: Bad request - freertos/ci-cd-github-actions@main is not allowed to be used in aws/aws-iot-device-sdk-embedded-C. Actions in this workflow must be: within a repository that belongs to your Enterprise account or match the following: FreeRTOS/CI-CD-Github-Actions/*, actions/*.
Retrying in 13.373 seconds
Failed to resolve action download info. Error: Bad request - freertos/ci-cd-github-actions@main is not allowed to be used in aws/aws-iot-device-sdk-embedded-C. Actions in this workflow must be: within a repository that belongs to your Enterprise account or match the following: FreeRTOS/CI-CD-Github-Actions/*, actions/*.
Retrying in 22.118 seconds
Error: Bad request - freertos/ci-cd-github-actions@main is not allowed to be used in aws/aws-iot-device-sdk-embedded-C. Actions in this workflow must be: within a repository that belongs to your Enterprise account or match the following: FreeRTOS/CI-CD-Github-Actions/*, actions/*.
```

**To Reproduce**
1. See https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1686/checks?check_run_id=3244517700

**Expected behavior**
No error as was happening till about an hour ago.

## Runner Version and Platform
Version of your runner?
'2.279.0'

OS of the machine running the runner? OSX/Windows/Linux/...
  Ubuntu 18.04.5 LTS

## What's not working?
```
Failed to resolve action download info. Error: Bad request - freertos/ci-cd-github-actions@main is not allowed to be used in aws/aws-iot-device-sdk-embedded-C. Actions in this workflow must be: within a repository that belongs to your Enterprise account or match the following: FreeRTOS/CI-CD-Github-Actions/*, actions/*.
```

## Job Log Output
NA

## Runner and Worker's Diagnostic Logs
NA

**Comment by thboop** [comment]
Hey @aggarg , can you please try again?

**Comment by aggarg** [comment]
Hi @thboop, Yes, it works now - https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1686/checks

Thanks. What was the issue?

**Comment by thboop** [comment]
We rolled out a feature flag that didn't seem to have the correct behavior, I've turned it off while we investigate more! Going to close this for now, feel free to reopen if you see it.
