### ISSUE TITLE
Support Windows Dump File Collection

### ISSUE THREAD

**Issue by nibanks** [actions/runner#1248]
**Describe the enhancement**
For Windows kernel/driver development in Azure Pipelines we need the ability to collect any kernel dumps that get generated from kernel crashes during testing. Assuming the environment is properly configured to collect kernel dumps at a well known location, work must be done on the runner side of things to collect (probably compress/zip) the dump, upload the file and then continue execution if the yaml specifies so.

**Additional information**
See https://github.com/actions/virtual-environments/issues/3858 for more details/discussion.

**Comment by ethomson** [comment]
Hi @nibanks - it looks like you found the [appropriate Azure Pipelines repo to report this in](https://github.com/microsoft/azure-pipelines-agent/issues/3540).  I don't think that this is work that we'll want to do within Actions, so I'm going to close this issue and it looks like the Azure Pipelines team can help support you.  Thanks!
