### ISSUE TITLE
Error while running ./bin/Runner.Listener

### ISSUE THREAD

**Issue by rohankm** [actions/runner#1252]
Hi,
when i run the ./config to ./run i get the following error... I debugged into the code and saw that Runner.Listener is causing this it has permissions to run still I get this issue.. Im running on my VPS with Cpanel installed 

Error:
An error occurred: Permission to read the directory contents is required for '/home/USER/actions-runner' and each directory up the hierarchy. Access to the path '/home' is denied.

**Comment by ruvceskistefan** [comment]
Hi @rohankm,
Are you still seeing this issue? I just want to confirm if this is still an issue for you?

**Comment by ruvceskistefan** [comment]
Hi @rohankm,
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
