### ISSUE TITLE
Moving a runner to a different group causes the remove command to partially fail

### ISSUE THREAD

**Issue by mikedalton** [actions/runner#1254]
**Describe the bug**

If a self-hosted runner is moved to a different runner group from the one in which it was provisioned (either the default group, or another group via the `--runnergroup` flag), attempting to run the `./config.sh remove` command generated by the GitHub Actions UI results in the following output:

```
# Runner removal

Does not exist. Skipping Removing runner from the server
√ Removed .credentials
√ Removed .runner
```

**To Reproduce**
1. On GitHub Enterprise Cloud or GitHub Enterprise Server, go to the Actions Runner configuration page
2. Follow the steps to add a self-hosted runner to the default group
3. Create a new runner group
4. Stop the runner client
5. In the web UI, move the runner to the newly-created runner group
6. Start the runner client, and then stop it again
7. In the web UI, confirm that the runner is listed under the new group
8. Use the `./config.sh remove --token <token>` command generated by the web UI to attempt to remove the runner
9. Observe the warning message above, indicating that the local config files have been removed but that the runner has not been removed from the server
10. Refresh the web UI and note that the runner is still listed

**Expected behavior**
Running the remove command should remove the runner from the server regardless of what group it was previously in or is currently in.

## Runner Version and Platform
Version of your runner?

2.278.0

OS of the machine running the runner? OSX/Windows/Linux/...

Ubuntu 20.04

GitHub Platform?

GitHub Enterprise Cloud and GitHub Enterprise Server 3.1.5 (possibly other versions as well)

## What's not working?
Explained above

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A

**Comment by TingluoHuang** [comment]
The runner should make another query to find its current runner group and continue the removal, we should fix this. @fhammerl FYI.
