### ISSUE TITLE
Containerized github runner crashes on Mac M1

### ISSUE THREAD

**Issue by bmbferreira** [actions/runner#1255]
**Describe the bug**
I'm trying to run a containerized github runner on Mac M1 but it is crashing on my mac M1 with the following error: 

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
./config.sh: line 81:   125 Segmentation fault      ./bin/Runner.Listener configure "$@"
```

**To Reproduce**
1. Install the github runner on a docker file, for example like this:
```Dockerfile
FROM ubuntu:20.04
ENV GITHUB_PAT=""
ENV GITHUB_OWNER=""
ENV GITHUB_REPOSITORY=""
ENV RUNNER_WORKDIR="_work"
ENV POOL_LABELS=""
ENV IMAGE_LABELS="ubuntu-20.04"
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Madrid
ENV GITHUB_RUNNER_VERSION=2.280.1

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
    && apt-get install -y \
        curl \
        sudo \
        git \
        jq \
        iputils-ping \
        rsync \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -m github \
    && usermod -aG sudo github \
    && echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER github
WORKDIR /home/github

RUN curl -Ls https://github.com/actions/runner/releases/download/v${GITHUB_RUNNER_VERSION}/actions-runner-linux-x64-${GITHUB_RUNNER_VERSION}.tar.gz | tar xz \
    && sudo ./bin/installdependencies.sh

COPY --chown=github:github entrypoint.sh runsvc.sh start.sh before_start.sh ./
RUN chmod u+x ./entrypoint.sh ./runsvc.sh ./before_start.sh ./start.sh

# Following is needed as all these nice wrapper scripts provided by GitHub do ignore '--once' directive
RUN sed -i "s/'run', '--startuptype', 'service'/'run', '--startuptype', 'service', '--once'/" ./bin/RunnerService.js

ENTRYPOINT ["/home/github/entrypoint.sh"]
```

2. Run this command on a Mac M1 machine `docker buildx build -t my-github-runner:test --platform linux/amd64 -f Dockerfile .` to build it

3. Run `docker run -it --platform linux/amd64 -e GITHUB_PAT=<some-access-token> -e POOL_LABELS=local -e GITHUB_REPOSITORY=<some-repo-name> my-github-runner:test` also on a Mac M1 machine to start the runner.

4. Do a Pull Request on a repository with a github action that triggers the previosly started runner.

**Expected behavior**

The runner would work on Mac M1 by specifying the correct platform, as described [here](https://earthly.dev/blog/using-apple-silicon-m1-as-a-cloud-engineer-two-months-in/).

## Runner Version and Platform
GitHub Runner 2.280.1
Docker version 20.10.7, build f0df350

OS of the machine running the runner? 
Mac OS Big Sur 11.4 M1 arm64

## What's not working?
```

# Authentication

qemu: uncaught target signal 11 (Segmentation fault) - core dumped
./config.sh: line 81:  1693 Segmentation fault      ./bin/Runner.Listener configure "$@"
```

**Comment by ruvceskistefan** [comment]
Hi @bmbferreira,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally.
Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
