### ISSUE TITLE
Canceled and Cancelled are both used in actions/runner

### ISSUE THREAD

**Issue by jsoref** [actions/runner#1261]
**Describe the bug**
Canceled and Cancelled are both used in actions/runner

**To Reproduce**
1. Trigger a cancellable run (e.g. an `on:push` that has a cancel option)
2. Trigger a cancel for it (e.g. by pushing a second time)
3. Visit the run https://github.com/jsoref/dhall-validator-action/actions/runs/1125145505
4. See the output

**Expected behavior**
Only use a single version of `canceled` / `cancelled` throughout a single view, and preferably a single platform. Ideally this platform would be `github`, but for the sake of argument, let's imagine that the platform is `actions/runner`.

Given that `cancelled()` is the form exposed via actions/runner, I think it has to win, unless you want to add support for `canceled()` as well, which just seems more painful: https://github.com/actions/runner/blob/be9632302ceef50bfb36ea998cea9c94c75e5d4d/docs/adrs/0274-step-outcome-and-conclusion.md#L21

## Runner Version and Platform
Version of your runner?
Current runner version: '2.280.1'

OS of the machine running the runner? OSX/Windows/Linux/...
  Ubuntu
  20.04.2
  LTS

## What's not working?
Please include error messages and screenshots.

> Status: Cancelled
> Canceling since a higher priority waiting request for 'spelling-refs/heads/test' exists
> A task was canceled.
![image](https://user-images.githubusercontent.com/2119212/129266971-b55b3377-d0c8-4ce2-8a3d-ff885823522f.png)

## Instances

https://github.com/actions/runner/search?q=canceled
28 code results in actions/runner or view all results on GitHub

https://github.com/actions/runner/search?q=cancelled
34 code results in actions/runner or view all results on GitHub

## Doc instances

On the bright side, the docs web site is using a stemming search or something and yields identical results either way, so it would be harmless to fix everything to use a single spelling:

https://docs.github.com/en?query=cancelled
[Developers / GitHub Marketplace / Marketplace API usage Handling plan cancellations: Step 1. Cancellation event](https://docs.github.com/en/developers/github-marketplace/using-the-github-marketplace-api-in-your-app/handling-plan-cancellations#step-1-cancellation-event)
> If a customer chooses to cancel a GitHub Marketplace order, GitHub sends a marketplace_purchase webhook with the action *cancelled* to your app when the *cancellation* takes effect. If the customer cancels during a free trial, your app will receive the event immediately. When a customer cancels a paid plan, the *cancellation* will occur at the end of the customer's billing cycle.

[GitHub Actions / Managing workflow runs
Canceling a workflow: Steps GitHub takes to cancel a workflow run](https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run)
> When *canceling* workflow run, you may be running other software that uses resources that are related to the workflow run. To help you free up resources related to the workflow run, it may help to understand the steps GitHub performs to cancel a workflow run. To cancel the workflow run, the server re-evaluates if conditions for all currently running jobs. If the condition evaluates to true, the job will not get *canceled*. For example, the condition if: always() would evaluate to true and the job continues to run. When there is no condition, that is the equivalent of the condition if: success(), which only runs if the previous step finished successfully. For jobs that need to be *canceled*, the server sends a *cancellation* message to all the runner machines with jobs that need to be *canceled*. For jobs that continue to run, the server re-evaluates if conditions for the unfinished steps. If the condition evaluates to true, the step continues to run. For steps that need to be *canceled*, the runner machine sends SIGINT/Ctrl-C to the step's entry process (node for javascript action, docker for container action, and bash/cmd/pwd when using run in a step). If the process doesn't exit within 7500 ms, the runner will send SIGTERM/Ctrl-Break to the process, then wait for 2500 ms for the process to exit. If the process is still running, the runner kills the process tree. After the 5 minutes *cancellation* timeout period, the server will force terminate all jobs and steps that don't finish running or fail to complete the *cancellation* process.

[Billing and payments / GitHub Marketplace apps
Canceling a GitHub Marketplace app: Canceling an app for your organization](https://docs.github.com/en/billing/managing-billing-for-github-marketplace-apps/canceling-a-github-marketplace-app#canceling-an-app-for-your-organization)
> Tip: If an app requires organization-level access, then only an organization owner can purchase, install, or cancel the app, and manage app billing for the organization. If the app doesn't require organization-level access, then a repository administrator can install and uninstall the app. In the top right corner of GitHub, click your profile photo, then click Your organizations. Next to the organization, click Settings. In your organization's Settings sidebar, click Billing & plans. Next to the app you want to cancel, use the Edit drop-down and click Cancel plan. In the dialog box, click OK.

[Billing and payments / GitHub Marketplace apps
Canceling a GitHub Marketplace app: Canceling an app for your personal account](https://docs.github.com/en/billing/managing-billing-for-github-marketplace-apps/canceling-a-github-marketplace-app#canceling-an-app-for-your-personal-account)
> In the upper-right corner of any page, click your profile photo, then click Settings. In your user settings sidebar, click Billing & plans. Next to the app you want to cancel, use the Edit drop-down and click Cancel plan. In the dialog box, click OK.

**Comment by ruvceskistefan** [comment]
Since it has been found that resolving this issue requires major protocol changes, the problem of inconsistency has been resolved only at the message level, while enums, class names, etc. remained the same. Therefore, I am regrettably closing this issue.
