### ISSUE TITLE
job stuck on "starting job..." but actually finished the job

### ISSUE THREAD

**Issue by saurik** [actions/runner#1263]
https://github.com/OrchidTechnologies/orchid/runs/3244623783

The build-lnx-bld job in this run has a queued status and shows "Starting job...", but then when you wait a second it manages to load what seems like the log of a completed build. I would probably just re-run it, but I figured you should see it in this state ;P.

**Comment by saurik** [comment]
I have just had another -- very different -- action end up in this behavior.

https://github.com/OrchidTechnologies/orchid/runs/3340142674

**Comment by nikola-jokic** [comment]
Hi @saurik,

Is this issue persistent on your workflow, or is this happening occasionally?

**Comment by saurik** [comment]
@nikola-jokic It was happening occasionally (and not even that often). FWIW, I haven't noticed it happening in long enough now that maybe you've since fixed the problem?

**Comment by nikola-jokic** [comment]
I believe so. I am glad that it is not bothering you anymore 😊
