### ISSUE TITLE
Configuring self-hosted runner: Registering the runner to the parent organization fails using $GITHUB_TOKEN

### ISSUE THREAD

**Issue by sidewaiise** [actions/runner#1264]
**Describe the bug**
I'm building a new runner image using a github action workflow.

The Dockerfile installs binaries, and then installs the github agent at the end. Using the ${{ github.token }} as the --token param for config.sh:

```
./config.sh --url https://github.com/my-org --token $GITHUB_TOKEN --labels label1,label2 --name my-label-$(($(date +%s%N)/1000000))
```

**To Reproduce**
1. Install/extract the actions runner v2.280.1 as a docker layer
2. Add the ./configure.sh line as described in the bug above to Dockerfile
3. Create a github workflow using `docker/build-push-action` to build the Dockerfile

**Expected behavior**
The configure step for self-hosted runner registration should work

## Runner Version and Platform
v2.280.1

OS of the machine running the runner? ubuntu-latest

## What's not working?
Registering a self-hosted runner with the parent organization in a github workflow, using a repository owned by the org.

## Job Log Output
Output is exactly as follows:

```
#12 0.222 # Authentication
#12 0.222 
#12 0.465 Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
#12 0.466 {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
#12 0.480 Response status code does not indicate success: 404 (Not Found).
#12 ERROR: process "/bin/sh -c cd actions-runner     && ./config.sh --url https://github.com/my-org --token \"${GITHUB_TOKEN}\" --labels arm64,Linux--name my-runner-$(($(date +%s%N)/1000000))" did not complete successfully: exit code: 1
------
 > [8/8] RUN cd actions-runner     && ./config.sh --url https://github.com/my-org --token "***" --labels arm64,Linux--name my-runner-$(($(date +%s%N)/1000000)):
#12 0.222 |                                                                              |
#12 0.222 |                       Self-hosted runner registration                        |
#12 0.222 |                                                                              |
#12 0.222 --------------------------------------------------------------------------------
#12 0.222 
#12 0.222 # Authentication
#12 0.222 
#12 0.465 Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
#12 0.466 {"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
#12 0.480 Response status code does not indicate success: 404 (Not Found).
------
Dockerfile:29
```

**Comment by sidewaiise** [comment]
On further experimentation, this seems to be a token permission issue. The runner is trying to add it's self to the organization using the `GITHUB_TOKEN`. I am guessing the solution will be to set up an org-level or user-level token with correct scopes. 

Is there any way to grant permissions to the workflow for adding a runner to the parent org?

**Comment by TingluoHuang** [comment]
The `GITHUB_TOKEN` is scope to the repository that the workflow is in, it can't be grant permission that is not scoped to the particular repository.

**Comment by thboop** [comment]
You may want to consider using a pat with the appropriate permissions and setting it as a secret, but there is no way to grant the permissions to a repo scoped github_token currently.

I'm going to close out this issue as it isn't a runner bug. Feel free to file [feedback for github actions](https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions#contacting-support) if this feature would be helpful for you.

**Comment by mountainash** [comment]
🗒️ For people coming here from following the "copy & paste" GitHub repo/org Settings instructions for setting-up a self hosted runner and see this "Not Found" error... it's most likely due to the TOKEN in the instructions having **expired**. Fix: refresh the page to get a new token, copy and paste the command and run again.

Request to project Maintainers... maybe the error message could be more specific to help diagnose the error.
