### ISSUE TITLE
Ability to change labels without config.sh remove

### ISSUE THREAD

**Issue by NorseGaud** [actions/runner#1267]
I have a need for my code to change the labels of an already active runner. I see that I'd have to unregister it (config.sh remove) but my code doesn't have the token necessary, only access to the runner's folder.

I'd love to be able to `./config.sh --replace --labels custom-label-1` and then only have that label for the runner.

**Comment by ethomson** [comment]
Hi @NorseGaud - thanks for the suggestion.  We shipped this recently, here's the [announcement](https://github.blog/changelog/2021-11-25-api-support-for-managing-labels-of-actions-self-hosted-runners/).  I'm going to close this issue.

Thanks again!
