### ISSUE TITLE
Composite Actions: Does not respect if: `failure()` condition

### ISSUE THREAD

**Issue by thboop** [actions/runner#1271]
**Describe the bug**
From the documentation of [failure()](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#failure), the function will return `true` if any previous step of a job fails. The step where this function is used should be executed.

It appears that using composite actions (with the `uses` key) does not work when  `if: ${{ failure() }}` is used in the step. When the action is a JavaScript Action, the action is executed as expected.  If a `run` key is used in that step instead, that works as expected as well.

**To Reproduce**
- Create a step that fails
- Add a later composite step that runs on `if: failure()`
- Notice the composite steps do not execute as expected.

**Expected behavior**
Composite steps should execute.

**Comment by jeroen** [comment]
Thanks for picking this up. Here is a live reprex: https://github.com/test-gha-bug/test-action

**Comment by jeroen** [comment]
Thanks for the fix. How do I know when this fix is in production so we can resume our operations (we use GitHub enterprise cloud)?

**Comment by thboop** [comment]
This will rollout with runner 2.280.3, trying to get that to all users as soon as we safely can.

**Comment by thboop** [comment]
@jeroen this should be fixed now, all runners should auto update to `2.280.3`! Thanks again for the report and repro, I'm going to close this issue out but if you are still having issues let me know and we can reopen.
