### ISSUE TITLE
Composite Actions Feedback: Show more information about what steps are being run

### ISSUE THREAD

**Issue by thboop** [actions/runner#1272]
**Describe the bug**
Currently in composite actions and composite run steps, we print the basic information about the step being run to the debug logs. As composite actions is leveraged more for reuse, we should print this information to the standard log, allowing users to see what steps are being run without enabling debug logging. For example, we should be able to see this information when running actions, and the equivalent run step information
![image](https://user-images.githubusercontent.com/52323235/129919063-52275ca6-106b-4bb6-b02a-60f46b34c0dc.png)

**Comment by crazy-max** [comment]
Maybe it's a bit out of scope for this issue but I think UI for composite actions could be improved with a tree view:

![image](https://user-images.githubusercontent.com/1951866/129961939-c37d0e04-ab90-415e-9990-8aa510babb4e.png)
> https://twitter.com/crazyws/status/1293525542810025991
