### ISSUE TITLE
Unrecognized command-line input arguments

### ISSUE THREAD

**Issue by sarantoo** [actions/runner#1281]
**Describe the bug**
Encounter unrecognized command-line input arguments when run as a service. Only happened in one of the two servers. 

**To Reproduce**
Can't reproduce on machine other than one of our servers.

**Expected behavior**
Service running correctly

## Runner Version and Platform
v2.280.3 Ubuntu 20.04.2 LTS x64

OS of the machine running the runner? Linux

## What's not working?
Service not running

## Job Log Output
```
ส.ค. 20 20:28:14 title runsvc.sh[28811]: .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
ส.ค. 20 20:28:14 title runsvc.sh[28814]: Starting Runner listener with startup type: service
ส.ค. 20 20:28:14 title runsvc.sh[28814]: Started listener process, pid: 28821
ส.ค. 20 20:28:14 title runsvc.sh[28814]: Started running service
ส.ค. 20 20:28:14 title runsvc.sh[28814]: Unrecognized command-line input arguments: 'n, startuptype, rvice'. For usage refer to: .\config.cmd --help or ./config.sh --help
```

**Comment by fhammerl** [comment]
Hi @sarantoo, thanks for reporting this issue.

Could you tell me exactly how you're invoking the runner? Do you run `runsvc.sh` directly? If yes, with what arguments?

> `runsvc.sh[28814]: Unrecognized command-line input arguments: 'n, startuptype, rvice'.`

`runsvc.sh` calls `bin/RunnerService.js`. On line 30, `RunnerService.js` starts the listener by starting a child process with the following arguments: 

```listener = childProcess.spawn(listenerExePath, ['run', '--startuptype', 'service'], { env: process.env });```

It seems the first two characters of these arguments got truncated. 

Can you reproduce the issue when running `./externals/node12/bin/node ./bin/RunnerService.js` in the runner directory?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
