### ISSUE TITLE
Action fails even when step passes

### ISSUE THREAD

**Issue by igbanam** [actions/runner#1285]
**Describe the bug**
A checkstyle step, with psalm, returns cleanly; but the output breaks GH Actions.

Output of the error is in [this gist](https://gist.github.com/igbanam/aab35f9c5270d069280739ae8c1314d0)

**To Reproduce**
1. Run a psalm checkstyle step as in the gist above locally
2. Ensure the output is without errors
3. Run the same step in actions

**Expected behavior**
A passing step.

## Runner Version and Platform
Version of your runner? — the one on Github actions

OS of the machine running the runner? OSX/Windows/Linux/... — Ubuntu

## What's not working?
Please include error messages and screenshots. — [output from job](https://gist.github.com/igbanam/479b2e68078e54ae78f090235618e60f)

## Job Log Output
[output from job](https://gist.github.com/igbanam/479b2e68078e54ae78f090235618e60f)

## Runner and Worker's Diagnostic Logs
This is on GH actions

p.s: I didn't know where best to raise this issue. So if this is not a runner issue, please help redirect to the proper team 🙏🏾

**Comment by TingluoHuang** [comment]
@igbanam the output you share shows some error I think, will this cause the step to fail?
```
Error with Psalm Shepherd:
Error: Extra content at the end of the document on line 4, column 1
```

The runner simply invokes the actions/script/tool you specified in YAML and uses the return code to decide whether to fail the step.

**Comment by igbanam** [comment]
This is the same step running locally. Notice it exits with a non-zero status

```
╭─   ~/projects/nobody-group/vaia on   blog ····························  base  3.0.0 at  02:02:45 PM ─╮
╰─❯ vendor/bin/psalm --shepherd --stats --output-format=checkstyle                                           ─╯
Scanning files...
Analyzing files...


<?xml version="1.0" encoding="UTF-8"?>
<checkstyle>
</checkstyle>

╭─   ~/projects/nobody-group/vaia on   blog ····························  base  3.0.0 at  02:05:57 PM ─╮
╰─❯ echo $?                                                                                                  ─╯
0
```

**Comment by igbanam** [comment]
Any ideas? — this is still an issue. Should I be asking somewhere else?

**Comment by igbanam** [comment]
Took a deeper dive into this, and it's not a runner bug

I find [Shepherd](https://github.com/psalm/shepherd) does not work for private repositories.
