### ISSUE TITLE
Runners crashing frequently with CrashLoopBackOff

### ISSUE THREAD

**Issue by azizzoaib786** [actions/runner#1290]
**Describe the bug**

Suddenly GitHub Runners containers starts to crash with below errors and keeps in CrashLoopBackOff.

And when we update the runner with the latest release it gets fixed but after sometime it starts throwing same error.

```mv: inter-device move failed: './externalstmp/node12' to './externals/node12'; unable to remove target: Directory not empty```
```mv: inter-device move failed: './externalstmp/node12_alpine' to './externals/node12_alpine'; unable to remove target: Directory not empty```

## Runner Version and Platform
Kubernetes Cluster 1.20
GitHub Runners version 2.280.3

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

**Comment by nikola-jokic** [comment]
Hi @azizzoaib786,

Are you experiencing this issue again? Please, look at this [issue](https://github.com/actions/runner/issues/1464), which might help with your problem. If not, could you please provide how did you set up your runner so we can try to reproduce this behaviour?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
