### ISSUE TITLE
Add --replace to create-latest-svc script

### ISSUE THREAD

**Issue by totogtr** [actions/runner#1292]
**Describe the enhancement**
It would be nice to add the option to use the --replace argument to the config.sh script when called by create-latest-svc.sh ; that way when automating the deployment it would replace existing runner with the same name when they couldn't have been removed dynamically

**Code Snippet**
https://github.com/actions/runner/blob/62d568674c790ba9176cbf1f7411f70a531e918e/scripts/create-latest-svc.sh#L168

`sudo -E -u ${svc_user} ./config.sh --unattended --url $runner_url --token $RUNNER_TOKEN --replace --name $runner_name --labels $labels
`

**Additional information**

**Comment by ethomson** [comment]
Thanks for the suggestion @totogtr - I'll put this on our backlog for future work.
