### ISSUE TITLE
Self-hosted runner doesn't create a work folder, e.g. "_work".

### ISSUE THREAD

**Issue by arslan** [actions/runner#1293]
**Describe the bug**
Self-hosted runner doesn't create a work folder, e.g. `_work`. The configuration script exits normally. Runner service works.

**To Reproduce**
1. Go to `actions-runner` folder.
2. Run `./config.sh --url URL--token TOKEN`.
3. Exits normally.
4. `_work` folder is missing.

**Expected behavior**
Work folder `_work` should appear in the 'actions-runner' directory.

## Runner Version and Platform
Version of your runner?
`actions-runner-linux-x64-2.280.3`

OS of the machine running the runner?
`Ubuntu 20.04 (Linux 5.4.0-81-generic)`

## Runner and Worker's Diagnostic Logs
Attached.
[Log.log](https://github.com/actions/runner/files/7070794/Log.log)

**Comment by TingluoHuang** [comment]
The runner should create the folder when it start running jobs.

**Comment by arslan** [comment]
@TingluoHuang Yep, fixed it. Thanks for the clarification.
