### ISSUE TITLE
Update node12 to a more current version

### ISSUE THREAD

**Issue by dan-mba** [actions/runner#1294]
**Describe the enhancement**
The current version of node12 in the actions runner is 12.13.1 which was released in Nov-2019.

The current node12 version is 12.22.5.

By using a more recent node12 version it will improve the ability to use native packages that take advantage of later versions of the 
[Node-API](https://nodejs.org/api/n-api.html#n_api_node_api_version_matrix)

The package I am trying to use requires node > 12.17.0

Issue #772 would fix my problem, but the timeline for that seems to be after October.

I was hoping it might be possible to upgrade node12 until support for node14 or 16 is available.

**Comment by peaceiris** [comment]
The first issue is #772

**Comment by dan-mba** [comment]
This issue is addressed by #1439 and released in version 2.285.0
