### ISSUE TITLE
Console colours hard to read on non-dark themes 

### ISSUE THREAD

**Issue by ilg-ul** [actions/runner#1295]
**Describe the bug**

The light gray text used in the runner configuration console is hard to read on non-dark themes.

**To Reproduce**

1. - set the console to have a white background
2. - run the `./config.sh` script

**Expected behavior**

Be able to read the console output.

## Runner Version and Platform

Version of your runner? 

- 2.280.3

OS of the machine running the runner? OSX/Windows/Linux/...

- macOS with light theme.

## What's not working?

The light gray text on white background is almost unreadable

![Screenshot 2021-08-29 at 15 50 05](https://user-images.githubusercontent.com/362732/131253238-16ddfcbd-e666-469e-adf0-29cdd1e0d41f.png)

## Job Log Output

- not relevant

## Runner and Worker's Diagnostic Logs

- not relevant

## Suggestion

Give up setting any colours and leave the default console settings.

**Comment by fhammerl** [comment]
Hi @ilg-ul , thank you for reporting this issue. We always welcome contributions from the community. I've marked this one as `good-first-issue`. 

For anyone who'd like to pick it up, I recommend you take a look at the [Terminal](https://github.com/actions/runner/blob/main/src/Runner.Common/Terminal.cs) class.
Consider replacing `ConsoleColor.White` with the default color `Console.ResetColor()`

**Comment by ilg-ul** [comment]
I added (#1319) as a simple pull request to replace `Console.ForegroundColor = ConsoleColor.White` with `Console.ResetColor()`.

Since I'm not used to the project workflow, please let me know if there is anything else I should do.

**Comment by ilg-ul** [comment]
Fixed by the pull request.

**Comment by ilg-ul** [comment]
I confirm that in v2.282.1 the text is now readable in a white terminal.

Thank you, Ferenc @fhammerl for your support.
