### ISSUE TITLE
Detect hosted virtual environment in PowerShell

### ISSUE THREAD

**Issue by freddydk** [actions/runner#1297]
I am running a PowerShell script in a github actions workflow.
Is there any way I can detect whether I am running on self-hosted agents or in the hosted virtual environments?

**Comment by fhammerl** [comment]
Hi @freddydk,

Unfortunately the answer is no, we don't support that. We generally use labels like `self-hosted` to make sure jobs get to the right runners, rather than deciding on a specific behaviour during job execution.

**Comment by freddydk** [comment]
Ok, thanks
