### ISSUE TITLE
Remove runner from GitHub without uninstall - or make uninstall faster

### ISSUE THREAD

**Issue by dgteixeira** [actions/runner#1308]
**Allow to remove runner from GitHub without uninstall - or make uninstall faster (<30s)**

When running shutdown script on preemptible GCP hosts, it never removes the runner from GitHub because it takes longer than the preemptible shutdown periods (30s).

When I execute the shutdown script with `svc.sh uninstall` it always takes over 32s to execute, which is longer than the VM host has to shutdown (example of timer below).

It should be possible to remove the runner from GitHub without having to uninstall the service, or at least, to be faster to do it.

EDIT/UPDATE: 
I'm running a MIG on GCP based on a preemptible node pool, where every machine gets destroyed, so when it goes down, I don't need to keep runner on it. Whenever a new host comes back up, it will execute the startup script and install the runner brand new (with the --replace flag).

**Code Snippet**

When running the remove without  `svc.sh uninstall`:
```
RUNNER_ALLOW_RUNASROOT=1 ./config.sh remove --token $REMOVE_TOKEN --unattended

# Runner removal

Removing service
Failed: Removing service
Unconfigure service first
```

When executing the script:

```
# time ./remove_script.sh
Removing runner vm-gh-runner-4zjb @ 

Generating a removal token...
Attempting to remove Runner from GitHub
/runner /

(...)
# Runner removal
√ Runner removed successfully
√ Removed .credentials
√ Removed .runner

real    0m32.833s
user    0m1.220s
sys     0m0.079s
```

**Additional information**
GCP Documentation for shutdown periods: https://cloud.google.com/compute/docs/shutdownscript

**Comment by dgteixeira** [comment]
I've tried between 10-15 times, and all the timers were between 32-35 seconds. Just shy of the 30 seconds in preemptible hosts in GCP.

**Comment by TingluoHuang** [comment]
I think `svc.sh uninstall` just run a bunch of `systemctl` commands to remove the `systemd` service, so we might not able to speed that up.

do you need to un-configure the runner when the machine goes down and is destroyed?
If you are re-using the same runner name, pass `--replace` during runner configure will overwrite the existing runner.

We have a feature that allows a runner to only take one job and unconfig itself at the end of the job coming soon https://github.com/actions/runner/pull/660, feels like you can leverage that in the future.

In the meantime, you can just skip unconfigure the runner, the only problem it will cause is you will have a bunch of offline runners shows up in the web UI. (The service will delete those after 30 days of inactive.)

**Comment by dgteixeira** [comment]
Hey @TingluoHuang , thanks for the fast response! 😁

I already use the `--replace` flag when starting the runner on startup, however the host names are not being repeated, so when it goes down it pops up a new one with a different ID. Nonetheless, I think I will also try this possible route, thanks 😊.

These hosts are supposed to be online for the majority of the time (with the preemptible-risk, of course), and are supposed to get multiple jobs, each.

Without running the shutdown script, they appear as offline in the UI, which I prefer not to have, since It will be used for an entire GH organization and a bunch of "offline" for 30 days (and preemptible hosts go down every day), would be very eye-sore.

What I'm currently attempting, with apparent success, is force signal-kill the `runsvc.sh` process and it's child processes and then `svc.sh uninstall`.

Will let you know how this turns out.

**Comment by TingluoHuang** [comment]
Other option:
First: `sudo ./svc.sh stop`  (this only stop the service, and not going remove and reload daemon, might save sometime.)

- Use REST API to remove it from the server
   - https://docs.github.com/en/rest/reference/actions#list-runner-applications-for-a-repository
   - https://docs.github.com/en/rest/reference/actions#delete-a-self-hosted-runner-from-a-repository

Or

- If you are really, really, really, really sure that you don't need the machine, the runner service configuration.
   - you can just `rm .service` which removes the service record from the runner's view, so the runner think it's not configured as a service.
   - then: `RUNNER_ALLOW_RUNASROOT=1 ./config.sh remove --token $REMOVE_TOKEN --unattended`

**Comment by dgteixeira** [comment]
Hey @TingluoHuang, both of those seem like a good idea as well.

However, since my objective is to have multiple services running in a single host (to make sure a VM can get multiple jobs), what do you believe it's the best option?

**Comment by thboop** [comment]
Fixed by https://github.com/actions/runner/pull/1580

Uninstall should be much much quicker, we no longer wait 30 seconds

**Comment by dgteixeira** [comment]
@TingluoHuang and @thboop thanks a lot for your help!
I will definitely try this out and get back to you!
