### ISSUE TITLE
Debug output for stop-commands prints "{actionCommand.Data}"

### ISSUE THREAD

**Issue by rcowsill** [actions/runner#1318]
**Describe the bug**
The debug output for the `stop-commands` workflow command prints the following to the log:

```text
##[debug]Paused processing commands until '##[{actionCommand.Data}]' is received
```

See:

https://github.com/actions/runner/blob/4e95d0d6ad46e454749cc5d69a7072df34a8e12f/src/Runner.Worker/ActionCommandManager.cs#L114

It looks like this was intended to use string interpolation to print the resume token's value, as was done here:

https://github.com/actions/runner/blob/4e95d0d6ad46e454749cc5d69a7072df34a8e12f/src/Runner.Worker/ActionCommandManager.cs#L103

**To Reproduce**
1. Create a workflow that uses the `stop-commands` workflow command
2. Set the `ACTIONS_STEP_DEBUG` secret to `true`
3. Run the workflow and look at the debug output for the `stop-commands` workflow command

**Expected behavior**
Debug output shows the actual value of the resume token, rather than the literal string "{actionCommand.Data}"

## Runner Version and Platform
GitHub hosted runner, version 2.281.1

## What's not working?
Debug output for the `stop-commands` workflow command prints "{actionCommand.Data}" instead of the resume token's value.

## Job Log Output
```text
::stop-commands::[TOKEN VALUE REDACTED]
##[debug]Paused processing commands until '##[{actionCommand.Data}]' is received
```

**Comment by fhammerl** [comment]
Hi @rcowsill, thank you for reporting this issue! Your assessment is correct. 

However, we're working on some changes and will be slightly reworking this part of the code. 

Thanks again for reporting. I'll be closing this issue for now.
