### ISSUE TITLE
unknown character streamed to action resulting in exit code 1

### ISSUE THREAD

**Issue by lostmygithubaccount** [actions/runner#1322]
**Describe the bug**

(not entirely sure this is the correct place for this issue, any guidance appreciated)

It seems like the string " ]0;" stops GitHub Actions in their tracks. This was discovered when streaming logs from a job in a GitHub Action which contains a line with the string of characters. ~~Further testing reveals if a GitHub Action workflow definition contains the string, it will not run.~~

**To Reproduce**

This is more important for our real scenario of streaming Azure Machine Learning job logs to a GitHub Action. It turns out, the following line (or similar) is often present in the logs:

\>\>\>   ]0;root@d04320ac5c1741f4968f2cbd650a23bc000000: /mnt/batch/tasks/shared/LS_root/jobs/main-master/91786579b49b44dbb8bebae7130e65d4/65ea4322-dafe-4a25-8d6a-eafc1e148769/wdroot@d04320ac5c1741f4968f2cbd650a23bc000000:/mnt/batch/tasks/shared/LS_root/jobs/

When this line is streamed to the Action, or redirected into a log.txt, the action fails. You can see an example of that happening here: https://github.com/Azure/azureml-examples/runs/3569228945 

**Expected behavior**
1. Actions don't fail with exit code 1 when this line is streamed to logs
~~2. Actions can be submitted containing the strings of characters~~ 

## Runner Version and Platform
Version of your runner? not sure...using regular stuff

OS of the machine running the runner? Linux (ubuntu-latest)

## What's not working?

You can see my confusion on this PR: https://github.com/Azure/azureml-examples/pull/741 

When the character is streamed to logs it exits and fails the action: 

![image](https://user-images.githubusercontent.com/54814569/132897539-2a33a819-daa6-4c1a-9e27-46275958538f.png)

## Job Log Output
See screenshot above.

## Runner and Worker's Diagnostic Logs
n/a

**Comment by lostmygithubaccount** [comment]
echo " ]0;"

**Comment by lostmygithubaccount** [comment]
>>>   ]0;root@d04320ac5c1741f4968f2cbd650a23bc000000: /mnt/batch/tasks/shared/LS_root/jobs/main-master/91786579b49b44dbb8bebae7130e65d4/65ea4322-dafe-4a25-8d6a-eafc1e148769/wdroot@d04320ac5c1741f4968f2cbd650a23bc000000:/mnt/batch/tasks/shared/LS_root/jobs/

**Comment by lostmygithubaccount** [comment]
apologies for the spam - it does specifically seem to be whatever this character is: 

**Comment by thboop** [comment]
Hey @lostmygithubaccount ,

That character appears to be the unicode replacement character. I've copied your suggested workflow and was able to verify that the action ran for me, I didn't see any issues with the steps and the job completed successfully.
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: test
      run: |
        echo "here"
        echo " �]0;"
        echo "there"
        echo "done!"
```

Are you able to reproduce this in a simple public repo that you can link to this issue?

**Comment by lostmygithubaccount** [comment]
thanks @thboop for investigating. completely wrong about not being able to run an action with that character in it - can confirm that is also working fine for me.

however, when that line in our logs are streamed to a GitHub Action, it is still failing with exit code 1. you can see that in the screenshot above, also here: 

![image](https://user-images.githubusercontent.com/54814569/132900423-de0a1b62-270b-4121-88e0-393ea57cce93.png)

Instead of printing the line: 

![image](https://user-images.githubusercontent.com/54814569/132900636-7d17158e-4117-4a8b-82b1-236ce0451d23.png)

which can be seen in the Azure Machine Learning logs, it exits in the action workflow.

That run is here: https://github.com/Azure/azureml-examples/runs/3569228945 

That is slightly harder to reproduce, since it is using Azure Machine Learning to submit a job then stream the logs from that job in the action.

it was first noticed with this action: https://github.com/Azure/azureml-examples/actions/workflows/cli-jobs-train-fastai-pets-job.yml

**Comment by ruvceskistefan** [comment]
Hi @lostmygithubaccount,
I see that the issue in which you referred this issue is closed, so I'm wondering if the problem still exists or can I close this issue as well?

**Comment by lostmygithubaccount** [comment]
Hi @ruvceskistefan,

I assume the problem still exists, but I was able to work around it for the purposes of our examples repository. I think it's fine to close this issue, I'll go ahead and close it. Thanks!
