### ISSUE TITLE
Can I install github self-hosted runner on another computer and use it in my own computer

### ISSUE THREAD

**Issue by RachelGanonNew** [actions/runner#1324]
Hi!
I'm working at a big orginization as a software developer.
I was asked to create a ci-cd pipeline.
We are using github self hosted runner,
Because secrity rules of the orginizatin, not all employees have admin/owner permissions.
My question is - Can my team lead(with admin permission) create the github self hosted runner from her computer and i'll write the pipeline in my own computer?
And pleas - I don't see any github action of .net framework, i'll highly apperciate if you'll create one!
thanks all.

**Comment by muhammetasan** [comment]
Yes you can write your workflow yml file under .github/workflows as explained in https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions 

Your team lead create and start github runner on her computer. As long as your yml file is inside target branch of any pull_request or push, the runner which is running on your leads computer can run the workflow that you write.

**Comment by RachelGanonNew** [comment]
Thank you
