### ISSUE TITLE
support one shot run

### ISSUE THREAD

**Issue by moba1** [actions/runner#1333]
Self hosted runner does not support one shot run.

> one shot run mean that self hosted program make only one job run & exit after job finished

If supported one shot run, self hosted runner will be able to secure idempotency by shutdowning instance in services as AWS AutoScalingGroup.

**Comment by apr-1985** [comment]
See the `--ephemeral` option added yesterday in https://github.com/actions/runner/pull/660

**Comment by moba1** [comment]
Thanks your information.
