### ISSUE TITLE
Runner Configuration Manager referencing deprecated API

### ISSUE THREAD

**Issue by chaychoong** [actions/runner#1336]
https://github.com/actions/runner/blob/7ffd9af644647114f924a8b6cede3aaf5d79b71f/src/Runner.Listener/Configuration/ConfigurationManager.cs#L616-L620

**Comment by TingluoHuang** [comment]
@chaychoong where do you see these apis are deprecated?

**Comment by thboop** [comment]
Going to close this out since we haven't heard from you in a while, but if there's anything else we can do to help here please let us know @chaychoong
