### ISSUE TITLE
`--ephemeral` doesnt "un-configure the runner" as help says

### ISSUE THREAD

**Issue by apr-1985** [actions/runner#1337]
**Describe the bug**
The help for `--ephemeral` says:
```
Configure the runner to only take one job and then let the service un-configure the runner after the job finishes
```

However, after the job has run you end up in a state where you cannot easily reconfigure the runner, but still need a remove token to run `config.sh remove`.

Ideally I was looking to have the process:
1. register runner with `unattended` and `ephemeral`
2. run `./run.sh`
3. Let actions give it a job
4. Let ephemeral unregister the runner
5. delete the _work folder
6. Go back to step 1

This would give a nice quick loop to being able to clean up runners without a full terminate/spin up new.  While ensuring that only a single job ran before it was cleaned.
It would also improve security by not needing to give the runners Org Admin level tokens to get registration/cleanup tokens as I could inject a registration token into the runner use that with the above flow for an hour, then terminate it and spin up new.

However because `ephemeral` isn't unconfiguring correctly I would need to remove the whole Actions folder and start by un-taring the runner code again which is waste time.

**To Reproduce**
1. configure runner `./config.sh --url https://github.com/MY_ORG --token $TOKEN --ephemeral --unattended  --runnergroup runner_group_1;`
2. let GH give it a job and let ephemeral remove it from GH
3. Delete `_work` and try to run again.  Get the error:
`Failed to create a session. The runner registration has been deleted from the server, please re-configure.` 
4. Run the configure command from step 1 and you get 
`Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.`

5. Try to run `./config.sh remove` and get 
`Enter runner remove token:`

**Expected behavior**
I would expect that `--ephemeral` do a full `config.sh remove` so that the runner could be setup again quickly and easily.

## Runner Version and Platform
Version of your runner? [ 2.282.0](https://github.com/actions/runner/releases/tag/v2.282.0

Amazon Linux 2

**Comment by pje** [comment]
Hey @apr-1985, thanks for the bug report! 

Looks like `--ephemeral` is correctly de-registering the runner on the service, but it's _not_ deleting the local registration files. In particular `.runner` looks like this: 

```
{
  "agentId": 26,
  "agentName": "gimbal",
  "poolId": 1,
  "poolName": "Default",
  "ephemeral": true,
  "serverUrl": "https://pipelines.actions.githubusercontent.com/v7i2sNCfhEkwIUUGKQRpoleBFdvSmAkwWSrytxXQBg9uTAUoKm",
  "gitHubUrl": "https://github.com/pje/sid",
  "workFolder": "_work"
}
```

**Comment by apr-1985** [comment]
Ace thanks for the reply. 
My workaround was deleting the whole actions folder and unzipping again. So just doing one file seems nicer as a workaround. 

Thanks again
