### ISSUE TITLE
Don't Remove Support to `--once`

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [actions/runner#1339]
On PR #660, the `--ephemeral` flag was introduced with the intent of replacing the `--once` flag. But by deregistering and reregistering the runner every time, the number of API calls to GitHub dramatically increases, and eventually, the rate limit is exceeded.

I experienced before the `--ephemeral` even existed. Every time I wanted to run a job, I was registering a new runner, starting it with `--once`, and deregistering it after the job was completed. Quickly the maximum number of API calls allowed to a GitHub App was exceeded. I solve the problem by keeping the credentials of runners and only registering and deregistering runners on upscale and downscale operations.

With the removal of the `--once` flag, it will not possible to run a single job on the runner without removing it when the job is completed. Effectively limiting the number of ephemeral runners that can be used within an hour. Using a PAT, you are limited to 2500 jobs run by a self-hosted runner, assuming the only operations you do are runner registration and deregistration. With a GitHub App, in the best case, you will be able to run 6250 jobs, or 7500 with GitHub Enterprise Cloud, which is not reasonable for a lot of companies.

@TingluoHuang @pje

**Comment by TingluoHuang** [comment]
With `--ephemeral` the deregistering of the runner is done by the service and not counted as part of your API rate limit.

**Comment by t0rr3sp3dr0** [comment]
Ok, then we have double the number of jobs that I estimated. But even then you are limiting the number of jobs that can be run by self-hosted runners within an hour.

There's also another problem to consider. Even if you have enough number of operations, registering multiple runners at the same time triggers the secondary rate limit. This was also a problem that I faced.

Unless registration of runners are exempt from rate limits, including secondary ones, I think we shouldn't remove this feature.

Also I'm not sure that's interesting for GitHub, as you're making every user of this feature increase their number of API calls towards your severs.

**Comment by thboop** [comment]
@t0rr3sp3dr0

The [api call token](https://docs.github.com/en/rest/reference/actions#create-a-registration-token-for-an-organization) is reusable for up to an hour, are you able to cache and reuse them?

**Comment by t0rr3sp3dr0** [comment]
Yes, I can definitely cache the registration token. Then I would be spending one API operation per repository, as I register runners on repositories and not on the organization.

The limit now becomes very reasonable. That would only be a problem if I had over 10k repositories, but I don't even have 1k repositories.

**Comment by t0rr3sp3dr0** [comment]
Actually, I noticed another problem. Maybe you have a suggestion for that as well.

The registration token cache works on our scenario because we run our Linux runners on Kubernetes and we have an operator that deals with everything.

But we also have a fleet of macOS runners and in this case we need to cleanup the environment between jobs. So we start macOS with the runner using `--once` and after the job is processed, we restore a snapshot to ensure we always have the same environment for any job run. This is possible because when the snapshot is taken the runner is already registered.

But by deregistering it at the end of the job when `--ephemeral` is used, the runner will not be able to start again after the snapshot is restored, as its credentials got invalided when the runner was deregistered on the server-side.

A workaround would be to have on the machine credentials with power to register a new runner when the snapshot is taken. But this poses a security risk that I'm not willing to take.

You might have some idea as GitHub manages its on fleet of macOS runners and solves this same problem somehow.

**Comment by thboop** [comment]
Hey @t0rr3sp3dr0 ,

Thanks for the feedback here. A few things our team is working on:

- We aren't going to remove `--once` flag just yet. Our team views ephemeral as the future, but we want to ensure we don't break your current workflows as we move towards it
- We are looking into providing a separate rate limit for the runner registration endpoint with a higher value, it wouldn't count against your normal rate limit quota. Rate limits allow us to prevent malicious users from doing denial of service attacks, but we want it high enough to not impact legit usage. I'll follow up with more exact details on numbers here in the near future.
- We are working on updating our docs with best practices to manage a pool of ephemeral runners, we will touch on caching and how to manage tokens in those docs. Typically this is an operator pattern, as you are already using on linux. Our macOS machines get a token passed in in a similar pattern

Please follow up if you have any questions or concerns, and we appreciate the

**Comment by t0rr3sp3dr0** [comment]
Thanks for the info, @thboop!

I just got worried because there’s a comment on the `--once` flag suggesting it would get removed by October 2021.
https://github.com/actions/runner/blob/f259e5706fd354b1bf6b54ea0a8705a5eaff48bf/src/Runner.Common/Constants.cs#L131

**Comment by MichaelJJ** [comment]
Providing a separate rate limit for the runner registration endpoint would be a great help, we're looking to use this for a large enterprise with many repos, so caching the token may not help that much.

**Comment by thboop** [comment]
We won't be deleting this endpoint in the near future, and we just rolled out a new  new rate limit for just the runner registration endpoint that supports (10,000) registrations an hour. If this limit isn't high enough for your use case, please create a support ticket and we can move forward from there.

Going to close this out.

You can see the status of this new rate limit at the `https://api.github.com/rate_limit` endpoint if you are authenticated.

```
        "actions_runner_registration": {
            "limit": 10000,
            "used": 1,
            "remaining": 9999,
            "reset": 1632884000
}
```

**Comment by MichaelJJ** [comment]
@thboop Does the endpoint count for enterprise, organization and repo registration tokens?

**Comment by MichaelJJ** [comment]
@thboop As a heads up, tried again today, the actions_runner_registration is not being used, still seeing API limit being consumed.  I'm using an OAuth token installed in an enterprise.

**Comment by thboop** [comment]
@MichaelJJ what endpoint were you hitting? It only applies to registering a runner when using `./config.sh` or the windows equivalent.

**Comment by MichaelJJ** [comment]
We are using the endpoints: https://api.github.com/enterprises/<enterprise>/actions/runners/registration-token and https://api.github.com/orgs/<org>/actions/runners/registration-token

We are looking to use the https://github.com/actions-runner-controller/actions-runner-controller and our own tools to create runner tokens for registering runners, also our enterprise has few enterprise users so we have a proxy API on-premise to allow a normal user to get a registration token.

I'll create an issue to have the enterprise/org endpoints added to the separate rate limit.
