### ISSUE TITLE
Build does not indicate failure after Job Queue timeout

### ISSUE THREAD

**Issue by mjannapureddy0816** [actions/runner#1347]
**Describe the bug**
We have a Workflow to be run two machines with  different system architectures (X64 and ARM64)  which are self hosted runners. This workflow runs on every pull request to master. We started to observe that the job waits in the queue for 24 hrs as the X64(label) agent was offline and after 24 hrs it just reports the build/workflow itself is passed(Showing green) on both ARM64 and X64 although only ARM64 passed.

**To Reproduce**
1. Configure two agents/runners with different labels (For Ex; X86 and ARM 64)
2. Include the below code in your build yaml file before the steps:
```
jobs:  
  build:
    runs-on: '${{ matrix.os }}'
    continue-on-error: true
    strategy:
         matrix:
           os: [X64, ARM64]
```

3. Set one of the agents offline (Turn off or shutdown the service)
4. Trigger the workflow and wait for 24 hrs (Not sure if we can manually set a lower timeout for testing) 

**Expected behavior**
After the timeout is reached it should indicate failure and should be reported in Red status 

## Runner Version and Platform
Version: 2.281.1
OS: Linux(ubuntu 18.04)

## What's not working?
Status reported is showing incorrect. It is showing Green after 24 hrs of timeout on an offline agent instead of showing it as failed or Red

## Job Log Output
Screenshot of the error:
![image](https://user-images.githubusercontent.com/84750130/133508930-491b3187-9b49-4098-be1f-da4b9132ced6.png)

**Comment by ruvceskistefan** [comment]
Hey @mjannapureddy0816,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
