### ISSUE TITLE
Added -coverpkg=./... to go test fails the step with no errors of value

### ISSUE THREAD

**Issue by ghstahl** [actions/runner#1353]
**Describe the bug**

I have a working step
```yaml
    - name: Generate coverage report and lint
      run: |
        mkdir -p coverage
        go test -v ./... -cover -short  -coverprofile=coverage/cov.out -json > coverage/report.json
        go tool cover -html=coverage/cov.out -o coverage/cov.html
        go tool cover -func=coverage/cov.out > coverage/byfunc.txt
        go install github.com/mgechev/revive@latest
        revive -config ./revive.toml -formatter default ./... > coverage/golint.txt
```
however when I add ```-coverpkg=./...``` it fails the step with no real errors to work with.
```yaml
    - name: Generate coverage report and lint
      run: |
        mkdir -p coverage
        go test -v ./... -cover -short -coverpkg=./... -coverprofile=coverage/cov.out -json > coverage/report.json
        go tool cover -html=coverage/cov.out -o coverage/cov.html
        go tool cover -func=coverage/cov.out > coverage/byfunc.txt
        go install github.com/mgechev/revive@latest
        revive -config ./revive.toml -formatter default ./... > coverage/golint.txt
```

## Error Output
[FAILED RUN](https://github.com/fluffy-bunny/grpcdotnetgo/runs/3636653188?check_suite_focus=true)
```bash
Run mkdir -p coverage
  mkdir -p coverage
  go test -v ./... -cover -short -coverpkg=./... -coverprofile=coverage/cov.out -json > coverage/report.json
  go tool cover -html=coverage/cov.out -o coverage/cov.html
  go tool cover -func=coverage/cov.out > coverage/byfunc.txt
  go install github.com/mgechev/revive@latest
  revive -config ./revive.toml -formatter default ./... > coverage/golint.txt
  shell: /usr/bin/bash -e {0}
  env:
    BINARY: server
    GOROOT: /opt/hostedtoolcache/go/1.17.1/x64
Error: Process completed with exit code 1.
```
Also, it works on my machine(windows go 1.17) and some private github actions where I copied from .  I can share those if you contact me.

**To Reproduce**
1. Go to [here](https://github.com/fluffy-bunny/grpcdotnetgo/blob/f50da1625a7f1101a7a3de1a86571e481f72ca79/.github/workflows/go.yml#L84)  

**Expected behavior**

## Runner Version and Platform
Version of your runner?
Current runner version: '2.282.1'
 Ubuntu
  20.04.3
  LTS

Environment: ubuntu-20.04
  Version: 20210913.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210913.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210913.1

## Runner and Worker's Diagnostic Logs

[logs_176.zip](https://github.com/actions/runner/files/7188505/logs_176.zip)
.

**Comment by nikola-jokic** [comment]
Hi @ghstahl,

Are you still experiencing this issue? I looked at your workflows and it seems to me like they are passing now, so I was wondering if this issue has been fixed, or should I start reproducing this behaviour?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
