### ISSUE TITLE
Self hosted Runner Going offline automatically every alternate day.

### ISSUE THREAD

**Issue by sarathk-blink** [actions/runner#1357]
We have a self-hosted runner thats set to run on Amazon Ec2 instance and every other day our jobs fail because the self-hosted runner being offline. Its same thing when I tried configuring my office mac to be self-hosted runner , it goes offline automatically. Every time we see the runner status as offline, we would then have to either SSH to EC2 to run ./run.sh or do the same thing locally.

This has been an on-going issue and haven't found any solution even after looking on the internet, appreciate any help.

**Comment by nikola-jokic** [comment]
I am closing this issue because it seems to be fixed. If you experience the issue again, feel free to re-open it!
