### ISSUE TITLE
Automatically de-register failed ephemeral runners

### ISSUE THREAD

**Issue by MichaelJJ** [actions/runner#1364]
Currently, if an ephemeral registers itself but if no job is run, the service does not complete successfully, or the machine is destroyed before the job is completed the runner will remain as registered, but offline in the repo.

Would it be possible for runners registered as ephemeral to automatically de-register after a period of time, like 24-72 hours?  Alternatively, could the registration date/last active be added to the runner API, as it's not currently possible to see when a runner was added to a repository.  Without this information it's not easy to create automation to clean stale runners.

**Comment by TingluoHuang** [comment]
The system will clean up offline runners after 30 days. 😄

**Comment by MichaelJJ** [comment]
That's good to know, maybe a configurable or lower time limit for ephemeral runners?  The runner list could get pretty messy...

**Comment by GMNGeoffrey** [comment]
I'd like to suggest that this should be possible (though not the default) even if the runner *isn't* ephemeral. I think it's reasonable to want a runner that runs multiple jobs, but also deregisters automatically without the need to fetch another token when it gets SIGTERM or similar.

I also just cleaned up 25 pages of offline runners (one API call at a time). Would be great to have this fixed :-)

**Comment by GMNGeoffrey** [comment]
For people currently experiencing the same pain as me, here's a super hacky script I run periodically to clean things up. I'm sure there's a much better way to do this that isn't a series of individual api calls with slapped-together exponential backoff, but this is good enough to just launch in some other tab while I'm doing other things


```shell
#!/bin/bash
# Copyright 2022 Google LLC.
# SPDX-License-Identifier: Apache-2.0

ORG=iree-org

sleep=4
readarray -t runners < <(gh api --paginate -H "Accept: application/vnd.github+json" "/orgs/${ORG}/actions/runners?per_page=100" \
  --jq '.runners | .[] | select(.status == "offline") | .id')
for runner in "${runners[@]}"; do
  while true; do
    gh api --method DELETE -H "Accept: application/vnd.github+json" "/orgs/${ORG}/actions/runners/${runner}"
    ret=$?
    if (( ret == 0 )); then
      break
    fi
    echo "Delete failed. Sleeping for ${sleep} seconds"
    sleep "${sleep}"
    echo "Increasing sleep to $(( sleep*=2 )) seconds"
  done
done
```

**Comment by sethvargo** [comment]
Per https://github.blog/changelog/2022-08-03-github-actions-remove-offline-self-hosted-runners/, it looks like ephemeral runners are now removed in a day instead of 30.

**Comment by TingluoHuang** [comment]
> Per https://github.blog/changelog/2022-08-03-github-actions-remove-offline-self-hosted-runners/, it looks like ephemeral runners are now removed in a day instead of 30.

We are rolling out this change slowly to avoid extra pressure on the service, it will probably take one week or two to finally reach 1 day from 30.
