### ISSUE TITLE
Allow use of a customised systemd template in svc.sh

### ISSUE THREAD

**Issue by andrewbelcher** [actions/runner#1367]
**Describe the enhancement**
https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service#customizing-the-self-hosted-runner-service describes the use of customised services and recommend using `actions-runner/bin/actions.runner.service.template` as a reference. But to do that, you have to completely manage the service yourself.

It would be really handy if there was an optional argument for `svc.sh` that allowed you to specify an alternative template file, but still have `svc.sh` handle replacements and be able to manage the service.

**Comment by ethomson** [comment]
Thanks for the suggestion @andrewbelcher - this seems like a reasonable addition.  I'm adding the `good-first-issue` tag in case somebody's interested in creating a PR.

**Comment by nikola-jokic** [comment]
#1612

**Comment by TingluoHuang** [comment]
The change will be included in the next runner release. 🙇
