### ISSUE TITLE
[BUG] There is no way to pass escape sequence \n to the underlying command on macos-latest runner

### ISSUE THREAD

**Issue by solodon4** [actions/runner#1373]
**Describe the bug**
Consider a simple bash command `echo "Hello World" | sed -e "s/ /\n/g"` which on my OS X laptop produces Hello and World on separate lines. Unfortunately, due to bug in either `macos-latest` runner or yaml parser used by it, there is currently no way for me to achieve that.

**To Reproduce**
Create a simple workflow with the following commands as I did [here](https://github.com/CrowdsTech/cocos2d-x-CI/blob/ac19f44a8bf0dee6602f2181e49c996adab16b71/.github/workflows/ci.yml#L56-L63):
```yaml
run: |
  echo "Hello World" | sed -e "s/ /\n/g"
  echo "Hello World" | sed -e "s/ /\\n/g"
  echo "Hello World" | sed -e "s/ /\\\\n/g"
  echo "Hello World" | sed -e "s/ /\x0A/g"
  echo "Hello World" | sed -e "s/ /\\x0A/g"
  echo "Hello World" | sed -e "s/ /\\\\x0A/g"
```
**Expected behavior**
I would expect at least one of the commands above to produce a valid two-line output, however, on`macos-latest` none of them does!

## Runner Version and Platform
Version of your runner?

`macos-latest`:
```
Current runner version: '2.283.1'
Operating System
  Mac OS X
  10.15.7
  19H1417
Virtual Environment
  Environment: macos-10.15
  Version: 20210919.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210919.1/images/macos/macos-10.15-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20210919.1
Virtual Environment Provisioner
  1.0.0.0-master-20210914-1
```

`ubuntu-latest`
```
Current runner version: '2.283.1'
Operating System
  Ubuntu
  20.04.3
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210919.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210919.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210919.1
Virtual Environment Provisioner
  1.0.0.0-master-20210914-1
```

## What's not working?
None of the cases in the above mentioned step executed on `macos-latest` produces a new line in the output, while 4 out of 6 tested syntaxes produce new line in the output on `ubuntu-latest`

## Job Log Output
Consider step named `GitHub Actions Bug Repro` in [this run of the workflow](https://github.com/CrowdsTech/cocos2d-x-CI/runs/3710001581?check_suite_focus=true) on `macos-latest` and `ubuntu-latest`:

Here is echo of the command the way runner sees it and the output produced by `macos-latest`:
```
Run echo "Hello World" | sed -e "s/ /\n/g"
  echo "Hello World" | sed -e "s/ /\n/g"
  echo "Hello World" | sed -e "s/ /\\n/g"
  echo "Hello World" | sed -e "s/ /\\\\n/g"
  echo "Hello World" | sed -e "s/ /\x0A/g"
  echo "Hello World" | sed -e "s/ /\\x0A/g"
  echo "Hello World" | sed -e "s/ /\\\\x0A/g"
  shell: /bin/bash -e {0}
HellonWorld
HellonWorld
Hello\nWorld
Hellox0AWorld
Hellox0AWorld
Hello\x0AWorld
```
and here is echo of the command the way runner sees it and the output produced by `ubuntu-latest`:
```
Run echo "Hello World" | sed -e "s/ /\n/g"
  echo "Hello World" | sed -e "s/ /\n/g"
  echo "Hello World" | sed -e "s/ /\\n/g"
  echo "Hello World" | sed -e "s/ /\\\\n/g"
  echo "Hello World" | sed -e "s/ /\x0A/g"
  echo "Hello World" | sed -e "s/ /\\x0A/g"
  echo "Hello World" | sed -e "s/ /\\\\x0A/g"
  shell: /usr/bin/bash -e {0}
Hello
World
Hello
World
Hello\nWorld
Hello
World
Hello
World
Hello\x0AWorld
```
As you can see the runners produce different outputs and what's worse, none of the `macos-latest` outputs allows me to produce two lines!

## Runner and Worker's Diagnostic Logs
- [`macos-latest` log](https://pipelines.actions.githubusercontent.com/oJVFBzC6k8mMK15K7UlpuHs3kZw2bohkTsXCCPRWDoqJ3Ac1o5/_apis/pipelines/1/runs/12/signedlogcontent/3?urlExpires=2021-09-25T22%3A14%3A11.2092187Z&urlSigningMethod=HMACV1&urlSignature=q%2FU1bXVjQa1AA08T%2BeJF1cwAtmBJGtLYeY0cFmZoi48%3D)
- [`ubuntu-latest` log](https://github.com/CrowdsTech/cocos2d-x-CI/commit/ac19f44a8bf0dee6602f2181e49c996adab16b71/checks/3710001604/logs)

**Comment by rcowsill** [comment]
It looks like this could be due to differences between BSD sed and GNU sed:

https://stackoverflow.com/questions/1421478/how-do-i-use-a-new-line-replacement-in-a-bsd-sed

**Comment by solodon4** [comment]
Possibly. Is there a way to tell quickly which sed am i using on my MacBook? Asking cause the above `echo "Hello World" | sed -e "s/ /\n/g"` produces two lines, but it is possible I brew upgraded it at some point. It is located in `/usr/bin/sed` and `man sed` says it is BSD yet my output differs from `macos-latest` so I'm not sure anymore what that beast is. `sed --version` is apparently an invalid switch

**Comment by rcowsill** [comment]
That's interesting, the fact that `--version` isn't a valid switch implies that you don't have GNU sed. Unfortunately there doesn't appear to be an easy way to check the version for BSD sed. 

Does your MacBook run Catalina or Big Sur? GitHub Actions currently uses Catalina 10.15 for `macos-latest` jobs, but you can specify `macos-11` to get Big Sur.

**Comment by solodon4** [comment]
It's macOS Big Sur 11.5 and at the bottom of `man sed` I see March 27, 2017, which means it is definitely not the 2005 version  that comes by default with macOS.

**Comment by ethomson** [comment]
Hi!  Thanks for opening this issue.

Definitely the easiest way to get a newline is `printf "Hello\nWorld\n"` instead of trying to use `echo` and `sed`.  Regardless, this does not look like a problem in the runner _application_, this is the apps installed on the virtual enironment.

This repository is really only focused on bug reports and development of the runner application, which is a very small component of GitHub Actions.  If you have trouble with your workflow, the [actions community forum](https://github.community/c/code-to-cloud/52) is the best place for that.

In the meantime, I'm closing this issue here.  Thanks again!
