### ISSUE TITLE
Add build instructions to compile runner from source

### ISSUE THREAD

**Issue by edudip-thomasp** [actions/runner#1375]
###### Describe the enhancement
Add build instructions to compile runner from source.

###### Additional information
This is necessary because autoupdate causes many problems in Kubernetes. I want to build runner inside a Dockerfile
myself and control deployment of that image myself using CI/CD. Of course I already tried to work myself into this stuff, but the C#/.NET ecosystem seems to be very complicated from my POV. Besides, I think every open source based repo should have such instructions because the usecase of building stuff from source can arise because of many different reasons.

**Comment by rcowsill** [comment]
Have you seen the build instructions on the contributing page?

https://github.com/actions/runner/blob/main/docs/contribute.md

There are a couple of missing items in the requirements section, but other than that I found it worked as described on Windows and Linux.

**Comment by edudip-thomasp** [comment]
Hey thank you so much. I will try start building runner inside a docker container in an hour or so!
