### ISSUE TITLE
https://github.com/actions/runner/releases , extract data of latest release version and commit hash programatically.

### ISSUE THREAD

**Issue by nixinator** [actions/runner#1415]
is there any way programmatically i can get notification of the latest release from https://github.com/actions/runner/releases 
with the github api, I want to hot wire the results of the latest version and commit hash into an update script i'm working on.

I don't want to go down the screen scraping route because that feel dirty..... and avoiding parsing html pages might save my sanity.

**Comment by nixinator** [comment]
hey, thanks to both of you for the idea, I've been out of the game with a  'super cold' , so not felt like doing much coding, but back in the game again, so lets see what we can do.

**Comment by ethomson** [comment]
> is there any way programmatically i can get notification of the latest release from https://github.com/actions/runner/releases with the github api

We don't have a mechanism for you to subscribe to new releases, but you can poll for releases at https://github.com/actions/runner/releases.atom

**Comment by nikola-jokic** [comment]
Hi everyone,

Because we try to keep issues related to the runner repository itself here, I will now close this issue. Thank you for providing the answers!
