### ISSUE TITLE
follow symlink to `.yml` file

### ISSUE THREAD

**Issue by nujarum** [actions/runner#1420]
I defined a `.yml` workflow file in an another directory, and created a symlink to that file under `.github/workflows`, as shown in the tree structure below.
```shell-session
<root>
├── .github
│   └── workflows
│       └── test.yml -> ../../entities/test.yml
└── entities
    └── test.yml
```

However, the attempt with this configuration returned an error and workflow did not run.
> **Invalid workflow file : .github/workflows/test.yml#L1**
> You have an error in your yaml syntax on line 1

Why doesn't GitHub Actions follow the symlink?
If the reason is security related, I'm going to give up.

What I want to do is to run `.yml` workflow files that are defined in a different repository by using `git submodule`.
By doing this, I believe I can run the same workflow in multiple repositories and avoid double maintenance.

If there are any alternatives, I would appreciate your suggestions.

**Comment by TingluoHuang** [comment]
Will this incoming feature help you?
https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

**Comment by nujarum** [comment]
@TingluoHuang
Thanks for your response.

When is this `Reusing workflows` feature going to be ready?
I've only had a quick look at it, but I think this feature will help me with what I want to do.
(Defining the parameters may be a bit tedious.)

On the other hand, I have a technical curiosity about GitHub Actions not following symlinks.
Is it intentionally making symbolic links unavailable for some reason?

**Comment by ethomson** [comment]
Reusing workflows has shipped!  :shipit: 

It is intentional that we do not follow symbolic links - it's for security purposes, and we don't have a plan to change this in the future.
