### ISSUE TITLE
Workfows missing branch of execution in UI

### ISSUE THREAD

**Issue by jneal-afs** [actions/runner#1422]
**Describe the bug**
The branch where the workflow is executed from is only available for `pull_request` and `push` event types. `schedule, `workflow_dispatch`,  and `workflow_run` do not show the branch. This is confusing and forces us to click into the workflow in order to find out what it is executed from.

![image](https://user-images.githubusercontent.com/88398073/137972619-44682a65-23f5-4f62-b0ef-942c0d9f9eef.png)

This screenshot shows the issue. The last row is a workflow_dispatch run with a missing branch.

**To Reproduce**
1. Run a workflow of type `workflow_dispatch`

**Expected behavior**
Branch should show in the UI

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Branch does not show.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by nikola-jokic** [comment]
Hi @jneal-afs,

Could you please provide an example workflow file, so we can reproduce this behaviour?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
