### ISSUE TITLE
Relax the 10-parameter input limitation on workflow_dispatch

### ISSUE THREAD

**Issue by DanySK** [actions/runner#1425]
**Describe the bug**

Workflows with more than 10 parameters are considered invalid.
Crucially, this also applies to *reusable workflows* used from a workflow that could be dispatched manually.

**To Reproduce**
1. Write a workflow with at least 11 inputs
2. set it to run `on: { workflow_dispatch: }`
3. See error upon execution

**Expected behavior**
The workflow does not trigger errors

## Runner Version and Platform
Current GHA hosted runner

## What's not working?
```
 Check failure on line 1 in .github/workflows/build-and-deploy.yml

GitHub Actions
/ .github/workflows/build-and-deploy.yml
Invalid workflow file
handling usage of workflow "DanySK/workflows/.github/workflows/build-and-deploy-gradle-project.yml@master": workflow is invalid: you may only define up to 10 `inputs` for a `workflow_dispatch` event
```

Note: I am not sure that `runner` is the correct repository for reporting this. Please let me know if I should open the issue report elsewhere.

The problem is also being discussed [here](https://github.community/t/you-may-only-define-up-to-10-inputs-for-a-workflow-dispatch-event/160733).

**Comment by bbrzoska** [comment]
We're also bumping into this. Our use case is using composite action and it requires many optional configuration options.

One workaround is to accept a JSON payload and deserialize within an action, but that's pretty nasty and error prone when triggering from the UI.

The limit should be at least 25 to cover most use cases.

**Comment by igorcosta** [comment]
Even for reusable workflows as suggested [here](https://github.community/t/no-more-than-10-inputs-for-reusable-workflows/206812), doesn't work.

**Comment by yongzhang** [comment]
Hope this limitation can be relaxed ASAP, it's a huge block to us.

**Comment by TingluoHuang** [comment]
Please report this to https://github.community/c/code-to-cloud/github-actions/41
the runner itself has no control over this limitation.

**Comment by igorcosta** [comment]
@yongzhang  this might help you https://github.com/github/professional-services-apac/issues/40

**Comment by yongzhang** [comment]
> @yongzhang this might help you https://github.com/github/professional-services-apac/issues/40

Thanks, but what is it? I got 404

**Comment by igorcosta** [comment]
> > @yongzhang this might help you [github/professional-services-apac#40](https://github.com/github/professional-services-apac/issues/40)
> 
> Thanks, but what is it? I got 404

@yongzhang  I pasted the wrong link, here  you go https://gist.github.com/igorcosta/b883655de1278b01c9533a8f17f9b58d

**Comment by igorcosta** [comment]
@yongzhang  My apologies, I pasted the wrong, see the updated link above.

**Comment by yongzhang** [comment]
> @yongzhang My apologies, I pasted the wrong, see the updated link above.

Thanks for sharing, I'm using workflow_dispath as user interface for manual deployment, the "on push" trigger may not be a good fit.

**Comment by acevos01** [comment]
Sometimes it's our QA team the ones that triggers this workflows and most of the time they don't have access to the code that's why the two options for add inputs using commit messages neither modifying files. In Gitlab for example there is an option to define through the UI additional environment variables, that doesn't exist at this moment in Gitub actions, and because of that some of us are using secrets as environment variables because that's the only way to externally inject this additional inputs( using the UI) . It would be easier if this restriction is removed.

**Comment by NunoMaga** [comment]
also blocked by this

**Comment by mnarra-varmour** [comment]
Just hit this issue. Please remove the limit asap.

**Comment by nkm269** [comment]
Please remove the limit asap.

**Comment by gfrid** [comment]
just hit this limit also. Its a CICD blocker.

**Comment by denist-huma** [comment]
> > Even for reusable workflows as suggested [here](https://github.community/t/no-more-than-10-inputs-for-reusable-workflows/206812), doesn't work.
> 
> That issue was addressed and can serve as a workaround in some cases. See my comment here: https://github.community/t/you-may-only-define-up-to-10-inputs-for-a-workflow-dispatch-event/160733/34?u=piekstra

this link is broken as many on GitHub community, lead to https://github.com/orgs/community/discussions/
