### ISSUE TITLE
svc.sh file missing in 2.283.3

### ISSUE THREAD

**Issue by brandonbirdj** [actions/runner#1446]
**Describe the bug**
When opening `actions-runner-linux-arm64-2.283.3.tar.gz` there is no  svc.sh file only the following.

- config.sh
- externals
- bin
- env.sh
- run.sh

**To Reproduce**
1. Follow the steps for a repo
```
# Create a folder
$ mkdir actions-runner && cd actions-runner# Download the latest runner package
$ curl -o actions-runner-linux-arm64-2.283.3.tar.gz -L https://github.com/actions/runner/releases/download/v2.283.3/actions-runner-linux-arm64-2.283.3.tar.gz# Optional: Validate the hash
$ echo "b2a0eeffdcd7b731298cf6fdb40e2a69d6c087310e812e8b2e34e643b6d3bfdf  actions-runner-linux-arm64-2.283.3.tar.gz" | shasum -a 256 -c# Extract the installer
$ tar xzf ./actions-runner-linux-arm64-2.283.3.tar.gz
```
2. `ls`

**Expected behavior**
https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service there should be a `svc.sh` file present

## Runner Version and Platform
Version of your runner?
2.283.3.

OS of the machine running the runner? OSX/Windows/Linux/...
Linux ARM64

## What's not working?
```
"./svc.sh install runner", "msg": "[Errno 2] No such file or directory: b'./svc.sh'"
```

## Job Log Output
NA

## Runner and Worker's Diagnostic Logs
NA

**Comment by project-administrator** [comment]
Why is this issue closed? 
There is still no svc.sh inside of the GH-runner package.

**Comment by project-administrator** [comment]
OK, just figured out that svc.sh is generated by running the config.sh
