### ISSUE TITLE
Can't find any online and idle self-hosted runner

### ISSUE THREAD

**Issue by TheOnlyWei** [actions/runner#1458]
**Describe the bug**
Workflow stuck on a job with the log:
```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprise that matches the required labels: 'Organization'
Waiting for a self-hosted runner to pickup this job...
```
The workflow doesn't cancel and has no option to delete when clicking "...".

This might also be causing double workflow file bug. Basically commit a workflow file, but I removed it with a force-push since it was not ready, and introduce the same workflow file again but updated, and you get double workflow files even though there are no workflow files in master branch but only one in a feature branch:

<img width="410" alt="github-actions-double-workflow" src="https://user-images.githubusercontent.com/19400755/140001022-5ac65205-c26f-4ecf-9fe5-7171b14af9a7.png">

**To Reproduce**
1. Make a PR with the workflow file to public repository with PR with the following triggers and multiple jobs:
```
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      the_input:
        description: 'the input'
        required: true
        default: 'testvalue'
      the_input2:
        description: 'the input  2'
        required: false
...
```
2. Rebase the workflow file into master and check Actions tab.
3. Actions tab will have a job that is stuck on:

```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprise that matches the required labels: 'Organization'
Waiting for a self-hosted runner to pickup this job...
```
Even though "Organization" tagged runner does exist.
4. Cancel run.
5. Job does not fully cancel as now there is a later job in the workflow that now becomes still stuck on:

```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprise that matches the required labels: 'Organization'
Waiting for a self-hosted runner to pickup this job...
```
6. Stop runner in self-hosted environment, but the job continues to run with following message:
```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprise that matches the required labels: 'Organization'
Waiting for a self-hosted runner to pickup this job...
```

So the run cannot be canceled.

**Expected behavior**
The workflow should find "Organization" self-hosted runner as it does exist. When I cancel a run, it should cancel all jobs, but it doesn't cancel all jobs as one of the jobs is stuck on:

```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprise that matches the required labels: 'Organization'
Waiting for a self-hosted runner to pickup this job...
```

## Runner Version and Platform
Version of your runner?
actions-runner-win-x64-2.283.3

OS of the machine running the runner? OSX/Windows/Linux/...
Windows Server 2019 Datacenter

## What's not working?
Please include error messages and screenshots.
```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprise that matches the required labels: 'Organization'
Waiting for a self-hosted runner to pickup this job...
```

<img width="992" alt="github-actions-stuck-job" src="https://user-images.githubusercontent.com/19400755/139954362-0a5ea90e-82fa-42dd-8008-416f56aae980.png">

## Job Log Output
```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprise that matches the required labels: 'Organization'
Waiting for a self-hosted runner to pickup this job...
```

**Comment by TingluoHuang** [comment]
@TheOnlyWei can you share a link to your workflow run?

**Comment by TheOnlyWei** [comment]
@TingluoHuang These are the 3 runs with the problem:
https://github.com/Azure-Samples/Hybrid-CSharp-Samples/runs/4085645994?check_suite_focus=true
https://github.com/Azure-Samples/Hybrid-Golang-Samples/runs/4085225831?check_suite_focus=true
https://github.com/Azure-Samples/Hybrid-Golang-Samples/runs/4085194307?check_suite_focus=true

**Comment by TingluoHuang** [comment]
you have a job level condition set to `always()` which means the job is always going to run even on cancellation.
```
  Process_Logs:
    runs-on: Organization
    needs: Samples_CI
    if: always()
```

**Comment by ChristopherHX** [comment]
> Even though "Organization" tagged runner does exist
```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprise that matches the required labels: 'Organization'
Waiting for a self-hosted runner to pickup this job...
```


I bet your runner group **excludes** Public Repositories, this security feature is confusing some folks.

A more detailed answer incl. Solution:
https://github.com/ChristopherHX/github-act-runner/discussions/40

**Comment by TheOnlyWei** [comment]
@TingluoHuang It is still stuck trying to find a runner that exists. So Process_Logs job should have run regardless if the expected behavior is that it should run, but it did not. And because of that, it has been running for several hours trying to find a runner.

@ChristopherHX I watched my organization admin member configure to allow public repositories. Unless they turned them off, that is not the issue.

**Comment by ChristopherHX** [comment]
> trying to find an "Organization" tagged runner, which is the default tag for org-level runner groups

I'm don't even aware that such a feature exists, "Organization" isn't added to runners by default or do I miss something?
- The runner sets the labels during configure ( no idea why you call it tags )
- You can alter the labels from the webui
- the runner group doesn't add "Organization" as label and as such you have to configure your runner with `config.sh --labels Organization` or it only has `self-hosted`, your operating system like `linux`, `windows` and your architecture like `x64`, `arm64`.

_However I also had stuck jobs on github actions with hosted runners, or a hosted runner lost connection to github actions during a run if the log of the cancelled step is empty after cancellation._

**Comment by TheOnlyWei** [comment]
@ChristopherHX If they are called labels officially, then they are labels, but that is not the issue. Here is a screenshot of the "Organization" tag:

![github-actions-org-label](https://user-images.githubusercontent.com/19400755/140093218-991f872f-589f-415e-8469-e6b95b5d3550.png)

**Comment by Saff-Elli-Khan** [comment]
I have fixed this issue by adding the runner name that I added on my yml file at "runs-on" to the idle runner labels!

**Comment by DanKaplanSES** [comment]
> I have fixed this issue by adding the runner name that I added on my yml file at "runs-on" to the idle runner labels!

@Saff-Elli-Khan Sorry, I wasn't able to understand this. Could you elaborate with an example or a snippet of your yml file?

**Comment by WarrenWongCodes** [comment]
Yes I am having similar issue. @Saff-Elli-Khan was this a change to the GHA yml configuration. If so, can you elaborate? Thank you.

**Comment by nikola-jokic** [comment]
Hi @DanKaplanSES, @WarrenWongCodes,

You can add labels to the runner either during the runner configuration, or from the UI. If you want to do it from the UI, open your runner and you can see something similar to this:
![image](https://user-images.githubusercontent.com/97525037/178478890-04144652-9353-4271-80e3-5faa70de6a68.png)
Click and create a new label, after which you can schedule your workflows using the same label
In this example:
```yaml
jobs: 
  example-job:
    name: Test
    runs-on: test
    steps:
```

I think it is safe to close this issue, but if you feel otherwise, feel free to re-open it or comment on it :relaxed:
