### ISSUE TITLE
Error: No such file or directory Running from Runner

### ISSUE THREAD

**Issue by isaacrlevin** [actions/runner#1467]
**Describe the bug**
Calls with Azure CLI fail when executed my runner, but SSH onto runner works

**To Reproduce**

If the following workflow runs it fails
See log that fails and related workflow

I can however ssh into the runner (with mxschmitt/action-tmate@v3) and run the same azure cli command and it works

**Expected behavior**
Azure CLI commands should execute with runner

## Runner Version and Platform
Version of your runner? 2.284.0

OS of the machine running the runner? ubuntu-latest

**Comment by nikola-jokic** [comment]
Hi @isaacrlevin,

Are you still seeing this issue? And if yes, please provide the workflow since it seems that you forgot to add it in the issue description?

**Comment by isaacrlevin** [comment]
I don't remember what this was :/ Closing. Sorry about that
