### ISSUE TITLE
Support labels by name in concurrency groups

### ISSUE THREAD

**Issue by toast-gear** [actions/runner#1468]
Labels in issues and PRs are a powerful way of organising and managing your workflows. For those of us that want build our processes around GitOps workflows, concurrency groups are very limited at the moment due to the lack of support for labels (branches without the ability manipulate them with something like `cut` aren't very useful for this type of flow). Concurrency groups would be far more powerful if I was able to select labels with a LIKE statements to build the concurrency group name:

```yaml
concurrency:
    # group: qa-service/api
    group: qa-${{ join(github.event.pull_request.labels['service/*'].name, '-') }}
```

**Comment by ChristopherHX** [comment]
What about joining all labels with a hyphen to create the groupname?
```yaml
concurrency:
    group: qa-${{ join(github.event.pull_request.labels.*.name, '-') }}
```

Something like this is even an official sample https://docs.github.com/en/actions/learn-github-actions/expressions#example-4
_I didn't tested this yet, but this is valid expression syntax_

**Comment by toast-gear** [comment]
Thanks for responding @ChristopherHX I did have a quick play with this idea and got weird results. Additionally, this approach is also limited as it restricts what labels can be used as it now requires all labels to align. In my ideal world I want to drive a whole series of flows from labels and so would want to include things like the version. Not being able to use a specific set of labels prevents this as the version.

**Comment by ChristopherHX** [comment]
I have no idea what GitOps flows are and have nothing to do with this runner or github.

> all labels have to now align and be static in order

If you only want to pick specfic label names as concurrency group, you could use `contains` to check if the label is present.
action expressions are complex, but indeed have their limits.

```yaml
concurrency:
    group: qa-${{ format('{0}-{1}-{2}', contains(github.event.pull_request.labels.*.name, 'projecta') && 'projecta' || 'none', contains(github.event.pull_request.labels.*.name, 'projectb') && 'projectb' || 'none', contains(github.event.pull_request.labels.*.name, 'projectc') && 'projectc' || 'none')}}
```

I assume, if this is actually working would behave like
- PR with label `projecta` get's concurrency group `qa-projecta-none-none`
- PR with label `projectb` get's concurrency group `qa-none-projectb-none`
- PR with label `projectc` get's concurrency group `qa-none-none-projectc`
- PR with label `projecta` and `projectc` get's concurrency group `qa-projecta-none-projectc`

I think it is even possible to disable concurrency for one label e.g. `run-always` will create a unique group name
```yaml
concurrency:
    group: qa-${{ contains(github.event.pull_request.labels.*.name, 'run-always') && github.run_id || format('{0}-{1}-{2}', contains(github.event.pull_request.labels.*.name, 'projecta') && 'projecta' || 'none', contains(github.event.pull_request.labels.*.name, 'projectb') && 'projectb' || 'none', contains(github.event.pull_request.labels.*.name, 'projectc') && 'projectc' || 'none')}}
```

You potenially are able to get rid of `none` as placeholder for a missing label, or make them unique in case no 'project*' label is present.

I'm not shure if I understand your usecase correctly
It depends on your exact usecase, but I still assume it is possible with a very complex expression.

You would have to add each project's label into the workflowfile, unless github would implement more functions in action expressions.

**Comment by toast-gear** [comment]
> I have no idea what GitOps flows are and have nothing to do with this runner or github.

Well sort of, it has nothing to do with the runner or github directly but it's a deployment methodology and the runner's features are highly related to any deployment methodology as GitHub Action's purpose is to enable deployments.

> You would have to add each project's label into the workflowfile, unless github would implement more functions in action expressions.

I suspect this is ultimately what is required.

> I'm not shure if I understand your usecase correctly

My use case is I have a single central helm-charts repository which will be deploying N number of app repositories in which N is increasing over time.

The primary deployment workflow for the helm-charts repo will accept a `repository_dispatch` event which will allow me limit the concurrency per app in that workflow as I can take the app name from the payload (I need to test this but a `repository_dispatch` events payload is in the github context so it should work in theory). This approach however will only allow me to limit the concurrency for that one workflow which ingests the dispatch. If I want to break my deployment workflow up into a few logical pieces because the flow includes pull requests being raised and merged then I am no longer able to maintain concurrency as I can't maintain a app label to drive my concurrency group name. I'm forced to have it all maintained in a single workflow which is not ideal (probably possible though which is the avenue I'll have to explore).

In order to be able to maintain concurrency over multiple workflows I'd have to statically add a new app label into each workflow for each repository that needs to be onboarded onto this helm-charts repo. This would work but I'd much rather be able to simply grab the label dynamically allowing my workflows to support an infinite amount of apps.

**Comment by toast-gear** [comment]
I am able to achieve my goal using the below and using the comments in a PR as a sort of database.

```yaml
concurrency:
  group: ${{ format('{0}', join(github.event.pull_request.labels.*.name, '-')) }}
```

This however would be much nicer if I could incorperate labels in my pull requests for information and organisation purposes and only use a subset in my concurrency group name by using namespaces in my labels

```yaml
concurrency:
    # group: qa-service/api
    group: ${{ format('{0}', join(github.event.pull_request.labels['service/*'].name, '-')) }}
```

**Comment by ethomson** [comment]
Hi @toast-gear, this seems like a possibly useful addition.  However, suggestions for GitHub Actions functionality belong in the [GitHub feedback forum](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback), where the product managers and engineers will be able to review them.  This repository is really only focused on the runner application, which is a very small component of GitHub Actions.  If you could open this issue there, that would be very helpful for us!  😄

In the meantime, I'm closing this issue here.  Thanks again!
