### ISSUE TITLE
Error: The operation was canceled on each 5th job

### ISSUE THREAD

**Issue by kuvaldini** [actions/runner#1473]
**Describe the bug**
Short: GitHub  reports `  Error: The operation was canceled.`
<img width="343" alt="изображение" src="https://user-images.githubusercontent.com/47349143/141142955-375bd7ea-7413-4021-80db-d75894282a5b.png">

Our public repo [`hyperledger/iroha`](https://github.com/hyperledger/iroha) uses GitHub Actions for CI/CD process. 
Since the build process is heavy, we utilize powerful self-hosted AWS spot instances.
[`philips-labs/terraform-aws-github-runner`](https://github.com/philips-labs/terraform-aws-github-runner) is responsible for demanding, registering and removing VM instances.

That system worked fine during about 4 months. And problem rarely appeared, we could close eyes on  it, just rerun.  
But last time `Error: The operation was canceled.` become appearing on each 5th job without any notable systematic.

**To Reproduce**
I am not sure if it is a simple dial to reproduce. I found no notable systematic.

**Expected behavior**
No error messages, no cancelation.

## Runner Version and Platform
Version of your runner? LATEST Okt 2021.

OS of the machine running the runner? Amazon Linux.

## What's not working?
<img width="343" alt="изображение" src="https://user-images.githubusercontent.com/47349143/141142955-375bd7ea-7413-4021-80db-d75894282a5b.png">

## Job Log Output
`  Error: The operation was canceled.`

## Runner and Worker's Diagnostic Logs
In  progress... Looking around for that logs on AWS.

**Comment by TingluoHuang** [comment]
Close as it's a VM configuration issue and it's solved. 🙇‍♂️

**Comment by kuvaldini** [comment]
Hello. Yes, since near New Year the problem disappeared (or appeared very-very rarely). Was it solved in github/actions code. Or where? If you can please point to the thread or PR. Thanks @TingluoHuang

**Comment by mycarrysun** [comment]
@TingluoHuang ping ☝️

**Comment by kuvaldini** [comment]
@TingluoHuang ping2
