### ISSUE TITLE
JSON-type secrets are not being safely redeacted.

### ISSUE THREAD

**Issue by retzero** [actions/runner#1488]
**Describe the bug**

I have this json secrets.
And this will give readable prints which is not very secret.
Only `{` and `}` are masked.

- Registered secrets
```json
{
  "id": 123,
  "uname": "john-doe",
  "password": "foobar"
}
```

- Workflow example
```yml
      - run:  echo "${{ secrets.ITEM_JSON }}"
```

- Output
```
***
  id: 123,
  uname: john-doe,
  password: foobar
***
```

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?
- 2.278.0

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by TingluoHuang** [comment]
According to doc:
> To help ensure that GitHub redacts your secret in logs, avoid using structured data as the values of secrets. For example, avoid creating secrets that contain JSON or encoded Git blobs.

https://docs.github.com/en/actions/security-guides/encrypted-secrets#naming-your-secrets

**Comment by retzero** [comment]
Oh, I see. It's a limitation. 😢 
Is there any action to take care of this topic? Or... are you just leaving it like this?

**Comment by TingluoHuang** [comment]
When we get a multi-line secret, we are going to match any given line of the secrets in your log to protect you the most.
In your example, the runner will try to find any outputs that contain:
- `{`
-  `"id": 123,`
-  `"uname": "john-doe",`
-  `"password": "foobar"`
- `}`

However, when you use bash to echo the string out, it changes the output
![image](https://user-images.githubusercontent.com/1750815/141888177-33f7be38-9f58-4d4e-a873-8e59d43bb836.png)

from `"password": "foobar"` to `password: foobar`

From the runner's point of view `password: foobar` is not a "secret". 😢

**Comment by retzero** [comment]
Got your point!

**Comment by bryanmacfarlane** [comment]
One option is to store the base64 encoded json as a secret and then decode action side.  someone could even write an action to do this 

```base
$ export test_sec=$(echo '{\nid:"123"\n}' | base64)
$ echo $test_sec
ewoiMTIzIgp9Cg==
$ export test_sec_d=$(echo $test_sec | base64 --decode)
$ echo $test_sec_d
{
id:"123"
}

```
