### ISSUE TITLE
Support Reusable Workflows in Private Repositories

### ISSUE THREAD

**Issue by cycloss** [actions/runner#1489]
**Describe the enhancement**
Allow reusable workflows to be triggered even if they reside in a private repository. This is a documented limitation of reusable workflows, but it would be very helpful if it were changed. 

I maintain microservices in my organisation's private repos, and it would be good to be able to run integration tests on them by calling a single workflow residing in one of their repos. Currently this is not possible so I have to copy the testing workflow into each of the repos. Not very dry.

**Comment by TingluoHuang** [comment]
Please open a ticket in https://github.community/c/code-to-cloud/github-actions/41

The runner has no knowledge about any reusable workflows, it only knows how to execute a single job within the workflow jobs graph.

**Comment by HeadOnChristian** [comment]
> Please open a ticket in https://github.community/c/code-to-cloud/github-actions/41

If anybody is looking for a ticket on private reusable workflows see https://github.community/t/reusable-workflows-in-private-organization-repositories/215009

**Comment by hex0cter** [comment]
This limitation is just so annoying...

**Comment by Gby56** [comment]
I'm also trying to understand the limitations of that versus internal private github actions... I'm seeing a huge problem with using environment variables inside an action, I just get errors when accessing simple github variables like `${{ github.event.repository.name }}`

**Comment by dimisjim** [comment]
> > Please open a ticket in https://github.community/c/code-to-cloud/github-actions/41
> 
> If anybody is looking for a ticket on private reusable workflows see https://github.community/t/reusable-workflows-in-private-organization-repositories/215009

link is broken...

**Comment by pedrofracassi** [comment]
Please support this.

**Comment by dodomood** [comment]
+1 
i have to duplicate templates when working with multiple private repos. really github ?

**Comment by deanb-everc** [comment]
+1

**Comment by jcprz** [comment]
+1 👎

**Comment by reneyo** [comment]
+

**Comment by czetsuya** [comment]
+1 on this.

**Comment by dataviruset** [comment]
This seems to be possible now: https://github.blog/changelog/2022-12-14-github-actions-sharing-actions-and-reusable-workflows-from-private-repositories-is-now-ga/
