### ISSUE TITLE
Allow reusable workflows to be located at arbitrary locations and be local

### ISSUE THREAD

**Issue by umarcor** [actions/runner#1493]
**Describe the enhancement**

Although the documentation does not specify the limitation, it seems that reusable workflows must be located in `.github/workflows`. Moreover, specifying the version is necessary. Therefore, it is not possible to have a reusable workflow in the current branch.

See 

> https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#calling-a-reusable-workflow
> You reference reusable workflow files using the syntax:
>
> {owner}/{repo}/{path}/{filename}@{ref}

and 

https://github.com/hdl/containers/actions/runs/1469619022
> invalid value workflow reference: references to workflows must be rooted in '.github/workflows'

and

https://github.com/hdl/containers/actions/runs/1469617309
> invalid value workflow reference: no version specified

It would be desirable if the syntax was changed to `[{owner}/{repo}/]{path}/{filename}.yml[@{ref}]`.

**Comment by TingluoHuang** [comment]
Please open a ticket in https://github.community/c/code-to-cloud/github-actions/41

The runner has no knowledge about any reusable workflows, it only knows how to execute a single job within the workflow jobs graph.

**Comment by umarcor** [comment]
Done! https://github.community/t/allow-reusable-workflows-to-be-located-at-arbitrary-locations-and-be-local/212745

**Comment by umarcor** [comment]
Ref: github/feedback#9050

**Comment by Tworkneh** [comment]
9050

**Comment by Tworkneh** [comment]
#9050
