### ISSUE TITLE
[Windows] ANSI color codes no longer work with Powershell in Actions CI

### ISSUE THREAD

**Issue by MSP-Greg** [actions/runner#1495]
**Describe the bug**

The Windows image `20211102.4` (and many before it) correctly displayed color using ANSI color codes generated in PowerShell script.  When `20211110.1` was released, color was no longer displayed.

I'm using PowerShell 7.2 locally, and nothing changed when I upgraded from the previous version.

Reviewed information in PowerShell docs [about_ANSI_Terminals](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.2#cmdlets-that-support-ansi-output).

Note that color is displayed when generated by js code in a custom action and also Ruby code.

**To Reproduce**

I can provide a script...

**Expected behavior**
Color should be displayed

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner?
GitHub Actions Windows-2019 and Windows-2022

## What's not working?
No color displayed in Actions log

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by TingluoHuang** [comment]
@fhammerl did PowerShell stop producing color code for Actions.

**Comment by MSP-Greg** [comment]
I did more checking on this.  The runner version did not change, but PowerShell went from 7.15 to 7.2.0.  But, as mentioned above, when I upgraded to 7.2.0 locally (Windows 10), nothing changed, color output stayed the same.

The page linked to in the opening post mentions ENV variables `TERM` or `NO_COLOR`, but I'm not seeing either defined in Actions jobs.  So, maybe there's some breaking change in PowerShell that's interacting with the code here?

**Working ANSI Color:**
windows-2019, version 20211102.4
Current runner version: '2.284.0'
PowerShell 7.1.5

**Monochrome:**
windows-2019, version 20211110.1
Current runner version: '2.284.0'
PowerShell 7.2.0

**Comment by fhammerl** [comment]
Hmm, is `Error` still printed in red? 

It would be worth checking the `__SuppressAnsiEscapeSequences` env variable. 

If `__SuppressAnsiEscapeSequences=1` is set, pwsh will not enrich its output with color codes

**Comment by MSP-Greg** [comment]
@fhammerl thanks.

I added:
```ps1
if ($env:__SuppressAnsiEscapeSequences) { Remove-Item env:\__SuppressAnsiEscapeSequences }
```
and still monochrome.  JFYI, this code has been running since early Feb-2020.

**Comment by MSP-Greg** [comment]
This is due to a change in PowerShell 7.2.0. If the output is redirected, 'plainText' is forced, and can't (currently) be changed.
