### ISSUE TITLE
Broken link in README for runner_e2etest.yml

### ISSUE THREAD

**Issue by Anselmoo** [actions/runner#1503]
**Describe the bug**
The link [https://github.com/actions-canary/actions-runner-e2e/actions/workflows/runner_e2etest.yml](https://github.com/actions-canary/actions-runner-e2e/actions/workflows/runner_e2etest.yml) of the [README.md](https://github.com/actions/runner) is broken

**To Reproduce**

Klick on: [https://github.com/actions-canary/actions-runner-e2e/actions/workflows/runner_e2etest.yml](https://github.com/actions-canary/actions-runner-e2e/actions/workflows/runner_e2etest.yml)

**Expected behavior**

See Runner e2etest

**Comment by thboop** [comment]
We deleted this link in https://github.com/actions/runner/pull/1582
