### ISSUE TITLE
When re-running a Workflow I don't want the old run logs to be lost

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#1505]
**Describe the enhancement**
I noticed that when re-run a failed workflow, the old run is lost. This should not happen because I want to have prove that something failed. It should add a new entry in the list of workflows, not reuse the same one.

In the image below, the workflow in the middle is marked as run 42, but where is the 41? I can't see it anymore because I clicked on the "re-run" button:

![image](https://user-images.githubusercontent.com/55927613/143046446-f622729a-faac-4029-8feb-80525151eecc.png)

You should follow what Bitbucket and Jenkins do. They both add a new entry in the top of the list

![image](https://user-images.githubusercontent.com/55927613/143046857-64dcde0b-7555-4717-b374-4c25dfb0ee40.png)

**Code Snippet**
n/a

**Additional information**
n/a

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by TingluoHuang** [comment]
https://github.community/c/code-to-cloud/github-actions/41
might be a better place for this question, the runner repo doesn't have context around the UI experience.
