### ISSUE TITLE
Enable user to bypass .gitignore ignores

### ISSUE THREAD

**Issue by twolodzko-equinix** [actions/runner#1511]
When running GitHub Actions it seems not to include the files listed in .gitignore. I had hard time of finding any documentation for this feature or finding any information how this can be bypassed.

Imagine a scenario, where as a maintainer of a repository I have .env file listed in .gitignore. The .env file is used for the configuration. It is ignored because users locally may want to change the configuration depending on their development requirements. At the same time, the .env file with the default settings is stored in the git repository but added to .gitignore so that local changes by the users are not accidentally version controlled. I want to use the defaults in .env for CI when testing the code using GitHub Actions. This is not possible  now because GitHub Actions ignores the files mentioned in .gitignore.

Feature request:
* Document how GitHub Actions treat .gitignore.
* Add a possibility to bypass this behavior,
* **or** even introduce a separate .actionsignore file for such behavior not to conflate them.

**Comment by ethomson** [comment]
> At the same time, the .env file with the default settings is stored in the git repository but added to .gitignore so that local changes by the users are not accidentally version controlled. 

`.gitignore` is narrowly focused on how files that are not in the repository are detected.  If a file is already in the repository, then `.gitignore` does not apply.  This is not a GitHub Actions behavior, but part of git itself.

> Document how GitHub Actions treat .gitignore.

We do not deal with `.gitignore` at all, this is entirely a git construct.

If you have questions about your workflow, some more information about how the workflow is structured would be useful, but I think that this would be best suited for the [GitHub Actions community forum](https://github.community/c/code-to-cloud/github-actions/41).  This is not an issue that the runner software itself is likely to be able to resolve.

**Comment by ethomson** [comment]
Closing this issue - let me know if you think that there's something else we can do to help!
