### ISSUE TITLE
Support more than one waiting job in a concurrency group

### ISSUE THREAD

**Issue by wagyourtail** [actions/runner#1523]
It would be great to have the ability for more than one job to be waiting in a concurrency group, instead of having them cancel when there's one waiting and another one tries to start. 

an example of where this makes sense is for deploying multiple different builds that can't run at the same time due to a server not liking concurrent uploads. 
for example, I attempted to do this in https://github.com/wagyourtail/JsMacros/actions/runs/1523603064 recently.

**Comment by TingluoHuang** [comment]
https://github.community/c/code-to-cloud/github-actions/41 will be a better place for this question, the runner itself has no knowledge about concurrency.
