### ISSUE TITLE
Where is `matrix` -> `include` documented?

### ISSUE THREAD

**Issue by posita** [actions/runner#1527]
**Describe the bug**
I can't (easily) find documentation on how to use `matrix` -> `include` and what the accepted formats are. Apologies if I missed it. If you dig, you can tease out some inferences from #343, but it's not clear.

**Comment by TingluoHuang** [comment]
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations
