### ISSUE TITLE
VssFileStorage embeds a windows path separator on other platforms

### ISSUE THREAD

**Issue by jsoref** [actions/runner#1528]
https://github.com/actions/runner/blob/be9632302ceef50bfb36ea998cea9c94c75e5d4d/src/Sdk/Common/Common/ClientStorage/VssFileStorage.cs#L195

This eventually results in something like:
```
/home/runner/.config/GitHub\ActionsService/8.0/Cache/34e00c7b-39b1-4ed9-b15e-f23056129642/0000005a-0000-8888-8000-000000000000/LocationServiceData.config
```

**Comment by ruvceskistefan** [comment]
Hi @jsoref,
Thanks for the reported issue, the problem should be solved in linked pull request. Please feel free to report if the problem still exists after the PR is merged and shipped to the production.
