### ISSUE TITLE
Runner is online, service is up, tags are correct, pipeline does not detect a runner 

### ISSUE THREAD

**Issue by Dmitry1987** [actions/runner#1529]
**Describe the bug**
I have a Runner on ubuntu 20.04 on aws, that is online, service is up, tags are correct, pipeline does not detect a runner and shows the following (stuck):
```
Can't find any online and idle self-hosted runner in the current repository, account/organization that matches the required labels: 'self-hosted , docker , linux'
Waiting for a self-hosted runner to pickup this job...
```

**To Reproduce**
1. Create ubuntu 20.04 on aws, t2.medium in my case
2. "add self hosted runner" in the repo of choice
3. follow steps to install, then start service
4. check online status in settings of the repo
5. check service logs and status
6. launch or replay an existing pipeline (that was working on a previous runner that was decommissioned)
7. it does not detect the runner exists on a repo

**Expected behavior**
pipeline works

## Runner Version and Platform
Version of your runner?
2.285.0

OS of the machine running the runner? OSX/Windows/Linux/...
ubuntu 20.04

## What's not working?
pipeline workflow to run on the self hosted runner, like it did on others which were connected earlier

## Job Log Output
```
Can't find any online and idle self-hosted runner in the current repository, account/organization that matches the required labels: 'self-hosted , docker , linux'
Waiting for a self-hosted runner to pickup this job...
```

## Runner and Worker's Diagnostic Logs
service after a few restarts seems fine:
```
Dec 02 22:31:44 ip-172-31-40-61 systemd[1]: Started GitHub Actions Runner (z-z-z.development).
Dec 02 22:31:44 ip-172-31-40-61 runsvc.sh[3448]: .path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Dec 02 22:31:44 ip-172-31-40-61 runsvc.sh[3469]: Starting Runner listener with startup type: service
Dec 02 22:31:44 ip-172-31-40-61 runsvc.sh[3469]: Started listener process, pid: 3479
Dec 02 22:31:44 ip-172-31-40-61 runsvc.sh[3469]: Started running service
Dec 02 22:31:47 ip-172-31-40-61 runsvc.sh[3469]: √ Connected to GitHub
Dec 02 22:31:48 ip-172-31-40-61 runsvc.sh[3469]: Current runner version: '2.285.0'
Dec 02 22:31:48 ip-172-31-40-61 runsvc.sh[3469]: 2021-12-02 22:31:48Z: Listening for Jobs
```

_diag file last lines are: 
```
[2021-12-02 23:26:56Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/ubuntu/actions-runner/.credentials_rsaparams
[2021-12-02 23:26:56Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2021-12-02 23:31:56Z INFO MessageListener] No message retrieved from session 'p-17c1-476b-a9e2-p' within last 30 minutes.
[2021-12-03 00:02:01Z INFO MessageListener] No message retrieved from session 'p-17c1-476b-a9e2-p' within last 30 minutes.
[2021-12-03 00:22:03Z WARN GitHubActionsService] Authentication failed with status code 401.
WWW-Authenticate: Bearer
Strict-Transport-Security: max-age=2592000
X-TFS-ProcessId: p-9d7f-4273-9e94-p
ActivityId: p-2cd6-4ac4-82d6-p
X-TFS-Session: p-7b8e-4e31-b62f-p
X-VSS-E2EID: p-c95e-p-a17f-032d3abdc9bb
X-VSS-SenderDeploymentId: p-p-8c82-e969-91f4e88fcdec
X-TFS-ServiceError: The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27+is+not+authorized+to+access+this+resource.
X-VSS-S2STargetService: p-0000-p-8000-000000000000/visualstudio.com
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: pppRef B: pppRef C: 2021-12-03T00:22:03Z
Date: Fri, 03 Dec 2021 00:22:03 GMT
[2021-12-03 00:22:03Z INFO RSAFileKeyManager] Loading RSA key parameters from file /home/ubuntu/actions-runner/.credentials_rsaparams
[2021-12-03 00:22:04Z INFO GitHubActionsService] AAD Correlation ID for this token request: Unknown
[2021-12-03 00:32:05Z INFO MessageListener] No message retrieved from session 'c2ad9f6f-17c1--a9e2-' within last 30 minutes.
[2021-12-03 01:02:09Z INFO MessageListener] No message retrieved from session 'c2ad9f6f-17c1--a9e2-' within last 30 minutes.
```

**Comment by Dmitry1987** [comment]
I suspect the authentication warning but don't understand how it could be related, because the steps to create this runner were the same as last time and it was working 🤔  where does the warning point to, access to what?

**Comment by TingluoHuang** [comment]
@Dmitry1987 there was a service bug yesterday that cause self-hosted runners to stop picking up jobs, the bug should get fixed now.
Do you mind trying to cancel all the stuck runs and queueing new runs to see whether they get picked up by your self-hosted runner?

**Comment by Dmitry1987** [comment]
Hi, it was resolved, thank you 👍

**Comment by biswajitm2024** [comment]
Since January 8, I have been facing the same issues. I tried it several times; sudo ./svc.sh stop and sudo ./svc.sh start are not working for me. My version is v2.321.0. Is there any solution?

**Comment by jonfuller** [comment]
I am having the same issue as @biswajitm2024 , also started January 8 for me.

I'm also running version 2.321.0.

**Comment by jonfuller** [comment]
> I am having the same issue as [@biswajitm2024](https://github.com/biswajitm2024) , also started January 8 for me.
> 
> I'm also running version 2.321.0, ubuntu.
> 
> I have other self-hosted runners picking up jobs fine (though, all of those may be either Windows or macOS).

I set up a new runner on the same machine, and everything is working fine. Just going with that solution. 🤷
