### ISSUE TITLE
Error: Docker pull failed with exit code 1

### ISSUE THREAD

**Issue by mohanss08** [actions/runner#1531]
My Workflow `yaml` file as follows,

```
jobs:
  build:
    runs-on: Linux-host-runner
    container:
      image: ubuntu-20.04-lts:latest  # This is our private docker image.
```

```
$ docker --version
Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3
```
GitHub Action Error:-

```
Starting job container
  /usr/bin/docker pull ubuntu-20.04-lts:latest
  Error response from daemon: pull access denied for ubuntu-20.04-lts, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning: Docker pull failed with exit code 1, back off 4.74 seconds before retry.
  /usr/bin/docker pull ubuntu-20.04-lts:latest
  Error response from daemon: pull access denied for ubuntu-20.04-lts, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning: Docker pull failed with exit code 1, back off 9.535 seconds before retry.
  /usr/bin/docker pull ubuntu-20.04-lts:latest
  Error response from daemon: pull access denied for ubuntu-20.04-lts, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Error: Docker pull failed with exit code 1
```
i have this `ubuntu-20.04-lts:latest` private docker image on my host system locally. Still it fails with above error during action build. 

It looks trying to connect docker hub. How do i fix this to pull our local private image?

**Comment by mohanss08** [comment]
Image needs to pushed to private registry and post that, In the `yaml` following needs to added. 
```
credentials: username: mona 
password: ${{ secrets.docker_hub_password}}
```

example helped.

**Comment by SubhanshuMG** [comment]
My yaml file is as follows:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@1e95c1de343b5b0c23352d6417ee3e48d5bcd422
        with:
          cosign-release: 'v1.4.0'


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          buildkitd-flags: --debug

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"

        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
        
        
Github error:
 
        
![image](https://user-images.githubusercontent.com/53417895/154365790-bc13e3f5-dcd9-49c7-bb1e-3f33c45372fe.png)

Can you please tell me how to fix this issue as this is completely new for me, tried looking for the solution in stackoverflow but still couldn't find it.

**Comment by hans2103** [comment]
mentioned [here](https://github.com/actions/jekyll-build-pages/issues/41) too and seems to be solved
