### ISSUE TITLE
Multistage builds fail to copy from previous stage

### ISSUE THREAD

**Issue by michaelkruglos** [actions/runner#1542]
**Describe the bug**
Multistage dockerfiles with COPY instruction used to copy files from previous stages fail with file not found errors.

**To Reproduce**
1. Write a multistage file (e.g. https://github.com/Soluto/tweek/blob/master/TweekApi.Dockerfile)
2. Run docker build in your workflow

**Expected behavior**
A clean build, like on my local machine.

**Comment by TingluoHuang** [comment]
https://github.community/c/code-to-cloud/github-actions/41 might be a better place for this question, also make sure to paste your workflow and logs that show the error.
