### ISSUE TITLE
workflow_call github context is not updated.

### ISSUE THREAD

**Issue by jhautin** [actions/runner#1548]
**Describe the bug**

I use a main workflow that is calculating a value. this value is given as input of a sub workflow. 

The issue is that the value is not part of the context. i have the original github context from the main workflow not the context with the new input.

Moreover, the event type is not a workflow_call but a workflow_dispatch.

main workflow : https://github.com/vectice/github-actions-issue/blob/main/.github/workflows/main_workflow.yml
sub workflow :   https://github.com/vectice/github-actions-issue/blob/main/.github/workflows/sub_workflow.yml

**To Reproduce**
1. Go to public repository https://github.com/vectice/github-actions-issue 
2. Run the main_workflow (https://github.com/vectice/github-actions-issue/actions/workflows/main_workflow.yml)
3. See context in display_context job of the sub workflow. the context is not the good one.

**Expected behavior**
I would expect a github context with:
* github event type set to `workflow_call`
* github inputs set to values in the `with` keyword (ie `github.event.inputs.something` not empty)

## Runner Version and Platform
Current runner version: **2.285.1**
* Operating System
   Ubuntu
   20.04.3
   LTS
* Virtual Environment
  Environment: ubuntu-20.04
  Version: 20211129.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211129.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211129.1
* Virtual Environment Provisioner
  1.0.0.0-master-20211123-1

## What's not working?
the context of the called sub-workflow contains the following values:
``` 
{
"workflow": "Main workflow",                                 <<< should be sub workflow
  "event_name": "workflow_dispatch",                    <<< should be workflow_call
  "event": {
    "inputs": {
      "call-sub-workflow": "true"                               <<< should be "something": "a_sample_value"
    }
  },
  "workflow": ".github/workflows/main_workflow.yml"    <<< should be .github/workflows/sub_workflow.yml

}
```
## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by TingluoHuang** [comment]
base on https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
>When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow. The called workflow is automatically granted access to github.token and secrets.GITHUB_TOKEN. For more information about the github context, see "Context and expression syntax for GitHub Actions."

You can ask on https://github.community/c/code-to-cloud/github-actions/41 if you need more help.
The runner itself has no control over this part.
