### ISSUE TITLE
Please, please, please - suggest the use of Net.WebClient instead of Invoke-WebRequest in self-hosted instructions

### ISSUE THREAD

**Issue by slee-accesso** [actions/runner#1550]
In Settings/Actions/Runners in a repo, when creating a self-hosted runner, a series of Powershell instructions are presented. Among them is an Invoke-WebRequest call like this:

`Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.285.1/actions-runner-win-x64-2.285.1.zip -OutFile actions-runner-win-x64-2.285.1.zip`

Invoke-WebRequest is terribly slow due to it updating the screen during the download. The same download can be made in a one liner like this:

`(New-Object Net.WebClient).DownloadFile("https://github.com/actions/runner/releases/download/v2.285.1/actions-runner-win-x64-2.285.1.zip", "$PWD\actions-runner-win-x64-2.285.1.zip")`

The performance difference with this ~70mb file?

Invoke-WebRequest: 154.4 seconds
Net.WebClient: 3.41 seconds

I think cutting off 151 seconds is a nice thing, no? Could you please replace the suggested command with the faster one (at least for windows?)

Thanks!

  - Sean

**Comment by Temtaime** [comment]
Wouldn't it better to report this bug to powershell repo ?

**Comment by slee-accesso** [comment]
Well - I thought you'd be interested in improving your user's experiences with a small change to your directions. But if you'd rather punt to Microsoft, I can't stop you.

**Comment by slee-accesso** [comment]
Thank you, @ruvceskistefan : )

**Comment by ruvceskistefan** [comment]
You're welcome, thank you for the reported issue and the proposed solution. Since I've created a PR that solves this problem, I'm closing this issue.

**Comment by ruvceskistefan** [comment]
Hi @slee-accesso,
Unfortunately, I will close this issue for now. This issue does not seem to be a problem with the runner application, so I'll report the problem to the powershell teams, and we'll see if they can solve the problem with the underlying commands.

**Comment by ruvceskistefan** [comment]
Here is the issue reported in the powershell repo: https://github.com/PowerShell/PowerShell/issues/16914
