### ISSUE TITLE
create-latest-svc.sh add support for enterprise

### ISSUE THREAD

**Issue by nikhil1290** [actions/runner#1552]
`create-latest-svc.sh` currently supports fetching token for an org or repo within an org. Please add support for running the service at an enterprise level.

```
-s          required  scope: repo (:owner/:repo) or org (:organization)
```

**Comment by TingluoHuang** [comment]
we are open to taking pull requests. 😄

**Comment by ethomson** [comment]
This seems like a reasonable enhancement, I agree.  This isn't something that we're going to be able to work on in the next few months, but as @TingluoHuang said, we're definitely open to a pull request.

**Comment by Righteousness666** [comment]
Maybe depends on the old request for an Apple echo.

**Comment by Righteousness666** [comment]
> `create-latest-svc.sh` currently supports fetching token for an org or repo within an org. Please add support for running the service at an enterprise level.
> 
> ```
> -s          required  scope: repo (:owner/:repo) or org (:organization)
> ```

![26227AA2-936C-4FFC-828F-52D288CC4BD7](https://user-images.githubusercontent.com/95431779/147418979-d93a35da-8d21-4d66-a254-05a537ae0671.jpeg)
![0F7F4F38-CF8C-4576-AF83-B8067674843A](https://user-images.githubusercontent.com/95431779/147418980-d19a4dc0-b839-417d-a1ab-88d50d9b6a8b.jpeg)
