### ISSUE TITLE
Unable to download the artifact. Error unexpected http 404 

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#1559]
**Describe the bug**
Action failed because it could not connect to github services to download an artifact. This never happened before. Probably some sort of instability, but this should never happen. Github Actions should retry up to N times before failing the action. Specially when it is a official action that downloads the artifact.

![Screenshot_20211215-194007_Opera](https://user-images.githubusercontent.com/55927613/146276296-0bd70eb4-156b-46ea-acf6-9d8b6affc9c3.jpg)

**To Reproduce**
1. Make the download artifact action to fail with 404.

**Expected behavior**
If any sort of connection error to github server while running a github action, the runner should retry the action up to N times before failing the entire action. This should not be handled by the developer.

## Runner Version and Platform
ubuntu-latest

OS of the machine running the runner?

## What's not working?
PS with the error is above

## Job Log Output
PS with the error is above

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by TingluoHuang** [comment]
The runner can't just retry all action since the underline action might not support retry. it might be a good feature to retry any given step based on user-config.
ex:
```yaml
- run: |
      do something...
  retry: 3
```

**Comment by AllanOricil** [comment]
I just think it is a bad design if you ask to every single action out there to implement a way of retrying an api call when an error happens. That is the reason I think the runner should intercept these calls and retry them. If not all, at least the ones that are to their own servers. It is not cool when you see a service failing because of their own instability. As a end user, if I see this happening I would switch over to a different provider

**Comment by ethomson** [comment]
@AllanOricil I agree that retrying should happen in this case, but I also agree that the runner shouldn't try to be the place where this logic happens.  The runner is a job executor, it doesn't have any insight into _what_ is running.  Nor do we have an opportunity to intercept outbound calls, short of trying to sniff https traffic.  It does seem like the artifact download action - https://github.com/actions/download-artifact - may want to add retry logic.  Would you be so kind as to open your issue there?

Many apologies that your workflow run failed here - I agree that we should improve this.  Thanks much.
