### ISSUE TITLE
Unable to parse reusable workflow owner and repository

### ISSUE THREAD

**Issue by paulineribeyre** [actions/runner#1562]
**Describe the bug**

**To Reproduce**
1. Create a reusable workflow A in repository `my-org/.github`, in directory `workflows`
2. Create a workflow B in another repository, with `uses: my-org/.github/workflows/A.yaml`
3. See error: `invalid value workflow reference: references to workflows must be prefixed with format 'owner/repository/'`
4. Move reusable workflow A to directory `.github/workflows`
5. Update workflow B with: `uses: my-org/.github/.github/workflows/A.yaml`
6. Now it works!

**Expected behavior**
I expected the owner (`my-org`) and repository (`.github`) in `uses: my-org/.github/workflows/A.yaml` to be parsed correctly.

## Runner Version and Platform
Default version/OS, running on github

## What's not working?
See above

## Job Log Output
```
Error : .github#L1
invalid value workflow reference: references to workflows must be prefixed with format 'owner/repository/'
```

## Runner and Worker's Diagnostic Logs
--

**Comment by TingluoHuang** [comment]
@paulineribeyre https://github.community/c/code-to-cloud/github-actions/41 might be a better place for this, the runner has limited knowledge about the workflow yaml schema.

**Comment by dhirschfeld** [comment]
I'm also running into this. Thanks for the workaround @paulineribeyre, though I agree it's sub-optimal.

Is there a discussion or issue I can follow to track any progress in fixing this bug?
