### ISSUE TITLE
`secrets.GITHUB_TOKEN` does not exist, but `github.token` does

### ISSUE THREAD

**Issue by girvel** [actions/runner#1573]
**Describe the bug**
`secrets.GITHUB_TOKEN` and `github.token` behave differently, though documentation says they dont.

When I try to pass `secrets.GITHUB_TOKEN` to workflow, i get an [error](https://github.com/girvel/tiny_storage/actions/runs/1607120343):
```
The workflow is not valid. .github/workflows/test.yaml (Line: 13, Col: 19): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.GITHUB_TOKEN
```
When I [replace](https://github.com/girvel/tiny_storage/commit/484a5add6c35f47dfeeba097d256ab6d42875488) `secrets.GITHUB_TOKEN` with `github.token`, i [dont](https://github.com/girvel/tiny_storage/actions/runs/1607160122) get this error.

**To Reproduce**
1. There is an [error](https://github.com/girvel/tiny_storage/actions/runs/1607120343)
2. I [replace](https://github.com/girvel/tiny_storage/commit/484a5add6c35f47dfeeba097d256ab6d42875488) `secrets.GITHUB_TOKEN` with `github.token`
3. Error is [gone](https://github.com/girvel/tiny_storage/actions/runs/1607160122)

**Expected behavior**
According to the [documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication), `secrets.GITHUB_TOKEN` should always exist.

## Runner Version and Platform
Default github runner

## What's not working?
The workflow is not valid. .github/workflows/test.yaml (Line: 13, Col: 19): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.GITHUB_TOKEN

## Job Log Output
-

## Runner and Worker's Diagnostic Logs
-

**Comment by TingluoHuang** [comment]
https://github.community/c/code-to-cloud/52 would be a better place for this question, the runner doesn't have knowledge about callable workflow.

**Comment by ajaykn** [comment]
@girvel, Please raise questions regarding reusing workflows at https://github.community/c/code-to-cloud/52 as @TingluoHuang mentioned.

Sharing the solution here for time being.
Regarding your workflow, 
You have defined, `REPO_TOKEN` as secret in called workflow. 
```code
on:
  workflow_call:
    secrets:
      REPO_TOKEN:
        required: true
        ```
  so if you want to pass the value from caller wf, you need to pass it as `jobs.<job_id>.secrets`
  https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idsecrets
  Where as you were trying to pass as `hobs.<job_id>.with` which is valid for inputs.
 
 And for inputs, we can use either `github or needs` context. but not `secrets` context.
 https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability.
 
 If you have any further questions, please post/reach out via [community thread](https://github.community/c/code-to-cloud/52).
