### ISSUE TITLE
Documentation updates around liblttng-ust0

### ISSUE THREAD

**Issue by myoung34** [actions/runner#1584]
**Describe the enhancement**

Documentation around the `liblttng-ust0` package requirement

The issue is that debian (specifically sid and the upcoming bookworm) are moving to `liblttng-ust1` vs `liblttng-ust0`
Im having to add some logic around which one to install but Im not sure what needs this under the hood and if the difference in whatever uts1 vs uts0 is, but this will likely cause issues for other actions project maintainers

**Code Snippet**

https://github.com/myoung34/docker-github-actions-runner/blob/master/Dockerfile.base#L48

**Comment by kaiwegner** [comment]
For now I have to switch to an older distro because of this 👎

**Comment by nyarly** [comment]
Likewise

**Comment by WoodyWoodsta** [comment]
Have the same issue:

```
Reading state information...
E: Unable to locate package liblttng-ust0
'apt-get' failed with exit code '0'
Can't install dotnet core dependencies.
```

**Comment by myoung34** [comment]
Youre all using `2.293.0` which was released 11 days ago.
The fix for this (https://github.com/actions/runner/pull/1946) was made 6 days ago

It's not been backported. You'll need to wait for a new version to come out to get a new `installdependencies.sh`

**Comment by myoung34** [comment]
@chingc v2.294.0 is out so this should be resolved now

**Comment by chingc** [comment]
@myoung34 I just tried the new version and no longer run into the issue.  Thank you!

**Comment by Bigpet** [comment]
> Hi @chingc , how where you able to solve this issue, as i am still stuck in it.

You need to install liblttng-ust1 with newer Ubuntu/Debian versions. The runner scripts should be able to use either
