### ISSUE TITLE
Ubuntu: serial console didnt work properly

### ISSUE THREAD

**Issue by ebattat** [actions/runner#1586]
**Describe the bug**

**To Reproduce**
1. We are running our container through GitHub action ubuntu20
2. Run 'virtctl console'
3. Notice that only 80% from the output is capture instead of 100% logs

**Expected behavior**
Not capture all the vm logs due to missing configuration.
When running the same on Centos8 all working properly and get 100% log.

## Runner Version and Platform
Version of your runner? latest 

OS of the machine running the runner? Linux

## What's not working?
Not get any error, just missing configuration cause to the log cut in the middle of run

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by TingluoHuang** [comment]
Any log or trace that can show the difference so we can check?

**Comment by ebattat** [comment]
Sorry. I run it through my container.
The current status is when running my container that run virtctl console from centos8 - 100% of log capture
But when running same container that run virtctl console from GitHub actions Ubuntu - first 80% of log capture
We need to configure serial console for it:
https://help.ubuntu.com/community/SerialConsoleHowto
Do you have any idea how can we configure it in GitHub action Ubuntu machine ?

**Comment by TingluoHuang** [comment]
https://github.com/actions/virtual-environments manage the hosted VM image, maybe they can provide some help. 🙇

**Comment by ebattat** [comment]
Sorry, didnt get you. Can I get Ubuntu image with those changes ?

**Comment by TingluoHuang** [comment]
Sorry, my fault, didn't read your question right. 😢 
I think the answer is NO, and if you want to use centos you might need to set up a self-hosted runner on your own hardware.

**Comment by nikola-jokic** [comment]
I am closing this issue since it is not related to the runner itself. Since we use this issue tracker to track bugs in the runner application itself, this is best served by https://github.community/c/code-to-cloud/52
