### ISSUE TITLE
Prefer node16 over node12 when running internal js script in runner

### ISSUE THREAD

**Issue by TingluoHuang** [actions/runner#1590]
The runner has packaged node 16 now, we should start using it to run any internal script the runner owns.

- RunnerService.js
- Hashfiles.js
- etc...

Running user scripts (actions) is covered by https://github.com/github/c2c-actions-runtime/issues/1585

**Comment by nikola-jokic** [comment]
Hi @TingluoHuang,

Since this [commit](https://github.com/actions/runner/commit/bd77ccf34e0bae95085d78dd1d22c91b9d0db68b) has been merged to the main branch, do you think it is now safe to close this issue?

**Comment by TingluoHuang** [comment]
https://github.com/actions/runner/pull/1621
