### ISSUE TITLE
strategy.matrix does not pass variables / secrets into workflow

### ISSUE THREAD

**Issue by vbohn-nelnet** [actions/runner#1591]
**Describe the bug**
When trying to include variables such as secrets in the strategy.matrix, the job fails with an "Invalid Workflow file error."

**To Reproduce**
Use the example from the Context and Expression syntax guide from the GitHub Actions docs (https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6)
Push up to any repo
The workflow file error will come up immediately

`    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
          scope: **************
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_READ_TOKEN }}
      - name: Run bootstrap
        run: npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_READ_TOKEN }}
      # Connect to VPN
      - name: Connect to VPN
        run: .github/vpn/vpn-connect.sh
        env:
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      - name: Configure Testing Credentials for Dev and Test Environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ matrix.aws-access-key-id }}
          aws-secret-access-key: ${{ matrix.aws-secret-access-key }}
          aws-region: us-west-2
      - name: Run flow tests on Dev
        run: npm run flow
      - name: Run e2e tests on Dev
        run: npm run e2e
        # Post to Teams channel on success
      - name: Send notification to Teams if scan passes
        if: ${{ success() }}
        run: 'curl -H ''Content-Type: application/json'' -d ''{"text": "The latest E2E Scan on ${{ matrix.env }} has passed"}'' ${{ secrets.SCHEDULED_E2E_TEAMS_ENGINEERING_WEBHOOK }}'
        #Send PagerDuty Alert upon failure
      - name: Send notification to PagerDuty if scan fails
        if: ${{ failure() }}
        run: ./node_modules/.bin/create-failed-check-pagerduty-event --check-type=E2E_TESTING --severity=warning
        env:
          PAGERDUTY_INTEGRATION_KEY: ${{ secrets.PAGERDUTY_GITHUB_INTEGRATION_KEY }}`

**Expected behavior**
Github should run both workflows with respective variables being passed in simultaneously.

## Runner Version and Platform
Version of your runner? ubuntu-latest

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
The error text is:
"Invalid workflow file
You have an error in your yaml syntax on line ___"

## Job Log Output
No diagnostic logs available

**Comment by TingluoHuang** [comment]
https://github.community/c/code-to-cloud/52 is a better location for support this, the runner doesn't have knowledge about the workflow YAML.
