### ISSUE TITLE
Internal/Private repo actions not functioning although repo option is set properly

### ISSUE THREAD

**Issue by timharris777** [actions/runner#1597]
Recently found this option in repositoing settings > actions
<img width="824" alt="image" src="https://user-images.githubusercontent.com/1483834/148579248-7109a306-1351-4605-87eb-41d8a7fff4e8.png">

Set it to org access as seen in the screenshot.

I tried to run the action directly from another repos workflow but it failed saying:
```
Download action repository '<org-removed>/<repo-removed>@master' (SHA:0543e0509f1b2b87c304e1789859bad624b9fabd)
32
Error: An action could not be found at the URI 'https://api.github.com/repos/<org-removed>/<repo-removed>/tarball/0543e0509f1b2b87c304e1789859bad624b9fabd'
```

Seems like I'm not the only one in the community that has run into this: https://github.community/t/github-action-action-in-private-repository/16063/76?u=timharris777

**Comment by floriank** [comment]
Just tried this out myself - setting up an action in repository A doesn't seem to be picked up in a Workflow in repository B:

```
// runner output in repo B
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve action `<removed>/<removed>@v0`, repository not found
```
Would be really nice if that worked :(

**Comment by mkrakowitzer** [comment]
Same here, I am able to share composite workflows, but not internal actions.
```
Getting action download info
Download action repository 'XXX/YYY@master' (SHA:107e288924a6b0be9e41e289c660d75ccaea3da2)
Error: An action could not be found at the URI 'https://api.github.com/repos/XXX/YYY/tarball/107e288924a6b0be9e41e289c660d75ccaea3da2'
```

**Comment by ricCap** [comment]
The option you set is for reusable workflows, not for actions.

If I did not miss anything, to use actions from internal/private repositories you still first need to check out the repo. Here's the documentation https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-an-action-inside-a-different-private-repository-than-the-workflow

There is an open ticket in the Github roadmap for using actions from internal repos https://github.com/github/roadmap/issues/74

**Comment by timharris777** [comment]
Latest announcement on changelog: https://github.blog/changelog/2022-01-21-share-github-actions-within-your-enterprise/

**Comment by Drowze** [comment]
> Latest announcement on changelog: https://github.blog/changelog/2022-01-21-share-github-actions-within-your-enterprise/

That's promising! It looks though that it is still limited to enterprise internal (not private) repositories. I believe internal repositories are available for on-prem enterprise GitHub, right? (in my usecase, we have an enterprise GitHub organization account, but we do not have an active GitHub on-prem)

**Comment by timharris777** [comment]
We do not have on-prem and it's working for us. All of the repos in our org are set to internal by default. I swapped on of the repos to private and I can confirm that it does not work. Switching it back to internal had it functioning properly again.

**Comment by uilton-oliveira** [comment]
@Drowze for our organization the internal repo visibility is not available as well... i contacted the support to ask why, since it looks like that it is available to some organizations...

**Comment by Drowze** [comment]
Hey @uilton-oliveira thanks for letting me know - please keep us posted :)

**Comment by uilton-oliveira** [comment]
> Hey @uilton-oliveira thanks for letting me know - please keep us posted :)

Based on support reply, internal repo is only available if you have Enterprise account, which is different from Enterprise organization, and it's more expensive, since it's billed annually and in pack of 10 licenses :(

**Comment by nikola-jokic** [comment]
Hi everyone,

I am sorry but I will have to close this issue since it is not related to the runner itself. We try to keep issues related to this repository and the runner itself. All issues related to the platform generally, should be posted on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team or feedback in this case 😊

**Comment by seunggabi** [comment]
I found it!

### Guide
- add collaborator `@my_bot` in `my-repo`
- create PAT `@my_bot`
- add `secrets.MY_BOT_PAT` int your `my-org`.

```yaml
jobs:
  annotaions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: my-org/my-repo
          ref: v1.0.0
          token: ${{ secrets.MY_BOT_PAT }}
          path: ./.github/actions/my-repo
      - name: action
        uses: ./.github/actions/my-repo 
```

### `./.github/actions/my-repo` has ` ./.github/actions/my-repo/action.yaml` or `./.github/actions/my-repo/action.yml`

**Comment by htpaf** [comment]
As I found this issue while searching for 

`
Unable to resolve action 'org/repo-with-wanted-action-definition', repository not found
`

it might help others that the token used did not have permission for "internal" repository but only "private" (probably and org level secret/token). After changing the repository from "internal" to "private" the error when away and the workflow could access and download the action.

**Comment by edtaupier** [comment]
@htpaf thank you for this. I don't really understand why the visibility of the calling repository should have any effect on its ability to call a shared action in another repo. The action permissions configured on the shared actions repo should be the only requirement I would think.
