### ISSUE TITLE
Unable to connect self hosted runner to github

### ISSUE THREAD

**Issue by nsagark** [actions/runner#1603]
Issue: 
I am trying to use a self hosted runner which is a ubuntu machine. This machine was used before as a self hosted runner for one of the repositories. However even after cleanup when I try to execute run.sh to connect it to github, I keep getting below error. Please suggest how I can connect this machine to github and use it as self hosted runner. I did validate that there were no active sessions running when I ran run.sh

Output after cleanup:

root@nirmata:~/actions-runner# ./config.sh remove --token 

# Runner removal

√ Runner removed successfully
√ Removed .credentials
√ Removed .runner

root@nirmata:~/actions-runner# ./run.sh

√ Connected to GitHub

A session for this runner already exists.
2022-01-12 00:32:27Z: Runner connect error: The actions runner lab_ubuntu already has an active session for owner nirmata.. Retrying until reconnected.

√ Connected to GitHub

A session for this runner already exists.

√ Connected to GitHub

A session for this runner already exists.

√ Connected to GitHub

A session for this runner already exists.

√ Connected to GitHub

A session for this runner already exists.

√ Connected to GitHub

A session for this runner already exists.

**Comment by TingluoHuang** [comment]
@nsagark try `ps -aux | grep runner` to see where is the other runner.listener process and kill it.

**Comment by nsagark** [comment]
@TingluoHuang : I saw below 2 processes running. I killed them and restart the process of adding my self hosted runner again. However I still the same error. Is there anything else we can check to make sure everything cleaned up properly?

root@nirmata:~/actions-runner# ps -aux | grep runner
root      337543  0.0  0.0   6432   668 pts/0    S+   03:46   0:00 grep --color=auto runner
root     2196382  0.0  0.0   6972  3228 ?        Ss    2021   0:00 /bin/bash /root/actions-runner/runsvc.sh

root@nirmata:~/actions-runner# ./run.sh

√ Connected to GitHub

A session for this runner already exists.
2022-01-12 03:47:33Z: Runner connect error: The actions runner lab already has an active session for owner nirmata.. Retrying until reconnected.

√ Connected to GitHub

A session for this runner already exists.

√ Connected to GitHub

A session for this runner already exists.

√ Connected to GitHub

A session for this runner already exists.

√ Connected to GitHub

A session for this runner already exists.

√ Connected to GitHub

A session for this runner already exists.

√ Connected to GitHub

A session for this runner already exists.

**Comment by TingluoHuang** [comment]
@nsagark you have a service configured.
`/bin/bash /root/actions-runner/runsvc.sh`

you might want to uninstall the service first.
maybe try `sudo ./svc.sh uninstall`

**Comment by nsagark** [comment]
Tried to uninstall it but looks like its already uninstalled

root@nirmata:~/actions-runner# ./svc.sh uninstall
Service actions.runner.nsagark-kyverno-demo.lab.service is not installed

**Comment by TingluoHuang** [comment]
@nsagark try `systemctl --type=service` and see if you have the runner running as service.
and then `systemctl stop <name>` to stop it.

**Comment by nsagark** [comment]
I did see a runner service which was in failed state. I did a cleanup of the runner service using below. However I still see the same error when I try to run the run.sh. Also tried to do a fresh install but still the same. 

https://superuser.com/questions/513159/how-to-remove-systemd-services

**Comment by nsagark** [comment]
Is there any recommended way to cleanup the previous runner service?

**Comment by TingluoHuang** [comment]
@nsagark config a new runner with a different name will unblock you.

**Comment by TingluoHuang** [comment]
you can also manually remove all the system-d files the runner generated if you really want to clean up the bad runner service.

**Comment by ruvceskistefan** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!

**Comment by gitcos** [comment]
I'm having the same problem, but on a mac, so it's not systemd.

```
% ./run.sh

√ Connected to GitHub

A session for this runner already exists.
2022-03-28 18:25:04Z: Runner connect error: The actions runner MIN-7611 already has an active session for owner MIN-7611.. Retrying\
 until reconnected.
```

No runner process is currently running (I checked with ps auxww | grep -i runner).

Since this same runner was working earlier today, I assume this is a session from earlier today from this same mac.  I had to reboot the Mac to install macOS updates, so I'm sure it's not still running anything from a previous session.  Is there any way to clear out that session somehow, from the client side?

**Comment by Sandeepb-nextcar** [comment]
Is this resolved ?  I see runner and svc running 
ps -ef | grep runner
runner       1     0  0 20:16 ?        00:00:00 /usr/local/bin/dumb-init -- startup.sh
runner       7     1  0 20:16 ?        00:00:00 /bin/bash /usr/local/bin/startup.sh
runner     454     7  0 20:16 ?        00:00:00 /bin/bash /runner/bin/runsvc.sh
runner     934   454  0 20:16 ?        00:00:00 ./externals/node12/bin/node ./bin/RunnerService.js
runner     941   934  0 20:16 ?        00:00:02 /runner/bin/Runner.Listener run --startuptype service
runner    1238     0  0 20:20 pts/0    00:00:00 sh -c clear; (bash || ash || sh)
runner    1245  1238  0 20:20 pts/0    00:00:00 sh -c clear; (bash || ash || sh)
runner    1246  1245  0 20:20 pts/0    00:00:00 bash
runner    1259  1246  0 20:20 pts/0    00:00:00 ps -ef
runner    1260  1246  0 20:20 pts/0    00:00:00 grep --color=auto runner
runner@nxcr-runner-25k44-nf29b:/$

**Comment by ruvceskistefan** [comment]
Hi @Sandeepb-nextcar,
Did you try to kill those runner processes or to stop runner service?

**Comment by onursokullu** [comment]
I was encountring the same issue on a Windows machine. Stoping the Github Actions Runner from services solved it for me. 

![gh-actions](https://github.com/actions/runner/assets/27517245/828fb2df-f450-4d2a-b385-1196e7ec988d)

**Comment by aldo-ramirez-G** [comment]
> @nsagark try `ps -aux | grep runner` to see where is the other runner.listener process and kill it.

on mac Terminal was able to execute without the dash in front of the aux `ps aux | grep runner`

**Comment by nileshgadgi** [comment]
I'm getting the same issue:

```
Jan 13 19:00:11 demo-sonarqube-vm bash[176956]: 2025-01-13 19:00:11Z: Runner connect error: The actions runner test-github-runner-org already has an active session.. Retrying until reconnect>
Jan 13 19:00:41 demo-sonarqube-vm bash[176956]: √ Connected to GitHub
Jan 13 19:00:41 demo-sonarqube-vm bash[176956]: A session for this runner already exists.
Jan 13 19:01:11 demo-sonarqube-vm bash[176956]: √ Connected to GitHub
Jan 13 19:01:11 demo-sonarqube-vm bash[176956]: A session for this runner already exists.
Jan 13 19:01:41 demo-sonarqube-vm bash[176956]: √ Connected to GitHub
Jan 13 19:01:41 demo-sonarqube-vm bash[176956]: A session for this runner already exists.
Jan 13 19:02:11 demo-sonarqube-vm bash[176956]: √ Connected to GitHub
Jan 13 19:02:11 demo-sonarqube-vm bash[176956]: A session for this runner already exists.
Jan 13 19:02:41 demo-sonarqube-vm bash[176956]: √ Connected to GitHub
Jan 13 19:02:41 demo-sonarqube-vm bash[176956]: A session for this runner already exists.
Jan 13 19:03:11 demo-sonarqube-vm bash[176956]: √ Connected to GitHub
Jan 13 19:03:12 demo-sonarqube-vm bash[176956]: A session for this runner already exists.
Jan 13 19:03:42 demo-sonarqube-vm bash[176956]: √ Connected to GitHub
Jan 13 19:03:42 demo-sonarqube-vm bash[176956]: A session for this runner already exists.
Jan 13 19:03:42 demo-sonarqube-vm bash[176956]: Stop retry on SessionConflictException after retried for 240 seconds.
Jan 13 19:03:42 demo-sonarqube-vm bash[176956]: Failed to create session. The actions runner test-github-runner-org already has an active session.
Jan 13 19:03:42 demo-sonarqube-vm bash[176952]: Runner listener exit with Session Conflict error, stop the service, no retry needed.
Jan 13 19:03:42 demo-sonarqube-vm bash[176948]: Exiting runner...
Jan 13 19:03:42 demo-sonarqube-vm systemd[1]: github-runner.service: Succeeded.
Jan 13 19:03:45 demo-sonarqube-vm systemd[1]: github-runner.service: Scheduled restart job, restart counter is at 95.
Jan 13 19:03:45 demo-sonarqube-vm systemd[1]: Stopped nileshgadgi github action runner at organization level..
Jan 13 19:03:45 demo-sonarqube-vm systemd[1]: Started nileshgadgi github action runner at organization level..
Jan 13 19:03:46 demo-sonarqube-vm bash[178314]: √ Connected to GitHub
Jan 13 19:03:46 demo-sonarqube-vm bash[178314]: A session for this runner already exists.
Jan 13 19:03:46 demo-sonarqube-vm bash[178314]: 2025-01-13 19:03:46Z: Runner connect error: The actions runner test-github-runner-org already has an active session.. Retrying until reconnect>
```

@ruvceskistefan @TingluoHuang any idea what could be the solution of this issue, workflow cannot be stated and linux runner is stucked here, showing above error called "runner already has an active session.. Retrying until reconnect"

**Comment by mmitchel** [comment]
this happened to me following a kernel panic. how long does github take to timeout and bring the server end down?

**Comment by jordanspvsoz** [comment]
Like others here we are running into the same issue. Similar output:

`./run.sh 

√ Connected to GitHub

A session for this runner already exists.
2025-01-28 03:08:55Z: Runner connect error: The actions runner $HOSTNAME already has an active session.. Retrying until reconnected.`

This is without having the systemd service installed or enabled. Only fix was to completely uninstall and remove the runner and reinstall which is not a very scalable solution.

**Comment by paigeadelethompson** [comment]
great

**Comment by paigeadelethompson** [comment]
wonderful
