### ISSUE TITLE
selfhosted runner version 2.278.0 can't be picked 

### ISSUE THREAD

**Issue by stardustman** [actions/runner#1604]
**Describe the bug**
the selfhosted runner can not pick up a job

**To Reproduce**
1. install a runner version 2.278.0
2. run a job on this runner
3. the job can't be picked by this runner

**Expected behavior**

## Runner Version and Platform
2.278

OS of the machine running the runner? OSX/Windows/Linux/...
Linux
## What's not working?
```
Jan 12 15:49:52 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: √ Connected to GitHub
Jan 12 15:49:54 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Current runner version: '2.285.1'
Jan 12 15:49:54 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: 2022-01-12 07:49:54Z: Listening for Jobs
Jan 12 16:14:54 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner update in progress, do not shutdown runner.
Jan 12 16:14:54 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Downloading 2.286.0 runner
Jan 12 16:50:28 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: An error occurred: Runner package '/root/actions-runner/_work/_update/runner1.tar.g
Jan 12 16:50:28 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner listener exited with error code 2
Jan 12 16:50:28 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner listener exit with retryable error, re-launch runner in 5 seconds.
Jan 12 16:50:33 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Starting Runner listener with startup type: service
Jan 12 16:50:33 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Started listener process, pid: 22965
Jan 12 16:50:35 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: √ Connected to GitHub
Jan 12 16:50:37 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Current runner version: '2.285.1'
Jan 12 16:50:37 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: 2022-01-12 08:50:37Z: Listening for Jobs
Jan 12 17:07:47 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner update in progress, do not shutdown runner.
Jan 12 17:07:48 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Downloading 2.286.0 runner
Jan 12 17:11:06 ip-172-31-45-111.cn-northwest-1.compute.internal systemd[1]: Stopping GitHub Actions Runner (juzibot.test-deploy)...
```

## Job Log Output

> Jan 12 19:11:51 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[30232]: Downloading 2.286.0 runner

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

##  journalctl -u actions.runner.juzibot.test-deploy.service --since '2022-01-12 03:57:49'

> Jan 12 15:12:08 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: √ Connected to GitHub
Jan 12 15:12:10 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Current runner version: '2.285.1'
Jan 12 15:12:10 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: 2022-01-12 07:12:10Z: Listening for Jobs
Jan 12 15:22:01 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner update in progress, do not shutdown runner.
Jan 12 15:22:02 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Downloading 2.286.0 runner
Jan 12 15:49:45 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: An error occurred: Runner package '/root/actions-runner/_work/_update/runner1.tar.g
Jan 12 15:49:45 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner listener exited with error code 2
Jan 12 15:49:45 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner listener exit with retryable error, re-launch runner in 5 seconds.
Jan 12 15:49:50 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Starting Runner listener with startup type: service
Jan 12 15:49:50 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Started listener process, pid: 2081
Jan 12 15:49:52 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: √ Connected to GitHub
Jan 12 15:49:54 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Current runner version: '2.285.1'
Jan 12 15:49:54 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: 2022-01-12 07:49:54Z: Listening for Jobs
Jan 12 16:14:54 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner update in progress, do not shutdown runner.
Jan 12 16:14:54 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Downloading 2.286.0 runner
Jan 12 16:50:28 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: An error occurred: Runner package '/root/actions-runner/_work/_update/runner1.tar.g
Jan 12 16:50:28 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner listener exited with error code 2
Jan 12 16:50:28 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner listener exit with retryable error, re-launch runner in 5 seconds.
Jan 12 16:50:33 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Starting Runner listener with startup type: service
Jan 12 16:50:33 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Started listener process, pid: 22965
Jan 12 16:50:35 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: √ Connected to GitHub
Jan 12 16:50:37 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Current runner version: '2.285.1'
Jan 12 16:50:37 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: 2022-01-12 08:50:37Z: Listening for Jobs
Jan 12 17:07:47 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Runner update in progress, do not shutdown runner.
Jan 12 17:07:48 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: Downloading 2.286.0 runner
Jan 12 17:11:06 ip-172-31-45-111.cn-northwest-1.compute.internal systemd[1]: Stopping GitHub Actions Runner (juzibot.test-deploy)...

**Comment by ethomson** [comment]
This line appears truncated:

```
Jan 12 16:50:28 ip-172-31-45-111.cn-northwest-1.compute.internal runsvc.sh[3366]: An error occurred: Runner package '/root/actions-runner/_work/_update/runner1.tar.g
```

Can you provide the full error message?

**Comment by stardustman** [comment]
how to set the self-hosted runner don't try to upgrade when the installed version is not latest?

**Comment by stardustman** [comment]
I have met this error again. could I choose not to upgrade the runner version?

**Comment by stardustman** [comment]
Feb 07 11:21:54 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: An error occurred: Runner package 'https://github.com/actions/runner/releases/download/v2.287.1/actions-runner-linux-x64-2.287.1.tar.gz' failed after...nload attempts
Feb 07 11:21:55 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: Runner listener exited with error code 2
Feb 07 11:21:55 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: Runner listener exit with retryable error, re-launch runner in 5 seconds.
Feb 07 11:22:00 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: Starting Runner listener with startup type: service
Feb 07 11:22:00 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: Started listener process, pid: 1790
Feb 07 11:22:02 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: √ Connected to GitHub
Feb 07 11:22:04 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: Current runner version: '2.286.1'
Feb 07 11:22:04 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: 2022-02-07 03:22:04Z: Listening for Jobs
Feb 07 11:22:08 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: Runner update in progress, do not shutdown runner.
Feb 07 11:22:08 ip-172-30-69-134.cn-northwest-1.compute.internal runsvc.sh[3097]: Downloading 2.287.1 runner

**Comment by stardustman** [comment]
when the runner try to upgrade itself, something error happens, how to close this feature?

**Comment by ethomson** [comment]
You can disable updates by passing the [`--disableupdate`](https://github.blog/changelog/2022-02-01-github-actions-self-hosted-runners-can-now-disable-automatic-updates/) parameter to the runner.  If you do this, you will need to upgrade the runner manually.

If looks the runner may not be able to communicate with GitHub to download the update?  Please make sure that you've reviewed the [documentation about runner communication with GitHub](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#communication-between-self-hosted-runners-and-github).

**Comment by stardustman** [comment]
Thanks a lot.

**Comment by nikola-jokic** [comment]
Hi @stardustman,

When you configure your runner with `--disableupdate`, change should be propagated to the service as well.

**Comment by nikola-jokic** [comment]
Hi @stardustman,

When you configure your runner, you pass the `--disableupdate`. That change should be propagated to your service as well.

**Comment by stardustman** [comment]
I found the `./run.sh --disableupdate` [in this doc](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#controlling-runner-software-updates-on-self-hosted-runners).
after executed this command, the runner start in foreground.
I need the run the `./svc.sh install` then execute `./svc.sh start` to let the runner running as a service.
I didn't find the `./svc.sh install` has the flag `--disableupdate`? so how to do it?
I notice if the runner version is to low, the github will not dispatch the job to the runner. @nikola-jokic

**Comment by nikola-jokic** [comment]
Hi @stardustman,

The documentation there is incomplete, and I will create a PR updating the docs. If you want to provide `--disableupdate` for your service, you should do it while configuring the runner. If you pass `--disableupdate` when you configure your runner, the service will be started with that flag just as you would invoke it with` ./run.sh --disableupdate`.

Thank you for spotting this! And you are right. Please refer to this [changelog](https://github.blog/changelog/2022-02-01-github-actions-self-hosted-runners-can-now-disable-automatic-updates/#:~:text=for%20compatibility%20with%20the%20github%20actions%20service%2C%20you%20will%20need%20to%20manually%20update%20your%20runner%20within%2030%20days%20of%20a%20new%20runner%20version%20being%20available.)

**Comment by stardustman** [comment]
I have another question: after reading the doc, if I disable autoupdate, I still need to update runner manually. if I didn't disable auto update, could I set the time such as at 04:00am when the runner need to update itself?  @nikola-jokic

**Comment by fhammerl** [comment]
The docs have been updated recently, make sure you use `--disableupdate` when configuring the runner `config.sh`, **not** when running it with `run.sh`. `--disableupdate` will then allow you to stick to a runner version until a newer one has been out for more than a month.

**Comment by nikola-jokic** [comment]
As of now, no. You would have to manually update your runner. The runner normally receives an update notification on a workflow event. Runner requires the service to send the information needed for the self-update. If you feel like it would be helpful to add this functionality, please post your feedback on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback) site which is actively monitored. Using the forum ensures that we route your problem to the correct team.

**Comment by stardustman** [comment]
ok, thanks a lot.
