### ISSUE TITLE
SELinux Enforcing stops systemd service from starting

### ISSUE THREAD

**Issue by krayon** [actions/runner#1606]
**Describe the bug**

When SELinux is Enforcing, scripts started by `systemd` need the `initrc_exec_t` context set. It is not currently.

**To Reproduce**

1. Have SELinux Enforcing;
2. Add a runner;
3. Run `./svc.sh install`
4. Observe that `systemd` failed to start the script:

    ```bash
    sudo grep -i denied /var/log/audit/audit.log|grep -i svc|tail -1|fold -s
    ```
    ```journald
    type=AVC msg=audit(1642053001.589:304): avc:  denied  { execute } for  
    pid=14114 comm="(unsvc.sh)" name="runsvc.sh" dev="vda1" ino=25325969 
    scontext=system_u:system_r:init_t:s0 
    tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0
    ```

**Expected behavior**

- `systemd` should be able to start the script.

## Runner Version and Platform

- Version: `2.278`
- OS: Linux (x64)

/cc: @mikedalton

**Comment by kgrzebien** [comment]
I think we could also update our diagnostics:
- Add information to esb-tools package if SELinux is turned on in the appliance
- Add check to [enterprise-diagnostic-scripts](https://github.com/github/enterprise-diagnostic-scripts/) to check files context.

**Comment by abhishek-CEQ** [comment]
Any update on this issue, when will it get resolved? I'm still facing this issue in current stable version.

**Comment by kcjones91** [comment]
> > Customer wrote in with similar behavior when attempting to use Actions self-hosted runner on CentOS 8, which was unblocked thanks to [@TingluoHuang](https://github.com/TingluoHuang)'s recommendation:
> > ```
> > sudo semanage fcontext --add --type initrc_exec_t /<fullpath>/runsvc.sh
> > restorecon -v /<fullpath>/runsvc.sh
> > sudo ./svc.sh start
> > sudo ./svc.sh status
> > ```
> 
> Can this information be posted in the documentation. It is quite handy to know about this

Does this work for you selinux enabled server

**Comment by jessie828** [comment]
> > > Customer wrote in with similar behavior when attempting to use Actions self-hosted runner on CentOS 8, which was unblocked thanks to [@TingluoHuang](https://github.com/TingluoHuang)'s recommendation:
> > > ```
> > > sudo semanage fcontext --add --type initrc_exec_t /<fullpath>/runsvc.sh
> > > restorecon -v /<fullpath>/runsvc.sh
> > > sudo ./svc.sh start
> > > sudo ./svc.sh status
> > > ```
> > 
> > Can this information be posted in the documentation. It is quite handy to know about this
> 
> Does this work for you selinux enabled server
> 

It did for me on Rocky Linux 8 and RHEL 8 ( I know they are practically the same)
