### ISSUE TITLE
More string functions available to expressions

### ISSUE THREAD

**Issue by andyli** [actions/runner#1608]
**Describe the enhancement**
The currently available [functions](https://docs.github.com/en/actions/learn-github-actions/expressions#functions) are pretty limited. Although in many cases, actions users can use shell scripting instead, but there are places where only expressions can be used. For example, setting top-level [`env:`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#env) variables, or setting a job's [`container:`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer) image. Particularly, we [need a `toLowerCase()` function to compute a repo's container registry name](https://github.community/t/additional-function-s-lowercase-uppercase/140632).

**Code Snippet**

I would propose adding some common string functions, borrowing from the [JS string methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#instance_methods):

 * replaceAll(input, searchFor, replaceWith)
 * substring(input, indexStart [, indexEnd])
 * toLowerCase(input)
 * toUpperCase(input)
 * trim(input)

**Additional information**
It was mentioned there is a desire to have some more string manipulation functions in https://github.com/actions/runner/issues/1288#issuecomment-997009573

**Comment by TingluoHuang** [comment]
Please report this to https://github.community/c/code-to-cloud/github-actions/41
