### ISSUE TITLE
Multiline Secrets in add-mask are not supported and do not fail

### ISSUE THREAD

**Issue by thboop** [actions/runner#161]
The add mask command encoded data and decodes it before registering it as a secret. A user can send an encoded multiline secret to the add-mask command, which it will then try to register as a single secret. Since we do our processing line by line, a multi-line secret will never mask as the secret masker works based on exact matches.

We should either explicitly fail when a multiline string is given, or split the string into individual secrets and mask all of those.

For now, we have updated the toolkit docs indicating it is not supported
https://github.com/actions/toolkit/pull/196

**Comment by bryanmacfarlane** [comment]
status?

**Comment by bryanmacfarlane** [comment]
I think we the toolkit makes it clear what is supported (and therefore not a bug)

**Comment by thboop** [comment]
Agreed, going to close this issue.
