### ISSUE TITLE
Runners suddenly failing to connect to postgres database

### ISSUE THREAD

**Issue by KathurimaKimathi** [actions/runner#1610]
**Describe the bug**

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by TingluoHuang** [comment]
Please include some logs or other information for helping us start the investigation.

**Comment by KathurimaKimathi** [comment]
Here are the logs:
```

**Comment by TingluoHuang** [comment]
@KathurimaKimathi do you mind checking `Is the server running on that host and accepting TCP/IP connections` as the error suggested?
The runner doesn't manage that database, you might need to debug the workflow or the action you are using.

**Comment by ruvceskistefan** [comment]
I regret that I'm going to close this issue - this is not related to the runner application, this is part of the overall service. Since we use this issue tracker to track bugs in the runner application itself, this is best served by https://github.community/c/code-to-cloud/52
