### ISSUE TITLE
Workflow is triggered three times

### ISSUE THREAD

**Issue by roscha444** [actions/runner#1620]
**Describe the bug**
I have a workflow file scheduled with following cronjob ( cron: "* 10 * * *" ). Today the workflows was triggered three times. Normally the workflow should triggered once. 

<img width="968" alt="image" src="https://user-images.githubusercontent.com/33632422/150326733-c199d368-18e5-4f9b-81e0-d8c783568ad4.png">

**To Reproduce**
1. Create new workflow file
2. Setup schedule with cron  "* 10 * * *"
3. Wait for execution

**Expected behavior**
One workflow run every day at 10 UTC

## Runner Version and Platform
GitHub.com

**Comment by TingluoHuang** [comment]
https://github.community/c/code-to-cloud/github-actions/41 will be a better place to ask for help for this.
the runner doesn't have context about how the scheduled job gets queued.
