### ISSUE TITLE
runner 2.287.0 cmd script issues

### ISSUE THREAD

**Issue by jeremyd2019** [actions/runner#1632]
1. can no longer run `run.cmd` when CWD not the same directory as `run.cmd`.  This seems to be due to https://github.com/actions/runner/blob/dc8b1b685faef0e887139b219d10564aa1ac7502/src/Misc/layoutroot/run.cmd#L22 not being `copy "%~dp0run-helper.cmd.template" "%~dp0run-helper.cmd" /Y`.  result seems to be an infinite loop of failure.
2. running `run.cmd --help` exits my interactive cmd session.  It appears that https://github.com/actions/runner/blob/dc8b1b685faef0e887139b219d10564aa1ac7502/src/Misc/layoutroot/run.cmd#L30 should have been `exit /b 0` to avoid exiting the cmd that's running run.cmd.  Workaround: `cmd /c run.cmd --help`

**Comment by thboop** [comment]
Looking into this now, thank you for the report

**Comment by thboop** [comment]
We've gone ahead and reverted this change and released a new runner version `2.287.1`. We will will reintroduce once we fixed some of these issues you were seeing.

Thanks!
