### ISSUE TITLE
JavaScript Actions in Alpine containers... but on Debian

### ISSUE THREAD

**Issue by Vrtak-CZ** [actions/runner#1637]
**Describe the bug**
Hi, I'm running self-hosted runner (since GitHub does not support ARM) on ARM Ubuntu with Docker container and I'm using `actions/checkout@v2 (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)`. First of all i tried to use that with my Alpine Based image but got `JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64` on "Checkout repository". So I switched to Debian based image and got same message but now on "Post Checkout repository".

Also I tried to find a reason why JavaScript Actions on Alpine ARM are not supported but i was unable to find any information. I just found it was introduced 2 years ago in commit "First pass" (https://github.com/actions/runner/commit/19189065057f4287ebcf46b09cd4f0c0ea9aa692).

**To Reproduce**
1. Run self-hosted runner on ARM with container
2. `actions/checkout@v2 (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)`
3. See error on 

**Expected behavior**
I workd and do not report Alpine error on debian.

## Runner Version and Platform
2.287.1

OS of the machine running the runner? OSX/Windows/Linux/...
Ubuntu 20.04 - ARM with Docker 20.10.12

## What's not working?
`actions/checkout@v2 (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)` with `JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64` but on Debian image.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by ruvceskistefan** [comment]
Hi @Vrtak-CZ,
Thanks for reporting this issue! We will try to reproduce this issue and we will get back to you as soon as we can :)

**Comment by wakaztahir** [comment]
Please fix this

**Comment by laverdet** [comment]
> Please fix this

They're not going to fix it. I have an action that resolves the problem. [laverdet/alpine-arm64](https://github.com/laverdet/alpine-arm64)
