### ISSUE TITLE
Can not use powershell WSman module in default runners

### ISSUE THREAD

**Issue by dpopiashvili** [actions/runner#1638]
I need to use Powershell Remoting from my github runners to invoke custom functions on remote machine. First thing I did was an attempt to add target instance IP as a trusted host:
`Set-Item WSMan:\localhost\Client\TrustedHosts -value *`
However, this code throws `Object reference not set to an instance of an object`. The same command works fine locally and otherwise, I've never encountered NullReferenceException with WSMan commands.

I tried same command on windows-2016, windows-2019 and windows-2022 None have worked. I suppose WSMan module is broken in default github runner. Both `Set-WSManQuickConfig` and `Set-Item wsman:\localhost\Client\TrustedHosts -value *` throws NullReferenceExceptions, while `Get-Item WSMan:\...` seems to work fine. It seems any changes requested via WSman causes the exception. 

Here's the yaml:

```
Setup-test-Environment:
    runs-on: windows-2019
    steps:
      - name: Support longpaths        
        run: git config --system core.longpaths true

      - name: Setup dependencies
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PowerShellForGitHub
          Install-Module -Name AWSPowerShell
          Get-Item WSMan:\localhost\Client\TrustedHosts
          Set-WSManQuickConfig
          Set-Item wsman:\localhost\Client\TrustedHosts -value *
          
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: recursive          
          token: ${{ secrets.ENG_STD_TOKEN }}

      - name: Create test environment
        run: |
          .\pr-env\setup-qa-env.ps1 -pr ${{ github.run_number }} -container test

```

![image](https://user-images.githubusercontent.com/22319012/151582898-b8173430-819e-4ed4-86ab-54bbff2d205f.png)

Can this be fixed? We are forced to revert to self-hosted runner because of this.

Thanks

**Comment by TingluoHuang** [comment]
https://github.com/actions/virtual-environments might be a better place to report this issue, it has control over what gets installed on the GitHub Hosted runner.
🙇
