### ISSUE TITLE
Using github context with ToJson can overflow windows environment variables size limits

### ISSUE THREAD

**Issue by valadas** [actions/runner#1647]
**Describe the bug**
The github context is very close to the windows environment variables limits and a simple long PR description makes it overflow that limit and fail some builds. One good example is dependabot PRs which almost always have a long PR body.

**To Reproduce**
1. Create an action that runs MSBuild on PRs or similar that read environment variables with a windows-latest runner.
2. Do a PR with a short sentence in the body.
2. Use ${{ toJSON(github) }} in the yaml as documented but still on a windows runner.
3. In the build log, copy-paste the resulting json into some text editor such as VSCode.
4. Select it all and notice the size is around 322xx characters

I am not sure what the proper solution is but this is very close to the 32760 characters for windows environment variables. 
Either the documentation needs adjustments or there are way to much stuff in the github context for windows runners

**Expected behavior**
Using the documentation one should assume a windows build to not fail by following the documentation and a simple dependabot PR makes the build fail.

## Runner Version and Platform
I don't know how to get that...

OS of the machine running the runner? OSX/Windows/Linux/...
windows-latest (2019 at the moment of writing)

## What's not working?
Builds fail intermittently depending on the length of a PR body.

## Job Log Output
Here is one example of this happening https://github.com/valadas/MyModule20220129/runs/5016425469?check_suite_focus=true

## Runner and Worker's Diagnostic Logs
This is a github runner, not sure how to get that information...

**Comment by TingluoHuang** [comment]
I would not suggest dumping the entire `GITHUB` context into the env block. 
Why do you need the full `GitHub` context as env, if you only need the event payload, there is the `GITHUB_EVENT_PATH` point to a file we create on disk that contains the payload.

**Comment by valadas** [comment]
It is done like that using [nuke.build ](https://nuke.build/), when I reported the issue there, the reply I got was it was done following the documentation here https://docs.github.com/en/actions/learn-github-actions/contexts 

Now that I am re-reading this, I see it was not in the environment variables in the documentation.

@matkoch any thoughts on this ? I have a workaround so I am not stuck, just trying to figure out if there is anything to do here in this repo regarding the docs or I like the idea of reading that info from a file

@TingluoHuang , do yo have any documentation to point to or examples of what exists on that file ?

**Comment by nikola-jokic** [comment]
Hi @valadas,

Do you still have this issue?

**Comment by valadas** [comment]
@nikola-jokic well I think it's ok to close here, I'll try to do a PR for Nuke to read the file instead of using the environment variable. Thanks guys.
