### ISSUE TITLE
hashFiles fails silently when it encounters a broken symlink

### ISSUE THREAD

**Issue by BYK** [actions/runner#1666]
**Describe the bug**
When the pattern passed to `hashFiles()` matches a broken symlink (a symlink that points to a non-existent file), `hashFiles()` silently fails and produces an empty hash. Example: https://github.com/formsort/formsort/runs/5096669434?check_suite_focus=true#step:4:139

**To Reproduce**
1. Create a repo
2. Add a symlink to a non-existent file `ln -s bla bla`
3. Create a workflow that uses `hashFiles("**")` in it
4. Observe that the output of `hashFiles("**")` is empty witout any errors
5. Now enable step debug logging: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
6. Re-run the action
7. Observe the unhandled promise rejection error, silently being swallowed:
   ```
   ##[debug](node:1536) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/runner/work/[redacted]'
   ```

**Expected behavior**
`hashFiles` should either skip over broken symlinks or fail the whole job loudly, clearly indicating the error.

## Runner Version and Platform
Version of your runner?

GitHub-hosted Ubuntu 20.04

## Job Log Output
```
##[debug](node:1536) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/runner/work/[redacted]'
```

**Comment by ruvceskistefan** [comment]
Hi @BYK,
Thanks for the reported issue! Our team is trying to reproduce your issue, could you please replace the broken example link with valid one?

**Comment by BYK** [comment]
Hi @ruvceskistefan, thanks for the quick turn around. The link is not broken, it's just a private repo. I just assumed you folks had access to private repos for investigating these kinds of issues.

Do you need a repro repo instead?

**Comment by ruvceskistefan** [comment]
@BYK sorry, my bad. Yes, the repro repo would be great, that's the easiest way we can investigate reported issue and help you later.

**Comment by nikola-jokic** [comment]
Hi @BYK,

I reproduced the issue. Working on the fix so you don't have to bother creating an example repository 😊.

**Comment by BYK** [comment]
@nikola-jokic thanks a lot and sorry for the slow turn around on my end :)

**Comment by nikola-jokic** [comment]
Hi @BYK, don't worry about it 😊. Your issue description was good enough! I submitted a [PR](https://github.com/actions/runner/pull/1678) fixing this issue
