### ISSUE TITLE
windows-latest chrome version unavaliable in registry

### ISSUE THREAD

**Issue by Pavocracy** [actions/runner#1668]
**Describe the bug**
The chrome version is unavailable in the registry unless you open chrome for the first time. This was discovered when trying to use pythons webdriver-manager to handle running the correct version of chromedriver. it uses the `reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version` command to get the chrome version.
I added steps to my github workflow to manually open chrome with `Start-Process -FilePath 'C:\Program Files\Google\Chrome\Application\chrome.exe'` but sometimes it gets the version of chrome and other times it does not. Possibly due to the order that steps are run in? or a delay between chrome opening up properly and adding to the registry and the other workflow steps being run before that happens?

**To Reproduce**
1. use the windows-latest for a github action
2. run a python script that uses the webdriver-manager
3. observe the output "Current google-chrome version is UNKNOWN"

an example of the used workflow can be found [here](https://github.com/Pavocracy/leetscraper/blob/main/.github/workflows/pull_requests.yml) and the python script used can be found [here](https://github.com/Pavocracy/leetscraper/blob/main/src/leetscraper/leetscraper.py#L89)

**Expected behavior**
webdriver-manager should be able to get the chrome version without taking extra steps as chrome is installed by default on windows-latest image. ubuntu-latest and macos-latest do not have this same issue.

## Runner Version and Platform
2.287.1
windows-latest through github runners

## What's not working?
There actual error codes are related to my failed unit tests, But this is caused by having a mismatched chromedriver and chrome versions as webdriver-manager will get the latest chromedriver when it cant find the version of chrome.

The chrome version error is: `"Could not get version for google-chrome with the any command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version"`

## Job Log Output
[Job Log Output](https://www.adampavey.com/githublogs/job-log-output.txt)

## Runner and Worker's Diagnostic Logs
[Runner Diagnostic Logs](https://www.adampavey.com/githublogs/logs_32.zip)

**Comment by Pavocracy** [comment]
Also if there is a workaround to this issue i would really appreciate sharing it! As i stated, just trying to open chrome through powershell as a job step didnt work all the time. You can see in the logs one instance of windows-latest passed, but others failed.

**Comment by Pavocracy** [comment]
Just to confirm, it definitely seems like this is the issue. Adding a 60 second sleep after opening chrome manually before moving on with other run steps resulted in all of the windows-latest workflows passing [as seen here](https://github.com/Pavocracy/leetscraper/actions/runs/1810940667)

**Comment by ruvceskistefan** [comment]
Hi @Pavocracy,
Thanks for filing this issue! I'm reproducing it now and I'll get back to you as soon as possible!

**Comment by Pavocracy** [comment]
I realized I should of just put the repo steps as spin up a windows-latest image and check the registry for a chrome version. It shouldn't be available due to the image not having chrome ever opened. 

The python webdriver-manager library showing this error is just extra steps and how I discovered the issue.

**Comment by ruvceskistefan** [comment]
Hi @Pavocracy,
We investigated the problem you reported and found that it was not a runner related issue. This issue concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team.

**Comment by Pavocracy** [comment]
Done. The post can be [found here](https://github.community/t/windows-latest-chrome-version-unavaliable-in-registry/228789)

Thank you for your efforts in reproducing this bug and responding with the correct place to post this issue :)
