### ISSUE TITLE
Systemd service doesn't fail when runner listener crashes

### ISSUE THREAD

**Issue by bionade24** [actions/runner#1677]
Due to a permission issue the runner listener crashes, but the systemd service still shows up as running.
```
$ sudo systemctl status actions.runner.name-robotics-name_ci.image-build.service
● actions.runner.name-robotics-name_ci.image-build.service - GitHub Actions Runner (name-robotics-name_ci.image-build)
     Loaded: loaded (/etc/systemd/system/actions.runner.name-robotics-name_ci.image-build.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-02-09 20:37:58 UTC; 8min ago
   Main PID: 20082 (runsvc.sh)
      Tasks: 8 (limit: 18966)
     Memory: 6.6M
     CGroup: /system.slice/actions.runner.name-robotics-name_ci.image-build.service
             ├─20082 /bin/bash /home/gh_actions_runner/runsvc.sh
             └─20085 ./externals/node12/bin/node ./bin/RunnerService.js

Feb 09 20:45:57 image-build runsvc.sh[20085]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Feb 09 20:45:57 image-build runsvc.sh[20085]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Feb 09 20:45:57 image-build runsvc.sh[20085]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallo>
Feb 09 20:45:57 image-build runsvc.sh[20085]:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocati>
Feb 09 20:45:57 image-build runsvc.sh[20085]:    at GitHub.Runner.Common.HostTraceListener.CreatePageLogWriter()
Feb 09 20:45:57 image-build runsvc.sh[20085]:    at GitHub.Runner.Common.HostTraceListener..ctor(String logFileDirectory, String logFilePrefix, Int32 pageSizeLimit, Int32 retentionDays)
Feb 09 20:45:57 image-build runsvc.sh[20085]:    at GitHub.Runner.Common.HostContext..ctor(String hostType, String logFile)
Feb 09 20:45:57 image-build runsvc.sh[20085]:    at GitHub.Runner.Listener.Program.Main(String[] args)
Feb 09 20:45:57 image-build runsvc.sh[20085]: Runner listener exited with error code null
Feb 09 20:45:57 image-build runsvc.sh[20085]: Runner listener exit with undefined return code, re-launch runner in 5 seconds.
```
Version 287.1
The restart should be handled by systemd and not internally on Linux.

**Comment by ruvceskistefan** [comment]
Hi @bionade24,
Thanks for filing this issue! We are working on reproducing the issue, so we will get back to you as soon as we have more informations.

**Comment by bionade24** [comment]
> Hi @bionade24,
> 
> As you can see in the log, the process is not terminated. Runner listener exited with status code unknown, but the runner service will retry in 5 seconds again. So the service is still running - hence the status `Active: active (running)`. Service tries to restart the listener if an error like that occurs, so if the error is a temporary one, in a few retries, you will have the listener up and running, ready to accept requests.
> 
> I will now close this issue, but if you have any further questions, please feel free to comment here blush

Hi, the thing is the runner service never failed, retrying all the time and I was trying to figure out why the runner wasn't showing up in Github despite being active. It was quite a time until I read the log output and see it's actually failing, solving the issue then was easy. But that's IMHO not how it should be handled with systemd. It's may valid to retry starting the listener for your code, I haven't read it, but after some time you should fail and if you want to retry, let systemd handle the real restarts:

```
Restart=on-failure
RestartSec=5s
```
This way the real state of the process is shown everywhere while it still tries to restart itself, so systemd toolchain and alert setups monitoring the journal get triggered. 

As I said in the last sentence of my bugreport, I believe 
> The restart should be handled by systemd and not internally on Linux.

**Comment by nikola-jokic** [comment]
Hi @bionade24,

We have successfully merged a[PR](https://github.com/actions/runner/pull/1693) that could solve this problem. It will be a part of the next release. Thank you for submitting this issue 😊
