### ISSUE TITLE
GitHub Self-hosted Runner in Active state for longtime

### ISSUE THREAD

**Issue by GopikaV24** [actions/runner#1681]
**Describe the bug**
Our self-hosted Runners are in **active** status for a long time.

We have 3 jobs defined in the workflow. After the first job successfully completed, the runner is in **active** status for a long time. So the second job getting failed after 10mins of trying to connect the agent.

When we checked logs, showing below error,
```
2022-02-11 09:43:56Z: Runner connect error: The HTTP request timed out after 00:01:00.. Retrying until reconnected.
2022-02-11 09:45:22Z: Runner reconnected.
```

**Expected behavior**
The Agent needs to as **idle** once the first job is completed.

## Runner Version and Platform
2.287.1

OS of the machine running the runner? 
Ubuntu-18.04

## What's not working?
![image](https://user-images.githubusercontent.com/60219629/153597707-3ac76606-03f5-419e-a1b3-b9a62ee0d928.png)

**Comment by ruvceskistefan** [comment]
Hi @GopikaV24,
Thanks for the reported issue! Can you send us a `_diag log file` so we can investigate the problem? Please be sure that there is no sensitive information in it.

**Comment by GopikaV24** [comment]
```
 cat Worker_20220214-055149-utc.log
[2022-02-14 05:51:50Z INFO HostContext] No proxy settings were found based on environmental variables (http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY)
[2022-02-14 05:51:51Z INFO HostContext] Well known directory 'Bin': '/home/bin.2.287.1'
[2022-02-14 05:51:51Z INFO HostContext] Well known directory 'Root': '/home'
[2022-02-14 05:51:51Z INFO HostContext] Well known config file 'Credentials': '/home/.credentials'
```
When the second job is trying to connect agents in the pipeline, getting these logs only.

**Comment by GopikaV24** [comment]
@[ruvceskistefan](https://github.com/ruvceskistefan), Can you please help us on this?

**Comment by ruvceskistefan** [comment]
@GopikaV24 of course, I'm investigating the issue and coming back as soon as I have more information.

**Comment by ruvceskistefan** [comment]
I didn't have any problems executing the workflow with three simple jobs. I need more information to find out what the problem is. Can you send me the entire content of the diagnostic log file or is this what you previously sent everything in that file?

**Comment by GopikaV24** [comment]
We have our GitHub self-hosted agent configured in the AKS cluster as POD.

We are getting this is occasionally only. For example, in the below screenshot, the 8th run can't able to pick an agent, as the agent is in **active** state.
![image](https://user-images.githubusercontent.com/60219629/154092972-70d7910c-f5a1-4aaf-a405-f583bdc54162.png)

The 8th job has these logs only. I got a log based on timestamp. 
![image](https://user-images.githubusercontent.com/60219629/154094173-43f3c405-c81f-4811-bfd7-52f67a23d3c3.png)

**Comment by ruvceskistefan** [comment]
Thanks for the additional information. We will try to reproduce your problem and determine the cause, but it can be tricky, considering that the described situation happens occasionally. I'll get back to you as soon as I have more information

**Comment by thboop** [comment]
@GopikaV24 , our team is digging into this for you thanks for the report.

Can you please provide:
- the contents of the `SelfUpdate-` file, the `Runner_20220215-095745-utc.log` file and the `Runner_20220215-095156-utc.log`
- the url of the failed job
- What entrypoint are you using to run the GitHub actions runner application? `run.sh` may exit due to auto update. 
  - What are you doing if that exits, do you invoke it again automatically?

> the runner is in active status for a long

What makes you think the runner is in the `active` status? Does the UI show it running a job? Do you see that it has picked up the job locally?

**Comment by GopikaV24** [comment]
**Selfupdate file**
```
 cat SelfUpdate-20220215-095736.log.succeed
[2022-02-15 09:57:36-5287] --------whoami--------
root
[2022-02-15 09:57:36-7244] --------whoami--------
[2022-02-15 09:57:36-9230] Waiting for Runner.Listener (79) to complete
[2022-02-15 09:57:36-9926] Process 79 still running
[2022-02-15 09:57:39-1150] Process 79 finished running
[2022-02-15 09:57:39-1510] Sleep 1 more second to make sure process exited
[2022-02-15 09:57:40-1613] move /home/bin /home/bin.2.285.1
renamed '/home/bin' -> '/home/bin.2.285.1'
[2022-02-15 09:57:40-2090] move /home/externals /home/externals.2.285.1
renamed '/home/externals' -> '/home/externals.2.285.1'
[2022-02-15 09:57:40-2392] Create junction bin folder
[2022-02-15 09:57:40-2505] Create junction externals folder
[2022-02-15 09:57:40-2842] Update succeed
[2022-02-15 09:57:40-2870] Rename /home/_diag/SelfUpdate-20220215-095736.log to be /home/_diag/SelfUpdate-20220215-095736.log.succeed
renamed '/home/_diag/SelfUpdate-20220215-095736.log' -> '/home/_diag/SelfUpdate-20220215-095736.log.succeed'
```
**Runner_20220215-095745-utc.log**  in the specific timestamp.
![final issue- self](https://user-images.githubusercontent.com/60219629/154419431-6d41de9a-e54f-47d5-9d6a-a62f4d6078bd.PNG)

We have a pipeline in a Private Repository. So we can't share the pipeline URL.
UI showing like this only. When we checked agent status, it showed **Active**. But there are no other pipelines running in that agent.
![image](https://user-images.githubusercontent.com/60219629/154420166-7ea9530a-989b-46f0-acca-cfdac7833322.png)

We referred [this article ](https://sanderknape.com/2020/03/self-hosted-github-actions-runner-kubernetes/)to deploy selfhosted agent to create in AKS cluster.

**Comment by GopikaV24** [comment]
Hi @ruvceskistefan / @thboop,
Any updates on this?

**Comment by ruvceskistefan** [comment]
Hi @GopikaV24,
There is no updates from my side, we are still trying to find out what the problem is.

**Comment by GopikaV24** [comment]
@ruvceskistefan / @thboop,

Can you please help us with this? We are facing this issue again and again?

**Comment by thboop** [comment]
Hey @GopikaV24 you should have heard from our support team with some next steps on how to address this issue! 

Lets handle this issue via that support process, so we can safeguard your data, i'm going to close out this issue.

**Comment by starverdiyev** [comment]
We have got the same problem. @GopikaV24 you find decision for this issue?
