### ISSUE TITLE
Unexpected value for `github.event.pull_request.base.sha`

### ISSUE THREAD

**Issue by JensDll** [actions/runner#1689]
**Describe the bug**
In a workflow run on `pull_request`, the `github.event.pull_request.base.sha` does not always seem to be the real pull request base. At the time of opening the pull request, it will have the `SHA` of the latest commit in `base.ref`. That seems unexpected because really it should have the `SHA` of the commit since creating the branch, right?

**To Reproduce**
1. Create a workflow run on `pull_request`, logging the `github` context.
2. On some branch `a` create a new branch `b`.
3. Make commits on `a`.
4. Make commits on `b`.
5. Push the changes from `a`.
6. Push the changes from `b` and open a pull request.

Let's assume the history looks like below:
```text
a  0 --- 1 --- 2
b     +  3 --- 4
```
**Expected behavior**
`github.event.pull_request.base.sha` is `0`

**Actual behavior**
`github.event.pull_request.base.sha` is `2`

## Runner Version and Platform
Version of your runner?
`2.287.1`

OS of the machine running the runner?
GitHub-hosted `ubuntu-latest` version `20.04.3`

## Job Log Output
I recreated the steps above and described the behavior once more. Here is the pull request:
- https://github.com/JensDll/workflow-reproductions/pull/1

**Comment by nikola-jokic** [comment]
Hi @JensDll,

If I understood your question correctly, 0 is actually the base commit for this PR. What you would like to accomplish is to get 2 as the last commit of your branch, which could be easily pulled from `github.event.pull_request.head.sha`.
The base would be a common ancestor so to speak, and what you are trying to get is the SHA of the head of the branch you want to merge on.

I don't think that this is erroneous behaviour, but please correct me if I understood this problem incorrectly.

**Comment by JensDll** [comment]
Hi @nikola-jokic,

In my example 3 and 4 would be the commits of the pull request and 0 the base. 1 and 2 are changes made by someone else before I could open the PR on GitHub. Now since 0 is the base, I would expect its SHA to be `github.event.pull_request.base.sha`, but that's not the case: Its value is 2, the head commit of the ancestor branch (at the time of opening).

I would like to get the base to run a `git diff`. Of course, comparing commits 2 and 4 is not an accurate
representation of what's changed.

**Comment by JensDll** [comment]
Alright, I think I just realized that the `github.event` information is coming more or less straight from the GitHub REST API.
https://docs.github.com/en/rest/reference/pulls#get-a-pull-request
I do believe this is a bug but nothing related to the runner at least. Might start a discussion over at [github/feedback](https://github.com/github/feedback/discussions).

Anyways, closing this issue then. Thanks

**Comment by izaitsevfb** [comment]
@JensDll, I'm facing the same problem. Have you managed to find a solution or a workaround?

**Comment by JensDll** [comment]
@izaitsevfb Unfortunately, I did not follow up in any discussion after opening this. I remember finding other sources describing the same problem shortly after reporting here. For example, https://github.com/github/docs/issues/431 was one.

As for workarounds, it would require some manual git plumbing. For reference, [here is what you could use](https://github.com/JensDll/should-run/blob/main/.github/workflows/main.yaml#L54) to find the base and head commit of a pull request in the context of a GitHub Action.

It looks like there is now an open discussion about the topic on the Community forum: https://github.com/orgs/community/discussions/39880
