### ISSUE TITLE
PWSH on Windows Exits 1 When stderr streams are redirected

### ISSUE THREAD

**Issue by thboop** [actions/runner#169]
This is reproducible in a simple script 
```
run: |
  npm ping
  npm ping
  npm ping
```
We aren't sure the impact at this time, but it appears to be a power-shell bug. We should file an issue with reproduction for them to fix.

**Comment by bryanmacfarlane** [comment]
status?

**Comment by thboop** [comment]
Powershell 7 still is not released, but the release candidate is available. Once powershell is upgraded in the virtual environments we should verify the fix works and close this issue.

**Comment by thboop** [comment]
Powershell 7 is released and this is resolved in our Windows builds!
