### ISSUE TITLE
Overview of attempt seem to get info from other attempts

### ISSUE THREAD

**Issue by DanielNoord** [actions/runner#1696]
**Describe the bug**
_This is probably not the right place to report this, but I couldn't find the correct place to do so. Please close and direct me to the place where this should be openend._

The attempt overview seems to get data from other attempts than the one you're currently viewing.

**To Reproduce**
https://github.com/PyCQA/pylint/actions/runs/1863301639/attempts/1

In the above run attempt 1 timed out in the `pytest-linux` matrix on job `Linux 3.8`. However, when you click on `5 jobs completed` it actually shows the overview of attempt 2 in which the jobs did all pass. So, even though the rest of this page is showing attempt 1 and the initial view is showing attempt 1 as well, clicking on any of the matrices seems to show info from attempt 2.

**Expected behavior**
Get the data from attempt 1 and not from attempt 2.

## Runner Version and Platform
Irrelevant I think.

## What's not working?
/

## Job Log Output
/

## Runner and Worker's Diagnostic Logs
/

**Comment by ruvceskistefan** [comment]
Hi @DanielNoord,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃

**Comment by DanielNoord** [comment]
Posted [here](https://github.community/t/overview-of-attempt-seem-to-get-info-from-other-attempts/230323). Thanks @ruvceskistefan!
