### ISSUE TITLE
Inconsistent Environment on Linux

### ISSUE THREAD

**Issue by Fleshgrinder** [actions/runner#1703]
**Describe the bug**
The runner’s environment is populated with the contents of the `.env` file but ignores the operating system’s standard `/etc/environment` file. This leads to the situation that commands – depending on how they are invoked – see a different environment. This is most apparent with `sudo`.

**To Reproduce**
1. `echo 'ENV_TEST=true' >>/etc/environment` while building the runner
2. Run `env; sudo env` within an action executed with the runner that has the `/etc/environment` line
3. Notice that `ENV_TEST` is only available in `sudo`’s `env`

> 🔥 It is possible that this is an issue with https://github.com/actions-runner-controller/actions-runner-controller and not this project, I am here to find this out. 😉

**Expected behavior**
I would expect that every command’s environment is prepopulated with the values from `/etc/environment` since that is the operating system’s standard. I guess it could also make sense to argue in another direction, but then no program should ever see the values from `/etc/environment`; this is definitely going to be significantly harder to achieve than sourcing `/etc/environment` before `.env` in [`LoadAndSetEnv`](https://github.com/actions/runner/blob/be9632302ceef50bfb36ea998cea9c94c75e5d4d/src/Runner.Listener/Program.cs#L130-L157) so that `.env` overwrites anything in `/etc/environment`.

Note that the separation between `/etc/environment` and `.env` would also allow setting environment variables for all users and the runner user separately.

## Runner Version and Platform
All Linux versions are affected, and I am specifically coming from https://github.com/actions-runner-controller/actions-runner-controller/issues/1135.

**Comment by ruvceskistefan** [comment]
Hi @Fleshgrinder,
Thanks for filing this issue! We are investigating the bug you described, so we will get back to you as soon as we have more informations.

**Comment by TingluoHuang** [comment]
The runner will only have environment variables inherent from the current running process and load from `.env` files across all platforms, Windows/Linux/macOS.

```
echo 'ENV_TEST=true' >>/etc/environment
env; sudo env
printenv|sort  // I don't see ENV_TEST=true is loaded by printenv as well.
```

**Comment by Fleshgrinder** [comment]
@TingluoHuang it is possible that the behavior is different per platform and that this is not a actions/runner issue to begin with, as stated in the description, I am coming from https://github.com/actions-runner-controller/actions-runner-controller/issues/1135. There the runner is a Docker image that is being executed in Kubernetes. That said, I think that you already are giving the answer to the issue:

> the **current running process** and load from `.env` file

Emphasize mine, I think that the problem is that the current running process in https://github.com/actions-runner-controller/actions-runner-controller ignores `/etc/environment`. I checked how things are done in https://github.com/actions/virtual-environments and there pretty much everything is set up in `/etc/environment` with a dedicated helper script to deal with it at https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/helpers/etc-environment.sh. I also ran things with the public GitHub runners and there the contents of `/etc/environment` are all present in the environment of both the current user and root.

Regarding the example I gave, it is too simplistic because obviously appending anything to `/etc/environment` at runtime would not change anything in the environment of the currently running process. It is about having stuff in `/etc/environment` baked into the runner platform that is being ignored once a runner is started. I am going to update the initial issue description to reflect this better in the reproducer. 😉

**Comment by ethomson** [comment]
Interesting.  `/etc/environment` is usually read by PAM.  However `docker run ...` (for example) bypasses PAM completely, IIRC, so the `/etc/environment` magic is bypassed.  (`sudo` however _does_ interact with PAM, I would think.)

This seems like a real problem, but I don't think that the runner is the right place to solve it.  `/etc/environment` should be read by thing that creates the environment, whether that's `/bin/login`, etc.  That's because by the time the runner is started, we don't know what's happened in the environment.  It's very possible that you had stuff populated by `/etc/environment` and then before you started the runner you intentionally _unset_ (or changed) those environment variables.  We wouldn't want to go add them back.  🤔

**Comment by Fleshgrinder** [comment]
@ethomson I did not know that Docker completely ignores PAM, but that explains the behavior we see here. I guess the best workaround is to `set -a; source /etc/environment; set +a` in the `entrypoint.sh` file of https://github.com/actions-runner-controller/actions-runner-controller to bring the standard behavior back. The only difference from this to the standard PAM behavior would be that it interprets `/etc/environment` like a script and thus would allow for command execution etc. 🤔

```bash
mapfile -t env </etc/environment
exec env - "${env[@]}" ./bin/runsvc.sh "${args[@]}"
```

This would not interpret anything, so I guess this is the solution here. I am going to test this to verify that the problem is with https://github.com/actions-runner-controller/actions-runner-controller and `LoadAndSetEnv` and once I can confirm I will close this issue.

Thanks for all the ideas and pointers. 😊

**Comment by ethomson** [comment]
> ```
> mapfile -t env </etc/environment
> exec env - "${env[@]}" ./bin/runsvc.sh "${args[@]}"
> ```

This is a clever solution.  😁  Feel free to ping me in the ARC repo if there's general disagreement about the "right place" to do this.  I think that what you've proposed is the right one, but I concede that it's not open and shut.  😁

**Comment by Fleshgrinder** [comment]
I test my idea from above and it works as expected. I am not yet entirely sure if it should be `exec env --` or `exec env -i --` but that is something for ARC. Thanks again everyone, and I might come back to your offer @ethomson. 😉
