### ISSUE TITLE
Runner seems to mess up `run` strings with nested quotes (at least on macOS)

### ISSUE THREAD

**Issue by phil-blain** [actions/runner#1705]
**Describe the bug**
_A clear and concise description of what the bug is._

I'm trying to run this command in a `run` step:

```bash
make check-gdb RUNTESTFLAGS="INTERNAL_GDBFLAGS='-nw -data-directory $PWD/gdb/data-directory -iex \"set height 0\" -iex \"set width 0\"' CC_FOR_TARGET=$CC CXX_FOR_TARGET=$CXX"
```

This command works correctly on my machine.

In my workflow, I have this step with this exact command:
~~~yaml
    - name: Test
      run: |
          echo 'set startup-with-shell off' > $HOME/.gdbinit
          cd ../build
          make check-gdb RUNTESTFLAGS="INTERNAL_GDBFLAGS='-nw -data-directory $PWD/gdb/data-directory -iex \"set height 0\" -iex \"set width 0\"' CC_FOR_TARGET=$CC CXX_FOR_TARGET=$CXX"
~~~

The runner seems to eat some quotes, as I get an error from make:
https://github.com/phil-blain/binutils-gdb/runs/5275011249?check_suite_focus=true

**To Reproduce**
1. Go to https://github.com/phil-blain/binutils-gdb/runs/5275011249?check_suite_focus=true
2. Run the workflow
3. See error

**Expected behavior**
I expected the runner to be able to run a Bash command that works correctly when I run it locally on my machine.

## Runner Version and Platform
Version of your runner?

'2.287.1'

OS of the machine running the runner? OSX/Windows/Linux/...

  Environment: macos-10.15
  Version: 20220213.1

## What's not working?
_Please include error messages and screenshots._

The runner seems to remove some quotes, so I get an [error from make](https://github.com/phil-blain/binutils-gdb/runs/5275011249?check_suite_focus=true). Note that the commands are shown correctly (in blue in the log) prior to running them:
~~~
Run echo 'set startup-with-shell off' > $HOME/.gdbinit
  echo 'set startup-with-shell off' > $HOME/.gdbinit
  cd ../build
  make check-gdb RUNTESTFLAGS="INTERNAL_GDBFLAGS='-nw -data-directory $PWD/gdb/data-directory -iex \"set height 0\" -iex \"set width 0\"' CC_FOR_TARGET=$CC CXX_FOR_TARGET=$CXX"
  shell: /bin/bash -e {0}
  env:
    CC: gcc-11
    CXX: g++-11
    jobname: osx-gcc
    runs_on_pool: macos-10.15
    CFLAGS: -I/usr/local/include -g3 -O0
make[1]: *** No rule to make target `height'.  Stop.
make: *** [check-gdb] Error [2](https://github.com/phil-blain/binutils-gdb/runs/5275011249?check_suite_focus=true#step:6:2)
Error: Process completed with exit code 2.
~~~

I also tried inverting the single quotes with the internal (escaped) double quotes, like this:
```bash
make check-gdb RUNTESTFLAGS="INTERNAL_GDBFLAGS=\"-nw -data-directory $PWD/gdb/data-directory -iex 'set height 0' -iex 'set width 0'\" CC_FOR_TARGET=$CC CXX_FOR_TARGET=$CXX"
```

In that case, I also get an error from make, but a different one, so I'm guessing [the runner messes up in a different way](https://github.com/phil-blain/binutils-gdb/runs/5261663018?check_suite_focus=true):
~~~
Run echo 'set startup-with-shell off' > $HOME/.gdbinit
  echo 'set startup-with-shell off' > $HOME/.gdbinit
  cd ../build
  make check-gdb RUNTESTFLAGS="INTERNAL_GDBFLAGS=\"-nw -data-directory $PWD/gdb/data-directory -iex 'set height 0' -iex 'set width 0'\" CC_FOR_TARGET=$CC CXX_FOR_TARGET=$CXX"
  shell: /bin/bash -e {0}
  env:
    CC: gcc-11
    CXX: g++-11
    jobname: osx-gcc
    runs_on_pool: macos-10.15
    CFLAGS: -I/usr/local/include -g3 -O0
/Applications/Xcode_1[2](https://github.com/phil-blain/binutils-gdb/runs/5261663018?check_suite_focus=true#step:6:2).[4](https://github.com/phil-blain/binutils-gdb/runs/5261663018?check_suite_focus=true#step:6:4).app/Contents/Developer/usr/bin/make: invalid option -- a
/Applications/Xcode_[12](https://github.com/phil-blain/binutils-gdb/runs/5261663018?check_suite_focus=true#step:6:12).4.app/Contents/Developer/usr/bin/make: invalid option -- a
/Applications/Xcode_12.4.app/Contents/Developer/usr/bin/make: invalid option -- c
/Applications/Xcode_12.4.app/Contents/Developer/usr/bin/make: invalid option -- x
/Applications/Xcode_12.4.app/Contents/Developer/usr/bin/make: invalid option -- x
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
# etc
make: *** [check-gdb] Error 2
Error: Process completed with exit code 2.
~~~

## Job Log Output
_If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here._

See above.

## Runner and Worker's Diagnostic Logs
_If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here._

Any way I can get those in the hosted VMs ?

**Comment by ruvceskistefan** [comment]
Hi @phil-blain,
Thanks for filing this issue! We are investigating the bug you described, so we will get back to you as soon as we have more informations.

**Comment by ruvceskistefan** [comment]
No problem @phil-blain, thanks for letting me know.
Thanks, you too! :)
