### ISSUE TITLE
Corrupted artifact: actions-runner-osx-x64-2.288.0.tar.gz

### ISSUE THREAD

**Issue by 0x2b3bfa0** [actions/runner#1719]
The latest macOS release file [`actions-runner-osx-x64-2.288.0.tar.gz`](https://github.com/actions/runner/releases/download/v2.288.0/actions-runner-osx-x64-2.288.0.tar.gz) is corrupted.

### Steps to reproduce the behavior
1. Go to the [Releases](https://github.com/actions/runner/releases) page
2. Download [`actions-runner-osx-x64-2.288.0.tar.gz`](https://github.com/actions/runner/releases/download/v2.288.0/actions-runner-osx-x64-2.288.0.tar.gz) from the latest ([v2.288.0](https://github.com/actions/runner/releases/tag/v2.288.0)) release
3. Try to extract the file with GNU [`tar`](https://www.gnu.org/software/tar) or any other compatible tool
4. Extraction fails

### Expected behavior
Extraction succeeds

## Version

Only happens with `v2.288.0` (latest) and this specific macOS artifact.

## Issue

```console
$ curl --silent --location https://github.com/actions/runner/releases/download/v2.288.0/actions-runner-osx-x64-2.288.0.tar.gz | gunzip > /dev/null
gzip: stdin: invalid compressed data--format violated
```

**Comment by thboop** [comment]
Thanks for the report we are working on a fix

**Comment by thboop** [comment]
We regenerated this release and confirmed it is no longer corrupted, going to close this issue but please let me know if you see any more issues!

Thanks for the report.

**Comment by 0x2b3bfa0** [comment]
Block 1444 in the [DEFLATE](https://datatracker.ietf.org/doc/html/rfc1951) stream was corrupted, and NLEN (34710) was not the [one's complement](https://en.wikipedia.org/wiki/One%27s_complement) of LEN (22286) as [expected](https://datatracker.ietf.org/doc/html/rfc1951#page-11); see Go [`compress/flate`](https://github.com/golang/go/blob/eb8198d2f67477517e7a735faa49dfd7c0fb3622/src/compress/flate/inflate.go#L637) for more information.

Given that `1000 0111 1001 0110` doesn't have any plausible resemblance to the bitwise negation of `0101 0111 0000 1110`, it's hard to believe in a bit flip. 🤔 Anyway, it doesn't matter now.

```console
$ go run main.go < actions-runner-osx-x64-2.288.0.tar.gz > /dev/null
panic: flate: corrupt input before offset 34572188
```
```go
package main

import (
	"compress/gzip"
	"io"
	"os"
)

func main() {
	zr, err := gzip.NewReader(os.Stdin)
	if err != nil {
		panic(err)
	}

	io.Copy(os.Stdout, zr)

	if err := zr.Close(); err != nil {
		panic(err)
	}
}
```
