### ISSUE TITLE
Runner version v2.288.1?

### ISSUE THREAD

**Issue by omsmith** [actions/runner#1720]
Good afternoon!

Apologies if this is the incorrect forum. I'm trying to understand the reason for the v2.288.1 runner release. Was there an issue with the  v2.288.0 build? Only apparent difference between the two source-wise is the version bump. Other than that, v2.288.0's tag is signed, while v2.288.1 is not. If there was a specific reason, it's not mentioned in the notes.

Not a major problem, just looking to understand.

Thanks

**Comment by TingluoHuang** [comment]
We got a corrupted binary uploaded into the release assets, we have pruned and reproduced the right package for 2.288.0.
However, since you may have cached the runner tar.gz by version, we bump the version to avoid anyone using a staled cache.

https://github.com/actions/runner/issues/1719

**Comment by omsmith** [comment]
Thanks - missed that issue. If it would be possible it would be great to mention that in the .1 release notes.

Appreciate it.
