### ISSUE TITLE
Slow docker build in self hosted runner

### ISSUE THREAD

**Issue by saurabh-paystack** [actions/runner#1724]
**Describe the bug**
I am running a Docker build step in self-hosted runner and it is very very slow as compared to when I run in hosted virtual runner. The difference is significant. I have noticed it always happen after `yarn install` layer at Removing intermediate container. But, the same build and Docker is fast in hosted runner. 

I am running the runner in K8s cluster and I checked it's resources which were all fine during the step so nothing suspicious there.   

**To Reproduce**
1. Run docker build step in hosted virtual runner
2. Run docker build step in self-hosted runner
3. Compare the time difference

**Expected behavior**
Time should be similar

## Runner Version and Platform
Version of your runner?
1.0.0

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

**Comment by nikola-jokic** [comment]
Hi @saurabh-paystack,

Forgive me if I did not understand you correctly, but the time used for the build is directly influenced by the machine power in which your action is taking place. Docker build on a machine with less CPU power and less memory would take much more time than the exact same Dockerfile and docker build command on better hardware.

**Comment by saurabh-paystack** [comment]
@nikola-jokic , thanks for your quick response. But, as I mentioned, I am running it as a K8s pod and I checked the utilisation of the pod during the run and it was well within the limit. Underlying host where the pod is running is not very powerful but I am not sure if it should impact as the pod has enough resources to utilise.

**Comment by nikola-jokic** [comment]
Based on the workings of the runner, your instruction will be passed to the system and executed on the host where the runner is executing. The time is taken by the action you are performing is completely up to the system executing the action. There is nothing inside the runner that could slow the execution of a command.

I am certain that, if the underlying host has more resources, the same action would take less time.

**Comment by nikola-jokic** [comment]
I will close this issue now since it is related to the underlying hardware where the self-hosted runner is executing, and not the runner itself.

**Comment by shiraze** [comment]
I've also found the hosted virtual runners to be really slow, and I agree with @nikola-jokic that this relates to server hardware.
I have an action that can complete in 38s when using a self-hosted runner, but takes 14m when using a virtual runner. The majority of that time difference, though, appears to be the time taken to download the image.

**Comment by byander** [comment]
I noticed the same thing.
My self-hosted runner is running in an Orange PI 3B (4 GB RAM) and the step to build an image Docker stops after almost 15 minutes of running.
My Orange PI isn't a big machine, but if I execute it manually building an image docker takes 2 minutes.


Self-hosted runner:
![image](https://github.com/user-attachments/assets/4128516a-d5bd-4555-a81f-9f3c3e475df5)

Execute manually 
![image](https://github.com/user-attachments/assets/880b3c19-00fe-4655-ba68-e832d99e01a9)
