### ISSUE TITLE
`--disableupdate` does not prevent an update from running on startup

### ISSUE THREAD

**Issue by JakeThurman** [actions/runner#1729]
**Describe the bug**
There is no way to skip an update from running on launch. This would be a good workaround for #1728.

**To Reproduce**
1. `run.cmd --disableupdate`
2. Update runs (assuming one is available)

**Expected behavior**
Startup runner without updating.

## Runner Version and Platform
**Version of your runner?**
3.287.1

**OS of the machine running the runner? OSX/Windows/Linux/...**
Windows

## What's not working?
Cannot workaround #1728 using --disableupdate (or similar)

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs

[Runner_20220303-153016-utc.log](https://github.com/actions/runner/files/8179006/Runner_20220303-153016-utc.log)

**Comment by ilyamt-tandemg** [comment]
I have the same problem.

**Comment by TingluoHuang** [comment]
You need to config the runner with `--disableupdate`
`./config.sh --disableupdate`

**Comment by JakeThurman** [comment]
It seems odd that the flag would silently do nothing if it's not configured.

**Comment by nikola-jokic** [comment]
Hey @JakeThurman,

I will now close this issue, but I will file an enhancement request regarding your last comment 😊

**Comment by Cheaterman** [comment]
IDGI, how is the config.sh workaround a "fix"? I can't run that on existing runners, how do I disable updates for them? :-)
