### ISSUE TITLE
The type or namespace name 'DB2Parameter' could not be found in github runner e.g. windows-2019

### ISSUE THREAD

**Issue by GaganVirk123** [actions/runner#1734]
I'm running MSBuild step in github actions. It's always failing because of 'DB2Parameter' namespace. This step is working fine in other repositories. 
```
- name: Build solution & Octopack
        run: |
          $SolutionPath = Resolve-Path *.sln
          & "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe" $SolutionPath /t:Build /p:Configuration=Release /p:RunOctoPack=true /p:OctoPackPackageVersion=$env:buildVersionNumber
```

![image](https://user-images.githubusercontent.com/84691842/156964913-9ab59a72-8f28-4b13-a52c-dc6990815290.png)

**Comment by ruvceskistefan** [comment]
Hi @GaganVirk123,
Can you send us a link to the repository, so we can reproduce the bug you reported? To me this looks like your internal problem, and not a runner's bug, but I will definitely investigate further when you send us a link to the repo.

**Comment by GaganVirk123** [comment]
https://github.com/lic-nz/sb-DnaAnalysis
Thanks for looking into this issue. But, I dont' know if you can access this repo.

**Comment by ruvceskistefan** [comment]
You're welcome. Unfortunately, I can't access the repo. Can you change access rights or make a minimal reproduction example?

**Comment by TingluoHuang** [comment]
it feels like a dependency issue with https://www.nuget.org/packages/IBM.Data.DB2.Core
Did you run `dotnet restore` to install those packages as part of your build?

**Comment by GaganVirk123** [comment]
Thanks for looking into it. I've added `dotnet restore` step. But it is failing for the same reason. I've added some code reference to give you some more idea.

![image](https://user-images.githubusercontent.com/84691842/157787050-00e35ba1-0fc8-4ad5-b423-4fa0ca731fe8.png)

![image](https://user-images.githubusercontent.com/84691842/157787499-9846be6c-0364-4dba-918c-32809b8145e7.png)

```
<Reference Include="IBM.Data.DB2, Version=9.7.4.4, Culture=neutral, PublicKeyToken=7c307b91aa13d208, processorArchitecture=AMD64">
      <Private>False</Private>
```

```
<providers>
    <provider invariantName="IBM.Data.DB2" type="IBM.Data.DB2.EntityFramework.DB2ProviderServices, IBM.Data.DB2.EntityFramework, Version=10.5.5.6, Culture=neutral, PublicKeyToken=7c307b91aa13d208" />
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
</providers>
```

**Comment by ruvceskistefan** [comment]
Hi @GaganVirk123,

I dont't think this issue is a runner problem, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback) site which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
