### ISSUE TITLE
GitHub self-hosted-runners on Mariner

### ISSUE THREAD

**Issue by ezYakaEagle442** [actions/runner#1750]
**Describe the enhancement**
When a customer using a Private-Endpoint in AKS or Azure Spring Cloud for instance, then a self-hosted-runner must be deployed in the same VNet.
Mariner is supported in [Azure DevOps self-hosted-runners,](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#check-prerequisites) but not in [GitHub Action self-hosted-runners.](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#linux)

RFE: Mariner to be supported in GitHub self-hosted-runners

**Code Snippet**
N/A

**Additional information**
I also created [Issue #2484 · microsoft/CBL-Mariner](https://github.com/microsoft/CBL-Mariner/issues/2484) 

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by nikola-jokic** [comment]
Hi @ezYakaEagle442,

Thank you for submitting this enhancement. We added it to the backlog 😊

**Comment by TingluoHuang** [comment]
We won't support this unless dotnet core officially supports it.

**Comment by LongChengIn** [comment]
hi @TingluoHuang , it seems Mariner supports dotnet now. Can we add support to let self-hosted runners run on Mariner?

**Comment by casanova-21** [comment]
Requesting that we reopen this issue now that CBL-Mariner supports dotnet core.
