### ISSUE TITLE
Called workflows cannot be queued onto self-hosted runners across organisations/enterprises

### ISSUE THREAD

**Issue by cytopia** [actions/runner#1753]
**Describe the bug**
My public [repository](https://github.com/cytopia/docker-bind) is using a reusable action from [another public repository](https://github.com/devilbox/github-actions) of an organization.  Everything works fine and as expected during git push and pull request, however, when the job is triggered by "schedule" I get the following error (in a matrix build):
```
Called workflows cannot be queued onto self-hosted runners across organisations/enterprises. Failed to queue this job. Labels: 'ubuntu-latest'.
```
This happens 99% of the time, there are also jobs that do succeed: https://github.com/cytopia/docker-bind/actions/runs/1984085598

**Note that I am not using a self-hosted runner.**

**To Reproduce**
1. Create [reusable workflow](https://github.com/devilbox/github-actions/blob/master/.github/workflows/docker-name-version-arch.yml) in a public repository in an organization
2. [Use this workflow](https://github.com/cytopia/docker-bind/blob/master/.github/workflows/action_schedule.yml) in your own public repository (not part of the organization) as a scheduled workflow

**Expected behavior**
The workflow runs as  fine (it does, if it is called from another repository inside the same organization)

## Runner Version and Platform
ubuntu-latest

## What's not working?
```
Called workflows cannot be queued onto self-hosted runners across organisations/enterprises. Failed to queue this job. Labels: 'ubuntu-latest'.
```

![Screenshot 2022-03-15 10-41-26  selection](https://user-images.githubusercontent.com/12533999/158350133-e1e77552-3cce-417a-8eab-01aa7ea49b15.png)

## Job Log Output
No output

## Runner and Worker's Diagnostic Logs
-

**Comment by nikola-jokic** [comment]
Hi @cytopia,

This is a [duplicate](https://github.com/actions/runner/issues/1749). Just to add it here, the appropriate team is aware of this issue and is working on the fix. Thanks for submitting it 😊
