### ISSUE TITLE
libclang-12-dev package cannot be installed in Ubuntu 20.04 image

### ISSUE THREAD

**Issue by lcarlier** [actions/runner#1774]
**Describe the bug**

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**
Running

```
apt install libclang-12-dev
```
fails with
```
Fetched 28.5 MB in 3s (9545 kB/s)
 Err:22 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libclang-12-dev amd64 1:12.0.0-3ubuntu1~20.04.4
  404  Not Found [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-toolchain-12/libclang-12-dev_12.0.0-3ubuntu1~20.04.4_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```
Full log: https://github.com/lcarlier/EasyMock/runs/5616386907?check_suite_focus=true

## Runner Version and Platform
Version of your runner?
Default

OS of the machine running the runner? OSX/Windows/Linux/...
Ubuntu 20.04

## What's not working?
Please include error messages and screenshots.
```
Fetched 28.5 MB in 3s (9545 kB/s)
 Err:22 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libclang-12-dev amd64 1:12.0.0-3ubuntu1~20.04.4
  404  Not Found [IP: 20.106.104.242 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/l/llvm-toolchain-12/libclang-12-dev_12.0.0-3ubuntu1~20.04.4_amd64.deb  404  Not Found [IP: 20.106.104.242 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

https://github.com/lcarlier/EasyMock/runs/5616386907?check_suite_focus=true

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by ruvceskistefan** [comment]
Hi @lcarlier,
Thanks for filing this issue! I am reproducing it now and I will get back to you as soon as possible!

**Comment by ruvceskistefan** [comment]
This issue does not seem to be a problem with the runner application, it concerns the software on machines running GitHub's hosted runners.
Could you please post your issue in the [Virtual Environments Repository](https://github.com/actions/virtual-environments/issues/new/choose) to ensure the correct team sees it. 😃
