### ISSUE TITLE
HTTP 502 "This page is taking too long to load" on matrix workflow

### ISSUE THREAD

**Issue by cytopia** [actions/runner#1786]
**Describe the bug**
I have the following workflow: https://github.com/devilbox/docker-php-fpm/blob/ci-build-test-separation/.github/workflows/action_branch.yml

When this is close to finish, I am unable to view it anymore via the Web UI with the following HTTP 502 error :
```
This page is taking too long to load.

Sorry about that. Please try refreshing and contact us if the problem persists.
```

https://github.com/devilbox/docker-php-fpm/actions/runs/2048736883

**To Reproduce**
1. Go to https://github.com/devilbox/docker-php-fpm/actions/runs/2048736883
2. See error

**Expected behavior**
Is should see my workflow in the UI

## Runner Version and Platform
ubuntu-latest

## What's not working?
The web ui for my workflow is not showing

## Job Log Output
Cannot provide, as I can't access the page

## Runner and Worker's Diagnostic Logs
Cannot provide, as I can't access the page

**Comment by cytopia** [comment]
Seems related to: https://github.community/t/workflow-receives-this-page-is-taking-too-long-to-load-message-with-unicorn/239583/3

**Comment by cytopia** [comment]
FYI: This has been fixed. Check the forum thread to confirm.

**Comment by nikola-jokic** [comment]
Hi @cytopia,

Thank you for notifying us! I am closing this issue now
