### ISSUE TITLE
Exfiltration of GitHub secrets using base32

### ISSUE THREAD

**Issue by leooelx** [actions/runner#1800]
**Describe the bug**
I found a bug on GitHub Actions that permits discover any secret stored on repository or organization.

To do this you only need to create a workflow to run a echo on a secret using a pipe with base32 decode.
Doing this the secret will appear on the pipeline log.

**To Reproduce**
name: Secret Expose
on:
  push:
  workflow_dispatch:

jobs:
  pipeline:
    name: Pipeline
    runs-on: self-hosted
    steps:
    - run: |
        echo ${{secrets.SOME_SECRET }} | base32

**Expected behavior**
The base32 of the secret will appear on the pipeline e you will be able to decode it to a clear text.

**Comment by thboop** [comment]
Hey @leooelx thanks for the report! 

This isn't a bug, the security boundary for the runner is a job getting assigned on your runner. You can read more information about our security hardening for workflows [here](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#potential-impact-of-a-compromised-runner).

At a high level, you should be very cautious with who can queue workflows in your repository. Even if we fixed this (which is almost impossible due the number of ways you can permeate secrets and print them to logs), a user could just send the secret to a third party website they own and view it there. If we prevent secrets from being set to third party websites (also a very difficult technical feat), we would also break a ton of valid user flows that need to be able to use secrets to auth.

Secret masking is best effort to help users in scenarios where they accidentally would have leaked a secret. A determined actor who is given access to modifying workflows in a repository with secrets will always find some way to get the value of the secret.
