### ISSUE TITLE
Hook feature - Set up runner step failed when working-directory specified

### ISSUE THREAD

**Issue by retzero** [actions/runner#1808]
**Describe the bug**

Hello,
I'm trying to use start/complete hook feature. (v 2.289.1)
But it's failing when default `working-directory` is set in the workflow.
Can you please guide me how to overcome this?

- My workflow

  ```yaml
  defaults:
    run:
      working-directory: 'xyz'
  
  jobs:
    build:
      runs-on: [ "self-hosted" ]
      steps:
        - uses: actions/checkout@v2
  ```

- Error prints

  ```
  A job started hook has been configured by the self-hosted runner administrator
  Run '/opt/hook_start.sh'
    shell: /usr/bin/bash -e {0}
  Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/github/actions-runner/_work/actions-playground/actions-playground/xyz'. No such file or directory
  ```

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?
2.289.1

OS of the machine running the runner? OSX/Windows/Linux/...
Linux (Ubuntu)

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by thboop** [comment]
Thanks for the report @retzero, thats a bug we will get a fix in the next runner version

**Comment by retzero** [comment]
@thboop 
Thank you for the feedback.
I suggest those steps(`Set up runner` and `Complete runner`) not to affect the result of the entire job.

**Comment by kkathuri-v** [comment]
I am using the latest version '2.301.1' for self hosted runner but still facing the same issue. I have also tried specifying the working directory at job level. Any ideas?

**Comment by nadvolod** [comment]
I'm facing the same issue `
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/java-sdet/java-sdet/java-sdet-bootcamp'. No such file or directory`
From https://github.com/ultimate-qa/java-sdet/actions/runs/4218390788/jobs/7322868158

**Comment by xposionn** [comment]
facing the same issue

**Comment by ojeolaayofe** [comment]
facing the same issue error: an error occured trying to start process '/usr/bin/bash' with working directory '/home/runner/work/admin-ca/admin-ca-data/.dev/'. No such directory

**Comment by bajajdivya** [comment]
facing the same issue
