### ISSUE TITLE
Network issues during gh action run on build

### ISSUE THREAD

**Issue by OmerGery** [actions/runner#1811]
**Describe the bug**
Network error during build , failure to download resources. flaky ,download works only on like 30% of the ci runs

**To Reproduce**
Download these resources from gh action ci run 

**Expected behavior**
Expected the resources to be downloaded and the build to succeed as the resources download work fine when downloading locally

## Runner Version and Platform
Version of your runner?
macos-latest 

## What's not working?

* What went wrong:
![image](https://user-images.githubusercontent.com/68545675/161999420-e81d29e3-ca74-4026-828f-466aa6a7acb1.png)

**Comment by ruvceskistefan** [comment]
Hi @OmerGery,
Can you send us URL of workflow run or workflow file, so that we can reproduce reported bug?

**Comment by ruvceskistefan** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!

**Comment by zenineasa** [comment]
I have a similar issue. I am attempting to fetch results from GitHub API. The following is the URL:
https://api.github.com/repos/zenineasa/hexhoot/releases/latest

The logs can be found here:
https://github.com/zenineasa/HexHoot/actions/runs/4656553035/jobs/8240442011
