### ISSUE TITLE
Support non-interactive `./config.sh remove`

### ISSUE THREAD

**Issue by logan-mauzaize-saagie** [actions/runner#1815]
**Describe the enhancement**
I use Terraform to (de)comission runners. I use a bash script on runner Virtual Machine in order to manage lifecyle. However, its seems the `./config.sh remove` has no non-interactive capabilities.

Using `./config.sh remove "${token}"` or `./config.sh remove <<<"${token}"` always prompting for token.

**Code Snippet**
N/A

**Additional information**
It would also be nice for a runner to be able to unregister itself without requiring a Github Personal Acces Token or a registration token. I suppose API is out-of-scope of this repository ? Can you lead me to appropriate URL for this RFE. Thank you!

**Comment by ruvceskistefan** [comment]
Hi @logan-mauzaize-saagie,
Have you tried with this command: `./config.sh remove --token TOKEN_VALUE`? That should work properly, so just let me know if everything went well.

**Comment by logan-mauzaize-saagie** [comment]
It's ok thank you ! May be some improvement should be made on help message.

Do you where I can post my RFE about self unregistration ?

**Comment by logan-mauzaize-saagie** [comment]
Just to be sure `--unattended` isn't supported by `./config.sh remove` ?

**Comment by ruvceskistefan** [comment]
You can post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃

As for the help, I think this (`--token string       Registration token. Required if unattended`) is quite enough, but I'm open to changes if there are more users with a similar problem. `--unattended` is one of valid flags for `config` command, not for `remove` command. `remove` command only supports `--token` and `--pat` args.

 I'm going to close this issue, feel free to ask if you have any more questions or reopen this issue.

**Comment by logan-mauzaize-saagie** [comment]
help doesn't show which option apply for which commands. That makes me confusing. May be having specific help message on `./config.sh remove --help` will be ... helpful

Thank you for your help and sorry for this RFE which is finally a support request :(

**Comment by ruvceskistefan** [comment]
You're welcome @logan-mauzaize-saagie!
I'll consult with the rest of the team, so we'll change the help message if everyone agrees.
