### ISSUE TITLE
Actions stuck on "Job is about to start running on the hosted runner" for hours

### ISSUE THREAD

**Issue by dimanlm** [actions/runner#1819]
**Describe the bug**
Ubuntu latest actions get stuck on "Job is about to start running on the hosted runner: Hosted Agent (hosted)". Usually after 3 hours it says if the build passed or not.
This problem started after I added more tests to my project (NodeJS - Jest)

**To Reproduce**
1. Push a new commit
2. Run "Actions"
3. See error

**Expected behavior**
There are 24 tests, and usually it takes 15 seconds (maximum) to run them locally.

## Runner Version and Platform
*Version of your runner?* Ubuntu-latest

Jobs in the workflow:

    jobs:
      build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [16.x] 
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        
        - name: Install Node dependencies
          run: npm i
    
        - name: Run unit and integration tests
          run: npm test
    
        - name: SonarCloud scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

## What's not working?
![image](https://user-images.githubusercontent.com/92322153/162737452-bb7464f3-55d9-4eb2-aa5d-1896479912d3.png)
![image](https://user-images.githubusercontent.com/92322153/162737256-2fba9b07-ca05-45ba-b5f4-459c674896ff.png)
![image](https://user-images.githubusercontent.com/92322153/162738654-58552896-f214-46c6-9893-0a9bb98c1a96.png)
"Run unit and integration tests" final log:
![image](https://user-images.githubusercontent.com/92322153/162740014-eeca0b8b-4a3b-493b-85d5-7e6b0cf4b025.png)

## Job Log Output
![image](https://user-images.githubusercontent.com/92322153/162737643-bc79e226-21f8-4639-870a-cfe657fe4aa4.png)

**Comment by nikola-jokic** [comment]
Hi @dimanlm, thanks for submitting this issue.

Could you please provide `_diag` file so we can investigate what is causing this issue?

**Comment by lithiumtoast** [comment]
Hey @dimanlm,

I had the same issue. I was able to use `ubuntu-18.04` instead of `ubuntu-latest` which then I could get my workflow running.

**Comment by dimanlm** [comment]
> Hey @dimanlm,
> 
> I had the same issue. I was able to use `ubuntu-18.04` instead of `ubuntu-latest` which then I could get my workflow running.

Hi @lithiumtoast ,

Thank you for your reply. I found out that open handles after jest tests were causing Github Actions runner to be blocked at this step waiting for the timeout. Those open handles were left by mongoose (mongoose.connect and .connection.close()). To fix this issue, I created a `test-teardown-globals.js` file, as suggested on this thread: https://github.com/visionmedia/supertest/issues/520#issuecomment-768148875
I will keep your suggestion to put `ubuntu-18.4` in my workflow though :)

**Comment by darius-sas** [comment]
In my case the problem was that the server running the self-hosted runner ran out of space (full of docker images!).
Maybe this is useful to someone.

**Comment by subooom** [comment]
Hey, I initially created the directory under `/home/ubuntu` and it was all working. I later decided to move the directory to `/var/www/html` and it stopped working. 

`Waiting for a runner to pick up this job...`

**Comment by jscherb1** [comment]
@darius-sas - how did you identify the server was full of docker images? And what did you do to remove those images?

**Comment by darius-sas** [comment]
> @darius-sas - how did you identify the server was full of docker images? And what did you do to remove those images?

Just out of luck actually...

You can use `docker system prune` to remove all unused images **and containers**! You can Google yourself how to remove old images

**Comment by therealdwright** [comment]
I have experienced this issue since the closure of this issue as recently as 20 minutes ago.

**Comment by roskelleycj** [comment]
> I have experienced this issue since the closure of this issue as recently as 20 minutes ago.

Ditto, just 30m ago this issue has occurred.  And https://www.githubstatus.com/ shows no issues.  

Seems like an issue in the GitHub Action infrastructure.

**Comment by nasirky** [comment]
It is currently happening for us as well on certain workflows.

**Comment by qpwo** [comment]
My whole host machine gets totally frozen every day or two and i have to hard reboot it

**Comment by dev-rinchin** [comment]
I had the same issue right now for macos-latest

https://github.com/sb-ai-lab/LightAutoML/actions/runs/10386491995/job/28757888335
[logs_27165338198.zip](https://github.com/user-attachments/files/16623433/logs_27165338198.zip)
