### ISSUE TITLE
Configure Listener Service Environment Variables

### ISSUE THREAD

**Issue by collin-miller** [actions/runner#1822]
**Describe the enhancement**
On self-hosted runners, I was unable to easily inject custom environment variables into the runner service config. Trying to use a `.env` file did not work. I eventually had to add an `override.conf` file and restart the service during instance bootstraping to accomplish this. 

As you add more event hooks or even just continue to support the existing `ACTIONS_RUNNER_HOOK_JOB_COMPLETED` and `ACTIONS_RUNNER_HOOK_JOB_STARTED` it would be beneficial for consumers to be able to pass these environment variables to the startup configuration.

**Code Snippet**
```bash
## new flag
./config.sh --env="key1=value1,key2=value2"
```

**Additional information**
Add any other context about the feature here.

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by nikola-jokic** [comment]
Hi @collin-miller,

Thank you for submitting the issue! If we are not reading the `.env` when we start it as a service, should we file this as a bug, rather than an enhancement with the flag?

**Comment by AvaStancu** [comment]
Hey @collin-miller ,
Thank you for your interest in the runner application and taking the time to provide your valuable feedback. We kindly ask you to redirect this feedback to the [GitHub Community Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests in GitHub Actions. [Read more about our guidelines here.](https://github.com/actions/runner/blob/main/docs/contribute.md)
