### ISSUE TITLE
Recommended upgrade path to `node16` for action authors?

### ISSUE THREAD

**Issue by hoffa** [actions/runner#1824]
**Describe the enhancement**

(Sorry this is more of a request for guidance; didn't see a better issue category)

If there is no change to the action interface, nor to its code, nor does it target post-Node.js 12 features, is it safe to bump `runtime` in `action.yml` to `node16` without updating major version, and without breaking Node.js 12 customers?

I guess in other words, does the runner safely fallback to Node.js 12 even if `runtime` is marked as `node16`? It would be unfortunate to ask users to update major version (and render a lot of documentation obsolete) when none of the code being executed has changed.

I see for at least some actions (e.g. [actions/setup-go](https://github.com/actions/setup-go), [actions/setup-python](https://github.com/actions/setup-python)) the runtime change was matched with a major version update, but not sure if that was solely due to the `runtime` change.

**Code Snippet**
N/A

**Additional information**
N/A

**Comment by fhammerl** [comment]
Hi @hoffa, thanks for taking an active interest in upgrading you actions to `node16`! 
Short answer: **The major version bump is highly recommended, but it is not a technical requirement for the action to run on `node16`.**

Check the [documentation](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions) for generic versioning guidelines.

### Long answer

While inconvenient in some cases, bumping a major version is recommended, at least from a semantic versioning perspective. Bumping the Node version also inherits any and all of Node's breaking changes between v12 and v16. 
Also, [actions/setup-go](https://github.com/actions/setup-go) and [actions/setup-python](https://github.com/actions/setup-python) also took this as an opportunity to introduce other breaking changes, specifically, removing deprecated features, as part of the major version bump.

On the other hand, for many actions, the transition between `node12` and `node16` can be entirely seamless, and ultimately the final versioning decision is in the hands of the action author.

**Comment by fhammerl** [comment]
To continue this discussion, I'd recommend you kindly post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃

**Comment by hoffa** [comment]
Thanks, it seems updating the major version makes sense. I was assuming (with my limited Node.js experience) that releases were backward compatible, which isn't the case (see e.g. [here](https://nodejs.org/en/blog/release/v16.0.0/)).

**Comment by hoffa** [comment]
From https://github.blog/changelog/2022-05-20-actions-can-now-run-in-a-node-js-16-runtime/

> As a result, actions authors who move from targeting Node.js 12 to Node.js 16 should release with a new major version number to communicate that there is a possible breaking change for GitHub Enterprise Server 3.3 and earlier.

**Comment by Andrey5045** [comment]
Here is my build.yml
What do I have to change here to upgrade node 12 to 16?

> name: Build and Deliver
> 
> on:
>   workflow_dispatch:
>     inputs:
>       AppVersion:
>         description: 'Version Name'
>         required: true
>         default: '1.0'
>       Solar2DBuild:
>         description: 'Solar2D Build Number'
>         required: true
>         default: '2020.3635'
>       Xcode:
>         description: 'Xcode Version'
>         required: true
>         default: '12.3'
> 
> 
> env:
>   DEVELOPER_DIR: /Applications/Xcode_${{ github.event.inputs.Xcode }}.app/Contents/Developer # this forces Xcode version
>   APP_VERSION: ${{ github.event.inputs.AppVersion }}
>   S2D_BUILD_NAME: ${{ github.event.inputs.Solar2DBuild }}
> 
> 
> jobs:
>   build:
>     runs-on: macos-10.15
>     steps:
>       - uses: actions/checkout@v2
>       - name: Build and Deliver
>         run: Util/build.sh
>         env:
>           CERT_PASSWORD:  ${{ secrets.CertPassword }}
>           APPLE_USERNAME: ${{ secrets.AppleUser }}
>           APPLE_PASSWORD: ${{ secrets.ApplePassword }}
>           APPLE_TEAM_ID:  ${{ secrets.AppleTeamId }}
>
