### ISSUE TITLE
Outputs from matrix returns only the last value

### ISSUE THREAD

**Issue by mbrancato** [actions/runner#1835]
**Describe the bug**
I noticed that if you have a matrix job's output feed into another job, only the value from the last job is provided.

**To Reproduce**

Create a job with a matrix and outputs
Access the outputs in a subsequent job

**Expected behavior**
This is a bit unclear - I think if you have a matrix job feed into a non-matrix job or different matrix, it might need to send an array of values. But if the matrix of Job A and Job B - I think the corresponding values only should pass. Basically, jobs shouldn't know if they are part of a matrix or not - or if they fall after a matrix.

## Runner Version and Platform
Hosted

OS of the machine running the runner? 
Linux

## What's not working?
The output values appear to be the values from the last job in the matrix to complete.

**Comment by ruvceskistefan** [comment]
Hi @mbrancato,
I found a [ticket](https://github.community/t/bug-jobs-output-should-return-a-list-for-a-matrix-job/128626/33) on GitHub Community Forum in which there is a discussion about the same issue. We will certainly investigate this issue and consider all suggestion from Community ticket, so I'll let you know what we have concluded.
