### ISSUE TITLE
Composite action status is using mixed case not lower case only

### ISSUE THREAD

**Issue by gitfool** [actions/runner#1841]
**Describe the bug**

Using the composite action status in a string comparison, as documented [here](https://docs.github.com/en/actions/learn-github-actions/expressions#evaluate-status-explicitly), does not work as expected because it returns mixed case `Failure` instead of `failure`.

**Expected behavior**

Status should be consistent across both job and composite actions and should be using all lowercase, as documented, to avoid needing further string manipulation like with `toLowerCase()`.

## Runner Version and Platform
Version of your runner? GHES 3.4.0; Runner 2.287.1

OS of the machine running the runner? Linux

## What's not working?

```js
${{ github.action_status == 'failure' }} # returns 'Failure'
```

**Comment by nikola-jokic** [comment]
Hi @gitfool,

Thank you for submitting this issue. We will investigate this and let you know when the fix is ready
