### ISSUE TITLE
Changing the title of the Run step used in the hook feature.

### ISSUE THREAD

**Issue by retzero** [actions/runner#1842]
Hello.

I want to change the title of the Run step used in the Hook feature. Is it possible?
Currently the script path is displayed. I want to hide the exposed path.

```
Set up runner
  A job started hook has been configured by the self-hosted runner administrator
  ▶ Run '/opt/hook_start.sh'
```

**Comment by nikola-jokic** [comment]
Hi @retzero,

Thank you for submitting this issue. I will mark it as an enhancement and add it to the board.

**Comment by AvaStancu** [comment]
@nikola-jokic @fhammerl what should be done here > should this line `▶ Run '/opt/hook_start.sh'` be removed completely, should it be replaced with a simple `▶ Running` or another option ? How do we know that everyone will be ok with the new option and we won't need to update it if someone else has another preference? Thanks!
