### ISSUE TITLE
ACTIONS_RUNNER_HOOK_JOB_COMPLETED not working

### ISSUE THREAD

**Issue by dan-stytch** [actions/runner#1847]
**Describe the bug**
I'm attempting to use the `ACTIONS_RUNNER_HOOK_JOB_COMPLETED` and am running into this error:
```
A job completed hook has been configured by the self-hosted runner administrator
[2](https://github.com/my-org/my-repo/runs/123456789?check_suite_focus=true#step:16:2)
Error: File doesn't exist
```

**To Reproduce**
1. Create job completed script outside of the `actions-runner` directory, e.g. `~/runner-job-completed.sh` per [this documentation](https://docs.github.com/en/actions/hosting-your-own-runners/running-scripts-before-or-after-a-job#triggering-the-scripts).
1. `chmod 755 ~/runner-job-completed.sh`
1. Set environment variable `ACTIONS_RUNNER_HOOK_JOB_COMPLETED` to `/Users/my-user/runner-job-completed.sh` in service plist
1. Restart runner service
1. Run workflow
1. See `File doesn't exist` error

**Expected behavior**
File should be found and run as expected

## Runner Version and Platform
Version of your runner? `osx-x64-2.290.1`

OS of the machine running the runner? `macOS 12`

## What's not working?
See above in bug description

**Comment by nikola-jokic** [comment]
Hi @dan-stytch,

Thank you for submitting this issue! We will get back to you as soon as we reproduce it and find the root cause of this issue.

**Comment by dan-stytch** [comment]
Hi @nikola-jokic I just wanted to check in on this to see if you'd been able to make any progress diagnosing. Thank you!

**Comment by nikola-jokic** [comment]
Hey @dan-stytch, sorry for the delay
Would you mind providing a debug log? And please, double-check that you are not exposing any sensitive information just in case.
Thank you in advance

**Comment by dan-stytch** [comment]
@nikola-jokic are you just looking for the surrounding context around that error from above? Or is there a separate log file I should be referencing? I can see if I can track that down, or repeat it, but I haven't had this hook configured since sharing the issue originally.

**Comment by dan-stytch** [comment]
@nikola-jokic I'm actually going to close this. I went searching for the log for that run, but was unable to find it so reinstalled the hook to repro and all seems to be working now. Unsure if it is just a new version of the runner or something else, but all seems to be good now!

**Comment by nikola-jokic** [comment]
Good to know! Thank you for notifying :smile: !

**Comment by Nmishin** [comment]
Had the same issue - fixed by:

1. Moving the file to the different directory (according to documentation: ["The custom scripts must be located on the runner, but should not be stored in the actions-runner application directory."](https://docs.github.com/en/actions/hosting-your-own-runners/running-scripts-before-or-after-a-job#triggering-the-scripts) )
2. Set full path to the script in the` .env`  file, like `ACTIONS_RUNNER_HOOK_JOB_COMPLETED=/opt/cleanup.sh`, $PATH didn't work here, and script will not be found even if it is there.
3. If you using systemd for runner, restart systemd automation.service every time you change the `.env` file.

**Comment by pnjihia** [comment]
Had to add a blank new line to my `.env` file. New variables were getting added right at the end of existing content.
