### ISSUE TITLE
Error: EPERM: operation not permitted, unlink -- GitHub Action Org Runner

### ISSUE THREAD

**Issue by pankajjain1** [actions/runner#1856]
Getting error when try to run same runner on different repo

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?2.9
[Uploading error.txt…]()

OS of the machine running the runner? Windows

## What's not working?
6s
Run actions/checkout@v3
  with:
    token: ***
    repository: Travelport-Enterprise/ECS-AUTOMATION.GHSAUTOUPDATES_WEB
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: [1](https://github.com/Travelport-Enterprise/ECS-AUTOMATION.GHSAUTOUPDATES_WEB/runs/6216567163?check_suite_focus=true#step:2:1)
    lfs: false
    submodules: false
    set-safe-directory: true
Syncing repository: Travelport-Enterprise/ECS-AUTOMATION.GHSAUTOUPDATES_WEB
Getting Git version info
Deleting the contents of 'D:\actions-runner\_work\ECS-AUTOMATION.GHSAUTOUPDATES_WEB\ECS-AUTOMATION.GHSAUTOUPDATES_WEB'
Error: EPERM: operation not permitted, unlink 'D:\actions-runner\_work\ECS-AUTOMATION.GHSAUTOUPDATES_WEB\ECS-AUTOMATION.GHSAUTOUPDATES_WEB\c8ae8d41-be[2](https://github.com/Travelport-Enterprise/ECS-AUTOMATION.GHSAUTOUPDATES_WEB/runs/6216567163?check_suite_focus=true#step:2:2)a-4e96-800[3](https://github.com/Travelport-Enterprise/ECS-AUTOMATION.GHSAUTOUPDATES_WEB/runs/6216567163?check_suite_focus=true#step:2:3)-f238[6](https://github.com/Travelport-Enterprise/ECS-AUTOMATION.GHSAUTOUPDATES_WEB/runs/6216567163?check_suite_focus=true#step
[error.txt](https://github.com/actions/runner/files/8585887/error.txt)
:2:6)f03aaae'

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by pankajjain1** [comment]
its c:\ drive issue

**Comment by srivastava-prashant** [comment]
@pankajjain1 Hey Pankaj.. We too are having similar issue. When we try to trigger build from Git Hub onto our build server (windows Box). Then, It gives an error at Step - Action/Checkout. 

I see you mentioned the issue is with C drive. Would it be okay with to elaborate what was the actual problem here in C drive.?

**Comment by GCO-NZ** [comment]
Whaty sort of C drive issue did you experience @pankajjain1 ?

**Comment by siddhant-17dash** [comment]
I guess what he meant is that, the C drive doesn't provide permission to remove/overwrite previous files for checking out new repo
