### ISSUE TITLE
Error: should be either '[path]/Dockerfile' or 'docker://image[:tag]' after update to v2.291.0

### ISSUE THREAD

**Issue by thiagosantosleite** [actions/runner#1859]
**Describe the bug**
Some actions starts to fail after the last update to v2.291.0 (we are using the @latest).

## Runner Version and Platform
Version of your runner?
OS:
Linux ip-10-4-2-173.ec2.internal 5.10.109-104.500.amzn2.x86_64 #1 SMP Wed Apr 13 20:31:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Runner:
v2.291.0

## What's not working?
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/1839326/165959452-b3d0b9f7-a0e5-47dd-b50f-b66fd1f8a690.png">

**Comment by NickDub-adeo** [comment]
> I can confirm this, we are seeing this error when using [`sonarsource/sonarcloud-github-action`](https://github.com/sonarsource/sonarcloud-github-action), [`Checkmarx/ast-github-action`](https://github.com/Checkmarx/ast-github-action) and [`reviewdog/action-detect-secrets`](https://github.com/reviewdog/action-detect-secrets) on self-hosted runners.

And with `KevinDeJong-TomTom/commisery-action` too...

**Comment by thboop** [comment]
Hey folks, we are creating a new release `2.291.1` which should fix this issue in the next few minutes. I've gone ahead and marked 2.291.0 as prerelease in the meantime.

**Comment by calmyournerves** [comment]
@thboop Thanks for the quick fix! Is there a way to trigger the runner auto-update on the server side? How often does it check for a new version?

**Comment by thboop** [comment]
We slowly roll out new runners to customers, once its rolled out to you it will automatically update. There is currently no way to manually trigger an update, but its on our radar. You can always download the latest binaries and reconfigure your runner to update if you wish.
