### ISSUE TITLE
Container operations are only supported on Linux runners

### ISSUE THREAD

**Issue by rgaufman** [actions/runner#1866]
I created a Mac runner, but getting this:

```
Error: Container operations are only supported on Linux runners
```

Am I missing something or are Mac runners with containers not supported? - I cannot seem to find any details in the documentation, maybe I missed something!

**Comment by alexiaizenberg** [comment]
Here you go: https://github.com/actions/runner/issues/904

**Comment by nikola-jokic** [comment]
Thank you @alexiaizenberg for providing an answer. Also, @rgaufman, you can find this in the docs on this [link](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#:~:text=self-hosted%20runners%20must%20use%20a%20linux%20operating%20system%20and%20have%20docker%20installed%20to%20run%20docker%20container%20actions.%20for%20more%20information%20about%20the%20requirements%20of%20self-hosted%20runners%2C%20see%20%22about%20self-hosted%20runners.%22). I am closing this issue now :relaxed:

**Comment by rgaufman** [comment]
That link talks about Windows, I am talking about Mac? - I don't see anything about "Container operations" on Mac on either link?

**Comment by nikola-jokic** [comment]
> Self-hosted runners must use a Linux operating system and have Docker installed to run Docker container actions.
This line can be found on the link I have commented on above :relaxed:

**Comment by rgaufman** [comment]
Ah, don't know how I missed that! - Is there any reason for that? - I have Docker installed on Mac, it runs all my Linux images. I guess I can't run a worker inside of a Linux docker container either :D
