### ISSUE TITLE
Stale sample usage `./delete.sh myorg`

### ISSUE THREAD

**Issue by jsoref** [actions/runner#1867]
This assumes one can pass a single argument:
https://github.com/actions/runner/blob/777ce5a0dc7ff840d0456870026e4351617a1dff/scripts/delete.sh#L11

This clearly indicates that isn't legal:
https://github.com/actions/runner/blob/777ce5a0dc7ff840d0456870026e4351617a1dff/scripts/delete.sh#L37-L38

And this code is called too early (it shouldn't be called until after the preceding excerpt):
https://github.com/actions/runner/blob/777ce5a0dc7ff840d0456870026e4351617a1dff/scripts/delete.sh#L29

**Comment by nikola-jokic** [comment]
Hi @jsoref,
Thank you for submitting this issue! We will make a PR fixing this.
