### ISSUE TITLE
Add `created_at` field to workflow_job event

### ISSUE THREAD

**Issue by npalm** [actions/runner#1881]
**Describe the enhancement**
At field `created_at` to`workflow_job` event to calculate time that it takes start jobs from the moment the event was created. 

**Code Snippet**
n/a

**Additional information**
We are creating some metrics to keep track of our fleet of self-hosted runners. For our users one of the most important things is, is the time it takes to start a job from the moment the event was created. This indicator indicates the time it takes from the moment a job is triggered it got start on the agent. For our self-hosted runners it means the time it takes to potentially create an istance start the agent.  See also [issue](https://github.com/philips-labs/terraform-aws-github-runner/issues/2048)

The workflow jobs event sent when the job is queued contains a field `started_at`. This is the moment the job is triggerd. Later we got an event when the job is started. Now the field `started_at` is updated. The diff between two timestamps is the time it takes to start the job. Calculationg the diff seems trivvial, but requires keep track on the state and or matching the events. The `actions/runs` API contains a `created_at` timestamp. Looks like the suite created for the job once the job was started. 

To calculate the time in uncomplicated way it would be very helpfull when the `created_at` time is added to the `workflow_job` events.

**Comment by ruvceskistefan** [comment]
Hi @npalm,
Thanks for reporting this enhancement request. I added it to the board, so we're going to consider it and work on it in the future.

**Comment by npalm** [comment]
@ruvceskistefan is the board also public?

**Comment by jacola** [comment]
@npalm, not sure if it helps, but I created a [sample webhook](https://github.com/github/customer-feedback/issues/5309) for someone looking to monitor queue time that shows how to capture that data after receiving similar requests from several GitHub admins.

**Comment by jacola** [comment]
@npalm, not sure if it helps, but I created a [sample webhook](https://github.com/jacola/ActionsTrafficMonitor) for someone looking to monitor queue time that shows how to capture that data after receiving similar requests from several GitHub admins.

**Comment by equalizer999** [comment]
There is actively work being done to add this to the event body ([PR](https://github.com/github/github/pull/260491) pending). ETA (for GA) - unknown still.
