### ISSUE TITLE
ephemeral runners not picking up new jobs

### ISSUE THREAD

**Issue by chemhack** [actions/runner#1887]
**Describe the bug**

We have been experiencing an issue with ephemeral runners not picking up new jobs recently, where there are queued jobs as well as idle ephemeral runners, but those queued jobs won't start on the idling runners.

**To Reproduce**

It's very hard to have a reliable step of reproduce in this case, as it only seems to happen when github.com is under stress. Here's what's our setup look like.

1. Setup auto scaling ephemeral runners following [official guideline](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners)
2. Wait until github.com is under stress. (most commonly around 4PM UTC, recent instance is today)
3. Observe queued jobs are not being started on the idling runners.

Note: the issue always recover on its own without any change of configuration in our setup.

**Expected behavior**

Queue jobs should start on idle runners.

## Runner Version and Platform
Version of your runner?
2.291.1

OS of the machine running the runner?
Linux

**Comment by chemhack** [comment]
Incident report which might be connected https://www.githubstatus.com/incidents/d1stj7xcn4fy

The issue today started around 16:00 UTC, according to the incident report, degraded performance on webhook only started from 17:05 UTC.

**Comment by ruvceskistefan** [comment]
Hi @chemhack,

This issue does not seem to be a problem with the runner application (the job doesn't even reach the runner, maybe the service was down), it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
