### ISSUE TITLE
Unable to configure/setup github runner on RHEL 6.6

### ISSUE THREAD

**Issue by cguttapalli** [actions/runner#1909]
**Describe the bug**
While trying to add a RHEL 6.6 vm as a github runner I am getting below error. 

$ ./config.sh --url https://github.com/glcp --token **************
./bin/libcoreclr.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/libcoreclr.so)
./bin/libcoreclr.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by ./bin/libcoreclr.so)
./bin/libSystem.Security.Cryptography.Native.OpenSsl.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/libSystem.Security.Cryptography.Native.OpenSsl.so)
./bin/libSystem.IO.Compression.Native.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/libSystem.IO.Compression.Native.so)
./bin/Runner.Listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/Runner.Listener)

**To Reproduce**
1. Go to an RHEL 6 machine 
        [build@**********]$ cat /etc/redhat-release
        Red Hat Enterprise Linux Server release 6.6 (Santiago)
2. Run 
                '# Create a folder
                $ mkdir actions-runner && cd actions-runner# Download the latest runner package
                $ curl -o actions-runner-linux-x64-2.291.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.291.1/actions-runner-linux-x64-2.291.1.tar.gz# Optional: Validate the hash
                $ echo "1bde3f2baf514adda5f8cf2ce531edd2f6be52ed84b9b6733bf43006d36dcd4c  actions-runner-linux-x64-2.291.1.tar.gz" | shasum -a 256 -c# Extract the installer
                $ tar xzf ./actions-runner-linux-x64-2.291.1.tar.gz'
                # Create the runner and start the configuration experience
                $ ./config.sh --url https://github.com/glcp --token AFIKKOFCJME3N4S2YCIAUUDCRP34I

3. See error

            ""./bin/libcoreclr.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/libcoreclr.so)
            ./bin/libcoreclr.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by ./bin/libcoreclr.so)
            ./bin/libSystem.Security.Cryptography.Native.OpenSsl.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/libSystem.Security.Cryptography.Native.OpenSsl.so)
            ./bin/libSystem.IO.Compression.Native.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/libSystem.IO.Compression.Native.so)
            ./bin/Runner.Listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/Runner.Listener)

**Expected behavior**

Expected to create the runner and start the configuration experience

## Runner Version and Platform
Version of your runner?
2.291.1

OS of the machine running the runner? OSX/Windows/Linux/...
Red Hat Enterprise Linux Server release 6.6 (Santiago)

## What's not working?
Please include error messages and screenshots.

./bin/libcoreclr.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/libcoreclr.so)
./bin/libcoreclr.so: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by ./bin/libcoreclr.so)
./bin/libSystem.Security.Cryptography.Native.OpenSsl.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/libSystem.Security.Cryptography.Native.OpenSsl.so)
./bin/libSystem.IO.Compression.Native.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/libSystem.IO.Compression.Native.so)
./bin/Runner.Listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/Runner.Listener)

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by fhammerl** [comment]
Hi @cguttapalli, thanks for reporting this. As far as I understand, RHEL 6 end of life was scheduled for Nov. 30, 2020. 

If you are required to use RHEL 6, I would try [manually updating GLIBC](https://stackoverflow.com/a/41107733) and trying again, although there may be other missing dependencies.

**Comment by nikola-jokic** [comment]
I am going to close this issue until we hear back from you. If the answer above does not help, feel free to re-open it :relaxed:

**Comment by chandrakanthbala** [comment]
@nikola-jokic @fhammerl What is the most recent runner version that supports RHEL6? 

And the link for RHEL6 dependencies shows "not found". Can you please provide the new link for that documentation?

**Comment by chandrakanthbala** [comment]
@cguttapalli Can you please let me know if you found a way to setup GitHub Runner on RHEL 6?
