### ISSUE TITLE
Runner removal command not matching the runner's environment shell

### ISSUE THREAD

**Issue by thomas-coveros** [actions/runner#1918]
**Describe the bug**
When attempting to remove a self hosted runner created in a Windows environment, the auto-generated command doesn't match the runner's environment, for this example, the command is for a bash shell, not a PowerShell.
The command should start with ./config.cmd not a ./config.sh .

**To Reproduce**
1. Create a self hosted runner in a Windows environment. Notice that the auto-generated commands match the chosen environment, in this case Windows.
2. Execute the provided command to start the runner, verify the runner is added to the repository.
3. Remove the runner. After providing the GitHub account password upon clicking the "Remove" button, note that the command to remove the runner uses ./config.sh instead of ./config.cmd .

**Expected behavior**
The auto-generated command should start with the runner's environment shell language, in this case PowerShell; ./config.cmd

## Runner Version and Platform
win-x64-2.291.1

## OS version
Windows 11 Pro 21H2 (OS Build 22000.675)

## What's not working?
Notice the wrong command as in ./config.sh
![image](https://user-images.githubusercontent.com/105665690/170630623-d720c1d8-4223-46ad-9689-e9825c8e1a10.png)

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A

**Comment by ruvceskistefan** [comment]
Hi @thomas-coveros,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally, specifically UI part of it. Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃

**Comment by thomas-coveros** [comment]
I'll do, thanks for the correction!
