### ISSUE TITLE
Runner service on Windows fails to start with the default user

### ISSUE THREAD

**Issue by lucascosti** [actions/runner#192]
## Runner Version and Platform
actions-runner-win-x64-2.160.2

Windows Server 2019 Standard (1809)

## What's not working?
If a user runs a powershell in a Windows user directory, and tries to use the default suggested user for running installing a service (`NT AUTHORITY\NETWORK SERVICE`), the config script completes successfully and says the service is running, but the service never actually successfully starts.

@thboop has identified that this is due to `NT AUTHORITY\NETWORK SERVICE` not having permissions to the user directory to start the service.

I have suggested that we add this extra paragraph to the 'Add runner' modal for adding a runner:

> Note: If you want to install the runner application as a service, you must open a shell with administrator privileges. We also recommend that you use `C:\actions-runner` as the directory for the runner application so that Windows system accounts can access the runner directory.

The [above note has been added to the docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/adding-self-hosted-runners), but IMO, it should also be in the modal UI. 

Failing powershell run below:

```
PS C:\Users\Lucas Costi\actions-runner> ./config.cmd --url https://github.com/lucascosti/actions-private-playground --token ABB2TGV5QRUAQRVT4DONCU25YXSSO

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration

Enter the name of runner: [press Enter for WIN-9L5VTRV5F51] win

√ Runner successfully added
√ Runner connection is good

# Runner settings

Enter name of work folder: [press Enter for _work]

√ Settings Saved.

Would you like to run the runner as service? (Y/N) [press Enter for N] y
User account to use for the service [press Enter for NT AUTHORITY\NETWORK SERVICE]
Granting file permissions to 'NT AUTHORITY\NETWORK SERVICE'.
Service actionsrunner.cT09lfQ8MbjRkaUM211SBR82j32Te65GnVI5TvwNaRzz0HCzOU.Default.win successfully installed
Service actionsrunner.cT09lfQ8MbjRkaUM211SBR82j32Te65GnVI5TvwNaRzz0HCzOU.Default.win successfully set recovery option
Service actionsrunner.cT09lfQ8MbjRkaUM211SBR82j32Te65GnVI5TvwNaRzz0HCzOU.Default.win successfully set to delayed auto start
Service actionsrunner.cT09lfQ8MbjRkaUM211SBR82j32Te65GnVI5TvwNaRzz0HCzOU.Default.win successfully configured
Service actionsrunner.cT09lfQ8MbjRkaUM211SBR82j32Te65GnVI5TvwNaRzz0HCzOU.Default.win started successfully
PS C:\Users\Lucas Costi\actions-runner> Get-Service "actionsrunner.*"

Status   Name               DisplayName
------   ----               -----------
Stopped  actionsrunner.c... GitHub Actions Runner (cT09lfQ8MbjR...


PS C:\Users\Lucas Costi\actions-runner> Start-Service "actionsrunner.*"
Start-Service : Failed to start service 'GitHub Actions Runner
(cT09lfQ8MbjRkaUM211SBR82j32Te65GnVI5TvwNaRzz0HCzOU.Default.win)
(actionsrunner.cT09lfQ8MbjRkaUM211SBR82j32Te65GnVI5TvwNaRzz0HCzOU.Default.win)'.
At line:1 char:1
+ Start-Service "actionsrunner.*"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
```

**Comment by thboop** [comment]
Filed an internal issue to get this fixed

**Comment by pokepoke81** [comment]
I just ran into this issue myself with the Windows setup. It still defaults in the documentation to the user profile.

**Comment by MichaelVoelkel** [comment]
Yep, I also did right now. Did you stop maintaining some parts of GitHub altogether? This is a very central, user-facing issue

**Comment by guibranco** [comment]
I had the same issue just now, in my Win11 laptop (I make it to work in a Windows Server 2016 yesterday, but in my personal laptop it doesn't work)

**Comment by kaltrin91** [comment]
i think it has to do with the user that its setup in the default settings, I changed the "Log on as" settings in the Github Actions Runner service to a local system account and it worked

**Comment by barrownicholas** [comment]
I'm just coming across this now, and it should really be documented better and replace the default setup steps. Solution above works like a charm.

**Comment by deckar01** [comment]
I looks like I have to delete the runner and start over as admin, because the service config logic is in a binary, and there are no docs on what the service needs. Please mention this at the beginning of the setup.
