### ISSUE TITLE
workflow_dispatch limited to 10 input values

### ISSUE THREAD

**Issue by gfrid** [actions/runner#1928]
workflow_dispatch limit issue of 10 input values has been opened and closed in 2021. Still no solution for this in 2022.
you need to remove this limit is a blocker of CI/CD.

**Comment by gfrid** [comment]
still no response

**Comment by AshwiniRaskar** [comment]
Is this resolved ?Any way to pass more than 10 params to github actions

**Comment by nikola-jokic** [comment]
Hey @gfrid,

Sorry for the late response :disappointed: . 
This issue does not affect the runner. It concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team.
