### ISSUE TITLE
Ephemeral runner doing unnecessary cleanup

### ISSUE THREAD

**Issue by zhiwei-arbo** [actions/runner#1929]
**Describe the enhancement**
We are self-hosting Github runners, running them in ephemeral mode. This means the whole pod gets cleaned up after the job. However, we've noticed that the runner does a [CleanupTempDir](https://github.com/actions/runner/blob/be9632302ceef50bfb36ea998cea9c94c75e5d4d/src/Runner.Worker/TempDirectoryManager.cs#L48) after the jobs, which takes significant amount of time for us (due to large number of files and size in our Bazel build) and seems to be redundant

Skipping the cleanup for Ephemeral steps might be possible here

**Code Snippet**
N/A

**Additional information**
N/A

**Comment by nikola-jokic** [comment]
Hi @zhiwei-arbo,

Thank you for submitting this enhancement. I added it to the board, and it will be considered in the future :relaxed:

**Comment by akanieski** [comment]
#2016  should address this if the team feels it fits.

**Comment by aktech** [comment]
*Disclaimer: This doesn't answers the actual question, but suggests an alternative:*

You can achieve this easily with https://cirun.io/ It creates on demand **ephemeral** runners for GitHub Actions on your cloud and manages the complete lifecycle. You simply connect your cloud provider and define what runners you need in a simple yaml file and that's it.

See https://docs.cirun.io/reference/examples.html#aws for example.
