### ISSUE TITLE
Docs: Incorrect Ubuntu version support spec

### ISSUE THREAD

**Issue by WoodyWoodsta** [actions/runner#1941]
**Describe the bug**
The [docs suggest](https://github.com/actions/runner/blob/main/docs/start/envlinux.md?plain=1#L13) that Ubuntu 22.04 is supported, but this is untrue as described in https://github.com/actions/runner/issues/1584

Either https://github.com/actions/runner/pull/1585 needs some attention, or the documentation needs to change.

**Comment by nikola-jokic** [comment]
Hey @WoodyWoodsta , 

Since the [PR](https://github.com/actions/runner/pull/1946/files) has been merged, I am closing this issue.

**Comment by WoodyWoodsta** [comment]
Thanks @nikola-jokic!
