### ISSUE TITLE
GitHub Custom Runner Release Process

### ISSUE THREAD

**Issue by elgohr** [actions/runner#1953]
Hi,

first of all, sorry for violating the issue template.
The GitHub Standard Support told be to post this here - so I'll do that.

Could you please provide details about the actions GitHub takes to ensure the security of the custom GitHub actions runner?
As the runner contains a self-updating mechanism, it would help to see how a malicious update is prevented.

When I got it correct from https://github.com/actions/runner/blob/main/.github/workflows/release.yml , pushing https://github.com/actions/runner/commits/main/releaseVersion or workflow_dispatch triggers the release.

As releaseVersion has only be modified 3 times, I would expect the rest of the releases to have been triggered by workflow_dispatch.
Could you please share some more insights on this part? What is happening before workflow_dispatch?

As I can't find anything about a signature in https://github.com/actions/runner/blob/100c99f2635be35c7ea690c58fa7d203725cac9e/src/Runner.Listener/SelfUpdater.cs, I'm assuming that the trust-relation of the self-updater is based on the security of HTTPS. Is this correct?

**Comment by TingluoHuang** [comment]
@elgohr 
- We create a separate release branch (ex: `releases/m294`) every time releasing a newer version runner, so we can patch the release in case we found bugs and keep the `main` branch moving forward.
- The `https://github.com/actions/runner/blob/main/.github/workflows/release.yml` will be triggered by either updating the `releaseVersion` or using `workflow_dispatch` to compile a binary and publish the binary as release assets in the `actions/runner` repository. 
- We will run through a set of tests to make sure the runner is working as expected.
- We will run through a set of deployments internally to start allowing older version runners to self-update to the latest version by stages (normally take days for safe rollout practice)
- In addition to the https, we do [validate the package hash](https://github.com/actions/runner/blob/100c99f2635be35c7ea690c58fa7d203725cac9e/src/Runner.Listener/SelfUpdater.cs#L532) during the update progress. 

I hope this answers your question?

**Comment by elgohr** [comment]
Hey @TingluoHuang ,
thank you for the insights :-)
There's just one more: Do you also test for unexpected behaviour (e.g. introduced by a supply chain attack)?

**Comment by TingluoHuang** [comment]
Not really I think, we rely on the `GitHub dependabot` to tell us whether there is any issue in the supply chain.
We make sure our process has proper branch protection rules setup, and need peer/manager approval for doing certain deployment operations.

**Comment by elgohr** [comment]
Great, thank you
