### ISSUE TITLE
Jobs not being created and idle runners not picking up existing job retries

### ISSUE THREAD

**Issue by waeljammal** [actions/runner#1957]
**Describe the bug**

Last week our pipelines were running fine but we were on a trail enterprise account, this morning we added our billing details, etc. thinking we would just continue work as usual, however, all our existing pipelines now refuse to restart and pushing updates to pull requests do not trigger new workflows at all, nothing appears in the actions list. These pull requests have no merge conflicts either.

When this happened we also upgraded our runners to the latest 2.293.0, all runners are listed as idle in the organization and are visible in each repo for use as well, all as it was before the weekend.

The only thing we see in the runner logs that might have any relevance here is this like.

```
X-TFS-ServiceError: The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27+is+not+authorized+to+access+this+resource.
```

**To Reproduce**
No idea, it was working last week and now it's totally dead, we can't even use the github provided runners our repo just does not create any new runs or replay existing runs.

**Expected behavior**

Creating a pull request, running one of our manual workflows or updating a pull request should be triggering our pipelines but it is not and nothing has changed since it was working last week apart from adding our billing details and activating our enterprise account.

## Runner Version and Platform
Version of your runner?
2.293.0

OS of the machine running the runner? OSX/Windows/Linux/...
Tried Ubuntu 18.04lts VM and we have 4 runners in Kubernetes running on EKS

## What's not working?
Please include error messages and screenshots.

![Screenshot 2022-06-20 at 5 22 32 pm](https://user-images.githubusercontent.com/140032/174644361-166ba113-6896-454e-ad18-9f2e1285b1f3.png)

![Screenshot 2022-06-20 at 5 23 40 pm](https://user-images.githubusercontent.com/140032/174644458-23b3b40a-8a25-49f5-ada6-70e48f774605.png)

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

```
[2022-06-20 14:59:08Z INFO MessageListener] No message retrieved from session '6cded060-764c-4526-a1a8-8c757c950bb5' within last 30 minutes.
[2022-06-20 15:24:12Z WARN GitHubActionsService] Authentication failed with status code 401.
Transfer-Encoding: chunked
WWW-Authenticate: Bearer
Strict-Transport-Security: max-age=2592000
X-TFS-ProcessId: 29016053-ac86-4708-aec2-4c8c8ba5df7e
ActivityId: ecdd0983-1d7e-444b-80fa-7ca0328ef96b
X-TFS-Session: 96408467-8750-4d46-82c8-52ce9e77b385
X-VSS-E2EID: 5eb3214c-9df8-4c49-a376-5e87a1a72712
X-VSS-SenderDeploymentId: fc1cfc90-fc40-edcb-6d0f-3b1380ee7b68
X-TFS-ServiceError: The+user+%27System%3aPublicAccess%3baaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa%27+is+not+authorized+to+access+this+resource.
X-VSS-S2STargetService: 0000005A-0000-8888-8000-000000000000/visualstudio.com
X-Cache: CONFIG_NOCACHE
X-MSEdge-Ref: Ref A: 895BBE2AD637490AA071D97E8854F6E8 Ref B: LON21EDGE1411 Ref C: 2022-06-20T15:24:12Z
Date: Mon, 20 Jun 2022 15:24:11 GMT
```

**Comment by waeljammal** [comment]
The repository is private, are the links still useful to you?

**Comment by TingluoHuang** [comment]
@waeljammal yes, with private repo we won't see any content of your private repo even if you share the URL with us.
but those URLs can help us find any error in the system that scoped to your repository.

**Comment by waeljammal** [comment]
> @waeljammal yes, with private repo we won't see any content of your private repo even if you share the URL with us. but those URLs can help us find any error in the system that scoped to your repository.

I think I posted the links after you responded. Please find them below and thanks for your prompt response in regards to this matter our entire dev team is being blocked at the moment.

https://github.com/azarc-io/verathread
https://github.com/azarc-io/verathread/actions/runs/2516014162

**Comment by waeljammal** [comment]
Hi, woke up this morning to find that jobs are being picked up again. Not sure if it resolved itself but either way thanks for the help, I'm going to close this ticket now.

**Comment by kevjumba** [comment]
We are actually having the same issue. All of our github runners are idle and the github actions for integration tests are hanging. e.g https://github.com/feast-dev/feast/runs/6991139372?check_suite_focus=true

**Comment by surazregmy** [comment]
Hi.. How did it automatically picked? I have similar issues and runners are idle.

**Comment by ccpp** [comment]
@kevjumba @surazregmy @waeljammal I have the same issue. Was this also resolved automagically for you?
