### ISSUE TITLE
Not able to run self-hosted runner application as a service on startup

### ISSUE THREAD

**Issue by aditishah-dev** [actions/runner#1958]
**Describe the bug**
Getting "Offline" status after starting up mac.  We have added self hosted runner in Mac M1 as per the documentation.
And then performed steps given in the [document](https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service) to start self hosted runner application on startup. 

Note that If we run ./run.sh manually then my runner is starting up properly and taking jobs from Github as self hosted runner. 
So the problem occurs with the "Running runner app on startup". 

**To Reproduce**
1. Install Github runner for Mac M1 ARM 
2. Setup self-hosted runner as service on startup
3. stderr.log 
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/USER/Downloads/actions-runner/runsvc.sh: Operation not permitted
```

**Expected behavior**
Service should be started on starting up mac and Github -> actions-> runner should show "Idle" state.

## Runner Version and Platform
Version of your runner?
actions-runner-osx-arm64-2.293.0

OS of the machine running the runner? OSX/Windows/Linux/...
Mac OS - ARM64

**Comment by TingluoHuang** [comment]
@aditishah-dev you will need to give `/bin/sh` full disk access to fix that error.
https://www.symscape.com/node/1727

**Comment by aditishah-dev** [comment]
@TingluoHuang Thanks for the solution!
I tried to setup runner again after adding /bin/sh as per steps given in link but faced same error.  
As per error, Operation not permitted coming from /bin/bash. so I have added access to /bin/bash and tried again. And now I am able to see Idle status after restarting mac.

**Comment by BrentMifsud** [comment]
im seeing the same problem.

Even after giving sh full disk access.

The runner service says started. But when I go to my list of runners it says 'offline'

run.sh works fine

**Comment by BrentMifsud** [comment]
ok I tried the following and got it working:

1. add `/bin/sh` to list of apps with full disk permission
2. run `./svc.sh uninstall`
3. run `./svc.sh install`
4. run `./svc.sh start`

seems as though the lack of disk permissions breaks the install. But it doesn't really tell you that anything is wrong.
