### ISSUE TITLE
Support for Windows Server 2022

### ISSUE THREAD

**Issue by EricStG** [actions/runner#1980]
**Describe the enhancement**
I would like Windows Server 2022 to be supported by the runner

**Code Snippet**
N/A

**Additional information**
According to [/docs/start/envwin.md](https://github.com/actions/runner/blob/main/docs/start/envwin.md), the latest supported version of Windows Server is 2019. Since Github hosted runners do run on Windows Server 2022, we should be able to do the same on self-hosted runners.

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by AvaStancu** [comment]
Hey @EricStG,
Thank you for your interest in the runner application and taking the time to provide your valuable feedback. We kindly ask you to redirect this feedback to the [GitHub Community Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests in GitHub Actions. [Read more about our guidelines here.](https://github.com/actions/runner/blob/main/docs/contribute.md)
