### ISSUE TITLE
An error occurred: Runner version v2.291.1 is deprecated and cannot receive messages.

### ISSUE THREAD

**Issue by arunkumar-telnyx** [actions/runner#1991]
**Describe the bug**
An error occurred: Runner version v2.291.1 is deprecated and cannot receive messages.

**To Reproduce**
1) Use a self hosted runner with the version 2.291.1 in k8s

**Expected behavior**
When you try to run a github action using that self hosted runner , it should throw an error : 
```
Waiting for a runner to pick up this job...
```

Logs 
```
√ Connected to GitHub

Current runner version: '2.291.1'
2022-07-11 15:34:21Z: Listening for Jobs
An error occurred: Runner version v2.291.1 is deprecated and cannot receive messages.
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Restarting runner...
```

## Runner Version and Platform
2.291.1  in k8s 

OS of the machine running the runner? OSX/Windows/Linux/...
Ubuntu

## What's not working?
Unable to pick up and run github action jobs

## Job Log Output
```
√ Connected to GitHub

Current runner version: '2.291.1'
2022-07-11 15:34:21Z: Listening for Jobs
An error occurred: Runner version v2.291.1 is deprecated and cannot receive messages.
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Restarting runner...
```

Kindly confirm if the issue is because of the older version and needs to be upgraded to resolve the same.

**Comment by nikola-jokic** [comment]
Hey @arunkumar-telnyx,

I am going to close this issue now, but for more context, you can refer to the comment https://github.com/actions/runner/issues/1843#issuecomment-1183295528 :relaxed:
