### ISSUE TITLE
Ubuntu-latest: Podman build failure: Connection reset by peer

### ISSUE THREAD

**Issue by ebattat** [actions/runner#1994]
Starting to get the following error **from 7/12 (Github actions change)**  when running podman build inside ubuntu-latest container:
**error running container: error from /usr/bin/crun creating container for [/bin/sh -c dnf update -y --nobest]: sd-bus call: Connection reset by peer**

Example for our failed build:
The full GitHub actions [link](https://github.com/redhat-performance/benchmark-runner/runs/7306853603?check_suite_focus=true)
The same workflow run successfully several days ago, [link](https://github.com/redhat-performance/benchmark-runner/runs/7229627245?check_suite_focus=true)

Steps to reproduce

```
name: Podman test
on:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Create container
        run: |
          cat <<EOF | sudo podman build -t test-container -f - .
          FROM fedora:36
          RUN echo test
          EOF
Output:

STEP 1/2: FROM fedora:36
Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:36...
Getting image source signatures
Copying blob sha256:75f075168a24344c81b41a4877ffc6005723793ced6424f20b5f3ee9d6a66b57
Copying blob sha256:75f075168a24344c81b41a4877ffc6005723793ced6424f20b5f3ee9d6a66b57
Copying config sha256:3a66698e604003f7822a0c73e9da50e090fda9a99fe1f2e1e2e7fe796cc803d5
Writing manifest to image destination
Storing signatures
STEP 2/2: RUN echo test
error running container: error from /usr/bin/crun creating container for [/bin/sh -c echo test]: sd-bus call: Connection reset by peer
: exit status 1
```

[For more detail ](https://github.community/t/error-running-container-error-from-usr-bin-crun-creating-container-for-bin-sh-c-dnf-update-y-nobest-sd-bus-call-connection-reset-by-peer-1994/261522/4)

**Workaround for GitHub actions till fix: **
`sudo -E XDG_RUNTIME_DIR= podman build -t test-container -f - . `

**Comment by ebattat** [comment]
Hi @[enhaut](https://github.com/enhaut)

Saw you added it to your tests ,this is just a workaround:
`sudo -E XDG_RUNTIME_DIR= podman build -t test-container -f - .`

Is any plan to fix it ?

**Comment by nikola-jokic** [comment]
Hey @ebattat,
 
This issue does not seem to be a problem with the runner application, it concerns the software on machines running GitHub's hosted runners. Could you please post your issue in the [Virtual Environments Repository](https://github.com/actions/virtual-environments/issues/new/choose) to ensure the correct team sees it. :smiley:

**Comment by nikola-jokic** [comment]
I will close this issue now since it is not related to the runner :relaxed:
