### ISSUE TITLE
Could not find a part of the path '/proc/1/cgroup' with container 

### ISSUE THREAD

**Issue by vinizup** [actions/runner#2007]
Attempting to use a job-container on my personal runner in ec2 (linux amazon), fails with the error message: Could not find a part of the path '/proc/1/cgroup'

Here is the repro:

on: [push]
jobs:
  build:
    runs-on:  developer 
    container: node:1.18
    steps:
      - run: printenv|sort

**Comment by jsoref** [comment]
Technically, your code is tripping on:
https://github.com/actions/runner/blob/591f8c351058ed1251ecf04a4195ff83a6828e12/src/Runner.Worker/ContainerOperationProvider.cs#L503

I suspect it means your AWS base Image doesn't have cgroups enabled, and cgroups are probably required by the Linux runner.

**Comment by nqb** [comment]
Hello,
I got exactly same bug on my side.
My self-hosted runner application runs as service under `github-runner` user (standard user). If I switch to `root`, I didn't have this bug anymore.
Any idea @jsoref or @vinizup ?

**Comment by philipbalinov** [comment]
@g

> Technically, your code is tripping on:
> 
> https://github.com/actions/runner/blob/591f8c351058ed1251ecf04a4195ff83a6828e12/src/Runner.Worker/ContainerOperationProvider.cs#L503
> 
> I suspect it means your AWS base Image doesn't have cgroups enabled, and cgroups are probably required by the Linux runner.

this will also occur on hardened systems where the `/proc` filesystem is mounted with the `hidepid` option. Switching the check to `/proc/self/cgroup` as in the PR fixes the issue.
