### ISSUE TITLE
Self-hosted runners - remote Docker daemon

### ISSUE THREAD

**Issue by jbdazn** [actions/runner#2023]
**Describe the enhancement**
For running our self-hosted runners, we are using an ECS cluster. Every ECS task executing a runner comes with a sidecar container running a Docker daemon used by our runner over TCP and/or a Unix socket on a shared volume. The runner is able to execute containers but there is no logic for creating a volume in the remote daemon with the current workspace. It prevents us from using containers for jobs or steps without having to manually create the volume and copy the workspace there.

The enhancement I would like to see is the ability to tell the runners that we want to use a remote Docker daemon and having the runner software performing the volume creation in the remote Docker daemon and copying to the remote volume the current workspace to keep the same experience as if the Docker daemon was running on the same system as the runner.

**Code Snippet**
not applicable.

**Additional information**
Our architecture is designed for providing Docker based runners running in ECS / Fargate. We are using the `--ephemeral` flag to ensure that only one job runs in our ECS task instances. The Docker daemon is ran in a separated container to prevent the execution of the runners in privileged mode and to keep a single process per container. Also, our ECS agents run on Amazon Linux 2022 allowing us to configure the agent Docker Daemon for using cgroup v2 and systemd as cgroup driver. We have full isolation for every embedded Docker Daemon as they get their own user namespace (two jobs running on our ECS agent can't see each other containers). To ensure network isolation, our runners are using the "awsvpc" network mode ensuring that every single instance gets its own elastic network interface and the TCP port for the Docker daemon is not exposed outside the network namespace of the ECS task instance. We are also providing providing different pools of ECS agents to provide support for ARM64 and AMD64 on Linux, for now.

**Comment by nikola-jokic** [comment]
Hey @jbdazn, thank you for reporting this issue!

The issue has been added to the board. In the meantime, you can customize the way container actions are performed by leveraging [container hooks](https://github.com/actions/runner-container-hooks). More information about container hooks can be found [here](https://docs.github.com/en/actions/hosting-your-own-runners/customizing-the-containers-used-by-jobs)
