### ISSUE TITLE
Make it possible to re-run jobs with a different actor

### ISSUE THREAD

**Issue by romainmenke** [actions/runner#2034]
see : https://github.blog/changelog/2022-07-19-differentiating-triggering-actor-from-executing-actor/

This broke our setup where we do not give any access to secrets to dependabot.
Instead we used to re-run the failed jobs manually.

This gave us the chance to review each pull request opened by dependabot manually before secrets would be exposed.

Now that the actor is stable we can no longer make CI pass on these pull requests.

**Comment by thyeggman** [comment]
I'd need a bit more context on your particular setup, but is there any reason you haven't chosen to [give Dependabot access to secrets](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-encrypted-secrets-for-dependabot) it needs?  The secrets are encrypted end-to-end, so they never reach GitHub unencrypted.

Unfortunately, for security reasons, we cannot allow users to impersonate other actors.

**Comment by romainmenke** [comment]
> but is there any reason you haven't chosen to [give Dependabot access to secrets](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-encrypted-secrets-for-dependabot) it needs?

That would mean giving all dependencies and their future updates access to secrets without any human involved. Would be a massive security issue :D

_I am not even sure why there is the option to give access to secrets on runs initiated by dependabot pull requests but that is outside of the scope of this issue._

> Unfortunately, for security reasons, we cannot allow users to impersonate other actors.

I should have worded this better.
I do not want to re-run as someone else.
I want to re-run a workflow as me instead of the original actor.

Any pull request opened by dependabot in our setup would just fail CI because it doesn't have access to secrets.

After manual review of the updated dependencies we used to be able to re-run the (failed) workflows.
These re-runs would have access to secrets as I (or a team member) has access to those secrets.

**Comment by thyeggman** [comment]
There are a few workarounds that might work if you don't want to give dependabot access to secrets.

1) Close and reopen the pull request.  If your workflow uses the [`pull_request` event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), `reopened` is one of the activity types that triggers it without additional syntax.  It should run as the user that reopened the workflow.
2) Use a different workflow trigger like `pull_request:labeled`, and label the pr with something like "Reviewed" when you want the workflow to run.  The workflow will run as the person who labeled the PR.

There are other events that might be useful in the documentation I linked, hopefully one of them fits your use case.

**Comment by romainmenke** [comment]
Thank you for those alternatives!

I was also going to try using a different target branch for dependabot.
The CI would still fail initially but after merge it would trigger a workflow run with me as the actor on the different target branch.

I think there are enough work arounds so that no change is required.
Thank you for taking the time to look into this!
