### ISSUE TITLE
In svc.sh, disable service also when stopping, enable when starting

### ISSUE THREAD

**Issue by drq883** [actions/runner#2060]
**Describe the enhancement**

We've been testing out the number of runners per machine to satisfy our action load to help minimize queuing. I have a script to stop or start any number of these runners using the svc.sh script. However, if the self-hosted runner host were to reboot, all the runner servers (that were stopped) start back up since they aren't disabled. Please consider disabling/enabling the service when it is stopped/started.

**Code Snippet**
```
--- systemd.svc.sh.template.orig	2022-06-22 12:08:07.000000000 -0400
+++ systemd.svc.sh.template	2022-08-17 06:28:43.742276832 -0400
@@ -105,12 +105,14 @@
 function start()
 {
     systemctl start ${SVC_NAME} || failed "failed to start ${SVC_NAME}"
+    systemctl enable ${SVC_NAME} || failed "failed to enable ${SVC_NAME}"
     status    
 }
 
 function stop()
 {
     systemctl stop ${SVC_NAME} || failed "failed to stop ${SVC_NAME}"    
+    systemctl disable ${SVC_NAME} || failed "failed to disable ${SVC_NAME}"
     status
 }
```
I'm not sure how to update the darwin template.

**Additional information**
Add any other context about the feature here.

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by nikola-jokic** [comment]
Hey @drq883,

Can you please redirect this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages)? Using this forum is a better place to start a discussion for feature requests, and will help us prioritize enhancements. :relaxed:
