### ISSUE TITLE
Make "remove" work with --unattended: Removes all config for ephemeral and regular runners

### ISSUE THREAD

**Issue by na-jakobs** [actions/runner#2061]
**Describe the enhancement**
We use ephemeral runners and sometimes end up with stale config. Can you make the **remove** command work with the --unattended flag?

Outcome would be a local cleanup of all config, skipping the remote runner deregistration.

**Code Snippet**
Running:
```./config.sh --unattended remove``` 
would work and remove all local config.

**Additional information**
None

**Comment by TingluoHuang** [comment]
Will `rm -f .runner .credentials .credentials_rsaparams` help in your case, if you just want to delete the local config?
