### ISSUE TITLE
Runner for AIX  / PowerPC 

### ISSUE THREAD

**Issue by kidharbachan** [actions/runner#2070]
Are there any plans to support a self hosted runner for AIX / PowerPC?

**Comment by AvaStancu** [comment]
Hey @kidharbachan,

Thank you for your interest in the runner application. We kindly ask you to redirect this question to the [GitHub Community Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team monitors and would be a better place to start a discussion for new feature requests in GitHub Actions. [Read more about our guidelines here.](https://github.com/actions/runner/blob/main/docs/contribute.md)
