### ISSUE TITLE
How can I test my action case in my local compueter ?

### ISSUE THREAD

**Issue by SAMZONG** [actions/runner#2073]
Hi, I want be a deveoper of the github action.

I'm a little confused about how I should test my program on my local computer.

**Comment by tmguillem** [comment]
Suggestion:
https://github.com/nektos/act

**Comment by SAMZONG** [comment]
> Suggestion: https://github.com/nektos/act

Thanks a lot

**Comment by nikola-jokic** [comment]
Thanks @tmguillem for answering! 

We currently don't support this feature, but you can leverage other open source projects like suggested :relaxed:.
