### ISSUE TITLE
Allow "injection" of steps to reusable workflows

### ISSUE THREAD

**Issue by flobernd** [actions/runner#2079]
**Describe the enhancement**

Reusable workflows are a great enhancement, but still limited e.g. compared to Azure DevOps templates. It would be great if we have some way to inject steps into a reusable workflow.

Possible implementations:

- https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#use-templatecontext-to-pass-properties-to-templates
- Allow `steps` keyword when using a reusable workflow and add another **mandatory** property like `run-before: {id}`/`run-after: {id}` to the `steps` context. The `{id}` specifies the id of the step inside the reusable workflow.
- Allow deserialization of individual steps using `- ${{ fromJson(...) }}`. This could be used inside a reusable workflow to dynamically insert a step based on e.g. an input argument.

**Additional information**

I implemented a reusable generic .NET test workflow. Sadly some of the tests require a SQL database to run, others a Redis server, and so on. We now have the option to either add a bunch of conditional dependency setup steps to the reusable action (which effectively destroys the generic aspect) or to stop using the reusable action at all.

**Comment by nikola-jokic** [comment]
Hey @flobernd,

Thank you for submitting this enhancement! It has been added to the board and considered in future enhancements :relaxed:

**Comment by casanova-21** [comment]
@nikola-jokic Hey! 👋 Can you give us an update on this one and whether or not it's made it onto your backlog or roadmap for this year? LinkedIn is asking about it.

**Comment by benwells** [comment]
Hey all!  Nikola brought this to my attention and I reached out to the Product Manager who owns reusable workflows (this feature is owned by a different team than the one @nikola-jokic and I are a part of).  The response was:

> In the long term, we want to provide support for step level insertion. However, currently, we are focusing on few other [improvements](https://github.com/github/roadmap/issues/636) in reusable workflows. At the moment, we don't have any concrete timelines but we will evaluate step templates support in CYQ3.

I would recommend redirecting this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions), which would be a more appropriate place to get the attention of the proper teams for this feature request.

**Comment by flobernd** [comment]
Thanks for the update. Posting in community forums on the other hand is like sending the message directly to /dev/null. None of my topics even got a single response yet... and I don't event blame you guys for not being able to properly monitor it. Just too much stuff, but pretty much pointless to post there any feature request.

**Comment by asottile** [comment]
for my use case I was able to make this work via a reusable local action

https://github.com/asottile/workflows/blob/v1.5.0/.github/workflows/tox.yml#L60

this checks for existence of the plugin point and then executes the action

you can see an example usage in https://github.com/pre-commit/pre-commit

**Comment by janosh** [comment]
is this being tracked anywhere? i wasn't able to find a request for this feature in https://github.com/orgs/community/discussions. seconding @flobernd's sentiment, maybe worth transfering this issue to the right issue tracker instead of closing
