### ISSUE TITLE
container exit itself after run it in github action

### ISSUE THREAD

**Issue by yunnysunny** [actions/runner#2081]
**Describe the bug**
I start run a docker container in github action and execute command to test on it. But it container exit silent when I call `docker exec`, it just showed container not running.

The script I used to test on it:

```shell
#!/bin/bash
set -ex

APP_PORT=4231
APP_ID=90945
APP_SECRET=232717ddf1893a9e39464b4752d451e61fc2e416
IMAGE_VERSION=${IMAGE_VERSION:-latest}
MY_NAME=myhello

docker build . -t ${MY_NAME} --build-arg APP_ID=${APP_ID} \
--build-arg APP_SECRET=${APP_SECRET} \
--build-arg IMAGE_VERSION=${IMAGE_VERSION}
# test command
container_id=$(docker run -e APP_PORT="${APP_PORT}" -p ${APP_PORT}:${APP_PORT}  -d ${MY_NAME})
docker exec -i "${container_id}" node -e "console.log(new Date().toString())"
docker exec -i "${container_id}" ps -ef | grep agent
sleep 3
curl http://localhost:${APP_PORT}
docker stop "${container_id}"
docker rm "${container_id}"
```

## Runner Version and Platform
Current runner version: '2.295.0'
Operating System
  Ubuntu
  20.04.4
  LTS

## Job Log Output
https://github.com/yunnysunny/alinode/runs/7987992638?check_suite_focus=true
```
Successfully built 712b1e60c5a7
Successfully tagged myhello:latest
++ docker run -e APP_PORT=4231 -p 4231:4231 -d myhello
+ container_id=692beb2d35074817fc7eff90ba85621ad08b59004e414bd6d60307009bbf351f
+ docker exec -i 692beb2d35074817fc7eff90ba85621ad08b59004e414bd6d60307009bbf351f node -e 'console.log(new Date().toString())'
Wed Aug 24 2022 13:25:24 GMT+0[80](https://github.com/yunnysunny/alinode/runs/7987992638?check_suite_focus=true#step:11:81)0 (China Standard Time)
+ grep agent
+ docker exec -i 692beb2d35074[81](https://github.com/yunnysunny/alinode/runs/7987992638?check_suite_focus=true#step:11:82)7fc7eff90ba[85](https://github.com/yunnysunny/alinode/runs/7987992638?check_suite_focus=true#step:11:86)621ad08b59004e414bd6d60307009bbf351f ps -ef
Error response from daemon: Container 692beb2d35074817fc7eff90ba85621ad08b59004e414bd6d60307009bbf351f is not running
make: *** [Makefile:13: test-hello] Error 1
Error: Process completed with exit code 2.
```

**Comment by fhammerl** [comment]
Hi @yunnysunny, thanks for reporting this issue.

Is it possible that the first exec (`docker exec -i "${container_id}" node -e "console.log(new Date().toString())"
`) somehow causes your entrypoint to exit? Do you experience the same if the execs are reversed?

Can you repro the issue locally, say with a `self-hosted` runner or using the command line to start this image and then exec the two commands?

Considering the problem happens while executing a shell script, rather than during any native runner code execution, this may not be a problem for this repo. If this is found to be the case, I'll redirect this issue to the community forums.

**Comment by yunnysunny** [comment]
I run the commands on my local machine, it works OK. I think the github action destory the docker container implicitly when the container started in backend in some case.

**Comment by callanchen** [comment]
I have the same issues. The runner makes the docker container crashed.

I use `docker exec ` to run a google test program.
