### ISSUE TITLE
Runner corrupts secrets containing backslashes

### ISSUE THREAD

**Issue by redlizard** [actions/runner#2089]
As of version 2.296.0, if the actions runner creates a docker container to execute an action which receives github secrets as environment variables, any backslash characters in the secret values get doubled. This results in the docker container receiving an incorrect value of the secret.

Commit https://github.com/actions/runner/commit/01fd04464d931699c6989f7c366a5ff3e155fe56 escapes all command line arguments to docker commands by replacing double-quote and backslash character with an escape sequence, which includes github secrets. This would work on unix, but the action runner dotnet framework uses the windows-native escape scheme, in which `\\` is not an escape sequence in most conditions. Thus, escaped backslashes in secret values are not interpreted correctly when starting a docker process using the resulting command line arguments.

**Comment by thboop** [comment]
Hey @redlizard thank you for the report we are digging into this issue.

Can you confirm if you are seeing this in [container actions ](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action)or just job/service [containers](https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container).

Do you have an example workflow yaml or action yaml you can provide?

**Comment by redlizard** [comment]
I am indeed seeing this in container actions, not service containers. I do not have a prepared testcase, but I could write one if necessary.

I do not think your solution posted here is quite correct. According to [this specification](https://docs.microsoft.com/en-us/previous-versions/17w5ykft(v=vs.85)), which I _think_ also applies to the dotnet process-spawning procedures, `\\` is an escape sequence _as long as it directly preceeds a quote character_; your solution does not implement this, and therefore reopens the problem fixed in #2062. Specifically, that means that in any sequence of backslash characters followed by a double-quote character, the backslashes act as escape characters; whereas in any other context, they are regular characters.

I have not checked that this specification does in fact apply to the process creation call used by the actions runner; it is only my best guess based on observed behavior so car. Caveat lector.

**Comment by redlizard** [comment]
I think #2091 solved it, and #2108 solved it better. I have not yet had the opportunity to test either of them, but it looks good to me on first glance.

**Comment by nikola-jokic** [comment]
Thank you, @redlizard, I will close this issue now but feel free to re-open it or submit another one if you see any problems with this :relaxed:
