### ISSUE TITLE
Self-hosted runners with rootless Docker broken after 2.296.1

### ISSUE THREAD

**Issue by quulah** [actions/runner#2103]
**Describe the bug**
We run self-hosted runners with rootless Docker set up.

After 2.296.1 hit, jobs with `container:` that worked previously, have now started failing in early stages.

Specifically in "Initializing containers" "Starting job container".

**To Reproduce**

**Expected behavior**

Well, it should work. :)

## Runner Version and Platform
Version of your runner?

2.296.1

OS of the machine running the runner? OSX/Windows/Linux/...

Ubuntu 20.04.4 LTS

## What's not working?

```
unable to resolve docker endpoint: context "rootless" does not exist
```

My best guess is that it is trying to talk to the `/var/run/docker.sock` instead of the rootless socket of the runner user, but setting `DOCKER_HOST` in the jobs does not help as it previously has for some cases such as building a container image within.

**Comment by quulah** [comment]
There's #827 which is most likely related, but until the recent update to the runner this has actually worked for us.

**Comment by quulah** [comment]
Pinning to 2.296.0 seems to have helped and our builds aren't failing anymore.

While I was at it, I set the `DOCKER_HOST` to point at the correct socket in the runner's `.env`. Not quite sure if that has an effect on this or not, but doesn't seem to hurt either.

**Comment by thboop** [comment]
Thanks for the report, we are working on a fix!

**Comment by quulah** [comment]
@hjokunbus I'm unsure whether your issue is related or not, but I suggest opening a new one in any case. Looks a bit different.

And [2.296.2](https://github.com/actions/runner/releases/tag/v2.296.2) seems to have fixed our problem, so I'll close this.
