### ISSUE TITLE
Environment variable "HOME=/github/home" now becomes "HOME" for self-hosted runner

### ISSUE THREAD

**Issue by coiby** [actions/runner#2104]
**Describe the bug**
Previously (2.295.0), `docker create` [was executed](https://github.com/coiby/kexec-tools/runs/8007120416?check_suite_focus=true) with `-e "HOME=/github/home"` now it [is executed](https://github.com/coiby/kexec-tools/runs/8204074915?check_suite_focus=true) with `-e "HOME"`. It seems this is reason why [the job container failed to start](https://github.com/coiby/kexec-tools/runs/8204074915?check_suite_focus=true) as this is only difference between the jobs run by runner 2.295.0 and 2.296.1 respectively. 

**To Reproduce**
1. re-run [this job](https://github.com/coiby/kexec-tools/runs/8204074915?check_suite_focus=true) 

**Expected behavior**

The runner call `docker create` with `-e "HOME=/github/home"`
 
## Runner Version and Platform
Version of your runner?
2.296.1

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?

Emulated Docker CLI using podman fails with the error "no such file or directory".

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by thboop** [comment]
Thanks for the report, we are working on a fix!

**Comment by nikola-jokic** [comment]
Hey, I will close this issue now since it has been resolved with the runner version `2.296.2`. Thank you @coiby for letting us know!
