### ISSUE TITLE
Github actions is 'skipping' output variable, breaking job builds

### ISSUE THREAD

**Issue by miguelmota** [actions/runner#2109]
**Describe the bug**

Github actions is skipping output variable on subsequent runs because it thinks it's a secret but it's not a secret at all

**To Reproduce**

Run https://github.com/hop-protocol/hop/blob/develop/.github/workflows/deploy.yml

See logs  https://github.com/hop-protocol/hop/actions/runs/3003891071

**Expected behavior**

Return output variable as normal

## What's not working?

Output variable being suppressed and job can't read it

## Job Log Output

![DeepinScreenshot_select-area_20220906195025](https://user-images.githubusercontent.com/168240/188777851-11c8eb61-bd7c-4973-9898-9d58f7193546.png)

**Comment by Link-** [comment]
Why don't you rename your output @miguelmota ?

**Comment by miguelmota** [comment]
Combining all the jobs into steps seems to have fixed it

Closing issue
