### ISSUE TITLE
actions are in queued but not in process.

### ISSUE THREAD

**Issue by taojintianxia** [actions/runner#2112]
as following screen shot, there are a lot of actions are in queued but none of these action are in process.
tried to cancel and re-run some actions, it still in queued. right now, there are more than 30 actions in queued and seems that it will get more and more actions blocked.

![image](https://user-images.githubusercontent.com/4112856/188908781-34ee3d29-00d2-4691-943a-4cc3f29d8774.png)

https://github.com/apache/shardingsphere/actions?query=is%3Aqueued

**Comment by thboop** [comment]
Hey @taojintianxia going to close this for now but please reopen if you see the issue again

**Comment by taojintianxia** [comment]
> 

I see, thanks
