### ISSUE TITLE
`.env` loading does not support all features of standard `.env` files.

### ISSUE THREAD

**Issue by Fleshgrinder** [actions/runner#2132]
```bash
# comments with equal signs = fail
DOUBLE_QUOTES="are literal"
SINGLE_QUOTES='are literal'
MULTILINE="is
not
possible"
```

Parsing of `.env` should be compliant with the reference implementation at https://github.com/motdotla/dotenv, but the current implementation is not: https://github.com/actions/runner/blob/3a1c89715cccc9ec2cf55c0903a8466de839d7fe/src/Runner.Listener/Program.cs#L136-L164

Please feel free to close this issue if you do not consider this to be a bug. However, in that case I would expect a formal definition of what kind of `.env` syntax is supported to avoid surprises for future users. ☺️

**Comment by nikola-jokic** [comment]
Hey @Fleshgrinder,

Thank you for submitting this issue! I applied appropriate labels and added this issue to the board :relaxed:

**Comment by bryanmacfarlane** [comment]
is there a standard?  I think this issue implies that because that one repo has a standard then that is an industry standard?

I think the standard of the runner env file is simple. the value is everything on the line after the first `=` char.   Just adding that to the docs makes it more clear and maybe that's the action item here.

**Comment by DARKo6o6o6** [comment]
Fix it

**Comment by Fleshgrinder** [comment]
There is no “standard” in form of an IETF RFC, just as there's no standard like that for Markdown. But there is a reference implementation that I referred to. It's fine to not consider this an issue, but at the very least the documentation should clearly explain the bespoke solution. I already wrote all of this in the issue description.
