### ISSUE TITLE
Error when running az acr login command from run step on Windows runner

### ISSUE THREAD

**Issue by stevenwolak** [actions/runner#2149]
**Describe the bug**

This is on a windows-2019 runner.

When attempting to run the following commands using the run action an error is thrown by the second command.  This sequence of commands used to complete without issue.

az login --service-principal -u <USER> -p <PASSWORD> --tenant <TENANT>
az acr login -n <ACR NAME>

**To Reproduce**
1. Set up a single run action to run the following commands on a windows-2019 runner
2. - name: Test ACR
    run: |
		az login --service-principal -u <USER> -p <PASSWORD> --tenant <TENANT>
		az acr login -n <ACR NAME>
3. Upon attempting az acr login, the following error is given:  Error: Process completed with exit code 1.

**Expected behavior**
Before the latest runner update, this worked correctly and the ACR was accessible with further steps/commands.

## Runner Version and Platform
Current runner version: '2.296.2'

OS of the machine running the runner? OSX/Windows/Linux/...

Image: windows-2019
  Version: 20220918.1
  Included Software: https://github.com/actions/runner-images/blob/win19/20220918.1/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win19%2F20220918.1

## What's not working?
It appears that when running the az acr login command it cannot find Docker.  As part of diagnosing this issue I added a step right before which does a simple `docker ps` command.  This command runs without issue and reports no running containers (as expected).

## Job Log Output
This output comes from running az acr login with the debug option enabled:

DEBUG: cli.knack.cli: Command arguments: ['acr', 'login', '-n', 'XXXXXXXXXX', '--debug']
DEBUG: cli.knack.cli: __init__ debug log:
Cannot enable color.
DEBUG: cli.knack.cli: Event: Cli.PreExecute []
DEBUG: cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0101B580>, <function OutputProducer.on_global_arguments at 0x0155F850>, <function CLIQuery.on_global_arguments at 0x0157D4A8>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: cli.azure.cli.core: Modules found from index for 'acr': ['azure.cli.command_modules.acr']
DEBUG: cli.azure.cli.core: Loading command modules:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands
DEBUG: cli.azure.cli.core: acr                       0.010        32       134
DEBUG: cli.azure.cli.core: Total (1)                 0.010        32       134
DEBUG: cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
DEBUG: cli.azure.cli.core: Loading extensions:
DEBUG: cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
DEBUG: cli.azure.cli.core: Total (0)                 0.000         0         0  
DEBUG: cli.azure.cli.core: Loaded 32 groups, 134 commands.
DEBUG: cli.azure.cli.core: Found a match in the command table.
DEBUG: cli.azure.cli.core: Raw command  : acr login
DEBUG: cli.azure.cli.core: Command table: acr login
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x03EB6928>]
DEBUG: cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to 'C:\Users\runneradmin\.azure\commands\2022-09-22.12-21-12.acr_login.1044.log'.
INFO: az_command_data_logger: command args: acr login -n *** --debug
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x03EDEB68>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x03EDEC40>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x03EF31D8>]
DEBUG: cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
DEBUG: cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0155F898>, <function CLIQuery.handle_query_parameter at 0x0157D4F0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x03EF3190>]
DEBUG: cli.azure.cli.command_modules.acr.custom: Could not run 'docker' command. Exception: [WinError 2] The system cannot find the file specified
DEBUG: cli.azure.cli.command_modules.acr.custom: Could not run 'docker.exe' command. Exception: [WinError 2] The system cannot find the file specified
WARNING: cli.azure.cli.command_modules.acr.custom: You may want to use 'az acr login -n XXXXXXXXXX --expose-token' to get an access token, which does not require Docker to be installed.
DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 354, in get_docker_command
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 361, in get_docker_command
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 288, in acr_login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 285, in acr_login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/custom.py", line 367, in get_docker_command
knack.util.CLIError: 2022-09-22 12:21:12.820874 An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.

ERROR: cli.azure.cli.core.azclierror: 2022-09-22 12:21:12.820874 An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.
ERROR: az_command_data_logger: 2022-09-22 12:21:12.820874 An error occurred: DOCKER_COMMAND_ERROR
Please verify if Docker client is installed and running.
DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03EB6A48>]
INFO: az_command_data_logger: exit code: 1
INFO: cli.__main__: Command ran in 1.291 seconds (init: 0.466, invoke: 0.824)
INFO: telemetry.main: Begin splitting cli events and extra events, total events: 1
INFO: telemetry.client: Accumulated 0 events. Flush the clients.
INFO: telemetry.main: Finish splitting cli events and extra events, cli events: 1
INFO: telemetry.save: Save telemetry record of length 3297 in cache
WARNING: telemetry.check: Negative: The C:\Users\runneradmin\.azure\telemetry.txt was modified at 2022-09-22 12:17:57.932691, which in less than 600.000000 s
Error: Process completed with exit code 1.

**Comment by sherriedcss** [comment]
any resolution?
