### ISSUE TITLE
Which command should handle broken symlinks

### ISSUE THREAD

**Issue by dhadka** [actions/runner#2150]
**Describe the bug**

https://github.com/actions/runner/blob/main/src/Runner.Sdk/Util/WhichUtil.cs should detect and ignore broken symlinks.  This should be considered a bug as calling the native `which` command will detect and ignore the broken symlink.

**To Reproduce**

See https://github.com/dhadka/repro-broken-symlink/actions/runs/3106185147/jobs/5032737959 for an example.  Here I'm creating a broken symlink for `pwsh` and then trying to run Powershell using `shell: pwsh` and through bash with `run: pwsh -Command ...`.

`shell: pwsh` fails because it's using the custom `WhichUtil` implementation, matches the broken symlink, and fails with `An error occurred trying to start process '/usr/local/bin/pwsh' with working directory '/home/runner/work/repro-broken-symlink/repro-broken-symlink'. No such file or directory`

`run: pwsh -Command ...` works fine as it uses the system's `which` command that ignores the broken symlink.

**Expected behavior**

If the target of the symlink does not exist, `WhichUtil` should skip it and locate any other matches on the PATH.

## Runner Version and Platform
Latest Version

OS of the machine running the runner? Ubuntu

## What's not working?
See repro above.

## Job Log Output
See repro above.

## Runner and Worker's Diagnostic Logs
N/A

**Comment by nikola-jokic** [comment]
Thank you, @dhadka, for reporting this! I applied correct labels and added this issue to the board. :relaxed:

**Comment by fhammerl** [comment]
In order for this to be more user-friendly, we should fail if the path returned by `which` is a broken symlink. 
In other words, after the runner code invokes which to get the path to the executable, we should enforce that it in fact exists.

**Comment by Eliminator1999** [comment]
Hi, I am a first time contributor, I would like to take this issue. Would appreciate any help on where to start

**Comment by fhammerl** [comment]
Hello @Eliminator1999. Let me know if you'd like me to assign you to this issue.

### High level goal
Make the runner work the same as `which`. `which` ignores broken symlinks, while the runner treats them as if they were executables.

### Code location and whatnot

By default, running `which -a pwsh` would ignore broken symlinks.

- The runner doesn't run `which` directly, rather it tries to simulate it.
- The runner [loops](https://github.com/actions/runner/blob/main/src/Runner.Sdk/Util/WhichUtil.cs#L35) through all segments in $PATH and tries to see if the [command](https://github.com/actions/runner/blob/main/src/Runner.Sdk/Util/WhichUtil.cs#L100) `pwsh` is present.
- Seems like if the result is a symlink, we should try and assert that it points to a real file.
Consider multi-level symlinks as well.

### Pre-requisites

Are you already familiar with how [Actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) works and how to use [self-hosted runners?
](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners)

Next, I'd recommend checking out our [contribution](https://github.com/actions/runner/blob/main/docs/contribute.md) document. 
Here's some more specific docs if you're using [vscode](https://github.com/actions/runner/blob/main/docs/contribute/vscode.md)

**Comment by Eliminator1999** [comment]
thank you @fhammerl, yes please assign this to me, and thanks for all the info!

**Comment by eli-entelis** [comment]
@fhammerl  @nikola-jokic , can someone please review the pr https://github.com/actions/runner/pull/2196? thank you

**Comment by fhammerl** [comment]
PR merged
