### ISSUE TITLE
brew not found

### ISSUE THREAD

**Issue by Matts966** [actions/runner#2159]
**Describe the bug**

described in https://github.com/actions/runner/issues/1865

**To Reproduce**
1. brew

**Expected behavior**

brew found

## Runner Version and Platform

macos-latest

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?

This issue was [reproduced here](https://github.com/Matts966/dotfiles-open/actions/runs/3130038942/jobs/5079835047).

## Job Log Output
same above

## Runner and Worker's Diagnostic Logs
same above

**Comment by antonmos** [comment]
apparently, this was announced in https://github.com/actions/runner-images/issues/6283

**Comment by nikola-jokic** [comment]
Thank you, @antonmos, for answering! I will close this issue :relaxed:

**Comment by Matts966** [comment]
@antonmos @nikola-jokic 
Thank you 🙏
