### ISSUE TITLE
Github Actions Self-Hosted runner registration is not moving further on Windows 2019 Server

### ISSUE THREAD

**Issue by Trident2021** [actions/runner#2160]
**Describe the bug**
I am installing self-hosted runner on my windows server 2019. It passes below steps when i run this command **./config.cmd --url <My_Repo_url> --token <My_token>** using powershell ISE. 

#Authentication 

Connected to Github

#Runner Registration 

Script is running... What should be done here to resolve this issue? Self-Hosted Runner is also not getting added or shown in the github runners page.

**To Reproduce**
1. Run configure step under "Runners/Create self-hosted runner"
2. Script is not showing any output neither its stopping, its on runner registration.

**Expected behavior**
A runner needs to be added

## Runner Version and Platform
Latest

OS of the machine running the runner? OSX/Windows/Linux/...
Windows Server 2019

**Comment by vtcanac** [comment]
I am hanging at the exact same point. Windows 10. Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz   2.30 GHz

I installed:
Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/v2.298.2/actions-runner-win-x64-2.298.2.zip -OutFile actions-runner-win-x64-2.298.2.zip

But 32 bit didn't run any better.

**Comment by krptodr** [comment]
The config.cmd is a bash script. You can't run this under PowerShell. Run it under Command Prompt and you'll see the dialogue

**Comment by code2gnana** [comment]
Thank you, this solved the problem for me. Yeah, run config.cmd in Command Prompt with Admin rights.

**Comment by RichardR-cg** [comment]
I had the same issue - I was trying it under Powershell, and it works in Command Prompt. The reason why I was trying it in Powershell  was that the instructions have `#` as the prefix for comments. The instructions need to make it clearer that this is run via command prompt.
