### ISSUE TITLE
Add check before assigning runners to the jobs present in queue

### ISSUE THREAD

**Issue by swathida-byte** [actions/runner#2161]
In a big organization, we have repositories where developers are also admins. As a GitHub runner group admin, we want to control which branches could use a particular runner group. As GitHub didn’t provide that option, is it possible to implement a check (by an external script), to only allow a few branches to user runners from a runner group?

**Comment by ruvceskistefan** [comment]
Hi @swathida-byte ,
We investigated the problem you reported and found that it was not a runner related issue. This issue concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team.
