### ISSUE TITLE
Liquorix kernel breaks self-hosted install

### ISSUE THREAD

**Issue by Jire** [actions/runner#2165]
![unknown](https://user-images.githubusercontent.com/707385/193164007-c27be9a8-5674-4368-a248-99a436dfff06.png)

When trying to use `config.sh`

**Comment by fhammerl** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

We use dotnet's [OSDescription](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.osdescription?view=net-7.0) to get a string that we then include in our UserAgent header as a `ProductInfoHeaderValue`.

The constructor of `ProductInfoHeaderValue` validates if a string is compliant with UserAgent formatting. There aren't many requirements, but one of them is matching brackets -> `()` 
Brackets represent a `comment` in a UserAgent.

Liquorix has an OS description that contains mismatched brackets, so the constructor of `ProductInfoHeaderValue` throws.

I'd probably go with dropping all `()` to prevent nested UserAgent `comments`
