### ISSUE TITLE
Run without Difficultly 

### ISSUE THREAD

**Issue by IRadvisor** [actions/runner#2167]
**Describe the enhancement**
A clear and concise description of what the features or enhancement you need.

**Code Snippet**
If applicable, add a code snippet.

**Additional information**
Add any other context about the feature here.

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by ruvceskistefan** [comment]
Hi @IRadvisor 
Thanks for filling this issue! I will close this issue, feel free to reopen it with more info about given problem and we will get back to you.
