### ISSUE TITLE
Installing runner 2.298.0 on MacOS fails at config.sh step

### ISSUE THREAD

**Issue by IridescentShadow** [actions/runner#2172]
**Describe the bug**
When installing runner 2.298.0 on MacOS 12.6, `config.sh` fails with the following message:
```
"Runner.Listener" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."
```

**To Reproduce**
```
mkdir actions-runner && cd actions-runner`
curl -O -L https://github.com/actions/runner/releases/download/v2.298.0/actions-runner-osx-x64-2.298.0.tar.gz
tar xzf ./actions-runner-osx-x64-2.298.0.tar.gz
./config.sh --url https://github.com/[[ REDACTED ]] --token [[ REDACTED ]]
```

**Expected behavior**
Runner should configure itself properly without a security warning.

## Runner Version and Platform
Runner version 2.298.0, MacOS 12.6

## What's not working?
<img width="272" alt="Screen Shot 2022-10-04 at 10 15 49 AM" src="https://user-images.githubusercontent.com/7838663/193843302-86992d27-c2ff-448d-bdfd-3295d1add044.png">

## Runner and Worker's Diagnostic Logs
None are generated since it can't even get that far

**Comment by fhammerl** [comment]
Hi @IridescentShadow, can you try running `run.sh` in the same library you ran `config.sh` in?

**Comment by IridescentShadow** [comment]
`run.sh` produces exactly the same error message about being unable to be checked for malicious software

**Comment by fhammerl** [comment]
Thanks.

After trying to run it, does this show up under `System Preferences` / `Security & Privacy` / `General`? 

What are your security settings like? (screenshot of window below could help) 

![image](https://user-images.githubusercontent.com/31069338/194542938-86f510af-550f-4728-8df1-ec81b12951a5.png)

**Comment by IridescentShadow** [comment]
It does appear there, yes. But when I click Open Anyway, and try running `run.sh` again, it seems to step through one library after another after another and force me to approve each one and re-run afterwards.

This doesn't seem like something the average user should be expected to do.

<img width="268" alt="Screen Shot 2022-10-07 at 10 41 01 AM" src="https://user-images.githubusercontent.com/7838663/194581466-9ead5993-c410-49dc-bf3d-8d7ffd5b81b0.png">
<img width="261" alt="Screen Shot 2022-10-07 at 10 41 25 AM" src="https://user-images.githubusercontent.com/7838663/194581472-5ae134a0-d0a7-4d74-b7d4-b3c641b3c4a2.png">
<img width="266" alt="Screen Shot 2022-10-07 at 10 41 41 AM" src="https://user-images.githubusercontent.com/7838663/194581473-38efa6d8-e506-4c02-92bd-9b3bbd0bae96.png">
<img width="262" alt="Screen Shot 2022-10-07 at 10 42 01 AM" src="https://user-images.githubusercontent.com/7838663/194581475-1a071008-e445-441f-a494-7ad2f1fd71bc.png">
<img width="267" alt="Screen Shot 2022-10-07 at 10 42 22 AM" src="https://user-images.githubusercontent.com/7838663/194581476-41e6bbe7-05c8-43e1-8181-6427d9586191.png">
<img width="267" alt="Screen Shot 2022-10-07 at 10 42 45 AM" src="https://user-images.githubusercontent.com/7838663/194581478-5c0dbd7f-3011-467d-822a-4d21d52e2bb3.png">
<img width="264" alt="Screen Shot 2022-10-07 at 10 43 05 AM" src="https://user-images.githubusercontent.com/7838663/194581480-277cc5a2-802e-45a5-b41e-e2310d1106f9.png">
<img width="269" alt="Screen Shot 2022-10-07 at 10 43 12 AM" src="https://user-images.githubusercontent.com/7838663/194581482-445d5a63-ad1d-49f7-ae92-ee051bd896cd.png">
<img width="267" alt="Screen Shot 2022-10-07 at 10 43 20 AM" src="https://user-images.githubusercontent.com/7838663/194581484-d6238fdb-e663-4d52-b24d-e1230c861643.png">
<img width="267" alt="Screen Shot 2022-10-07 at 10 43 27 AM" src="https://user-images.githubusercontent.com/7838663/194581486-d7e695d7-1fcc-4b5e-900a-0d8d5f9e22cd.png">
<img width="269" alt="Screen Shot 2022-10-07 at 10 43 34 AM" src="https://user-images.githubusercontent.com/7838663/194581487-ce10a464-c83b-46bd-9eec-861b0ec8ae43.png">
<img width="269" alt="Screen Shot 2022-10-07 at 10 43 41 AM" src="https://user-images.githubusercontent.com/7838663/194581490-5aedcead-2add-48c3-a08c-d1d8f54fefc5.png">
<img width="264" alt="Screen Shot 2022-10-07 at 10 43 47 AM" src="https://user-images.githubusercontent.com/7838663/194581492-f8d6f5df-faee-44a0-97bd-5e355e65df75.png">
<img width="263" alt="Screen Shot 2022-10-07 at 10 43 54 AM" src="https://user-images.githubusercontent.com/7838663/194581494-ec30d432-8a75-41dc-b2b7-34a9d25b18af.png">
<img width="266" alt="Screen Shot 2022-10-07 at 10 44 01 AM" src="https://user-images.githubusercontent.com/7838663/194581495-c0747575-ad04-4f8f-9236-008e87bc8d0f.png">

**Comment by TingluoHuang** [comment]
Make sure you didn't download the runner package via the browser UI.

**Comment by IridescentShadow** [comment]
I deleted everything runner-related and reinstalled via curl, and it seems to be cooperating. It's possible that there was an archive Chrome had downloaded and that somehow that one got expanded instead of the curl one. Either way, I think this ends up being related to a browser download.
