### ISSUE TITLE
Self-hosted runner switching executed commit between matrix steps

### ISSUE THREAD

**Issue by Eshnek** [actions/runner#2186]
**Describe the bug**
I am running a test suite 8 times on my self-hosted runner to catch flaky tests. I want to do this via matrices, because the output is so clean that way.

The issue I face is that multiple commits mix with each other, and I do things in the first matrix step that configure the tests for all of the rest of the steps. So if the runner switches from `Commit A` to `Commit B` during one of the matrix jobs, it will be running on the wrong configuration because the state of the workspace is not reset between executions on the self-hosted runner. Thus the runner might say a test failed, when really the prior commit failed, or vice versa.

My current solution is to queue the behavior all in one job, that way there is no question that the desired behavior will go all the way through without switching between commits. But this requires duplicating code, and the log is huge and artifacts may conflict, so this is not ideal.

**To Reproduce**
1. Have a self-hosted runner workflow with a matrix like the one below
2. Trigger multiple builds
3. The matrix is not guaranteed to execute in order, and I see no way to make this the case

I have tried with different workflow and job concurrency settings, to no avail:
```
    runs-on: self-hosted
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        version: [1, 2, 3, 4, 5, 6, 7, 8]
    concurrency: 'gcc'
    timeout-minutes: 30
    steps:
      ...
```

**Expected behavior**
If `Commit A` and `Commit B` are pushed at approx the same time,
`Commit A` should run matrix jobs 1-8, then `Commit B` should run jobs 1-8 without mixing with each other

## Runner Version and Platform
Self hosted, Ubuntu 22.04 LTS Headless installed a couple of days ago

## What's not working?
This image encapsulates my issue - I want the older job to never be waiting subordinate to the newer job, regardless of the matrix strategy:
![Demo](https://user-images.githubusercontent.com/89618355/194428259-ce2fb76e-3218-4358-8351-03d684970e7d.png)

**Comment by nikola-jokic** [comment]
Hey @Eshnek,

Thank you for reporting this! Since the runner is not responsible for picking up work, this issue does not seem to be a runner issue, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback) site which is actively monitored? Using the forum ensures that we route your problem to the correct team. :relaxed:

**Comment by Eshnek** [comment]
@nikola-jokic 

Yes. I have posted it [here](https://github.com/community/community/discussions/35937)
