### ISSUE TITLE
Windows Runner Provisioner in the foreground is in the "way" for my failed unit tests screenshots

### ISSUE THREAD

**Issue by FJBDev** [actions/runner#2189]
**Describe the bug**
The Windows Runner Provisioner in the foreground is in the "way" for my failed unit tests screenshots.
Therefore, when some of my UI tests fail, I can't see the actual reason why it is failing.

![image](https://user-images.githubusercontent.com/25235665/194627218-4ef5d375-5f37-4563-9c94-932299a692f5.png)

**To Reproduce**
Launch a GitHub Action and make a UI test fail. This will trigger the upload of the screenshot as an artifact where you can see that the provisioner command windows is in the foreground at all times

**Expected behavior**
Provisioner command windows should be in the background

## Runner Version and Platform
2.297.0

Windows-Latest

## What's not working?
![image](https://user-images.githubusercontent.com/25235665/194627218-4ef5d375-5f37-4563-9c94-932299a692f5.png)

**Comment by nikola-jokic** [comment]
Hi @FJBDev,

I hope I can provide more context to this. The window management is outside the runner's control. The runner executes commands from your workflow, and it is up to the OS to decide where to put the window. In your use case, you are using the command prompt to start the runner, but you can also run it as a service, for example. The runner responsibility is only to execute your action, not to control stuff outside of it.

I will close this issue since it is not related to the runner :relaxed:

**Comment by FJBDev** [comment]
>In your use case, you are using the command prompt to start the runner, but you can also run it as a service, for example.

@nikola-jokic Can you guide me to documentation on how to do that. As I have never specified to run the runner in a command prompt, I would be interested to know how to start the runner as a service
Thanks

**Comment by nikola-jokic** [comment]
No problem, you can find reference here: https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service?platform=windows

**Comment by FJBDev** [comment]
> No problem, you can find reference here: https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service?platform=windows

But that is for self-hosted runners, I use [github-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) and I don't see a way to do that with a GitHub-hosted runner but maybe you know ?
