### ISSUE TITLE
How to gracefully shutdown GitHub action runner?

### ISSUE THREAD

**Issue by gajus** [actions/runner#2190]
We have a use case that requires to shutdown GitHub action runner after a special event occurs. However, we want to do this only once the runner completes the current job. How do I do that?

**Comment by gajus** [comment]
I can mostly achieve this via `ACTIONS_RUNNER_HOOK_JOB_COMPLETED`, but how would I stop the service from the hook given that the user is does not have `sudo`?

**Comment by nikola-jokic** [comment]
Hey @gajus,

If you can leverage the hook, you can send the SIGINT to the process by running for example `pkill -2 Runner.Listener`

**Comment by gajus** [comment]
I am not sure of how safe this is, but yeah, that works. Thank you

**Comment by paulz** [comment]
Thank you, that's exactly what we are looking for:

we are running multiple self hosted runners on macOS and need to reboot machine from time to time gracefully allowing current jobs to complete without starting new jobs.

How can we archive this?

just tried as an experiment to quit and even force quit all `Runner.Listener` processes on macOS and see them restarting.

**Comment by GMNGeoffrey** [comment]
Doesn't the proposed solution only work if the runner isn't is currently executing a job? It seems like the desired effect here would be to stop the runner immediately if it isn't currently executing a job.

**Comment by pauldraper** [comment]
Documentation says the hook should not be used like this.

> Note: The script defined in ACTIONS_RUNNER_HOOK_JOB_COMPLETED is executed at the end of the job, before the job completes. This makes it unsuitable for use cases that may interrupt a runner, such as deleting the runner machine as part of an autoscaling implementation.
