### ISSUE TITLE
Gracefully shutdown service containers

### ISSUE THREAD

**Issue by danielpacak** [actions/runner#2202]
**Describe the enhancement**

I realized that service containers are force-removed with `docker rm --force`. Therefore, the main process inside a container will receive a terminal SIGKILL that cannot be handled. Would it make sense to send a non-terminal signal SIGTERM before service containers are stopped? For example, use `docker stop --time=10 <container_name>` followed by `docker kill --signal=SIGTERM <container_name>`.

My primary use case is a service container that creates [commit status](https://docs.github.com/en/rest/commits/statuses) when it's started (pending), and then updates that status (success or failure) when the container is terminated.

**Code Snippet**

N/A

**Additional information**

N/A

**Comment by nikola-jokic** [comment]
Hi @danielpacak,

Thank you for submitting this enhancement! I will apply correct labels and add it to our backlog :relaxed:

**Comment by camtheman256** [comment]
This can be fixed by gracefully stopping the container (with `docker stop`) as part of your workflow. The `${{ job.services.<service>.id }}` variable provides access to the ID of the container. So the step looks like:

```yaml
# This step stops the container gracefully
- name: Stop service container
  run: docker stop ${{ job.services.service.id }}
```
