### ISSUE TITLE
macOS runner: Failed to download action

### ISSUE THREAD

**Issue by gleniat** [actions/runner#2207]
**Describe the bug**
The runner is unable to start executing any action, including a basic `actions/checkout@v3` action. The log is empty for the first 100 seconds, then an "Failed to download action" error shows up. The issue is on macOS only.

```
Warning: Failed to download action 'https://api.github.com/repos/maierj/fastlane-action/tarball/862de2c57cdfab21c874c037df7c8c73eae64938'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

The internet connections is fine, i tried it in Terminal:
```
# curl -w "download time: %{time_total}" https://api.github.com/repos/maierj/fastlane-action/tarball/862de2c57cdfab21c874c037df7c8c73eae64938
download time: 0.207570
```

**To Reproduce**
1. Setup a new macOS runner and connect it to any repository with a single action
2. Run the workflow by pushing to the repo
3. See error (you must wait at least 100 seconds)

**Expected behavior**

## Runner Version and Platform
macOS 12.4, v2.298.2

## What's not working?
Please include error messages and screenshots.

## Job Log Output
```
Warning: Failed to download action 'https://api.github.com/repos/maierj/fastlane-action/tarball/862de2c57cdfab21c874c037df7c8c73eae64938'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

## Runner and Worker's Diagnostic Logs
[worker.log](https://github.com/actions/runner/files/9794319/worker.log)

**Comment by ruvceskistefan** [comment]
Hey @gleniat, can you provide workflow file that you've been using so we can try to reproduce your issue and we will get back as soon as we can with more feedback.
