### ISSUE TITLE
Clang in ubuntu latest but not the latest runner

### ISSUE THREAD

**Issue by rob-mur** [actions/runner#2208]
**Describe the bug**
There seems to be a difference between the latest ubuntu-latest Github Runner and the image in this repo.

**To Reproduce**
1. Run clang --version in a normal github actions workflow using Github runner
2. See that it exists
3. Set up a self hosted runner using the most recent build of linux x64
4. Run clang --version with the self hosted runner
5. See that it doesn't exist

**Expected behavior**
My understanding is this image would be the same as the most recent ubuntu-latest. It would be beneficial if they were identical to avoid having to write different workflows depending on the type of runner hosting.

## Runner Version and Platform
latest, ubuntu x64.

OS of the machine running the runner? Tried both on a raw metal ubuntu 20.04 and a wsl install on windows 11

**Comment by nikola-jokic** [comment]
Hi @rob-mur,

Forgive me if I did not fully understand the issue, but this repository is not an image. If you pull down the release, you can configure and execute the runner. It does not pre-install the environment because you can run it on multiple architectures and operating systems.
So the runner itself is not tied with the packages that the hosted environment provides. It is simply a way for you to configure it on your own machine. If your machine does not have clang installed, you just need to install it there.

**Comment by rob-mur** [comment]
Thanks for your response! 

I understand this is the code for the runner (I just happen to be dockerizing it hence me saying 'image', sorry for the confusion).

I guess what I'm looking for is the exact install steps that go into producing the Github Runner ubuntu-latest image. I.e., what packages does it come with? (For example clang)

Apologise as I think this isn't a bug with your actual runner code, but a feature request to provide a dockerfile that replicates an instance of the hosted runner.

Perhaps you already do and I just don't know where it is!

**Comment by nikola-jokic** [comment]
Oh, don't worry, I just wanted to clarify to make sure I understand the issue :relaxed: 

I will mark this as a feature request. We currently don't have an image that is officially supported. You can see dependencies of hosted machines preinstalled here: https://github.com/actions/runner-images/releases

**Comment by rob-mur** [comment]
Ok thanks for the confirmation.

I think the implied best practice (at least for me) is to build and run docker images within actions for each part of the pipeline, and just use actions for the orchestration i.e. uploading artifacts/creating releases etc.

Let me know if you can think of a different way, and thanks for your help!

**Comment by nikola-jokic** [comment]
Hey @rob-mur

Just to let you know that the official image for the runner has been published :relaxed: This image is meant for k8s clusters, but you can safely use it however you see fit :relaxed: This is a minimal image and you can extend it with installations that you would require.
And also, you are right. You can assign labels to the runners running with specific configurations, and then pick the runners you see fit based on the label.
Sorry for the late response...
