### ISSUE TITLE
New "set-output" command

### ISSUE THREAD

**Issue by rez1dent3** [actions/runner#2225]
**Describe the bug**
After reading the [article](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), I began to update my github actions. But now there is a problem with escaping the string.  Something like this already happened here: https://github.com/actions/runner/issues/267

**To Reproduce**
```diff
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
-         echo "::set-output name=stdout::$OUTPUT"
+         echo "stdout=$OUTPUT" >> $GITHUB_OUTPUT
```

Diff: https://github.com/bavix/laravel-wallet-benchmark/pull/33/files

**Expected behavior**
Hyphenation characters will be displayed correctly.

Expected table: https://github.com/bavix/laravel-wallet-benchmark/pull/32#issuecomment-1286184416
Actual table: https://github.com/bavix/laravel-wallet-benchmark/pull/33#issuecomment-1289343926

---
Do I understand correctly that now escaping is automatic and crutches at the github actions level are no longer needed?

**Comment by xt0rted** [comment]
I ran into this yesterday while updating some of my workflows. The fix was to remove the escape code, it's no longer needed. If your value might span multiple lines then you need to write it out like this https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

**Comment by rez1dent3** [comment]
Hello, @xt0rted . Thanks, I'll try later. Most likely this will solve the problem. I created an issue to report a possible mass issue.

**Comment by rez1dent3** [comment]
```diff
-        OUTPUT="${OUTPUT//'%'/'%25'}"
-        OUTPUT="${OUTPUT//$'\n'/'%0A'}"
-        OUTPUT="${OUTPUT//$'\r'/'%0D'}"
-        echo "::set-output name=stdout::$OUTPUT"
+        echo "stdout<<EOF" >> $GITHUB_OUTPUT
+        echo "$OUTPUT" >> $GITHUB_OUTPUT
+        echo 'EOF' >> $GITHUB_OUTPUT
```

@xt0rted Yes you are right. Thank you.
