### ISSUE TITLE
Azure deploy fails if commit message is bigger than 8kb

### ISSUE THREAD

**Issue by yaba** [actions/runner#2230]
**Describe the bug**
Deploying to Azure Web App fails with **502 BAD GATEWAY**, if the commit message is longer than 8kb.

**To Reproduce**
1. Create Node App
2. Commit with a long message (>=8kb)
3. Deploy to Azure Web App using the default workflow
4. Check logs; should fail with 502

**Expected behavior**
Deploy correctly regardless of commit message; truncate if needed or generate proper warning/error message as 502 is quite vague.

## Runner Version and Platform
Version of your runner: 2.298.2

OS of the machine running the runner? Ubuntu, 20.04.05, LTS

## What's not working?
Please include error messages and screenshots.
Deploy to Azure:
![image](https://user-images.githubusercontent.com/406229/198021261-3ce4763d-1fef-4ce9-8d16-d412f9b779bb.png)

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

Run azure/webapps-deploy@v[2](https://github.com/yaba/XXXXXXXX/actions/runs/3328497691/jobs/5504570397#step:4:2)
  with:
    app-name: XXXXXXXX
    slot-name: Production
    publish-profile: ***
    package: .
Package deployment using ZIP Deploy initiated.
Error: Failed to deploy web package to App Service.
Error: Deployment Failed with Error: Error: Failed to deploy web package to App Service.
Bad Gateway (CODE: [5](https://github.com/yaba/XXXXXXXX/actions/runs/3328497691/jobs/5504570397#step:4:5)02)
App Service Application URL: https://XXXXXXXX.azurewebsites.net

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by bubon4ik222** [comment]
> run

**Comment by timscharfenort8989** [comment]
Hug

**Comment by yuu-eguci** [comment]
I had the same error today.
Thanks to your issue ... to your "Describe the bug" I was able to find out the cause of the error and to avoid the error.
I appreciate it.

You are right, 502 is quite an ambiguous message. I hope this issue will be fixed.

**Comment by raja-anbazhagan** [comment]
Maybe this needs to be raised at @Azure/webapps-deploy The code that fails is clearly from the actions rather than the runner. The trimming part needs to be done at the action source. 

Technically there isn;t any limit to commit message. https://stackoverflow.com/a/9733872/2557818
