### ISSUE TITLE
Self hosted runner ‘loses connection after between 12 and 30 mins

### ISSUE THREAD

**Issue by rathboma** [actions/runner#2241]
I have a self hosted MacOS runner. I use it to build my electron based desktop app for MacOS.

the final build step is to submit the app to apple for notarization.

Lately this process has been taking a long time. So my build script blocks as it waits for the result.

unfortunately after between 12 and 30 minutes waiting GitHub complains that it has lost connection with the runner. It also discards all the output from this build step for some reason.

I have been unable to find documentation on what timeout value to change to fix this, which makes me think it is likely a bug.

Examples:

https://github.com/beekeeper-studio/beekeeper-studio/actions/runs/3380486591/jobs/5617658424

Hoping someone can help shed some light on this.

I’ll try and pull logs from the box but wanted to post first in case it’s something simple I’m not understanding.

Thanks to all maintainers for your great work.

**Comment by nikola-jokic** [comment]
Hey @rathboma,

Thank you for your kind words! I saw that the run #7 has succeeded. Are you still experiencing this issue? Was it a temporary failure?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!

**Comment by rathboma** [comment]
Hi! Sorry just saw this.

My build did eventually pass, but the issue persists. If a task takes too long my runner just disconnects.

Not sure how to effectively debug, happy to though, given direction!

**Comment by nikola-jokic** [comment]
Hey @rathboma,

I have re-opened the issue. We will try to figure out what might be causing this issue and get back to you :relaxed:

**Comment by aktech** [comment]
We're seeing this too quite often with our [cirun.io](https://cirun.io) runners on a bunch of repositories.

- https://github.com/nebari-dev/nebari/actions/runs/3573573698
- https://github.com/NeuroDesk/neurocontainers/actions/runs/3561839883/jobs/5983092985

**Comment by gakama** [comment]
Seeing this consistently for a couple of partners. Reported around November 28th. Happy to provide links to pipelines. We are an internal MSFT Team.

https://github.com/Azure/azure-osconfig/actions/runs/3576580899/jobs/6056702848

**Comment by grimley517** [comment]
I am also experiencing this issue with a number of Mac osx based runners.

**Comment by henrikingo** [comment]
I'm experiencing the same. The workflow jobs time out at twelve minutes. It seems at that point the connection has already been lost for a while, maybe as long as 4-5 minutes - meaning the last output is from 8 minutes into the job.

https://github.com/nyrkio/turso/actions/runs/18316570729

**Comment by henrikingo** [comment]
Ok so the twelve minutes is the github side timeout. The disconnect from the runner happens earlier, and in my case was due to OOM.
