### ISSUE TITLE
GitHub Actions step is hanging/stuck until timeout

### ISSUE THREAD

**Issue by soumyamahunt** [actions/runner#2244]
**Describe the bug**

Sometimes Swift package action hangs on macos runners until the workflow is terminated by timeout.

The output logging stops if the log was monitored actively before the hang. When trying to open the log for already hanged step no logs is displayed until the action is timed out.

**To Reproduce**

I am able to reproduce this issue consistently by running `cd` job in [this](https://github.com/SwiftyLab/ValidatableKit/blob/main/.github/workflows/main.yml) workflow which runs [this](https://github.com/SwiftyLab/ci/blob/main/.github/workflows/cd.yml) reusable workflow.

**Expected behavior**

The runner should not hang or get stuck and should complete.
If there is some hang more details could be provided with process caused the hang.

## Runner Version and Platform

Facing this issue on `macos-12` runner, could be applicable to other macos runners as well.

## What's not working?

The timed out step's log can be found [here](https://github.com/SwiftyLab/ValidatableKit/actions/runs/3403558251/jobs/5660206527).

## Job Log Output

https://github.com/SwiftyLab/ValidatableKit/actions/runs/3403558251/jobs/5660206527

**Comment by grant-mccarriagher** [comment]
Seems to be related to https://github.com/actions/runner/issues/2140

**Comment by soumyamahunt** [comment]
I have moved the action from which the hang was occurring to run on ubuntu runner instead of macos runner and able to complete my workflow without hang. Closing this issue.
