### ISSUE TITLE
Exit on "Runner is deprecated and cannot receive messages"

### ISSUE THREAD

**Issue by duhow** [actions/runner#2246]
**Describe the enhancement**
Exit the application as **Failed** (or **Terminated**) if "Runner version is deprecated".

The expectation of having the Application (in Kubernetes as a Pod) reporting as **Failed**, is to trigger Monitoring to acknowledge there's an issue with Runners themselves, instead of "retrying to infinite" when having an outdated Runner that cannot pickup jobs.

**Code Snippet**
```
Current runner version: '2.296.2'
2022-11-04 09:48:25Z: Listening for Jobs
An error occurred: Runner version v2.296.2 is deprecated and cannot receive messages.
Runner listener exit with retryable error, re-launch runner in 5 seconds.
```

**Additional information**
Issue split from https://github.com/actions-runner-controller/actions-runner-controller/issues/1984 .
Relates to #1991 .

**Comment by nikola-jokic** [comment]
Hey @duhow,

Thanks for raising this issue :relaxed: We will let you know as soon as the fix is ready!
