### ISSUE TITLE
Finish runner --help outputs with unattended config doc

### ISSUE THREAD

**Issue by TingluoHuang** [actions/runner#226]
`./config.sh/cmd --help` will only print out some basic info about how to use the cli.

Ex:
```
H:\Source\runner_new\_layout>config.cmd --help

Commands:,
 .\config.cmd          Configures the runner
 .\config.cmd remove   Unconfigures the runner
 .\run.cmd             Runs the runner interactively. Does not require any options.

Options:
 --version  Prints the runner version
 --commit   Prints the runner commit
 --help     Prints the help for each command
```

We should include more information in this help output, like all arguments the runner takes durring config and example for doing unattended runner config.

**Comment by dakale** [comment]
Have you started on this yet? I can pick it up

**Comment by TingluoHuang** [comment]
@dakale sure, thanks.
