### ISSUE TITLE
Can we set runs-on: parameter during run time

### ISSUE THREAD

**Issue by swathida-byte** [actions/runner#2261]
I have a requirement where I need to run the second job using the output of the first job 
the first job runs and decides on which runner the second job has to run 
so my requirement is can the runs-on parameter take variable ???

**Comment by swathida-byte** [comment]
```  CI_BUILD_APP:
    name: CI_BUILD_APP
    needs: [CI_TRIGGER_APP]
    runs-on: ${{needs.CI_TRIGGER_APP.outputs.node-label}}
    ```
    getting the below error 
    <div class="js-updatable-content js-socket-channel" data-channel="eyJjIjoiY2hlY2tfc3VpdGVzOjM5MjA4MSIsInQiOjE2Njg2MjE4OTl9--7957f37f2b06384537cfd6babffbb129d8999a49b9a3e77c1d9c24e380a143d7" data-url="/CDH/dwx/actions/runs/52596/annotations_partial" style="box-sizing: border-box; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="actions-fullwidth-module color-bg-default color-shadow-small mb-3 pt-3 pb-1 border rounded" style="box-sizing: border-box; border: 1px solid var(--color-border-default)  !important; border-radius: 6px !important; box-shadow: var(--color-shadow-small)  !important; background-color: var(--color-canvas-default)  !important; margin-bottom: 16px !important; padding-bottom: 4px !important; padding-top: 16px !important;">

Error when evaluating 'runs-on' for job 'CI_BUILD_APP'. .github/workflows/CI_BUILD_APP.yaml (Line: 166, Col: 14): Unexpected type of value '', expected type: OneOf.
--


</div></div><div id="artifacts" class="js-updatable-content js-socket-channel" data-channel="eyJjIjoid29ya2Zsb3dfcnVuOjUyNTk2OmV4ZWN1dGlvbiIsInQiOjE2Njg2MjE4OTl9--94a9dd5c6418c8f1e0342c88fd20e3ac7817a49a392587b42f32f0444ea33963 eyJjIjoid29ya2Zsb3dfcnVuOjUyNTk2OmFydGlmYWN0cyIsInQiOjE2Njg2MjE4OTl9--43337206bf685d12fe38067831b074f42856363343a93dc7b46a36b16bf46d32" data-url="/CDH/dwx/actions/runs/52596/artifacts_partial" style="box-sizing: border-box; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="actions-fullwidth-module color-bg-default Box color-shadow-small mb-3 pt-3 pb-1 border rounded" style="box-sizing: border-box; background-color: var(--color-canvas-default)  !important; border: 1px solid var(--color-border-default)  !important; border-radius: 6px !important; box-shadow: var(--color-shadow-small)  !important; margin-bottom: 16px !important; padding-bottom: 4px !important; padding-top: 16px !important;"><div class="mt-1 mb-3 px-3" style="box-sizing: border-box; margin-top: 4px !important; margin-bottom: 16px !important; padding-right: 16px !important; padding-left: 16px !important;"><div class="mx-0 mx-md-1" style="box-sizing: border-box; margin-right: 4px !important; margin-left: 4px !important;"><br class="Apple-interchange-newline">

**Comment by johnpaulkj** [comment]
yeah as far as I checked, runs-on only accepts input params, not any like env or ouputs...

**Comment by kishaningithub** [comment]
@fhammerl Any updates on this?
