### ISSUE TITLE
hashFiles should allow limiting the length of the hash

### ISSUE THREAD

**Issue by ssbarnea** [actions/runner#2266]
Current hashes are very long and do not really make hard to copy/paste. It would be much easier to limit the size to 4-8 chars like git itself.

**Comment by nikola-jokic** [comment]
Hey @ssbarnea,

I will close this issue now, but if you feel like this could be useful addition, can you please post this to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests in GitHub Actions. For more information on this policy please [read our contribution guidelines](https://github.com/actions/runner#contribute).
