### ISSUE TITLE
Permission error when installing runner service

### ISSUE THREAD

**Issue by germa89** [actions/runner#2269]
**Describe the bug**
It seems I cannot install the service.

When I run:
```bash
{user@machine}{/home/user/actions-runner}$ sudo ./svc.sh install
```
I get the following output:
```text
Creating launch runner in /etc/systemd/system/actions.runner.pyansys.pymapdl-ci-0.service
Run as user: user
Run as uid: 247567
gid: 245095
./svc.sh: line 74: ./bin/actions.runner.service.temp: Permission denied
Failed: failed to create replacement temp file
```
The issue is in this line of ``svc.sh``:
```bash
sed "s/{{User}}/${run_as_user}/g; s/{{Description}}/$(echo ${SVC_DESCRIPTION} | sed -e 's/[\/&]/\\&/g')/g; s/{{RunnerRoot}}/$(echo ${RUNNER_ROOT} | sed -e 's/[\/&]/\\&/g')/g;" "${TEMPLATE_PATH}" > "${TEMP_PATH}" || failed "failed to create replacement temp file"
```
It seems that the variables have the following values:
```bash
SVC_DESCRIPTION=GitHub Actions Runner (pyansys.pymapdl-ci-0)
RUNNER_ROOT=/home/user/actions-runner
TEMPLATE_PATH=/home/user/actions-runner
run_as_user=user
```
The configuration I used when installed the runner is:
```text
√ Connected to GitHub

# Runner Registration

Enter the name of the runner group to add this runner to: [press Enter for Default] ansys-internal

Enter the name of runner: [press Enter for machine] pymapdl-ci-0

This runner will have the following labels: 'self-hosted', 'Linux', 'X64' 
Enter any additional labels (ex. label-1,label-2): [press Enter to skip] pymapdl,mapdl,docker,machine

√ Runner successfully added
√ Runner connection is good

# Runner settings

Enter name of work folder: [press Enter for _work] 

√ Settings Saved.
```
**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**
I would expect the service to be installed.

## Runner Version and Platform
Version of your runner?
actions-runner-linux-x64-2.299.1.tar.gz

OS of the machine running the runner? OSX/Windows/Linux/...
Linux Ubuntu 22.04.1 LTS

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by nikola-jokic** [comment]
Hey @germa89,

Can you please check which user owns the folders for the runner? If the other user owns these folders, then the creation of temp file will fail with permission denied since the user is not allowed to write to it

**Comment by vinay-ab-inbev** [comment]
Hi 
I am getting the same error 
          " sed: -e expression #1, char 26: invalid reference \4 on `s' command's RHS
            Failed: failed to create replacement temp file "
