### ISSUE TITLE
Action inputs may have non-POSIX-compliant kebab-cased environment variables

### ISSUE THREAD

**Issue by diamondburned** [actions/runner#2283]
**Describe the bug**

Currently, if kebab-cased input names were to be used (e.g. `file-path`), then it is impossible to get these inputs as environment variables from inside POSIX-compliant programs such as Bash.

**To Reproduce**

A reproduction of this issue can be found at [diamondburned/gh-non-compliance](https://github.com/diamondburned/gh-non-compliance).

1. Create an `action.yml` that runs using NodeJS, such as `node16`.
2. Inside the main JS file, execute a shell script that inherits the environment variables.
3. Try to print `${INPUT_FILE-PATH}`.

Bash will fail to parse `INPUT_FILE-PATH` and will instead print out some garbage like `-PATH`.

Even the workaround `name="INPUT_FILE-PATH"; echo ${!name}` fails to work with modern Bash (tested on Bash 5.1).

**Expected behavior**

GitHub Runner should map dash (`-`) characters to either an underscore or delete them entirely, as they're not allowed by the POSIX standard. This way, the input variable can be printed by doing `${INPUT_FILE_PATH}`.

In fact, it should also map all characters that are not in the `[A-Za-z_]` character set to be deleted. So:

- `file-path` becomes `INPUT_FILE_PATH`
- `file_path` becomes `INPUT_FILE_PATH`
- `filePath` becomes `INPUT_FILEPATH`
- `file.path` becomes `INPUT_FILEPATH`

A JS snippet that does this would look like

```js
function sanitizeEnvName(name) {
    return name.replace(/[- ]/g, "_").replace(/[^A-Za-z0-9_]/g, "").toUpperCase()
}
```

As a side note, accessing the variable by doing `process.env["INPUT_FILE-PATH"]` works, but it's needlessly inconvenient that programs have to manually convert environment variable names from being kebab-cased to snake-cased for shell and other POSIX-compliant programs to work.

## Runner Version and Platform

Runner version 2.299.1 on Ubuntu Latest (20.09).

## What's not working?

The code in [diamondburned/gh-non-compliance](https://github.com/diamondburned/gh-non-compliance) produces the following output:

```
nodejs: camel_cased is camel's value
nodejs: kebab-cased is kebab's value
bash: camel_cased = camel's value
bash: kebab-cased = CASED
```

with the code

```js
console.log("nodejs: camel_cased is", process.env["INPUT_CAMEL_CASED"])
console.log("nodejs: kebab-cased is", process.env["INPUT_KEBAB-CASED"])
```

and

```sh
# This works.
echo "bash: camel_cased = ${INPUT_CAMEL_CASED}"
# This does not work.
echo "bash: kebab-cased = ${INPUT_KEBAB-CASED}"
```

By using the workaround for Bash, we get an `invalid variable name` error.

## Job Log Output

Job log outputs can be found at https://github.com/diamondburned/gh-non-compliance/actions/runs/3551162295/jobs/5965142131. See the **Run action** step.

**Comment by flobernd** [comment]
A little off topic, but would it make sense to release an official style guide for actions? This could as well mitigate this issue without the introduction of breaking changes.

I personally don't know if I should prefer underscores or hyphens for my action inputs/outputs. Same for other identifiers like job/step names.

Not even the "official" actions provided by the GitHub team are using a consistent style for that matter.

On my question regarding this topic in the community section I did not receive a single answer.

Now that I saw this issue, it probably makes sense to always use underscores for identifiers to be consistent.

**Comment by AvaStancu** [comment]
Hey @diamondburned ! Thank you for the suggestion! While this is a limitation of POSIX, the actions runner supports a variety of ecosystems. Adding this limitation to env naming on the runner would break backwards compatibility with a variety of node and javascript actions and we would like to avoid that. In addition to your proposed workaround you can also use the env CLI https://man7.org/linux/man-pages/man1/env.1.html to set envs outside the standard allowed syntax.

**Comment by diamondburned** [comment]
> Adding this limitation to env naming on the runner would break backwards compatibility with a variety of node and javascript actions and we would like to avoid that.

The solution that I proposed does not have to break backwards compatibility: assuming the user does not add their own `INPUT_` environment variables (when they know that `INPUT_` is already used by GitHub), then adding an additional environment variable for each incorrectly-named input should not break everything.

For example, given `kebab-cased`, GitHub Actions can make two variables, `INPUT_KEBAB-CASED` and `INPUT_KEBAB_CASED`, which would not break backwards compatibility while allowing newer programs to be written correctly.

Not to mention, it's often the case that people declare their own environment variables without checking if it exists beforehand anyway, so an `INPUT_KEBAB_CASED=whatever` would still work when it's now set.

Of course, I wouldn't know what every single person did with their script. Maybe the above assumption does not check out. Either way, I feel like it's a better route to take than not permitting shell scripts to access those inputs.

> In addition to your proposed workaround you can also use the env CLI https://man7.org/linux/man-pages/man1/env.1.html to set envs outside the standard allowed syntax.

Yes, I can technically use `env` and something like `cut` to access the variables, but doing this workaround would involve changing ways to access inputs across the entire shell script.

Instead of doing

```sh
echo ${INPUT_PART_1} ${INPUT_PART_2}
```

I now have to do something like

```sh
function input() {
  # Do the funny case conversion, probably using tr
  # Map with the right regex, probably using sed
  # env | grep "^$1" (hopefully it doesn't have any dots...) | cut -d= -f2-
}

echo $(input "part-1") $(input "part-2")
```

where `input` (hopefully) does the right mapping.

> While this is a limitation of POSIX, the actions runner supports a variety of ecosystems.

As far as I can tell, NodeJS is the only ecosystem that receives this type of treatment where it gets official GitHub libraries to fetch inputs. Perhaps having one for Bash scripts would be nice, maybe something like this:

```sh
#!/usr/bin/env bash
. $(import-gh-actions)

echo $(actions::input "part-1") $(actions::input "part-2")
```

**Comment by aairey** [comment]
> @AvaStancu What about the style guide / documentation part I mentioned? This could at least help people to avoid this issue and besides that it will be a good thing for the community to have an official style guide document for the GitHub Actions ecosystem.

That would be really useful.
At least having a warning in the official docs that this does not work in `run` steps (or anything POSIX-compliant for that matter) would be useful.
If you know a bit of shell, you know `-` won't work in an ENV variable but not everyone knows this.

Reference doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs:~:text=When%20you%20specify,COLOR%20environment%20variables.
