### ISSUE TITLE
Unexpected error message "A mapping was not expected" when using re-suable workflow template with parameters

### ISSUE THREAD

**Issue by zma318** [actions/runner#2289]
**Describe the bug**
We're using re-usable GHA workflow template on a GHA workflow with triggering condition

```
on:
  issue_comment:
    types: [created]
```

with code

```
jobs:
  call-workflow:
    uses: our-re-usable-workflow-template
    secrets: inherit
    with:
      is-pull-request: ${{ github.event.issue.pull_request }}
```

And our if condition in the re-usable template is to see if this issue_comment is a pull_request or not. 

`    if: ${{ inputs.is-pull-request }}
`

However, seeing this unexpected error message 
`The template is not valid. A mapping was not expected` and it's pointing to the `is-pull-request` templating in my caller workflow.

The same template passed when triggering condition is

```
on:
  pull_request:
    branch: [main]
```

Any ideas why?

**To Reproduce**
Setup a re-usable workflow with params passing in.
Setup the triggering condition as creating issue_comment
Pass `github.event.issue.pull_request` in to see if this is a pull_request
Feel free to use this param in your re-usable workflow template.
See job fails.

**Expected behavior**
Job should be able to run and pass correct params in.

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?

> The template is not valid. .github/workflows/job-preview-reusable.yaml (Line: 12, Col: 24): A mapping was not expected

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by zma318** [comment]
Re-usable workflow:

> name: Job Preview

on:
  workflow_call:
    inputs:
      is-pull-request:
        required: true
        type: string
      github-event-comment:
        required: true
        type: string

jobs:
  job_preview:
    if: ${{ inputs.is-pull-request }}
    runs-on: ubuntu-latest
    steps:

**Comment by drobinson** [comment]
@zma318 did you find a solution to this? I'm having a similar issue...

**Comment by akarinaat** [comment]
I got the same error and it was because I had an indentation error. Verify everything in your yaml has the right syntax and the right indentation. 
Some times, when you save the document it is saved with format which causes the error.

**Comment by justinmchase** [comment]
I had this error because my expression lacked a `$` such as `{{ github.event_name == 'workflow_dispatch' }}` when it should have been `${{ github.event_name == 'workflow_dispatch' }}`.

Also, the if doesn't need `${{ }}` and can just have the expression assigned right to it such as `if: github.event_name == 'workflow_dispatch'`

**Comment by samy-soliman** [comment]
For me it was the use of `${{ github.event.repository.owner }} ` instead of `${{ github.repository_owner }}`

**Comment by nrgbistro** [comment]
I also encountered this and it was because I was using an incorrect variable name to reference an input for my composite action. My error message was: 

```
The template is not valid. <repo>/.github/workflows/frontend.yml@v1 (Line: 77, Col: 19): A mapping was not expected
```

But that referenced line number had absolutely nothing to do with where the error was, in fact it was commented out code. Just a tip for anyone running into this in the future, don't pay attention to that line number as it will make you more confused.

**Comment by suimonen667** [comment]
> EDIT: It was actually because I was trying to pass in an object to a composite action input, which is apparently unsupported. Solved by splitting the object into individual inputs that are each a string.

This worked, thank you for this comment

**Comment by jm-janzen** [comment]
> EDIT: It was actually because I was trying to pass in an object to a composite action input, which is apparently unsupported. Solved by splitting the object into individual inputs that are each a string.

Yup, this is it. My issue was with a `repository_action`, but I was pulling my hair out trying to debug the issue when the answer was right in front of me.

`"A mapping was not expected"` = you passed an object.
`"A sequence was not expected"` = you passed an array.

The solution for me was to stringify the JSON at source, before passing it to GitHub.
