### ISSUE TITLE
macOS Large Runner 

### ISSUE THREAD

**Issue by gblikas** [actions/runner#2300]
I posted this question, originally, in the Github Community space, which I think might have been the wrong location,
- 🔗 https://github.com/orgs/community/discussions/40401

I'm currently in the beta-program for Large Github Runners. There are some great options for windows and ubuntu, but macOS is still stuck at a 3 core option. Is there an expected release date, or a larger (unlisted) runner option for macOS?

**Comment by nikola-jokic** [comment]
Hey @gblikas,

You posted the question in the right place, and the team is aware of it :relaxed:. I will close this issue, as noted [here](https://github.com/actions/runner#contribute), in the contribution guidelines. But thank you for showing this much interest!

**Comment by gblikas** [comment]
@nikola-jokic Thanks for getting back to me. If this issue is getting closed and the team is aware of the issue, and feedback on when macOS Large Runners will be available? I haven't gotten any feedback on https://github.com/orgs/community/discussions/40401

**Comment by gblikas** [comment]
@nikola-jokic It looks like my last comment was removed automatically?

**Comment by fhammerl** [comment]
More powerful macOS runners are planned to come in Q1 2023

As the issue says, these runners are not part of the 'Larger Runners' ecosystem, rather you'll be able to pick them by editing your `runs-on` in your workflow YAML.


Public roadmap item:
https://github.com/github/roadmap/issues/506
