### ISSUE TITLE
Add gfortran 12 in ubuntu 22.04 by default

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [actions/runner#2305]
**Describe the enhancement**
All but one of the preinstalled GNU C compiler packages in the ubuntu 22 image (as of 20221127.1) have corresponding gfortran packages; gcc version 12 does not. For consistency it would be useful to include it.

**Comment by nikola-jokic** [comment]
Hey @AlexanderRichert-NOAA,

Since this concerns the software on machines running GitHub's hosted runners, could you please post your issue in the [Virtual Environments Repository](https://github.com/actions/virtual-environments/issues/new/choose) to ensure the correct team sees it? :relaxed:
