### ISSUE TITLE
hashfiles() expression function needs to handle symlink loop gracefully

### ISSUE THREAD

**Issue by TingluoHuang** [actions/runner#234]
When user has symlink loop in the folder they trying to hash, the runner will stuck on finding all files under the folder, the job will hang and user get no idea what's going wrong.

We need to detect the symlink loop, stop the recursion search and continue find other files.

**Comment by dakale** [comment]
Im not sure globbing with node solves anything. Youll just get a list of files (some of which may be symlinks) and then when you try to hash them, wont you just follow the link to the target and hit the same issue? Although, there may be existing javascript implementations of things other than glob that could be leveraged

**Comment by TingluoHuang** [comment]
dotnet doesn't have any api to deal with symlink, it always follow symlinks...

**Comment by dakale** [comment]
Yea, my follow up was going to be youd need to detect cycles in code (tarjans, or maybe a max stack depth), or with an existing node module, or shell out to a different tool other than node that can do this. Beyond that, I dont know what the correct behavior is for hashing files that contain cyclic links, but it seems like you probably wouldnt be able to

**Comment by joshmgross** [comment]
The feature flag that this is behind has rolled out everywhere. Thanks @TingluoHuang!
