### ISSUE TITLE
Setting Environment Variable does not work on a self hosted runner on windows 11

### ISSUE THREAD

**Issue by kumaakh** [actions/runner#2350]
**Describe the bug**
On a self hosted runner on windows [this documented feature](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable) does not work. i.e. the environment varaibles set from one step are not available in the following steps.

**To Reproduce**
1. Go to '[this public workflow](https://github.com/Apra-Labs/workflow-experiments/blob/main/.github/workflows/cuda-test.yml)'
2. Look at the last run also attached [the build log here](https://github.com/Apra-Labs/workflow-experiments/actions/runs/3826370788/jobs/6510106059) 

**Expected behavior**
as per [this documented feature](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable), This should output 'yellow', but it dow not

## Runner Version and Platform
Runner 2.299.1
From what I have observed, this used to work fine till 2.298.x (late Oct 2022)

OS of the machine running the runner? 
Windows 11 Pro

## What's not working?
screen shot
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/7100034/210293061-0e7d7a25-4fab-47fa-8005-ec8e798f3a56.png">

## Job Log Output
[github-action-runner-log.txt](https://github.com/actions/runner/files/10334081/github-action-runner-log.txt)

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by Sylfwood** [comment]
To access an environment variable under Windows runners, you must use $Env:ENV_VARIABLE. The Github documentation is confusing about this for Windows.

Try using `echo "key=value" >> $Env:GITHUB_ENV`.
