### ISSUE TITLE
cronjob fails to use curl occasionally 

### ISSUE THREAD

**Issue by shalev007** [actions/runner#2351]
**Describe the bug**
We have a cron-job action that runs every 10 mins, it's an e2e test that constantly checks our cli tool.
Every now and then a job fails because it cannot download our cli tool for some reason.

**To Reproduce**
Cannot reproduce since there is no exact time, it just happens sometimes.

**Expected behavior**
I would expect that the action to have an constant behavior

## Runner Version and Platform
Version of your runner?
2.299.1

OS of the machine running the runner? OSX/Windows/Linux/...
Ubuntu 20.04.5 LTS

## What's not working?
Please include error messages and screenshots.
![image](https://user-images.githubusercontent.com/51760613/210518193-4a495531-37d0-467d-992b-4d2e7a0768c9.png)

**Comment by nikola-jokic** [comment]
Hey @shalev007,

Can you please submit runner logs for a failed job? And please, make sure to deduct everything you would like not to be seen :relaxed:

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
