### ISSUE TITLE
Runner build should produce and publish containers

### ISSUE THREAD

**Issue by bryanmacfarlane** [actions/runner#239]
Thank you 🙇‍♀ for wanting to create a feature in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.  

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions or issues with the service, writing workflows or actions, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#contacting-support)

If you have a feature request that is relevant to this repository, the runner, then please include the information below:

**Describe the enhancement**
Every runner build should produce containers and they should be published.  This allows for kubernetes or other container services to elastically run jobs with the latest runner (avoiding the need for potential updates when starting)

**Additional information**
Would be nice to have standard linux distros as well as alpine

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by nikola-jokic** [comment]
Happy to say we can close this issue now, since this [PR](https://github.com/actions/runner/pull/2250) has been merged, and building images is part of the release process now :relaxed:
