### ISSUE TITLE
Cannot install ruby on macOS runner - 2 issues

### ISSUE THREAD

**Issue by jaaywags** [actions/runner#2391]
**Describe the bug**
There are actually two bugs in this. Both prevent installing ruby on a self-hosted runner type, macOS.

**To Reproduce**
Steps to reproduce the first issue:
1. Setup a macOS self hosted runner (default options)
2. Create a repo with a workflow that has the following step
```
- name: Install Ruby
  uses: ruby/setup-ruby@v1
  with:
    ruby-version: 3.0.2
    bundler-cache: true
```
3. Start the runner
4. Run the workflow

**Expected behavior**
The workflow runs successfully

**Actual behavior**
Runner fails to install Ruby due to ImageOS not being set
https://github.com/jaaywags/test-self-hosted-runners/actions/runs/3983539312/jobs/6828949281

**Fix and repo-steps for issue 2**
1. Stop runner (control+c)
2. Edit the `.env` file and add `ImageOS=macos11` to the bottom of the file
3. Save and exit
5. Start the runner again
6. Re-run the workflow

**Expected behavior**
The workflow runs successfully

**Actual behavior**
Runner fails to install Ruby due to permission denied
https://github.com/jaaywags/test-self-hosted-runners/actions/runs/3983576219/jobs/6829016956

## Runner Version and Platform
Version of runner: v2.300.2
OS of the machine running the runner: macOS Ventura 13.1

## What's not working?
First error message:
```
Error: The environment variable ImageOS must be set
```

Second error message:
```
 Entries added to PATH to use selected Ruby:
    /Users/runner/hostedtoolcache/Ruby/3.0.2/x64/bin
Error: Error: EACCES: permission denied, mkdir '/Users/runner'
```

**Comment by jaaywags** [comment]
We can probably close this.

This seems to be an issue not with [actions/runner](https://github.com/actions/runner), but more with the [setup-ruby plugin](https://github.com/ruby/setup-ruby).

[I found this issue on their github](https://github.com/ruby/setup-ruby/issues/322). 

My fix was to create a runner user. Then from there, 2 options. Either run the self-hosted action runner as that runner user, or give read/write access of that users home director  to the user running this self-hosted action runner.

Here is the successful run
https://github.com/jaaywags/test-self-hosted-runners/actions/runs/3988743841/jobs/6840304666

**Comment by cemlyn007** [comment]
Hey @jaaywags, thanks for your answer, but could you explain why you needed to create a runner user? I'm just wondering why is it not sufficient to just recursively give read/write permissions in /User/runner to the user that runs ./run.sh?

**Comment by jaaywags** [comment]
@cemlyn007 hmmm, I can't exactly remember it's been too long. If I do, I'll reply again.

I think the reason I may have wanted to create a runner user was to segregate that stuff from my main account but I can't recall for sure.

**Comment by cemlyn007** [comment]
Hi @jaaywags, good point! Hope you have a fantastic week 🥳

**Comment by dejanbasic** [comment]
> > We can probably close this.
> > This seems to be an issue not with [actions/runner](https://github.com/actions/runner), but more with the [setup-ruby plugin](https://github.com/ruby/setup-ruby).
> > [I found this issue on their github](https://github.com/ruby/setup-ruby/issues/322).
> > My fix was to create a runner user. Then from there, 2 options. Either run the self-hosted action runner as that runner user, or give read/write access of that users home director to the user running this self-hosted action runner.
> > Here is the successful run https://github.com/jaaywags/test-self-hosted-runners/actions/runs/3988743841/jobs/6840304666
> 
> i have to setup self-hosted on mac mini, and facing with same issue about Error: Error: EACCES: permission denied, mkdir '/Users/runner' research and find this post. But link successful run u were share i cant not access. Can u share your action.yml pls :(

same problem :(
