### ISSUE TITLE
Please fix documentation on reusable workflows

### ISSUE THREAD

**Issue by bond-** [actions/runner#2401]
**Describe the bug**
Our organization uses GH Enterprise v3.5. As per the docs specified here I tried to write a re-usable workflow
https://docs.github.com/en/enterprise-server@3.5/actions/using-workflows/reusing-workflows

### The documentation specifies this is how I can call a local workflow which is wrong:  
```
 jobs:
   call-workflow-2-in-local-repo:
     uses: ./.github/workflows/workflow-2.yml
```
This gives an error: 
```
Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/path/to/.github/workflows/workflow-2.yml'. Did you forget to run actions/checkout before running your local action?
```
This is wrong it should be actually called like this apparently:
```
 jobs:
   call-workflow-2-in-local-repo:
     uses: ./.github/workflows/workflow-2
```
Here `workflow-2` should be a folder with an `action.yml` file under it.

### The documentation specifies this is how I pass inputs or secrets to reusable workflow which is wrong:  
```
name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
```
But I get this error:
```
Error: /path/to/./.github/workflows/workflow-2/action.yml (Line: X, Col: Y):
Error: /path/to/./.github/workflows/workflow-2/action.yml (Line: X, Col: Y):
Error: /path/to/./.github/workflows/workflow-2/action.yml (Line: X, Col: Y):
Error: /path/to/./.github/workflows/workflow-2/action.yml (Line: X, Col: Y): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.envPat
Error: /path/to/./.github/workflows/workflow-2/action.yml (Line: X, Col: Y): Unrecognized named-value: 'input'. Located at position 1 within expression: input.config-path
Error: Fail to load /path/to/./.github/workflows/workflow-2/action.yml
```
Who do I go for help when the docs itself are wrong.

**To Reproduce**
1. Go to https://docs.github.com/en/enterprise-server@3.5/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
3. Follow the steps for `Calling a reusable workflow`, specifically local workflow
4. See errors described above

**Expected behavior**
Steps in the documentation work as expected

## Runner Version and Platform
Version of your runner?
2.289.3

OS of the machine running the runner?
Linux

## What's not working?
- see above in description

## Job Log Output
- see above in description

**Comment by lindluni** [comment]
I believe you are confusing Reusable Workflows and local actions. A reusable workflow does not specify an action.yml file and is called directly as mentioned in the documentation. As such, if you are actually attempting to write a local Action, variable input does not exist for local actions.

**Comment by ruvceskistefan** [comment]
Hey @bond- 
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
