### ISSUE TITLE
Action job never ends

### ISSUE THREAD

**Issue by gonft** [actions/runner#2409]
**Describe the bug**
Action workflow never ends

**To Reproduce**
1. The action is executed
2. All workflow steps are complete
3. Workflow is still in queue and not finished

**Expected behavior**
All workflows have finished and the queue must be closed

## Runner Version and Platform
Version of your runner?

OSX(Ventura 13.2 Apple M1, RAM 64GB)

## What's not working?
Please include error messages and screenshots.

<img width="642" alt="스크린샷 2023-01-31 오후 9 53 39" src="https://user-images.githubusercontent.com/3823239/215765421-89c0bb2d-2997-44c9-9205-85899c24f8a6.png">

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by amodm** [comment]
I'm facing the same issue.

My actions in [this repo](https://github.com/amodm/swift-rs) consistently get stuck on `Post Checkout` step, for anywhere from 20-40 mins, and eventually times out. All previous steps proceeded successfully.

One such run is this: https://github.com/amodm/swift-rs/actions/runs/4054199193/jobs/6977785548

Repo: https://github.com/amodm/swift-rs
Relevant workflow yaml: https://github.com/amodm/swift-rs/blob/master/.github/workflows/main.yaml
Runner: macos-latest

After having run more debugging, I realised that the `Post Checkout` step actually passes, but it's the `Complete job` step of the runner that gets stuck: https://github.com/amodm/swift-rs/actions/runs/4061274934/jobs/6991136477

**Comment by amodm** [comment]
After some hit & trial, it seems to have narrowed down to running the `leaks` command for me. When tests in my repo run `leaks` as a regular user, the runner gets stuck at the end, but when it's run as `sudo leaks`, it doesn't. I've no idea why it is so 🤷🏼‍♂️ , but it's consistently reproducible for me.

**Comment by KeisukeKudo** [comment]
I too encountered a similar problem.
I was able to work around it by specifying `runs-on: ubuntu-20.04` as a temporary fix.

**Comment by dluhhbiu** [comment]
Have the same issue. Don't know how to fix it. Ubuntu-20.04 didn't help :disappointed:

**Comment by KeisukeKudo** [comment]
@dluhhbiu 

How about creating a `yaml` with the workflow name and file name changed?

**Comment by robbporto** [comment]
This started happening again today.

**Comment by ChristosCh00** [comment]
happening again now. out of the blue. also the logs and properly formatted into steps as they typically are

**Comment by rogerweb** [comment]
@robbporto and @ChristosCh00, it was an incident with Actions in GitHub, as captured in their status page:

https://www.githubstatus.com/incidents/f7jl0mdd2jr5

It has been resolved. In my case I simply re-ran the job and it finished fine.

**Comment by victorandujar** [comment]
Is someone facing the same issue right now? jobs never ends...

**Comment by haegeon-kim** [comment]
The same problem happened again... there was no problem 19 hours ago, but it happened 
<img width="339" alt="스크린샷 2024-09-13 14 50 10" src="https://github.com/user-attachments/assets/65c404e0-f034-4c1d-862e-1f91c614aa48">
<img width="623" alt="스크린샷 2024-09-13 14 50 19" src="https://github.com/user-attachments/assets/42499514-3cef-479c-b17d-b56dc6512fbc">

**Comment by antspy** [comment]
Seeing this issue today - Is there a known workaround?

**Comment by CorneliusKluge** [comment]
Right now, there is a known incident going on with GitHub actions: https://www.githubstatus.com/
