### ISSUE TITLE
The runner has received a shutdown signal

### ISSUE THREAD

**Issue by andrefagundeshubstuff** [actions/runner#2427]
**Describe the bug**
We started to get the following error while running workflows:

The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

**To Reproduce**
1. Click on the failed workflow
2. Go to annotations
3. See the error in the first row

**Expected behavior**
I expect to have my workflows running without any runner related errors.

## Runner Version and Platform
2.301.1

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
Workflows are eventually failing with an runner related error. The logs does not provide any information that can lead to a better understanding of the problem. I would like to be advised on how to approach this error in order to determine the root cause. 

## Job Log Output
2023-02-09T20:11:49.9484027Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2023-02-09T20:11:49.9749746Z ...
2023-02-09T20:11:49.9966268Z ##[error]The operation was canceled.
2023-02-09T20:11:50.0154231Z Uploading runner diagnostic logs
2023-02-09T20:11:50.1523865Z Completed runner diagnostic log upload
2023-02-09T20:11:50.1524223Z Cleaning up orphan processes

## Runner and Worker's Diagnostic Logs
No relevant information in the worker and runner logs

**Comment by andrefagundeshubstuff** [comment]
Found the cause myself. The job was running on a AWS SPOT instance which was terminated.

**Comment by ruvceskistefan** [comment]
Hey @andrefagundeshubstuff,
I'm glad that you found the problem, I'll close this issue, feel free to reopen it if you're still having the same problem and we will investigate further.
