### ISSUE TITLE
Upgrading v2.299.2 ==> v2.302.0 breaks workflow log functionality

### ISSUE THREAD

**Issue by IAXES** [actions/runner#2435]
**Describe the bug**
Upgrading to `v2.302.0` breaks the workflow logs in GitHub Actions. If one is viewing the logs "live", most, but not all, actions will render logs to the web UI console. However, upon refreshing the page, jobs will report (via the left-hand sidebar), "This job has been skipped.", even though the job successfully ran to completion. As for the log view on the right, there appears to be a 50% chance that any given step just randomly gets stuck with a "running" state (yellow "running" icon persists next to the step, even after the job has concluded). The only way to view logs (reliably) is to "view RAW logs" once the overall workflow has concluded.

I've done 4 rollbacks/re-applies between these 2 versions today (and even nuked my ephemeral CI/CD system via Terraform, to rule out stale intermediate artifacts in a throwaway/test CI/CD system to verify).

**To Reproduce**
Detailed above.

**Expected behavior**
Workflow logs render on-demand, or, at least, are usable after a job concludes.

## Runner Version and Platform
v2.302.0 is problematic. Running on Ubuntu 20.04 x64 LTS (latest), against GHES v3.5.3.

## What's not working?
![image](https://user-images.githubusercontent.com/8325672/218899552-b96d2fb7-4318-4f5a-bf57-89bd98ec6d91.png)

**Comment by gorkemgoknar** [comment]
v2.302.0 change of github runner installing docker cli also removes docker buildkit support

**Comment by abbylentz** [comment]
Hi, is 2.302.1 available? If I tell a customer to update/upgrade their runners, will this be available?

**Comment by ruvceskistefan** [comment]
Hey @IAXES ,
I'll close this issue since the problematic PR is reverted. If you're still having the same issue please feel free to reopen it and we will continue the investigation.
