### ISSUE TITLE
Add support for long-term tokens

### ISSUE THREAD

**Issue by myoung34** [actions/runner#244]
**Describe the enhancement**

Currently the only way to set up an agent is to dig around the settings and take the runner token from the UI. This changes hourly which is frustrating when debugging as it will eventually just stop working.

**Code Snippet**

```
config.sh --url "${REPO_URL}" --token "${RUNNER_TOKEN}" --agent "${_RUNNER_NAME}" --work "${_RUNNER_WORKDIR}"
```

**Additional information**

n/a

**Comment by TingluoHuang** [comment]
We are working on adding api to allow you generate the register token using your PAT.

**Comment by bryanmacfarlane** [comment]
☝️ that's correct.  It's also an api / service workitem that's coded and will ship soon (not part of the runner)

**Comment by bryanmacfarlane** [comment]
note that the other work I noted around containers as part of the build will call that api

**Comment by bryanmacfarlane** [comment]
The api has released.

https://developer.github.com/v3/actions/self_hosted_runners/#create-a-registration-token
