### ISSUE TITLE
Unexpected cache misses when running `actions/cache@v3`

### ISSUE THREAD

**Issue by chetbox** [actions/runner#2448]
**Describe the bug**
`actions/cache@v3` has cache misses all of a sudden.

**To Reproduce**
1. Create an job that saves to the cache and restores via prefix match. e.g.
```yaml
    - uses: actions/cache@v3
      with:
        path: folder
        key: folder-${{ env.SUFFIX }}
        restore-keys: |
          folder-
        fail-on-cache-miss: true
```
(In my case this ran successfully earlier today.)
2. When this action runs it creates an error because of a cache miss
3. See error

**Expected behavior**
A cache with key `folder-*` is retrieved. There is no error.

## Runner Version and Platform
```
Current runner version: '2.301.1'
Operating System
[3](https://github.com/chetbox/brighton-explorers-signal/actions/runs/4208212963/jobs/7303978034#step:1:3)
  Ubuntu
[4](https://github.com/chetbox/brighton-explorers-signal/actions/runs/4208212963/jobs/7303978034#step:1:4)
  22.04.1
[5](https://github.com/chetbox/brighton-explorers-signal/actions/runs/4208212963/jobs/7303978034#step:1:5)
  LTS
Runner Image
[7](https://github.com/chetbox/brighton-explorers-signal/actions/runs/4208212963/jobs/7303978034#step:1:8)
  Image: ubuntu-22.04
[8](https://github.com/chetbox/brighton-explorers-signal/actions/runs/4208212963/jobs/7303978034#step:1:9)
  Version: 20230217.1
[9](https://github.com/chetbox/brighton-explorers-signal/actions/runs/4208212963/jobs/7303978034#step:1:10)
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230217.1/images/linux/Ubuntu2204-Readme.md
[10](https://github.com/chetbox/brighton-explorers-signal/actions/runs/4208212963/jobs/7303978034#step:1:11)
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230217.1
```

## What's not working?

Cache fails to restore.

```
Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set. Input key: folder-73489456
```

## Job Log Output
```
Run actions/cache@v3
  with:
    path: folder
    key: folder-656528678
    restore-keys: folder-
    fail-on-cache-miss: true
    enableCrossOsArchive: false
  env:
    SUFFIX: 73489456
Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set. Input key: folder-73489456
```

## Extra info

I have verified the multiple caches I expect to exist with the prefix `folder-` exist by running:

```shell
gh api \
  -H "Accept: application/vnd.github+json" \
  /repos/OWNER/REPO/actions/caches
```

[`actions/cache@v3`](https://github.com/actions/cache) appears to have no new releases since last week. I was successfully running job that restore caches a few hours ago.

**Comment by michaelwilner** [comment]
I am seeing the same

**Comment by bryanmacfarlane** [comment]
I wonder if the action treats failure to determine if cache key exists and successfully determining that the cache key does not exist the same.   This is just a theory and is not based on anything other than I know there was a live site incident with some github services returning 500s last night.  Were there any 500s in that steps logs?

Also in the case of the former, I assume you would want to move forward on the cache miss as ideally, the cache should be an optimization and not critical to the success?  Unless in your cases something else is populating those folders and the ability to copy that folder down during that workflow run is critical to it's success (and it's not capable of building that folder).

We may also want to move this issue to the actions/cache repo.

**Comment by chetbox** [comment]
I understand that in most cases a cache miss is an optimisation however in my case the action cannot run if the cache hasn't restored some important data, hence I am using the `fail-on-cache-miss: true` option.

I was planning to submit this as an issue on https://github.com/actions/cache however there hasn't been an update to the action for over a week so the issue is unlikely to be there. Maybe it's an issue with the internal GitHub API?

I have a scheduled job that runs every 2 hours and it is still failing.

**Comment by chetbox** [comment]
I have created this issue as suggested by @bryanmacfarlane above https://github.com/actions/cache/issues/1114

**Comment by ruvceskistefan** [comment]
Hey @chetbox,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃

**Comment by chetbox** [comment]
Thanks. The issue seem to have been caused by `@actions/toolkit` and has now been resolved. See https://github.com/actions/cache/issues/1114 for more info.
