### ISSUE TITLE
`ACTIONS_RUNNER_HOOK_JOB_COMPLETED` doesn't see the `GITHUB_ENV` contents

### ISSUE THREAD

**Issue by rvem** [actions/runner#2459]
**Describe the bug**
I have a runner configuration with both `ACTIONS_RUNNER_HOOK_JOB_STARTED` and `ACTIONS_RUNNER_HOOK_JOB_COMPLETED`.

`ACTIONS_RUNNER_HOOK_JOB_STARTED` fetches some data from the remote server and sets env variables that are used in set actual job step and that are later used for clean up in `ACTIONS_RUNNER_HOOK_JOB_COMPLETED`.
Env setup in `ACTIONS_RUNNER_HOOK_JOB_STARTED` is done the following way:
```
{
    echo "VAR1=VAL1"
    echo "VAR2=VAL2"
    ...
} >> "$GITHUB_ENV"
```

When `ACTIONS_RUNNER_HOOK_JOB_COMPLETED` attempts to source the `GITHUB_ENV` to read these variables, it finds
a file with the empty contents

While variables set in `ACTIONS_RUNNER_HOOK_JOB_STARTED` are visible during the other steps of the job.

**To Reproduce**

Setup runner with `ACTIONS_RUNNER_HOOK_JOB_STARTED` that adds some variables to `GITHUB_ENV` and 
`ACTIONS_RUNNER_HOOK_JOB_COMPLETED` which tries `source "$GITHUB_ENV"` and use these variables.

**Expected behavior**
`ACTIONS_RUNNER_HOOK_JOB_COMPLETED` is able to see variables set by `ACTIONS_RUNNER_HOOK_JOB_STARTED`

## Runner Version and Platform
Version of your runner?
`github-runner-2.301.1`

OS of the machine running the runner? OSX/Windows/Linux/...
NixOS

## Job Log Output
`ACTIONS_RUNNER_HOOK_JOB_COMPLETED` is essentially the following:
```
echo "Cleanup"
echo "$GITHUB_ENV"
cat "$GITHUB_ENV"
```

"Complete runner" step logs:
```
A job completed hook has been configured by the self-hosted runner administrator
Run '<...>/complete-script.sh'
Cleanup
/run/github-runner/public-runners-11/_temp/_runner_file_commands/set_env_d96864b6-f89e-44e3-a1c7-c35e7d2c0f61
```

**Comment by softlberton** [comment]
Hi @rvem ,

I've had some issues in the past with pre and post job scripts, all related to my self-hosted runner version

When updating to version **2.303.0** everything was resolved.

**Comment by rvem** [comment]
Thanks, I'll check if updating runner helps
