### ISSUE TITLE
How can I select runners with Intel Ice Lake ?

### ISSUE THREAD

**Issue by jiangjiguang** [actions/runner#2467]
### Discussed in https://github.com/actions/runner/discussions/2466

<div type='discussions-op-text'>

<sup>Originally posted by **jiangjiguang** February 28, 2023</sup>
Now I have used the avx512vbmi and avx512_vbmi2 instruction set. I already knew Intel Ice lake include them, but Intel cascade lake dose not include them.  So how can I select runners with Intel Ice lake ?  thanks</div>

**Comment by ruvceskistefan** [comment]
Hey @jiangjiguang,

Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your question to the correct team. 😃
