### ISSUE TITLE
Docker build command not using environment variables (such as HTTP_PROXY)

### ISSUE THREAD

**Issue by acottre** [actions/runner#2476]
**Describe the bug**
HTTP_PROXY environment variable is passed through to the docker container when it is ran, but if it is required at the `docker build` stage, it does not propagate.

**To Reproduce**
First, a simple Dockerfile
```
FROM ubuntu:22.04
RUN env && apt-get update && apt-get -y upgrade
ENTRYPOINT ["/bin/env"]
```
And a simple action.yml 
```
runs:
  using: 'docker'
  image: 'Dockerfile'
```
You will see that the "env" during the docker build had no environment variables, whereas the docker image that is ran, has a lot

**Expected behavior**
I expect that the environment variables, specifically the http proxy (which I need to do the apt-update) would be there so that it works.

## Runner Version and Platform
actions-runner-linux-x64-2.296.3 self hosted Centos 7.9

## Job Log Output
If you look at a github action to build a docker job, you can see the two steps:
```
/usr/bin/docker build -t e455ed:4bc97031b3db52c327f2c917fc8683ad -f "<path_to_dockerfile>/Dockerfile" "<path_containing_dockerfile>"
```
And then
```
/usr/bin/docker run --name <name> --label <label> --workdir /github/workspace --rm -e "HTTP_PROXY" -e "http_proxy" -e "HTTPS_PROXY" -e "https_proxy" -e "NO_PROXY" -e "no_proxy" -e "SSH_AUTH_SOCK" -e -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" ...
```

**Code**
It looks like [here](https://github.com/actions/runner/blob/main/src/Runner.Worker/Container/DockerCommandManager.cs#L201) you can see environment variables are added to the docker run command, but none are done for the docker build command [here](https://github.com/actions/runner/blob/main/src/Runner.Worker/Container/DockerCommandManager.cs#L102).

**Workaround**
We can force the docker service to include these variables for now, via https://docs.docker.com/network/proxy/#configure-the-docker-client. But I would like them to be passed through the system like the rest.

**Comment by nikola-jokic** [comment]
Hey @acottre,

Thank you for reporting this! I think the issue you described should be considered as a feature request. 
It can also potentially be a breaking change, in case some workflows are relying on the current behaviour.

Can you please redirect this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests in GitHub Actions. 

For more information on this policy please [read our contribution guidelines](https://github.com/actions/runner#contribute).

**Comment by acottre** [comment]
Okay, I've raised it here: https://github.com/orgs/community/discussions/50311

**Comment by nikola-jokic** [comment]
Thank you!
