### ISSUE TITLE
Runner unable to be configured

### ISSUE THREAD

**Issue by vini-gorillas** [actions/runner#2478]
**Describe the bug**
The runners are deployed on k8 cluster and the pods are stuck with the exit code 2. The pods do. not even shutdown themslves after some failed retries which makes it impossible for. new runners to come up. 

**To Reproduce**
1. Se the errors from the pod: 

> Started listener process
An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.
Runner listener exited with error code 2
Runner listener exit with retryable error, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service

**Expected behavior**
the pod is killed and restarted after some  failed attempts. 

## Runner Version and Platform
Version of your runner?
2.279.0
OS of the machine running the runner? OSX/Windows/Linux/...

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"

## What's not working?

Runner cannot start the service

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs

[2023-03-09 09:53:58Z ERR  Terminal] WRITE ERROR: An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.
[2023-03-09 09:53:58Z ERR  Listener] System.InvalidOperationException: Not configured. Run config.(sh/cmd) to configure the runner.
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.LoadSettings()
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
   at GitHub.Runner.Listener.Program.MainAsync(IHostContext context, String[] args)

**Comment by nikola-jokic** [comment]
Hey @vini-gorillas,

Can you please check if this issue is happening when you are running the newest version of the runner? 
There are multiple improvements implemented in newer releases, so it would be nice to know if this issue is already resolved.

Thank you in advance :relaxed:
