### ISSUE TITLE
LTO - internal compiler error on ubuntu 20 runner

### ISSUE THREAD

**Issue by Nir-Az** [actions/runner#2508]
SInce Ubuntu 18 runners are deprecated we upgraded to Ubuntu 20 runners
We build with default GCC compiler and it activates link time optimizations that failed the build on an internal error in the compiler

```
lto1: internal compiler error: in add_symbol_to_partition_1, at lto/lto-partition.c:153
```

You can see the failure here: https://github.com/Nir-Az/librealsense/actions/runs/4542446813/jobs/8005870668

## Runner Version and Platform
```
Current runner version: '[2](https://github.com/Nir-Az/librealsense/actions/runs/4542446813/jobs/8005870668#step:1:2).[3](https://github.com/Nir-Az/librealsense/actions/runs/4542446813/jobs/8005870668#step:1:3)03.0'
Operating System
  Ubuntu
  20.0[4](https://github.com/Nir-Az/librealsense/actions/runs/4542446813/jobs/8005870668#step:1:4).[6](https://github.com/Nir-Az/librealsense/actions/runs/4542446813/jobs/8005870668#step:1:7)
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 2023031[7](https://github.com/Nir-Az/librealsense/actions/runs/4542446813/jobs/8005870668#step:1:8).1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230317.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230317.1


```

**Comment by softlberton** [comment]
Hi @Nir-Az ,

You could try this:

[how-can-i-solve-the-lto1-internal-compiler-error-in-lto-tag-to-tree-code-at-l](https://stackoverflow.com/questions/58840044/how-can-i-solve-the-lto1-internal-compiler-error-in-lto-tag-to-tree-code-at-l)

Regards !!

**Comment by Nir-Az** [comment]
Thanks for trying to help.
We don't see this issues with compiling on stronger computers so we wish to keep LTO on as it might reduce binaries size.
GH actions runners has 2 cores and 7 GB of memory, this might be the configuration that expose this compiler error..
