### ISSUE TITLE
PATH changes at runtime even when using the same User in self-hosted runners

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#2528]
**Describe the bug**
I created a self-hosted runner, installed some binaries, and ended up with this `PATH`
<img width="846" alt="image" src="https://user-images.githubusercontent.com/55927613/231453134-af604913-87b8-463a-9e73-a2f9b904c66e.png">

Then I configured one of my workflows to run using this runner. While this workflow was running, I noticed that none of my binaries were available because the runner changed the PATH at runtime, even when using the same User. Why does it happen? 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/55927613/231453502-b1c20a64-5fd0-49ee-8133-42f13213b10f.png">

The same happens for HOME. It is empty....

**To Reproduce**
1. Create a self-hosted runner using 2.303.0 and a Linux image (debian)
2. change its PATH for User X (it can be the root)
3. Create a workflow and run `echo $PATH` using the same User X
4. Verify that `PATH` is different. Because it is different, none of your binaries will be available at runtime.

**Expected behavior**
PATH must not change while the runner is running

## Runner Version and Platform
2.303.0 Linux

## What's not working?
`PATH` changes at runtime

**Comment by milesj** [comment]
@AllanOricil I've been dealing with a similar problem here: https://github.com/actions/runner/issues/2540

My problem is windows, but maybe a similar problem is happening on unix.

**Comment by AllanOricil** [comment]
@milesj I had this problem because the runner runs the steps with this bash command (which github calls the default template)

`bash --noprofile --norc`

This means that the `~/.profile` and `~/.basrc` were not loaded. Which means that my PATH changes won't be loaded, since they are registered in those files. So, to fix this issue, I changed the bash command to 

`bash -leo`

This forces the steps to run logged in as the User, and therefore load his `~/.profile` and `~/.basrc` files. 

Besides that, you also have to ensure you have configured the runner in the right User's directory. If you don't do it, then the bash configuration files for that user you was expecting to be loaded won't be sourced.

The same information I shared above can be abstracted to Windows runners. They also have a default shell, and a default template. You have to find the right one which will force the steps to run using the User's profile and powershell configurations.

**Comment by milesj** [comment]
Thanks for the info, that's helpful.

**Comment by markusjevringsesame** [comment]
I have the same problem. I'm not sure where I'd change this. I'm using the `summerwind/actions-runner:v2.306.0-ubuntu-22.04` as a base image, and no amount of Dockerfile manipulation lets me get to a working state where the PATH that is specified in my Dockerfile is accepted.

**Comment by morremeyer** [comment]
@markusjevringsesame You can override this with a `.env` file in `/runnertmp`, check for example https://github.com/actions/actions-runner-controller/issues/2273#issuecomment-1492556526.

I've been looking for this issue too, will open a documentation PR soon.

**Comment by AllanOricil** [comment]
Kind weird. The implementation should not change anything that isn't in the workflow yaml. It causes unpredictable and undocumented problems. I closed this because I found a solution. But if you want I can reopen this.

**Comment by morremeyer** [comment]
@AllanOricil I can't follow, this is not a change in any workflow.

@markusjevringsesame I see where you're coming from. I think this needs to be documented much better or ideally changed so that the PATH in the runner **extends** the PATH, not overwrites it.

**Comment by AllanOricil** [comment]
Even paths|home you add to the yaml are overwritten or not loaded

**Comment by Ghostbird** [comment]
> @markusjevringsesame You can override this with a `.env` file in `/runnertmp`, check for example [actions/actions-runner-controller#2273 (comment)](https://github.com/actions/actions-runner-controller/issues/2273#issuecomment-1492556526).
> 
> I've been looking for this issue too, will open a documentation PR soon.

I think that only applies to the ARC. The path `/runnertmp` doesn't exist on my machine, and cannot be created either (`/` is read-only)

**Comment by NiklasRosenstein** [comment]
Same problem here, I'm looking for a way to have `rustup` preinstalled on the Runner but in CI it won't find the binary.

**Comment by matan-legit** [comment]
why is this closed? how is it solved?

**Comment by morremeyer** [comment]
Because the behavior is intended and documented. See e.g. https://github.com/actions/runner/issues/2528#issuecomment-1733694912

**Comment by matan-legit** [comment]
@morremeyer is there any way to do other things that intended to run in .bashrc like this? not only env vars

**Comment by encryptcoder** [comment]
I ended up doing something like this in my Dockerfile

```Dockerfile
FROM ghcr.io/actions/actions-runner:latest
# ...
ENV ACTIONS_RUNNER_HOOK_JOB_STARTED=/home/runner/setup-path.sh
RUN echo 'eval "$(mise activate bash)"; echo "PATH=$PATH"; echo "$PATH">>$GITHUB_PATH' >> /home/runner/setup-path.sh
# ...
```
