### ISSUE TITLE
Cant run the app as a service using a non root user

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#2534]
**Describe the bug**
I have a self-hosted runner (Linux - Debian) running the runner app with a non root user. It runs perfectly when starting the app with `run.sh`. However, when starting the app as a service, using the same non root user, the service throws an exception that I can't really determine the cause. Take a look:

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/55927613/231800199-a662e375-7357-4fb0-84af-6591812a092c.png">

**To Reproduce**
1. create a non root user and login with it `su -s /bin/bash -l USER_NAME`
2. download the runner (2.303.1)
3. configure the runner
4. start the runner with `./run.sh` and verify that it is working as expected
5. unregister the runner
6. configure the runner again
7. logout (return to root session)
8. download the runner (2.303.1) again or copy the one from /home/USER_NAME
9. run `sudo ./svc.sh install USER_NAME` (install the service to run as the non root user) as described [here](https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service)
10. verify that the service was installed successfully, as shown below
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/55927613/231801226-7c9c1ed5-67c7-4358-99ff-c99b5363e265.png">
11. run `sudo ./svc.sh start`
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/55927613/231801377-7fe936a4-d6f8-4c53-875a-b19ffc119819.png">
12. verify the exception was thrown `sudo ./svc.sh status`
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/55927613/231801577-5402867b-3f55-477e-96ea-2b0d24928bb5.png">

**Expected behavior**
The runner app, when started as service, must run as a non root user. 

## Runner Version and Platform
2.303.1

OS of the machine running the runner? OSX/Windows/Linux/...
Linux (Debian)

## What's not working?
The runner app does not work when started as a service, running with a non root user. But it does work when using `run.sh` in the non root user directory

## Job Log Output
````bash
admin@ip-10-191-243-218:~/actions-runner$ sudo ./svc.sh status

/etc/systemd/system/actions.runner.VodafoneIS-salesforce-metadata.test-service.service
● actions.runner.VodafoneIS-salesforce-metadata.test-service.service - GitHub Actions Runner (VodafoneIS-salesforce-metadata.test-service)
     Loaded: loaded (/etc/systemd/system/actions.runner.VodafoneIS-salesforce-metadata.test-service.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-04-13 14:48:24 UTC; 35s ago
   Main PID: 1262 (runsvc.sh)
      Tasks: 8 (limit: 9523)
     Memory: 9.6M
        CPU: 762ms
     CGroup: /system.slice/actions.runner.VodafoneIS-salesforce-metadata.test-service.service
             ├─1262 /bin/bash /home/admin/actions-runner/runsvc.sh
             └─1265 ./externals/node16/bin/node ./bin/RunnerService.js

Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access…cationSize)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, Fi…cationSize)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at GitHub.Runner.Common.HostTraceListener.CreatePageLogWriter()
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at GitHub.Runner.Common.HostTraceListener..ctor(String logFileDirectory, String logFilePrefix, Int32…entionDays)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at GitHub.Runner.Common.HostContext..ctor(String hostType, String logFile)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at GitHub.Runner.Listener.Program.Main(String[] args)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]: Runner listener exited with error code null
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]: Runner listener exit with undefined return code, re-launch runner in 5 seconds.
````

**Comment by AllanOricil** [comment]
@nikola-jokic could you help here. Thanks.

**Comment by couling** [comment]
@AllanOricil Running my eyes over this I don't see the exception, just the tail end of a stack trace. I think you'll need to use `journalctl` to print the whole stack trace and some lines before that.  You can print the last 100 lines of a service named "foo" with:

```
journalctl -u foo -n 100
```

**Comment by AllanOricil** [comment]
@couling  
Running `journalctl -u actions.runner.VodafoneIS-salesforce-metadata.DEVELOP_BASIC.service` did not return anything

<img width="647" alt="image" src="https://user-images.githubusercontent.com/55927613/232024085-c58bc71f-ae63-42a9-978f-4fb84e9aaedb.png">


<img width="923" alt="image" src="https://user-images.githubusercontent.com/55927613/232024055-72735019-7455-430f-ac75-14df7bbb81e0.png">



And this is the exception I have when running the service using a non root user
````bash
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access…cationSize)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, Fi…cationSize)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at GitHub.Runner.Common.HostTraceListener.CreatePageLogWriter()
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at GitHub.Runner.Common.HostTraceListener..ctor(String logFileDirectory, String logFilePrefix, Int32…entionDays)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at GitHub.Runner.Common.HostContext..ctor(String hostType, String logFile)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]:    at GitHub.Runner.Listener.Program.Main(String[] args)
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]: Runner listener exited with error code null
Apr 13 14:48:55 ip-10-191-243-218 runsvc.sh[1265]: Runner listener exit with undefined return code, re-launch runner in 5 seconds.
````

**Comment by AllanOricil** [comment]
@couling I have many runners, and the one I ran the journalctl command has a service named that way. I think the output was empty because that runner has no issues. Is this right? 

I'm going to create another runner, install the runner app as a service for a non sudoer, run journalctl again, and then I will post the outputs here.
