### ISSUE TITLE
config.sh ... --replace true, --replace NAME or just --replace does not work A runner with the name xxxxxx already exists.

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#2538]
I have a script that recreates my runners using the exact same names. To avoid having to manually remove the runners from the repo before recreating them again, my script passes `--replace true` to the `config.sh`.  Im expecting the runners to be replaced, but this does not happen. Im getting an error message saying something like "name already used..." 

I've also tried using `--replace NAME` and it does not work.

**Comment by nnellanspdl** [comment]
`./config.sh --replace` has stopped working for me now too.

I get the error `A runner with the name vmghrunnpe201 already exists.` and that's it.

**Comment by nikola-jokic** [comment]
I was able to reproduce it only when the `replace` has an argument.
The script is using a correct `config.sh` invocation
Can you write what system are you using and the exact command that is failing?
And please make sure you replace any information that you don't want to be exposed

**Comment by AllanOricil** [comment]
Im using `Linux ip-10-191-243-15 5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux`

**Comment by nikola-jokic** [comment]
And can you send the command that is failing when you don't pass any arguments to the `--replace` flag?

**Comment by AllanOricil** [comment]
> And can you send the command that is failing when you don't pass any arguments to the `--replace` flag? 

The command is in one of my comments above. There is also a picture showing the output and the error message.

**Comment by nikola-jokic** [comment]
I can't reproduce this issue... I ran your script, and it works fine for me. The only thing is that maybe you can put quotes around arguments to make sure nothing is breaking up your command. I'm not sure, but I don't think something is wrong with the `--replace` flag... I'm not sure how exactly are you using your script, but I created a directory, created a file with your script, executed it with almost the same parameters and it worked

**Comment by AllanOricil** [comment]
@fhammerl could you explain your test steps. I believe we might be doing something differently, since both used the same script that I posted here.

**Comment by fhammerl** [comment]
`conf2.sh`:
```sh
#!/bin/bash

RUNNER_RUNTIME_VERSION=2.303.0
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --gh-owner) GH_OWNER="$2"; shift ;;
        --gh-repo) GH_REPO="$2"; shift ;;
		--runner-runtime-version) RUNNER_RUNTIME_VERSION="$2"; shift ;;
        --runner-name) RUNNER_NAME="$2"; shift ;;
		--runner-labels) RUNNER_LABELS="$2"; shift ;;
		--run-as-root) RUNNER_ALLOW_RUNASROOT="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

if [ ! $GH_OWNER ]; then
	echo "ERROR --gh-owner is required" >&2
	exit 1;
fi

if [ ! $GH_REPO ]; then
	echo "ERROR --gh-repo is required" >&2
	exit 1;
fi

if [ ! $RUNNER_RUNTIME_VERSION ]; then
	echo "ERROR --runner-runtime-version is required" >&2
	exit 1;
fi

if [ ! $RUNNER_NAME ]; then
	echo "ERROR --runner-name is required" >&2
	exit 1;
fi

if [ ! $RUNNER_LABELS ]; then
	echo "ERROR --runner-labels is required" >&2
	exit 1;
fi

pwd
who

# STEP 2 - download the github-actions-runner app
echo "DOWNLOADING RUNNER CONFIGURATION"
mkdir actions-runner && cd actions-runner
download_runner_cmd=$(curl -o actions-runner-linux-x64-$RUNNER_RUNTIME_VERSION.tar.gz -L https://github.com/actions/runner/releases/download/v$RUNNER_RUNTIME_VERSION/actions-runner-linux-x64-$RUNNER_RUNTIME_VERSION.tar.gz) && (echo $download_runner_cmd >&2)
$download_runner_cmd

tar xzf ./actions-runner-linux-x64-$RUNNER_RUNTIME_VERSION.tar.gz

# STEP 4 - create registration token using the GH_TOKEN from STEP 3

# export ACTIONS_RUNNER_INPUT_REPLACE=true
REPO_REGISTRATION_TOKEN="AHNBTOKENTOKENCONSTANTCONSTANT"
# STEP 5 - configure runner to run as a service
export RUNNER_ALLOW_RUNASROOT=true

echo "CONFIGURING RUNNER"
./config.sh --url https://github.com/$GH_OWNER/$GH_REPO \
	--token $REPO_REGISTRATION_TOKEN \
	--name $RUNNER_NAME \
	--labels $RUNNER_LABELS \
	--disableupdate \
	--replace \
	--unattended \
	--runasservice

if [ $? -ne 0 ]; then
    echo "ERROR while registering the runner"
	exit 1
fi

rm ./actions-runner-linux-x64-$RUNNER_RUNTIME_VERSION.tar.gz
```

I ran the above script like so on my private repo (with a correct reg token):
`./conf2.sh --gh-owner fhammerl --gh-repo instarunner --runner-name DEVELOP_BASIC --runner-labels foo`

Replacement works fine
