### ISSUE TITLE
GitHub Actions runs workflow twice for a template repository

### ISSUE THREAD

**Issue by hsz** [actions/runner#2550]
**Describe the bug**
When one creates a new project based on a template repository which contains a workflow that listens for the `push` event, the workflow runs twice.

**To Reproduce**

1. Go to https://github.com/hsz/github-actions-runs-workflow-twice-for-template-repository
2. Click the "Use this template" button to create a new project out of this template repository
3. Navigate to Actions tab of your new project
4. See a dummy workflow defined in `.github/workflows/hello.yml` run twice

**Expected behavior**
Run such a workflow once, as before.

**Comment by meiMingle** [comment]
@TingluoHuang Sir, please take a look at this error if you have time. Redundant workflow runs lead to waste of github resources, which is serious.

**Comment by skofsxm** [comment]
Is this issue resolved? I too face an issue that action is triggered twice.
Appreciate your response.

**Comment by hsz** [comment]
The issue seems to be obsolete now.
