### ISSUE TITLE
Inexplicable issues with Windows runner

### ISSUE THREAD

**Issue by mcallegari** [actions/runner#2556]
Hi, already posted this in [community discussions](https://github.com/orgs/community/discussions/50032) with no feedback at all.

I maintain a Qt application and recently started to adopt GitHub actions.
On Linux runners all good, however on Windows I've got a couple of issues I'm not able to figure out.
The project builds fine on a MSYS2 environment (either a PC or Appveyor CI)
On Actions I've got these:

cannot install files during make install with an inexplicable error
https://github.com/mcallegari/qlcplus/actions/runs/4357415918/jobs/7616702516#step:12:100
cannot find a library (libusb-1.0) via pkg-config even though the library is there
https://github.com/mcallegari/qlcplus/actions/runs/4215656744/jobs/7316954943#step:10:1555
The libusb-1.0 package provides the correct files:
https://packages.msys2.org/package/mingw-w64-i686-libusb?repo=mingw32
GH actions YAML file here:
https://github.com/mcallegari/qlcplus/blob/winbuild/.github/workflows/build.yml

Any help would be really appreciated.
Thanks!

**Comment by AF250329** [comment]
Hi

It seems that you have an error in your Makefile. According to workflow output:


![image](https://user-images.githubusercontent.com/78792938/235763613-cd845499-b777-40e7-b5fe-a811a724f2af.png)

There's a C:/C:/......  Check your Makefile on Windows

**Comment by mcallegari** [comment]
Thanks for the reply, but as I mentioned before, mine is a Qt project, so Makefiles are generated by qmake.
Unless the installed Qt version is buggy, Makefiles are generated correctly.
Also, if you notice, the "double C:" is present a few lines before and it seems perfectly fine:
https://github.com/mcallegari/qlcplus/actions/runs/4357415918/jobs/7616702516#step:12:94

Again, this project builds correctly on vanilla MSYS2 and with AppVeyor CI so I ended up thinking there might be something not right on Actions.
I admit I never built with Chocolatey before. Is there a way to use an alternative Windows runner, like a plain MSYS2 installation?

How about my other report about libusb1?
Thanks!

**Comment by AF250329** [comment]
The error that I highlighted in my answer does not come from Github Action. I don't know how Makefile works or what could be wrong with it. I personally think that Makefiles belong to Linux and just insisting to run pure Linux oriented code on Windows with some hacky compilers is wrong - but anyway - I think you should check the error and try to debug it by adding some output to script. This will give you some hints what wrong when running the same code on your computer and Github Action. Good luck

**Comment by mcallegari** [comment]
So basically, you don't know how Makefile works and you think building a Qt application on Windows is hacky and wrong.
Then why did you reply to my report in the first place? We're both wasting time here.

Is there anybody else more open minded and more competent that can please give an insight to this? Thanks

**Comment by AF250329** [comment]
Mmmm.. I know enough about Makefiles to know that only old versions of C++ was actually used it in build process according to Microsoft and even that one was not 1-to-1 as GNU Makefile implementation. Then MS leave it altogether for MSBuild scripts engine.

I personally think that using hacky MinGW when Microsoft already rolled out 'Linux subsystem for Windows' is hacky. MinGW trying to bend POSIX thread implementation to whatever Microsoft think is `CreateRemoteThread` should be. MS changing it undelaying implementation almost every release  of C++ libraries and most (?) of inner working details is un-documented. So what MinGW implementation think  on creating new thread on Windows ? (and it should also support Linux ot at least align to it behavior ) <- it is very hackishly way to compile application that Linux oriented in it nature and may be use quirks from Linux word. Again Microsoft already released Linux Subsystem for Window - so it makes MinGW and other similar system obsolete. So yes - using them today is just insisting to use old/outdated tools. Does MinGW still supported and actively developed ? I don't think so.. Nobody could beat MS in it own field of Windows....

I am still insist that error is not coming from Github Action - I am not sure what you still keep coming to it ? I see that Github Action **do** run you script and even resend output from script/app to the screen of workflow.

Please try to debug around this error let us all know what the error was
