### ISSUE TITLE
installdependencies.sh fail on Alpine Linux

### ISSUE THREAD

**Issue by aelnosu** [actions/runner#2575]
**Describe the bug**
When trying to run "installdependencies.sh" it recognize can not recognize I am using alpine.[See attachment (I am using Docker)]
![Screenshot 2023-04-28 11 32 15 AM](https://user-images.githubusercontent.com/113621927/235226288-b60154c1-9700-4840-b44e-ef0aee26a188.png)

1. Go to 'alpine-linux root'
2. Run './bin/installdependencies.sh' as root
3. See error

**Expected behavior**
Should install dependence.

## Runner Version and Platform
Version of your runner?
linux-x64-2.303.0.tar.gz

OS of the machine running the runner? OSX/Windows/Linux/...
Linux-Alpine:Latest

## What's not working?
Please include error messages and screenshots.
![Screenshot 2023-04-28 11 32 15 AM](https://user-images.githubusercontent.com/113621927/235226681-b5682726-7c11-4db4-bb42-cabea373552e.png)

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by rajadev2019** [comment]
Please look into it.
