### ISSUE TITLE
Unclear error messages in actions

### ISSUE THREAD

**Issue by mark-jordanovic-lewis** [actions/runner#2584]
**Describe the bug**
Unclear error message in workflow error. This causes an unecessary amount of debugging.

**To Reproduce**
1. Create an action that takes inputs.
2. Mistype the `runs` keyword as `run`.
3. Use the action in a workflow.
4. See the error: `Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.xxxxxx`

**Expected behavior**
A clear and concise description of the actual error: `'run' is not a valid keyword. Did you mean to write 'runs'?`

## Runner Version and Platform
Version of your runner? latest

OS of the machine running the runner? Ubuntu 20.04

**Comment by ruvceskistefan** [comment]
Hey @mark-jordanovic-lewis,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
