### ISSUE TITLE
a PR triggered a push action

### ISSUE THREAD

**Issue by taojintianxia** [actions/runner#2589]
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/4112856/236619908-c79da28c-d5ef-49d2-8e8b-02fc4a71aa2b.png">

in this pull request, not only triggered the action for pull_request, but also triggered an action for push.
https://github.com/apache/shardingsphere/pull/25455/checks

**Comment by ruvceskistefan** [comment]
Hey @taojintianxia ,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
