### ISSUE TITLE
spawned processes not utilizing all cpu resources

### ISSUE THREAD

**Issue by derekn** [actions/runner#2593]
**Describe the bug**
when running ffmpeg on self-hosted runners cpu usage appears to be capped at 50% usage (half of single core), when running same command manually on same runner machine it utilizes +700% cpu usage (all 8 cores). I experience the same issue on 2 separate self-hosted runners.

**To Reproduce**
1. create worflow that transcodes a video file using ffmpeg on self-hosted runner
2. check cpu usage on runner for ffmpeg process
3. manually run the same ffmpeg command logged into the runner directly
4. check cpu usage for ffmpeg process, notice the difference

**Expected behavior**
processes spawned from github runner service should utilize the same resources as if they were manually run

## Runner Version and Platform
Linux Ubuntu 20.04.6 LTS and Ubuntu 22.04.2 LTS
Current runner version: 2.304.0

## What's not working?
<img width="1304" alt="htop-github-action" src="https://github.com/actions/runner/assets/1420397/2cf67bf7-627c-4ba6-a94b-b238bf1c2f74">
<img width="1301" alt="htop-manually-run" src="https://github.com/actions/runner/assets/1420397/6111975f-b773-49b3-bb21-71127d89e12a">

**Comment by derekn** [comment]
this is solved, it was a limitation on the runner not within the github action service.

**Comment by zhouzh1** [comment]
@derekn could you share your fix? Seems that I also encountered such kind of issue. thx.

**Comment by derekn** [comment]
> @derekn could you share your fix? Seems that I also encountered such kind of issue. thx.

in my case the CPU was being limited in a service override on the runner via `CPUQuota` in systemctl
