### ISSUE TITLE
Type conversion error using repository variable for timeout-minutes

### ISSUE THREAD

**Issue by sgrtye** [actions/runner#2599]
**Describe the bug**
When using the repository variable for timeout-minutes in actions.yml, an error occurs with the message.

Error when evaluating 'timeout-minutes' for job 'Template'. .github/workflows/action-Template.yml (Line: 8, Col: 22): Unexpected value '10'

The problem can be solved by using the [fromJSON()](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson) function.

Example:
`timeout-minutes: ${{ fromJSON(vars.TIMEOUT) }}`

However, the type conversion is not supported natively in either YAML or repository variables.

The original discussion page is linked [here](https://github.com/orgs/community/discussions/55332).

**To Reproduce**
1. Set repository variable 'TIMEOUT' to 10.
2. In actions.yml write `jobs: Template: runs-on: ${{ vars.SYSTEM }} timeout-minutes: ${{ vars.TIMEOUT }}`
3. See error

**Expected behavior**
An error would occur, and the action failed.

## Runner Version and Platform
Version of your runner?
Latest

OS of the machine running the runner? 
OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

Error when evaluating 'timeout-minutes' for job 'Template'. .github/workflows/action-Template.yml (Line: 8, Col: 22): Unexpected value '10'
<img width="1107" alt="image" src="https://github.com/actions/runner/assets/55668018/267b7329-b9f2-46d4-8f81-547b91358d0e">

**Comment by ruvceskistefan** [comment]
Hey @sgrtye ,

This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
