### ISSUE TITLE
Support node20 in runs for JavaScript actions

### ISSUE THREAD

**Issue by kroese** [actions/runner#2619]
It would be very handy if Node 20 was supported in runs for Javascript actions, so that you could do:

```
runs:
  using: 'node20'
  main: 'index.js'
```

But currently only `node12` and `node16` are available, which is strange because all runners default to `node18` now.

**Comment by MikeMcC399** [comment]
> But currently only node12 and node16 are available, which is strange because all runners default to node18 now.

`node12` is being force-updated to use `node16` and `node12` is no longer listed in the documentation (https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions)

At this stage, supporting `node20` would probably make more sense which would give the change a longer lifetime.

**Comment by MikeMcC399** [comment]
Currently https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/ says

"we will start enforcing the use of Node16 rather than Node12 on the 14th of June." (2023)

**Comment by Hyokune** [comment]
I would also love for the support for `node18` to come through since we're upgrading all of our applications and actions to 18 but if this is the only one that doesn't support 18, it's going to have to be out of sync to the rest of our system.

**Comment by alexpeterson91** [comment]
Yeah we're having some issues with our CI/CD since we've updated our SDK to use node18, we've updated our GHAs to use checkoutV3 so it uses node 16 at least but were having a bunch of issues not being able to use node18 in our non self hosted runners, Would really like to know if Node18 is gonna be supported since we cant upgrade everything to node20, we really want to know if and when Node18 will be integrated.

**Comment by DariuszPorowski** [comment]
JFYI potential ugly temporary workaround for action authors: https://github.com/orgs/community/discussions/53217#discussioncomment-6227341

**Comment by MikeMcC399** [comment]
Without a resolution to this issue there is no long-term future for GitHub JavaScript Actions. It is difficult to understand why there has been no response so far. It's a critical piece of functionality to provide an upgrade path.

**Comment by rethab** [comment]
@benwells from GitHub has commented on this yesterday: https://github.com/actions/runner/discussions/2704

**Comment by MikeMcC399** [comment]
@takost 

> Hello, latest runner release ([2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0)) contains latest node16 version and node20 version. This runner version will be fully rolled-out by the end of this week. After release you will be able to use `'node20'` actions

Many thanks for the heads-up on this release!

Will the documentation on https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions also be updated to include `node20`? I couldn't see any related open PR on https://github.com/github/docs/pulls so far.

**Comment by MikeMcC399** [comment]
- issue #2786 opened for documentation.

**Comment by MikeMcC399** [comment]
@kroese 

I guess your issue could be closed now that ([2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0)) has been released. What do you think?

**Comment by WtfJoke** [comment]
Its now officially anounced:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

The docs were updated as well:
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

**Comment by Heyracks4456** [comment]
Deprecation: Importing non-Git repositories with GitHub Importer https://github.blog/changelog/2023-04-17-deprecation-importing-non-git-repositories-with-github-importer
