### ISSUE TITLE
Setting and targeting based on custom labels

### ISSUE THREAD

**Issue by nodesocket** [actions/runner#262]
There is mention of labels (https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-self-hosted-runners-in-a-workflow). How can I set a custom label on a actions runner instance and target it? For example we have a staging and production actions runner. If the branch = master we want to use the production actions runner, else we want to use the staging actions runner.

**Comment by R2ZER0** [comment]
A perhaps easier starting point could be to add the runner name as a label, so you could do something like:
```yaml
runs-on: [self-hosted, my-runner-name]
```

**Comment by bryanmacfarlane** [comment]
Custom labels are on the short backlog.  Hopefully coming soon.

**Comment by jonchang** [comment]
Homebrew has forked the GitHub Actions runner to support custom labels targeting by macOS version. It'd be great if this feature gets added to the official runner!

https://github.com/Homebrew/gha-runner

**Comment by rubencwi** [comment]
This is a critical functionality to be able to differentiate runners between environments or geo locations

**Comment by timharris777** [comment]
> Homebrew has forked the GitHub Actions runner to support custom labels targeting by macOS version. It'd be great if this feature gets added to the official runner!
> 
> https://github.com/Homebrew/gha-runner

This is great!! I just looked at the code changes. I think I'll be using this fork . Hoping github does this soon as it is critical functionality for us to adopt github actions.

**Comment by TingluoHuang** [comment]
@MalloZup I think the feature is out there and you can take a try.
https://help.github.com/en/actions/hosting-your-own-runners/using-labels-with-self-hosted-runners

**Comment by MalloZup** [comment]
@TingluoHuang thx a lot! :cupid:

**Comment by davidkarlsen** [comment]
```
Unrecognized command-line input arguments: 'labels'. For usage refer to: .\config.cmd --help or ./config.sh --help
./config.sh --version
2.169.1
```

**Comment by davidkarlsen** [comment]
Nothing in cmdline help:
```
runner@89ba235fdc6c:~$ ./config.sh --help

Commands:
 ./config.sh         Configures the runner
 ./config.sh remove  Unconfigures the runner
 ./run.sh            Runs the runner interactively. Does not require any options.

Options:
 --help     Prints the help for each command
 --version  Prints the runner version
 --commit   Prints the runner commit

Config Options:
 --unattended     Disable interactive prompts for missing arguments. Defaults will be used for missing options
 --url string     Repository to add the runner to. Required if unattended
 --token string   Registration token. Required if unattended
 --name string    Name of the runner to configure (default 89ba235fdc6c)
 --work string    Relative runner work directory (default _work)
 --replace        Replace any existing runner with the same name (default false)

Examples:
 Configure a runner non-interactively:
  ./config.sh --unattended --url <url> --token <token>
 Configure a runner non-interactively, replacing any existing runner with the same name:
  ./config.sh --unattended --url <url> --token <token> --replace [--name <name>]
```

**Comment by davidkarlsen** [comment]
though it does seem to work! :-)

**Comment by TingluoHuang** [comment]
@davidkarlsen Oops... thanks for reporting, looks like we forgot to update the CLI help

@lokesh755 for fixing this. 😄

**Comment by MalloZup** [comment]
@davidkarlsen  yes the GUI is working allthough the CLI need a fix.

@TingluoHuang  I would perhaps rename the issue with this info at least.

**Comment by rubencwi** [comment]
experiencing the same problem with labeling from CLI
