### ISSUE TITLE
Reopening #886

### ISSUE THREAD

**Issue by Greg-Myers-SB** [actions/runner#2622]
**Describe the bug**
When opening the "run" page for an active job you can see:

Gray checkmarks and expandable sections for completed steps and all of their log lines.
Yellow loading animation on any active steps.
Circles for the future steps.
The log lines for the active steps will then start streaming in, but the prior lines for that step are not there, and there appears to be no way to see them until the step completes.

**To Reproduce**

- Run an action
- Visit the run page after a few seconds and try to find the log lines for the currently running step that occurred before you loaded the page.

**Expected behavior**
All of the log lines that were emit before I loaded the page should be visible, then new ones stream in afterwards.

Same as #886 , still ongoing bug.

**Comment by ruvceskistefan** [comment]
Hey @Greg-Myers-SB,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃

**Comment by Greg-Myers-SB** [comment]
@bryanmacfarlane in this post https://github.com/actions/runner/issues/886#issuecomment-1405845909 mentioned this is in progress, so I believe this is the correct team and place for this issue. 
Please re-open so people like @julienbonastre and others [can follow](https://github.com/actions/runner/issues/886#issuecomment-1510520501) an open issue. This is a disservice to now allow tracking progress of an open and accepted issue on GitHub.

**Comment by Greg-Myers-SB** [comment]
https://github.com/actions/runner/issues/886#issuecomment-1669631425
> The current ETA for beta testing this feature is end of August / early September timeframe.

**Comment by Greg-Myers-SB** [comment]
Closing as this is now in public Beta
https://github.com/orgs/community/discussions/89879
https://github.com/github/roadmap/issues/839
