### ISSUE TITLE
Dedupe annotations created by problem matchers

### ISSUE THREAD

**Issue by xt0rted** [actions/runner#264]
**Describe the enhancement**
When running a matrix build check annotations created by problem matchers are duplicated across each workflow run. This means if you run the same workflow on macos, ubuntu, and windows you end up getting 3 of the same annotation showing in the file. This gets very noisy and since they're all the same it'd be nice if these were deduped and only one was shown or created.

**Code Snippet**
If applicable, add a code snippet.

**Additional information**
An example of this can be seen here https://github.com/StylishThemes/GitHub-Dark/commit/ca70a8e3e201aff4cab86664c593bbd16e43a959#diff-aa780f1a07d37f73f07563ec2df97206

**Comment by silverwind** [comment]
It'd be nice if cases of exact same errors would show as one merged annotation instead, for example:

````
GitHub Actions / build (macOS-latest, ubuntu-latest, windows-latest)
````

**Comment by thboop** [comment]
@xt0rted, @silverwind  thanks for the feedback! 
We've brought this to the attention of the team working on Annotations to see if we can improve this experience! ✔️ 

This isn't an issue we could solve in the Runner, so I'm going to close this issue.
