### ISSUE TITLE
network label same for each workflows

### ISSUE THREAD

**Issue by bbrunodiad** [actions/runner#2647]
**Describe the bug**
Hi
When I launch 2 workflows at the same time that use service container (to run postgres, redis an rabbitmq for example), they have the same label. 
As you can see, the 1st workflow creates a network with this label : 
```
Create local container network
  /usr/bin/docker network create --label c3f261 github_network_02a5eecd05de4c4f
```
But the second one is going to destroy the first : 
```
Clean up resources from previous jobs
  /usr/bin/docker ps --all --quiet --no-trunc --filter "label=c3f261"
  /usr/bin/docker network prune --force --filter "label=c3f261"
  Deleted Networks:
  github_network_02a5eecd05de4c4f
```
**To Reproduce**
1. In my case, when I launch two workflows at the same time, the second one always destroy the first 

**Expected behavior**
How to modify this label so the workflows can be no dependant ? 

## Runner Version and Platform

My runners are currently hosted on an ECS cluster 

## What's not working?
The first job : 
<img width="1325" alt="image" src="https://github.com/actions/runner/assets/107848125/27424f14-3ead-4d11-9b50-c85a4e8f3f1e">

The second job that destroys the first one : 
<img width="817" alt="image" src="https://github.com/actions/runner/assets/107848125/42841331-c23a-43d0-b739-a39822ebafd1">

**Comment by bbrunodiad** [comment]
Any helper ^^

**Comment by nikola-jokic** [comment]
Hey @bbrunodiad,

Can you explain how did you start your runners, so I can reproduce this issue exactly :relaxed:? I think I know where the fix should be applied to, but I want to confirm that I'm covering your use-case

**Comment by bbrunodiad** [comment]
> Hey @bbrunodiad,
> 
> 
> 
> Can you explain how did you start your runners, so I can reproduce this issue exactly :relaxed:? I think I know where the fix should be applied to, but I want to confirm that I'm covering your use-case

Yes for sure ! They are Launched with dispatch mode!
