### ISSUE TITLE
Error: An image label with the label Ubuntu22 does not exist.

### ISSUE THREAD

**Issue by short-dsb** [actions/runner#2653]
**Describe the bug**
No longer able to run jobs on `ubuntu-latest`.

**To Reproduce**
1. Run a job on `ubuntu-latest`
3. Job is automatically cancelled with error “An image label with the label Ubuntu22 does not exist.”

**Expected behavior**
Job runs normally, as it did previously.

## Runner Version and Platform
> Current runner version: '2.304.0'

OS of the machine running the runner? OSX/Windows/Linux/...
Linux (Ubuntu)

## What's not working?
Please include error messages and screenshots.

> An image label with the label Ubuntu22 does not exist.

![annotations](https://github.com/actions/runner/assets/105942728/3560069d-998d-4d13-867a-4ba6f36c6032)

## Job Log Output
> This job was cancelled

**Comment by GZGavinZhao** [comment]
I'm encountering the same error here. GitHub cli shows me this:
```
ANNOTATIONS
! An image label with the label Ubuntu22 does not exist.
analyze; Dart 2.18.0; PKGS: ngast, ngcompiler, ngdart; `dart format --output=none --set-exit-if-c...: .github#1

X GitHub Actions has encountered an internal error when running your job.
analyze; Dart 2.18.0; PKGS: ngast, ngcompiler, ngdart; `dart format --output=none --set-exit-if-c...: .github#1
```

Relevant [run](https://github.com/angulardart-community/angular/actions/runs/5249594878), relevant [job](https://github.com/angulardart-community/angular/actions/runs/5249594878/jobs/9482566027).

**Comment by GZGavinZhao** [comment]
Seems to be due to actions/runner-images#7660

**Comment by GZGavinZhao** [comment]
Ah yes, this issue has been resolved. Just paused the CI for a few days and then everything went back to normal. Thanks for following up!

**Comment by nikola-jokic** [comment]
Thank you for the confirmation!
