### ISSUE TITLE
The runner has received a shutdown signal

### ISSUE THREAD

**Issue by Rotemsim3339** [actions/runner#2662]
The self-hosted runner: xxx lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

For the last few weeks we are facing this issue. at least once a day.
we are running on self hosted - kubernetes - aws machine- linux m5.8xlarge. so there is no chance its a resources issue.
no logs to help for investigating this issue. and its not happening on the same workflow/same time at the day. a bit randomly. 

running for exmaple : https://github.com/digibank-il/mobile-tests/actions/runs/5308905824

any lead would be halpful.
Thanks,

**Comment by nikola-jokic** [comment]
Hey @Rotemsim3339,

Is this happening when you have a spike of runners? I guess this can happen when many runners are scheduled on the same node, but I might be wrong. Do you have requests/limits configured for the runner? Maybe configuring runner pods as `Guaranteed` can fix this problem :relaxed:
