### ISSUE TITLE
Exit code 3 after auto update

### ISSUE THREAD

**Issue by imishchuk-carbon** [actions/runner#2669]
Hello, team.

**Describe the bug**
We are running self-hosted Github runners in AWS ECS and recently enabled `auto-update`. Current configuration of self-hosted Github runner is using version `2.304.0`. Now that `2.305.0` is available, runner tries to update but in that process it sends `exit code 3` and thus ECS task is stopped. As far as I understand, [this code](https://github.com/actions/runner/blob/main/src/Runner.Listener/SelfUpdater.cs#L764-L797) handles runner update, yet I am not sure at which stage does it send exit code. Intention is to intercept that call to prevent ECS from stopping the task.

**To Reproduce**
1. Run self-hosted Github runner in ECS
2. Use previous version, e.g. `2.304.0`
3. Do not disable auto-update
4. Start the runner

**Expected behavior**
Either runner restart is done graciously without stopping main process or some mechanism to catch the signal is provided.

## Runner Version and Platform
`2.304.0`

OS of the machine running the runner? OSX/Windows/Linux/...
`Linux`

## What's not working?
```
# Authentication
--
  | Using V2 flow: False
  | √ Connected to GitHub
  | # Runner Registration
  | √ Runner successfully added
  | √ Runner connection is good
  | # Runner settings
  | √ Settings Saved.
  | √ Connected to GitHub
  | Current runner version: '2.304.0'
  | 2023-06-23 08:46:43Z: Listening for Jobs
  | Runner update in progress, do not shutdown runner.
  | Downloading 2.305.0 runner
  | Waiting for current job finish running.
  | Generate and execute update script.
  | Runner will exit shortly for update, should be back online within 10 seconds.
  | Runner update process finished.
```

<img width="611" alt="image" src="https://github.com/actions/runner/assets/100925121/fe5a3741-1316-43a7-be6b-e1ec8b78a595">

Thank you.

**Comment by imishchuk-carbon** [comment]
Same behavior can be reproduced in local Docker as well
```
docker run -it --entrypoint /bin/bash \
  -e RUNNER_SCOPE="org" \
  -e ORG_NAME="org_name" \
  -e RUNNER_WORKDIR="/tmp/_work" \
  -e RUNNER_GROUP="ECS-runners" \
  -e ACCESS_TOKEN="ghp_***" \
  githubRunnerImage:2.304.0

bash-4.2# /tini -- /entrypoint.sh ./bin/Runner.Listener run --startuptype service

[WARN  tini (9)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
Runner reusage is disabled
Obtaining the token of the runner
Configuring

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Using V2 flow: False

√ Connected to GitHub

# Runner Registration




√ Runner successfully added
√ Runner connection is good

# Runner settings


√ Settings Saved.


√ Connected to GitHub

Current runner version: '2.304.0'
2023-06-23 10:23:05Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.305.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should be back online within 10 seconds.
Runner update process finished.

bash-4.2# echo $?
3
```

Thanks

**Comment by nikola-jokic** [comment]
Hey @imishchuk-carbon,

I think the problem is that your entrypoint is the `./bin/Runner.Listener`. The RunnerListener would exit with the status code 3, and the caller is responsible to interpret this exit code and re-start the runner.

The correct entrypoint would be to actually run the `./run.sh` or `./svc.sh`. They eventually start the RunnerListener, and once the listener exits, they inspect the exit code and re-start it on the self update :relaxed:

**Comment by imishchuk-carbon** [comment]
Hey @nikola-jokic 

Thanks for looking into this.
Yeah, let me try changing entrypoint and see how it goes.

**Comment by imishchuk-carbon** [comment]
Hey @nikola-jokic 
Yup, changing entrypoint to execute `./run.sh` after all necessary configuration was done solved the issue.
Thank you.
