### ISSUE TITLE
Workflow File Marked Invalid with Depth of 3

### ISSUE THREAD

**Issue by ahmedElqutb** [actions/runner#2674]
**Describe the bug**
Working in one of our repos we had a failed workflow run as per:
```error parsing called workflow
".github/workflows/e2e.yml"
-> "./.github/workflows/e2e-workflow-versioned.yml" (source branch with sha:db045259a288357f34cb1e82b20765e80c24b3b9)
--> "./.github/workflows/e2e-tests-and-summary.yml" (source branch with sha:db045259a288357f34cb1e82b20765e80c24b3b9)
---> "./.github/workflows/e2e-tests.yml" (source branch with sha:db045259a288357f34cb1e82b20765e80c24b3b9)
: job "feature-kie" calls workflow "./.github/workflows/e2e-feature-kie.yaml", but doing so would exceed the limit on called workflow depth of 3
```

**To Reproduce**
1. running the aforementioned workflow on github.

**Expected behavior**
workflow run would start without said issue

## Runner Version and Platform
[v2.303.0](https://github.com/actions/runner/releases/tag/v2.303.0) hosted on github

OS of the machine running the runner? inapplicable

## What's not working?
<img width="1142" alt="Screenshot 2023-06-27 at 14 51 43" src="https://github.com/actions/runner/assets/24413320/320ceee6-2d72-4e47-9900-8d0334845cd8">

**Comment by nikola-jokic** [comment]
Hey @ahmedElqutb,

Thank you for raising this issue. However, this issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions) which is actively monitored. Using the forum ensures that we route your problem to the correct team. :relaxed:
