### ISSUE TITLE
Show steps name in composite

### ISSUE THREAD

**Issue by behdad088** [actions/runner#2681]
**Describe the bug**
When running action with composite it does not show the steps name, instead it shows a generic message `Run action ..`. I tried using `Run and shell` to print out the steps with some steps does not accept these values. 

![Screenshot 2023-07-07 094021](https://github.com/actions/runner/assets/9384578/347f7eb0-d6b9-45d0-9a55-004592eb0cb3)

**To Reproduce**

1. Step up an action with composite 
2. Use the composite in an action 
3. run the action

Or you can simply look at my setup [here](https://github.com/behdad088/AspnetCoreMicroservices-Eshop).

**Expected behavior**
The expected behavior would be to show all the steps name when running the action with composite. Below is a screenshot of what happens when I run the same steps directly into actions without using composite. 

 ![Screenshot 2023-07-07 095539](https://github.com/actions/runner/assets/9384578/6e75dc0d-d381-4e1b-b494-3574850793d9)

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? All

## What's not working?
Please include error messages and screenshots.
![Screenshot 2023-07-07 095758](https://github.com/actions/runner/assets/9384578/cc664ebd-1203-4198-8b4f-d506bccf5874)

**Comment by nikola-jokic** [comment]
Hey @behdad088,

Thank you for raising this issue. This is however an enhancement, so can you please post this to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests and enhancements in GitHub Actions. 

For more information on this policy please [read our contribution guidelines](https://github.com/actions/runner#contribute). :relaxed:

**Comment by kluen** [comment]
Hi @behdad088, did you end up re-creating this ticket somewhere else? I was unable to find anything.

**Comment by behdad088** [comment]
Hi @kluen, yes I re-created a ticket [here](https://github.com/orgs/community/discussions/61038) but have not gotten any response yet!

**Comment by Sbrjt** [comment]
https://github.com/actions/runner/issues/1877

**Comment by HiteshSahu-TW** [comment]
Any update on this?
