### ISSUE TITLE
Problem matcher rooted file path from container action does not work

### ISSUE THREAD

**Issue by ericsciple** [actions/runner#269]
refer to https://github.com/actions/toolkit/issues/224#issuecomment-571304570

**Comment by ericsciple** [comment]
Working on a fix... should be pretty small, will finish testing tomorrow.

This might also be a problem with job container. Test that scenario too.

**Comment by ericsciple** [comment]
@edhgoose fyi

**Comment by edhgoose** [comment]
Thank you @ericsciple! Is that change now deployed (if not, when will I know it is)? I'll give it a spin and see if its working for me as hoped!

**Comment by ericsciple** [comment]
Not deployed yet. v2.164.0 is going out soon. Based on typical rhythm, I would expect 2.164.1 to be next week or the week after.

**Comment by edhgoose** [comment]
Hi @ericsciple - just checking in as I haven't seen this mentioned in the release notes, am I safe in assuming this is on production now?

I'm unfortunately not seeing it working for me. Any ideas on how I can check what's failing?

**Comment by TingluoHuang** [comment]
@edhgoose it's part of 2.165.0/1 runner and it's about to release.

**Comment by edhgoose** [comment]
Thank you!
