### ISSUE TITLE
Unable to change the workspace on local runner

### ISSUE THREAD

**Issue by huncholane** [actions/runner#2706]
name: Deploy

on:
  push:
    branches:
      - main
env:
  GITHUB_WORKSPACE: /home/user/repo/name

This says it relies on the environment variable GITHUB_WORKSPACE
https://github.com/actions/checkout

This says you can change environment variables.
https://www.actionsbyexample.com/environment-variables.html

One would think its possible to change the environment variable to another location than /home/user/actions_runner/_work/repo/repo/name

The goal here is to change the workspace, but it's not possible to change this variable?
Maybe it's best to just use git hooks. This wastes ram, limits abilities, and costs money to deploy on multiple servers.

**Comment by nikola-jokic** [comment]
Hey @huncholane,

I'm not entirely sure if this is fixing your problem, but using https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun seems like a more appropriate. If not, can you write what exactly you want to do so I can try to help :relaxed: ? You can't overwrite environment variables used by the runner to influence its behaviour.

**Comment by sternj** [comment]
I think this should be reopened-- I just ran into the same problem. Not being able to change the path of the default workspace from being `<repo-name>/<repo-name>` has caused problems for me.

**Comment by alexgaganashvili** [comment]
@nikola-jokic , I need to be able to set GITHUB_WORKSPACE to a volume mount (which is a block storage volume) so that the checkout action occurs faster. I'm using NFS-backed storage to support RWX and cloning repo to an NFS storage-backed volume is very slow.
