### ISSUE TITLE
Use of echo "::endgroup::" overwrites last command status

### ISSUE THREAD

**Issue by Skptak** [actions/runner#2724]
**Describe the bug**
The use of `echo "::endgroup::"` for putting logs into a collapsible section will over-write the status of the previous command written. This means if you want to run a command inside of an echo group, then close the group, then conditionally print a message based upon the command that was run you have to put the `echo "::endgroup::"` inside of the if/else statement.

**To Reproduce**
1. Create a github workflow file
2. Add `set -e` on a `shell: bash`, or an equivalent version for `shell: powershell`, to the run command
3. Create an echo group using `echo "::group::GROUP_NAME"`
4. Run a command that will return an error status
5. Run the `echo "::endgroup::` command
6. Check the status of the previous command
7. See the status of the `echo "::endgroup::`, not of the command you ran

**Expected behavior**
I expected `echo "::endgroup::` to not over-write the status of the previous command as I did not expect it to be run on the same shell.

## Runner Version and Platform
This error can be produced on the `ubuntu-latest shell:default`, `windows-latest shell:bash`, `windows-latest shell:default`

## What's not working?
Explained Below

## Job Log Output
Workflow file for `ubuntu-latest` with `shell: default` showing this issue can be found [here](https://github.com/Skptak/FreeRTOS/actions/runs/5694857186/workflow#L235). Output for `ubuntu-latest` using `shell:default` can be found [here](https://github.com/Skptak/FreeRTOS/actions/runs/5694857186/job/15436865783#step:3:28). 

Workflow file for `windows-latest` with `shell: bash` showing this issue can be found [here](https://github.com/Skptak/FreeRTOS/actions/runs/5694857186/workflow#L15). Output for `windows-latest` with `shell: bash` can be found [here](https://github.com/Skptak/FreeRTOS/actions/runs/5694857186/job/15436866217#step:3:27).

Workflow file for `windows-latest` with `shell: default` showing this issue can be found [here](https://github.com/Skptak/FreeRTOS/actions/runs/5694857186/workflow#L154). Output for `windows-latest` with `shell: default` can be found [here](https://github.com/Skptak/FreeRTOS/actions/runs/5694857186/job/15436865644#step:4:344).

Another (potentially easier to follow) Workflow file for `windows-latest` with `shell: default` showing this issue can be found [here](https://github.com/Skptak/FreeRTOS/actions/runs/5695028050/workflow#L153). Output for `windows-latest` with `shell: default` can be found [here](https://github.com/Skptak/FreeRTOS/actions/runs/5695028050/job/15437357346#step:4:23).

## Runner and Worker's Diagnostic Logs
N/A

**Comment by nikola-jokic** [comment]
Hey @Skptak,

Please correct me if I'm wrong, but this seems to be working fine.
The `ls 123421849832` returns an exit code, but since the `set +e` is used, the script proceeds.
Then, the `echo "::endgroup::"` command is executed. Since echo did not return an error, `$?` would be `0`.

To get around this issue, you can save the error code just before endgroup.
```bash
ret=$?
echo "::endgroup::"
if [[ "$ret" = "0" ]]; then
# ...
```

**Comment by Skptak** [comment]
Hey @nikola-jokic,
Yes, you're correct that by using the command `set +e` I should continue past an error in my script. I have updated my workflows to get the error code, and then use the `echo "::endgroup::"` command. After which I use the `set -e` command to enable instant failure on errors, and then check the capture returned status as you proposed:
```
          # Store status as the echo group will overwrite it
          exitStatus=$?
          set -e
          echo "::endgroup::"

          if [ $exitStatus -eq 0 ]; then
            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
          else
            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
          fi
```

The reason I raised this bug is because I was under the assumption that `echo "::endgroup::"` was a command exclusively being run on the github workflow parser. Much in the way that the above` ${{ env.bashFail }}`   is replaced by the actual string for the runner, not evaluated as a variable when I use it

Since I **assumed `echo "::endgroup::"` was not run on the actual runner machine**, I considered this behaviour to be a bug. Since it's a log aggregation command, and only used by end-users to create collapsible logs, I thought it would not be run on the host machine for the workflow and therefore not over-write a previous commands status.

I feel that simply adding a note to the relevant [github documentation](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines) stating that these echo groups are commands run on the host machines, and therefore overwrite exit statuses, would be useful.

**Comment by bryanmacfarlane** [comment]
The runner does execute the script.  It watched stdout for `::endgroup::` (that's why you need to echo it) and other output commands and then performs the relevant work.

**Comment by nikola-jokic** [comment]
Closing this issue since it is not a runner bug.

Feel free to open an issue in the https://github.com/github/docs repo :relaxed:
