### ISSUE TITLE
/home/runner/work/_temp/f05122dc-d259-4a83-8fcf-b8e459d2a95a.sh: line 2: token:: command not found

### ISSUE THREAD

**Issue by deba1275** [actions/runner#2735]
This is my simple test workflow 

name: Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-20.04
    steps:
      - name: Output Github context
        run: "${{ toJSON(github) }}" 

while running - I am getting error 

/home/runner/work/_temp/f05122dc-d259-4a83-8fcf-b8e459d2a95a.sh: line 2: token:: command not found
 
Any suggestion how to fix this issue .. looks like something additional steps require.

**Describe the bug**
/home/runner/work/_temp/f05122dc-d259-4a83-8fcf-b8e459d2a95a.sh: line 2: token:: command not found

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by nikola-jokic** [comment]
Hey @deba1275,

With `run: "${{ toJSON(github) }}"`, you are essentially writing script which contains json serialized object. Since JSON output is not a valid script, the command fails.

I assume you would like to output contents of it. The correct way would be:
`run: echo "${{ toJSON(github) }}"`
