### ISSUE TITLE
Self-hosted runner group picks up wrong job, and doesn't pick up the right job

### ISSUE THREAD

**Issue by yanghua-ola** [actions/runner#2768]
**Describe the bug**
I have 5 GitHub runners running side by side on a Mac Mini. They are separated into two runner groups, 
1. `Default` 
2. `client-deploy`. 

The `client-deploy` group was limited to `playground` repository. So far I have observed two unexpected behaviours.

1. **occasionally runner in `client-deploy` group picked up job from repository other than `playground`**

   Given sample workflow from another repository not in the allowed list of the runner group, sometimes the runner picked up the job regardlessly. It happens frequently enough, but when I trigger the workflow again, usually the right agents picked up the job

    Workflow file
    ![image](https://github.com/actions/runner/assets/86941588/ba9bc7e6-e799-4cd1-9fd8-578e7ffadd58)
      
    Job info
    ![image](https://github.com/actions/runner/assets/86941588/a446129d-5d5f-4a63-8b9e-16c23deeb685)

2. **runner in `client-deploy` group didn't pick up job from `playground` repository**
    > Here you see `clientdeploy` instead of `client-deploy` as the runner group name, it was a desperate attempt to see if `-` made a difference.

    This happens 100%. But curiously, if I add a label to the runner and specify runner with label instead of runner group name, the runner was able to pick up the job.
  
    Workflow file
    ![image](https://github.com/actions/runner/assets/86941588/f6b02a4f-87f4-4f5d-ab42-ccf8a32b99e8)
    
    Job info
    ![image](https://github.com/actions/runner/assets/86941588/9f7fb137-bb7c-4496-a67a-084b6aea75ed)

    ![image](https://github.com/actions/runner/assets/86941588/436c1453-dd31-45da-8e6e-8475ce9a185e)

**To Reproduce**
I don't think it would be easy to replicate my setup (Mac OS, multiple runners on same machine). However if you have a troubleshoot script, I am happy to run it and report back. I tried [this guide](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/monitoring-and-troubleshooting-self-hosted-runners?platform=mac#troubleshooting-network-connectivity), didn't find anything.

**Expected behavior**
Runner in `client-deploy` group picks up job from approved repository, not jobs from other repositories

## Runner Version and Platform
Version of your runner?
2.307.1

OS of the machine running the runner? OSX/Windows/Linux/...
```
Model Name: Mac mini
Model Identifier: Mac14,3
Model Number: Z16L00005ZP/A
Chip: Apple M2
System Version: macOS 13.2.1 (22D68)
```
## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by markstos** [comment]
I'm seeing this on a Linux self-hosted runner running with four runners that all report their version 2.308.0.

In the affected repo's settings, I see it has exactly one one runner shared with it, named `ci`, in the runner group `Default`.  

In the affected workflow, I have this:

```yaml
jobs:
  build:
    runs-on:
      labels: self-hosted
      group: Default
```

It seems seems like I would set up for success: Only the correct runner is shared with the repo and the workflow has precisely selected it. 

Yet, the log output from a run of that workflow will clearly show a different runner has been selected.

As a test, I shut down the other three runners on the server and re-ran the workflow. In that case, when there is exactly one runner on the server, the correct runner is selected! But as soon as I turn the other runners back on, a wrong runner is selected again. 

Given what the other report said above, I'm going to try adding an additonal label to the correct runner and try to select it by label instead of group.

**Comment by markstos** [comment]
Like the other reporter, when I switch from using groups to labels to target the runner, I'm able to select it successfully. I tried launching the job three times after switching to selecting by label, and all three selected the correct runner.

**Comment by hallgeir-osterbo-visma** [comment]
We're having a similar issue. We have a workflow that SHOULD use a Github-hosted runner (ubuntu-latest). 

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       ...
```
However, it's being picked up by one of several self-hosted runners, that is newly created. The self-hosted runners are in different runner groups as well, and are organization runners.

**Comment by mikkoc** [comment]
We just hit the same issue. Yesterday we updated our self-hosted runners from 2.301.1 to 2.309.0 and now our self-hosted runners are randomly picking up jobs that are supposed to run on `ubuntu-latest`. Our self-hosted runners are AmazonLinux 2023.

**Comment by f1sle** [comment]
I noticed something weird today... I had a self-hosted actions runner on my "machine#1" for the project and I decided to run containers on my "machine#2", so I created another self-hosted runner for the same project; I got a pop-up asking if I want to remove existing actions-runner for the project - machine#1. I hit yes, and after I re-run my jobs my containers were created on machine#1 instead of machine#2...

**Comment by vartiait2** [comment]
We also noticed this bug today. We have self-hosted linux runners (all within a single runner group) and using also GitHub hosted Windows runners. A self-hosted linux runner with labels "self-hosted, Linux, X64, ubuntu-22.04" incorrectly picks up a job labeled with (runs-on) "windows-2022".

**Comment by thboop** [comment]
Hey folks, Thanks for taking the time to report this issue, our team is looking into it. Could you please provide a workflow url like [this](https://github.com/actions/runner/actions/runs/6326848222) where you saw the issue? If you don't feel comfortable posting that in this thread, please email me by appending `@github.com` to my username

**Comment by DARKo6o6o6** [comment]
I will take care of it in my own time other things are more important

**Comment by hallgeir-osterbo-visma** [comment]
I've re-enabled the self-hosted runner we had that was picking up the jobs that were meant for the ubuntu-latest hosted agent -- for some reason it works fine so far today. Has something been done that could have fixed this lately? 

I'll keep it running and see if it keeps being stable. If it fails I'll send you the logs @thboop (unfortunately it's in a private repo so I suppose sharing the URL won't be any good).

**Comment by vartiait2** [comment]
Yesterday, we downgraded runners' version back to 2.301.1 and the jobs were picked up correctly, and afterwards couldn't anymore reproduce the bug when trying with newer runner versions including 2.309.0.

**Comment by Kaspik** [comment]
@luketomlinson Still seeing this issue, where job is run on wrong runner that is not even specified in workflow file. Should run on `macOS` `iOS`, runs on something totally else and random.

[here](https://github.com/classdojo/dojo-behavior-ios/actions/runs/7567012607) is a link to the run
Attaching screenshots where you can see what runners & labels we have, what it should run on in the workflow file, and what it actually runs on (I don't even know what `d2` machine name is, it's not attached to our repo at all?! Is it some random foreign runner?)

<img width="1246" alt="Screenshot 2024-01-18 at 9 20 38" src="https://github.com/actions/runner/assets/7204168/ff492720-e037-4478-aff6-f6358255ad4b">
<img width="923" alt="Screenshot 2024-01-18 at 9 21 22" src="https://github.com/actions/runner/assets/7204168/9462989e-60c6-4b8a-9f7d-15d205696d42">
<img width="819" alt="Screenshot 2024-01-18 at 9 23 02" src="https://github.com/actions/runner/assets/7204168/1152c27f-511f-445d-a96a-c1adf94bfc0b">

**Comment by rbleuse** [comment]
Hi @luketomlinson I'm facing the same issue with our GHES 3.11
Our group `chatbot-platform` allows a public repository to run workflows, however it's the wrong group / runner that is picked when executing the job

<img width="797" alt="Screenshot 2024-05-28 at 9 41 59" src="https://github.com/actions/runner/assets/626863/661116fd-cf3e-4be0-9f74-8dfdb732ced9">
<img width="407" alt="Screenshot 2024-05-28 at 9 42 25" src="https://github.com/actions/runner/assets/626863/7349e1eb-ae0d-4102-8c04-f50f1cae83df">

**Comment by luketomlinson** [comment]
@rbleuse Thanks for bringing this up. I believe this issue is fixed in GHES 3.12+. If that doesn't resolve your issue, I'd recommend going through our support channels. Thanks!

**Comment by OleksandrMakarov-AppsULove** [comment]
@luketomlinson This issues is raised again. Current runner version is 2.319.1
I can remove all labels like prod, android, ios but job still picked up

![Screenshot 2024-09-12 110401](https://github.com/user-attachments/assets/f5db5c51-f139-4d6b-9cf3-cabad54011ea)

**Comment by luketomlinson** [comment]
@OleksandrMakarov-AppsULove Do you have a runner name or any logs so I can look and see what this runner is doing? A runner name or id or session id would be great.

**Comment by luketomlinson** [comment]
Thanks @OleksandrMakarov-AppsULove taking a look

**Comment by luketomlinson** [comment]
@OleksandrMakarov-AppsULove Are you still experiencing this issue?

**Comment by OleksandrMakarov-AppsULove** [comment]
@luketomlinson Today I've tested it and now it works as expected. Thanks

**Comment by PaulKlauser** [comment]
We just added some GitHub-hosted larger-runners and are seeing this issue among them. With the runner label specified in the workflow, we'll see the wrong runner get picked up for the build.

This is on a private enterprise repo, but I'm happy to provide any additional details I can here, or via a private support channel.
