### ISSUE TITLE
config.sh not properly configuring runner all of a sudden

### ISSUE THREAD

**Issue by jcshadhara** [actions/runner#2801]
We have self-hosted runners that were working just fine a three days ago. Suddenly, our usual way to run the configuration steps is no longer working, and runners keep on crashing.

Here is the script we use as entrypoint to the Dockerfile containing the runner binaries and all the dependencies already in place:
```
#! /bin/bash

GITHUB_REPO=${GITHUB_REPO}
GITHUB_PAT=${GITHUB_PAT}
GITHUB_LABELS=${GITHUB_LABELS}

if [[ -z ${GITHUB_PAT} && -z ${GITHUB_REPO} ]]; then
    echo "GITHUB_REPO and GITHUB_PAT env variables are required"
    exit 1
fi

./config.sh --unattended --url ${GITHUB_REPO} --pat ${GITHUB_PAT} --ephemeral --replace ${GITHUB_LABELS:+--labels ${GITHUB_LABELS}}

./run.sh
```
As you can see it's pretty straight-forward.

And this is the error we get from the runner:
```
--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration




A runner exists with the same name
√ Successfully replaced the runner
Message queue listen OAuth token.
An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.
Runner listener exit with terminated error, stop the service, no retry needed.
Exiting runner...
```

Any ideas of what can be happening?

**Comment by fhammerl** [comment]
Thanks for reporting this issue. We're investigating it 👍

**Comment by cbllopez** [comment]
Our runners just stopped working with this error:

[RUNNER 2023-08-28 14:28:52Z ERR  Terminal] WRITE ERROR: An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.
An error occurred: Not configured. Run config.(sh/cmd) to configure the runner.

Running config.sh returns:

[RUNNER 2023-08-28 14:37:44Z ERR  Runner]    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
[RUNNER 2023-08-28 14:37:44Z ERR  Terminal] WRITE ERROR: The SSL connection could not be established, see inner exception.
The SSL connection could not be established, see inner exception.
[RUNNER 2023-08-28 14:37:44Z INFO Listener] Runner execution has finished with return code 1

**Comment by jcshadhara** [comment]
Any updates on this?

**Comment by patricioperezv** [comment]
@fhammerl it seems like for some repos the https://api.github.com/actions/runner-registration endpoint is returning a non-expected url, in our case firewall/proxy doesn't allow connection to that other url (expected: https://pipelines.actions.githubusercontent.com, unexpected: https://pipelinesghubeus5.actions.githubusercontent.com).

According to this doc i would only expect connections to the pipelines.actions.githubusercontent.com url ... https://github.com/actions/runner/blob/main/docs/checks/actions.md

**Comment by TingluoHuang** [comment]
BTH, here is the official doc for URL firewall rules.
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#communication-between-self-hosted-runners-and-github

**Comment by patricioperezv** [comment]
@TingluoHuang oh, interesting, thanks! going to talk with our network folks :)

**Comment by jcshadhara** [comment]
@patricioperezv Highly unlikely, if it was the case, our runners would've failer a long time ago.
This issue started happening overnight. Funnily enough, it still happens, but it's random now. Each runner has a chance of becoming in a kind of "inconsistent" state when the `config.sh` script fails for the first time, and that runner becomes unrecoverable, BUT if you unregister it from Github BEFORE re-creating it, and remove the `--replace` flag from the script paremeters, workers start spinning up as usual again and never crash.

Why has the `--replace` flag suddenly stopped working? ¯\_(ツ)_/¯ The mystery remains unveiled.

**Comment by jcshadhara** [comment]
@fhammerl It's been three weeks now and you guys haven't yet said a word on this regard. Is this already resolved or still under investigation? I'd appretiate if you could give us some updates,.

**Comment by nikola-jokic** [comment]
Hey @jcshadhara, this should be fixed now. Can you please confirm?
