### ISSUE TITLE
Ephemeral runners not deregistered immediately on exit causing subsequent same named registrations to fail

### ISSUE THREAD

**Issue by maskati** [actions/runner#2809]
**Describe the bug**

I am using a set of self-hosted ephemeral runners, which are replaced on completion with subsequent same named instances. According to [using ephemeral runners for autoscaling](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/autoscaling-with-self-hosted-runners#using-ephemeral-runners-for-autoscaling):
> The GitHub Actions service will then automatically de-register the runner after it has processed one job

It seems however that runner deregistration is not "fully complete" at the point of runner exit. When reusing the same runner name for subsequent replacement runners shortly after the previous runner has exited (and presumably deregistered), this results in a runner replacement rather than reregistration. This in turn causes issues in runner startup.

Ephemeral runner instance 1:
```
2023-08-29 07:42:58.356: Running job: xxx
2023-08-29 07:45:36.187: Job xxx completed with result: Succeeded
2023-08-29 07:45:36.393: √ Removed .credentials
2023-08-29 07:45:36.395: √ Removed .runner
2023-08-29 07:45:36.407: Runner listener exit with 0 return code, stop the service, no retry needed.
2023-08-29 07:45:36.408: Exiting runner...
```
Ephemeral runner instance 2 (replacing instance 1 with the same name):
```
2023-08-29 07:46:10.842: √ Connected to GitHub
2023-08-29 07:46:11.274: A runner exists with the same name
2023-08-29 07:46:11.416: √ Successfully replaced the runner
2023-08-29 07:46:11.424: Message queue listen OAuth token.
```

The error [Message queue listen OAuth token](https://github.com/actions/runner/blob/be65955a9d2503060186d1e8d97a87587051161d/src/Runner.Listener/Configuration/ConfigurationManager.cs#L363) seems to cause this second instance to exit with a error return code (1) and runner startup to fail. Ephemeral runner instance 2 logs (_diag/Runner):
```
[2023-08-29 07:46:11Z INFO CommandSettings] Flag 'ephemeral': 'True'
[2023-08-29 07:46:11Z ERR  Runner] System.NotSupportedException: Message queue listen OAuth token.
[2023-08-29 07:46:11Z ERR  Terminal] WRITE ERROR: Message queue listen OAuth token.
[2023-08-29 07:46:11Z INFO Listener] Runner execution has finished with return code 1
at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
```

**Expected behavior**

Ephemeral runners should be completely deregistered at the moment they exit i.e. subsequent runner registration with the same name should not cause same named runner replacement.

Also, in the case of runner replacement, this should probably not result in the error `Message queue listen OAuth token`. I am not entirely sure if this error is related to the runner replacement or some other issue.

## Runner Version and Platform
Runner 2.308.0 on Linux.

**Comment by thboop** [comment]
Hey @maskati , thanks for the report!

We rolled a fix for this yesterday, please let us know if you are still seeing the issue so we can reopen this investigation!

**Comment by maskati** [comment]
@thboop  it seems the `Message queue listen OAuth token` error has resolved (last occurrence 31st August), but has been replaced with a different `SessionConflictException` error (first occurrence 1st September). Example logs:

```
06:31:42.840 √ Connected to GitHub
06:31:43.073 A runner exists with the same name
06:31:43.225 √ Successfully replaced the runner
06:31:45.380 √ Runner connection is good
06:31:45.385 √ Settings Saved.
06:31:47.501 √ Connected to GitHub
06:31:48.246 A session for this runner already exists.
06:31:48.249 Runner connect error: The actions runner xxx already has an active session for owner xxx. Retrying until reconnected.
06:32:19.301 √ Connected to GitHub
06:32:19.407 A session for this runner already exists.
06:32:51.042 √ Connected to GitHub
06:32:51.147 A session for this runner already exists.
06:33:22.457 √ Connected to GitHub
06:33:22.572 A session for this runner already exists.
06:33:53.804 √ Connected to GitHub
06:33:53.907 A session for this runner already exists.
06:34:25.265 √ Connected to GitHub
06:34:25.654 A session for this runner already exists.
06:34:57.197 √ Connected to GitHub
06:34:57.308 A session for this runner already exists.
06:35:28.503 √ Connected to GitHub
06:35:28.609 A session for this runner already exists.
06:35:28.609 Failed to create session. The actions runner xxx already has an active session for owner xxx.
06:35:28.609 Stop retry on SessionConflictException after retried for 240 seconds.
06:35:28.617 Runner listener exit with terminated error, stop the service, no retry needed.
06:35:28.619 Exiting runner...
```
