### ISSUE TITLE
Cannot run the Pipeline

### ISSUE THREAD

**Issue by nipunai7** [actions/runner#2826]
<img width="1602" alt="image" src="https://github.com/actions/runner/assets/10683839/16eba6f4-2cd0-4595-ac52-d5b7e2bb88bb">

I have restarted the machine and runner. Still nothing works.

**Comment by AndreiBondarenko** [comment]
Currently experiencing this as well, no changes to the workflow since it worked last (yesterday).

**Comment by scottquested** [comment]
It's related to this issues #2824 that was closed and "resolved" yesterday

**Comment by skynetigor** [comment]
Also happening for us. Randomly fail our builds with this issue. We had the same yesterday but today it's much worse.

**Comment by bhaveshtolia** [comment]
Happening with us as well since yesterday. It is more frequent today. Re-running the jobs does fix it, but it keeps coming back

**Comment by aramfe** [comment]
We experience the same issue! Need a fix asap!

**Comment by ruvceskistefan** [comment]
Hey all, we had a incident and was a temporary issue. I'll close this one, if you still have problems we will reopen it.
