### ISSUE TITLE
Allow Bypassing of SSL Cert Validation on Self-Hoster Runners

### ISSUE THREAD

**Issue by Kremlin** [actions/runner#286]
**Describe the enhancement**

Allow bypassing SSL certificate validation

**Additional information**

When a proxy server does SSL inspection, it does a sort of "man in the middle" action with certificates, such that the certs for github.com come back as being signed from an internal CA.
Even when using the `--sslskipcertvalidation` flag, it reports:

```
[2020-01-16 15:54:33Z] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
```

**Comment by TingluoHuang** [comment]
The runner doesn't support bypass SSL CA cert validation error. Customer needs to install their self-signed CA certs to certificate store on each platform. 
Linux: OpenSSL store
macOS: keychain
Windows: Windows certificates manager

**Comment by snyder-riley-pfg** [comment]
@Kremlin we were running into the same issues, and following @TingluoHuang by adding our certs to the linux ssl store did not work.

What we found was by setting `SSL_CERT_DIR` to `/etc/ssl/certs` it then trusted our certs and we were able to configure the runner.

**Comment by TingluoHuang** [comment]
@snyder-riley-pfg how did you add your cert to openssl store? i think `SSL_CERT_DIR` is just another way to set trusted certs for openssl, in the end the runner still use openssl for query trusted certs.

**Comment by snyder-riley-pfg** [comment]
@TingluoHuang we used [update-ca-trust](https://www.mankier.com/8/update-ca-trust) to add the certs, then setting that environment variable seemed to tell the service to look where we were adding them. Perhaps before it was looking in `/etc/pki/tls` or another directory which was not where we were adding our certs.

**Comment by H6LS1S** [comment]
export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0

**Comment by clairmont32** [comment]
> @Kremlin we were running into the same issues, and following @TingluoHuang by adding our certs to the linux ssl store did not work.
> 
> What we found was by setting `SSL_CERT_DIR` to `/etc/ssl/certs/` it then trusted our certs and we were able to configure the runner.
> 
> Working on RHEL 7.7

I'm running into this on Ubuntu. Did you simply do `SSL_CERT_DIR=/etc/ssl/certs` within the terminal or within one of the Actions scripts? I tried with export but that didnt work for me.

**Comment by snyder-riley-pfg** [comment]
> > @Kremlin we were running into the same issues, and following @TingluoHuang by adding our certs to the linux ssl store did not work.
> > What we found was by setting `SSL_CERT_DIR` to `/etc/ssl/certs/` it then trusted our certs and we were able to configure the runner.
> > Working on RHEL 7.7
> 
> I'm running into this on Ubuntu. Did you simply do `SSL_CERT_DIR=/etc/ssl/certs` within the terminal or within one of the Actions scripts? I tried with export but that didnt work for me.

We ended up getting network exceptions from our security team to stop doing their MITM cert inspection on our action runner for most things, so not sure how accurate my solution still is.

We were setting these in the actions workflow, for example on a step:

```
SSL_CERT_DIR: /etc/ssl/certs
```

Or for builtin steps that used node:

```
- name: Checkout
    uses: actions/checkout@v2
    env: 
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-bundle.crt
```

Where `/etc/ssl/certs/ca-bundle.crt` is the bundle that has our internal certs.

@deutmeyerbrianpfg has done a lot of work with our self hosted runners in our datacenter, he might be able to comment further.

**Comment by u2mejc** [comment]
I also added my certs by running `update-ca-certificates`, and confirmed successfully the before and after, by testing with `curl`.

The runner still threw an error, until I tried H6LS1S's suggestion:

> export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
🙏

**Comment by pkit** [comment]
I'm not sure why it's closed. `GITHUB_ACTIONS_RUNNER_TLS_NO_VERIFY=1` did not help much.
While `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` **did help** a lot.
In the end it's kinda working only when both `NODE_EXTRA_CA_CERTS` and `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER` are set up in the systemd service environment.
I.e. add it to the `/etc/systemd/system/actions.runner.<your service id>` file as:
```
[Service]
.........
Environment=NODE_EXTRA_CA_CERTS=/etc/ssl/certs/my-custom-ca.pem
Environment=DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0

``` 
Still I see some strange disconnections/handshake errors in websockets that push logs to the action UI.

**Comment by PrabhakaranSeeniraj** [comment]
> export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0

very useful thanks a lot buddy

**Comment by appatalks** [comment]
I've come across a number of request seeking assistance with the ```self-signed``` certificate question. <br>
With this in mind, I've crafted this [bash script](https://github.com/appatalks/gh_shr_cert_update/blob/main/add_certificate.sh) that will look at the runner's installation, extract the appliance hostname and export the SSL to the Runner's OS certificate store and ```.env``` file for ```node_extra_ca_certs```. This is preferred over bypassing verification. I hope others find utility with this.

Warm regards,
--AppaTalks
