### ISSUE TITLE
macOS runners get stuck without error and time out

### ISSUE THREAD

**Issue by matthme** [actions/runner#2874]
**Describe the bug**
In my workflow macOS runners (macos-11 and macos-latest) consistently stop logging and time out after 6 hours without error. It occurred at 2 different steps in the workflow so far. The same workflow runs fine on Windows and Linux.

**To Reproduce**
Run [this](https://github.com/lightningrodlabs/we/actions/runs/6237680749/job/16953790221) job, wait for the runner to stop logging and time out despite there being no error.

**Expected behavior**
Either show an error or continue with the workflow.

## Runner Version and Platform
Happens for both macos-11 and macos-latest runners.

## What's not working?
The runner stops logging despite there being no error and it times out after 6 hours, automatically canceling the job.

## Job Log Output
Here is where it got stuck in one of the cases:
```
> grapes-editor@0.1.0 build
> rimraf dist && rollup -c


src/index.ts → dist...
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
(!) Plugin typescript: @rollup/plugin-typescript: outputToFilesystem option is defaulting to true.
created dist in 24.1s
##[debug]Re-evaluate condition on job cancellation for step: 'Install and prepare'.
Error: The operation was canceled.
```

## Runner and Worker's Diagnostic Logs
[Runner_20230920-072401-utc.log](https://github.com/actions/runner/files/12684888/Runner_20230920-072401-utc.log)
[Worker_20230920-072406-utc.log](https://github.com/actions/runner/files/12684889/Worker_20230920-072406-utc.log)

**Comment by nebuk89** [comment]
jobs can only run on hosted runners up to 6 hours: https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits :)

**Comment by oir** [comment]
I am not sure why this is closed as complete? I don't think the problem is that the jobs time out after 6 hours. The problem is getting stuck for 6 hours in the first place instead of completing in, e.g. 1 hr.

Unless I misunderstand the original post.

**Comment by matthme** [comment]
You understood my post correctly @oir - I am well aware that there is a timeout of 6 hours. The above job should be finished in well below one hour but it just gets stuck and stops logging shortly after starting.
