### ISSUE TITLE
Unable to locate package `google-cloud-sdk`

### ISSUE THREAD

**Issue by khause** [actions/runner#2891]
**Describe the bug**
We're using [free-disk-space](https://github.com/marketplace/actions/free-disk-space-ubuntu) in our workflow and it fails to get `google-cloud-sdk` with the error:
```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package google-cloud-sdk
Error: Process completed with exit code 100.
```

When we rerun the workflow, it passed then on subsequent runs, it will bounce between passing and failling.

Upon further debugging, the only difference we discovered was that the passing runs were executed `Runner Image Version: 20230917.1.0` whereas the failing runs were on `Runner Image Version: 20230924.1.0`.

**To Reproduce**
1. Setup a workflow using [free-disk-space](https://github.com/marketplace/actions/free-disk-space-ubuntu)
2. Run it
3. See error if the image used was `20230924.1.0`

**Expected behavior**
Should **not** fail to locate `google-cloud-sdk`

## Runner Version and Platform
Version of your runner?
`Runner Image Version: 20230924.1.0`

OS of the machine running the runner? OSX/Windows/Linux/...
`Ubuntu 22.04.3 LTS`

## What's not working?
```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package google-cloud-sdk
Error: Process completed with exit code 100.
```

## Job Log Output
N/A

## Runner and Worker's Diagnostic Logs
N/A

**Comment by nikola-jokic** [comment]
Hey @khause,

This issue is related to the machine that executes your workflow and not the runner itself. Can you please submit this problem to the [runner-images repository](https://github.com/actions/runner-images)? :relaxed:

Closing this issue, since we try to keep issues related to the runner itself here.
