### ISSUE TITLE
Unable to use `./config remove --token ...` on a just-in-time runner

### ISSUE THREAD

**Issue by jenseng** [actions/runner#2920]
**Describe the bug**
When an ephemeral runner is launched [with just-in-time registration](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-just-in-time-runners), you can't perform deregistration from the runner itself (say, if you want to automatically tear down idle runners after a period of time).

**To Reproduce**
1. Launch a runner with just-in-time registration, e.g. `./run.sh --jitconfig ${encoded_jit_config}`
2. Before a job is assigned, generate a runner removal token and run `./config remove --token ${runner_removal_token}`
3. See the error

**Expected behavior**
The runner should be removed

## Runner Version and Platform
Version of your runner? 2.310.1

OS of the machine running the runner? Linux

## What's not working?

You get the following output and prompt, followed by an error
```
# Runner removal

How would you like to authenticate? [press Enter for OAuthAccessToken] 

Failed: Removing runner from the server
The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.
```

When launching ephemeral runners with a registration token, they can be removed normally:

```
# Runner removal


√ Runner removed successfully
√ Removed .credentials
√ Removed .runner
```

## Observations and a workaround

I noticed that the `.runner` file is slightly different between JIT vs registration-token runners. Specifically, a JIT runner has no `gitHubUrl` entry. I found that by adding this missing entry, the remove command then works as expected.

So if this entry were automatically persisted during registration, it seems that would fix the bug.

**Comment by jenseng** [comment]
It looks like the runner CLI just [writes](https://github.com/actions/runner/blob/4647f3ed5f650737156e6242d91c5a7cd12cdeb4/src/Runner.Listener/Runner.cs#L211-L225) the `.runner` file (and others) directly from the decoded jitconfig, so it seems that this might need to be fixed in the service that generates the jitconfig.

**Comment by thboop** [comment]
Thanks for the report @jenseng . @rentziass is taking a look!

**Comment by rentziass** [comment]
Thank you so much for the report @jenseng ❤️  I just found the issue: `gitHubUrl` is never provided by our API, it's instead set by the runner itself [during standard configuration](https://github.com/actions/runner/blob/main/src/Runner.Listener/Configuration/ConfigurationManager.cs#L135). Working on a fix to include that URL in the just-in-time configuration our API returns.

**Comment by rentziass** [comment]
@jenseng the fix for this should now be generally available! Thanks again for the report, please feel free to reopen this if you're still having issues!

**Comment by jaswanthikolla** [comment]
I don't think this is fixed. I don't see githubURL in the .runner file
```
{"AgentId":"64634", 
"AgentName":"arss-runner-uber-xyz-runner-abc", 
"DisableUpdate":"True","Ephemeral":"True","PoolId":"4",
"PoolName":null,
"ServerUrl":"https://pipelinesghubeus21.actions.githubusercontent.com/sometoken/",
"RunnerScaleSetId":"11", 
"RunnerScaleSetName":"arss-runner-uber", 
"WorkFolder":"_work"}
```
