### ISSUE TITLE
CRITICAL: Old runner pods get stucked in Terminating state once container in that pod still Running

### ISSUE THREAD

**Issue by odselsevier** [actions/runner#2937]
**Describe the bug**
CI is not working properly, some steps just exiting with code 1. 
CI runner controller always use maximum amount of runners. 
It should use only minimum number of runners always, except all min runners are overwhelmed and controller want to spin more runners

Old runner pods get stucked in Terminating state once container in that pod still Running
`kubectl delete pod` does not work at all, 
pod cannot be deleted, because container in that pod still running(not init container)

**To Reproduce**
1. Run some ci jobs, version of runner is latest - `v2.310.2`, in our case min 6 runners, max 12 runners
2. See that runners can get stuck in terminating state, also they have finalizers that not allowing pods gracefully terminated

To Reproduce from source code with test:
Create pod that have 2 init containers and one not init container that are `runner` container
Resources/mocks that need to reproduce bug:
- those 2 init containers should have `Completed` state 
- `runner` container should have `Running` state
- pod should have `Terminating` state
- pod should have finalizers

```
finalizers:
 - actions.summerwind.dev/runner-pod 
```

**Expected behavior**
Pods not getting stucked for 20 days or so.

Pods in terminating state that have finalizers and runned containers should be gracefully removed via runner controller in source code. We should not stop pods and remove finalizers manually.

## Runner Version and Platform
Orchestrator: Kubernetes 1.28
Container Management: Docker 
Version of your runner? v2.310.2
Debian, Ubuntu 20/22, Amazon Linux2
 
## What's not working?
CI is not working properly, some steps just exiting with code 1. 

## Temporary solution
I removed those pods via cleaning finalizers 

```
$ kubectl get pods --all-namespaces | grep Terminating | awk '{print $2 " --namespace=" $1}' | xargs kubectl patch pod -p '{"metadata":{"finalizers":null}}'

$ kubectl get pods --all-namespaces | grep Terminating | awk '{print $2 " --namespace=" $1}' | xargs kubectl delete pod

```

**Comment by shankarRaman** [comment]
@odselsevier we are also seeing the same issue. However I feel this question should be asked here https://github.com/actions/actions-runner-controller/issues since you are using the ARC to manage your runner pods. Would you like to post it there?

**Comment by ruvceskistefan** [comment]
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
