### ISSUE TITLE
Double-billing when re-running failed jobs

### ISSUE THREAD

**Issue by wheeheee** [actions/runner#2964]
**Describe the bug**
Choosing the option to re-run a single failed job does that, BUT when viewing the usage, the minutes spent on successful jobs are duplicated, exactly. This seems unlikely to be the case if they were actually run because of jitter.
I was also viewing the summary page while it was running, and saw only the failed job being re-run. While I'm not a paying customer, this doesn't look nice for those who are.

**To Reproduce**
1. Push a commit that runs a CI job with at least one failure.
2. On the run page in actions, press the dropdown Re-run jobs, then Re-run failed jobs
3. On completion, open the usage. Note the duplicated run time.

**Expected behavior**
Only the minutes spent on running the failed jobs are listed and added to total runtime.

## Runner Version and Platform
2.311.0 (latest, run on standard GitHub-hosted runners)

OS of the machine running the runner? macOS + Linux

## What's not working?
Correct calculation of minutes, duplicating minutes for non-running, successful jobs when "Re-run failed jobs" is selected.
An example at https://github.com/wheeheee/MFCC.jl/actions/runs/6716402654/usage

## Job Log Output
See the link above

## Runner and Worker's Diagnostic Logs
Not self-hosted.

**Comment by fahmifan** [comment]
I still experience this issue, is it reflected on the actual bill or it just UI bugs?
