### ISSUE TITLE
Piping to file causing CI to hang

### ISSUE THREAD

**Issue by enchorb** [actions/runner#2979]
**Describe the bug**
We have been using `Nx` and outputing the result of commands to a file. This has been working fine for months and that portion of CI hasn't been touched, nor have we updated `Nx`. All of a sudden this code hangs CI until we cancel or it times out

```
# Write To File Is Hanging CI
PHASE=$(npx nx affected --target=${{ matrix.phase }} --configuration=dev --parallel=3) || FAILED=true
echo "$PHASE" | sed "s/[^-a-zA-Z 0-9_~!@#$%^&*()+<>?{}|;,.:\'\"\/\\]//g" > phase.out
 echo "$PHASE"
```

Workaround is removing the pipe, but this removes the comment on our PRs in another step

`npx nx affected --target=${{ matrix.phase }} --configuration=dev --parallel=3 || FAILED=true`

**Expected behavior**
Not hanging

## Runner Version and Platform
GitHub Linux Runner

## Job Log Output
CI just hangs on that step until cancelled or timed out

**Comment by thedtvn** [comment]
same
