### ISSUE TITLE
git is not installed in Ubuntu and Windows Runner images

### ISSUE THREAD

**Issue by devarshgandhi** [actions/runner#3000]
**Describe the bug**
git is not installed in Ubuntu 22.04 runner images.
http://ghcr.io/actions/actions-runner:latest

**To Reproduce**
1. Launch a Runner
2. Check if git is installed or not.
3. [Documentation](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) describes git as installed tool

**Expected behavior**
Git should be installed in windows and Linux runners.

It's not listed in https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231115.7 and our testing is implying that it's not installed. In fact, it seems like only Mac images have Git installed; I don't see them listed for Windows either.

## Runner Version and Platform
Version of your runner?
https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231115.7

OS of the machine running the runner? OSX/Windows/Linux/...
Linux
Windows

## What's not working?
`ls /usr/bin` there is no git and if I `whereis git` , I don't find anything. That said, I was able to sudo apt install git --yes` and that worked, but would be nice to avoid that.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by ruvceskistefan** [comment]
Hey @devarshgandhi, 
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
