### ISSUE TITLE
toJSON method should accept arrays as direct input?

### ISSUE THREAD

**Issue by Levelleor** [actions/runner#3022]
**Describe the bug**

I'm trying to pass an array directly to the `toJSON()` method input:
https://github.com/Levelleor/gha-test/actions/runs/7089900480/workflow#L11

But it rejects the workflow with an error:
>  Invalid workflow file
> The workflow is not valid. .github/workflows/test.yaml (Line: 11, Col: 14): Unexpected symbol: '['. Located at position 8 within expression: toJSON(['one'])

**Expected behavior**
I expected GHA to work properly with array object and let it be used as a input here.

Any reason for this behavior?

![imagen](https://github.com/actions/runner/assets/11915185/31cae1c7-45ea-48ef-a636-fc8d8d112c93)

**Comment by Levelleor** [comment]
It works properly with `toJSON('["one", "two"]')` but why do I have to encapsulate the array object in a string to be able to pass it in the `toJSON` method?

**Comment by ruvceskistefan** [comment]
Hey @Levelleor ,
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
