### ISSUE TITLE
`./bin/installdependencies.sh` is missing dependencies on Linux Arm

### ISSUE THREAD

**Issue by gaebor** [actions/runner#3030]
I set up a self-hosted runner on my raspberry pi (inside a docker). But when I tried to run a checkout action then I get the error: 
```
/home/runner/actions-runner/externals/node20/bin/node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```
see here in action: https://github.com/gaebor/primes/actions/runs/7146730168/job/19465003848#step:2:16

## To reproduce
 * build this self-hosted runner docker image: https://github.com/gaebor/self-hosted-docker-runners/blob/c6baa3473bf5b47e23db0e43362a7e3a31076e86/Dockerfile.ubuntu.arm
   * on a raspberry pi
   * provide the proper build args (token)
 * run the built image
 * make a github action that uses this runner
   * for me: https://github.com/gaebor/primes/blob/d244599a151e48e89e9914f1c7c29a2be95451a0/.github/workflows/test.yaml#L32-L35
 * I got the `libatomic.so.1: cannot open shared object file` error

## Expected behavior
 * runner is able to checkout my repo

## Runner Version and Platform
 * 2.311.0
 * ubuntu 22 docker image on a raspberry pi host

## fix
 * If I install `gcc` additionally in the runner then the checkout action works.
 * Please, add the proper dependencies to `./bin/installdependencies.sh`

**Comment by ruvceskistefan** [comment]
Hey @gaebor, this dependancy problem should be resolved on node level (https://github.com/nodesource/distributions/issues/1687) so I'll close this one and you can transfer your issue there if it's still a problem.

**Comment by gaebor** [comment]
Thanks 🤗
