### ISSUE TITLE
actions/runner docker image is not equivilent to GitHub hosted runner. 

### ISSUE THREAD

**Issue by jgreat** [actions/runner#3080]
**Describe the bug**

I'm following the instructions [here](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller) for deploying self-hosted runners with the gha-runner-scale-set controller. 

The gha-runner-scale-set helm chart uses `ghcr.io/actions/actions-runner:latest` as the runner image.  That image is missing a lot of binaries/packages/utilities that are _expected_ by common GitHub Actions.

Some examples: 

[actions/cache@v3](https://github.com/actions/cache) _strongly prefers_ zstd for compression. Its fails to find cache entries if there is a mismatch of zstd vs non-zstd. 
[actions/checkout@v4](checkout) needs git installed for submodule checkouts.

zstd and git are installed in GitHub hosted runners, but not in the image. I'm sure there are a bunch more things, but these are the first 2 issues I've found. 

**To Reproduce**
Run common github supported `actions/*` on  ghcr.io/actions/actions-runner image. 

**Expected behavior**
GitHub provides a self-hosted runner image for use with GitHub supported gha-runner-scale-sets that is equivalent to GitHub-hosted runners for compatibility. 

## Runner Version and Platform
Version of your runner? ghcr.io/actions/actions-runner:latest - 2.311.0

OS of the machine running the runner? OSX/Windows/Linux/...
Docker image used on kubernetes with gha-runner-scale-sets version 0.8.1

## What's not working?
Please include error messages and screenshots.

## Job Log Output

actions/checkout@v4 failed because git not installed: https://github.com/mobilecoinfoundation/mobilecoin/actions/runs/7414580822/job/20175934729

actions/cache@v3 failed because my build uses an image with zstd, but the runner doesn't have zstd installed. Docker steps failed because cache was not restored in earlier step: https://github.com/mobilecoinfoundation/mobilecoin/actions/runs/7402844013/job/20143066728

## Runner and Worker's Diagnostic Logs
Runners are ephemeral, so that's going to be hard to get.

**Comment by MosJef** [comment]
This is by design. The GitHub hosted runner images can be found here: https://github.com/actions/runner-images These contain all the tooling etc that you expect when using the GitHub hosted runners such as `ubuntu-latest` etc. 

[About ARC - About the runner container image](https://docs.github.com/en/enterprise-server@3.11/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller#about-the-runner-container-image) has some more info:

> This image contains the least amount of packages necessary for the container runtime and the runner binaries. To install additional software, you can create your own runner image. You can use ARC's runner image as a base, or use the corresponding setup actions. For instance, actions/setup-java for Java or actions/setup-node for Node.

This allows much more control around what is contained in the image for those running ARC. ARC users may not want or need _all_ the tooling available in the official images. 

Theres some information on how you can modify the container to match your needs here: [Creating your own runner image](https://docs.github.com/en/enterprise-server@3.11/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller#creating-your-own-runner-image)

**Comment by jgreat** [comment]
Thanks for the https://github.com/actions/runner-images as a reference, but it doesn't have any docker images as release artifacts.

I do understand that those VM images pretty much include everything and the kitchen sink.  And that's probably too much. I don't depend on the runner having the right version of rust, python or whatever for my task.  But the current actions/runner docker image doesn't have enough utilities to run _your_ basic actions.   

I don't think it should be too much to ask that `actions/*` actions, supported by GitHub, should work out of the box. I don't believe that I should have to install `git` to use `actions/checkout` in a simple workflow.

I think the power of GitHub actions over other services is that simple things work and you can leverage community work so you don't have to build the entire system yourself.

Right now I need to build a downstream image off your image, or build my own checkout action to install git.  Either one of those is more pressure on the consumer.

**Comment by mbmcmullen27** [comment]
Ran into this today as well. Would at the very least expect git to be installed by default in the github provided runner, or at least some mention of the fact that I need to make a custom image if I need standard utilities

**Comment by ventsislav-georgiev** [comment]
IMO using custom runner image for self-hosted runners is a must. No amount of predefined tools will be enough for every possible job you can execute. In that sense, having the least amount of utilities is perfect.

It is also mentioned in the docs and the first recommended step is to make a custom image using their as a base image. There are also links to the [Dockerfile of the runner](https://github.com/actions/runner/blob/main/images/Dockerfile) and even its [base image](https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/6.0/bullseye-slim/amd64/Dockerfile). All is plainly visible.

However, I do agree with @mbmcmullen27 that at least having `git` is kind of expected. Using self-hosted runners without checking out code from GitHub is a very niche use-case and one can always create custom image without basing it on the runner image.

**Comment by mbmcmullen27** [comment]
I think it should be more explicit than [this](https://docs.github.com/en/enterprise-server@3.11/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller#about-the-runner-container-image), users coming from the old version of ARC will expect it to have everything the public runners have. I can understand the need for having a bare image available for users to extend and I agree with your sentiment there, but I would considered this a breaking change if you are trying to migrate from an old ARC install. Previously you didn't need to customize the image ahead of time to test this, considering some actions will use git to install

**Comment by alexklibisz** [comment]
+1 these runner images should at least have git installed. I ran into this just now while trying out the new "scale-set" paradigm for ARC. Maybe the original ARC images had too much installed, but git seems like a strange one to omit.

**Comment by gcaracuel** [comment]
> +1 these runner images should at least have git installed. I ran into this just now while trying out the new "scale-set" paradigm for ARC. Maybe the original ARC images had too much installed, but git seems like a strange one to omit.

I faced problems with other packages as-well that many actions uses: unzip & wget

**Comment by wwalther** [comment]
At this point the [Quickstart](https://docs.github.com/en/enterprise-server@3.11/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller#using-runner-scale-sets) needs to be updated to explicitly call out the need to customize the image.

**Comment by NatoBoram** [comment]
As a fun side-note, [`act`](https://github.com/nektos/act) has [60 GB images](https://github.com/catthehacker/docker_images?tab=readme-ov-file#images-available)  to re-implement GitHub's hosted runners.

There's also people who've registered `act` to [act as a runner](https://github.com/ChristopherHX/github-act-runner).

There's real demand for this even if some people may find it "too much".

* https://github.com/nektos/act/issues/706
* https://github.com/cli/cli/issues/3585

**Comment by joshgc** [comment]
I think @wwalther is right as a top-priority issue. The doc can be fixed easily and is far to subtle. I spend far too long to realize GH hides these images on purpose.

**Comment by crohr** [comment]
@jgreat IF you're still looking for a more compatible alternative with official runners, and you are on AWS, I would suggest you look at [RunsOn](https://runs-on.com), which provides [compatible images for AWS](https://github.com/runs-on/runner-images-for-aws).

**Comment by jgreat** [comment]
If others are still running into this issue we're publishing a public image that just pulls in the upstream `ghcr.io/actions/actions-runner` and pulls in a few commonly needed packages. Example scale-set template can be found in the repo README.

Source: https://github.com/mobilecoinofficial/gha-runner
Image: mobilecoin/gha-runner:latest (https://hub.docker.com/r/mobilecoin/gha-runner)

This image is automatically updated with renovate and pretty much stays in lockstep with the upstream image releases.
