### ISSUE TITLE
v2.312.0 regression : nodeJs not packaged correctly anymore

### ISSUE THREAD

**Issue by odoucet** [actions/runner#3094]
**Describe the bug**
self-hosted runner regression on image v2.312.0 that do not package nodeJS anymore

**To Reproduce**
The following workflow :  
```
name: Build
jobs:
  build:
    runs-on: arc-runner
    container: docker.io/docker:git
    steps:
      - uses: actions/checkout@v3
```
leads to following error : 
```
Run actions/checkout@v3
Run '/home/runner/k8s/index.js'
  shell: /home/runner/externals/node16/bin/node ***0***
env: can't execute '/__e/node16/bin/node': No such file or directory
Error: Error: failed to run script step: command terminated with non-zero exit code: exit status 127
Error: Process completed with exit code 1.
Error: Executing the custom container implementation failed. Please contact your self hosted runner administrator.
```

**Expected behavior**
```
Run actions/checkout@v4.1.1
Run '/home/runner/k8s/index.js'
Syncing repository: xxx/xxxxx
Getting Git version info
[...]
```

## Runner Version and Platform
Version of your runner?  ghcr.io/actions/actions-runner:v2.312.0
OS of the machine running the runner? Linux Kubernetes 1.26.11

**Forcing image v2.311.0 makes it work again, so it's definitely a regression in latest image.**

## What's not working?
It seems nodeJS path is not correct anymore in image, and is faling with `actions/checkout@v3` (also with `actions/checkout@v4.1.1`)

## Job Log Output
see up.

## Runner and Worker's Diagnostic Logs
nothing relevant.

**Comment by gmmcal** [comment]
Also having the same problem

**Comment by gmmcal** [comment]
And also confirm that rolling back to 2.311.0 fixes the problem. spot on report @odoucet

**Comment by TingluoHuang** [comment]
I pull down the image and verity the binary is there.

![Image](https://github.com/actions/runner/assets/1750815/442c60cf-bcc6-4c7b-b1ae-a63f49fa42e5)

@nikola-jokic is this a problem with the latest container hook version (0.5.0)?

**Comment by gmmcal** [comment]
any updates on this?

**Comment by TingluoHuang** [comment]
We revert the change and re-publish the image without the updated container hook.
https://github.com/actions/runner/pull/3101

**Comment by gmmcal** [comment]
Ohh so 2.312.0 is stable and healthy?

**Comment by TingluoHuang** [comment]
> Ohh so 2.312.0 is stable and healthy?

It should now.

**Comment by gmmcal** [comment]
nice! will test tomorrow and report back.

**Comment by cgundy** [comment]
Is the container hook version not set to 5.0 in release 2.312.0 anymore? If so, would you be able to update the release notes as well? I am using the 2.312.0 image and was trying to understand why I couldn't see the new kube-scheduler features reflected (part of the 5.0 hook version release).

**Comment by nikola-jokic** [comment]
Hey, the hook has this issue, but [this](https://github.com/actions/runner-container-hooks/pull/130) PR aims to fix it. Hopefully, we will publish a new hook version soon and maybe re-publish the image (cc @fhammerl)

**Comment by odoucet** [comment]
this absolutely does not look like the original error.

Le jeu. 1 févr. 2024 à 15:04, Peter Dudfield ***@***.***> a
écrit :

**Comment by peterdudfield** [comment]
@odoucet should i make a separate issue?
