### ISSUE TITLE
Not able to start the runner as a service

### ISSUE THREAD

**Issue by praveenambati1233** [actions/runner#3104]
**Describe the bug**
Not able to start the Github runner as a service using svc.sh  script.

**To Reproduce**
[azureuser@githubrunner actions-runner]$ sudo ./svc.sh install
Creating launch runner in /etc/systemd/system/actions.runner.ambati-org.githubrunner.service
Run as user: azureuser
Run as uid: 1000
gid: 1000
Relabeled /etc/systemd/system/actions.runner.ambati-org.githubrunner.service from unconfined_u:object_r:user_home_t:s0 to unconfined_u:object_r:systemd_unit_file_t:s0
Created symlink /etc/systemd/system/multi-user.target.wants/actions.runner.ambati-org.githubrunner.service → /etc/systemd/system/actions.runner.ambati-org.githubrunner.service.
[azureuser@githubrunner actions-runner]$ sudo ./svc.sh start

/etc/systemd/system/actions.runner.ambati-org.githubrunner.service
● actions.runner.ambati-org.githubrunner.service - GitHub Actions Runner (ambati-org.githubrunner)
   Loaded: loaded (/etc/systemd/system/actions.runner.ambati-org.githubrunner.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2024-01-23 10:03:13 UTC; 10ms ago
  Process: 8114 ExecStart=/home/azureuser/actions-runner/runsvc.sh (code=exited, status=203/EXEC)
 Main PID: 8114 (code=exited, status=203/EXEC)

Jan 23 10:03:13 githubrunner systemd[1]: Started GitHub Actions Runner (ambati-org.githubrunner).
Jan 23 10:03:13 githubrunner systemd[1]: actions.runner.ambati-org.githubrunner.service: Main process exited, code=exited, status=203/EXEC
Jan 23 10:03:13 githubrunner systemd[1]: actions.runner.ambati-org.githubrunner.service: Failed with result 'exit-code'.

**Expected behavior**
To start the runner service 

## Runner Version and Platform
Version of your runner? latest

OS of the machine running the runner? Linux

**Comment by praveenambati1233** [comment]
This issue is fixed after running the command   chcon system_u:object_r:usr_t:s0 runsvc.sh

**Comment by marcusbetts** [comment]
> This issue is fixed after running the command chcon system_u:object_r:usr_t:s0 runsvc.sh

This helped me and resolved the same issue for me
