### ISSUE TITLE
breaking change from 2.311.0 to 2.312.0: js

### ISSUE THREAD

**Issue by peterdudfield** [actions/runner#3127]
**Describe the bug**
My github actions worked in [2.311.0](https://github.com/openclimatefix/contributors/actions/runs/7649672430) but did not work in [2.312.0](https://github.com/openclimatefix/contributors/actions/runs/7751194859/job/21138670762). I'm not totally clear whats going on here, but i thought someone on here might.

Thank you in advance if anyone can help

**Expected behavior**

## Runner Version and Platform
0.312.0

OS of the machine running the runner? Linux - ubunutu   22.04.3

## What's not working?
First bit of js code doesnt seem to work

## Job Log Output
see links above

## Runner and Worker's Diagnostic Logs
See links above

**Comment by TingluoHuang** [comment]
Some one checked in a invalid file at https://github.com/openclimatefix/quartz-status/blob/master/.all-contributorsrc, and that cause the Actions to error out.
I forked the code and this is where it blows up:
```
{"projectName":"quartz-status","projectOwner":"openclimatefix"}
TEST............
undefined
/workspaces/merge-all-contributors/dist/index.js:29801
                for (contributor of contributorFile.contributors) {
                                                    ^

TypeError: contributorFile.contributors is not iterable
    at /workspaces/merge-all-contributors/dist/index.js:29801:53
    at Array.reduce (<anonymous>)
    at /workspaces/merge-all-contributors/dist/index.js:29796:57
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by peterdudfield** [comment]
Thank you
