### ISSUE TITLE
Add ability to opt out of running workflows for pull requests

### ISSUE THREAD

**Issue by zhangyoufu** [actions/runner#313]
**Describe the enhancement**

Add ability to opt out of running workflows for pull requests.

**Additional information**

According to [the document](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories):
> Forks of your public repository can potentially run dangerous code on your self-hosted runner machine by creating a pull request that executes the code in a workflow.

AFAIK, there is no way to disable pull requests on GitHub. So public repositories cannot make use of self-hosted runners if the owner cares about security.

**Comment by bryanmacfarlane** [comment]
This isn't a runner feature.  It's a service feature.  Please request on github community
