### ISSUE TITLE
Rerun of Action does not pick up new PR label

### ISSUE THREAD

**Issue by Souheil-Yazji** [actions/runner#3149]
**Describe the bug**
We have a Github action which uses a label on PRs to determine whether or not to push an image to an image reg. [Here is the particular line](https://github.com/StatCan/aaw-kubeflow-containers/blob/master/.github/workflows/build_push.yaml#L87). We can see that this conditional statement checks the label, and it does indeed work if a new commit is applied to the PR, or if the PR is created with the label pre-appended. 

[Here is an example PR where I experience this scenario.](https://github.com/StatCan/aaw-kubeflow-containers/pull/590) 
[Here is the associated workflows.](https://github.com/StatCan/aaw-kubeflow-containers/actions/runs/7849191356/job/21460921420) 

You can see that there's 3 different runs, the original ran without the label. I cancelled the workflow because I want the container image to push to remote. I applied the `auto-deploy` label to the PR then re-ran the workflow and the boolean expression evaluated to false. Logs bellow.

**To Reproduce**
1. create a workflow which evaluates a conditional statement based on PR labels
2. run workflow without the label
3. add label
4. rerun workflow without creating a new commit
5. conditional statement will not evaluate to a new value and the label will not be picked up by the runner
6. create a new arbitrary commit to force the runner to pick up the new label

**Expected behavior**
I would expect that if I added the label, then simply re-ran my workflow, the runner would pick up the new label on the PR, but that's not the case. 

## Runner Version and Platform
2.312.0

OS of the machine running the runner? ubuntu-latest

## What's not working?
See description, if more details are required please ask.

## Job Log Output
See [full logs](https://github.com/StatCan/aaw-kubeflow-containers/actions/runs/7849191356/job/21460921420#step:3:2): 
```
##[debug]Evaluating: (success() && (github.event_name == 'pull_request') && contains(github.event.pull_request.labels[*].name, 'auto-deploy'))
...
##[debug]Expanded: (true && ('pull_request' == 'pull_request') && contains(Array, 'auto-deploy'))
##[debug]Result: false
```

## Runner and Worker's Diagnostic Logs
If required, please ask.

**Comment by banhpete** [comment]
Hey @Souheil-Yazji, ran into the same issue.

Found this thread and figured you might be interested in it too

https://github.com/orgs/community/discussions/39062

**Comment by ruvceskistefan** [comment]
Hey all, 

Since this is resolved in thread mentioned above I'll close this one. 😄
