### ISSUE TITLE
remove temporary fix

### ISSUE THREAD

**Issue by bryanmacfarlane** [actions/runner#315]
Can we remove this yet?

**Comment by thboop** [comment]
I have a pr available to merge once the issue is resolved #316

**Comment by bryanmacfarlane** [comment]
What is the virtual environments bug number that we're waiting on?

**Comment by TingluoHuang** [comment]
https://github.com/actions/virtual-environments/issues/263

**Comment by TingluoHuang** [comment]
another way to fix this is to add git/bin to path in dev.cmd

**Comment by thboop** [comment]
> another way to fix this is to add git/bin to path in dev.cmd

That might just make sense to do to help with contributing, I'll go ahead and make that change.
