### ISSUE TITLE
core.exportVariable does not set variable LD_LIBRARY_PATH value on MacOS

### ISSUE THREAD

**Issue by SeyfSV** [actions/runner#317]
**Describe the bug**
core.exportVariable does not set variable with underscores (ex. LD_LIBRARY_PATH) on macos-latest runner.
It works good on ubuntu-latest and windows-latest.
Not all variables with underscores can't be set, for example with varible ENV_VARIABLE issue does not occur.

**To Reproduce**
Create action and call core.exportVariable('LD_LIBRARY_PATH', 'test').
Run Actions within macos-latest  runner

**Expected behavior**
LD_LIBRARY_PATH is set

_modified according to [note](https://github.com/actions/toolkit/issues/323#issuecomment-579437440)_

**Comment by thboop** [comment]
May be related to how we set up the .env file: https://github.com/actions/runner/blob/6c70d53eead402ba5d53676d6ed649a04e219c9b/src/Misc/layoutroot/env.sh#L12

**Comment by SeyfSV** [comment]
I do not think so, because `DYLD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH_A` variables have same behaviour:
![image](https://user-images.githubusercontent.com/25712100/73779886-83cee280-479e-11ea-8676-b7b1e9a8411a.png)

**Comment by TingluoHuang** [comment]
might related to https://apple.stackexchange.com/questions/278385/environment-var-ld-library-path-weirdly-hidden-under-bash-on-mac?noredirect=1&lq=1

**Comment by TingluoHuang** [comment]
I am going to close this issue since it looks like a limitation of macOS. ☝️apple doc above
Feel free to reopen it if you think anything we can help.
