### ISSUE TITLE
Runner storage issue

### ISSUE THREAD

**Issue by holashchand** [actions/runner#3184]
**Describe the bug**
The runner builds getting failed for us with error "no space left on device".

The jobs we are doing in the runner -
The build job which builds some `docker images` and do end to end api tests

> I'm not sure what was the VM storage structure before 27th Feb 24 date, Earlier we were able to build images for size more than 25GB. Now we reduced them to around 8GB and still the storage is getting full.

#### My questions are -

1. What are the changes regarding the storage?
2. How should we run our tests now to not face storage full? and utilise the storage well?

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Current runner version: '2.313.0'
Runner Image
  Image: ubuntu-22.04
  Version: 20240225.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240225.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22/20240225.1

Last working build runner -
Current runner version: '2.313.0'
Operating System
Runner Image
  Image: ubuntu-22.04
  Version: 20240218.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240218.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22/20240218.1
Runner Image Provisioner
  2.0.341.1

## What's not working?
Storage getting full
```
Pulling clickhouse (clickhouse/clickhouse-server:23.4.2.11-alpine)...
23.4.2.11-alpine: Pulling from clickhouse/clickhouse-server
failed to register layer: write /usr/bin/clickhouse-odbc-bridge: no space left on device
make: *** [Makefile:48: test] Error 1
```

##### Before running anything
```
Run df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   55G   18G  76% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001

Run docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          14        0         3.122GB   3.122GB (100%)
Containers      0         0         0B        0B
Local Volumes   0         0         0B        0B
Build Cache     0         0         0B        0B
```
##### Before failing with error - no space left on the ...
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   71G  2.5G  97% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001

Run docker system df
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Images          23        0         8.453GB   8.453GB (100%)
Containers      0         0         0B        0B
Local Volumes   0         0         0B        0B
Build Cache     119       0         4.236GB   4.236GB
```

As it can be seen from the above logs that storage device `/dev/sdb1` is not being utilised at all. How should we run or configure runner to utilise that as well?
Or even is this the correct platform for this issue :)

Thanks for your response in advance

**Comment by chrisgacsal** [comment]
We are hitting the exact same issue:

**Comment by lhotari** [comment]
To address diskspace issues with Docker in GitHub Actions, it's possible to configure docker in the Runner VM to use `/mnt/docker` as the data directory. Here's an example in apache/pulsar:
https://github.com/apache/pulsar/blob/2ba02e2002661121f24130c1bf6018e290a8699f/.github/actions/clean-disk/action.yml#L51-L55
