### ISSUE TITLE
self-hosted runner fails to start as a service on Rocky 9

### ISSUE THREAD

**Issue by nycalex** [actions/runner#3186]
**Describe the bug**
I have a self-hosted runner that fails to start as a service on Rocky linux 9. Same sequence of steps works on Debian.

**To Reproduce**
1. create local user 'tester': sudo adduser tester
2. become this user.   sudo su - tester
3. create directory.  mkdir actions-runner && cd actions-runner
4. download and unpack as user 'tester'
5. install under user tester    ./config.sh --url https://github.com/user/repo --token xxxxxxxx
6. if i start the service by hand via ./runsvc.sh under user tester - it runs and registers to github.
7. exit to root
8. go to the directory cd /home/tester/actions-runner/
9. create the service       ./svc.sh install tester
10. this is where it fails:    ./svc.sh start

**Expected behavior**
service should start and stay up

## Runner Version and Platform
2.314.1 and 2.313

OS of the machine running the runner? OSX/Windows/Linux/...
Rocky9

## What's not working?

root@servername actions-runner]# ./svc.sh status

/etc/systemd/system/actions.runner.repo.servername.service
× actions.runner.repo.servername.service - GitHub Actions Runner (repo.servername)
     Loaded: loaded (/etc/systemd/system/actions.runner.repo.servername.service; enabled; preset: disabled)
     Active: **failed** (Result: exit-code) since Tue 2024-03-05 19:25:38 UTC; 30s ago
   Duration: 26ms
    Process: 6373 ExecStart=/home/tester/actions-runner/runsvc.sh (code=exited, status=203/EXEC)
   Main PID: 6373 (code=exited, status=203/EXEC)
        CPU: 22ms

Mar 05 19:25:38 servername.fqdn systemd[1]: Started GitHub Actions Runner (repo.servername).
Mar 05 19:25:38 servername.fqdn systemd[6373]: actions.runner.repo.servername.service: Failed to locate executable /home/tester/actions-runner/runsvc.sh: Permission denied
Mar 05 19:25:38 servername.fqdn systemd[6373]: actions.runner.repo.servername.service: Failed at step EXEC spawning /home/tester/actions-runner/runsvc.sh: Permission denied
Mar 05 19:25:38 servername.fqdn systemd[1]: actions.runner.repo.servername.service: Main process exited, code=exited, status=203/EXEC
Mar 05 19:25:38 servername.fqdn systemd[1]: actions.runner.repo.servername.service: Failed with result 'exit-code'.
[root@servername actions-runner]# 

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by EdgeSync** [comment]
Just adding to this, we are facing the same issue on RHEL9.3 using a self hosted runner version 2.304.0

The workaround the solves it for us is to include /bin/bash at the start of the ExecStart command e.g.

`ExecStart=/bin/bash /home/myuser/actions-runner/runsvc.sh`

**Comment by nycalex** [comment]
i can confirm that it worked. @EdgeSync  thanks for the workaround.

**Comment by hluengas** [comment]
I think this is an issue with SELinux 

Runnig 
```
sudo chcon system_u:object_r:usr_t:s0 ./svc.sh
sudo chcon system_u:object_r:usr_t:s0 ./runsvc.sh
```

fixes it on Fedora 39

you can also add these lines to the `create-latest-svc.sh` script at the end like so:
```
#---------------------------------------
# Configuring as a service
#---------------------------------------
echo
echo "Configuring as a service ..."
prefix=""
if [ "${runner_plat}" == "linux" ]; then
    prefix="sudo "
fi

${prefix} chcon system_u:object_r:usr_t:s0 ./svc.sh
${prefix}./svc.sh install ${svc_user}
${prefix} chcon system_u:object_r:usr_t:s0 ./runsvc.sh
${prefix}./svc.sh start
```

**Comment by ruvceskistefan** [comment]
Hi All, here you can find [Supported architectures and operating systems for self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#linux)

**Comment by hluengas** [comment]
RHEL, CentOS, and Fedora are all listed as supported. There is no mention of SELinux not being supported. Why was this closed?

**Comment by simonkeng** [comment]
I'm also seeing this on Rocky Linux 8.9:

```
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
```

with the GitHub Actions self-hosted runner `2.315.0` (`https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-linux-x64-2.315.0.tar.gz`). 

When `sudo ./svc.sh start` is ran:

```bash
● actions.runner.blahblahblah.service - GitHub Actions Runner (blahblahblah.blahblah.service)
   Loaded: loaded (/etc/systemd/system/actions.runner.blahblahblah.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2024-04-09 18:31:59 UTC; 10ms ago
  Process: 262289 ExecStart=/scr/actions-runner/runsvc.sh (code=exited, status=203/EXEC)
 Main PID: 262289 (code=exited, status=203/EXEC)
```

but following @EdgeSync suggestion to append `/bin/bash` to `ExecStart` in the symlinked service file, will fix the issue. 

From the link @ruvceskistefan shared... Is Rocky 8/9 not a supported platform? I kind of assumed CentOS and RHEL support would imply Rocky support... 🤔

**Comment by pythoninthegrass** [comment]
> sudo chcon system_u:object_r:usr_t:s0 ./svc.sh
> sudo chcon system_u:object_r:usr_t:s0 ./runsvc.sh

Solved it for me on Asahi (Fedora 39). Thanks @hluengas!

**Comment by warrenson** [comment]
Can confirm this issue on RHEL9.3 with runner version 2.317.0.

The workaround (https://github.com/actions/runner/issues/3186#issuecomment-1983516807) from @EdgeSync works for me.

The SElinux context fix does not, however my runner is installed on an NFS mount, giving the `runsvc.sh` script a different context `system_u:object_r:nfs_t:s0`.

**Comment by vorburger** [comment]
This is also required on a Fedora 40 Server VM.

Ideally, `svc.sh install` should check for SElinux, and if present, do that by itself.

**Comment by enriquecs-ss** [comment]
> Just adding to this, we are facing the same issue on RHEL9.3 using a self hosted runner version 2.304.0
> 
> The workaround we've been using is to modify the systemd service file that is created (/etc/systemd/system/actions.runner.<...>.service) and include /bin/bash at the start of the ExecStart command e.g.
> 
> `ExecStart=/bin/bash /home/myuser/actions-runner/runsvc.sh`

You are my hero ❤️❤️
