### ISSUE TITLE
Step summaries shown in reverse order

### ISSUE THREAD

**Issue by maskati** [actions/runner#3188]
**Describe the bug**
Step summaries are shown on the action run summary page in reverse order. Probably related to #3174.

**To Reproduce**
```
steps:
- run: |
    echo "### Step: 1" >> $GITHUB_STEP_SUMMARY
- run: |
    echo "### Step: 2" >> $GITHUB_STEP_SUMMARY
- run: |
    echo "### Step: 3" >> $GITHUB_STEP_SUMMARY
```

Summary page:
![image](https://github.com/actions/runner/assets/21118898/329fa64f-fae6-4083-a0ec-a01c95c06931)

**Expected behavior**
Step summaries are shown in the order 1, 2, 3.

## Runner Version and Platform
`ubuntu-22.04` version `2.314.1`.

**Comment by thboop** [comment]
Hey @maskati thanks for the report, our team is taking a look and will follow up on this issue

**Comment by SrRyan** [comment]
Hi @maskati this should be fixed now. Thanks for letting us know.

**Comment by thboop** [comment]
Going to close this out but if you see this again please let us know @maskati !
