### ISSUE TITLE
linux runner segfaults binaries with asan (ubuntu-22.04 20240310.1.0)

### ISSUE THREAD

**Issue by zoff99** [actions/runner#3207]
**Describe the bug**

this image works:
https://github.com/actions/runner-images/blob/ubuntu22/20240304.1/images/ubuntu/Ubuntu2204-Readme.md

https://github.com/zoff99/asan_b0rken/actions/runs/8270309634/job/22627532071

-----------------

this has the segfault:
https://github.com/actions/runner-images/blob/ubuntu22/20240310.1/images/ubuntu/Ubuntu2204-Readme.md

https://github.com/zoff99/asan_b0rken/actions/runs/8292857655/job/22694866014

**To Reproduce**
compile a dummy C program:

```
#include <stdio.h>
int main()
{
 printf("xxxx\n");
 return 0;
}
```

```
clang-14 -O0 -g a.c  -fsanitize=address   -fsanitize-recover=address -o b
./b;./b;./b;./b;./b;./b;./b;./b;./b;./b
```

it segfaults every couple of runs.

**Expected behavior**
should not segfault

## Runner Version and Platform
Version of your runner?
ubuntu-22.04 20240310.1 -> broken
ubuntu-22.04 20240304.1 -> still works

**Comment by sreimers** [comment]
This workaround fixes the problem:

```yml
    - name: mmap rnd_bits workaround
      run: |
        sudo sysctl -w vm.mmap_rnd_bits=28
```

**Comment by zoff99** [comment]
thank. you da man. where did you find the fix?
this also fixes it on my local linux box. i don't even need to recompile. the same binary works after this

**Comment by zoff99** [comment]
https://github.com/google/sanitizers/issues/1614

**Comment by zoff99** [comment]
https://github.com/luau-lang/luau/commit/d2ed2150ca4c6dc84e77cbae930f6233354d9961

**Comment by phil-blain** [comment]
This here project is for the runner; the project for the GitHub actions images is https://github.com/actions/runner-images/.

This was reported in https://github.com/actions/runner-images/issues/9491 and fixed in https://github.com/actions/runner-images/pull/9513.
