### ISSUE TITLE
add timing output at group level

### ISSUE THREAD

**Issue by adrian-gierakowski** [actions/runner#321]
NOTE: I am not 100% is this issue belongs in this repo but I couldn't find one which seemed more appropriate.

**Describe the enhancement**
Currently the UI for github actions shows the time which it took to complete the entire **step**. I believe it would be useful to show the time at the **group** level as well (the groups which are created with `core.startGroup()/endGroup()` from the [actions toolkit](https://github.com/actions/toolkit). This would help with diagnosing which group in a long running step takes the longest to complete.

<img width="749" alt="Screenshot 2020-02-06 at 16 08 09" src="https://user-images.githubusercontent.com/330177/73956290-a37c1d00-48fc-11ea-9ff6-24e67e2045e5.png">

**Code Snippet**

**Additional information**

**Comment by TingluoHuang** [comment]
@yaananth @andymckay for ideas.
The `::group::/::end-group::` is just a UI trick, maybe the UI can calculate the time difference?

**Comment by andymckay** [comment]
Just to note that you can also click on `Show Timestamps` and see the difference between the steps. Here's a very bad example:

![Screen Shot 2020-02-25 at 10 35 57 AM](https://user-images.githubusercontent.com/74699/75276235-a3b05f80-57ba-11ea-9499-c0c467e1cc31.png)

Agreed, it might be nice to have that time on the right though. Thanks for that feedback 🙇

**Comment by adrian-gierakowski** [comment]
thanks @andymckay
The timestamps are definitely useful!

**Comment by andymckay** [comment]
I've filed the feedback internally, thank you once again.
