### ISSUE TITLE
macos-latest-xlarge suddenly missing distutils

### ISSUE THREAD

**Issue by nkallen** [actions/runner#3231]
**Describe the bug**

distutils is used by node-gyp . It was previously installed on macOS-latest-xlarge but is suddenly missing. 

I tried both 

                  sudo -H pip install setuptools
and 

                  pip install setuptools 

but I continue to get errors like

Traceback (most recent call last):
91
  File \"/Users/runner/hostedtoolcache/node/17.5.0/arm64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py\", line 42, in <module>
92
    import gyp  # noqa: E402
93
    ^^^^^^^^^^
94
  File \"/Users/runner/hostedtoolcache/node/17.5.0/arm64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py\", line 9, in <module>
95
    import gyp.input
96
  File \"/Users/runner/hostedtoolcache/node/17.5.0/arm64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py\", line 19, in <module>
97
    from distutils.version import StrictVersion
98
ModuleNotFoundError: No module named 'distutils'
99

**Comment by nebuk89** [comment]
Hey, could you open runner image issues in https://github.com/actions/runner-images/ please (if this is still an issue)!

Thanks
