### ISSUE TITLE
runner remove token

### ISSUE THREAD

**Issue by sozercan** [actions/runner#3238]
**Describe the bug**
My self-hosted runner expired due to inactivity.

```
Failed to create a session. The runner registration has been deleted from the server, please re-configure. Runner registrations are automatically deleted for runners that have not connected to the service recently.
```

So I went about reconfiguring:
```
./config.sh --url ...
Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.
```

Ok I guess I have to remove first
```
./config.sh remove
Enter runner remove token:
```

I have no idea what a remove token is, nor is it explained in the `Add new self-hosted runner` UI.

I just removed the entire `actions-runner` directory and redownloaded again to resolve this.

It would be user-friendly if there was a way to remove the relevant config without a token.

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by cegekaJG** [comment]
You're supposed to get the removal token from the Runner settings on GitHub.
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/removing-self-hosted-runners

**Comment by zvkemp** [comment]
Maybe you're "supposed" to get the token from there, but they are removed when the runner expires after a scant 14 days. Why is the token even necessary if Github no longer recognizes the runner?

**Comment by cegekaJG** [comment]
> Maybe you're "supposed" to get the token from there, but they are removed when the runner expires after a scant 14 days. Why is the token even necessary if Github no longer recognizes the runner?

I've had the same problem and GitHub support advised me to delete the folder containing the runner and reinstalling it. This worked for me, so the token seems only necessary if you want to remove the runner registration from GitHub without waiting for it to expire.

**Comment by gainadenis** [comment]
For anyone else who ends up here: 
You can remove the `.runner` file and then execute `./config.sh remove`. After that your runner can be registered again with a new token.

**Comment by devbird007** [comment]
@gainadenis Thank you.

**Comment by Wiesler** [comment]
Noticed after removing the .runner and then pressing the ... to remove the runner on Github it shows the ./config.sh remove with token command.

**Comment by paoloose** [comment]
If none of that worked, for me it was easier to just remove the actions-runner directory and download the content again

**Comment by olivierodo** [comment]
> For anyone else who ends up here: You can remove the `.runner` file and then execute `./config.sh remove`. After that your runner can be registered again with a new token.

This works but i also add to delete`rm .runner_migrated`

**Comment by bosterho** [comment]
I removed the actions-runner directory and downloaded again, but it still says "Cannot configure the runner because it is already configured"
It doesn't show up in the repo on Github, at Settings -> Actions -> Runners
