### ISSUE TITLE
Builds requesting runs-on `macos-14` and getting `macos-14-arm64`

### ISSUE THREAD

**Issue by leighmcculloch** [actions/runner#3256]
**Describe the bug**

Builds requesting runs-on `macos-14` and getting `macos-14-arm64`.

**To Reproduce**
1. Run a job that requests `macos-14` or `macos-latest`

**Expected behavior**
That the workflow will run macos x86_64.

## Runner Version and Platform
Version of your runner? `20240415.6`

OS of the machine running the runner? `macOS`

## What's not working?
<img width="607" alt="Screenshot 2024-04-24 at 9 28 59 pm" src="https://github.com/actions/runner/assets/351529/7e261384-44a2-42d9-abfb-2f54c2ff114c">

Ref: https://github.com/stellar/binaries/actions/runs/8815749910/job/24198334002?pr=20

**Comment by koffie** [comment]
We actually have the same problem with macos-latest

**Comment by sobolk** [comment]
We seem to be running into problems here https://github.com/aws-amplify/amplify-backend/actions/runs/8852791618/job/24312497620 .

The summary is that:
1. A job installs dependencies on `macos-latest` which now resolves to ARM64. Some dependencies come with arch dependent binaries (we're on NodeJS). This job caches result of installation.
2. Another job runs on `macos-latest-xl` which still resolves to OSX14 and runs on Intel. It restores previously cached artifacts that came from ARM64 worker. Which leads to runtime failures.

When is `macos-latest-xl` planned to match `macos-latest` with respect to architecture and OSX version?

**Comment by pvdrz** [comment]
Same issue here: https://github.com/rust-lang/rust-bindgen/actions/runs/8807570984/job/24315825391

`macos-latest` is running on an `arm` machine.

**Comment by leighmcculloch** [comment]
According to this post by GitHub in January the `macos-14` runner is exclusively arm64:
- https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
