### ISSUE TITLE
Rustup missing on macOS-14-ARM runners

### ISSUE THREAD

**Issue by SpikeHD** [actions/runner#3257]
**Describe the bug**
The `rustup` utility, described as available in macOS 14 runners (and which is available in previous runners) [here](https://github.com/actions/runner-images/blob/macos-14-arm64/20240422.3/images/macos/macos-14-arm64-Readme.md#rust-tools), is not present.

**To Reproduce**
1. Create job with `runs-on: macos-14-arm` or `runs-on: macos-latest`
2. Have the job use a `rustup` command (such as `rustup target add x86_64-apple-darwin`)
3. Job will fail with `rustup: command not found`

**Expected behavior**
`rustup` is available and works as expected.

## Runner Version and Platform
Version of your runner?
**20240422.3**

OS of the machine running the runner?
**macOS 14**

## What's not working?

| Failing job (macOS-14-ARM) | Succeeding job (macOS-13) |
|-|-|
| ![image](https://github.com/actions/runner/assets/25207995/ce47a478-6ee6-4549-b4d5-d3f2cb155855) | ![image](https://github.com/actions/runner/assets/25207995/baca8271-a4db-4376-9933-339de942edad) |

## Job Log Output

```
> Run rustup target add x86_64-apple-darwin
  rustup target add x86_64-apple-darwin
  shell: /bin/bash -e {0}
/Users/runner/work/_temp/31cbddd0-8ace-4fa0-ac09-9cd3620e06a9.sh: line 1: rustup: command not found
Error: Process completed with exit code 127.
```

**Comment by nebuk89** [comment]
Please add to https://github.com/actions/runner-images/ if still an issue :)
