### ISSUE TITLE
Unwanted extra runner waiting forever

### ISSUE THREAD

**Issue by JasonGrace2282** [actions/runner#3260]
**Describe the bug**
When changing from `macos-latest` image to `macos-13` an extra runner appears that should not have been created

**To Reproduce**
See this pr: <https://github.com/ManimCommunity/manim/pull/3729>

**Expected behavior**
The extra ci run should not be created

## Runner Platform
Macos-latest

**Comment by behackl** [comment]
The runner likely shows up in the list because it is configured to be required; might not actually be a bug.
