### ISSUE TITLE
hashFiles has begun failing in the past day or so

### ISSUE THREAD

**Issue by alex** [actions/runner#3267]
**Describe the bug**

Beginning approximately a day ago, my job (which had previously been working without incident) began failing with:

```
Error: The template is not valid. .github/workflows/ci.yml (Line: 171, Col: 16): hashFiles('**/Cargo.lock') failed. Fail to hash files under directory '/runner/_work/bcrypt/bcrypt'
```

in the "Post Run actions/cache@v4.0.2" step.

**To Reproduce**

1. See https://github.com/pyca/bcrypt/actions/runs/8888884331/job/24420464244?pr=783
2. Re-running the job consistently reproduces it.

https://github.com/pyca/bcrypt/pull/783 is the underlying PR, which can not plausibly cause this. All action versions are pinned.

**Expected behavior**
It continues working.

## Runner Version and Platform
Version of your runner? 2.316.0

OS of the machine running the runner? Linux

**Comment by wesleyhaws** [comment]
Experiencing the same thing. I might be nice to include what you did to fix this.

**Comment by alex** [comment]
No memory, sorry. You might be able to find it in the commit log for that repo.
