### ISSUE TITLE
Support Docker Actions with dockerfile named with lowercase

### ISSUE THREAD

**Issue by jthegedus** [actions/runner#327]
**Describe the enhancement**
I get the following error when using a **lowercased** filename for my **dockerfile** in my Dockerfile-based Action:

```
##[error]File not found: '/home/runner/work/github-action-awesome-lint/github-action-awesome-lint/./Dockerfile'
```

I would expect the file `dockerfile` to be picked up for the Build in addition to `Dockerfile`.

Renaming the file with Title case worked as expected.

**Comment by TingluoHuang** [comment]
@jthegedus where do you use `dockerfile`, in the `action.yml`?

**Comment by jthegedus** [comment]
That would have been my error 🙃 Sorry for wasting your time. Hopefully in future people will see this via Google search instead of making the same mistake I did.
