### ISSUE TITLE
My Github Actions stuck in Queued status

### ISSUE THREAD

**Issue by Mryan2005** [actions/runner#3300]
## Description
My Github Actions stuck in Queued status. It was working 13 minutes but I can't cancel it.

Area for Triage:

## Question, Bug, or Feature?
Bug

## Virtual environments affected
Image: ubuntu-22.04
Version: 20240516.1.0
runner version: 2.316.1

## Expected behavior
Actions should start running jobs which builds and pushes builds.

## Actual behavior
Github Actions stuck in Queued status. 13 minutes but I can't cancel it.

## Repro steps

Commit code to repo branch
Actions gets triggered
Job stuck in Queued

**Comment by kCzainskiBCFSoftware** [comment]
There seems to be some issue with actions, check: https://www.githubstatus.com/

**Comment by Mryan2005** [comment]
So, Action is Degraded, and It make my action stuck in Queued status @kCzainskiBCFSoftware

**Comment by dima1034** [comment]
+1

**Comment by NurlanMirovich** [comment]
+1

**Comment by NurlanMirovich** [comment]
+1

**Comment by eylongit12** [comment]
Same

**Comment by Mryan2005** [comment]
ok, I see.

**Comment by lushuan** [comment]
+1

**Comment by Mryan2005** [comment]
> same question,i solved it by recreated repository

so cool
