### ISSUE TITLE
2.317.0 Linux x64 download URL fails

### ISSUE THREAD

**Issue by joshtrutwin** [actions/runner#3312]
**Describe the bug**

From the 2.317.0 tag release page: https://github.com/actions/runner/releases/tag/v2.317.0

`curl -O -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
`
Getting a "blob does not exist" message:

```
$ cat actions-runner-linux-x64-2.317.0.tar.gz
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:20fcd9d5-a01e-0033-099a-b2befe000000
Time:2024-05-30T14:07:02.9234202Z</Message></Error>
```

**To Reproduce**

Attempt to download Linux x64 runner release tarball.

**Expected behavior**

Software package downloads :)

## Runner Version and Platform

2.317.0

OS of the machine running the runner? OSX/Windows/Linux/...

Linux x64

## What's not working?

See above - not sure if it's a problem with all releases or just Linux x64

## Job Log Output

N/A

## Runner and Worker's Diagnostic Logs

N/A

**Comment by TingluoHuang** [comment]
should be fixed now.

**Comment by joshtrutwin** [comment]
looks good, tyvm
