### ISSUE TITLE
too many breaking update 

### ISSUE THREAD

**Issue by joebnb** [actions/runner#3332]
<img width="865" alt="image" src="https://github.com/actions/runner/assets/1646883/a9ee34fb-0f7b-4183-8d03-c14fe103ce4a">

would decrease this?every 2 month i need build a image to up to date

**Comment by joebnb** [comment]
<img width="826" alt="image" src="https://github.com/actions/runner/assets/1646883/3dd2fa6f-b547-4c27-90ce-a810dc4c7afc">

seem there has not break change

**Comment by gricey432** [comment]
Every release is a "breaking release" in that previous releases become broken a while after new versions come out. I can't find where that was documented but there's a lot of conversation about this problem in #246

**Comment by nebuk89** [comment]
We allow you to opt out but do eventually stop old runners connecting https://github.blog/changelog/2022-02-01-github-actions-self-hosted-runners-can-now-disable-automatic-updates/

This can give you more time to verify new runner versions if you need :)
