### ISSUE TITLE
macos-latest image lacks `/usr/local/lib/gcc/current` symlink

### ISSUE THREAD

**Issue by PhilipDeegan** [actions/runner#3337]
Please add a symlink like in the previous images such that 

```/usr/local/lib/gcc/current``` points to the current gcc like ```/opt/homebrew/Cellar/gcc/14.1.0/lib/gcc/current```

[Previous discussion with no responses...](https://github.com/orgs/community/discussions/124141)

**Comment by nebuk89** [comment]
I think you got an answer in the discussion? Feel free to re-open here if not
