### ISSUE TITLE
Latest version (v2.317.0) of github runner available is forbidden. Nothing to upgrade to.

### ISSUE THREAD

**Issue by mattnakama-skytap** [actions/runner#3378]
**Describe the bug**
Our github runner refuses to run jobs, saying that version v2.317.0 is forbidden. I checked this repo's latest release, and it's v2.317.0. What are we supposed to upgrade to?

The last successful job completed at 20:46:14 UTC
The first "forbidden" error message shows up at 20:46:41 UTC

**To Reproduce**
1. Install latest github-runner v2.317.0 on NixOS
2. Start it and try to run a github action/workflow
3. See error

**Expected behavior**

## Runner Version and Platform
v2.317.0

OS of the machine running the runner? OSX/Windows/Linux/...
NixOS 24.05

## What's not working?
recent journalctl output:
```
Jul 09 20:57:25 automation2 Runner.Listener[432636]: √ Connected to GitHub
Jul 09 20:57:25 automation2 Runner.Listener[432636]: Current runner version: '2.317.0'
Jul 09 20:57:26 automation2 Runner.Listener[432636]: 2024-07-09 20:57:25Z: Listening for Jobs
Jul 09 20:57:27 automation2 Runner.Listener[432636]: An error occured: Error: Forbidden Runner version v2.317.0 is deprecated and cannot receive messages.
Jul 09 20:57:27 automation2 systemd[1]: github-runner-argo-2.service: Main process exited, code=exited, status=1/FAILURE
```

## Job Log Output
There's no job log output, because it refuses to run jobs.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by ellisvalentiner** [comment]
Seeing the same problem.

```
2024-07-09 21:22:38.129  DEBUG --- Docker enabled runner detected and Docker daemon wait is enabled
2024-07-09 21:22:38.13  DEBUG --- Waiting until Docker is available or the timeout of 120 seconds is reached
}CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
2024-07-09 21:22:38.146  NOTICE --- WARNING LATEST TAG HAS BEEN DEPRECATED. SEE GITHUB ISSUE FOR DETAILS:
2024-07-09 21:22:38.147  NOTICE --- https://github.com/actions/actions-runner-controller/issues/2056

√ Connected to GitHub

Current runner version: '2.317.0'
2024-07-09 21:22:40Z: Listening for Jobs
An error occured: Error: Forbidden Runner version v2.317.0 is deprecated and cannot receive messages.
Runner listener exit with terminated error, stop the service, no retry needed.
Exiting runner...
2024-07-09 21:22:40.771  NOTICE --- Runner init exited. Exiting this process with code 0 so that the container and the pod is GC'ed Kubernetes soon.
Removing the .runner file
```

**Comment by mattnakama-skytap** [comment]
@luketomlinson apologies for the ping, but could this be a backend issue? I happened to see your comment on #3366 and am wondering if there was a recent backend change. We did not change anything about our runners today; they just suddenly stopped working.

https://github.com/actions/runner/issues/3366#issuecomment-2204514441

**Comment by luketomlinson** [comment]
👋 This was a bad backend change. This should be rolled back now.

**Comment by ellisvalentiner** [comment]
Thanks! Our runners are working again.

**Comment by mattnakama-skytap** [comment]
> This should be rolled back now.

Thank you :slightly_smiling_face: 
I can confirm that our runners are back online :muscle:

**Comment by alexellis** [comment]
Also ran into this. Thanks for the swift rollback.

**Comment by jacobwgillespie** [comment]
@luketomlinson We are currently seeing this error again, here's an example session:

```
[2024-07-26 17:05:02Z ERR  GitHubActionsService] GET request to https://broker.actions.githubusercontent.com/message?sessionId=cfa9c468-c485-4c87-9c52-ae63a51668a6&status=Online&runnerVersion=2.317.0&os=Linux&architecture=X64&disableUpdate=true failed. HTTP Status: Forbidden
```

Since v2.318.0 was just released one hour ago, perhaps this has broken the logic?
