### ISSUE TITLE
"cannot run in wd" when running npm install in node Docker image since 2.165.2

### ISSUE THREAD

**Issue by Livven** [actions/runner#338]
## Describe the bug

Since runner version 2.165.2 running `npm install` in the `node:lts` Docker image skips the `postinstall` script with the message `cannot run in wd`.

This generally happens when running the command as a root user and can be fixed with the `--unsafe-perm` flag, however this was not necessary with runner version 2.164.0 using the exact same Docker image (`sha256:454651174f54836571258a329788574cf6552bddfd1a7113e769bd9fc3776fe6`).

See the following two jobs from the same commit, but using different runner versions:

- [2.164.0](https://github.com/Livven/sunnygit/runs/451149267#step:4:66): custom `postinstall` (`patch-package && electron-builder install-app-deps`) is executed
- [2.165.2](https://github.com/Livven/sunnygit/runs/456405350#step:4:64): `cannot run in wd`

This is not a big issue as the workaround with `--unsafe-perm` exists and [works fine](https://github.com/Livven/sunnygit/runs/456386767#step:4:62), but having it work out-of-the-box would still be nice.

## To Reproduce

1. `npm install`

## Expected behavior

Running `npm install` in the `node:lts` Docker image should execute the `postinstall` script.

## Runner Version and Platform

2.165.2, `ubuntu-latest`

## What's not working?
> Please include error messages and screenshots.

## Job Log Output
> If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
> If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by TingluoHuang** [comment]
@Livven I am not sure this is a runner issue since the following run already failed with 2.164.0 runner.
https://github.com/Livven/sunnygit/runs/451977080?check_suite_focus=true#step:4:59

maybe something to do with the repo rename?  gitchops -> sunnygit

**Comment by Livven** [comment]
Damn, you're right, I overlooked that. And indeed adjusting the name in the package.json to match the Github project [fixes the issue](https://github.com/Livven/sunnygit/runs/465428388). No idea what kinda magic is responsible for that, perhaps matching package name with working directory but that does not seem to be the case on Gitlab.

Anyway, thanks for your help!
