### ISSUE TITLE
v2.318.0 release commit was unsigned/unverified

### ISSUE THREAD

**Issue by joseph-aha** [actions/runner#3409]
**Describe the bug**
The git commit releasing `v2.318.0` was not signed and is unverified on GitHub. This prevents `git verify-commit` from validating the release integrity of the branch.

**To Reproduce**

![Unverified v2 318 0](https://github.com/user-attachments/assets/294b0b96-729b-49db-a071-33e3f255f35c)

**Expected behavior**

(v2.317.0 release)
![Verified v2 317 0](https://github.com/user-attachments/assets/5fc8e209-e87d-458e-a066-85b5d34be544)

## Runner Version and Platform
Version of your runner? v2.318.0

OS of the machine running the runner? Not applicable (but we are using Linux)

## What's not working?
`git verify-commit v2.318.0` fails due to unsigned/unverified commit:

![Unverified v2 318 0](https://github.com/user-attachments/assets/8005541d-3271-4bad-b444-d93751bf8106)

## Job Log Output
Not applicable

## Runner and Worker's Diagnostic Logs
Not applicable

**Comment by nebuk89** [comment]
Let me find out what has happened here

**Comment by nebuk89** [comment]
We will add repo rules to avoid this in the future

**Comment by timothyeburke** [comment]
@nebuk89 Thank you! This will be a huge improvement for my team!
