### ISSUE TITLE
Show docker logs when service fails to start

### ISSUE THREAD

**Issue by dakale** [actions/runner#341]
If a service fails to start (healthcheck becomes `unhealthy`) we could print the `docker logs`. Without being able to see logs, the job just fails and it is hard to debug

cc @jclem

**Comment by TrejGun** [comment]
must feature

**Comment by JoannaaKL** [comment]
Hi @dakale is this ticket about adding more explicit error message in the 'Initialise containers' step or the case where logs are not visible at all? 
We noticed that all docker logs are being printed in 'Stop containers' step (under 1 and 2 points):

![image](https://user-images.githubusercontent.com/67866556/188593131-c9a01dbd-c71e-4671-a7d8-4986cd6e2014.png)

Ps. This screenshot is from our work-in-progress branch but 'Stop containers' section was not modified. :)
