### ISSUE TITLE
Introduce $COMMIT_RANGE (simmilar to $TRAVIS_COMMIT_RANGE) 

### ISSUE THREAD

**Issue by jjangga0214** [actions/runner#342]
**Feature Request**

I think providing an env var like `$COMMIT_RANGE` would be possible. For example, Travis provides `$TRAVIS_COMMIT_RANGE`, which is the range of commits that were included in the push or pull request. 

This would be very handy for incremental lint. For example,
```bash
eslint $(git diff --name-only --diff-filter=d $COMMIT_RANGE | egrep '\.(js|ts)$')
```
would run eslint only for modified .js or .ts files from the last push. 

P.S. For forks who want to know what the example command means,
- `--name-only` option only lists filename, not content.
- `--diff-filter=d` does not list deleted files. 
- `egrep '\.(js|ts)$'` filters only files with `.js` or `.ts` extension.

_Workaround 1._

Just naively compare origin/master with HEAD of current branch.

```bash
eslint $(git diff --name-only --diff-filter=d origin/master HEAD | egrep '\.(js|ts)$')
```

_Workaround 2._

Record the last pused commit SHA into the cache, and restore it(e.g. `$THE_LAST_COMMIT`) in every push and run 

```bash
eslint $(git diff --name-only --diff-filter=d $THE_LAST_COMMIT HEAD | egrep '\.(js|ts)$')
```
But this is somewhat inconvenient.

**Advanced Feature Request**

Introduce `$COMMIT_RANGE_UNPASSED`, which is a commit range from the last success(pass every executed jobs with exit code 0) push. 

This would be useful for this scenario, for example.

1. Someone pushes files.
2. Lint is failed.
3. The one has another priority task, so does not fix the file for now.
4. The one makes some changes on other files, and pushes it.

In this case, if lint is configured to run only against `$COMMIT_RANGE`, then this time the lint would be passed, even though the previously failed file is not fixed. So, one might want to lint against `$COMMIT_RANGE_UNPASSED`, for making sure the lint is failed again. This can be useful to remind there's a file to fix later.

**Comment by ericsciple** [comment]
@jjangga0214 does the github event payload contain the values you want?

```yaml
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```

The event json is also written to `$GITHUB_EVENT_PATH` if that helps.

**Comment by jjangga0214** [comment]
@ericsciple Oh, thanks!
I checked `$GITHUB_EVENT_PATH`, and it gives `before`, which is the last commit previously pushed, and `after`, which is the latest commit(current pushed commit).

```json
{
  "after": "93a7bbba9ffbdc28b8fb071d32313e9f5cb79edf",
  "base_ref": null,
  "before": "89b442ca3a29bb997b8e21c07d005a1e893d8eb0"
}
```

This is essentially the same information as `$COMMIT_RANGE`, so the problem is solved!
However, a thing like `$COMMIT_RANGE_UNPASSED` would still be useful.
So let this issue as a feature request for it then.

Thanks again by the way :)

**Comment by eregon** [comment]
As a note,
```yml
      run: ...
      env:
        COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
```

Works nicely for PRs (`if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then`).

When using `actions/checkout@v2` it needs 
```yml
      with:
        fetch-depth: 0
```

**Comment by nikola-jokic** [comment]
Hey @jjangga0214 

I know it has been a long time since this is submitted, but can you please post this to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages)? 

That should be a better place to start this discussion. The forum is actively monitored and since this change is affecting the platform in general, it will help us route the feature request to the correct team.

I will close this issue here since there is nothing we can do on the runner, but please submit it to the forum :relaxed:
