### ISSUE TITLE
Build system info in the log

### ISSUE THREAD

**Issue by hugovk** [actions/runner#346]
**Describe the enhancement**

Please could you could output the OS version along with other pertinent tools and version numbers at the start of each run?

This can really help debug problems when things are upgraded in the image. For example, Travis CI begins builds with "Build system information":

![image](https://user-images.githubusercontent.com/1324225/68320106-0aa0f000-00c8-11ea-834d-d02d84af3734.png)

For example, see https://github.com/actions/virtual-environments/issues/53#issuecomment-550405295 and https://github.com/actions/virtual-environments/issues/81#issuecomment-562761489 for confusion caused by not knowing what is running. 

Thank you!

**Additional information**

Originally requested at https://github.com/actions/virtual-environments/issues/79, and they suggested requesting it here.

**Comment by hross** [comment]
@hugovk thanks for bringing this up. we definitely want to do this. check out the above doc ☝️for info on how we'll do it (probably ship in the next week or so).

**Comment by TingluoHuang** [comment]
shipped as part of the 2.168.0 runner.
