### ISSUE TITLE
Workflow jobs are completed, but still working.

### ISSUE THREAD

**Issue by gorjs3540** [actions/runner#3462]
**Describe the bug**
Workflow jobs are completed, but still working. Strangely, it's only one action.
It is probably the same as this problem #2409 

**To Reproduce**
1. The action is executed.
2. All workflow steps are complete.
3. Workflow is still in queue and not finished.
4. It is not even canceled. The request was successful, but it was not canceled.

**Expected behavior**
All workflows have finished and the queue must be closed.

## Runner Version and Platform
Version of your runner?

workflow jobs: `ubuntu-latest`
local machine: `macOS(Sonoma 14.6.1 Apple M3 Pro, RAM 36GB)`

## What's not working?
Please include error messages and screenshots.
<img width="685" alt="스크린샷 2024-09-13 14 59 12" src="https://github.com/user-attachments/assets/c7ab29f0-c2fd-49e9-8d73-69ba1b6352d2">
<img width="637" alt="스크린샷 2024-09-13 15 05 09" src="https://github.com/user-attachments/assets/fd0e5a07-9a60-4ebc-a9f9-8d5cafdaa51d">
Strangely, it's only one action
<img width="314" alt="스크린샷 2024-09-13 15 06 24" src="https://github.com/user-attachments/assets/0c90461f-c9ab-4568-bc50-52026b7875fc">

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by vihaanthora** [comment]
Facing this same issue in my repository as well. Terminating the job doesn't seem to be stopping it either.

**Comment by gorjs3540** [comment]
I've had a problem with github status since writing this PR. If it's resolved after this, I'll close that PR.
<img width="2168" alt="스크린샷 2024-09-13 15 12 32" src="https://github.com/user-attachments/assets/37a259f4-0ebe-4f76-b1ee-c448a844fb60">

**Comment by haegeon-kim** [comment]
Status normalized and resolved! 👍

**Comment by antspy** [comment]
Is it possible that there was a regression? I am still seeing the issue today

**Comment by gmazzo** [comment]
Same here, jobs is ended (even for days) but the check never gets completed 🤦 

![Image](https://github.com/user-attachments/assets/ab80f149-b76a-4be2-a913-cdc8710f69e3)

Which is blocking on my PRs on that repo, and only for that repo. If I remember correctly, it started to happen with an specific `typescript` bump from dependeabot but I can't understand how that may affect the internals of GHA to silently fail to to update the PR's check 🤔
