### ISSUE TITLE
An error occured: Error: Forbidden Runner version v2.320.0 is deprecated and cannot receive messages.

### ISSUE THREAD

**Issue by spoonincode** [actions/runner#3486]
**Describe the bug**
Despite 2.320.0 being the latest runner release (released about 50 minutes ago as of this report), it is considered forbidden

**To Reproduce**
Run 2.320.0, it errors out.

**Expected behavior**
Latest released runner should work.

## Runner Version and Platform
2.320.0 Linux

## What's not working?
```
[   18.167887] runner.sh[1167]: --------------------------------------------------------------------------------
[   18.168004] runner.sh[1167]: |        ____ _ _   _   _       _          _        _   _                      |
[   18.168024] runner.sh[1167]: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
[   18.168040] runner.sh[1167]: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
[   18.168056] runner.sh[1167]: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
[   18.168141] runner.sh[1167]: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
[   18.168158] runner.sh[1167]: |                                                                              |
[   18.168182] runner.sh[1167]: |                       Self-hosted runner registration                        |
[   18.168198] runner.sh[1167]: |                                                                              |
[   18.168225] runner.sh[1167]: --------------------------------------------------------------------------------
[   18.168582] runner.sh[1167]: # Authentication
[   20.103561] runner.sh[1167]: √ Connected to GitHub
[   20.207693] runner.sh[1167]: # Runner Registration
[   20.401836] runner.sh[1167]: √ Runner successfully added
[   21.694475] runner.sh[1167]: √ Runner connection is good
[   21.694599] runner.sh[1167]: # Runner settings
[   21.697790] runner.sh[1167]: √ Settings Saved.
[   21.719474] runner.sh[1122]: + ./run.sh
[   23.562029] runner.sh[1198]: √ Connected to GitHub
[   23.928657] runner.sh[1198]: Current runner version: '2.320.0'
[   23.929168] runner.sh[1198]: 2024-10-03 20:14:45Z: Listening for Jobs
[   24.338755] runner.sh[1198]: An error occured: Error: Forbidden Runner version v2.320.0 is deprecated and cannot receive messages.
[   24.353845] runner.sh[1194]: Runner listener exit with terminated error, stop the service, no retry needed.
```

## Job Log Output
n/a

## Runner and Worker's Diagnostic Logs
na/a

**Comment by nsheaps** [comment]
Can confirm on self-hosted runners with the Github AutoscalingSet on EKS
Started failing about 30m ago, affects all new builds on self-hosted runners

**Comment by TingluoHuang** [comment]
Can someone share the runner diag log with us?

**Comment by knkarthik** [comment]
We are experiencing this as well on EKS with gha-runner-scale-set.

**Comment by TingluoHuang** [comment]
The issue should have been mitigated, please let me know if you still see any error.

**Comment by AlexSwensen** [comment]
@TingluoHuang we are also experiencing the same issue around the same time. Restarting our workers to see if it's resolved...

**Comment by nsheaps** [comment]
Looks like they're starting to run again! I think I need to kill the failed EphemeralRunners though. Going to kill most but leave one to confirm (come back later to check)

**Comment by nsheaps** [comment]
Can confirm, as soon as I deleted the failed EphemeralRunners new runners were created for the workflows. I had to delete them, they didn't seem to be self recovering (used one from 75m ago, no logs streaming from controller or pod (did not exist)). Seems like the controller gets into a state that if a runner fails to start the listener gets stuck thinking that a pod is allocated but won't try to start it more than 5 times.

I think there's a subtle bug here that it needs to retry indefinitely with an exponential backoff (up to a limit, perhaps 5m interval?) so that it can self recover.

**Comment by nsheaps** [comment]
@TingluoHuang A random chosen runner's logs are attached (from k8s log streaming, so searched the runner pod for lines that began with `[RUNNER `)
[exportedLogRecords.CSV](https://github.com/user-attachments/files/17250328/exportedLogRecords.CSV)

**Comment by spoonincode** [comment]
Seems to be working well now, thanks for the quick fix.
