### ISSUE TITLE
OSX Runner service fails to start

### ISSUE THREAD

**Issue by jl-gogovapps** [actions/runner#349]
**Describe the bug**

When I ssh into my OSX box, and try to start the service, I receive the following error:
`Could not find domain for port (Aqua)`

The command I'm running is `cd actions-runner && ./svc.sh install`

The ./run.sh command works without issue

**To Reproduce**
./svc.sh start

**Expected behavior**
- The service starts
- Rebooting the machine starts the service automatically

## Runner Version and Platform
Version of your runner?
osx-x64-2.165.2

OS of the machine running the runner? OSX/Windows/Linux/...
OSX Catalina

## What's not working?

`Could not find domain for port (Aqua)`

## Job Log Output
```
$ ./svc.sh install
Creating launch runner in /Users/xxx/Library/LaunchAgents/actions.runner.xxx-xxx.xxx-build-osx.plist
Creating /Users/xxx/Library/Logs/actions.runner.xxx-xxx.xxx-build-osx
Creating /Users/xxx/Library/LaunchAgents/actions.runner.xxx-xxx.xxx-build-osx.plist
Creating runsvc.sh
Creating .service
svc install complete
```

## Runner and Worker's Diagnostic Logs
N/A

**Comment by TingluoHuang** [comment]
@jl-gogovapps i did a quick google search on the error, looks like related permission around the SSH user and the service installed user.
what user did you use to run `./svc.sh install` and what user did you use to SSH?

**Comment by jl-gogovapps** [comment]
Hey @TingluoHuang, thanks for checking in on it.   I'm ssh-ing, and then running `./svc.sh install` so it's the same user.  It's also the only primary user on the machine.

**Comment by jl-gogovapps** [comment]
Looks like this did the trick for me!

```
sudo cp {/Users/xxx/Library/LaunchAgents,/Library/LaunchDaemons}/your.plist
```

I was able to reboot my machine without logging in and see the runner active

**Comment by raphaelcruzeiro** [comment]
This is happening on a fresh macOS install.

**Comment by ivan-gaydamakin** [comment]
Solution by @jl-gogovapps not good, because LaunchDaemons doesn't have access to keychain.

Better copy to LaunchAgents Like:
sudo cp {/Users/xxx/Library/LaunchAgents,/Library/LaunchAgents}/your.plist

**Comment by zackrspv** [comment]
This issue is still ongoing - MacOS BigSur 11.4 - even if copying to /Library/LaunchAgents or even the Daemon folder, it still won't run with the same Aqua domain issue. 

Thus, once the agent is INSTALLED, you cannot remove it, nor reconfigure it using the built-in SH commands. 

Note, generally speaking, we run 2-3 runners on the same mac machine, so that we can run parallel QA checks and builds - the first agent runs fine, but sequent agents give that same Aqua domain issue.

**Comment by pjelar** [comment]
> This issue is still ongoing - MacOS BigSur 11.4 - even if copying to /Library/LaunchAgents or even the Daemon folder, it still won't run with the same Aqua domain issue.
> 
> Thus, once the agent is INSTALLED, you cannot remove it, nor reconfigure it using the built-in SH commands.
> 
> Note, generally speaking, we run 2-3 runners on the same mac machine, so that we can run parallel QA checks and builds - the first agent runs fine, but sequent agents give that same Aqua domain issue.

+1

**Comment by pjelar** [comment]
> This issue is still ongoing - MacOS BigSur 11.4 - even if copying to /Library/LaunchAgents or even the Daemon folder, it still won't run with the same Aqua domain issue.
> 
> Thus, once the agent is INSTALLED, you cannot remove it, nor reconfigure it using the built-in SH commands.
> 
> Note, generally speaking, we run 2-3 runners on the same mac machine, so that we can run parallel QA checks and builds - the first agent runs fine, but sequent agents give that same Aqua domain issue.

Actually after logging in as the user it worked as stated above

**Comment by jl-gogovapps** [comment]
@ivan-gaydamakin  thanks for that feedback.  I haven't given it a try, but that could explain all the keychain headaches I was having 😆

**Comment by VladasZ** [comment]
I still have this issue. It appears if I SSH to my mac without logging to GUI. If I login physically everything is okay. @jl-gogovapps maybe this issue should be reopened? You closed it with a workaround but the issue is still here.

**Comment by mad01** [comment]
I still have the same issue to. It only works for the when logging in to the mac with VNC and after that it's okay to start the service over ssh. i still run my service as a user service

**Comment by stingalleman** [comment]
Also still having this issue. Can this issue be reopened? @TingluoHuang @jl-gogovapps

**Comment by thboop** [comment]
@stingalleman are you seeing the aqua domain issue or the issue described in [this ticket](https://github.com/actions/runner/issues/743). I want to be sure we reopen the correct issue.

Can you also describe your setup, how are you configuring the runners and how many runners do you on a single machine?

**Comment by stingalleman** [comment]
@thboop No, I'm not having the issue described in that ticket.

I'm having this issue on both a Intel and Apple Silicon-based runner, both running MacOS 11.2.1. I just run a single runner on each machine.

I cannot try this fix as I do not have a VNC or physical access to said machines.

<details>
<summary>Log</summary>

```
# Authentication


√ Connected to GitHub

# Runner Registration

Enter the name of the runner group to add this runner to: [press Enter for Default]

Enter the name of runner: [press Enter for vulcanus]

This runner will have the following labels: 'self-hosted', 'macOS', 'X64'
Enter any additional labels (ex. label-1,label-2): [press Enter to skip] intel

√ Runner successfully added
√ Runner connection is good

# Runner settings

Enter name of work folder: [press Enter for _work]

√ Settings Saved.

builder@vulcanus actions-runner % ./svc.sh install
Creating launch runner in /Users/builder/Library/LaunchAgents/actions.runner.pakket-project.vulcanus.plist
Failed: error: exists /Users/builder/Library/LaunchAgents/actions.runner.pakket-project.vulcanus.plist
builder@vulcanus actions-runner % ./svc.sh start
starting actions.runner.pakket-project.vulcanus
Could not find domain for port (Aqua)
Failed: failed to load /Users/builder/Library/LaunchAgents/actions.runner.pakket-project.vulcanus.plist
```

</details>

**Comment by NRay7882** [comment]
I'm having this same problem on MacOS 11.6 when trying to install the runner as part of the AWS ec2-macos-init user_data configuration, which runs as root:
```
root# su - ec2-user -c "export RUNNER_CFG_PAT=<GITHUB_PERSONAL_ACCESS_TOKEN> \                                                                                                                                           && /Users/ec2-user/actions-runner/create-latest-svc.sh \
    -s <ORG/REPO> \
    -n <RUNNER_NAME> \
    -u ec2-user \
    -l aws-testing"
Configuring runner @ <ORG/REPO>

/usr/bin/curl
/usr/local/bin/jq

Generating a registration token...

Downloading latest runner ...
Downloading v2.283.3 for osx ...
https://github.com/actions/runner/releases/download/v2.283.3/actions-runner-osx-x64-2.283.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   645  100   645    0     0   7166      0 --:--:-- --:--:-- --:--:--  7166
100 48.7M  100 48.7M    0     0  37.8M      0  0:00:01  0:00:01 --:--:-- 45.4M
-rw-r--r--  1 ec2-user  staff  51151504 Oct  4 21:16 /Users/ec2-user/actions-runner/runner/actions-runner-osx-x64-2.283.3.tar.gz

Extracting actions-runner-osx-x64-2.283.3.tar.gz to /Users/ec2-user/actions-runner/runner
~/actions-runner/runner ~

Configuring <RUNNER_NAME> @ https://github.com/<ORG>/<REPO>
/Users/ec2-user/actions-runner/runner/config.sh --unattended --url https://github.com/<ORG>/<REPO> --token *** --name <RUNNER_NAME> --labels aws-testing

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration




√ Runner successfully added
√ Runner connection is good

# Runner settings


√ Settings Saved.


Configuring as a service ...
Creating launch runner in /Users/ec2-user/Library/LaunchAgents/actions.runner.<ORG>-<REPO>.<RUNNER_NAME>.plist
Creating /Users/ec2-user/Library/Logs/actions.runner.<ORG>-<REPO>.<RUNNER_NAME>
Creating /Users/ec2-user/Library/LaunchAgents/actions.runner.<ORG>-<REPO>.<RUNNER_NAME>.plist
Creating runsvc.sh
Creating .service
svc install complete
starting actions.runner.<ORG>-<REPO>.<RUNNER_NAME>
Could not find domain for port (Aqua)
Failed: failed to load /Users/ec2-user/Library/LaunchAgents/actions.runner.<ORG>-<REPO>.<RUNNER_NAME>.plist
```

**Comment by F-WRunTime** [comment]
> 

Is this still an issue for anyone else? My M1 runner never remains online for more than 5 minutes then goes offline. Comes back online. Are there default configurations for Mac's that require the networking configuration to be updated?

**Comment by amaraldavi1** [comment]
If you enable the autologin for the user that runs the github script it will work! Similar to this video. Tested on mac-m1. https://www.youtube.com/watch?v=lFQRgxW0Cq4
