### ISSUE TITLE
[Bug] Multiple jobs triggered currently on the same self-hosted runner

### ISSUE THREAD

**Issue by siddvenk** [actions/runner#3544]
**Describe the bug**
We have noticed a behavior change where multiple jobs are being triggered on the same runner concurrently, which is causing issues.

2 days ago, we had a "successful" run of one of our core workflows https://github.com/deepjavalibrary/djl-serving/actions/runs/11686892919. The failures there are valid, but the key point from that workflow is that all jobs were successfully picked up by our self-hosted runners when a runner was ready. I'm not sure how to best show this, but the start time for each job lines up with when a previous job finished and a runner became available. Jobs are "staggered" according to when a runner is actually available.

We are no longer observing this behavior. We have started seeing that all jobs are started at the same time, regardless of whether there is a free runner or not. This workflow run shows that https://github.com/deepjavalibrary/djl-serving/actions/runs/11725668282. The start time for all jobs is roughly the same, and I can see that two jobs are being triggered on the same runner at the same time. For example, this job https://github.com/deepjavalibrary/djl-serving/actions/runs/11725668282/job/32662789056 uses `g6-25831` and starts at the same time as this job https://github.com/deepjavalibrary/djl-serving/actions/runs/11725668282/job/32662792422 also using `g6-25831`.

In this example workflow, we have more jobs than self-hosted runners. The expected behavior is that jobs are queued until a runner becomes free, and only start when a runner is 

Since then, 

**To Reproduce**
1. Workflow with 2 jobs, where each job uses the same self-hosted runner (only 1 available)

**Expected behavior**
Jobs should be queued until a self-hosted runner actually becomes available. Jobs should not start concurrently on the same machine.

## Runner Version and Platform
self-hosted runner using 2.320.0 (same version on both the working runs, and impacted runs)

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
We are seeing errors in the `actions/checkout` step, but I don't believe this is an error with that action. I can see that multiple jobs are being scheduled on the same self-hosted runner at the same time. We expect that only 1 job runs on a runner at a time.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by siddvenk** [comment]
I see, yea I totally missed the sequential piece because the prior job completed/failed so quickly.

Do you have an idea of why we would suddenly start seeing this issue? I don't see any recent changes that would explain why the behavior changed suddenly...

**Comment by siddvenk** [comment]
we determined a workaround. Still unclear why this started happening all of a sudden, but thanks for the pointers.

**Comment by Arwarld** [comment]
@siddvenk Can you specify how you your workaround works? As I am facing the same issues

2025-04-05 05:23:13Z: Running job: job_name
2025-04-05 05:57:04Z: Running job: job_name
2025-04-05 05:57:26Z: Job job_name completed with result: Canceled
2025-04-05 05:57:36Z: Job job_name completed with result: Failed
