### ISSUE TITLE
bash not found in node12_alpine?

### ISSUE THREAD

**Issue by teohhanhui** [actions/runner#358]
**Describe the bug**
First, my apologies if this is not the correct place for this issue, but I see: https://github.com/actions/runner/blob/6c70d53eead402ba5d53676d6ed649a04e219c9b/src/Misc/externals.sh#L142 and https://github.com/actions/runner/blob/6c70d53eead402ba5d53676d6ed649a04e219c9b/src/Runner.Worker/Handlers/StepHost.cs#L151-L152

It seems like the `node12_alpine` external tool (image) does not contain `bash`(?), resulting in something like https://github.com/codecov/codecov-action/issues/60

(?) I'm not really sure because according to https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/non-glibc-containers.md it seems like `bash` is compulsory in such an image?

As you can see this is how it was called: https://github.com/codecov/codecov-action/blob/71d5dea6af7ed28ffc892337ef6cc9d63dcfc155/index.js#L83

**To Reproduce**
1. Use an `alpine`-based image as the job container
2. Try to execute `bash` using `exec.exec` (`@actions/exec`)
3. Get error such as https://github.com/teohhanhui/api-platform-core/runs/487602279?check_suite_focus=true#step:18:15

**Expected behavior**
No error, `bash` is executed.

## Runner Version and Platform
Version of your runner? No idea (hosted version on github.com)

OS of the machine running the runner? No idea (hosted version on github.com)

## What's not working?
```
Container distribution is alpine. Running JavaScript Action with external tool: node12_alpine
bash codecov.sh -n phpunit-php7.4 -F phpunit -Z
##[error]Codecov failed with the following error: There was an error when attempting to execute the process 'bash'. This may indicate the process failed to start. Error: spawn bash ENOENT
```

## Job Log Output
https://github.com/teohhanhui/api-platform-core/runs/487602279?check_suite_focus=true#step:18:15

## Runner and Worker's Diagnostic Logs
N/A (hosted version on github.com)

**Comment by teohhanhui** [comment]
Uhh, I've misunderstood something, `bash` needs to be installed in the job container? And `node12_alpine` is not a container / image, but a binary.

Perhaps this could be better documented though...

**Comment by TingluoHuang** [comment]
Yes, any executable you use needs to be installed in the job container. 😄
