### ISSUE TITLE
Provide runner as a Docker Image

### ISSUE THREAD

**Issue by WtfJoke** [actions/runner#367]
**Describe the enhancement**
Is it possible for you to provide official docker images for letting a runner run?

**Additional information**
We want to use self hosted runner, but we dont want to maintain machines/vms so it would be cool to have a ready to run official docker image in order to use them in services like aws fargate/azure container instances.

If im wrong here and I should have opened a topic in the github actions community forum please let me know and feel free to close the issue/feature request.

**Comment by vincentbrison** [comment]
Some example of runner as a Docker image:
- https://github.com/tcardonne/docker-github-runner
- https://github.com/myoung34/docker-github-actions-runner
- https://github.com/joeyx22lm/docker-github-actions-runner

Additionally, Runner running in Docker is not able to use Docker itself (https://github.com/actions/runner/blob/f9b5d626c5486d1f02b3bd45879f61834b7aeecc/src/Runner.Worker/ContainerOperationProvider.cs#L68), which is a major downside to be able to manage self hosted runners with Kubernetes for example, without losing time playing with VMs or real machines.

**Comment by WtfJoke** [comment]
Thank you @vincentbrison for providing these examples, I found a couple of them as well, but I am not sure if we are allowed to use them in our company (we have a restriction to use only official images). Thats the reason why I asked here. :)

The hint about docker in docker is useful (a couple of application suffer of this problem).  👍

**Comment by ppamorim** [comment]
I don't understand this limitation, what's the difference between this and a VM running in the machine? We are using M1 machines as our hosts and since the native runner on macOS does not support containers, we decided to use Docker, but when executing it, we get this error.

**Comment by scolastico** [comment]
Also its possible with docker to run a docker conatiner in a docker container.
You only need to mount the docker directory `/var/lib/docker` in the normal file system so it doesnt gets mounted as an AUFS mountpoint.

This page i found describes a bit better than me: https://www.docker.com/blog/docker-can-now-run-within-docker/

**Comment by pdomagala-tr** [comment]
@scolastico did you manage to do this?

**Comment by scolastico** [comment]
not in this way but in another: https://github.com/scolastico-dev/s.RunnerManager

**Comment by pdomagala-tr** [comment]
are you able to run docker inside the docker container?

**Comment by nikola-jokic** [comment]
Hey everyone,

There is a bare-minimum runner image available now: ghcr.io/actions/actions-runner:latest
The Dockerfile is available [here](https://github.com/actions/runner/blob/main/images/Dockerfile). 

It is now part of the release process (https://github.com/actions/runner/pull/2250). The idea is to provide an image that can be used by `actions-runner-controller`, but also as a stand-alone image.

**Comment by danm** [comment]
hi @nikola-jokic how do you use this image?

`docker run ghcr.io/actions/actions-runner:2.300.2` ?

**Comment by nikola-jokic** [comment]
Hey @danm,

You would need to provide an entrypoint. Keep in mind, the entrypoint should know how to configure and run the runner. The entrypoint by default does not exist. So imperatively, you can provide an `--entrypoint` with `docker run`, or you can use this `Dockerfile` as a base for building your own minimal runner image.

**Comment by Spriz** [comment]
Hi @nikola-jokic  - thanks for providing those Dockerfiles - is there any plans to support docker in docker? We're in the process of migrating from Gitlab CI/CD to Github Actions and it seems quite agressive to run autoscaling VMs compared to running 1-2 dedicated machines that runs 5-10 instances of that container.

Either being able to use docker-in-docker, or having the agent support multiple workspaces on the same VM would both solve this.

**Comment by danm** [comment]
Hi @CarlSargunar 
This is the way we are creating Docker the runner.

Create a directory with 2 files, `Dockerfile` and `runner.sh`

The Dockerfile could look like this...

Dockerfile
```Dockerfile
FROM ghcr.io/actions/actions-runner:latest
RUN sudo apt update -y && sudo apt install build-essential git curl -y

RUN curl -sL https://deb.nodesource.com/setup_16.x -o ./tmp/nodesource_setup.sh
RUN sudo chmod +x ./tmp/nodesource_setup.sh
RUN sudo ./tmp/nodesource_setup.sh

COPY ./runner.sh .
CMD ["./runner.sh"]
```

runner.sh
```sh
#!/bin/sh

./config.sh --url https://github.com/$REPO --token $TOKEN --name $NAME --unattended
sudo ./bin/runsvc.sh
```

Run `docker build --no-cache -t docker/github-runner .` to build your image.
Run `docker run docker/github-runner`

Though I don't think you are supposed to use `runsvc.sh` anymore. Check the docs for the recommended.

**Comment by uhthomas** [comment]
For anyone stumbling upon this in future, this one command should be enough. Just replace the URL and token.

```sh
❯ docker run -it ghcr.io/actions/actions-runner:2.314.1 sh -c './config.sh --url https://github.com/<user or org>/<repo> --token <token> --unattended && ./run.sh'
```

(use `docker run -d` instead of `docker run -it` to run in the background)

**Comment by dorinclisu** [comment]
Here's my docker compose solution that survives host reboot, it works around the limitation that runner registration config paths are hardcoded. https://github.com/dorinclisu/devops-setup/tree/main/github_runner
