### ISSUE TITLE
Install as service 

### ISSUE THREAD

**Issue by Emtec** [actions/runner#370]
**Describe the bug**
Cannot install runner as service, when runner name contains spaces. 

**To Reproduce**
1. Configure new runner with a name that contains spaces
2. Run sudo ./svc.sh install
3. See error

**Expected behavior**
SVC bash should just install runner as service.

## Runner Version and Platform
OS of the machine running the runner? Centos 8

## What's not working?
Creating launch runner in /etc/systemd/system/actions.runner.{Owner}-{RepositoryName}.{Runner name: Development Server}.service
Run as user: centos
Run as uid: 1000
gid: 1000
chmod: cannot access '/etc/systemd/system/actions.runner.{Owner}-{RepositoryName}.{Runner name: Development Server}': No such file or directory
chmod: cannot access 'Server.service': No such file or directory
Failed: failed to set permissions on /etc/systemd/system/actions.runner.{Owner}-{RepositoryName}.{Runner name: Development Server}.service

## Possible solution
In file svc.sh before UNIT_PATH add:
``SVC_NAME=${SVC_NAME// /_}``

**Comment by TingluoHuang** [comment]
@Emtec thanks for reporting, do you want to create a PR to fix this? 😄
