### ISSUE TITLE
Question: is the runner locked when executing a pipeline?

### ISSUE THREAD

**Issue by nicolas-marcq** [actions/runner#375]
Hi,
I don't find the answer in the doc.
Is the runner locked and not accept another jobs when already executing a pipeline?

I'm wondering because my pipeline use a docker compose to provide services, it would not woks with multiple execution of the same pipeline in the same runner.

Thanks.

**Comment by ericsciple** [comment]
@nicolas-marcq yes a runner is locked for the duration of a job - does not accept other jobs

**Comment by nicolas-marcq** [comment]
Thanks.
