### ISSUE TITLE
Debug logs for hashFiles function

### ISSUE THREAD

**Issue by JeremyLoy** [actions/runner#377]
The `hashFiles` function accepts a glob (which I think is parsed by the actions/toolkit glob package).

Its extremely hard at the moment to determine if your glob (and therefore cache-key) is correct as it doesn't output the names of the hashed files.

I propose the filename inputs to `hashFiles` are logged to provide a simpler, smoother, and more accurate experience using actions/cache

**Comment by TingluoHuang** [comment]
@JeremyLoy 

the v2 hashfiles function print out folloing info under debug (v2 hashfiles is still rolling out to service, should hit all service later this week or early next week)
```
##[debug]Search root directory: '/Users/runner/runners/2.165.2/work/canary/canary'
##[debug]Search pattern: '**/package-lock.json'
##[debug]Starting process:
##[debug]  File name: '/Users/runner/runners/2.165.2/externals/node12/bin/node'
##[debug]  Arguments: '"/Users/runner/runners/2.165.2/bin/hashFiles"'
##[debug]  Working directory: '/Users/runner/runners/2.165.2/work/canary/canary'
##[debug]  Require exit code zero: 'False'
##[debug]  Encoding web name:  ; code page: ''
##[debug]  Force kill process on cancellation: 'False'
##[debug]  Redirected STDIN: 'False'
##[debug]  Persist current code page: 'False'
##[debug]  Keep redirected STDIN open: 'False'
##[debug]  High priority process: 'False'
##[debug]Process started with process id 1166, waiting for process exit.
##[debug]Match Pattern: **/package-lock.json
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::implicitDescendants 'true'
##[debug]::debug::omitBrokenSymbolicLinks 'true'
##[debug]::debug::Search path '/Users/runner/runners/2.165.2/work/canary/canary'
##[debug]/Users/runner/runners/2.165.2/work/canary/canary/node/package-lock.json
##[debug]/Users/runner/runners/2.165.2/work/canary/canary/toolkit/core/package-lock.json
##[debug]/Users/runner/runners/2.165.2/work/canary/canary/toolkit/github/package-lock.json
##[debug]Find 3 files to hash.
##[debug]Hash result: '4609310090f562c0d84909ca18fefb0c2b2fe753979db324f2aab1e7580ba038'
```

I hope that will solve your problem?

**Comment by JeremyLoy** [comment]
Yes, this is exactly what I'm looking for.

How does one enable the debug log level?

**Comment by TingluoHuang** [comment]
@JeremyLoy  https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging

**Comment by TingluoHuang** [comment]
close since v2 hashFiles() has shipped to all actions' user.

**Comment by IanButterworth** [comment]
As it appears related I'll note that there seems to be a bug in the implementation of how `hashFiles` is parsed as an expression, causing multiple args to be grouped together into a single pattern arg https://github.com/orgs/community/discussions/75884
