### ISSUE TITLE
Cron triggered two times at once and missed one time

### ISSUE THREAD

**Issue by Maxim-Mazurok** [actions/runner#379]
**Describe the bug**
My action is scheduled to run every hour: https://github.com/Maxim-Mazurok/google-api-typings-generator/blob/master/.github/workflows/build.yml

But recently this action got run on the same hour twice and missed another run. You can see in the log below, that I expected job to run at 16:04:xx, but it got ran on 17:04:09

This is the start times of my action:
Mon, 09 Mar 2020 15:04:09 GMT (https://github.com/Maxim-Mazurok/google-api-typings-generator/runs/495421149)
Mon, 09 Mar 2020 17:04:09 GMT (https://github.com/Maxim-Mazurok/google-api-typings-generator/runs/495738420)
Mon, 09 Mar 2020 17:04:08 GMT (https://github.com/Maxim-Mazurok/google-api-typings-generator/runs/495738422)

**To Reproduce**
It seems like a one-off thing, I investigate every build fail and haven't found anything like this.

**Expected behavior**
It was expected for script to run every hour

## Runner Version and Platform
2.165.2

Linux

## What's not working?
```
 ! [remote rejected] types -> types (cannot lock ref 'refs/heads/types': is at 70187e254f5923245a73c42eefe7e5fa2637f4f1 but expected b990ce033f1106f6a9d5d76e7bb725b9490fc96a)
858
error: failed to push some refs to 'git@github.com:Maxim-Mazurok/google-api-typings-generator.git'
```
caused by two runs at once

## Job Log Output
Mon, 09 Mar 2020 15:04:09 GMT (https://github.com/Maxim-Mazurok/google-api-typings-generator/runs/495421149)
Mon, 09 Mar 2020 17:04:09 GMT (https://github.com/Maxim-Mazurok/google-api-typings-generator/runs/495738420)
Mon, 09 Mar 2020 17:04:08 GMT (https://github.com/Maxim-Mazurok/google-api-typings-generator/runs/495738422)

**Comment by TingluoHuang** [comment]
@andymckay do you mind take this cron trigger issue? 😄

**Comment by Maxim-Mazurok** [comment]
Off topic, but @TingluoHuang profile breaks GitHub 😅

![Screenshot_2020-03-21-12-38-23-619_com android chrome](https://user-images.githubusercontent.com/7756211/77216746-e32b5b00-6b70-11ea-95cd-a63a1ba0cba0.jpg)

**Comment by andymckay** [comment]
Thanks @Maxim-Mazurok @TingluoHuang, I've filed an issue internally with the team and we'll take a look at that.

**Comment by TingluoHuang** [comment]
close this as the internal issue has been closed.

**Comment by Maxim-Mazurok** [comment]
@TingluoHuang it would be great to know the outcome, since I haven't received any email from support regarding ticket closure.
