### ISSUE TITLE
The default shell for Windows (Powershell) does not show the stderr/stdout on exit error

### ISSUE THREAD

**Issue by evandrocoan** [actions/runner#382]
**Describe the bug**
For example, this build my which used the default shell for windows (powershell), did not showed the stdout or stderr of the error. It just says the command exited with some error code. Doing so, you have no ideia from which line the error comes from or what was happening: https://github.com/evandroforks/anki/runs/522520124?check_suite_focus=true#step:5:10
![image](https://user-images.githubusercontent.com/5332158/77189352-3096c200-6ab6-11ea-8b76-50ff5bace971.png)

This problem does not happens if I change the shell to `cmd`: https://github.com/evandroforks/anki/runs/522428852?check_suite_focus=true#step:5:26
![image](https://user-images.githubusercontent.com/5332158/77188980-9e8eb980-6ab5-11ea-8df6-4f0acd2f3bfe.png)

**Question, Bug, or Feature?**: 
"Bug"

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Comment by dakale** [comment]
The runner captures all output from the shell processes it runs and prints them to the console. In your example it looks like you are comparing two different steps: The first one using `pwsh` is "Fix choclately install" and the `cmd` step is "Set up ripgrep ... ", so I would expect them to have different outputs.

Are you sure the first step is supposed to be outputting anything?

**Comment by evandrocoan** [comment]
I am certain Powershell never ever tells me when there is an error. This was not the only case. Running the same commands locally on my computer, Powershell is quite verbose about their errors:
![image](https://user-images.githubusercontent.com/5332158/77451255-300e6c00-6dd3-11ea-9177-6c666166ea6e.png)

**Comment by pcolby** [comment]
@hbuckle wrote:
> It's something to do with the new error view in PowerShell 7.
> Try adding `$ErrorView = "NormalView"` at the top of the script

That did it for me! Thanks! :smile: 

As per the [MS docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7#errorview), `$ErrorView` is now defaulted to `ConciseView`. As @hbuckle  suggested, I simply added:

```ps1
$ErrorView = 'NormalView'
```

And now get the more detailed output I'd expected.

**Comment by evandrocoan** [comment]
@pcolby Thanks for reporting back! @alepauly, this `$ErrorView = 'NormalView'` should be the default value because it is quite frustrating having PowerShell hiding from you what went wrong.

**Comment by TingluoHuang** [comment]
@ericsciple @dakale should we set `$ErrorView = 'NormalView'` when we generate the `.ps1` script?

**Comment by fhammerl** [comment]
>Is it possible to set this for all pwsh invocations in a given workflow file? (explicit use of pwsh or by OS default) 
I'd recommend setting a job level ENV for `ErrorView`.

**Comment by fhammerl** [comment]
We have decided against modifying the `powershell` default behaviour here. As a workaround, set the ErrorView ENV to NormalView or ConciseView on the job or step level, or directly in your script.ps1 file that you're executing.
