### ISSUE TITLE
Unable to find type [Stubble.Core.Builders.StubbleBuilder]

### ISSUE THREAD

**Issue by BrightRan** [actions/runner#387]
In [this ticket](https://github.community/t5/GitHub-Actions/New-Exception-on-Running-Workflow/m-p/51304/highlight/false#M8142), the customer has an action to run a script for his custom PowerShell workflow. The script includes a step to execute the command "**`Install-Module Poshstache -Force`**" to install the module **`Poshstache`**.
This action could work fine in the past, but now it failed and from the catch error message, it shows:
```
::error file=/github/home/.local/share/powershell/Modules/Poshstache/0.1.6/ConvertTo-PoshstacheTemplate.ps1,line=67,col=24::Unable to find type [Stubble.Core.Builders.StubbleBuilder].
```
I noticed a recent reported issue [here](https://github.com/baldator/Poshstache/issues/10), it looks likes the problem occurs on **PowerShell 7**.
I also tested and tried on **PowerShell 7** and **PowerShell 5.1**, the module **`Poshstache`** can be installed successfully on **PowerShell 5.1** but failed on **PowerShell 7**, same as **chwarr** mentioned in that issue. And it seems also can work on some other versions lower than **PowerShell 7**.

I also noticed that the version of PowerShell on the GitHub-hosted Ubuntu runner has been updated from **PowerShell 6.2** to **PowerShell 7** recently. Maybe this is the reason why the customer's action could work last month but can't work now.

**Comment by Mike-E-angelo** [comment]
Looks like this issue is fundamentally due to Actions upgrading PowerShell without the explicit consent of the dependent user.  Is there a way to force PowerShell 5.1 on an image?  Is there a reason this isn't done from the outset?  It would seem that a forced upgrade to a major version would be seen as a breaking change.  Following semantic versioning, its meaning would imply exactly that.

So, ideally, something of this magnitude should also involve the explicit consent and awareness of those using it.

We are dead in the water with our release deployment until this is addressed, unfortunately. 😞

**Comment by stevo1212** [comment]
f

**Comment by stevo1212** [comment]
s

**Comment by stevo1212** [comment]
d

**Comment by stevo1212** [comment]
.

**Comment by stevo1212** [comment]
hbdbbdb

**Comment by stevo1212** [comment]
> I also noticed t

**Comment by TingluoHuang** [comment]
You might want to use self-hosted runner if you want to control what's installed on the machine the runner runs on.
https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#about-self-hosted-runners

Hosted runner provides a convenient environment for most people, but it do have the downside of losing control on the machine. :)

You can reach to https://github.com/actions/virtual-environments for more consultant. 😄

**Comment by Mike-E-angelo** [comment]
Thank you for the suggestion @TingluoHuang.  Although, that sounds like more work. 😁  

Is there not a way to "peg" a hosted image so that I am guaranteed a stable, known environment with each run in a hosted environment?

**Comment by TingluoHuang** [comment]
@Mike-E-angelo you might want to check with https://github.com/actions/virtual-environments, from my knowledge, you can pin to a particular hosted image.

**Comment by TingluoHuang** [comment]
close this, since it's not related to the runner.
