### ISSUE TITLE
Closing and opening a pull request doubles the number of jobs

### ISSUE THREAD

**Issue by evandrocoan** [actions/runner#391]
On the next screenshot, I have a pull request from (https://github.com/ankitects/anki/pull/528) which I hit the close and open button, to force jobs to re-run. But when the pull request opened, the old jobs (failed jobs) are kept on the list, while new running jobs are being added. The correct number of jobs on the next screenshot should be 7, but there are 14 jobs. I already tried refreshing the page (Ctrl+F5) twice, but they still there. Pushing new commits to the branch, remove the duplicated jobs, otherwise they stay there forever.

![image](https://user-images.githubusercontent.com/5332158/77723620-c0190500-6fcf-11ea-8267-9b86a71c3151.png)

**To Reproduce**
1. Open a pull request with few jobs (failed maybe better?)
1. Wait until the jobs finished running.
1. Now open and close the pull request.

**Comment by TingluoHuang** [comment]
@andymckay for question about check suites experience for open/close PR. 😄

**Comment by TingluoHuang** [comment]
This is fixed. Close.
