### ISSUE TITLE
machines appear to have pseudo-TTY issues

### ISSUE THREAD

**Issue by mvdan** [actions/runner#392]
**Describe the bug**

A Go test that makes use of pseudo-TTYs works fine on both Linux and Mac locally, and on Linux on Actions. However, on Mac on Actions, it fails pretty regularly, about a quarter of the time.

**To Reproduce**

1) Install Go 1.14.x
2) Clone https://github.com/mvdan/sh
3) Revert https://github.com/mvdan/sh/commit/ab43dfa8ae84bf3e4c10176a4bd4d837aa97ba9a to re-enable the flaky test
4) Run the test a bunch of times, via `go test -run TestRunnerTerminalExec/Pseudo ./interp`

You can hammer the test much harder by using [stress](https://godoc.org/golang.org/x/tools/cmd/stress). For example, to run 64 parallel processes until you hit a failure:

```
go test -vet=off -c -o test && stress -p=64 ./test -test.run TestRunnerTerminalExec/Pseudo
```

**Expected behavior**

No failures, ever. @theclapp was nice enough to run the `stress` line above, and he got zero failures even after 200k runs in over fifteen minutes. Likewise, I can't reprodue any issue on Linux.

## Runner Version and Platform

From a recent failed job on `macos-latest` today, `Current runner version: '2.165.2'`. Links below.

## What's not working?

The test fails with a weird `signal: hangup` error:

```
--- FAIL: TestRunnerTerminalExec (0.00s)
    --- FAIL: TestRunnerTerminalExec/Pseudo (0.04s)
##[error]        terminal_test.go:129: signal: hangup
FAIL
FAIL	mvdan.cc/sh/v3/interp	3.529s
```

Below is a list of such failures in the past few weeks:

* https://github.com/mvdan/sh/pull/531/checks?check_run_id=538743036
* https://github.com/mvdan/sh/runs/507984876
* https://github.com/mvdan/sh/runs/462330729

I really don't know what else to try. Given that physical Mac machines of ours can't reproduce the issue, and that the error seems to come from a OS signal, I don't know how else to proceed but to raise a bug here.

/cc @myitcv @leitzler

**Comment by mvdan** [comment]
I should clarify - there were another 4-5 failures, but those jobs were retried and succeeded, so I don't have the links anymore.

**Comment by myitcv** [comment]
We're also seeing issues with the Mac builders for the https://github.com/govim/govim project, to the extent that we had to disable the Mac tests:

https://github.com/govim/govim/commit/2d6e2fb03301c6c5f512f18b17aa0a5b00a9d575

Our tests are considerably more involved than @mvdan's so I suspect using the repro above will be simpler. But in case you need the repro steps, the linked commit gives the steps our mac builds used to follow before we disabled them.

Very happy to provide more info/help diagnose - we're just out of ideas on our side :)

**Comment by mvdan** [comment]
I forgot to link our issue about this: https://github.com/mvdan/sh/issues/513

I haven't personally written a minimal reproduction program, but I imagine it would be possible given the pseudo-TTY Go library. It's a bit hard for us to come up with a reliable reproducer, given that we can't get a shell on a machine that sees the issue.

**Comment by mvdan** [comment]
Literally half an hour after filing this issue, I've just found the exact same failure on ubuntu-latest:

https://github.com/mvdan/sh/runs/539777043?check_suite_focus=true

So maybe this isn't related to Mac after all. It does seem to happen more on that platform, though. I'm unable to repro the failure locally on Linux, too

**Comment by myitcv** [comment]
I'm starting to wonder whether this is Go version related. We only ever ran these tests on Mac using 1.14.x

**Comment by mvdan** [comment]
If that were true, wouldn't we be able to reproduce this locally? I'm completely unable to on Linux with Go 1.14.1, even after tens of thousands of runs with `stress`.

**Comment by leitzler** [comment]
Could be worth testing with the preemptive scheduler disabled in CI?

**Comment by myitcv** [comment]
Are you running the exact same Linux distro? Kernel etc?

**Comment by mvdan** [comment]
> Could be worth testing with the preemptive scheduler disabled in CI?

Proving a failure positive is trivial, but proving a negative is near impossible. I guess I could have changes like that in master for a few weeks, but it seems like shots in the dark unless we actually have a working theory.

Also, note that all three failures linked above are for Go 1.13.x, so I don't think this is a recent issue with Go 1.14. I think I've had failures with 1.14, but I don't have a link for proof right now. I've disabled that test for now to avoid more headaches, so I won't be getting more failure logs for the time being.

> Are you running the exact same Linux distro? Kernel etc?

Probably not. I haven't investigated further in this direction. I don't think Linux or the distro are to blame, given that Mac shows the exact same bug.

**Comment by TingluoHuang** [comment]
Has anyone tried to run the test on a self-hosted runner instead of the `macos-latest` hosted runner?
So we can narrow down to whether this is an issue of how runner executes your test or something on the hosted VM/image.

**Comment by mvdan** [comment]
I personally don't own any mac machines, so I can't do any debugging, sorry.

**Comment by nikola-jokic** [comment]
Hi @mvdan,

I wanted to investigate this issue again, but while looking at the repository workflow, I have noticed that macos-latest was included in the workflow [file](https://github.com/mvdan/sh/blob/master/.github/workflows/test.yml).

Could you please tell me if this issue is resolved, or should I investigate this further? 

Thank you in advance!

**Comment by nikola-jokic** [comment]
While looking again at the actions with your repository, I believe it is safe to say that this issue has been resolved. So I am closing it now but feel free to re-open if you experience the same issue again 😊

**Comment by mvdan** [comment]
Following up a bit late, but indeed, I don't think this is an issue with Actions anymore. It took me quite a bit of debugging, but I ended up with https://github.com/creack/pty/issues/127, where further investigation is taking place. Closing this seems appropriate :)

**Comment by nikola-jokic** [comment]
@mvdan, thank you for notifying us!
