### ISSUE TITLE
Report SHA when retrieving GitHub actions

### ISSUE THREAD

**Issue by jsoref** [actions/runner#398]
If you have a feature request that is relevant to this repository, the runner, then please include the information below:

**Describe the enhancement**
Currently if someone uses a github action by tag (as opposed to sha), there's no way to know what precise version of the action was used.

Please report the SHA used for each docker action – specifically in cases when actions aren't pinned to SHAs (they're often pinned to symbolic names – branches/tags)

**Code Snippet**
(Any workflow that specifies a docker action by a symbolic name.)

**Additional information**

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by jsoref** [comment]
@TingluoHuang: Is it possible to actually report this now with the introduction of `ActionDownloadInfo.ResolvedSha` in #515? I can't see any sign that this is actually surfaced, and I'd still very much like to have this information...

**Comment by TingluoHuang** [comment]
@jsoref YES. I will create a PR.

**Comment by TingluoHuang** [comment]
PR merged and the change will get release soon.

**Comment by jsoref** [comment]
@TingluoHuang: Don't suppose you have a definition of `soon`? It hasn't arrived yet. How often are releases?

**Comment by thboop** [comment]
> @TingluoHuang: Don't suppose you have a definition of `soon`? It hasn't arrived yet. How often are releases?

Hey @jsoref , this should be available for all customers by the end of this week. Its found in release [2.280.1](https://github.com/actions/runner/releases/tag/v2.280.1).

**Comment by jsoref** [comment]
Is there a way for a workflow/action to know the version of the runtime?
I can't see a way to identify it in:
https://docs.github.com/en/actions/reference/environment-variables

I understand I could programmatically retrieve the logs and parse them by hand, but....
