### ISSUE TITLE
Document the minimum dependencies necessary to use this action with custom containers

### ISSUE THREAD

**Issue by kevinburke1** [actions/runner#399]
It would be nice to know the minimum amount of software necessary to run this with a custom container. For example, this project requires `git` at at least v2.18. 

I'm currently trying to debug this failure:

```
/usr/bin/docker exec  186a95cc5746a0d66133af0ae7ec9e161d903825e4c12bdf02f1a2fcede1fe14 sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "no such file or directory": unknown
```

I suspect this means I need to add Node.js to the container image but I'm not sure.

**Comment by igagis** [comment]
@chrispat 
> we automatically inject node into the container as that is a runtime concern you should not have to deal with.

is `node` a binary executable? What if my container is `i386` or `arm`?

**Comment by nikola-jokic** [comment]
Hi @igagis! Is this issue still a problem on a newer runner version?

**Comment by igagis** [comment]
@nikola-jokic I don't know, I'm not using official runner for self-hosted machines anymore, I'm using https://github.com/ChristopherHX/github-act-runner and also I don't use javascript-based actions in my pipelines anymore. So, I cannot check, sorry.

**Comment by nikola-jokic** [comment]
Since this issue is related to actions/checkout, but we use this issue board to track issues with the runner, I am closing this issue.
