### ISSUE TITLE
IPv6 on GitHub-hosted runners

### ISSUE THREAD

**Issue by BrightRan** [actions/runner#402]
In [this ticket](https://github.community/t5/GitHub-Actions/GitHub-Actions-IPv6-Network-Issues/td-p/52085), the user is trying to reach the **`IPv6 address`** of Google by running the command "**`curl -6 https://www.google.com`**" on the **`GitHub-hosted Ubuntu runner`**, but it always failed to connect and returned the message "**`Couldn't connect to server`**".
The command "**`curl https://www.google.com`**" or "**`curl -4 https://www.google.com`**" can work fine to reach the **`IPv4 address`**.

I also tested directly ping the **`IPv6 address`** of Google via the command "**`ping6 ipv6.google.com`**", it also failed to connect and returned the message "**`connect: Network is unreachable`**".

To check whether the current Linux kernel supports **`IPv6`** via the command,
```
[ -f /proc/net/if_inet6 ] && echo 'IPv6 ready system!' || echo 'No IPv6 support found! Compile the kernel!!'
```
It returns "**`IPv6 ready system!`**", looks like **`IPv6`** is supported.
Then to check whether the **`IPv6 module`** has loaded,
```
lsmod | grep -qw ipv6 && echo "IPv6 kernel driver loaded and configured." || echo "IPv6 not configured and/or driver loaded on the system."
```
It returns "**`IPv6 not configured and/or driver loaded on the system.`**", looks like the **`IPv6 module`** is not loaded.
Load the **`IPv6 module`** and check again.
```
modprobe ipv6
lsmod | grep -qw ipv6 && echo "IPv6 kernel driver loaded and configured." || echo "IPv6 not configured and/or driver loaded on the system."
```
Still the returned result still shows that the **`IPv6 module`** is not loaded. Looks like this should be the reason for failed to reach the **`IPv6 address`**.

Why it can't load the **`IPv6 module`** on the GitHub-hosted runner? Whether this is an expected behavior for some limitations set on the hosted runners?

**Comment by TingluoHuang** [comment]
@BrightRan you want to ask at https://github.com/actions/virtual-environments
this repository is for the runner executable only. 😄

**Comment by BrightRan** [comment]
@TingluoHuang Ah, my mistake 😁, thank you for your reminder. 
I seems has no permission to transfer this issue to the repository **`actions/virtual-environments`**.
I have create a new issue in that repository. Close this issue and turn to follow the [issue-668](https://github.com/actions/virtual-environments/issues/668) in **`actions/virtual-environments`**.
