### ISSUE TITLE
./config.sh remove - Failed: Removing service

### ISSUE THREAD

**Issue by nicolas-marcq** [actions/runner#403]
**Describe the bug**
Cannot remove the runner

**To Reproduce**
Run:
```
./config.sh remove
```

**Expected behavior**
The runner is removed.

## Runner Version and Platform
2.165.2
Linux Ubuntu 18.04

## Job Log Output
```
 ./config.sh remove

# Runner removal

Removing service
Failed: Removing service
Unconfigure service first
```

I tried by manually removing the service from systemd. Still not ok.

**Comment by TingluoHuang** [comment]
try ‘sudo ./svc.sh uninstall’ first

**Comment by TingluoHuang** [comment]
close now, please reopen if suggested doesn't help.

**Comment by ffittschen** [comment]
@TingluoHuang  We still see the same error on macOS. When calling `sudo ./svc.sh uninstall`, the script just responds with _Must not run with sudo_.

**Comment by m-hilgendorf** [comment]
This is failing for me as well. `svc.sh` fails with:

```
./svc.sh uninstall
uninstalling actions.runner.jitbot-test-runner.MacCloud
stopping actions.runner.jitbot-test-runner.MacCloud
Could not find domain for port (Aqua)
Failed: failed to unload /Users/user198536/Library/LaunchAgents/actions.runner.<OMITTED>.plist
```

I've looked at #349 for a workaround but my user doesn't have sudoers permissions on this machine. 

Is there a better way to reconfigure the runner than uninstalling it?

**Comment by jgwinner** [comment]
I ran into this issue.

The fix for me was the  `sudo ./svc.sh uninstall ` command, which is not mentioned in the GitHub control panel when you try to remove the service.

I think "unconfigure service first' is slightly misleading, as the command is actually uninstall at the O/S level, and "remove" at the GitHub level.

Secondly, if you clone a VM with a GitLab runner, the two are tied at the hip; removal of one Runner screws up the other one, but I will open a second ticket for that.

         == John ==

**Comment by jgwinner** [comment]
To be clear: this should be reopened, and `sudo ./svc.sh` uninstall command, should be mentioned in the GitHub control panel when you try to remove the service.

**Comment by SeriousM** [comment]
> To be clear: this should be reopened, and `sudo ./svc.sh` uninstall command, should be mentioned in the GitHub control panel when you try to remove the service.

and should be mentioned in the error message after `./config.sh remove` fails.

```
 Unconfigure service first according to https://www.visualstudio.com/en-us/docs/build/admin/agents/v2-linux
```
is just too less information and the link results in a 404!

**Comment by asenyaev** [comment]
If you have macOS:

`launchd` can't load user's services until it logs in via GUI. That's why need to log in under the certain user via GUI, and then service can be started / deleted.

In addition, auto login feature can help in that case.
