### ISSUE TITLE
get permission denied when using docker in self-hosted server

### ISSUE THREAD

**Issue by beetlikeyg087** [actions/runner#411]
HI all, I have an issue about using docker in self-hosted server
I have a runner installed on ubuntu 18.04
The runner is running with svc.sh
And my pipeline is using  a docker
The docker is already installed in the server and can run without sudo 

```
# my pipeline
name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
    
    - name: check out
      uses: actions/checkout@v2
    
    - name: Use go docker
      uses: docker://golang:1.13.9-alpine3.10

    - name: Run go
      run: go run main.go

```

logs
```
 Pull golang:1.13.9-alpine3.109s
##[error]Docker pull failed with exit code 1
Pull down action image 'golang:1.13.9-alpine3.10'
/usr/bin/docker pull golang:1.13.9-alpine3.10
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=golang&tag=1.13.9-alpine3.10: dial unix /var/run/docker.sock: connect: permission denied
##[warning]Docker pull failed with exit code 1, back off 3.258 seconds before retry.
/usr/bin/docker pull golang:1.13.9-alpine3.10
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=golang&tag=1.13.9-alpine3.10: dial unix /var/run/docker.sock: connect: permission denied
##[warning]Docker pull failed with exit code 1, back off 5.8 seconds before retry.
/usr/bin/docker pull golang:1.13.9-alpine3.10
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=golang&tag=1.13.9-alpine3.10: dial unix /var/run/docker.sock: connect: permission denied
##[error]Docker pull failed with exit code 1
```

any idea?

**Comment by kdichev** [comment]
@beetlikeyg087 I found your issue while trying to fix the same problem I managed to make the action run the docker command itself by also restarting the service with:
```
sudo ./svc.sh stop
sudo ./svc.sh start
```
hope that helps

**Comment by beetlikeyg087** [comment]
@kdichev I downgrade to version 1.164.0 and it worked. I think it's the bug of the latest version 1.168.0

**Comment by mrturkmen06** [comment]
Seems the suggestion from @kdichev is correct, it worked me as well. I do not think there is a bug related to this particular problem in latest version. @beetlikeyg087

**Comment by TingluoHuang** [comment]
the permission denied is from docker daemon, looks like a problem with USER/GROUP permission setup, doesn't look like a runner issue to me. I am going to close the issue for now.

**Comment by dskvr** [comment]
I keep hitting this bug on self-hosted runners. I've followed all troubleshooting steps, I believe this is a bug @TingluoHuang. Otherwise, more information regarding docker setup procedure should be provided given `actions/runner`'s dependence on a functional docker daemon.

**Comment by shusson** [comment]
make sure you have given permission to the user that will run the github agent like so:

```
sudo usermod -a -G docker <USER>
```

**Comment by BiggerNoise** [comment]
One addition to @shusson 's comment. If you had to create the docker group to add your USER, then you may need to restart the docker daemon before it will grant permissions to that group.

I was running a pretty basic Ubuntu 18 on AWS and needed to do this.

**Comment by prashantkalkar** [comment]
I also had to restart the github runner service after adding the user to docker group.

**Comment by sarvpriy** [comment]
Sorry for the lame comment but I am using `./run.sh` as instructed by github while creating action runners.
When I try to run `sudo ./svc.sh start` it says
`Failed to start actions.runner.sarvpriy-sample-ms-test.sarvpriy-pc.service: Unit actions.runner.sarvpriy-sample-ms-test.sarvpriy-pc.service not found.
Failed: failed to start actions.runner.sarvpriy-sample-ms-test.sarvpriy-pc.service`

What do `svc.sh` do?

**Comment by riju-dc** [comment]
> @beetlikeyg087 I found your issue while trying to fix the same problem I managed to make the action run the docker command itself by also restarting the service with:
> 
> ```
> sudo ./svc.sh stop
> sudo ./svc.sh start
> ```
> 
> hope that helps

I can't thank you enough. I had tried everything at this point and was seriously considering setting `777` to `/var/run/docker.sock` just to see if it works. Thanks again.

**Comment by intelpljanot** [comment]
> Sorry for the lame comment but I am using `./run.sh` as instructed by github while creating action runners. When I try to run `sudo ./svc.sh start` it says `Failed to start actions.runner.sarvpriy-sample-ms-test.sarvpriy-pc.service: Unit actions.runner.sarvpriy-sample-ms-test.sarvpriy-pc.service not found. Failed: failed to start actions.runner.sarvpriy-sample-ms-test.sarvpriy-pc.service`
> 
> What do `svc.sh` do?
# firstly you need to install unit as a service, to use start stop.
sudo svc.sh install

**Comment by pantelis-karamolegkos** [comment]
What is the recommendation here? To run the `systemd` runner service as `root` or as say `ununtu` on EC2?

**Comment by pyon123** [comment]
@intelpljanot how can I install Unit as a service?

**Comment by intelpljanot** [comment]
> @intelpljanot how can I install Unit as a service?

I give you exact command in my comment :) 
`sudo svc.sh install`

**Comment by jordharrisonebay** [comment]
> > @intelpljanot how can I install Unit as a service?
> 
> I give you exact command in my comment :) `sudo svc.sh install`
`sudo ./svc.sh install` ;)

**Comment by SirojiddinYakubov** [comment]
> Same as @prashantkalkar, I had to restart the self-hosted runner service after adding the user I created the runner on the system with.
> 
> For posterity...
> 
> _(cd into your self-hosted runners' directory first obvs...)_
> 
> `sudo ./svc.sh stop` _then_ `sudo ./svc.sh start`
> 
> Bingo Bango! That's all you need!

This is a solution for me too

**Comment by rahulvikhe** [comment]
@prashantkalkar restarting runner solved my issue thanks

**Comment by Firas2515** [comment]
[](url)

**Comment by wojtekadams** [comment]
Below commands resolved my problem with **Permission denied** 
`sudo usermod -aG docker $USER`
`newgrp docker`
`sudo ./svc.sh stop`
`sudo ./svc.sh start`
