### ISSUE TITLE
How to change the name of self hosted?

### ISSUE THREAD

**Issue by granty1** [actions/runner#417]
Hello, if I add multiple self hosts to a repository, how can I distinguish these hosts? I see that the document says `self-hosted` to declare

If I have configured two private runners for a repository, both of which are Linux based, how can I specify one of them when execute jobs?

**Comment by TingluoHuang** [comment]
@granty1 we are adding customize label support for self-hosted runner, so you can tag each runner with some tag, then use the tag in `runs-on:[self-hosted, sometag]`

**Comment by lyndsey-ferguson** [comment]
One question, I saw that the new labels feature was added, can I make `sometag` be dynamic? Like create variable can be different based on whether the event is on master or a dev's branch?

`runs-on: [self-hosted, is_master]`
?

**Comment by TingluoHuang** [comment]
@lyndsey-ferguson I think you can, but you might need to have 2 jobs, the first job needs to set the dynamic tag as job outputs, then the second job can consume it in `runs-on`.

**Comment by TingluoHuang** [comment]
I am going to close this issue since the original question has been answered.

**Comment by pksinghjft** [comment]
> @lyndsey-ferguson I think you can, but you might need to have 2 jobs, the first job needs to set the dynamic tag as job outputs, then the second job can consume it in `runs-on`.

Any sample code for this?

**Comment by lyndsey-ferguson** [comment]
@pksinghjft you're asking @TingluoHuang for the sample code, correct?

**Comment by besmiralia** [comment]
Here is some sample code. I have tagged a runner as `app-staging`
![image](https://user-images.githubusercontent.com/8680949/191966507-4968f60b-c555-4871-8b9a-2277545bbf89.png)

**Comment by saminwankwo** [comment]
Any one here knows, how i can change a runner name?,

**Comment by besmiralia** [comment]
@saminwankwo Currently, you have to uninstall and reinstall it. I haven't found a way to rename it. But, you can add more labels and refer to it by the new label instead.

**Comment by saminwankwo** [comment]
> @saminwankwo Currently, you have to uninstall and reinstall it. I haven't found a way to rename it. But, you can add more labels and refer to it by the new label instead.

Thank you, That's What i did do
