### ISSUE TITLE
How to stop self-updating

### ISSUE THREAD

**Issue by summerwind** [actions/runner#431]
Is there a good way to stop runner's self-updating behavior?

I'm running self-hosted runners as a Pod on Kubernetes. When a new version of self-hosted runner was released, runner tried to update itself. I think that this behavior may cause unintended problems as the Runner is updated even though the administrator does not want it.

**Comment by SvanBoxel** [comment]
Related: https://github.com/actions/runner/issues/246

**Comment by bryanmacfarlane** [comment]
This is a dupe of #246 with most of the discussion captured there.
