### ISSUE TITLE
Tag releases correctly

### ISSUE THREAD

**Issue by arhue** [actions/runner#445]
**Describe the bug**
Releases are being incorrectly tagged, breaking Docker flow.

**To Reproduce**
1. Go to https://github.com/actions/runner/releases/tag/v2.169.1
2. See `Pre-release` when the version is not pre-release for x64.

**Expected behavior**
Releases should be marked with the correct tag.

This is important for me because I am referencing the latest release in my Docker build with `curl -sL https://api.github.com/repos/actions/runner/releases/latest | jq -r '.assets[].browser_download_url' | grep linux-x64`. There is a forced update when Github releases an update, which makes the self hosted runners stop working unless I update the Docker container, which is fine. I am relying on versions being tagged correctly to pull the correct build.

I am currently using `https://api.github.com/repos/actions/runner/releases` to pull the top most release, but this sometimes may actually be a pre-release.

**Comment by TingluoHuang** [comment]
I flip the `pre-release` tag to `release` when the runner deploys to all repositories across GitHub.
We have 3 deployment rings, (0, 1, 2, 3), `0` is `GitHub` internal, `1`/`2`/`3` for public customers, and more customers in outer rings.

you might want to use the following API to figure out what runner version available for your repository.
https://developer.github.com/v3/actions/self-hosted-runners/#list-runner-applications-for-a-repository

**Comment by arhue** [comment]
Makes sense. Thanks for the explanation. That API worked well. Thanks!
