### ISSUE TITLE
Please have JobRunner load /etc/environment from the runner

### ISSUE THREAD

**Issue by rbellamy** [actions/runner#455]
**Describe the enhancement**
The JobRunner should load the contents of `/etc/environment` at startup. I realize the environment is launched with `--norc`: https://github.com/actions/runner/blob/6c70d53eead402ba5d53676d6ed649a04e219c9b/src/Runner.Worker/Handlers/ScriptHandlerHelpers.cs#L14 

It is surprising to realize there is a slew of environment variables and tools pre-installed by the runner that is unavailable via `${{ env.* }}`.

**Additional information**
Up until now, I always assumed that whatever environment the runner was running in would be populated into the `jobs.<job id>.env` dictionary. I've just run some tests, and this does not seem to be the case.

The GitHub hosted runners come with a slew of environment variables via the /etc/environment file. Of particular interest to me are the various `JAVA_HOME*` variables, which point to JDKs (8, 11, 13, etc), with the default JAVA_HOME pointing to 11 (e.g. `JAVA_HOME=/usr/lib/jvm/zulu-8-azure-amd64`). I expected the following code to work, but it doesn't:
 
```yaml
- name: Build with Maven
  env:
    JAVA_HOME: ${{ env.JAVA_HOME_8 }}
  runs: mvn -DskipTests compile
```

There are two surprises here:

1. `${{ env.JAVA_HOME_8 }}` is empty, which causes,
2. `$JAVA_HOME` to be UNSET, so now it's empty too.

**NOTE: `$JAVA_HOME_8` IS SET IN THE ENVIRONMENT.**

You can see an example of what I'm talking about here: https://github.com/terradatum/test-workflows/actions. Specifically, review the "Debug Environment" step here: https://github.com/terradatum/test-workflows/runs/613285323?check_suite_focus=true.

**I'd like to forward a feature request that `${{ env.* }}` be populated with the current environment at startup.**

Is the expectation that I must populate `JAVA_HOME_8` in `${{ env.JAVA_HOME_8}}` myself? That seems silly, since the purpose of the `set-env` command is to populate BOTH the environment and `${{ env.* }}`:

```yaml
- name: populate JAVA_HOME_8
  runs: |
    ::set-env name=JAVA_HOME_8::$JAVA_HOME_8
```

**Comment by TingluoHuang** [comment]
@rbellamy here is the reason we don't populate environment variables. 😄 
https://github.com/actions/runner/blob/master/docs/adrs/0278-env-context.md#dont-populate-the-env-context-with-environment-variables-from-runner-machine

**Comment by rbellamy** [comment]
Thanks so much for your answer! So the choice was deliberate. :)
