### ISSUE TITLE
Add configurable cancel timeout parameter

### ISSUE THREAD

**Issue by t3mi** [actions/runner#464]
**Describe the enhancement**
For our case we need to do some infrastructure cleanup (which was provisioned for the test runs in the same workflow) but with current static 5 min cancelation timeout we unable to do it in time if deployment fails. It would be great if there would be a configurable parameter added, at least for self-hosted runners, which will cover such scenario.

**Code Snippet**
```
...
  runs-on: self-hosted
    timeout-minutes: 60
    cancel-timeout-minutes: 15
    defaults:
...
```
**Current behaviour**
Runner `agent name` did not respond to a cancelation request with 00:05:00.

**Comment by TingluoHuang** [comment]
@chrispat from the product team for feedback.

**Comment by t3mi** [comment]
Are there any progress for this to be added to the roadmap?

**Comment by jasongornall** [comment]
bumping this

**Comment by nikola-jokic** [comment]
Hey @t3mi,

Could you please post this enhancement on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages)? This enhancement is not scoped to the runner itself, it affects the platform more generally. 

Using this forum can help us prioritize features and ensure that the correct team sees them.

I will close this issue now since we are trying to scope issues related to the runner itself. For more information on this policy please [read our contribution guidelines](https://github.com/actions/runner#contribute).

**Comment by t3mi** [comment]
Created a discussion [#42850](https://github.com/orgs/community/discussions/42850)

**Comment by thiagomarafeli** [comment]
Guys, it seems to me that this feature was implemented, right? But, although I found it on VSCode Github Actions autocomplete, in Github online editor it says "Unknown key" and I can't find any documentation of it in the [syntax docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions).

So, overall, is this implemented? If it is, there seems to be no documentation and it should have at least some description of what it actually does.

**Comment by bryan-bar** [comment]
> Guys, it seems to me that this feature was implemented, right? But, although I found it on VSCode Github Actions autocomplete, in Github online editor it says "Unknown key" and I can't find any documentation of it in the [syntax docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions).
> 
> So, overall, is this implemented? If it is, there seems to be no documentation and it should have at least some description of what it actually does.

I do not see updated docs on the timeout but I see that `actions/languageservices` uses `cancel-timeout-minutes`: https://github.com/actions/languageservices/blob/main/workflow-parser/testdata/reader/job-cancel-timeout-minutes.yml#L6-L21
