### ISSUE TITLE
Self Hosted Runner In Service Mode Not Working On MacOS Catalina

### ISSUE THREAD

**Issue by vsaravind007** [actions/runner#481]
**Describe the bug**
When running as service, runner is not picking up jobs & Github Actions UI is waiting for the job to start. Setup was done and the runner works correctly in interactive mode `./run.sh`. There are no installation errors or service errors, service status shows 'running', but will never pickup a job.

**To Reproduce**
1. Go to runner folder, run `./svc.sh start` 
2. Output will show the following 
```
starting actions.runner.diagnal.Aravind-Mac-Mini
status actions.runner.diagnal.Aravind-Mac-Mini:

/Users/aravind/Library/LaunchAgents/actions.runner.diagnal.Aravind-Mac-Mini.plist

Started:
1025 0 actions.runner.diagnal.Aravind-Mac-Mini
```
3. Trigger a workflow, it'll never pickup the job.
4. Checking status `./svc.sh status` will return the following:
```
status actions.runner.diagnal.Aravind-Mac-Mini:

/Users/aravind/Library/LaunchAgents/actions.runner.diagnal.Aravind-Mac-Mini.plist

Started:
- 1025 actions.runner.diagnal.Aravind-Mac-Mini

```

**Expected behavior**
Runner should work in service mode as well.

## Runner Version and Platform
Runner version 2.169.1

OS Version: MacOS Catalina 10.15.4

**Comment by TingluoHuang** [comment]
@vsaravind007 can you check `/Users/aravind/Library/Logs/actions.runner.diagnal.Aravind-Mac-Mini`? there should be 2 log files that might contain extra log info.

**Comment by wagenet** [comment]
I have a similar situation except, in my case, it picks up some jobs, just not consistently. I currently have jobs waiting to run and the runner isn't running anything. There's nothing unusual in the logs.

**Comment by vsaravind007** [comment]
> @vsaravind007 can you check `/Users/aravind/Library/Logs/actions.runner.diagnal.Aravind-Mac-Mini`? there should be 2 log files that might contain extra log info.

@TingluoHuang Yes, there are errors, `stderr.log`

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
/bin/bash: /Users/aravind/Desktop/actions-runner/runsvc.sh: Operation not permitted
```
This is a fresh installation of MacOS, any ideas ?

**Comment by TingluoHuang** [comment]
@vsaravind007 check this: https://stackoverflow.com/a/61533355

**Comment by EfficientSetting** [comment]
I have the very same issue as originally posted here. Most jobs aren't picked up, the runner is marked as "Active" but then never updated.

I don't see anything in my stderr log file and so it doesn't seem to be a permissions issue.
What I'm seeing in the _diag folder are only warnings that a PATCH requested failed and this

`[2020-07-23 16:07:24Z WARN GitHubActionsService] Authentication failed with status code 401.`

I'd love to get this to work since GitHub Actions is otherwise useless to us

**Comment by GeorgeTsiokos** [comment]
Try installing and configuring the runner in `/System/Volumes/Data/`

**Comment by thboop** [comment]
Are you still seeing this issue @vsaravind007

**Comment by thboop** [comment]
Going to close this out, but if you see this again please let me know and we can reopen it!
