### ISSUE TITLE
Matrix Jobs - Sorted for start order?

### ISSUE THREAD

**Issue by MSP-Greg** [actions/runner#483]
**Describe the enhancement**

When running a workflow file, the order of jobs appears to be sorted regarding the starting of jobs.

The jobs as listed on the left side of the web UI appear as they are listed in the matrix.  Conversely, jobs seem to actually start based on an alpha sort?

I noticed this when trying to shorten total CI time.  The workflow has more than 5 macOS jobs, and one job takes about twice the time that the others take.  It also sorts last.  If it's the last job, total test time is 3x.  If I can force it to run first, test time would be 2x.

Originally, it was at the end of the matrix.  When I moved it to the beginning, nothing changed.

**Code Snippet**

Original matrix - truffleruby-head is the 2x job and starts last
```
ruby: [ 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, head, jruby, truffleruby-head ]
```
Modified matrix - truffleruby-head still starts last, but is listed first in the job list
```
ruby: [ truffleruby-head, jruby, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, head ]
```

**Comment by TingluoHuang** [comment]
@ericsciple for an idea.
I guess the UI and the runtime execution engine are not lines up on sorting. 😢

**Comment by ericsciple** [comment]
The matrix is generated in a predictable order, based on how the defined order.

Something in the orchestration layer doesn't respect the order.

**Comment by mmoayyed** [comment]
I can also confirm that order of jobs seems to be determined alphabetically, and not based on how they are defined. 

According to the documentation:

> The order that you define a matrix matters. The first option you define will be the first job that runs in your workflow.

...which isn't true.

For example:

![image](https://user-images.githubusercontent.com/1205228/90492522-87342500-e156-11ea-900b-3bdeca8e4194.png)


The above images show a matrix running 6 jobs. While `simple` is defined as the first job in the matrix, it's not run. `groovy` or `filesystem` jobs, etc are executing since alphabetically they come before `simple`. Likewise, the other two jobs beginning with `w` do always start last regardless of their position in the matrix.

**Comment by denzhel** [comment]
I have the same issue as well.

We're working with Terraform and different workspaces using the same repo:

```
# Support multiple workspaces
strategy:
   matrix:
      workspace: [dev-us-east-1, stg-us-west-2]
```

It is documented that order matters, however, it is chosen randomly when I use it:
```
- name: Change Terraform workspace
      run: terraform workspace select ${{ matrix.workspace }}
      if: steps.check.outputs.triggered == 'true'
```

Instead of running the Terraform process on dev-XXX first, it runs randomly and sometimes chooses stg-XXX first

**Comment by denzhel** [comment]
Please ? can anyone help ! We will owe you our lives !

**Comment by denzhel** [comment]
![](https://media.giphy.com/media/fdLR6LGwAiVNhGQNvf/giphy.gif)

**Comment by MSP-Greg** [comment]
There are several ways workflows can vary.  Just to clarify:

Assuming:

1. Workflow is run with `fail-fast: false` in `strategy:`
2. Workflow jobs are independent, ie, not dependent on other jobs finishing first.
3. There are limits as to how many jobs can run concurrently, in particular, macOS.

Given the above, a workflow will complete in shortest amount of time if the number of jobs running concurrently is maximized.

I've seen several workflows that often end with one or two jobs running, simply because of the alpha sort.  If these jobs could be pushed to the start of the 'job list', the workflow would complete faster.

This is certainly a benefit to users, and possibly to GitHub/MSFT...

Just to be clear, this won't shorten the total combined job time, but it can shorten the workflow time.

**Comment by denzhel** [comment]
@MSP-Greg  How does it solve the issue I'm having above and in the bug I opened ?
#703

**Comment by MSP-Greg** [comment]
@denzhel

I wasn't sure if my original post clarified the issue that some have.  I believe your issue is also valid, but doesn't meet the 2nd criteria?

**Comment by denzhel** [comment]
@MSP-Greg 

Correct. My issue deals with jobs in a workflow that other jobs are depended on it.

**Comment by JRubics** [comment]
Is there any progress on this issue? I also have it

**Comment by ruvceskistefan** [comment]
Thank you for your interest in the runner application and taking the time to provide your valuable feedback. We kindly ask you to redirect this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests in GitHub Actions. For more information on this policy please [read our contribution guidelines](https://github.com/actions/runner#contribute).
