### ISSUE TITLE
UnprocessableEntity from 'POST https://api.github.com/repos/myorganization/myproject/actions-runners/registration'

### ISSUE THREAD

**Issue by timharris777** [actions/runner#487]
**Describe the bug**

1. Run Create registration token method of github API
2. Pass token from the response to config.sh
3. Runner authentication fails with message
```
Http response code: UnprocessableEntity from 'POST https://api.github.com/repos/myorganization/myproject/actions-runners/registration'
{"message":"Validation Failed","documentation_url":"https://developer.github.com/v3"}
Response status code does not indicate success: 422 (Unprocessable Entity).
An error occurred: Not configured
```

This error does not reproduce if I push the button Add runner from project settings before any API calls. After pushing this button runner authentication works pretty well event with tokens generated with API. For me it looks like this button also changes some flag in project settings.

**To Reproduce**
1. Create a new repo
2. Call the rest api to create a registration token for a new runner
3. Use that token with config.sh in to setup and run a new runner in the recently created repo.
4. The error will be given.

**Expected behavior**
I would expect to be able to do the above steps without having to manually go into the interface first and click the "Add Runner" button in the repo settings.

## Runner Version and Platform
Any version

OS of the machine running the runner? OSX/Windows/Linux/...
Any OS

Here is a thread in the community with the exact same issue:
https://github.community/t5/GitHub-Actions/Self-hosted-runners-API-Unprocessable-Entity/td-p/47098

**Comment by timharris777** [comment]
This might be related but if I try to get the /actions/runners/downloads endpoint for any newly created repo I'm getting a blank response. Seems like there is something that does not initialize until that button is clicked in the ui.

**Comment by timharris777** [comment]
Ok, so I have figured out that if I add a `.github/workflows/test.yaml` file to the repo the  /actions/runners/downloads api responds properly and the registration works properly as well.

Very strange... seems like the there is some kind of check in the background that needs to test positive before the registration will work or the  /actions/runners/downloads api will respond.

Please help as this is breaking our ability to automate github self-hosted runners.

**Comment by TingluoHuang** [comment]
@joshmgross might be able to help on this.

**Comment by joshmgross** [comment]
👋 Hey @timharris777, thanks for reporting this. I've filed an issue internally to get this fixed.

**Comment by timharris777** [comment]
Thanks @joshmgross , can't wait for the fix! I'm currently having to go click that button in the settings page for every repository in our org that wants to use our automated self-hosted runner solution.

Looking forward to not having to make the click anymore! :-)

**Comment by timharris777** [comment]
@tpinniger, adding you to this issue as you will be interested when it's fixed.

**Comment by rngadam** [comment]
Same problem here. Our automated registration script worked until last week. 

Our automated process to add a repo is:

1) setup and register agent
2) add workflow to repo and commit

...now seems to want:

1) add workflow to repo
2) setup and register agent

**Comment by joshmgross** [comment]
👋  This issue should now be fixed. Runner registration should now work correctly for new repositories that have not used Actions yet or created any workflows.

Thank you for finding this issue.
