### ISSUE TITLE
Post step title prefixed with "Post Pre"

### ISSUE THREAD

**Issue by hashtagchris** [actions/runner#489]
**Describe the bug**
When an action has both `pre` and `post` stages defined, the `post` step title is prefixed with "Post Pre" instead of just "Post".

**To Reproduce**
1. Create a workflow that executes an action with both `pre` and `post` stages. [Example](https://github.com/h10s/test-workflows/blob/master/.github/workflows/test-simple-actions.yml#L28-L30) 
1. Execute that workflow.
1. Inspect the name of the action's post step.

**Expected behavior**
The `post` step title is prefixed with just "Post".

## Runner Version and Platform
Version of your runner? 2.262.1

OS of the machine running the runner? macOS 10.14.6

## What's not working?
Please include error messages and screenshots.

From https://github.com/h10s/test-workflows/runs/690167853?check_suite_focus=true:

![image](https://user-images.githubusercontent.com/7145717/82368525-95519880-99e3-11ea-813d-3a47d60328b9.png)

**Comment by TingluoHuang** [comment]
fixed.
