### ISSUE TITLE
Issue with supporting Cyrillic characters in the runner.

### ISSUE THREAD

**Issue by gigi1988b** [actions/runner#501]
**Describe the bug**
Issue with supporting Cyrillic characters in the runner. Any character causes an error  

**To Reproduce**  
1. Push file with Cyrillic characters;  
2. Run tests  
3. See error "unmappable character for encoding ASCII"  

## Runner Version and Platform
Current runner version: '2.262.1'  
Operating System  
  Ubuntu  
  18.04.4  
  LTS  
Virtual Environment  
  Environment: ubuntu-18.04  
  Version: 20200518.1  
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20200518.1/images/linux/Ubuntu1804-README.md  

OS of the machine running the runner? Linux ubuntu   18.04.4  

## What's not working?  
"unmappable character for encoding ASCII" if in file has cyrillic characters   
https://prnt.sc/sm1f0x

**Comment by TingluoHuang** [comment]
@gigi1988b doesn't feel like a runner issue, more like a Java issue or environment issue. 😄 
maybe try `export JAVA_OPTS=-Dfile.encoding=UTF8` to make Java use UTF-8 to read files.  
I am not a Java expert, just searched online for this hint, might be wrong.

https://github.com/broadinstitute/gatk/issues/4434
