### ISSUE TITLE
secrets handling in log

### ISSUE THREAD

**Issue by hholst80** [actions/runner#507]
A picture says it all.

![image](https://user-images.githubusercontent.com/6200749/82953788-b1d56e00-9fab-11ea-940a-6c7038f880e7.png)

**Comment by TingluoHuang** [comment]
Do you have ‘docker’ as secret?

**Comment by hholst80** [comment]
Either that, or as username. That the not-to-hard-to-guess conclusion. ;-)

I think it would make more sense that only {{ secrets }} are replaced verbatim with `***` in the log. What is the use-case for a global search-replace application of all secrets? What program emits the password to stdout? (besides gdm).

**Comment by TingluoHuang** [comment]
@hholst80 sorry, I didn't quite get your suggestion.

secrets can be leaked in many inattention ways, ex
- Pass secret as args to cli, the full commandline invocation may miss quote `space` or escape special character which causes the shell to error and echo back the input.
- Debug mode of tools, like CURL/Git, that prints HTTP auth header.
- Error messages from different cli may contain part of your secret, like Git.

**Comment by hholst80** [comment]
So you say that git can emit the password verbatim on error? Can you provide an example?

**Comment by hholst80** [comment]
That is unlikely that git will spit out auth credentials in any recent release. 

My comment is not a question as much as it is a comment that the current "solution" is a hack that solves nothing. There is no current use case / problem that it actually solves. If anything it leaks the information that my secret is "docker". Thus, the current behavior makes things worse from a security point of view.

**Comment by ericsciple** [comment]
The current runner solution is designed to help prevent all workflow secrets from being printed. One example is debug tracing like `set -x` in bash. The trade off is that weak secrets could get incorrectly masked in other places.

**Comment by rmehner** [comment]
👋  GitHub support got me here, sorry for necroposting. We have another example:

A secret is named `FOOBAR_ROLLBAR_ACCESS_TOKEN`

Somewhere in a script we do a curl request to the actual domain of the application, which has the `foobar` in the domain, e.g.: `curl -v https://foobar.com`.

In the log output it's masked with asterisks now:

`https://***.com`

Is there a way to turn off this feature, at least temporarily? It makes debugging actions super hard right now and in a private repo I'm willing to take the risk.

Or is there any documentation on how the masking exactly works, so we could rename the secrets accordingly to make sure they don't clash and trigger this?

Thanks in advance!

**Comment by rmehner** [comment]
In another repo we see the following in the log:

`importing cache manifest from docker.pkg.github.com/rmehner/***/***-main:latest`

The *** mask the name of the repo, which is *not* anywhere in the secrets, neither in keys nor in values. Is that intentional?

**Comment by kris-luminar** [comment]
Encountering this issue as well. Logged it in https://github.com/cypress-io/github-action/issues/622 .

**Comment by kris-luminar** [comment]
So it looks my issue is that I have a GH secret with the value '2' and GH redacts any text in logs that match the value of GH secrets. From [a SO comment](https://stackoverflow.com/questions/61308519/why-the-action-cannot-access-secrets#comment108503369_61308519) (italics added).

> Any secret value (as well as certain encodings, such as Base64, of secret values) is scrubbed from the output and replaced with asterisks in the logs, which is a best security practice. This is true no matter how you render them: *if the log text matches a secret, it's scrubbed*. They are still accessible to your scripts and workflows, but cannot be viewed.

**Comment by jroes** [comment]
I've found a particularly problematic case here - I have some secret with the value 1, and I get a ton of asterisks (as intended). However, one of my actions creates review apps, and because there's a 1 in the name of the app (based on PR #), this breaks my PR apps.

I would classify this behavior as a bug at this point. Perhaps a simple fix would be the secret needs to be > 1 character in length to be masked?

**Comment by tking16** [comment]
This also breaks Markdown used for custom [$GITHUB_STEP_SUMMARY](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) e.g. if a secret contains a rounded bracket your links will looks as follows:
`[Link to github](www.github.com**`

**Comment by tking16** [comment]
Honestly, what is the point in an "issues" page when the team **never** answers..?
