### ISSUE TITLE
Get "Name or service not known" error when trying to install self-hosted runner

### ISSUE THREAD

**Issue by BrightRan** [actions/runner#511]
In [this community ticket](https://github.community/t/selfhosted-action-runner-error/115790), the users are trying to install a self-hosted runner on Linux. But they always get the following error:
```
# Authentication
Name or service not known
```
This is the first runner they are setting up on this machine.

**Comment by TingluoHuang** [comment]
@BrightRan make sure customer has access to
```
github.com
api.github.com
*.actions.githubusercontent.com
```

https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#communication-between-self-hosted-runners-and-github
