### ISSUE TITLE
Enabling Docker Daemon With experimental features

### ISSUE THREAD

**Issue by Accipiter7** [actions/runner#533]
Currently github runners don't support
docker build --squash flags as it required docker daemon  with experimental features enabled.

While it can be done manually using following commands on any linux machine.

sudo echo "{
"experimental": true
}
" >> /etc/docker/daemon.json

sudo systemctl restart docker.service

But however i got Permission Denied.

**Comment by TingluoHuang** [comment]
@Accipiter7 check https://askubuntu.com/a/103644
you need to `sudo bash -c 'echo "{\"experimental\": true}" >> /etc/docker/daemon.json'`

you might want to check whether `/etc/docker/daemon.json` content some other settings first.

**Comment by Accipiter7** [comment]
thnx for helping issue solve now.
cat /etc/docker/daemon.json resulted in 
{ "cgroup-parent": "/actions_job" }

Hence  using  following commands solves my issue 

sudo bash -c 'echo "{ \"cgroup-parent\": \"/actions_job\",\"experimental\":true}" > /etc/docker/daemon.json'

sudo systemctl restart docker.service

**Comment by Accipiter7** [comment]
Solved so closing
