### ISSUE TITLE
Add libicu version in `installdependencies.sh` for Ubuntu 20.04 focal

### ISSUE THREAD

**Issue by shivammathur** [actions/runner#534]
**Describe the bug**
Currently there is no `libicu` version in `installdependencies.sh` for Ubuntu 20.04 focal.
https://github.com/actions/runner/blob/97883c8cd503e32d86af6c016b6c1eb9c4ab80be/src/Misc/layoutbin/installdependencies.sh#L74
https://github.com/actions/runner/blob/97883c8cd503e32d86af6c016b6c1eb9c4ab80be/src/Misc/layoutbin/installdependencies.sh#L103

**To Reproduce**
Setup the runner on Ubuntu 20.04 focal.

**Expected behavior**
`libicu66` should be installed on Ubuntu 20.04 by `installdependencies.sh`. 

The script can install `libicu-dev` instead of attempting to install different versions of `libicu` or use a regex so that `apt` picks the correct version of `libicu`.

**Runner Version and Platform**
2.263.0

**OS of the machine running the runner?**
Ubuntu 20.04

**What's not working?**
`installdependencies.sh` does not have `libicu` version for Ubuntu 20.04 which prevents the runner from starting.

**Comment by TingluoHuang** [comment]
@shivammathur thanks for reporting. 🎉
