### ISSUE TITLE
Runner version to be present in addition to labels

### ISSUE THREAD

**Issue by t3mi** [actions/runner#537]
**Describe the enhancement**

For me as a user it would be very helpful to see a version of the runner in the settings actions tab without going to check the latest job which run on it or directly connecting to the box.

**Comment by nikola-jokic** [comment]
Hey @t3mi,

Can you please post this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages)? This enhancement is not scoped to the runner, it affects the platform more generally. Using this forum will help us route your request to the correct team. 

Sorry for the delay :disappointed:

**Comment by t3mi** [comment]
Created a discussion [#42851](https://github.com/orgs/community/discussions/42851)
