### ISSUE TITLE
I'm geting an error when run windows seft-hosted docker script

### ISSUE THREAD

**Issue by phivanloi** [actions/runner#542]
-My docker-compose config
![image](https://user-images.githubusercontent.com/12540136/84562249-2d416880-ad7d-11ea-8148-2cbedd937b25.png)

- My github action config
![image](https://user-images.githubusercontent.com/12540136/84562233-0daa4000-ad7d-11ea-9e0e-318c5fb0a3a4.png)

-But im geting error
![image](https://user-images.githubusercontent.com/12540136/84562271-6c6fb980-ad7d-11ea-94ca-c36c3ea0e30d.png)

When i run docker-compose up in my windows server it not get error.
![image](https://user-images.githubusercontent.com/12540136/84562304-be184400-ad7d-11ea-9d2f-2fd59952bc97.png)

**Comment by TingluoHuang** [comment]
Can you try use cmd shell?
Run: your script 
Shell: cmd

**Comment by phivanloi** [comment]
Thank TinglueHuang.
I'm try it on cmd shell, and result success. Here my script result
![image](https://user-images.githubusercontent.com/12540136/84584110-ced2c380-ae2a-11ea-8b4e-3428dfc1617c.png)
I think my githup action run on windows power shell by default.

**Comment by TingluoHuang** [comment]
@phivanloi I mean in your yaml file
```yaml
- run: docker-compose update -d --build
  shell: cmd
```

**Comment by phivanloi** [comment]
Oh. this work. Thank TingluoHuang. 
![image](https://user-images.githubusercontent.com/12540136/84611522-5599a600-aee8-11ea-9434-59de3d713d6a.png)
