### ISSUE TITLE
GitHub actions runner worker process crashed with error: System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/jworks/_tool'

### ISSUE THREAD

**Issue by yaananth** [actions/runner#544]
Internal telemetry:

```
ProductTrace
| where OrchestrationId =~ "0f26db4e-bfa8-4131-92d1-49477a7f5d6a.pipeline.__default"
| project PreciseTimeStamp, Message
```

Internal [alert](https://vstskalypso.dev.azure.com/mseng//summary?containerId=69c38056-8eab-4174-93da-37282b4c2c33&selectedPage=summary&monitorId=8861a99d-1e6b-4203-b9a5-4c80388d5cbd&runId=85842087)

Url: https://github.com/tsukiy0/jworks/actions/runs/133926164

```
GitHub actions runner worker process crashed with error: System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/jworks/_tool'. at System.IO.FileSystem.CreateDirectory(String fullPath) at System.IO.Directory.CreateDirectory(String path) at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken) at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken) at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut) at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

**Comment by uwehdaub** [comment]
We had the same problem 5 times in the last two days.
We are using runner 2.278.0 on LINUX.

Maybe our setup of self-hosted runners is resposible to trigger this problem.
We run the runner inside docker on LINUX VMs and we use each runner only for one WF step.
Then the runner is de-registered and a new one is started.
(This should address the problem of shared runner state.)

BR Uwe Daub

**Comment by uwehdaub** [comment]
And again another occurrence today.

**Comment by uwehdaub** [comment]
To get a higher priority I've created this:
https://enterprise.githubsupport.com/hc/en-us/requests/1133265

**Comment by TingluoHuang** [comment]
@uwehdaub do you have any runner diagnostic log from runner inside your container?
I am seeing a bunch of these with similar path naming patterns and assume that is from yours? 😄 
```
GitHub actions runner worker process crashed with error: System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp-github-runner/metro-digital-inner-source-TG9K0Ez1jWxqW/_temp'.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at GitHub.Runner.Worker.TempDirectoryManager.InitializeTempDirectory(IExecutionContext jobContext)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
```

Do you happen to map the same path on the host into different containers? base on MSDN the error means
```
DirectoryNotFoundException
The specified path is invalid (for example, it is on an unmapped drive).
```
So I wonder some of your container volume maps caused the trouble.

**Comment by uwehdaub** [comment]
Every container gets its own subdirectory mapped. The common root is `/tmp-github-runner`.
The name of the subdirectory is composed of the org name and a random string comming from `/dev/urandom` (of length 13).

So the only potential problem could be, that `/dev/urandom` generates the two strings, starting with the some prefix.
But I can change the runner start script, to address this potential problem.

**Comment by uwehdaub** [comment]
Now, that I had a fresh look on the startup script, I noticed, that we have the following in:
`docker run -v ${WORKDIR}:${WORKDIR}` but the `${WORKDIR}` where never created before.

Now I'm not wondering why it's failing from time to time, but I'm wondering, why it's working most of the time ... :-)

**Comment by uwehdaub** [comment]
We fixed our setup script by creating the `WORKDIR` before we mount it in the docker command.
Nevertheless we problem stays persistent.
We still get from time to the the error message e.g.
```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp-github-runner/metro-digital-inner-source-FcmpXjbA9dmSY/_temp'.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at GitHub.Runner.Worker.TempDirectoryManager.InitializeTempDirectory(IExecutionContext jobContext)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
   at GitHub.Runner.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```
Of course the path changes, because every runner gets its own working directory.

Any hints, how we could solve this problem?

**Comment by uwehdaub** [comment]
We finally solved the problem. It was introduced by a cleanup script, which deleted the whole base directory `/tmp-github-runner`.

**Comment by nikola-jokic** [comment]
Hi @uwehdaub,

I will now close this issue since it seems like this matter is resolved 😊. If you experience the same issue, please, feel free to re-open it, or open a new issue.
