### ISSUE TITLE
on.<push|pull_request>.path ignores provided "path" and triggers for any PR.

### ISSUE THREAD

**Issue by dbabokin** [actions/runner#545]
``on.<push|pull_request>.path`` ignores provided "path" and triggers for any PR and any push.

Here's the workflow, which doesn't honor the "path" for PRs:
[https://github.com/ispc/ispc/blob/master/.github/workflows/rebuild-llvm10.yml](https://github.com/ispc/ispc/blob/master/.github/workflows/rebuild-llvm10.yml)

It does trigger workflow for any commit to master and any PR, ignoring providing path ``"llvm_patches/*10_0*"``.

**Comment by dbabokin** [comment]
Any suggestions how to debug the issue?

**Comment by TingluoHuang** [comment]
@andymckay can someone from your team take a look at this?

**Comment by hfaulds** [comment]
I opened a PR whith what I think is the fix https://github.com/ispc/ispc/pull/1804

**Comment by dbabokin** [comment]
Thank you for catching this! I feel stupid for this typo. I've looked at this line many times, but it looked perfectly correct to me.

Why this was not caught as syntax problem? Can/should this be fixed?

**Comment by TingluoHuang** [comment]
the editor shows the error, actually. 😄 
![image](https://user-images.githubusercontent.com/1750815/85437932-54582100-b559-11ea-977d-841461afd3ff.png)

**Comment by dbabokin** [comment]
Right, but I don't use the editor. For other syntax problems I had Actions failure, pointing to the problem. Like here: https://github.com/dbabokin/ispc/actions/runs/131860211

So, it's kind of surprising that it doesn't catch all syntax problems.

**Comment by TingluoHuang** [comment]
@hfaulds already created an internal issue to track that problem. 🎉

**Comment by hfaulds** [comment]
@dbabokin sorry again about this. It's very confusing that unknown attributes here are just ignored. There should at the very least be a warning (as an annotation). I only noticed the problem because I forked the repo and opened up the in-browser editor, if I had chosen to edit it locally then I doubt I would have noticed ❤️

**Comment by akashagarwal7** [comment]
Hi @TingluoHuang! Was this ever fixed? I have similar behaviour with `on.<push|pull_request>.path-ignores` not ignoring markdown files specified like so:
```yml
on:
  pull_request:
    branches:
      - "*"
    # Ignore if a commit only includes changes to a Markdown file.
    paths-ignore:
      - "**/*.md"
```

The `push` equivalent seems to be working flawlessly. Happy to create a new issue if need be.
