### ISSUE TITLE
GitHub actions runner worker process crashed with error: Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by yaananth** [actions/runner#546]
Internal [alert](https://vstskalypso.dev.azure.com/mseng//summary?containerId=69c38056-8eab-4174-93da-37282b4c2c33&selectedPage=summary&monitorId=8861a99d-1e6b-4203-b9a5-4c80388d5cbd&runId=86170529)

https://github.com/hftex/prime/actions/runs/135699683

`GitHub actions runner worker process crashed with error: Failed to create CoreCLR, HRESULT: 0x80004005`

**Comment by Tiko-Nazaryan** [comment]
Hey guys. I have got a same error in my side.

**Comment by Tiko-Nazaryan** [comment]
@yaananth in my side there wasn't enough space on server

**Comment by nikola-jokic** [comment]
Hey everyone,

This issue seems to be related to the runtime or the host itself. Since we are trying to keep this board with issues related to the runner project itself, I will now close it. Feel free to re-open it if you feel like this issue is related to the runner, but about it, I believe it is related to the host itself.

**Comment by nikola-jokic** [comment]
Hi @rahul-FLS,

It is usually related to the resources on the machine. This issue was also related to the runtime https://github.com/dotnet/core/issues/6733, but that is likely not the case with the runner. Please, check your resources on the server if you are seeing this issue.

**Comment by rahul-FLS** [comment]
Thanks @nikola-jokic but I don't think its related to space issue on server

<img width="709" alt="image" src="https://user-images.githubusercontent.com/94915383/162978793-e99f55bc-c7b6-4825-91c2-2a1a501189c6.png">

**Comment by nikola-jokic** [comment]
Can you send your diagnostic logs so we can try to track it down?

**Comment by rahul-FLS** [comment]
I just get this when try to see the runner container logs

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/94915383/163005140-9438c715-6cb8-4408-b9bf-8886b7398cbb.png">

**Comment by vmk-dev** [comment]
I got the same issue today with this docker-image: https://github.com/myoung34/docker-github-actions-runner

Runner does not start anymore due to:

```
Runner reusage is disabled
Obtaining the token of the runner
curl: (6) getaddrinfo() thread failed to start
Disable auto update option is enabled
Configuring
Failed to create CoreCLR, HRESULT: 0x80070008
Failed to create CoreCLR, HRESULT: 0x80070008
```

**Comment by rahul9170** [comment]
> I got the same issue today with this docker-image: https://github.com/myoung34/docker-github-actions-runner
> 
> Runner does not start anymore due to:
> 
> ```
> Runner reusage is disabled
> Obtaining the token of the runner
> curl: (6) getaddrinfo() thread failed to start
> Disable auto update option is enabled
> Configuring
> Failed to create CoreCLR, HRESULT: 0x80070008
> Failed to create CoreCLR, HRESULT: 0x80070008
> ```

@vmk-dev do you have a PSP enforced which doesn’t allow to write in root file system? If yes then you’d need to modify that. Alternatively you could mount an emptyDir volume to /tmp of the runner pod to get rid of this.
