### ISSUE TITLE
hashFiles() may output empty string when patterns are not matched

### ISSUE THREAD

**Issue by zhangyoufu** [actions/runner#556]
**Describe the bug**
hashFiles() may output empty string when patterns are not matched. This behavior is not documented.

**To Reproduce**
```
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: debug
      env:
        HASH: ${{ hashFiles('a-pattern-that-does-not-match') }}
      run: 'echo "HASH: ${HASH}"'
```

**Expected behavior**
`HASH: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

**Related code**
https://github.com/actions/runner/blob/4e7d27a53c84466562d366256b960433bafc469b/src/Misc/expressionFunc/hashFiles/src/hashFiles.ts#L47-L53

**Comment by nikola-jokic** [comment]
Hey @zachariahcox,

PR is merged to the docs! Thank you for submitting this issue.
