### ISSUE TITLE
self-hosted action runner failed to update

### ISSUE THREAD

**Issue by karancode** [actions/runner#562]
**Describe the bug**
I am running GitHub action runner inside a docker container (DinD). When a new runner version is available, runner tries to upgrade itself and for this I am already running `./bin/runsvc.sh` as the entrypoint process. But runner upgrade fails with error(mentioned below).

**To Reproduce**
1. Go to https://github.com/karancode/ghar
2. please set the github repo name, token, etc. and build the docker Dockerfile. Make sure to set an older runner version.
3. run the docker container and let the runner upgrade its version.

**Expected behavior**
Runner version should be upgraded successfully and container process should also survive.

## Runner Version and Platform
Tried with runner version `v2.262.1` (or any older version).
Running on `Ubuntu 18.04` docker image.

## What's not working?
```
# Authentication

√ Connected to GitHub

# Runner Registration

√ Runner successfully added
√ Runner connection is good

# Runner settings


√ Settings Saved.

.path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Starting Runner listener with startup type: service
Started listener process
Started running service

√ Connected to GitHub

2020-06-21 08:28:53Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.263.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should back online within 10 seconds.
/_work/_update.sh: line 96: /bin/mv: No such file or directory
Runner listener exited with error code 3
Runner listener exit because of updating, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn /bin/Runner.Listener ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /bin/Runner.Listener',
  path: '/bin/Runner.Listener',
  spawnargs: [ 'run', '--startuptype', 'service' ]
}
```

Please help me out here 🙇

**Comment by TingluoHuang** [comment]
@karancode you don't have `mv` in your container?
```
/_work/_update.sh: line 96: /bin/mv: No such file or directory
```

**Comment by karancode** [comment]
@TingluoHuang Thanks. But I confirmed that I have `mv` in my container..
```
root@ghar-deployment-787d476d6-pkswd:/# mv
mv: missing file operand
Try 'mv --help' for more information.
root@ghar-deployment-787d476d6-pkswd:/# which mv
/bin/mv
root@ghar-deployment-787d476d6-pkswd:/#
```

**Comment by karancode** [comment]
@TingluoHuang is there any update? or anything I should check for ?

**Comment by balhalees** [comment]
I have the same issue, any help is much appreciated!
My Docker image is based on debian:buster 
I did check and I do have /bin/mv in my container.

**Comment by nikola-jokic** [comment]
Hi @karancode, @balhalees,

Are you still seeing this issue?

@balhalees if you are, could you please send me your Dockerfile so I can try to reproduce it?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
