### ISSUE TITLE
Add a built-in powershell.

### ISSUE THREAD

**Issue by Summpot** [actions/runner#575]
**Describe the enhancement**
I think actions need to have the ability to directly control the system (through a certain shell language), but it is clear that sh and bash do not support all platforms, it may be a good idea to add support for powershell, I noticed [actions/setup-dotnet](https://github.com/actions/setup-dotnet/blob/master/src/installer.ts#L400-L451) used node to call powershell to install dotnet, why not try to support pwsh directly?

**Code Snippet**
Just like this
```yml
runs:
  using: 'pwsh'
  main: './MyScript.ps1'
```

**Additional information**
Add any other context about the feature here.

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by TingluoHuang** [comment]
@Summpot 

The runner carries a `node` binary under `externals/node12/bin`, so your actions can run on any platform (windows/linux/macos)

```
runs:
  using: 'pwsh'
  main: './MyScript.ps1'
```
Will most likely to fail on a non-windows platform since PowerShellCore is not normally not installed by default.

**Comment by Summpot** [comment]
@TingluoHuang 
I noticed that all the GitHub-hosted runners have installed PowerShell 7.0.2.
> Will most likely to fail on a non-windows platform since PowerShellCore is not normally not installed by default.

**Comment by TingluoHuang** [comment]
@Summpot 
Yes, we install it on the hosted runner, but workflow can run on a self-hosted runner which might not have PowerShell installed.
We don't want the customer needs to know how the action is implemented before adding it to their workflow.

We might support PowerShell ONLY IF there is a small size portable PowerShell executable that we can package within the runner.

**Comment by Summpot** [comment]
@TingluoHuang I thought of an idea that could run a powershell script without using a powershell executable.
Like this,
![image](https://user-images.githubusercontent.com/29229273/87225103-22e6ae80-c3bd-11ea-8959-0d9c8aaeb917.png)
By using these libraries,

``` xml
<ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.Commands.Diagnostics" Version="7.1.0-preview.5" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Management" Version="7.1.0-preview.5" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Utility" Version="7.1.0-preview.5" />
    <PackageReference Include="Microsoft.PowerShell.ConsoleHost" Version="7.1.0-preview.5" />
    <PackageReference Include="Microsoft.WSMan.Management" Version="7.1.0-preview.5" />
    <PackageReference Include="System.Management.Automation" Version="7.1.0-preview.5" />
  </ItemGroup>
```
I think it could also increase the start-up speed of the powershell.

**Comment by ericsciple** [comment]
We are adding support for an action.yml to define a series of [`run` steps](https://github.com/actions/runner/blob/main/docs/adrs/0549-composite-run-steps.md).

However as Ting mentioned, attempting to run a powershell script will fail if powershell/pwsh is not in the PATH.

We intentionally run scripts in a separate process (isolate memory). Also if we ran the DLLs directly, a user script "exit 1" would stop the runner.worker process. Also there are also behavioral differences between running powershell/pwsh.exe and creating your own host (for example stderr from external commands typically doesnt cause error records). We want the behavior to match what users experience locally when they run their scripts.

**Comment by Summpot** [comment]
@TingluoHuang @ericsciple
I have some questions. 
1.What about the cross-platform capabilities of Composite Run Steps?
2.Which shell will it use?
3.If it uses powershell, the self-hosted runner still needs to install powershell?
4.If it uses a platform-specific shell (such as sh) then does the author need to 
mark the platform on which the action can run?
5.If a composite action and the workflow that calls it use different versions of the same action, how does it behave?
