### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ojedavidea** [actions/runner#577]
.

**Comment by timharris777** [comment]
Check this out: https://github.com/sdras/awesome-actions

**Comment by timharris777** [comment]
Other than using those examples I posted above, you just need to find the event you want to trigger off of and then you can use the octokit api to do whatever you want.

**Comment by ojedavidea** [comment]
I would like to know how to add a label, a milestone and edit a project after a push or pull request with actions, but I don’t understand GitHub documentations, is there an easier way? Thank you!

`https://github.com/ojedavidea/hello-world/actions`
[https://github.com/ojedavidea/hello-world/actions](https://github.com/ojedavidea/hello-world/actions)

### 1. I chose a random name ; is there a necessity to call workflow files in a specific way?

### 2. I renamed from `CI` to `test29` but I don’t know the effect this line does to the workflow

### 3. I don’t understand why there is so many variations in the way to write the `on:` part. Earlier today someone told me to write `on: [pull_request]` which is obviously not the same as writing `on: pull_request: branches: [ master ]`
It seems that the `[]` are mandatory in both and that this would tell what `on:` applies to. But again why the white space in `[ master ]` and not in `[pull_request]` ? Is there a mistake?
I will let the `push:` part but I don’t understand the difference between an action triggered by `push:` and one by `pull_request:` since every change made on the repository on GitHub website is a commit. If I understand correctly `push:` applies to all and `pull_request:` only to Pull-Request? If I write only `push:` will it apply to all commits even Pull-Request and Issues?

`on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]`

### 4. I will let the build be named `build` but I don’t understand why change the name of it, is there a protocol to respect naming it and what changing this name does to the workflow?

`build:`

### 5. This part seems unchanged across almost all workflow file types, is it okay to assume using it exactly as is for all of them in the future will always result with successful runs?

`jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2`

What does `$GITHUB_WORKSPACE` mean? Is it a way to say that the workflow will work for all files from the `on:` part?

### 6. My point here is to verify if the file I would have just commited has this `name: Octocat` at `Line 1`. I have been told to write this code :

`- name: check the value for name
       run: |
            .....               # check the name value, if it's not 'Octocat', exit 1 to fail the workflow.`

But I don’t understand the power of `|` and `.....` in order to perform this step. It seems that the order is sent from the `# check the name value, if it's not 'Octocat', exit 1 to fail the workflow.` description, which is odd because it is only a description in the code due to `#` . Am I missing something that operates in behind?
Then I don’t see in the code where is it specified that the job needs to verify the `Line 1` and the variable `name:` or is it the check the name value part that gives this order?

I have tried this workflow earlier and it didn’t perform successfully with a commited file containing `name: Octocat` at `Line 1` so I assume I am not doing it correctly but I don’t understand why?

### 7. My point here is to apply a label and a milestone to the commited file.

`- name: add label and milestone    # will be executed when name value is correct
      run: |
           curl --request PATCH \
                --url ${{ github.event.pull_request.issue_url }} \
                --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
                --data '{"milestone": 1, "labels": [ "bug" ]}'      # 1 is the milestone number`

I still don’t understand the power of `|` and also the meaning here of `curl` and `--request PATCH`.
It seems that if I want this workflow to work on all commits and not only on Pull-Requests, I need this line of `url --url ${{ github.event.pull_request.issue_url }}` for `on: push:` and `on: issue:` but I don’t know how to write this in the code?

Why is there this `--header 'authorization: token ${{ secrets.GITHUB_TOKEN }}'` here and in other workflow files elsewhere on GitHub this `repo-token: "${{ secrets.GITHUB_TOKEN }}"` what is the right way to write this?

Is this line correct?

`--data '{"milestone": 1, "labels": [ "bug" ]}'`

### 8. I am stuck at this step :

`X check the value for name 0s
##[error]Process completed with exit code 127.
1.   Run .....               # check the name value, if it's not 'Octocat', exit 1 to fail the workflow.
4. /home/runner/work/_temp/20252ea1-0825-4109-9eec-0f613c17d951.sh: line 1: .....: command not found
5. ##[error]Process completed with exit code 127.`

it seems that this `.....` and/or this `# check the name value, if it's not 'Octocat', exit 1 to fail the workflow.` are not recognized lines of code.
