### ISSUE TITLE
Private Runner User Workflow Execution vs Runner Process User

### ISSUE THREAD

**Issue by JohnCrawford4588** [actions/runner#580]
**Description**
The same user that is designated to execute the workflow is always the same user that is running the process that hosts the runner.  This practice is dangerous because a workflow has the potential to corrupt or take down the runner process.

**Suggestion**
Offer an option in the runner's config where you can specify a separate user to execute the workflows than what runs the runner process.

**Workflow Illustration**
Create a workflow that runs on a private runner with this snippet in it:
```
kill -9 -1
```
That will terminate the runner process on the runner.

**Comment by ericsciple** [comment]
I think auto-scaling self-hosted runners will solve this. Not sure of a timeline however.

**Comment by thboop** [comment]
Unless we restrict this user from performing certain actions (like shutting down the computer), I'm not sure we could ensure safety of the runner.

The security boundary is the job getting assigned to that runner, once it is assigned we currently give full machine permissions, this allows us to support a variety of ci/cd workflows that require those escalated permissions.

We are looking into better supporting various autoscaling solutions, the [autoscaling solutions](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners) sitting above the runner should really be in charge of managing state, i'm not sure we will ever be able to fully support this at a runner level. So I'm going to close out this issue, but I appreciate you taking the time to post it.
