### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by andymckay** [actions/runner#588]
👋 This issue is to track the move over to using `main` as the default branch for this repo. We’d love your team's help in completing this transition.

**Do not remove your old default branch**, customers are going to be using it. We will be sending messages out about these changes, but if you want to message in your repository, that's fine as well.

- [x] Create a `main` branch.
- [x] You might need to rebase any pull requests you want to merge before changing the default branch.
- [x] Change the default branch in settings to `main`.
- [x] Update any documentation in this repo to refer to the new branch name, although using the version tag is still preferred.
- [x] Check that this Action works correctly for users who have a repository with a custom default branch name.
- [x] Close this issue and celebrate 🎉

We are aiming to complete this work by ~July 17th~ August 28th.

**Comment by hross** [comment]
@TingluoHuang looks like this is done.

**Comment by t0rr3sp3dr0** [comment]
What was the motivation behind this change?

**Comment by hross** [comment]
@t0rr3sp3dr0 see these articles for context on the default branch change. This is a github wide effort:

https://thenextweb.com/dd/2020/06/15/github-plans-to-replace-racially-insensitive-terms-like-master-and-whitelist/

https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by t0rr3sp3dr0** [comment]
@hross this might not be the right place to discuss the subject, but github/renaming is not accepting issues and I don't know where else to write about it. My apologies in advance.

I've been reading about the change of the default branch name on git and so far as I know there is no consensus about it. Have you considered that `main` has a worse connotation in other cultures than `master`? https://lore.kernel.org/git/20200616210701.22924-1-zeevriend@gmail.com/
