### ISSUE TITLE
Disable process cleanup

### ISSUE THREAD

**Issue by croachrose** [actions/runner#598]
**Describe the bug**
Our build process starts a bazel server on each run but the runner kills the process on cleanup. I want the server to stay around.

**To Reproduce**
1. Start a background process in a job
2. `Complete job` steps kills the process

**Expected behavior**
I expect some kind of ability to disable this behavior. I see `process.clean` but have no idea how to modify that variable.

## Runner Version and Platform
linux-x64-2.267.1

**Comment by TingluoHuang** [comment]
@croachrose can you start the background process on the host machine before the runner starts?

**Comment by croachrose** [comment]
@TingluoHuang not really. The process is started based on the repository being tested and the version of the tool we are using (`bazel`). Is there no way to expose `process.clean` to either the config script or to the workflow config?

**Comment by michhyun1** [comment]
This would be really helpful for me as well. We are trying to run a server in the background while we run tests against it

**Comment by TingluoHuang** [comment]
`RUNNER_TRACKING_ID="" && ./yourtool` before starting your process, then the process you start should not get killed by the runner.

**Comment by croachrose** [comment]
> `RUNNER_TRACKING_ID="" && ./yourtool` before starting your process, then the process you start should not get killed by the runner.

What do you mean by "before starting your process"? Is this within my workflow config or before starting my runner?

**Comment by TingluoHuang** [comment]
> > `RUNNER_TRACKING_ID="" && ./yourtool` before starting your process, then the process you start should not get killed by the runner.
> 
> 
> 
> What do you mean by "before starting your process"? Is this within my workflow config or before starting my runner?

In your workflow.

**Comment by TingluoHuang** [comment]
close this, and hope this worked. 😄

**Comment by swamicontact** [comment]
Run RUNNER_TRACKING_ID=" " ./jfrog.exe  is this the correct representation?  for me each workflow run JFROG CLI settings are getting disappeared, so due to this  the other parallel workflow jobs are getting failed since it is searching for JFROG setup

**Comment by sg-s** [comment]
@TingluoHuang really struggling with this -- can you point me to an example?

**Comment by subratliku** [comment]
how to resolve this on a Windows container with powershell?

**Comment by MaksZhukov** [comment]
@subratliku Hey! Have you found a solution?

**Comment by subratliku** [comment]
I am able to do it with ssh connection to remote windows machine by
installing  openssh on the windows.
And 2nd alternative is by converting  the service as windows service  using
nssm tool.

**Comment by gladykov** [comment]
So then how one would will kill such runner / process at the end of workflow?

**Comment by Pwuts** [comment]
The `$env:RUNNER_TRACKING_ID="" && ./start-something` trick doesn't seem to work on Windows runners. :/

I'm trying to get [a process](https://github.com/Significant-Gravitas/AutoGPT/actions/runs/8373443800/job/22926520535#step:4:4) to continue running between two steps but [no luck so far](https://github.com/Significant-Gravitas/AutoGPT/actions/runs/8373443800/job/22926520535#step:5:9). @TingluoHuang any suggestions?

**Comment by pekspro** [comment]
@Pwuts, does it works if you start the process in bash instead of PowerShell in Windows? That solved the issue for me.

https://stackoverflow.com/questions/78464218/running-a-background-process-in-multiple-steps-on-windows

**Comment by jasonsketchup** [comment]
> So then how one would will kill such runner / process at the end of workflow?

For POSIX shell...
```
pkill -lif [...]
```

For example...
```
pkill -lif /opt/homebrew/bin/appium
```

**Comment by buzzy** [comment]
That does not work at all for me.

RUNNER_TRACKING_ID="" && ./server &

It starts the server for a few seconds and when the workflow finishes, it gets forced killed! Like with kill -9

**Comment by mr-entropia** [comment]
This trick appears to not work anymore. At the end of the workflow I get the following;

> Cleaning up orphan processes
> Terminate orphan process: pid (4458) (bash)

Instead of the process I actually started being killed, now it's `bash` which effectively does the same.

**Comment by NorseGaud** [comment]
Still works for me. Users need to be aware that & is not enough. In bash, you need something like this:

```
    export RUNNER_TRACKING_ID="" # hack to keep backgrounded processes from being killed by github actions
    nohup "${STORAGE_DIR}/server" "${SERVER_PORT}" "${MGMT_PORT}" 1 > server.log 2>&1 &
    SERVER_PID="$!"
    echo "$SERVER_PID" > _pid
    disown "$SERVER_PID"
```
