### ISSUE TITLE
space in volume path causes error during config

### ISSUE THREAD

**Issue by jeffrey-kinesso** [actions/runner#601]
**Describe the bug**
If there is a space in the mounted volume on Mac an error occurs on a CD command during configuration step
Example volume with space:  `/Volumes/Macintosh HD - Data`

**To Reproduce**
1. download a fresh runner
2. run configuration script
3. See error:  
```
➜  actions-runner ./config.sh --url https://github.com/myorg --token redacted
./config.sh: line 70: cd: /Volumes/Macintosh: No such file or directory
```

**Expected behavior**
CD should succeed

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner?
macOS x64

## What's not working?
config

## Job Log Output
n/a

## Runner and Worker's Diagnostic Logs
n/a

**Comment by TingluoHuang** [comment]
@jeffrey-kinesso thanks for reporting and fixing the bug. 🎉
