### ISSUE TITLE
Provide status if runner is occupied with a job

### ISSUE THREAD

**Issue by davidkarlsen** [actions/runner#604]
**Describe the enhancement**
Be able to run a command like `runner.sh jobstatus` to tell if the runner is occupied with a job or not. This way I can block termination until it is free.

**Code Snippet**
N/A

**Additional information**
This will be used to drain k8s pods.

**Comment by TingluoHuang** [comment]
You could query GitHub REST API to get this info.
https://docs.github.com/en/rest/reference/actions#list-self-hosted-runners-for-a-repository

The service is the source of the truth for the actions system, don't rely on the runner.

**Comment by GMNGeoffrey** [comment]
I don't think this is a solution for several reasons: listing runners requires permissions that an entity with access to a single runner (for instance, the runner machine itself) may not (and should not) have, the server may have lost connection to the runner even if the runner is still processing a job, the network requests add additional latency that make it more likely that the result is outdated by the time it arrives. This is somewhat related to #745. The runner application itself should provide endpoints to monitor its status
