### ISSUE TITLE
self-hosted server's connection to github PR timeout for unit test longer than a few minutes

### ISSUE THREAD

**Issue by yaoli** [actions/runner#611]
**Describe the bug**
I've tested the self-hosted server for some quick jobs in the workflow, and verified they are working well. However, when the I introduced jobs running longer than a few minutes, the job finished successfully on the server, but the response doesn't get relayed back to the PR interface under PR `checks`, the status of the check is forever queuing. 

**To Reproduce**
Any long-running job should do

**Expected behavior**
Same behavior as short-running jobs

## Runner Version and Platform
Version of your runner? 
I'm not sure how to check its version.

Linux

## What's not working?
Maybe the following `grep timeout *.log` could provide a clue for debugging, I'm not sure how to extend that time limit.
````
Runner_20200722-170253-utc.log:[2020-07-22 17:02:54Z INFO RunnerServer] Establish connection with 100 seconds timeout.
Runner_20200722-170253-utc.log:[2020-07-22 17:02:54Z INFO RunnerServer] Establish connection with 60 seconds timeout.
Runner_20200722-170253-utc.log:[2020-07-22 17:02:54Z INFO RunnerServer] Establish connection with 60 seconds timeout.
Runner_20200722-170253-utc.log:[2020-07-22 17:02:55Z INFO JobDispatcher] Set runner/worker IPC timeout to 30 seconds.

**Comment by nikola-jokic** [comment]
Hey @yaoli,

Are you still seeing this issue on the newer version? If so, could you please provide a repository that I can use to reproduce this behaviour for further debugging? Thanks!
