### ISSUE TITLE
self-hosted: Provide debian package

### ISSUE THREAD

**Issue by nyetwurk** [actions/runner#617]
Distributing an installer package via curl is not ideal.

Provide a debian package.

**Comment by bryanmacfarlane** [comment]
The runner produces a linux package (see releases) and it runs fine on debian.  

The config commands don't need sudo.  As a matter of fact, they block in config.  The only command that needs to be run as sudo is configure as a service and that's a requirement of systemd.

**Comment by nyetwurk** [comment]
I only see tarballs in latest release

**Comment by nyetwurk** [comment]
Also, there is no `debian/` directory in the source tree suitable for `debuild` or `dpkg-buildpackage`

**Comment by nikola-jokic** [comment]
Hey @nyetwurk,

Thank you for your interest in the runner application and taking the time to provide your valuable feedback! I know it has been a while, but we kindly ask you to redirect this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for this feature requests in GitHub Actions. For more information on this policy please [read our contribution guidelines](https://github.com/actions/runner#contribute).
