### ISSUE TITLE
Add an environment variables to indicate workflow duration 

### ISSUE THREAD

**Issue by merou** [actions/runner#618]
**Describe the enhancement**
Please add env variables to indicate start and stop of of a workflow e.g:
`GITHUB_WORKFLOW_STARTED` 
`GITHUB_WORKFLOW_FINISHED`

Since a running workflow cannot have a finished timestamp, should be the value of the current timestamp.
Those can be express in `unix timestamp`.

**Comment by bryanmacfarlane** [comment]
A workflow runs many jobs and a runner runs one job.  So finished would always be undefined.  

Do you have a scenario / need for started?

**Comment by merou** [comment]
Yes I am building a dashboard and it easier to collect this data from env variables - e.g drone:
https://docker-runner.docs.drone.io/configuration/environment/variables/
DRONE_BUILD_STARTED/DRONE_BUILD_FINISHED

I understand that finished cannot be defined but it can still hold the value of the current time.

I can of course add a start/stop steps to report time but I find fetching this data from envs more elegant.

**Comment by ericsciple** [comment]
Adding a step has the advantage that you control the time format

**Comment by merou** [comment]
True but in my case I would do that within my last docker custom action e.g entrypoint.sh using github actions env. vars, e.g:
```
#!/bin/bash -x

DELTA=$(expr ${GITHUB_WORKFLOW_FINISHED} - ${GITHUB_WORKFLOW_STARTED})
DURATION=$(date -d@$DELTA -u +%H:%M:%S)
```
