### ISSUE TITLE
[Linux] Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by dkvilo** [actions/runner#619]
## Runner Version and Platform

Runner Version: **2.267.1**
OS: **Ubuntu Linux x64**

## What's not working?
![Erro Message](https://i.imgur.com/ZK581Dp.png)

**Comment by jk2K** [comment]
+1

```
Runner Version: 2.284.0
OS: Linux ci-runner-c6c7f440 4.18.0-193.el8.jj_001.x86_64 #1 SMP Mon Aug 3 16:19:58 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
CentOS: CentOS Linux release 7.2.1511 (Core)
```

**Comment by jk2K** [comment]
related to https://github.com/actions/runner/issues/546

**Comment by jk2K** [comment]
I don't know why, but it works, you can set `COMPlus_EnableDiagnostics` env

such as

```bash
su -s /bin/bash githubrunner -c "COMPlus_EnableDiagnostics=0 ./config.sh"
```

**Comment by nikola-jokic** [comment]
Hey everyone,

I will now close this issue since @jk2K provided an answer. Thank you @jk2K!
