### ISSUE TITLE
ARM-based runners throw ICU error on AWS Graviton/Graviton2 instances

### ISSUE THREAD

**Issue by bdruth** [actions/runner#629]
**Describe the bug**
When attempting to run `./config.sh` (or anything else) on freshly baked AWS Graviton/Graviton2 instances running Amazon Linux 2, the .NET Core runtime throws an error indicating that it `Couldn't find a valid ICU package installed on the system`. However, `libicu` is already installed, and installing the only other `icu` related packages (`icu`, `libicu-devel`) doesn't affect change in this error. The only "fix" for this appears to be setting the `configProperties` to include `"System.Globalization.Invariant": true`.

**To Reproduce**
1. Launch an AWS Graviton/Graviton2 (a1/*6g*) instance with Amazon Linux 2
2. Follow the steps to install an ARM64 action-runner from your GitHub repo's _Actions_ -> _Add Runner_

**Expected behavior**
When running `./config.sh` command, the runner configuration should complete successfully.

## Runner Version and Platform
`2.267.1`

Linux/ARM64

## What's not working?
`./config.sh` crashes.
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.StringComparer.get_OrdinalIgnoreCase()
   at GitHub.Runner.Sdk.RunnerWebProxy..ctor()
   at GitHub.Runner.Common.HostContext..ctor(System.String, System.String)
   at GitHub.Runner.Listener.Program.Main(System.String[])
./config.sh: line 79:  1689 Aborted                 ./bin/Runner.Listener configure "$@"
```

### Workaround

Applying the following patch sets the `System.Globalization.Invariant` property in 3 `configProperties` locations.

```
patch -p1 <<ICU_PATCH
diff -Naur a/bin/Runner.Listener.runtimeconfig.json b/bin/Runner.Listener.runtimeconfig.json
--- a/bin/Runner.Listener.runtimeconfig.json	2020-07-01 02:21:09.000000000 +0000
+++ b/bin/Runner.Listener.runtimeconfig.json	2020-07-28 00:02:38.748868613 +0000
@@ -8,7 +8,8 @@
       }
     ],
     "configProperties": {
-      "System.Runtime.TieredCompilation.QuickJit": true
+      "System.Runtime.TieredCompilation.QuickJit": true,
+      "System.Globalization.Invariant": true
     }
   }
-}
\ No newline at end of file
+}
diff -Naur a/bin/Runner.PluginHost.runtimeconfig.json b/bin/Runner.PluginHost.runtimeconfig.json
--- a/bin/Runner.PluginHost.runtimeconfig.json	2020-07-01 02:21:22.000000000 +0000
+++ b/bin/Runner.PluginHost.runtimeconfig.json	2020-07-28 00:02:59.358680003 +0000
@@ -8,7 +8,8 @@
       }
     ],
     "configProperties": {
-      "System.Runtime.TieredCompilation.QuickJit": true
+      "System.Runtime.TieredCompilation.QuickJit": true,
+      "System.Globalization.Invariant": true
     }
   }
-}
\ No newline at end of file
+}
diff -Naur a/bin/Runner.Worker.runtimeconfig.json b/bin/Runner.Worker.runtimeconfig.json
--- a/bin/Runner.Worker.runtimeconfig.json	2020-07-01 02:21:16.000000000 +0000
+++ b/bin/Runner.Worker.runtimeconfig.json	2020-07-28 00:02:19.159028531 +0000
@@ -8,7 +8,8 @@
       }
     ],
     "configProperties": {
-      "System.Runtime.TieredCompilation.QuickJit": true
+      "System.Runtime.TieredCompilation.QuickJit": true,
+      "System.Globalization.Invariant": true
     }
   }
-}
\ No newline at end of file
+}
ICU_PATCH
```

**Comment by csoma** [comment]
Related answer: 
https://stackoverflow.com/questions/62942913/install-dotnet-core-on-ec2-linux-ami-2-c6g/63023835#63023835

**Comment by bdruth** [comment]
Thanks for the tip - I had no luck finding info on this when I was looking, so disabling it seemed the simplest way to make it work. With this info, is the feeling that this is a non-issue for actions-runner and should be handled downstream?

**Comment by armisv** [comment]
@bdruth  could you please share the fix to this?

**Comment by nikola-jokic** [comment]
Hi @bdruth,

Yes, you are right. This is related to the host executing the runner, and not the runner itself. I will close this issue now since this is not related to this repository and I am glad you have it working 😊
