### ISSUE TITLE
Protect self-hosted runner by a secret

### ISSUE THREAD

**Issue by dkurt** [actions/runner#631]
**Describe the enhancement**
Current GitHub Actions documentation recommends not to use self-hosted runners for public repositories. Malicious code from pull requests to your project will be executed without any checks. One of the simplest ways to protect self-hosted runner is to add a check for secret environment variable.

**Code Snippet**
1. User configures the runner with a secret
```
./config.sh --url https://github.com/username/repository --token *** --secret MY_SECRET:MY_VALUE
```

2. User defines a secret for corresponding repository
![image](https://user-images.githubusercontent.com/25801568/89073450-2f8a7100-d383-11ea-878b-0b0b0f494c60.png)

3. > Secrets are not passed to workflows that are triggered by a pull request from a fork.

    That means that Runner.Listener **before** running a code from `.github/workflow` on self-hoster runner checks a value of secret variable from `./configure.sh` and environment variable - it's correct for `push` or scheduled triggers but not for external pull requests.

**Additional information**
Please guide me how to help here. I have not found build instructions for `actions/runner` so cannot experiment locally and find exact place in code to perform such check.

**Comment by dkurt** [comment]
Seems like it's working now:

![image](https://user-images.githubusercontent.com/25801568/115993837-3fb34200-a5dd-11eb-833f-169474cb5215.png)

**Comment by Fulviuus** [comment]
Hey @dkurt, I was looking to implement the *exact* proposal you suggested on a fork of the Github runner repo, but I see that you closed this issue - how did you solve the problem, in the end?

**Comment by dkurt** [comment]
> Hey @dkurt, I was looking to implement the *exact* proposal you suggested on a fork of the Github runner repo, but I see that you closed this issue - how did you solve the problem, in the end?

Hi! GitHub implemented this feature. So now  PRs from fork repos will require special button push.

**Comment by Fulviuus** [comment]
I see - is this what you are referring to?
https://github.blog/changelog/2021-07-01-github-actions-new-settings-for-maintainers/

**Comment by dkurt** [comment]
@Fulviuus, yes

> I see - is this what you are referring to?
> https://github.blog/changelog/2021-07-01-github-actions-new-settings-for-maintainers/

@Fulviuus, yes
