### ISSUE TITLE
"No runner group found with identifier 1"

### ISSUE THREAD

**Issue by davidkarlsen** [actions/runner#634]
**Describe the bug**
I always see "runners-pod-br88n runner An error occurred: No runner group found with identifier 1." in the log when a runners shuts down.

**To Reproduce**
1. Run runner with: https://github.com/evryfs/github-actions-runner
2. Terminate instance, and see the error in the console-log.

**Expected behavior**
Unsure if it is a problem or not - but it doesn't look as expected.

## Runner Version and Platform
2.272.0

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
See description

## Job Log Output
See description

## Runner and Worker's Diagnostic Logs
See description

**Comment by nikola-jokic** [comment]
Hi @davidkarlsen, are you still experiencing this issue? If yes, could you also provide `_diag` logs so we can investigate it further?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
