### ISSUE TITLE
MaxParallelism has no effect

### ISSUE THREAD

**Issue by mhart** [actions/runner#639]
**Describe the bug**
Creating a new agent with a `maxParallelism` greater than 1 seems to have no effect – the returned agent only has a `maxParallelism` of 1

**To Reproduce**
1. Modify https://github.com/actions/runner/blob/48ac96307cea09bf51b55a3589c66526c0ea4e80/src/Runner.Listener/Configuration/ConfigurationManager.cs#L494 to be a number greater than 1
2. Recompile and register an agent
3. Observe the returned response has `maxParallelism: 1`

**Expected behavior**
Agents can be created with a parallelism greater than 1 as you can for Azure DevOps: https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/agents/add?view=azure-devops-rest-5.1

## Runner Version and Platform
Version of your runner? 2.272.0

OS of the machine running the runner? OSX

## Question
Is this something that is or will be supported?

If not, what's the best way to register agents that can process multiple jobs at once?

**Comment by TingluoHuang** [comment]
`MaxParallelism` is always 1, this is by design.
If you want to run multiple jobs in parallel on a machine, just configure multiple runners side-by-side. 😄
