### ISSUE TITLE
GitHub Actions do not work/run when the `.github/workflows/checks.yml` file is created in a commit which creates several files at once

### ISSUE THREAD

**Issue by evandrocoan** [actions/runner#642]
**Describe the bug**

GitHub Actions do not work/run when the `.github/workflows/checks.yml` file is created in a commit which creates several files at once.

**To Reproduce**

1. Create a new repository
1. Commit some files
1. Create now at once `.github/workflows/checks.yml` and a bunch of other files in the same commit.
1. Now on, GitHub Actions will never run on that repository.

**Expected behavior**

Creating `.github/workflows/checks.yml` and several other files in the same commit should not make/force GitHub Actions to never run in a repository.

**Comment by ruvceskistefan** [comment]
Hi @evandrocoan,
I tried to reproduce the bug you reported, but I didn't succeed. I followed all the steps you described and in my opinion this is no longer a problem. I'm sending you a link to the [repository](https://github.com/ruvceskistefan/reproducing-issue-642) I created for the purpose of reproducing this issue. There you can see successfully executed workflow and commit in which a YML file (.github/workflows/hello_world.yml) with many other files has been added.
I'm going to close this issue, feel free to write if you have more questions or if you want us to reopen the issue.
