### ISSUE TITLE
Adding github.action_path to JavaScript and Docker Actions

### ISSUE THREAD

**Issue by ethanchewy** [actions/runner#649]
See: https://github.com/github/help-docs/pull/14954#discussion_r467074094

**Comment by edigaryev** [comment]
Why was this closed?

The [`github` context documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) for `action_path` still states:

>This property is only supported in composite actions.

And no `GITHUB_ACTION_PATH` environment variable seems to be set when invoking JavaScript actions.
