### ISSUE TITLE
`composer validate` command not working in a self-hosted environment

### ISSUE THREAD

**Issue by Jamesking56** [actions/runner#650]
**Describe the bug**
`composer validate` in self-hosted runner gives a strange error message:

```
The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly.
```

The environment variables are set correctly because if I SSH into my server, `composer validate` works as normal. This error also does not appear when using GitHub's own hosted runners.

**To Reproduce**
1. Add a self-hosted runner
2. Add a workflow step that runs `composer validate`

**Expected behavior**
`composer validate` to run as normal.

## Runner Version and Platform
Version of your runner? v2.272.0

OS of the machine running the runner? Ubuntu 20.04

## What's not working?
Error message appears in workflow log on GitHub:

```
The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
```

**Comment by quisse** [comment]
I'm having this issue too. A workaround is to make sure the the service runs under a non root user by running `svc.sh install githubactionsrunner` and making sure the `_diag` directory is owned by the `githubactionsrunner` user.

**Comment by bryanmacfarlane** [comment]
If you're running as a service there's a .env file that's read at startup.  looks like it's not in the docs

the format is key=val so you can do something like `env > .env` to capture the environment.  by default I think it only pushes certain ones to that file: https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/start/nixsvc.md#setting-the-environment

**Comment by pekhota** [comment]
@bryanmacfarlane thank you so much. You comment was very helpful for me.

**Comment by nikola-jokic** [comment]
Hi everyone,

I think it is safe to close this issue now since there are multiple places in the docs describing the `.env` (for example https://docs.github.com/en/actions/hosting-your-own-runners/using-a-proxy-server-with-self-hosted-runners#using-a-env-file-to-set-the-proxy-configuration).
