### ISSUE TITLE
Generate a duplicated job when a job runs on 'macos-latest'

### ISSUE THREAD

**Issue by BrightRan** [actions/runner#654]
Associated community ticket: https://github.community/t/macos-runners-are-not-working/126787

There is a job named "**qa_android_tests**" which runs on '**`macos-latest`**' in the customer's workflow.
When the workflow was triggered, it generated two jobs with the same name "**qa_android_tests**", one was success but another was failure. See the workflow run [here](https://github.com/simpledotorg/simple-android/actions/runs/202009394/workflow).
![two_same_jobs](https://user-images.githubusercontent.com/46307996/89763138-7c5d0d00-db24-11ea-999e-b1f0b69fc5a6.PNG)

Other jobs run on other runners in the same workflow were normal.

**Comment by vinaysshenoy** [comment]
For what it's worth, it seems to have been a temporary issue and is fixed now.

**Comment by nikola-jokic** [comment]
Thank you for notifying @vinaysshenoy! Closing this issue now 😊
