### ISSUE TITLE
Allow env vars to be accessible across jobs if so desired

### ISSUE THREAD

**Issue by timharris777** [actions/runner#656]
Allow workflow level env to be updated within a job step so that the next job can use it. Currently env vars set/updated within a step can only be accessed from within that same job. The next job will not be able to access it. Setting outputs can be a bit cumbersome.

**Comment by AvaStancu** [comment]
Hey @timharris777 ,

Thank you for your interest in the runner application and taking the time to provide your valuable feedback. We kindly ask you to redirect this feedback to the [GitHub Community Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests in GitHub Actions. [Read more about our guidelines here.](https://github.com/actions/runner/blob/main/docs/contribute.md)
