### ISSUE TITLE
Command to early-exit the job and set check conclusion

### ISSUE THREAD

**Issue by ylemkimon** [actions/runner#662]
**Describe the enhancement**
Currently to skip the rest of steps during a job, an `if` condition has to be added to all of steps or steps have to be moved to another job.

It'd be nice to have a command to early-exit (premature, prematurely, graceful, gracefully) (end, finish, terminate, termination, stop, halt, skip, cancel, discontinue, fail) the job during a step without failing the job:
```
::exit::
```

It'd be also nice to set the conclusion of early-exited job:
```
::exit::failure
```
(equivalent to `exit 1`)
or
```
::exit::neutral
```
(equivalent to `exit 78` [in Actions v1](https://github.community/t/github-actions-neutral-exit-code-is-incorrectly-interpreted-as-failure/16088))
and [other check conclusions](https://developer.github.com/v3/checks/runs/#parameters).

This would help save build time for both GitHub and customers.

**Additional information**

Related StackOverflow and GitHub Community posts:
- [How to fail a job in Github Actions?](https://stackoverflow.com/q/57903836)
- [How to force to exit in Github Actions step](https://stackoverflow.com/q/60589373)
- [How to write a GitHub Action with a neutral Check Run status](https://stackoverflow.com/q/57687369)
- [How to perform an early clean exit of a job ?](https://github.community/t/how-to-perform-an-early-clean-exit-of-a-job/17531)
- [Early successful termination of job](https://github.community/t/early-successful-termination-of-job/16500)
- [Github Action Skip Steps/Fall Through Syntax](https://stackoverflow.com/q/60382188)

Related issues:
- https://github.com/actions/toolkit/issues/146
- https://github.com/veggiemonk/skip-commit

Other CIs:
- CircleCI: [`circleci-agent step halt`](https://circleci.com/docs/2.0/configuration-reference/#ending-a-job-from-within-a-step)
- Travis CI: [`travis_terminate`](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/bash/travis_terminate.bash)
- AppVeyor: [`appveyor exit`](https://www.appveyor.com/docs/build-configuration/#build-pipeline) ([Linux](https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#premature-termination-of-the-build-process))
- Jenkins: [`currentBuild.result`](https://devops.stackexchange.com/q/885)
- GitLab CI: [`exit 0`](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/18041)

**Comment by A-Tokyo** [comment]
This is really useful and is quite needed!

**Comment by remorses** [comment]
This is useful to not repeat the same if statement many times, you can instead do an early exit

**Comment by christian-kreuzberger-dtx** [comment]
This would be a great addition. Right now I have a pre-condition that I can only check in a bash-script, and I'm exiting with `exit 1` for a purpose. However, in my PR it shows up as a failure :(

![image](https://user-images.githubusercontent.com/56065213/109924439-8d3bbe80-7cc0-11eb-8f08-2a7a317c0a7b.png)

**Comment by bartlettroscoe** [comment]
I can't believe GHA does not support this.  I guess you need to just implement and entire job as one big step run by your own driver script and then you can put whatever logic you want in that script to terminate early and with a zero exist (and a nice informational message).  Is that the only current workaround for this?

GHA seems to be a new unique declarative language with somewhat limited functionality.

**Comment by lpil** [comment]
Has anyone found a work-around for this? Thanks

**Comment by SnowCait** [comment]
How about step instead of command?

```
steps:
  - exit: success()
    if: failure()
```

```
steps:
  - exit: failure()
    if: steps.step1.outputs.count > 0
```

**Comment by spookylukey** [comment]
A couple of untested ideas as partial workarounds:

- A step could cancel the whole workflow using the REST API - https://docs.github.com/en/rest/reference/actions#cancel-a-workflow-run
- One workflow could contain the initial check, with the remaining steps in a separate workflow which is conditionally triggered by the first workflow.

**Comment by seemethere** [comment]
This would be extremely useful especially with the addition of:
* https://github.com/actions/runner/pull/1302 

If this functionality was available one could re-create the [re-run workflow from failed](https://support.circleci.com/hc/en-us/articles/360050303671-How-to-rerun-a-workflow) feature that's popular within CircleCI

**Comment by Typraeurion** [comment]
> * One workflow could contain the initial check, with the remaining steps in a separate workflow which is conditionally triggered by the first workflow.
I don’t see how this could work.  A workflow triggered by another [workflow run](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run) will run whether the other workflow succeeded or failed; you can’t filter based on its conclusion.

**Comment by solarmosaic-kflorence** [comment]
Another workaround is to define all of the conditional steps in a composite action, and then make the invoking of the composite action conditional. This has limitations, though, because composite actions do not support all of the syntax in workflow files.

**Comment by rocklan** [comment]
Any update on when this might be resolved?

**Comment by jalaziz** [comment]
I have a use case that's not really solved with conditional steps.

In the case I'm trying to solve for, we want to set the check condition to the `neutral` status.

The use case is pretty simple. We would like to warn the users that their commit messages may be missing information. However, some of that information is optional and shouldn't block a PR from being merged if it's intentionally missing. A skipped or success status gives the wrong impression. The `neutral` status seems to be the next best thing in the absence of a `warning` status.

**Comment by JCMais** [comment]
Are there any updates on this feature? I was checking the roadmap I was not able to find any related issues

**Comment by fbidu** [comment]
bump

**Comment by rodrigobrim** [comment]
No way. Two years without such a simple solution? We just need a job to finish the workflow with success or not.

Why is this so hard to implement?

**Comment by jerrygreen** [comment]
It was already implemented in V1 version of GitHub Actions.

By some reason, they broke it, therefore it’s not possible right now anymore.

Was there some reasoning behind that? Was that just a mistake?

Nobody knows.  GitHub seems quiet about that. Not because of «it’s hard».

IMO highly likely just another [bureaucracy moment](https://youtu.be/JtEkUmYecnk).

**Comment by rodrigobrim** [comment]
How can we pressure to higher the priority here?

This issue has more than 300 likes.

**Comment by jerrygreen** [comment]
Spamming messages here definitely won't help

There's «Contact Github» link in the footer, maybe it's more appropriate way to send feedback, if nobody created it there yet:

https://support.github.com/features/feedback

**Comment by eterv** [comment]
is there any update?

**Comment by krtschmr** [comment]
really github? we can't abort a workflow? it's 2022

**Comment by nsalfos** [comment]
This needs to be check and implemented, we need a way to skip the rest of the steps if we need to.

**Comment by apearce-nov** [comment]
bump. 

Workaround for now is to set a `SHORT_CIRCUIT` env variable that I will set as the first step of each job with short circuit logic. I check the value of this variable in every step of the job after it is set to see if the step needs to be executed.

It's a lot of redundant code, but its worth the hours saved from needlessly running entire jobs just to get their dependent jobs to execute as expected.

**Comment by tristan957** [comment]
You bumped an issue that was already bumped 2 hours ago. Please read instead of spamming people with emails.

**Comment by mycaule** [comment]
> This would be a great addition. Right now I have a pre-condition that I can only check in a bash-script, and I'm exiting with `exit 1` for a purpose. However, in my PR it shows up as a failure :(
> 
> ![image](https://user-images.githubusercontent.com/56065213/109924439-8d3bbe80-7cc0-11eb-8f08-2a7a317c0a7b.png)

You can make the first step always succeed by setting the correct outputs
https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs


```yml
jobs:
  check:
    runs-on: decathlon
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: early
        name: Branch check
        run: |
          status="skip"
          if $condition
          then
            status="deploy"
          fi

          echo "status=$status" >> $GITHUB_OUTPUT
  deploy:
    name: Deploy
    needs: check
    if: needs.check.outputs.status == 'deploy'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Do the heavy deploy
      run: |
        echo "This runs only when condition=$condition is met"
```

**Comment by kerryj89** [comment]
I am also in need of this.

> This would help save build time for both GitHub and customers.

I always wonder if saving build time is not in their business interest until they need to be competitive.

**Comment by fabriciomurta** [comment]
This is a little old and unanswered issue, but I believe it deserves an explanation.

This happens because the default bash shell for linux/macos runs with `-o pipefail`. You can override it, and it is documented in [Workflow syntax for GitHub Actions: Exit codes and error action preference](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference).

In short, just use in the step, besides the `run` section, a `shell` either

```yaml
shell: bash {0}
```

Or maybe similar to the default, without pipefail:

```yaml
shell: /bin/bash --noprofile --norc -e {0}
```

You can see what current shell command your workflow is using in the logs, like this:
![image](https://user-images.githubusercontent.com/10730372/221388188-3610db35-063e-45ee-b704-c17708a375a5.png)

Another way to avoid this is just handle the commands that potentially can return error, like

```bash
my_dangerous_command || true
```

to completely ignore its return status or

```bash
success=true
my_dangerous_command || success=false
if ! ${success}; then
  echo "The command failed."
else
  echo "Dangerous command is good. Let's carry on."
fi
```

This should make script handling a bit easier, but beware of your steps that rely on early quitting to determine whether they're good or not!..

**Comment by Kurt-von-Laven** [comment]
This may be helpful for some wanting to continue execution within a Bash script, although `pipefail` is considered a best practice in Bash development, GitHub Actions doesn't `set -eo pipefail` unless you explicitly set `shell: bash`, and most people are usually better off with Python scripts in my experience. Regardless of my personal opinion, this doesn't address the original issue, which is about preventing execution of subsequent _workflow_ steps in a successful job.

**Comment by terozio** [comment]
> really github? we can't abort a workflow? it's 2022

2023 is not looking much better either. This is the most upvoted open issue in the repository, open for almost 3 years and I haven't noticed any indication that there would even be a plan to work on this. Happy to be proven wrong...

**Comment by SatishBethi** [comment]
I really hope they add this soon 🤞

**Comment by mauritsdebruin** [comment]
Yeah this is basic functionality that is very much due for implementation. Please fix.
I don't understand how it can take years and years to get something as basic as this implemented, especially considering the amount of upvotes.

**Comment by Gnts** [comment]
This could help us tremendously to cleanup our workflows and make them more readable :)

**Comment by izi-p** [comment]
Any updates on this? 🥹 this is a must have

**Comment by dirkf** [comment]
> GHA seems to be a new unique declarative language with somewhat limited functionality.

Someone at GH was really keen on the obscurity and brittleness of IBM JCL but felt it needed a dash more random behaviour to bring it "up" to the level of `command.com`?

**Comment by constgen** [comment]
a hope

**Comment by Mikilll94** [comment]
Any update on this?

**Comment by oliveryasuna** [comment]
Right now, I have to use `if` on each subsequent step. This would be a huge improvement in usability and readability.

**Comment by janaagaard75** [comment]
I know this is will probably not work for everybody, but the use cases I have could all be solved by allowing me to tell GitHub to treat a skipped task as passed instead of a waiting (indefinitely) for it to start.

**Comment by phraemer** [comment]
Can someone from GitHub at least tell us how likely we are to get this feature request implemented?

It's such an obvious win as far as many of us can tell but maybe there are difficulties we are unaware of.

**Comment by DARKo6o6o6** [comment]
I made this program I need help with the final part please help me

**Comment by ndiaz-addepar** [comment]
This has been opened for ***three years***  Is there going to be any progress here ?

**Comment by skst** [comment]
I think you answered your own question. 😉

**Comment by Kurt-von-Laven** [comment]
Recommend using either a script (Python, Bash, and PowerShell are supported) or a separate job for the steps the repeated if applies to as a workaround.

**Comment by user1689** [comment]
interested

**Comment by user1689** [comment]
Ref: https://github.blog/changelog/2023-09-21-github-actions-force-cancel-workflows/

**Comment by ljharb** [comment]
This is a pretty user-hostile way to close this issue (as any bot closure is); this issue has been opened for 4 years, so even quite inactive monitoring should have surfaced it to your team.

**Comment by Jackenmen** [comment]
Either way, it would be good to get people to move their upvotes to some common discussion on the [GitHub Actions product feedback discussion forum](https://github.com/orgs/community/discussions/categories/actions?discussions_q=is%3Aopen+category%3AActions+label%3A%22Product+Feedback%22) (putting a correct link here since the one given by the bot doesn't fully work) since that is in fact where they want all feature requests to go to nowadays.

As far as I can tell, there weren't any existing discussions there that would represent the same problem as this issue (there's https://github.com/orgs/community/discussions/67407 but it's a question, not an enhancement request) so I made one here, mostly just copy-pasting the description from the original comment by ylemkinon with a few added remarks:
https://github.com/orgs/community/discussions/82744

**Comment by ljharb** [comment]
@joshmgross since you directed people here in https://github.com/actions/github-script/issues/147#issuecomment-1009082845, is there any chance this could be reopened, or that https://github.com/orgs/community/discussions/82744 could be updated?

**Comment by silverqx** [comment]
Has anything changed about this? I'm searching for how to **successfully** exit the workflow in the middle to skip the rest of the steps. Is it possible?

**Comment by nsalfos** [comment]
> Has anything changed about this? I'm searching for how to **successfully** exit the workflow in the middle to skip the rest of the steps. Is it possible?

i dont think anything changed in GHA iteself... i might be wrong tho...
there is a way but is not pretty... you have to put a conditional for each step after the one you want to skip. 
like:

```
- name: I dont want anything to run after this
  id: boss-step
  run: |
    echo "somevar=false" >> $GITHUB_OUTPUT

- name: Some next step
  if : ( steps.boss-step.outputs.somevar  != 'false' ) 
  run: |
    echo "will only run if somevar is not false"
  
- name: Some other step
  if : ( steps.boss-step.outputs.somevar  != 'false' ) 
  run: |
    echo "will only run if somevar is not false"
```

and so on... for how many steps you have after your condition

**Comment by silverqx** [comment]
Ok, thx for reply, I have 27 steps to skip so this isn't a solution for my workflow. I will have to create a new workflow for this case.

**Comment by ArkadiuszMichalski** [comment]
I experienced the same problem myself. I am unable to terminate entire workflow as success without adding conditions in subsequent steps, which significantly obfuscates the entire code.

Closing this issue after a few years is not serious, considering how many people expect it.

**Comment by burhanyasar** [comment]
It might not fit all scenarios but in our similar too many if else case, it was possible to split the single pipeline to tag a new version on push and other pipelines would just run on a new tag, instead of checking an if statement.

**Comment by emilshr-sigtech** [comment]
Bumping this up as this is a very common use-case that the community is demanding.

**Comment by distante** [comment]
4 years on the making... :(

**Comment by silverqx** [comment]
They aren't making it 4 years. I think they don't do it because it doesn't fit nicely into the current code as it would need custom logic, something like an edge case, some coders don't like this and prefer the default behavior. Also, I think it would need to patch things all around to make this real.

**Comment by jerrygreen** [comment]
> 4 years on the making... :(

It's 6 or 7 years since they removed it. With no apparent reason.

**Comment by rodrigobrim** [comment]
Here's the solution:

```
- name: Early exit
  run: |
    gh run cancel ${{ github.run_id }}
    gh run watch ${{ github.run_id }}
  env:
    GH_TOKEN: ${{ secrets. GITHUB_TOKEN }}
```

Source: https://stackoverflow.com/a/75809743

**Comment by TWiStErRob** [comment]
@rodrigobrim that cancels the whole workflow and sets the conclusion to cancelled, right? The ask here is to pass a single job, but set the conclusion to success/failure.

**Comment by praxder** [comment]
Any updates on this??

**Comment by rmacklin** [comment]
@praxder The issue was closed because they want feature requests to be posted in Discussions rather than Issues (https://github.com/actions/runner/issues/662#issuecomment-1870709667). The corresponding Discussion thread is here: https://github.com/orgs/community/discussions/82744
If you want this feature, make sure to upvote that post.

**Comment by pboling** [comment]
Since commits and PRs don't get back links from Discussions those should still link here, so GitHub, and all of us, can see how much effort is going into working around the limitations of GHA. Maybe, hopefully, GitHub can be shamed into action?

**Comment by BattlefieldDuck** [comment]
This issue should be reopen

**Comment by tobiastornros** [comment]
Would be nice since we use turbo-ignore and sometimes want to exit early with success.

**Comment by nebuk89** [comment]
Re-opened, sorry this one got closed! We are aware and tracking this

**Comment by Master-Antonio** [comment]
please add the skip or stop bottom for job, actually i have a workflow in a loop, i need go to the step forward to save all, but is in a loop :( :( and i cant stop the job before, and if i cancel the workflow i lose all the datas.
