### ISSUE TITLE
Tracking: Composite Actions Polish

### ISSUE THREAD

**Issue by hross** [actions/runner#666]
This issue is tracking the remaining work to polish composite actions (and anything that comes up). So far there are a few bugs:

* [INPUT_* doesn't appear to be passed down](https://github.com/actions/runner/issues/665)
* [logs are out of order](https://github.com/actions/runner/issues/664)

And we also want to finish out the work to allow actions within actions. See this:

* [Remaining work for true composite actions](https://github.com/actions/runner/issues/646)

**Comment by Kampe** [comment]
Any word on this?  Looking forward to using the (full) feature!

**Comment by hross** [comment]
We have not been able to bite it off yet and will probably not be able to get to this in the coming month or so.

**Comment by thboop** [comment]
`uses` is now available for composite actions 🎉 , and the rest of these items have been addressed, closing this issue out in favor https://github.com/actions/runner/issues/646#issuecomment-901336347
