### ISSUE TITLE
Organization Runners do not show in repository settings > actions as being available to use.

### ISSUE THREAD

**Issue by timharris777** [actions/runner#668]
Organization runners do not show in repository `settings > actions` as being available to use. There is no way for engineers to know what organization runners are availalable for their repository to use without an org level admin looking it up in org `settings > actions` and letting them know.

My expectation is that the available org level runners would show in repo `settings > actions` similar to how available org level secrets show in repo `settings > secrets`.

**Comment by hross** [comment]
We know this is an issue and are working on adding org runners to the repository so you can view them. Expect this to land in the next few weeks (we are working on it now).

**Comment by timharris777** [comment]
Confirming that this is now showing in the UI. Thanks!
