### ISSUE TITLE
Very slow queuing with plenty of idle runners available

### ISSUE THREAD

**Issue by mhart** [actions/runner#676]
Originally posted here:

https://github.community/t/very-slow-queuing-behavior-when-idle-runners-are-available/127674

**Describe the bug**
When no other builds are running (all my runners are idle), there is very delayed behavior from GH actions before builds even start. This is especially noticeable with, for example, a 4^4 matrix (256 checks), even if you have 256 idle self-hosted runners.

The UI shows “X queued checks” at a rate of around 4 per second (ie, “4 queued checks”, “8 queued checks”, etc), before it finally gets to 256 checks queued. It takes a full 1min 40sec before the first of my runners even receives a message and starts building. It takes 12-13min for the entire run to be marked as finished, even if each build does no work and completes in 1sec or less.

**To Reproduce**
1. Register (and run) 256 self-hosted runners
2. Run a workflow that uses a 4^4 matrix:
```
    strategy:
      matrix:
        ix1: [ 0, 1, 2, 3 ]
        ix2: [ 0, 1, 2, 3 ]
        ix3: [ 0, 1, 2, 3 ]
        ix4: [ 0, 1, 2, 3 ]
```
3. Observe that it takes a long time before the first build message is sent to a runner
4. Observe how, even after all checks are completed, it still takes many minutes (10?) for the entire workflow to be marked as finished

You can also observe similar behavior with fewer checks – eg, even just 16 runners and a 4^2 matrix. Even then, checks are queued before the first build will start – and there's a noticeable delay after the 16th check has finished before the whole workflow is marked as complete. I see an overall run time of 1min10sec – even though each worker has completed its build in less than a second

**Expected behavior**
1. There should be no queueing when idle runners are available
2. Runners should receive build messages with no delay – within a few seconds at most.
3. Workflows should be marked as finished soon after the final check is complete.

## Runner Version and Platform
Checked 2.272.0 and 2.273.0

Checked on OSX and Linux

## What's not working?
This is not a problem with the runner (ie, the software in this repo) in any way as far as I can tell – it's purely behavior on the service-side that's causing this.

I suspect there's some sort of serial process that just gets compounded the more parallel jobs you have (which defeats the purpose of having parallel jobs in the first place)

**Comment by gierdo** [comment]
Our self-hosted runner infrastructure is scaling automatically, downscaling removes runners that have been idle for a certain amount of time. With sane idle time limits (~10 minutes), runners get terminated before jobs from our (ever growing) queue are assigned to them.

This issue costs us quite a bit of time and money.

**Comment by hross** [comment]
We have an internal ticket tracking this issue (related to the community feedback item). It is a back end infrastructure issue that we are working on but don't yet have a good solution for. Since it's not related to the runner, I'm going to close this issue (but we will keep an eye on the community feedback ticket and track this internally).

Thanks for bringing this up @mhart

**Comment by ahfarmer** [comment]
@hross This is still a problem over a year later - is work still being done here?

**Comment by MattChappleOVO** [comment]
Really interested with this. Is there any progress @hross ? 

We're in the process of setting up ephemeral runners in AWS with the Philips-Labs solution. Runners are created fine but the instances sit there ready for the job for an age. 

Best so far is 2mins, worst was over 25mins. The frustrating thing is that the job does eventually run, I'd almost prefer it didn't and errored with something to hang our hat on.

Any assistance or tweaks would be much appreciated.

**Comment by mytting** [comment]
The runner registered and idel was assigned a job 30 seconds later. Does this have anything to do with the `--ephemeral` argument?

**Comment by aktech** [comment]
Yes, it will be good to get some insight on this, this is the bottleneck for us at [Cirun.io](https://cirun.io). The fastest we can get a runner to start a job from the point of workflow trigger is 90 sec to 120 seconds, and delay by github is around 30 seconds on an average. If this gets resolved, [Cirun.io](https://cirun.io) will be able to spinup runners under 60 seconds.


Hey @MattChappleOVO 25 mins? how is that happening?

**Comment by ay0o** [comment]
We are also using AWS runners experiencing the same issue.

Usually, everything is working fine, then a random job takes 30 minutes to pick a runner, even though there are plenty available.

Definitively, it doesn't looks like an issue that should be in the "closed" state.

**Comment by aktech** [comment]
> then a random job takes 30 minutes to pick a runner,

@ay0o 30 minutes is a long time, what do you use to spin up runners? (We never had more than a couple of minutes delay)

**Comment by ay0o** [comment]
https://github.com/philips-labs/terraform-aws-github-runner

**Comment by royashbrook** [comment]
> even in 2023 the issue is still there :(

👆

**Comment by Jameswood-vega** [comment]
we also suffer from the same problem. 
we wait for 25 minutes for a task that takes 1/10 of a second to execute.

**Comment by ramones156** [comment]
been waiting 1.5 hrs and no runner is picking it up

**Comment by martin-nef** [comment]
Experiencing the same issue at the moment:

* Our GitHub hosted runner labeled "X" is fully available (ubuntu-latest, 4-core, 16GB, with a public IP)
* A job is labelled to run on "X" (triple-checked, there's no typo)
* This job has stuck on "Waiting for a runner to pick up this job..." for over 26 minutes.

**Comment by rattrayalex** [comment]
@hross or @rentziass,  could this issue be reopened? 

While @martin-nef 's issue may have been unrelated, this still happens sporadically for us and is very troubling.

**Comment by demeralde** [comment]
Same problem, is there any way to fix this?

**Comment by iamzoltan** [comment]
also have the same issue. our repo is in the correct runner group as well.

**Comment by cjackson234** [comment]
same issue here

**Comment by thibistaken** [comment]
Same issue here. Any workaround? Still stuck as `Waiting for a runner to pick up this job` for more than 1 hour 30 minutes and counting... thanks!

**Comment by TingluoHuang** [comment]
@thibistaken do you mind share more info about your runner that is waiting for job?
Ex: the runner name, and where it is configured to, org/repo url, the URL to the job that is waiting for the runner. 🙏

**Comment by thibistaken** [comment]
@TingluoHuang do you know where I can find such information? I cancelled the workflow run and did a second attempt, which worked. The first workflow only has "The run was canceled by @thibistaken." and when I click on more details I only see "This job was cancelled".

**Comment by cprey** [comment]
@hross or @rentziass can this issue be reopened?
We're using self-hosted runners and the wait time is often longer than the actual job. We're using autoscaling K8s runners and have plenty available.

**Comment by xavierrigau** [comment]
@hross or @rentziass I am seeing this issue every single day. We have plenty of runners doing nothing and jobs take 3m to start. 

I was trying to see why it was closed after being flagged as a bug and cannot find a documented resolution.

Could you guys please open it again and fix it and/or publish a good workaround? It is costing money and time to sit there waiting for jobs to start. TIA.

**Comment by procinger** [comment]
another me too 

We use the ephemeral runner with minReplicas 0 / maxReplicas 30 in a K3S setup. I see every day how several seconds, sometimes even minutes pass until a runner is scheduled and spawns.

We also have a few VMs (different datacenter / region) for legacy stuff with the normal runner, which is permanently waiting for jobs. This also shows the same behavior, it sometimes takes ~2 min until it finally picks up the job and no the runner is not busy, it idles.

I would be happy if the problem could be picked up again.
Thank you

**Comment by xavierleune** [comment]
Hi there,
It's been a few months since the last comment, so I think we might follow up here ^^
This is still a thing at this date, even with an organization runner. Maybe @TingluoHuang or @heavymachinery have some feedback to share ?
Thanks 🙏

**Comment by naueramant** [comment]
Still a thing, @github could you please look into this?

**Comment by agoodkind** [comment]
Any updates? Still an issue.

**Comment by dkachur1** [comment]
Any updates on this?
