### ISSUE TITLE
Pi Zero W: ./config.sh: line 79:  6312 Segmentation fault ./bin/Runner.Listener configure "$@"

### ISSUE THREAD

**Issue by Ryazbeck** [actions/runner#688]
**Describe the bug**
Going through the steps to add self-hosted runner on a Raspberry Pi Zero W. Apologies if this is the wrong repo. I spent some time searching and couldn't find an answer.

**To Reproduce**
1. Run this on a Raspberry Pi Zero W
```
mkdir actions-runner && cd actions-runner
curl -O -L https://github.com/actions/runner/releases/download/v2.273.0/actions-runner-linux-arm-2.273.0.tar.gz
tar xzf ./actions-runner-linux-arm-2.273.0.tar.gz
./config.sh --url https://github.com/Ryazbeck/ygwifi --token *
```

**Expected behavior**
./config.sh to run successfully

## Runner Version and Platform
Not installed

## OS of the machine running the runner?
Raspbian lite
> Linux raspberrypi 4.19.118+ #1311 Mon Apr 27 14:16:15 BST 2020 armv6l GNU/Linux

## What's not working?
> pi@raspberrypi:~/actions-runner$ ./config.sh --url https://github.com/Ryazbeck/ygwifi --token *
> ./config.sh: line 79:  6430 Segmentation fault      ./bin/Runner.Listener configure "$@"

**Comment by Ryazbeck** [comment]
Dotnet doesn't work on armv6

https://github.com/dotnet/runtime/issues/3013#issuecomment-584588214

**Comment by TingluoHuang** [comment]
@CrabbyPete  yes.
