### ISSUE TITLE
svc.sh Missing from tarballs

### ISSUE THREAD

**Issue by whyman** [actions/runner#690]
**Describe the bug**
`./svc.sh` seems to be missing. As per the docs, this should be used to install a systemd service

**To Reproduce**
1. Download the linux x64 release
2. No file present

**Expected behavior**
file to present

## Runner Version and Platform
Version of your runner? 2.273.0

OS of the machine running the runner? Linux

## What's not working?
File not found

## Job Log Output
N/A
## Runner and Worker's Diagnostic Logs
N/A

**Comment by juliobbv** [comment]
@whyman the `./svc.sh` script does not come in the tarball itself, but instead, it's generated from a template. You can generate the file by running `./config.sh` and responding 'yes' when the config process asks you to install the runner as a service.

**Comment by juliobbv** [comment]
I'm closing the bug with some instructions. @whyman, let me know if you have any questions.

**Comment by whyman** [comment]
Thanks for the information! Would it be good to put that information into the docs somewhere? Or I am just blind?

**Comment by rviscuso** [comment]
Also worth noting that `svc.sh` only gets created if you run `config.sh` as root. 

Example command from https://github.com/actions/runner/blob/main/scripts/create-latest-svc.sh
```sudo -E -u ${svc_user} ./config.sh --unattended --url $runner_url --token $RUNNER_TOKEN --name $runner_name --labels $labels```
