### ISSUE TITLE
2.273.1 appears to break pipenv/python

### ISSUE THREAD

**Issue by JohnPeacockMessageSystems** [actions/runner#705]
**Describe the bug**
Beginning Sept 11, formerly working actions started failing with mysterious Python/pipenv errors. After much debugging, it was determined that one of the job cleanup routines was deleting all files but not directories under github_home/.local/share, which specifically breaks pip/wheel/pipenv. Since we have the runner local, I was able to watch the directories themselves (.local/share/virtualenv and .local/share/virtualenvs) and the cached files exist until the Post Checkout phase executes. 

**To Reproduce**
1. Add the https://github.com/SparkPost/github-action-tester-python
2. Add any Python test plan in .github/run-tests.sh, e.g.
```cd path/to/test
pipenv install
pipenv run pytest```

Note that you have to have an existing `Pipfile` with packages to install.

3. You can run the tests multiple times in a single action plan, but only the first time. You will get mysterious errors about missing files because pip/wheel expect to find files under images in the share/virtualenv folder that were deleted during the previous run's Post Checkout cleanup phase.

**Expected behavior**
Either
a. only the ./local/share/virtualenvs directory for this run is deleted
b. all files AND directories under ./local/share are deleted

## Runner Version and Platform
2.273.1

OS of the machine running the runner?
Amazon Linux 2 (equivalent to RHEL7)

**Comment by JohnPeacockMessageSystems** [comment]
You'll have to use `SparkPost/github-action-tester-python@v1.0` for testing since I added a workaround to delete the directory tree that was causing problems in v1.1

**Comment by nikola-jokic** [comment]
Hey @JohnPeacockMessageSystems,

Are you still experiencing this issue with the newest version of the runner?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
