### ISSUE TITLE
Are notice annotations currently supported?

### ISSUE THREAD

**Issue by xt0rted** [actions/runner#707]
When creating annotations with the api it supports the levels `notice`, `warning`, and `failure`. [Using commands](https://github.com/actions/toolkit/blob/main/docs/commands.md#log-level) we can create `warning` and `error` (`failure`) annotations. Is there a way to create `notice` annotations with commands or is that not currently supported?

**Comment by thboop** [comment]
Hey @xt0rted , Notice annotations are not currently supported through commands. I've tagged this as an enhancement, we are aware of this feature!

You can create notice annotations through the api if needed!
