### ISSUE TITLE
Intermittent failure of gcc compilation on ubuntu-20.04 runner

### ISSUE THREAD

**Issue by starseeker** [actions/runner#718]
**Describe the bug**

Observing an intermittent gcc compilation failure on ubuntu-20.04, version 20200914.1 that appears to be unrelated to any changes to project source code or build setup on our part.

**To Reproduce**
1. Set up Actions CI testing for BRL-CAD C/C++ project with code at https://github.com/starseeker/cadcitest using the following setup: https://github.com/starseeker/cadcitest/blob/master/.github/workflows/btest.yml
2. Push trivial change to text file or some other change to trigger tests.
3. Occasionally (not all the time) we get a failure in the build step, which doesn't seem related to our code changes.

**Expected behavior**
Deterministic compilation success or failure consistent with expected environmental and code behaviors.

## Runner Version and Platform
Latest Github production runner, ubuntu-20.04, version 20200914.1

OS of the machine running the runner? OSX/Windows/Linux/...
Linux (default Github runner environment...)

## What's not working?
When pushing changes to trigger testing actions, we are seeing occasional failures on the Linux runner early in the build step that do not appear to be related to changes in our code. 

The failure is seen building a single self-contained C file program - the detailed failure is shown below.  
(I have also seen a failure mode where the linker doesn't report a failure but a subsequent build step attempting to use the binary fails to run it with a "permission denied" error.)

On some occasions re-running the job (without performing any commits at all to the repository) results in a success - that would seem to suggest the failure is either a dependency issue of some sort in our build setup or some variation in the environment.  The former is possible but would be surprising to me - with a single C file, there isn't a lot that we control manually about dependency management.

Is there any chance that some issue with I/O in the runner VM could result in a not-fully-written .o file that would cause a linker failure?  Or perhaps a delay in fully writing the .c file that could result in it getting compiled to a .o file without it's contents?  To the best of my knowledge this is not a failure we have ever observed on non-VM compilation environments, so I'm at a bit of loss when it comes to trying to diagnose it.

## Job Log Output
2020-09-23T14:46:48.4904229Z [5/3576] /usr/bin/gcc  -Iinclude/brlcad -w -fPIE -std=gnu99 -MD -MT misc/tools/lemon/CMakeFiles/lemon.dir/lemon.c.o -MF misc/tools/lemon/CMakeFiles/lemon.dir/lemon.c.o.d -o misc/tools/lemon/CMakeFiles/lemon.dir/lemon.c.o -c ../misc/tools/lemon/lemon.c
2020-09-23T14:46:48.5874958Z [6/3576] : && /usr/bin/gcc -w -m64 -g -ggdb3    -rdynamic misc/tools/lemon/CMakeFiles/lemon.dir/lemon.c.o -o bin/lemon   && :
2020-09-23T14:46:48.5875972Z FAILED: bin/lemon 
2020-09-23T14:46:48.5877163Z : && /usr/bin/gcc -w -m64 -g -ggdb3    -rdynamic misc/tools/lemon/CMakeFiles/lemon.dir/lemon.c.o -o bin/lemon   && :
2020-09-23T14:46:48.5878511Z /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
2020-09-23T14:46:48.5879655Z (.text+0x24): undefined reference to `main'
2020-09-23T14:46:48.5880307Z collect2: error: ld returned 1 exit status

**Comment by starseeker** [comment]
Possibly relevant context - the overall build of which the above is a part is being launched in parallel.

**Comment by starseeker** [comment]
Update - seeing a similar failure building single-threaded (not identical, but also seems to be related to files not being fully written out before the next build step is launched).

**Comment by ethomson** [comment]
Hi @starseeker - apologies for the delay, I'm trying to take a pass through the bug reports.

Curious if you figured this problem out?  I'm also puzzled looking at the report.  However, this does not appear to be related to the runner _application_, even if there's a problem with the GitHub hosted runner.  I'm going to close this and suggest that you post in the [support forum](https://github.community/c/code-to-cloud/github-actions).

Please let me know if you do, I'd like to dig in on this.
