### ISSUE TITLE
github project repo name is creating twice and after cloned repo via API getting error as its not a gitrepo 

### ISSUE THREAD

**Issue by chaitanya-bojja-by** [actions/runner#719]
**Describe the bug**

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by ethomson** [comment]
I'm afraid that I don't see a bug report here, it looks like you've just kept the issue template as-is.  Please feel free to open a new issue with the requested details if you're encountering a problem.
