### ISSUE TITLE
Question: Is it possible to run the runner for only one job in queue so I can stop virtual machine and setup new one a fresh one.

### ISSUE THREAD

**Issue by pekhota** [actions/runner#720]
I'm trying to implement the github flow when for each flow then new virtual machine is going to run up. I can automate instance creation, etc but I can't figure out how to proceed only one flow and then setup new virtual machine for another. Any help please?

**Comment by j3parker** [comment]
Watch this PR: #660

**Comment by pekhota** [comment]
@j3parker thank you so much! It helped me a lot!
