### ISSUE TITLE
Job failed on Ubuntu 20.04 runner

### ISSUE THREAD

**Issue by BrightRan** [actions/runner#724]
Associated GitHub Community ticket: https://github.community/t/ubuntu-runner-prematurely-shutdown/134665

In the customer's workflow, he set a matrix to run job on different OSs. The job always is failed on **`Ubuntu 20.04`**, and returns the following error message:
> The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.

**Comment by nikola-jokic** [comment]
It seems like [petersteneteg](https://github.community/u/petersteneteg) fixed this issue so we can close it.
