### ISSUE TITLE
"Re-run all jobs" button does not generate worklow_run.requested event.

### ISSUE THREAD

**Issue by timharris777** [actions/runner#726]
**Describe the bug**
When someone clicks the "re-run all jobs" button on a github action workflow, the `workflow_run.requested` event is not triggered.

This is an issue for us because we have created a custom github app that will cancel workflow_runs if the last person to edit the workflow file is not an admin on the repo. We are doing this because github has not provided a solution for our security concern outlined in the following issues:

https://github.com/actions/runner/issues/458
https://github.com/actions/runner/issues/494

My solution works great, except that when a workflow is cancelled any user can go re-run the cancelled workflow and we are not able to intercept that run and cancel it because the "re-run all jobs" button does not seem to trigger any events.

**To Reproduce**
1. Subscribe to workflow_run events.
2. Run a workflow and you will see workflow_run:requested and then workflow_run:complete events.
3. Now click the "Re-run all jobs" button
4. You will see no events triggered.

**Expected behavior**
I would expect the "re-run all jobs" button to trigger the `workflow_run:requested` event:action since it is actually doing that. Or at least another comparable event:action should be triggered.

## Runner Version and Platform
- Github hosted runners is where this has been tested. It looks like it does the same on all though.

**Comment by timharris777** [comment]
@mikedrexler, keeping you in the loop.

**Comment by mikedrexler** [comment]
Thank you for the mention, @timharris777 !  Have you also opened a support ticket?  If so, what is that number?  Considering the circumstances, I would expect them to support this as a High Priority ticket.  From what you've shared, I would agree with your expected behavior.

**Comment by mikedrexler** [comment]
Hi @timharris777 !  I've also opened a thread in the appropriate channel to see if there may be an alternate action that is being triggered in your scenario.  Stay tuned...

**Comment by timharris777** [comment]
After further troubleshooting it looks like when workflows are triggered without the "re-run all jobs" button I get a ` workflow_run:requested` and `check_run:created` followed by a `workflow_run:completed` and `check_run:completed` event and action.

Whenever I use the “re-run all jobs” button I get `check_run:created` followed by a `workflow_run:completed` and `check_run:completed`

It’s missing the `workflow_run:requested` event

**Comment by eladchen** [comment]
Ah! I actually experienced the same issue myself.

https://github.community/t/event-workflow-run-is-only-triggered-once/133950/2

**Comment by eladchen** [comment]
Hi

Is that something we can keep track of? Or is that internal?

> Hi @timharris777 ! I've also opened a thread in the appropriate channel to see if there may be an alternate action that is being triggered in your scenario. Stay tuned...

**Comment by timharris777** [comment]
@eladchen , I think it's internal. I also opened an enterprise support ticket and they responded and said it was not currently supported, which wasn't very helpful. I'm working on some code that will use the `check_run:created` event:action to find the related workflow_run id. If I can figure out a reliable way to reconcile the two then I'll share it with you.

**Comment by timharris777** [comment]
@eladchen , if you trigger off of the `check_run:created` event:action you can get `check_run.check_suite.id` and then list workflow_runs for your repository using this (https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#list-workflow-runs-for-a-repository) and then filter the list of workflows down to the one where the `"check_suite_id"` matches what you pulled from the `check_run:created` payload. Hope that helps you workaround this.

**Comment by eladchen** [comment]
Awesome! Thank you for sharing.

**Comment by virgofx** [comment]
Just experienced this issue as well. Using the "Re-run all jobs" is a very handy feature to retrigger a workflow via the UI without having to create another commit. Would expect the workflow to dispatch the `workflow_requested` event as well.

**Comment by omeraplak** [comment]
I have noticed that this problem has been fixed in cloud runner. Those who follow this thread like me can check it out. 🥳

**Comment by timharris777** [comment]
> I have noticed that this problem has been fixed in cloud runner. Those who follow this thread like me can check it out. 🥳

No way, I'll definitely check it out. I had quite the workaround because of this issue. Thanks for the heads up!

**Comment by ruvceskistefan** [comment]
Hel all, 

This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃

**Comment by thapaashesh** [comment]
All, 

I used to have a 'Re-run all jobs' button in my GitHub runner, but it seems to have disappeared. I would appreciate any help in finding out how to get this button back.
