### ISSUE TITLE
Action branch names with / broken in 2.273.4?

### ISSUE THREAD

**Issue by j3parker** [actions/runner#736]
As of today if our actions come from a branch on a repo with `/` in the branch name it fails with errors like this:

```
Unable to resolve action `Brightspace/third-party-actions@actions/checkout`, repository not found
```

We do this a lot because we mirror third-party-actions into branches in a central repo in our org (more context [available in the README](https://github.com/Brightspace/third-party-actions)).

We're seeing it fail on v2.273.4 runners, at least.

I see a lot of `.Split( '/' )` in here, but I haven't finished investigating: https://github.com/actions/runner/compare/v2.273.3...v2.273.4#diff-488a6cefa4a643b9314f32898b46937eR51

**Comment by j3parker** [comment]
We're seeing this happen in some repos but not others, all with 2.273.4 🤔

**Comment by j3parker** [comment]
```
Current runner version: '2.273.4'
Runner name: 'i-01bea0d66428dd4f2'
Machine name: 'ip-10-0-3-21'
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `Brightspace/third-party-actions@actions/checkout`, repository not found
Unable to resolve action `Brightspace/third-party-actions@actions/github-script`, repository not found
Retrying in 21 seconds
Failed to resolve action download info. Error: Unable to resolve action `Brightspace/third-party-actions@actions/checkout`, repository not found
Unable to resolve action `Brightspace/third-party-actions@actions/github-script`, repository not found
Retrying in 26.719 seconds
```

We're seeing it consistently fail in some repos and not in others. The `/` appears to be important but I'm double checking that.

**Comment by j3parker** [comment]
This diff fixes a broken repo:

![image](https://user-images.githubusercontent.com/597907/94963863-c4feca00-04c6-11eb-8a61-72b0cd5d4723.png)

We've reproduced it failing with `/`s and changing them to `-` and it appeared to work.

It seems like the problem is sticky per-repo, even after destroying and recreating the runner VMs. Could this be something on the backend? E.g. we're seeing it

* Fail in [Brightspace/github-actions-infrasctructure](https://github.com/brightspace/github-actions-infrastructure)
* Work in [Brightspace/bdp-ingestion](https://github.com/Brightspace/bdp-ingestion)

(both of these are private repos)

**Comment by j3parker** [comment]
Similar sounding thing: https://github.community/t/setup-job-action-is-failing-on-certain-repos/135118
(they also have `/`s in their branch name...)

**Comment by j3parker** [comment]
Here's a public repo that is _not_ using our self-hosted runners but is failing: https://github.com/Brightspace/brightspace-integration/runs/1200341852?check_suite_focus=true

**Comment by iheanyi** [comment]
👋🏾  Hello there from the Actions team, thanks for reporting this! I will take a look and see what I can find.

**Comment by bricker** [comment]
I can confirm this issue.

* When pointing at `bricker/github-actions/gcloud-sdk@bcr/202007/creds_path`, I get the error mentioned in this issue:

```
Unable to resolve action `bricker/github-actions@bcr/202007/creds_path`, repository not found
```

* When pointing at `bricker/github-actions/gcloud-sdk@BCR-creds_path`, the action is loaded and runs normally.

**Comment by pjquirk** [comment]
Sorry for the trouble, we identified a bug in a change we rolled out to the Actions Service that caused this and rolled it back.  The runner is fine to continue using as-is.  Thanks again for reporting this and let us know if you continue to see the issue!

**Comment by j3parker** [comment]
Thanks!!
