### ISSUE TITLE
Self-hosted runner failed to update itself from 2.273.4 -> 2.273.5 bug

### ISSUE THREAD

**Issue by deeno35** [actions/runner#739]
**Describe the bug**
Auto update from 2.273.4 -> 2.273.5 resulted in the runner process crashing.  Multiple attempts to restart it failed in the same way.  

**To Reproduce**

**Expected behavior**
Updates should act seamlessly or self heal (ie update failed before, skip this version and just start back up).

## Runner Version and Platform
Version of your runner? 2.273.4

OS of the machine running the runner? Amazon linux (EC2)

## What's not working?
2 problems during update:
```
Oct  5 16:40:40 ip-172-31-52-163 dhclient[3613]: XMT: Solicit on eth0, interval 119690ms.
Oct  5 16:07:09 ip-172-31-52-163 run.sh: /home/ec2-user/actions-runner/_work/_update.sh: line 31: nul: Permission denied
Oct  5 16:07:09 ip-172-31-52-163 run.sh: /home/ec2-user/actions-runner/_work/_update.sh: line 31: nul: Permission denied
Oct  5 16:07:09 ip-172-31-52-163 run.sh: /home/ec2-user/actions-runner/_work/_update.sh: line 31: nul: Permission denied
Oct  5 16:07:09 ip-172-31-52-163 systemd: github_action_runner.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
Oct  5 16:07:09 ip-172-31-52-163 systemd: Unit github_action_runner.service entered failed state.
Oct  5 16:07:09 ip-172-31-52-163 systemd: github_action_runner.service failed.
```
Maybe consider using /dev/null?  changing perms on /nul to have writable by all fixed it, but it's not good to be dumping files on the root partition anyhow.  At least I would suggest using /tmp vs local dir (which becomes "/" when running daemonized)

2nd prob (the real prob)
```
Oct  5 16:49:39 ip-172-31-52-163 run.sh: √ Connected to GitHub
Oct  5 16:49:40 ip-172-31-52-163 run.sh: 2020-10-05 16:49:40Z: Listening for Jobs
Oct  5 16:49:43 ip-172-31-52-163 run.sh: Runner update in progress, do not shutdown runner.
Oct  5 16:49:43 ip-172-31-52-163 run.sh: Downloading 2.273.5 runner
Oct  5 16:49:49 ip-172-31-52-163 run.sh: Waiting for current job finish running.
Oct  5 16:49:49 ip-172-31-52-163 run.sh: Generate and execute update script.
Oct  5 16:49:49 ip-172-31-52-163 run.sh: Runner will exit shortly for update, should back online within 10 seconds.
Oct  5 16:49:49 ip-172-31-52-163 systemd: github_action_runner.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
Oct  5 16:49:49 ip-172-31-52-163 systemd: Unit github_action_runner.service entered failed state.
Oct  5 16:49:49 ip-172-31-52-163 systemd: github_action_runner.service failed.
```
Looks like the update to 2.273.5 is failing.  It was repeatable, in the end I downloaded the 2.273.5 tar ball manually, untarred on top of my current install and that started up just fine.

**Comment by thboop** [comment]
Hey @deeno35 thanks for filing this issue!
For the second problem, how are you starting the runner?

If running as a service, you need to invoke the runner via the `runsvc.sh` entrypoint or else it will fail to auto-update. We have more information on this in our [docs](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service#customizing-the-self-hosted-runner-service-1)

**Comment by deeno35** [comment]
Oh great, looks like it's all wrapped up now as a service and I can just use that instead.  I had made a quick systemd wrapper to run it so it starts when the ec2 instance starts.

**Comment by deeno35** [comment]
I took a quick peek at runsvc.sh, it's still not quite set up to run daemonized as there are local path references.  In particular this is problematic.  
```
./externals/node12/bin/node ./bin/RunnerService.js &
```
It will work out better to use the path of the current script there (like `dirname $0) instead of the relative path as not all scripts will be executed from the install dir of github actions.
