### ISSUE TITLE
Reuse/import workflows

### ISSUE THREAD

**Issue by fregante** [actions/runner#748]
**Describe the enhancement**

Workflows tend to grow large once you start splitting some steps to run in separate jobs. Some other workflows are inherently large because they do a lot.

In many cases, I reuse the [same workflow](https://github.com/notlmn/browser-extension-template/blob/master/.github/workflows/deployment.yml) in multiple repositories and I wish I could just import it instead of copy-pasting it and manually updating it everywhere.

**Code Snippet**

I wish I could just use this in a workflow file:

```yml
import:
  - use: fregante/workflows@v1
    file: webextension-deployment.yml
```

and this would work as if I copied the whole file.

**Comment by sindresorhus** [comment]
The biggest reason I'm currently staying on Travis CI for existing projects is that the same config for GitHub Actions is more verbose and boilerplaty. Would be nice if workflows could be reused across repos.

**Comment by MarcosCela** [comment]
This will be a game changer to manage workflows on a big org.

**Comment by trevorbaca** [comment]
This would be great. Something like Travis's import command.

My workaround in GitHub actions is currently just a hard link in the to-be-tested repo.

**Comment by fregante** [comment]
I ended up writing my own tool to store my workflows in a repo and easily download/update them elsewhere:

https://github.com/fregante/ghat

**Comment by fidou** [comment]
Hi, I would like to use this functionality also from the same repo. 
I am currently using github environments to deploy by executing 20 steps to deploy in an environment, and I have to do this 3 times (with slightly different parameters) on development, test and production. 
It would be nice to reuse workflow working without the need of the central workflow library as my steps are very specific to my repository and my application.

**Comment by acobaugh** [comment]
IMO, the recently-released "Reusable Workflows" aren't really what this part of the community was looking for. As implemented, those appear to be just "workflows that can be called by other workflows with clearly defined input/output boundaries". The boilerplate still needs to be copied around to every repo, so they don't really do much to keep the per-repo yaml DRY.

However, similar to the OP's case, tools like Gitlab CI can do something like this:
```
include:
  - project: ci/gitlab-ci-templates
    ref: master
    file: helm-charts/.gitlab-ci.yml
```

and then nothing else needs to be placed in `.gitlab-ci.yml`. You can still override `env` locally. Gitlab also supports an `extends` keyword, so you can centrally define jobs, then reuse those jobs with `extends` while overriding different parts of those jobs for special cases.

Workflow Actions are sooo close. I think `include`/`import` function would knock github out of the park.

**Comment by iiro** [comment]
Completely agree with all of you on this. Not sure would this help everyone here, but have you seen this: https://github.com/github/roadmap/issues/52 ? I was hoping to see this happening on Q2 next year but, now it's postponed to "Future" :/

I guess we have to try to use the "Reusable Workflows" for time being... For us, that should work pretty well though.

**Comment by acobaugh** [comment]
I hadn't seen https://github.com/github/roadmap/issues/52, but that looks like it's a universal "run this workflow on all repos", which isn't quite what I want. I want to define a workflow per language or project type, then reuse the entire workflow yaml file across multiple repos.

I think Reusable workflows are nice for some use cases, but because they don't inherit `on` or `jobs` or `env`, they're really just externally-defined workflows you trigger from locally-defined workflows. IMO, `on`, `job`, and `env` need to be reusable, too, to really be useful.
