### ISSUE TITLE
Setting strategy.matrix to variable value returns a "invalid workflow file" error

### ISSUE THREAD

**Issue by petreboy14** [actions/runner#751]
**Describe the bug**
It seems that we can no longer set `matrix.strategy` to an output of a previous job. Trying to do so will cause the job to immediately fail with a "Invalid Workflow file" error. 

**To Reproduce**
1. Use the example from the Context and Expression syntax guide from the GitHub Actions docs (https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6) 
2. Push up to any repo
3. The workflow file error will come up immediately

**Expected behavior**
There should not be a workflow file error unless something has changed about matrix variables/syntax

## Runner Version and Platform
Version of your runner? ubuntu-latest

## What's not working?
An example can be found [here](https://github.com/petreboy14/test/actions/runs/296426374 )
The error text is:
"Invalid workflow file
You have an error in your yaml syntax on line 15"

## Job Log Output
No job log output as the jobs never run

## Runner and Worker's Diagnostic Logs
No diagnostic logs available

For reference here is the example from the docs pasted fully:
```
name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: build

**Comment by tianon** [comment]
The failure mode on PRs is especially awkward -- it doesn't list a failed check, but rather just ignores the checks completely (so the PR looks "green" even though some of the checks are completely ignored). :disappointed:

**Comment by mattcat10** [comment]
We are seeing the same as well

**Comment by sindrig** [comment]
According to @cschleiden this should have been resolved. See discussion here: https://github.community/t/dynamic-matrix-yaml-syntax-error/136705/7

We would like some kind of an explanation and/or what will be done to prevent something like this again.

**Comment by tianon** [comment]
"Ran 28 seconds ago" -- https://github.com/docker-library/official-images/actions/runs/302561117

I don't believe this is completely fixed. :disappointed:

**Comment by tianon** [comment]
We've got a PR from four hours ago (https://github.com/docker-library/official-images/pull/8883) which doesn't have any Actions checks due to this (and several others, but that's the most recent).  Every PR I merge there ends up emailing me with that action "failing" (which if it were parsing the YAML properly, wouldn't even be trying to run on a merge since it only triggers on PRs).

**Comment by cdb** [comment]
We have rolled out 2 bug fixes now, to cover both the cases in this issue (`matrix: ${{ expression }}`, and `strategy: ${{ expression }}`, and have added additional unit test coverage. Thanks for reporting this and let us know if you continue to see the issue!

**Comment by pakalas** [comment]
Hi, 
Getting "Invalid type found: array was expected but string was found" at ${{fromJson(needs.setup.outputs.matrix)}}
Why is this happening (used to work as of yesterday)?

`name: default

on:
  workflow_dispatch:
  
jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo '::set-output name=value::[\"a\", \"b\", \"c\"]'
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"`

**Comment by ruvceskistefan** [comment]
First of all, thank you all for your contribution. Since another issue related to this has been reported (thank you both @pakalas and @nikola-jokic), I think it makes sense to close this issue and move all communication to a newer issue [#1660](https://github.com/actions/runner/issues/1660).

Feel free to reopen this issue if needed, or better switch to the newer issue.
