### ISSUE TITLE
Have disabled self-hosted runners on public repositories, but the runners still are listed on the settings page of the public repositories

### ISSUE THREAD

**Issue by BrightRan** [actions/runner#758]
Associated GitHub Community topic: https://github.community/t/self-hosted-runners-are-not-visible-to-github-actions-workflows-in-public-repositories-by-default-no-runner-matching-the-specified-labels-was-found/137827

We can see the option "**Allow public repositories**" for the groups of organization level self-hosted runners.
![group-setting](https://user-images.githubusercontent.com/46307996/96092467-7fe28b00-0efd-11eb-9bbb-053af2cd0e08.PNG)

If disable this option, the public repositories in the organization will not be allowed to use the self-hosted runners in the group.
But these runners still are listed on the settings page of the public repositories.
![repo-settings](https://user-images.githubusercontent.com/46307996/96093045-41010500-0efe-11eb-8f06-21943e401138.PNG)

This will mislead the user that these self-hosted runners are still can be used in the public repositories. But when try to use these self-hosted runners to run the workflows in the public repositories, it will return "Not Found" error like as below:
```sh
No runner matching the specified labels was found: self-hosted.
```

I think, if we select not allow public repositories to use the self-hosted runners of a group, this group should be hidden instead of still displaying it on the settings page of the public repositories.

**Comment by ruvceskistefan** [comment]
Hi @BrightRan,

This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. I see that there is already an issue reported on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52), so I've also gone ahead and notified the team responsible for this area of the issue.
Thank you for the report.

**Comment by lrotschy** [comment]
I'm not having success reproducing this issue. Let me know if I have missed something in the setup. I have another idea that I will test out as well.


Here is what I did:

1. Setup
Create a public repo and a private repo within an org.
In the org, create a private runner group with all repositories selected.
In the org, create a runner group that is available to public repos with all repositories selected.
In the org, set default runner group to all repos, excluding public.
In the org, create a self hosted runner in each of the above groups, and one in the default group. 

In public-repo runners list: no runners listed

In private-repo runners list: all three runners listed

2. Edit private runner group to allow public.

Runner in "private group" appears in public repo.

3. Edit private runner group to disallow public.

Runner does not appear in public repo.

**Comment by lielaedel** [comment]
@BrightRan, you were able to reproduce this, right? Could you send me the url of the page the screenshot was taken from?

**Comment by lrotschy** [comment]
@BrightRan, you said you could reproduce this, right? Could you post the URL of the page where the screenshot was taken?

**Comment by lrotschy** [comment]
Based on the date of this issue and the fact that I was unable to reproduce it in production (both in my staff account and a test account without custom-hosted runners enabled), I think this issue has been resolved in the course of work on the runners UI in the last year.
