### ISSUE TITLE
Proxies with port 80 are stripped of their port

### ISSUE THREAD

**Issue by JasonLaquaTR** [actions/runner#759]
**Describe the bug**
Proxies are stripped of their port if it is 80. This causes anything that uses libcurl to fail because it's default proxy port is 1080.

**To Reproduce**
1. Setup self-hosted runner
2. Add https_proxy with port 80 in .env file (ex. `https_proxy=http://proxy:80`)
3. Start runner
4. Configure and run workflow to use something that uses libcurl (ex. checkout plugin)
5. See operation timeout error with proxy port set to 1080
6. You can also print the environment variables and see that port 80 has been stripped from https_proxy

Related Issue: [actions/checkout#216](https://github.com/actions/checkout/issues/216)

**Expected behavior**
Keep port 80 as a part of the proxy environment variable

## Runner Version and Platform
Version of your runner?
2.273.5
OS of the machine running the runner? OSX/Windows/Linux/...
OSX and Linux
## What's not working?
Environment variable is being stripped of proxy port
Expected
```
http_proxy=http://proxy:80
HTTP_PROXY=http://proxy:80
https_proxy=http://proxy:80
HTTPS_PROXY=http://proxy:80
```
Actual
```
http_proxy=http://proxy/
HTTP_PROXY=http://proxy/
https_proxy=http://proxy/
HTTPS_PROXY=http://proxy/
```
## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.
```
fatal: unable to access 'https://github.com/actions/runner.git/': Failed to connect to proxy port 1080: Operation timed out
The process '/usr/bin/git' failed with exit code 128
```

## Code causing problem
[RunnerWebProxy.cs:72-130](https://github.com/actions/runner/blob/2709cbc0eae592e6004b016c52c04382f19c7683/src/Runner.Sdk/RunnerWebProxy.cs#L72)

**Comment by mayur-kumar1** [comment]
@JasonLaquaTR Looks like its still happening with v2.294.0. We have a few self-hosted runner pods running on GKE. We are behind a corporate proxy, but the proxy still changes to 1080.
the http_proxy variable is `http://ep.threatpulse.net:80`

`Error: fatal: unable to access 'https://github.com/lbg-gcp-foundation/***-android-core/': Failed to connect to ep.threatpulse.net port 1080: Operation timed out` 

Do I need to do something at my end to resolve this?

**Comment by SCE-sotoodaa** [comment]
Also running into this same issue as of today with version v2.308.
@mayur-kumar1 were you able to find a workaround or resolution for this?
