### ISSUE TITLE
Bad tokens being passed to runners, resulting in 401 errors

### ISSUE THREAD

**Issue by mhart** [actions/runner#769]
**Describe the bug**
We see 401 errors in the setup portions of our actions, especially when trying to download action tarball URLs like `https://api.github.com/repos/actions/checkout/tarball/a81bbbf8298c0fa03ea29cdc473d45769f953675`, and especially in workflows with a number of jobs (~20). It doesn't happen every build, but happens frequently enough to be annoying.

Examples can also be seen around the web of this happening to others:

- https://github.com/tailscale/tailscale/actions/runs/92926574
- https://github.community/t/failure-during-job-set-up/16142
- https://github.com/fastai/fastai2/actions/runs/25226353

## Runner Version and Platform
Version of your runner? 2.273.5

OS of the machine running the runner? Linux

## Job Log Output

```
Current runner version: '2.273.5'
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2'
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/a81bbbf8298c0fa03ea29cdc473d45769f953675'. Error: Response status code does not indicate success: 401 (Unauthorized).
Warning: Back off 18.746 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/a81bbbf8298c0fa03ea29cdc473d45769f953675'. Error: Response status code does not indicate success: 401 (Unauthorized).
Warning: Back off 18.006 seconds before retry.
Error: Response status code does not indicate success: 401 (Unauthorized).
```

## Suggestions

EDIT: a previous version of this description had presumed it was due to rate-limiting, but subsequent debugging has shown it's actually bad tokens being passed to the runners and the 401s are actually `Bad credentials` errors.

So I'm not sure what to suggest here beyond:

- Don't pass bad/expired tokens to runners (still unclear why this is happening – why aren't the tokens valid?)
- Provide better debugging of errors (include response bodies)
- Provide a way to debug tokens, and why api.github.com would be returning `Bad credentials` for them.

**Comment by mhart** [comment]
I've modified the source code to add some logging for these errors. The cause in most cases seems *not* to be rate limits, but rather a cryptic `Bad credentials` error:

```json
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

This happens, even when just downloading URLs like `https://api.github.com/repos/actions/checkout/tarball/a81bbbf8298c0fa03ea29cdc473d45769f953675`

Can anyone shed some light on why `api.github.com` might return this error? The token should be added as per:

https://github.com/actions/runner/blob/5ba7affea4d039fac1014876bc57aa4007b84c3c/src/Runner.Worker/ActionManager.cs#L796-L805

Is there some chance that authentication tokens issued to self-hosted runners are sometimes invalid?

**Comment by mhart** [comment]
Some example request ids, in case that helps narrow down the issue. Is there a chance GitHub Actions can sometimes issue expired authentication tokens?

```
X-GitHub-Request-Id: C334:114E:3AD136:9A5921:5F9F485F
```
```
X-GitHub-Request-Id: 88A9:6C37:F814E4:19BF2AA:5F9F4874
```

**Comment by mhart** [comment]
I can actually replicate this just by doing this from my actions:

```
run: curl https://x-access-token:${{ secrets.GITHUB_TOKEN }}@api.github.com
```

About 1 in 100 jobs will fail with a 401 `Bad credentials` message – so it seems that every now and then an invalid token is being issued?

Is there any way I can debug this any further?

**Comment by thboop** [comment]
@mhart we made some service side fixes in this area, are you still seeing this issue?

**Comment by mhart** [comment]
Ooh, good question. I haven't tested this out in quite a while.

I'll go ahead and close it, and if I see it again, I'll reopen or open a new issue. Thanks!

**Comment by pathcl** [comment]
@thboop just curious what changed in between? we're experiencing similar issues

**Comment by coreyti** [comment]
I've been experiencing this issue frequently today. Our Terraform IaC manages a few dozen memberships to our org, and most pipeline runs fail because the run hits 1 or 2 API request failures along the lines of:

```
Error: GET https://api.github.com/orgs/<organization>/memberships/<member>: 401 Bad credentials []
```

If I re-run the job a few times, eventually it completes without issue.

**Comment by ttrssreal** [comment]
I'm also encountering this in workflows with ~20 jobs

**Comment by mj-hd** [comment]
@ttrssreal it seems to be caused by Github's incident:
https://www.githubstatus.com/incidents/02z04m335tvv
