### ISSUE TITLE
config.sh is cutting the service file name

### ISSUE THREAD

**Issue by dvdknaap** [actions/runner#771]
**Describe the bug**
The SVC_NAME in svc.sh is cut to a certain amount of chars which cause problem when you start with the same name so when the name is cut till the amount of chars it cause an error on install because the service file already fixed

**Expected behavior**
That it only cut chars at 255 chars

## Runner Version and Platform
2.2.73.5

OS of the machine running the runner? Linux

## What's not working?
`./svc.sh install username`
Failed: error: exists /etc/systemd/system/actions.runner....

edit:
It's caused by this line:
https://github.com/actions/runner/blob/main/src/Runner.Listener/Configuration/ServiceControlManager.cs#L52

What is the reason that this has been added and can this be removed?

edit2:
The limit is 255 chars on linux so don't know why this has been added, it only cause a lot of problems
https://serverfault.com/a/9548

**Comment by TingluoHuang** [comment]
Thanks for reporting.
dup with https://github.com/actions/runner/issues/730
