### ISSUE TITLE
self-hosted runners shouldn't be forced to use pre-release versions

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [actions/runner#787]
**Describe the bug**
I have self-hosted runners on version 2.273.5, today they started to receive AgentRefresh messages to update them to version 2.273.6. Version 2.273.6 is currently tagged as pre-release on GitHub and shouldn't be forced into production runners.

**To Reproduce**
1. Run self-hosted runner on version 2.273.5
2. It receives AgentRefresh message to version 2.273.6

**Expected behavior**
It shouldn't receive AgentRefresh messages for pre-release versions unless some flag is specified.

## Runner Version and Platform
Version of your runner?
2.273.5

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

**Comment by t0rr3sp3dr0** [comment]
It is important to notice that this is not the first time my runners are forced to upgrade to a pre-release version.

**Comment by TingluoHuang** [comment]
@t0rr3sp3dr0 sorry, forgot to flip the bit during the release process.
updated.

**Comment by TingluoHuang** [comment]
We stop adding pre-release flag for future runner releases.
