### ISSUE TITLE
Implement composite actions support for job matrixes

### ISSUE THREAD

**Issue by webknjaz** [actions/runner#810]
**Describe the enhancement**

I was pleasantly surprised when I learned about the composite actions. However, there's this one thing missing. Azure Pipelines let have the concept of templates giving you the flexibility of generating job matrices based on the user input. For example https://github.com/asottile/azure-pipeline-templates.

I'd like to be able to do the same in the GitHub Actions ecosystem. Currently, composite actions are the closest thing to allowing users to ship parametrized shareable pieces of workflows.

I think it'd be great if those pieces of workflows could contain matrixes of jobs rather than just steps. Think about it: it is pretty common for library/framework maintainers to test their projects across a variety of envs. People have to keep copy-pasting those matrixes from one project to another and once the time comes to upgrade them, they have to remember all the places across projects where the matrix definitions have to be updated.

OTOH if there was a mechanism to ship ready-to-use jobs where only the command for running tests would be parametrized and maybe some test env exclusions, it'd be so much more scalable maintenance-wise.

I'm not sure what the actual design of this feature would look like but this is my call to explore what could be done in this area to address this need.

**Code Snippet**

N/A

**Additional information**

I'm opening this as a follow-up for https://github.com/actions/runner/issues/438

**Comment by vsoch** [comment]
We would also really really love this! ping @davidbeckingsale. Is this something that GitHub is working on?

**Comment by thboop** [comment]
@webknjaz I think [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) (which shipped at the end of last year) covers this nicely, is there anything else you would want to request, or can I close out this issue?

**Comment by vsoch** [comment]
Could you please point to an example that had a composite action with a matrix? I don’t think reusable workflows exactly covers that.

**Comment by vsoch** [comment]
hey @thboop ! I ironically came searching for this again and found my own issue :laughing: 

I clicked the link above for the workaround but it seems to be removed (and redirects to the discussions). Does it still exist, or do you remember the content so I can try searching for it?

**Comment by vsoch** [comment]
I think I might have found it? It looks like the workaround is to put the matrix on the outside?

https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow
