### ISSUE TITLE
Redaction

### ISSUE THREAD

**Issue by matkoch** [actions/runner#815]
**Describe the bug**
Redaction is too greedy.

**To Reproduce**
Outputting `--password password` prints `-***`

**Expected behavior**
I'd understand if it's at least `--password ***` but even that mangles with the valid help text of `dotnet` for instance:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/5005566/99756715-09354080-2aee-11eb-9f5d-e903a4718c8b.png">

## What's not working?

A while ago, I got this (note I do redact myself):

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/5005566/99756766-236f1e80-2aee-11eb-8a31-b2e773904f56.png">

Now it does this:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/5005566/99756771-2a962c80-2aee-11eb-83bd-3f171e3c2538.png">

**Comment by matkoch** [comment]
It seems that you're more redacting than just what's passed as secrets, i.e., tokens after `--password` and maybe others like `--api-key` etc... I'm not sure if that's a great idea.

**Comment by TingluoHuang** [comment]
@matkoch you must have a registered secret that is `-password YOUR TOKEN`, the runner has no magic and it's doing string match for secret redaction.

**Comment by matkoch** [comment]
No i don't

**Comment by TingluoHuang** [comment]
Do you mind echo the string length for the secret, and check whether that's expected or not?
Ex:
```
-run: |
   test_length="${{secrets.YOURSECRETS}}"
   echo ${#test_length}
```
