### ISSUE TITLE
Use public runners together with self-hosted runners

### ISSUE THREAD

**Issue by igagis** [actions/runner#820]
**Describe the enhancement**
Currently, for a single job within a workflow, it is only possible to use either a public runner or self-hosted one.
It is not possible to use both, for example when job has a large build matrix and needs a lot of runners.

According to github actions documentation on self-hosted runners each self-hosted runner automatically gets some labels, in particular the OS indication label, i.e. `linux`, `windows`, `macos`.
Public runners `ubuntu-latest`, `windows-latest`, `macos-latest` do not seem to have those labels.

So, when using `runs-on: [linux]` will only select linux self-hosted runners, but will not select `ubuntu-latest` runner, which seems illogical.

Proposal is to apply OS labels to public runners as well. Possibly apply some other labels to public runners, like `ubuntu`, `ubuntu-20.04`, `docker` (i.e. runner has docker installd) etc. Self-hosted runners can be set to have higher priority, i.e. public runner will be selected only if there are no free matching self-hosted runners.

**Code Snippet**
N/A

**Additional information**
I'm developing my githuib actions workflows for use with public runners only for now, but would like to drop in self-hosted runners later when I need more build resources. So, with this feature I would not have to mess with workflows again for all my repositories, but just add some self-hosted runners to my organisation.

**Comment by ethomson** [comment]
Thanks for the suggestion.  This feels like it would be a breaking change, but I'd need to think more about it.

However, we use the issues in this repository for bug reports in the runner application itself.  This is not controlled by the runner application, so I'm going to close this issue.  Feedback about GitHub Actions should go to the [GitHub feedback site](https://github.com/github/feedback/discussions/8473).
