### ISSUE TITLE
`hashFiles()` doesn't play well with containers

### ISSUE THREAD

**Issue by ojab** [actions/runner#837]
**Describe the bug**
`hashFiles()` is run on host, so if, for example, container for CI is build and used in subsequent steps — we cannot cache output using `hashFiles()` .

**To Reproduce**
1. https://github.com/ojab/hashFiles_in_container/blob/main/.github/workflows/test.yml (I was unable to quickly setup github package registry, so it's currently not working, but hopefully you got the idea)
2. Comment `options: --mount` hack
2. Run workflow
3. `hashFiles()` doesn't find any files

**Expected behavior**
It should be possible to somehow mount container contents to workspace without `--mount` hack

## Runner Version and Platform
Current runner version: '2.274.2'
Operating System
  Ubuntu
  18.04.5
  LTS

## What's not working?
I've done something like `run: cp hashFiles.js /home/host_runner/runners/2.274.2/bin/hashFiles/index.js` with modified `hashFiles.js` and found out that it's running on the host.

**Comment by nikola-jokic** [comment]
Hi @ojab,

Did you consider [defining outputs for jobs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs)? Also, you can see [this article](https://github.com/marketplace/actions/dynamic-build-docker-image#outputs) which defines outputs

**Comment by ojab** [comment]
The issue is that `hashFiles()` fails because cannot find the files, so step doesn't complete. In some cases it's possible to run a separate job outside of the container with only `hashFiles()` and use output from there, but it's not ideal.

**Comment by nikola-jokic** [comment]
Hi @ojab,

I have created a PR to fix this issue 😊. Thank you for submitting it!

**Comment by nikola-jokic** [comment]
Hey @ojab,

I have mistakenly mentioned and commented that the PR for this issue has been submitted. So sorry about that 😊. Could you please provide an answer to my previous comment?

**Comment by nikola-jokic** [comment]
I am closing this issue now. This really works as expected, and your use case is a bit tricky. Since you have a work-around, I hope this is not that big of an issue for you 😊
