### ISSUE TITLE
Enable collaborators with Read Access to re-run a workflow

### ISSUE THREAD

**Issue by fao89** [actions/runner#841]
Currently, collaborators with `Read Access` can only view workflow runs, I would like they also have the permission to re-run the workflow.

**Comment by nikola-jokic** [comment]
Hi @fao89,

This is not really related to this repository. Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored? Using the forum ensures that we route your problem to the correct team. 😃
