### ISSUE TITLE
Allow runner installation

### ISSUE THREAD

**Issue by zimbatm** [actions/runner#846]
**Describe the enhancement**

The current design of the runner extracts itself into a folder and then runs from that location. The end result is that the folder now contains a mix of code and data. This doesn't play nicely with how things are usually installed on Linux.

It would be really nice if the project was designed to be installed onto the system. This would allow producing .deb and .rpm packages that are managed like the rest of the system. The runtime configuration can then clearly be put into its own location, which makes it easier to upgrade the runner itself.

**Additional information**

I am somebody who manages systems and the typical Java and .NET self-extracting approach makes my life harder.

**Comment by schmidtw** [comment]
Separation would also make it easier systematically handle SELinux.

**Comment by nikola-jokic** [comment]
Hey @zimbatm,

Thank you for taking the time to provide your valuable feedback! We kindly ask you to redirect this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which our team actively monitors and would be a better place to start a discussion for new feature requests in GitHub Actions. 

For more information on this policy please [read our contribution guidelines](https://github.com/actions/runner#contribute).
