### ISSUE TITLE
Shebangs are not portable

### ISSUE THREAD

**Issue by Mic92** [actions/runner#848]
**Describe the bug**

Scripts in the repo assume that base is installed at `/bin/bash`. This is however not the case on NixOS, GuixSD, various BSD derivates and also macOS has a very dated `/bin/bash` version.
It is therefore mandatory to use `/usr/bin/env` which is part of the Posix standard and relies on path lookups and hence makes shebangs portable across different distributions.

**To Reproduce**
Run https://github.com/actions/runner/blob/main/scripts/create-latest-svc.sh
See command not found error

**Expected behavior**

Shebangs use portable /usr/bin/env

## Runner Version and Platform
Version of your runner?

master @ 80bf68d

OS of the machine running the runner? OSX/Windows/Linux/...

NixOS

## What's not working?

shebangs scripts are broken

**Comment by Mic92** [comment]
This is fixed by https://github.com/actions/runner/pull/314

**Comment by TingluoHuang** [comment]
PR merged.
