### ISSUE TITLE
Runner fails with `workflow_run` when workflow names contains square brackets

### ISSUE THREAD

**Issue by billyvg** [actions/runner#854]
The runner fails with `(Unknown event)` when a workflow name contains square brackets (`[]`). This happens with the `workflow_run` event.

See this test commit: https://github.com/billyvg/sentry/commit/c901cb917d493617f59bd421313b013471326131#diff-94e5c36535c8d15527cd1d10249426c03a2a5261a99a7f9ba9bec7d4eb411553R11

and results in a `Startup failure`:  https://github.com/billyvg/sentry/actions/runs/411542674

**Comment by TingluoHuang** [comment]
Looks like we use glob to do the workflow match, so you need to escape the `[]`, ex: `- backend lint \[py3.6\]`

**Comment by TingluoHuang** [comment]
I am going to close this since we have an internal issue for tracking this, plus this is not a runner bug.
https://github.com/github/c2c-actions-experience/issues/4110

**Comment by antdking** [comment]
hi @TingluoHuang, I think I've just run into this issue.

Is there a public tracker for it? What's the status?
