### ISSUE TITLE
Unnecessary dependencies included

### ISSUE THREAD

**Issue by meiswjn** [actions/runner#875]
**Describe the bug**
Hey,

I have noticed that under x64 architectures, both the normal node and node12_alpine are installed:
https://github.com/actions/runner/blob/45c19eb7cb35d416e6b8ef32aba4c6e6236b13c1/src/Misc/externals.sh#L143

For me, it is not clear what the benefit of having the alpine version of node12 along with the normal one is. It makes up for 25% (50MB) of the runner size. For scaled runner deployments, those 50MB are a waste of cost if it is really not needed.

Thanks!
**To Reproduce**
1. Go to https://github.com/actions/runner/blob/45c19eb7cb35d416e6b8ef32aba4c6e6236b13c1/src/Misc/externals.sh#L143
2. Download the x64-runner
3. Unpack it.

**Expected behavior**
The very minimum of what is necessary is downloaded.

## Runner Version and Platform
2.275.1

OS of the machine running the runner? OSX/Windows/Linux/...
x64

**Comment by TingluoHuang** [comment]
the alpine node is included because you may run container job using an apline container.
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
