### ISSUE TITLE
Interval cron trigger not triggering as often as expected

### ISSUE THREAD

**Issue by krispy1298** [actions/runner#877]
**Describe the bug**
I have an action that should be running every 5 minutes, which is the maximum amount of times an hour according to [docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule). Therefore, there should be 12 events per hour in an ideal run. I am getting 2–4 events per hour. 

Unclear if this is an issue with the frequency or with an interval cron setting as a whole. Actions at a defined time (ie `- cron: '0 7 * * *'`) work perfectly in the same repo.

**To Reproduce**
```yaml
on:
  schedule:
    - cron: '*/5 * * * *'
```

**Expected behavior**
Action is triggered roughly every 5 min.

**Comment by TingluoHuang** [comment]
According to https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
```
Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. High load times include the start of every hour. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
```
Also, the schedule run might get delayed if the actions service is under DDOS attack. 😞 

I am going to close this since the schedule is controlled by the service, if you have lots of missing runs for schedules, please reopen this with some sample data (repo URL + time interval), I can help you check our telemetry.

**Comment by ssarioglu** [comment]
if it does not work, why is it there?

**Comment by youcefnb** [comment]
This should be reopened. This feature is extremely unreliable and borderline unusable and somehow there is zero support nor recognition of this fact from github. Please reopen.

**Comment by TRegourd** [comment]
hi, I'm trying to trigger a Netlify build on a certain interval, but I'm not able to make it run...

my `.github/workflows/main.yml`

`name: Trigger Netlify Build
on:
  schedule:
    - cron: '30 * * * 1-5'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} my-web-hook`

I don't think my code has anything wrong, maybe a problem on github action's side ?
