### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by meiswjn** [actions/runner#879]
**Describe the enhancement**
So-called "retryable" errors (for example, error code 2: Not configured) cause the runner not to exit. It is assumed, that the underlying cause will be fixed within the next attempts. Every 5 seconds, the runner tries to start again: 

There should be a maximum number of attempts - self-hosted runners are often deployed in an unattended manner and this might cause indefinite loops.

**Code Snippet**
https://github.com/actions/runner/blob/main/src/Misc/layoutbin/RunnerService.js#L53

**Comment by ethomson** [comment]
Yeah, I think that this makes sense, we should probably have a limit on the number of failures before we just give up.  Apologies for the trouble and thanks for the feedback.
