### ISSUE TITLE
Command path is added to the command line output breaking JSON based commands

### ISSUE THREAD

**Issue by DavidGOrtega** [actions/runner#887]
I have have a nodeJS based CLI that has to do a call to another CLI (terraform) which outputs JSON. To do so I use nodejs async exec. In common shells Everything works, however inside the Github actions the exec returns with the path of the executable first breaking my JSON output.

**To Reproduce**
try to parse the JSON output of a CLI command that generates JSON

**Expected behavior**
Command line path should not be returned

## Runner Version and Platform
Latest
Ubuntu latest in Github actions

## What's not working?
Logging the output you can see that line 80 is an added line with the executable path being returned to my internal nodejs exec.

![image](https://user-images.githubusercontent.com/414967/103387913-a8465280-4b06-11eb-97a4-e1f863769b61.png)

**Comment by kamaz** [comment]
I think I'm having a similar issue. I save the output in the script using `::set-output`

```shell
echo ::set-output name=service_url::$(terraform output -raw service_url)
```

but when I try reading the value I'm getting following

```text
rl: [command]/home/runner/work/_temp/2f71ee36-d132-4d89-8be8-11bb3e9c6f1b/terraform-bin output -raw service_url https://service-bff-xxxxxxx.a.run.app::debug::Terraform exited with code 0. ::debug::stdout: https://service-bff-xxxxxxx.a.run.app ::debug::stderr: ::debug::exitcode: 0 ::set-output name=stdout::https://service-bff-xxxxxxx.a.run.app ::set-output name=stderr:: ::set-output name=exitcode::0
```

instead of getting a simple output `https://service-bff-xxxxxxx.a.run.app`

**Comment by TingluoHuang** [comment]
I don't think this is a runner issue since the runner won't print `terraform-bin` on its own, the action you used might prints it.
Please check the action you used to see what they print.

I am going to close this now, but feel free to reopen if you have more logs and think this is still a runner issue. 😄
