### ISSUE TITLE
我使用runner执行简单的shell命令，显示成功，但是实际上并没执行

### ISSUE THREAD

**Issue by ylmcr7** [actions/runner#888]
name: Java CI with Gradl

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      
    - name: Build with Gradle
      run: sudo bash /home/ubuntu/test.sh

我想做的是  只要我 push代码  就可以执行这个脚本

**Comment by hross** [comment]
we would need a log for more detail on this bug
