### ISSUE TITLE
Fedora runner

### ISSUE THREAD

**Issue by mazzystr** [actions/runner#898]
**Describe the bug**
Is there a way to run a Fedora based runner?

**To Reproduce**
1. https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners 

And of course ...
```
jobs:
  build:
    runs-on: fedora
```
yields error log ...
```
No runner matching the specified labels was found: fedora.
```

**Comment by kolyshkin** [comment]
I think this is the wrong repo. Please see https://github.com/actions/virtual-environments/issues/2307

**Comment by mazzystr** [comment]
Ah yes indeed.  I'll close this issue then.
