### ISSUE TITLE
Access runner name for self-hosted runners

### ISSUE THREAD

**Issue by ladislas** [actions/runner#899]
We already have `${{ runner.os }}`, it would be great to also have `${{ runner.name }}` for self-hosted runners.

We have Mac laptop serving as our CI server with 2 runners running in parallel. We cache our builds but have run into issues when configuration was done on one runner and the build is done on another (our tools complain about path not being the same).

We've solved the issue by adding the runner name to our cache key.

But the workaround is ugly: `$(basename $(dirname $(dirname $(dirname $(pwd)))))`

It would be easier to just be able to access `${{ runner.name }}` to return for example `my_build_runner1`.

**Comment by ladislas** [comment]
Well thanks for that! :)

**Comment by NicklasWallgren** [comment]
@fhammerl How do one check if a workflow is running on a self-hosted runner?

Some sort of boolean, or access to the `runner group name` would have been handy. 

Maybe `${{ runner.group }}`.
