### ISSUE TITLE
Failed to register GitHub runner.

### ISSUE THREAD

**Issue by zjslqshqz** [actions/runner#902]
Failed to register GitHub runner.
os: window 2008 R2
powerShell: 5.1 
> Yes, I upgraded the original 2.0 to 5.1

runner :2.275.1

```shell
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
```

## Runner and Worker's Diagnostic Logs
[Runner_20210111-111521-utc.log](https://github.com/actions/runner/files/5795667/Runner_20210111-111521-utc.log)

**Comment by TingluoHuang** [comment]
@zjslqshqz can you try `Invoke-WebRequest -Uri https://pipelines.actions.githubusercontent.com/AqwOkDKd9ML1YXY7Ny44c1sLw4OlA0OJSarpYgouGuPst6OjDA/_apis/connectionData` from powershell to see whether you get any error?

**Comment by zjslqshqz** [comment]
> @zjslqshqz can you try from powershell to see whether you get any error?`Invoke-WebRequest -Uri https://pipelines.actions.githubusercontent.com/AqwOkDKd9ML1YXY7Ny44c1sLw4OlA0OJSarpYgouGuPst6OjDA/_apis/connectionData`

Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ Invoke-WebRequest -Uri https://pipelines.actions.githubusercontent.co ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], W
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

so..is..ssl....

**Comment by zjslqshqz** [comment]
> @zjslqshqz can you try `Invoke-WebRequest -Uri https://pipelines.actions.githubusercontent.com/AqwOkDKd9ML1YXY7Ny44c1sLw4OlA0OJSarpYgouGuPst6OjDA/_apis/connectionData` from powershell to see whether you get any error?

I have tried using mandatory tls 1.2: 
```shell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```
Can be valid for `Invoke-WebRequest`. But it is invalid for the registration .exe

**Comment by zjslqshqz** [comment]
> @zjslqshqz can you try `Invoke-WebRequest -Uri https://pipelines.actions.githubusercontent.com/AqwOkDKd9ML1YXY7Ny44c1sLw4OlA0OJSarpYgouGuPst6OjDA/_apis/connectionData` from powershell to see whether you get any error?

Okay, I read the window runner support information again, I know, window 2008 is not supported. Thank you

**Comment by zjslqshqz** [comment]
@TingluoHuang Okay, I read the window runner support information again, I know, window 2008 is not supported. Thank you

**Comment by danielscatigno-ncpc** [comment]
Hi, can we reopen that? I'm running Windows Server 2012 R2 and experiencing the same problem
Here is the response I get
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a receive.
At line:1 char:1
+ Invoke-WebRequest -Uri https://pipelines.actions.githubusercontent.com/AqwOkDKd9 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], Web
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
