### ISSUE TITLE
Passing status check doesn't overwrite failed one on commit

### ISSUE THREAD

**Issue by danielchabr** [actions/runner#908]
**Describe the bug**
The github actions check output that passes doesn't overwrite previous failed output. The checks get accumulated on the commit and it appears as failed even though it is now passing all checks. 

Reason that passing PR checks are not enough and commit checks should pass too is that in my private repo I'm using a [bors](https://bors.tech/) integration that automatically manages merging but the failing commit status is breaking it as it assumes that it's not safe to merge.

![image](https://user-images.githubusercontent.com/3509981/104468122-619d3180-55b7-11eb-89f4-a2c3517ea007.png)

**To Reproduce**
I've created test repo where the issue is reproduced on this pull request https://github.com/danielchabr/github-action-test/pull/1. While the pull request does correctly appear as passing, the commit itself seems to be failing https://github.com/danielchabr/github-action-test/pull/1/commits

**Expected behavior**
The commit should display green mark once checks run successfully and old failing checks should get overwritten

## Runner Version and Platform
Current runner version: '2.275.1'
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20201210.0

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by ruvceskistefan** [comment]
This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃
