### ISSUE TITLE
Bump node version

### ISSUE THREAD

**Issue by nv35** [actions/runner#909]
As can be seen in [externals.sh](https://github.com/actions/runner/blob/3b34e203dceb5a9a84bd811d0837c165078ad17f/src/Misc/externals.sh#L6), node version that is downloaded is 12.13.1 (released on 2019-11-19).
As can be seen in [node download website](https://nodejs.org/dist/latest-v12.x/), last 12.x is 12.20.1.
Along bugfixs, many security issues were fixed in the meantime.

**Comment by hross** [comment]
closing in favor of tracking in https://github.com/actions/runner/issues/1011
