### ISSUE TITLE
ldd error on prerelease v2.276.0

### ISSUE THREAD

**Issue by vschettino** [actions/runner#911]
**Describe the bug**
On prerelease v2.276.0, we got the following error:

```
Registering runner test-runner
ldd: ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/System.IO.Compression.Native.so: No such file or directory
```
It registers OK, but then when we try to use a container step:
![Captura de tela de 2021-01-15 09-56-18](https://user-images.githubusercontent.com/7289698/104729923-f159f180-5717-11eb-85f6-5bcb1e7206f1.png)

However Docker is running and it was working fine on prior versions. 

**To Reproduce**
1. Start the runner v2.276.0
2. Run a container step on `self-hosted` (mine was a simple `python --version` with `python:3.9-slim`. 
3. See error

**Expected behavior**
It should run as usual.

## Runner Version and Platform
Version of your runner?
v2.276.0

OS of the machine running the runner? OSX/Windows/Linux/...
Linux (Debian 10)

**Comment by TingluoHuang** [comment]
@vschettino thanks for reporting.

looks like dotnet rename `System.Security.Cryptography.Native.OpenSsl.so ` to `lib System.Security.Cryptography.Native.OpenSsl.so` in dotnet 5... 😄 

i can't repro the container error, as the error shows, is your docker daemon running?
can you try `docker run --rm python:3.9-slim` on the machine?

![image](https://user-images.githubusercontent.com/1750815/104736617-3c243b00-5711-11eb-8ce2-ddd1c30be8e7.png)

![image](https://user-images.githubusercontent.com/1750815/104736664-4a725700-5711-11eb-9d97-23b47c299eb4.png)

**Comment by vschettino** [comment]
Glad I could help!

Seems the Docker issue is something from our end. I will look into it and if something else comes up I'l come back here. 

Thanks!

**Comment by bblacey** [comment]
FYI, this seems to be related more to Debian 10 than Docker.  I just installed a Debian 10 libvirt VM and have the exact same issue.

**Comment by usrbinkat** [comment]
Also getting the error when trying to setup AWS RHEL8 AMI based self hosted runner:
```
[ec2-user@ip-172-31-28-39 actions-runner]$ ./config.sh --url https://github.com/CodeSparta/cradle --token '47REDACTED12'
ldd: ./bin/libSystem.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/libSystem.IO.Compression.Native.so: No such file or directory

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration'
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Response status code does not indicate success: 404 (Not Found).
```
