### ISSUE TITLE
Runner.Listener won't boot on NixOS

### ISSUE THREAD

**Issue by ldub** [actions/runner#918]
**Describe the bug**
When launching the runner on NixOS it crashes with HRESULT: 0x80004005

![image](https://user-images.githubusercontent.com/3114081/104984686-14103280-59c4-11eb-8e0c-398b5c196e16.png)

It appears this may be related to the CoreCLR trying to write some diagnostic files/symbols in a read-only directory (/nix)

**To Reproduce**

1. launch an aws instance in us-east-1 with `ami-0a2cce52b42daccc8` or any ami from [this list](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/ec2-amis.nix) (for other regions)
2. in any directory, create default.nix and pinned-nixpkgs.nix files as in this Gist: https://gist.github.com/ldub/05807068a8f0cc9cc3793b511b0c78ba
2. Run `nix-build -E "(import ./pinned-nixpkgs.nix {}).unstable.current.pkgs.callPackage ./default.nix {}"`. This will create a `result` directory/symlink which will contain the Github Actions Runner binaries downloaded from the v2.275.1 tarball directly from github.
3. Run with `./result/run.sh`
4. Add env vars to enable tracing and disable diagnostics and try running the same (see below)

**Expected behavior**
Github Actions Runner starts.

## Runner Version and Platform
Runner v2.275.1
Platform: NixOS (linux)

## What's not working?
```
❯ ./result/run.sh
Failed to create CoreCLR, HRESULT: 0x80004005
```

Additionally, I've found the following related issues and code:

https://github.com/actions/runner/issues/619
https://github.com/dotnet/runtime/issues/9336

Dongbo Wang suggesting that `COMPlus_EnableDiagnostics=0` env var could disable diagnostic information being written.
https://github.com/PowerShell/PowerShell/issues/13166

Enable tracing with `COREHOST_TRACE=1`: https://github.com/dotnet/runtime/blob/1f66c4b8d34bd881bbd739d704c66dbd8c405bb1/src/installer/corehost/cli/hostpolicy/hostpolicy.cpp#L72-L85
(https://github.com/dotnet/runtime/blob/master/docs/design/features/host-tracing.md)

As such, I tried running with

```
COMPlus_EnableDiagnostics=0 COREHOST_TRACE=1 ./result/run.sh
```

or

```
COMPlus_EnableDiagnostics=0 COREHOST_TRACE=1 /nix/store/s7xlxawysw3q894k8gbnigpzim1bgdnd-actions-runner-2.275.1/bin/Runner.Listener
```

This results in the same error, but a long trace being printed (its the last file in the same gist above): https://gist.github.com/ldub/05807068a8f0cc9cc3793b511b0c78ba#file-zz-corehost_trace-log

Could you offer any help in getting the runner to run on NixOS?

**Comment by matthewbauer** [comment]
@ldub This appears to happen because Nixpkgs runs GNU binutils 2.34 strip on the DLLs. It looks like strip is somehow breaking dotnet binaries. Adding:

```
dontStrip = true;
```

To the derivation fixes this.
