### ISSUE TITLE
Hosted Github runner auto update to 2.276.0 fails - leaves runner in dead state

### ISSUE THREAD

**Issue by deeno35** [actions/runner#925]
**Describe the bug**
hosted runner service dies during update.  Re running the service manually tries to install again so it is stuck in an "upgrade loop".  Downloading the newest version and installing manually fixes.

**To Reproduce**
1. This happens on it's own - as a user I don't have control over opting out of updates or at least controlling when they happen or what frequency they happen.

**Expected behavior**
An upgrade does not leave a runner in the off state.  
- would be nice if the process was managed by systemd or something to restart if dead
- If it does die a couple times, I expect when I restart the service that the runner can either self heal or realize an update is bad and skip it.  
 
This is probably the 6th time or so in less than 1 year of using github hosted runners that I've had to report an upgrade issue like this.

## Runner Version and Platform
Version of your runner?
whatever comes before 2.276.0.  This is all auto updated so I don't know what version is running since I'm not managing it.

OS of the machine running the runner? OSX/Windows/Linux/...
4.14.177-139.254.amzn2.x86_64

## What's not working?
Please include error messages and screenshots.

Jan 20 19:49:29 ip-172-31-62-197 run.sh: Downloading 2.276.0 runner
Jan 20 19:49:35 ip-172-31-62-197 run.sh: Waiting for current job finish running.
Jan 20 19:49:35 ip-172-31-62-197 run.sh: Generate and execute update script.
Jan 20 19:49:35 ip-172-31-62-197 run.sh: Runner will exit shortly for update, should back online within 10 seconds.
Jan 20 19:49:35 ip-172-31-62-197 systemd: github_action_runner.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
Jan 20 19:49:35 ip-172-31-62-197 systemd: Unit github_action_runner.service entered failed state.
Jan 20 19:49:35 ip-172-31-62-197 systemd: github_action_runner.service failed.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by shadiramadan** [comment]
I have this exact same issue.  All runners no longer work because it is stuck in a crash loop.
Like other threads have said containers should NOT auto update.  The image should be swapped out instead.

**Comment by amenocal** [comment]
I'm having the same issue were my container are all stuck in a crash loop because it is trying to update. 

Also, `pre-releases` shouldn't be mandatory to update. Right now my containers tried to update to the latest pre-release version, which I'm not sure it should be this way. Also, since it is a pre-release it doesn't show up in this [api call](https://api.github.com/repos/actions/runner/releases/latest) which is what I'm using to know what is the latest version and apply that.

**Comment by deeno35** [comment]
Dead again - 2.277.1
```
Feb 11 17:45:26 ip-172-31-62-197 run.sh: Runner update in progress, do not shutdown runner.
Feb 11 17:45:26 ip-172-31-62-197 run.sh: Downloading 2.277.1 runner
Feb 11 17:45:28 ip-172-31-62-197 run.sh: Waiting for current job finish running.
Feb 11 17:45:29 ip-172-31-62-197 run.sh: Generate and execute update script.
Feb 11 17:45:29 ip-172-31-62-197 run.sh: Runner will exit shortly for update, should back online within 10 seconds.```

**Comment by hross** [comment]
this should be fixed now. closing but reopen if you still see issues.
