### ISSUE TITLE
Automatic Docker Cleanup

### ISSUE THREAD

**Issue by zgriesinger** [actions/runner#926]
**Describe the enhancement**
We have been having quite a few issues with docker between multiple runs on our self hosted runners. We have a few workflows that spin up a docker compose files to run integration tests.

We weren't having any issues when running these workflows on the public runners, but once we moved to self hosted we were having port collisions and we had to add manual steps to clean up the docker containers between runs, which was a fairly complicated process to assure every single container is cleaned up.

I am wondering how GitHub public runners handle this problem and if possible could the self hosted runners leverage a similar cleanup step? While cleaning them up manually is working it is a cumbersome process to make sure every workflow file is cleaning up after itself after moving from public runners to self-hosted.

**Comment by TingluoHuang** [comment]
@zgriesinger the GitHub Hosted runners run on a fresh VM for every job, so it doesn't need to worry about any cleanup.

**Comment by hross** [comment]
We probably won't add this to self hosted as there are a lot of edge cases and the current way to handle this is use "ephemeral" runners which reset their environments on each run so a clean environment is guaranteed. We are looking at shipping some features in the near future to support this more easily so please stay tuned.

**Comment by richardwu** [comment]
@zgriesinger a bit late but adding a cron job to prune images works for us:
```
(crontab -l ; echo "*/5 * * * * docker system prune -af") | crontab
```

**Comment by tristantreb** [comment]
I ran into an issue where docker volumes were taking all the disk space. I updated the command to include volumes:
```
(crontab -l ; echo '0 * * * * docker system prune -af --volumes') | crontab
```
It prunes all unused docker images, containers, networks and volumes every hour

**Comment by gchamon** [comment]
I created this action to work around the issue described https://github.com/waycarbon/github-action-container-cleanup

The functionality is described in the readme, but in a nutshell, it uses a post script to check which containers where launched during the workflow lifetime and kill them. It works really well for us in self-hosted deployment without risking killing containers we need to live for the duration of the runner lifetime, such as metrics exporters and loggers.
