### ISSUE TITLE
Allow setting docker command line options when running starting a container

### ISSUE THREAD

**Issue by smorimoto** [actions/runner#934]
Currently, the lack of a way to enable it in the Actions runner is quite a problem, and adding this feature allows testing on various architectures without having to provision a self-host runner. Docker supports the `--experimental` flag at the moment, so we can probably implement it without much extra work. What do you think? And I can implement that if you don't have much bandwidth.

Related links:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer
https://github.com/docker/cli/blob/master/experimental/README.md

Related issues:
https://github.com/actions/runner/issues/648
https://github.com/actions/virtual-environments/issues/1368

**Comment by hross** [comment]
Closing this in favor of https://github.com/actions/runner/issues/648
