### ISSUE TITLE
Org-level self-hosted runner working but unlisted

### ISSUE THREAD

**Issue by drruruu** [actions/runner#936]
**Describe the bug**
Despite successfully accepting jobs, a configured org-level self-hosted runner is not present under Settings > Actions > Self-hosted runners

**To Reproduce**
1. Configure and Install service.
2.  Run job.

**Expected behavior**
The runner should be listed within the Default group.

## Runner Version and Platform
`2.276.1`

## OS of the machine running the runner? OSX/Windows/Linux/...
Debian 10 (buster)

## What's not working?
![image](https://user-images.githubusercontent.com/8763488/105545616-e972f200-5cc1-11eb-96cd-23f101897078.png)

## Job Log Output
Set up Job:
```
Current runner version: '2.276.1'
Runner name: '<runner name>'
Runner group name: 'Default'
Machine name: '<machine ip>'
```

## Runner and Worker's Diagnostic Logs
N/A

**Comment by TingluoHuang** [comment]
@drruruu what's your repo/org url?

**Comment by thboop** [comment]
We are aware of this issue and working on a fix. Hope to have it rolled out in the new couple hours.

**Comment by looshlee** [comment]
Just leaving these two reports here for tracking 🤞🏻 : 
https://github.zendesk.com/agent/tickets/993261
https://github.zendesk.com/agent/tickets/993435

**Comment by michaelfdickey** [comment]
Enterprise Support has 3 different cases reporting this issue as well:

[ZD993312](https://github.zendesk.com/agent/tickets/993312)
[ZD993356](https://github.zendesk.com/agent/tickets/993356)
[ZD993240](https://github.zendesk.com/agent/tickets/993240)

**Comment by thboop** [comment]
This issue should be fixed now!
