### ISSUE TITLE
Code Scan for large public repo

### ISSUE THREAD

**Issue by frank-dong-ms** [actions/runner#941]
Hi Github Actions Experts,

I'm trying to run Github code scan for pytorch on my own fork: https://github.com/frank-dong-ms/pytorch

I finished set up workflow but the problem is pytorch is very large repo so the build+codeQl analyze time is much larger than 6 hours which is max execution time for single job according to: https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits. 
Since this is public repo so self-hosted runner is also not recommended due to security reasons: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories. 
So I'm wondering what I can do to enable code scan for such a large repo? Thanks for any recommendations.

Thanks

**Comment by hross** [comment]
unfortunately we don't have a way to run it for longer without breaking the repo into smaller chunks.
