### ISSUE TITLE
GitHub Actions log prints secret if it is part of git output

### ISSUE THREAD

**Issue by trivikr** [actions/runner#943]
**Describe the bug**
Reference: https://github.com/wei/git-sync/issues/25

**To Reproduce**
* GitHub Action being tested: https://github.com/wei/git-sync
* Tested with repo: https://github.com/trivikr/git-sync-test
* Example GitHub Action test run: https://github.com/trivikr/git-sync-test/runs/1773895924?check_suite_focus=true

Steps to reproduce:
* Set up public keys and private keys as per README.
* Set up destination_repo in GitHub secret `GIT_SYNC_DESTINATION_REPO`.

<details>
<summary>Repro git-sync config</summary>

```yml
name: git-sync

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "trivikr/git-sync-test"
          source_branch: "main"
          destination_repo: ${{ secrets.GIT_SYNC_DESTINATION_REPO }} 
          destination_branch: "main"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key:  ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
```

</details>

<details>
<summary>GitHub Action test run output</summary>

```console
SOURCE=git@github.com:trivikr/git-sync-test.git:main
DESTINATION=***:main
Cloning into '/root/source'...
Warning: Permanently added 'github.com,140.82.113.4' (RSA) to the list of known hosts.
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
* main                0ebf7d8 [source/main] chore: allow manually running git-sync workflow
  remotes/source/HEAD -> source/main
  remotes/source/main 0ebf7d8 chore: allow manually running git-sync workflow
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
To github.com:trivikr/private-git-sync-test.git
   b27fdec..0ebf7d8  main -> main
```

</details>

Note that private git repository name is hidden when DESTINATION is printed:
```console
DESTINATION=***:main
```
However, the private git repository name is shown in git output.
```console
To github.com:trivikr/private-git-sync-test.git
   b27fdec..0ebf7d8  main -> main
```

**Expected behavior**
The destination repository name should be masked in GitHub Action log as it's sensitive.

## Runner Version and Platform
Version: 2.276.1
OS: Ubuntu 18.04.5 LTS

## What's not working?
The sensitive information passed as a GitHub secret is printed inside git log.

## Job Log Output
<details>
<summary>GitHub Action test run output</summary>

```console
SOURCE=git@github.com:trivikr/git-sync-test.git:main
DESTINATION=***:main
Cloning into '/root/source'...
Warning: Permanently added 'github.com,140.82.113.4' (RSA) to the list of known hosts.
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
* main                0ebf7d8 [source/main] chore: allow manually running git-sync workflow
  remotes/source/HEAD -> source/main
  remotes/source/main 0ebf7d8 chore: allow manually running git-sync workflow
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
To github.com:trivikr/private-git-sync-test.git
   b27fdec..0ebf7d8  main -> main
```

</details>

**Comment by TingluoHuang** [comment]
@trivikr 
What did you set for `GIT_SYNC_DESTINATION_REPO`?

**Comment by TingluoHuang** [comment]
the runner secret mask expects string exactly match.
did you set `GIT_SYNC_DESTINATION_REPO ` to `git@github.com:trivikr/private-git-sync-test.git`?
if so, the runner won't mask any substring of your secret.

**Comment by trivikr** [comment]
> the runner secret mask expects string exactly match.
> did you set `GIT_SYNC_DESTINATION_REPO ` to `git@github.com:trivikr/private-git-sync-test.git`?
> if so, the runner won't mask any substring of your secret.

Yes. The value stored in `GIT_SYNC_DESTINATION_REPO ` is `git@github.com:trivikr/private-git-sync-test.git`

Is the solution to change GitHub action code to allow only substring which needs to be masked, like `trivikr/private-git-sync-test.git` in GitHub secret?

**Comment by TingluoHuang** [comment]
The runner can't mask substring, since it doesn't know which part of the secret is really "secret" 😄 
ex: `git@github.com:trivikr/private-git-sync-test.git`, should the runner mask `git` or `github.com`


if https://github.com/wei/git-sync expect `destination_repo` from `secrets`, they can register extra secrets since the action has firsthand knowledge about what's their output may look like.

**Comment by trivikr** [comment]
Thank you @TingluoHuang for the explanation.
I've posted a suggestion here https://github.com/wei/git-sync/issues/25#issuecomment-768105358
