### ISSUE TITLE
2.276.1 @ Ubuntu 18.04: `ldd: ./bin/libSystem.Security.Cryptography.Native.OpenSsl.so: No such file or directory`

### ISSUE THREAD

**Issue by ddinchev** [actions/runner#945]
**Describe the bug**
I'm trying to install a self-hosted runner on Ubuntu 18.04 using the automation script and I get the following errors:

```
~$ curl -s https://raw.githubusercontent.com/actions/runner/automate/scripts/create-latest-svc.sh | bash -s ***/*** ***-runner
Configuring runner @ ***/***

/usr/bin/curl
/usr/bin/jq

Generating a registration token...

Downloading latest runner ...
Downloading v2.276.1 for linux ...
https://github.com/actions/runner/releases/download/v2.276.1/actions-runner-linux-x64-2.276.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   665  100   665    0     0  24629      0 --:--:-- --:--:-- --:--:-- 24629
100 70.5M  100 70.5M    0     0  90.1M      0 --:--:-- --:--:-- --:--:-- 95.5M
-rw-rw-r-- 1 *** *** 73928496 Jan 27 10:47 actions-runner-linux-x64-2.276.1.tar.gz

Extracting actions-runner-linux-x64-2.276.1.tar.gz to ./runner
~/runner ~

Configuring jenkins-runner @ https://github.com/***/***
./config.sh --unattended --url https://github.com/***/*** --token *** --name ***-runner
ldd: ./bin/libSystem.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/libSystem.IO.Compression.Native.so: No such file or directory

---

# Authentication


√ Connected to GitHub

# Runner Registration



√ Runner successfully added
√ Runner connection is good

# Runner settings


√ Settings Saved.
```

The runner reports to be started successfully but the errors seem to be related to .NET upgrade from v3 to v5 and I'm unsure if I can rely on the runner working correctly.

**Comment by ddinchev** [comment]
Symlinking the expected library paths to the actual library paths seems to resolve the errors:

```bash
for lib in $(find . -name 'System.*'); do
    toFile=$(echo "$lib" | sed -e 's/\.\/System\./.\/libSystem./g');      
    if ! [ -f $toFile ]; then 
        sudo ln -s $lib $toFile; 
    fi;   
done
```

Credits goes to [this stackoverflow user](https://stackoverflow.com/a/65910123/762886).

**Comment by TingluoHuang** [comment]
thanks for reporting, we will fix this soon.

**Comment by maciejgwizdala** [comment]
`sed -i -e 's/libSystem./System./g' config.sh` will do the trick as well, as ldd wants to check wrong filenames within config.sh

**Comment by hross** [comment]
we rolled back this update so closing this

**Comment by itslenny** [comment]
FYI @hross I just hit this exact same issue with `2.279.0`

```
2021-07-28 18:29:54Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.279.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should back online within 10 seconds.
ldd: ./bin/libcoreclr.so: No such file or directory
ldd: ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/System.IO.Compression.Native.so: No such file or directory
./config.sh: line 80: ./bin/Runner.Listener: No such file or directory
ldd: ./bin/libcoreclr.so: No such file or directory
ldd: ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/System.IO.Compression.Native.so: No such file or directory
./config.sh: line 80: ./bin/Runner.Listener: No such file or directory
...
```

**Comment by MichaelJJ** [comment]
@hross Still seeing with 2.283.1:
```
ldd: ./bin/libcoreclr.so: No such file or directory
ldd: ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/System.IO.Compression.Native.so: No such file or directory
```

**Comment by dmattia** [comment]
@hross  Hit this with `2.286.0`, though only when using an arm64 executor

**Comment by MichaelJJ** [comment]
Still seeing this with the latest version

**Comment by trym-b** [comment]
I got the same issue when following the linux instructions in `https://github.com/<org>/<repo>/settings/actions/runners/new`, but I only got this issue when running `./config.sh` as a different user like: `sudo --user <user-name> sh -c /home/<user-name>/actions-runner/config.sh --name testing --unattended --url https://github.com/<org>/<repo> --token <token> --labels my-test-label`

When running as the target user directly everything worked just fine.

Tested this on version `2.291.1`

**Comment by NoelOmo** [comment]
Still experiencing this when running `./config.sh`

`ldd: ./bin/libcoreclr.so: No such file or directory
ldd: ./bin/System.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/System.IO.Compression.Native.so: No such file or directory
./config.sh: line 80: ./bin/Runner.Listener: cannot execute binary file: Exec format error`

**Comment by eumoh1601** [comment]
still facing this error in 2.296.2 when running ./config
`dd: ./bin/libcoreclr.so: No such file or directory
ldd: ./bin/libSystem.Security.Cryptography.Native.OpenSsl.so: No such file or directory
ldd: ./bin/libSystem.IO.Compression.Native.so: No such file or directory
./config.sh: line 80: ./bin/Runner.Listener: cannot execute binary file: Exec format error`

**Comment by AllanOricil** [comment]
These 3 errors happen but the runner is alive and can process jobs. What exactly is the impact of these errors?
<img width="639" alt="image" src="https://user-images.githubusercontent.com/55927613/235118275-2614f413-d499-4e87-a969-398f5e476145.png">

**Comment by jawsthegame** [comment]
I was struggling with this and realized it was PEBKAC. I was trying to install the MacOS runner on Linux. Check and make sure you aren't doing the same.
