### ISSUE TITLE
Github workspace no such file or directory

### ISSUE THREAD

**Issue by zacksiri** [actions/runner#946]
**Describe the bug**
I was running my build just fine as usual and all of a sudden in the subsequent build as my action was doing it's job all of a sudden it's now throwing an error.

** (ErlangError) Erlang error: :enoent Shows that the the command being run is 

```
sudo chown -R builder:abuild /github/workspace (which I got from GITHUB_WORKSPACE env variable) 
``` 

**To Reproduce**
1. Run action one day and pass
2. Next day action is failing
3. See error

**Expected behavior**
Execute task successfully

## Runner Version and Platform
Version of your runner?

Hosted Runner Current runner version: '2.276.1'

OS of the machine running the runner? OSX/Windows/Linux/...

ubuntu-latest

## What's not working?

<img width="1116" alt="Screen Shot 2021-01-27 at 8 25 59 PM" src="https://user-images.githubusercontent.com/134488/105997166-e02cbf80-60dd-11eb-9521-8833eaac91e7.png">
<img width="1121" alt="Screen Shot 2021-01-27 at 8 26 42 PM" src="https://user-images.githubusercontent.com/134488/105997244-f89cda00-60dd-11eb-8404-f79af0e72ed8.png">

I have already tried upgrading checkout action to v2 and doesn't seem to help

https://github.com/artellectual/helipad

**Comment by TingluoHuang** [comment]
@zacksiri I noticed you are using container action https://github.com/upmaru/pakman
did anything change in that action?

**Comment by zacksiri** [comment]
> @zacksiri I noticed you are using container action https://github.com/upmaru/pakman
> 
> did anything change in that action?

I don't think anything relating to writing files changed. It used to work and it just stopped working.

**Comment by zacksiri** [comment]
@TingluoHuang In the action the only thing that has changed is after this broke I've been trying various things to try and fix it but it all seems unrelated and the problem still persists.

**Comment by zacksiri** [comment]
@TingluoHuang could my issue and https://github.com/actions/runner/issues/945 have the same root cause?

**Comment by TingluoHuang** [comment]
@zacksiri no, #945 is just we forgot to update some check script before you configure self-hosted runner. since you are using hosted runner, that script doesn't get run at all.

One way to test is to use some container actions to just echo out the file inside the container, 
ex: 
```
use: docker://ubuntu:18.04
with:
  args: ls -l .
```

**Comment by zacksiri** [comment]
@TingluoHuang I've tried running ls -la inside and it's returning correctly. 

https://github.com/artellectual/helipad/runs/1777144995?check_suite_focus=true

```
Run upmaru/pakman@develop
11
/usr/bin/docker run --name e60dbde067c94ee2997f27f1d0eaf21a_e3d0bc --label 442333 --workdir /github/workspace --rm -e ABUILD_PRIVATE_KEY -e ABUILD_PUBLIC_KEY -e INPUT_COMMAND -e INPUT_ARCHIVE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/helipad/helipad":"/github/workspace" 442333:e60dbde067c94ee2997f27f1d0eaf21a  "--command" "bootstrap" "--archive" ""
12
{"total 64\ndrwxr-xr-x 9 1001  116 4096 Jan 27 13:49 .\ndrwxr-xr-x 6 root root 4096 Jan 27 13:49 ..\n-rw-r--r-- 1 1001  116  159 Jan 27 13:49 .formatter.exs\ndrwxr-xr-x 8 1001  116 4096 Jan 27 13:49 .git\ndrwxr-xr-x 3 1001  116 4096 Jan 27 13:49 .github\n-rw-r--r-- 1 1001  116  888 Jan 27 13:49 .gitignore\n-rw-r--r-- 1 1001  116  733 Jan 27 13:49 README.md\ndrwxr-xr-x 5 1001  116 4096 Jan 27 13:49 assets\ndrwxr-xr-x 2 1001  116 4096 Jan 27 13:49 config\n-rw-r--r-- 1 1001  116 1095 Jan 27 13:49 instellar.yml\ndrwxr-xr-x 4 1001  116 4096 Jan 27 13:49 lib\n-rw-r--r-- 1 1001  116 1749 Jan 27 13:49 mix.exs\n-rw-r--r-- 1 1001  116 7414 Jan 27 13:49 mix.lock\ndrwxr-xr-x 4 1001  116 4096 Jan 27 13:49 priv\ndrwxr-xr-x 4 1001  116 4096 Jan 27 13:49 test\n",
13
 0}
```

However when any command containing `/github/workspace` I'm getting the error mentioned in the beginning of the thread. Do you have any idea what may have changed on Github Actions / runner side that is causing my issue?

Tonight I will try and Start from scratch a new docker and run the command like you suggested.

**Comment by TingluoHuang** [comment]
@zacksiri I didn't see the `.apk` folder in your `ls` output.

**Comment by TingluoHuang** [comment]
both pass and failed jobs used the same runner version.

![image](https://user-images.githubusercontent.com/1750815/106095435-cd2be680-6101-11eb-8279-0a07ed3f3462.png)
![image](https://user-images.githubusercontent.com/1750815/106095468-d917a880-6101-11eb-8350-70806d397bdb.png)

**Comment by zacksiri** [comment]
> @zacksiri I didn't see the `.apk` folder in your `ls` output.

Yeah because the .apk step failed. the command I used for creating .apk is 

`mkdir -p /github/workspace/.apk/artellectual/helipad` all the missing directories in between will be created as well. However I believe the issue right now is it cannot find `/github/workspace`

**Comment by zacksiri** [comment]
@TingluoHuang Seems like something broke in my toolchain it has nothing to do with Github Runner (more to do with Alpine packages dependency tree) I'm closing this issue.

**Comment by zacksiri** [comment]
@TingluoHuang Thank you for your help!

**Comment by koppor** [comment]
For the googlers coming here (because of a similar issue)

wrong:

```yaml
      - run: ls -la
        working-directory: $GITHUB_WORKSPACE/tmp
```

right:

```yaml
      - run: ls -la
        working-directory: ${{ github.workspace }}/tmp
```
