### ISSUE TITLE
Docs: `if: github.event == 'push'` doesn't work, it should be `github.event_name`

### ISSUE THREAD

**Issue by miaotony** [actions/runner#950]
**Describe the bug**

I found a documentation bug when I edited one of my GitHub Action configuration files.

At the end of the documentation, we could see the `Running steps or jobs conditionally` section, which told that we can specify a condition in the `if:` property based on the event name.

![bug](https://user-images.githubusercontent.com/41962043/104232600-8e542a80-548b-11eb-9b63-d98550ae818b.png)

However, when I used `if: github.event == 'push'` to do such thing, the action didn't run this step.

**To Reproduce**
1. Go to one of the action configuration files.
2. Run a step with `if: github.event == 'push'`.
3. When push, this step doesn't run.

**Expected behavior**
Run a specific step when `push` events happen.

## Runner Version and Platform
The latest version.
Ubuntu-latest *(No matter what OS actually)*

## What's not working?
I tried to solve it by referring to the documentation [Contexts and expression syntax for GitHub](https://docs.github.com/articles/contexts-and-expression-syntax-for-github-actions), in which I found that `github.event` was an `object` and `github.event_name` was a `string`.

So I tested them using codes like these.

![](https://user-images.githubusercontent.com/41962043/104233225-77620800-548c-11eb-880b-09486c4f3d85.png)

```yml
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```

![](https://user-images.githubusercontent.com/41962043/104233419-cc9e1980-548c-11eb-8c62-17e23ecc2643.png)

By dumping the `github` context, we can see that `github.event` is actually an object and `github.event_name` is a string that we want.

Finally, I change the code from `github.event` to `github.event_name`, and that step works successfully.

## Solution

Update the document on the right of the online editor.

`if: github.event == 'push'` should be `if: github.event_name == 'push'`.

Thank you!

**Comment by TingluoHuang** [comment]
we should fix the doc. 👍 
thanks for reporting. @miaotony

**Comment by miaotony** [comment]
> 
> 
> we should fix the doc. 👍
> thanks for reporting. @miaotony

Hey, @TingluoHuang 
It looks like everything is the same as it was...
Could you please fix it when you get a chance?

**Comment by dimaslanjaka** [comment]
i dont know where the documentation context `github` in workflows.

can i using condition like `github.event_name != 'workflow_call'` ?

example

```yml
      - name: commit and push
        if: (steps.changes.outputs.staged > 0 || steps.changes.outputs.commits > 0) && github.event_name != 'workflow_call'
```

**Comment by CucaJaime** [comment]
[com/en-au/microsoft-365/buy/compare-all-microsoft-365-products]()
