### ISSUE TITLE
Issues generating a React Native build using `workflow_dispatch`; Works fine `on push`

### ISSUE THREAD

**Issue by SandroMachado** [actions/runner#951]
Hi there,

I'm trying to use github actions to generate iOS and Android builds from a React Native project.

I have two different configurations, one is working the other one is not.

1. If I set my action to run on a **push to a branch**, **everything works as expected** and the build is generated with success.
 
2. If I set my action to run on a `workflow_dispatch` it fails with the error: `Watchman error: query failed: synchronization failed`.

Searching a bit for the error I found that it could be related with other apps doing things with the files. [See this stackoverflow post](https://stackoverflow.com/a/44978184/3482000).

Is there any difference in the internals of the runner that can cause this? Why it could be working with the `push` and not working with the `dispatch`? 

## Runner Version and Platform
I'm using a MacOS instance on AWS to run the runner.

**Comment by TingluoHuang** [comment]
@SandroMachado is the workflow fails to run with the error or is your step fail?
do you have some logs to share?

**Comment by SandroMachado** [comment]
It's my step that fails. 

There is any difference between these two methods to execute the actions?

Thanks for your help.

**Comment by TingluoHuang** [comment]
No, once the job lands on the runner the only different is the GitHub event payload, whether is a push event or workflow dispatch event.

**Comment by SandroMachado** [comment]
@TingluoHuang thank you for you clarification. I will close the issue.
