### ISSUE TITLE
Multiple instances of the runner stealing memory

### ISSUE THREAD

**Issue by digimbyte** [actions/runner#956]
I have a small server that I want to auto-update but looking at my mem usage, my runner has multiple equal instances of itself and several copies of node.js
This is an issue as the test build also requires Opus to compile and since all the ram is being used, it can't even compile with the limited ram (512GB)
For the record, I am not running multiple services or instances of the runner itself, this is after 1 install with one push.

![image](https://user-images.githubusercontent.com/6645396/106386746-3ec9a480-6422-11eb-8810-3153ea4537b9.png)

_Originally posted by @digimbyte in https://github.com/actions/runner/issues/747#issuecomment-770388699_

**Comment by acuteaura** [comment]
Those look like threads in the same memory space, not processes. Try pressing "H". `htop` is a bit confusing there.

**Comment by hross** [comment]
We will look into this but without more concrete details I can't promise specific action. Thank you for the report.

**Comment by nikola-jokic** [comment]
Hi @digimbyte,

Are you still experiencing this issue? Could you please provide an example repository or a `_diag` file so we can investigate it further?

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!
