### ISSUE TITLE
config.sh does not respect proxy settings.

### ISSUE THREAD

**Issue by CollinAlpert** [actions/runner#961]
**Describe the bug**
When trying to run the config.sh script, the connection times out. 

**To Reproduce**
1. Specify proxy `http_proxy=<ip-address>` in .env file in actions-runner directory.
2. Run config.sh script
3. See error

**Expected behavior**
The runner registers to GitHub.

## Runner Version and Platform
2.276.1

OS of the machine running the runner? Debian 10

## What's not working?
"Connection timed out"

**Comment by CollinAlpert** [comment]
After some debugging I found out why. Simply specifying the IP address does not work. You need to prefix it with "http://" or "https://". You might want to specify that in the docs, as it's not obvious.

**Comment by TingluoHuang** [comment]
@CollinAlpert also should be something like `https_proxy=http://127.0.0.1:9090`?

**Comment by CollinAlpert** [comment]
Yes, I had that in there as well. Just without the `http://` prefix.
