### ISSUE TITLE
Runner can't connect to API.github.com 

### ISSUE THREAD

**Issue by ackbyte** [actions/runner#962]
**Describe the bug**
Actions are failing behind a corporate proxy with deep inspection. 

**To Reproduce**
1. start self hosted action runner behind a proxy with enable deep inspection feature
2. make a change to repository content and push it
3. self hosted action runner will start a job but fail because of self signed ssl certificate of the proxy in between

**Expected behavior**
Self signed certificates will be ignoring by putting something into **.env**  file, to ignore SSL issues.

## Runner Version and Platform
2.276.1

OS of the machine running the runner? Linux: RHEL 7.9

## What's not working?
![Screenshot 2021-02-03 at 14 27 47](https://user-images.githubusercontent.com/683434/106757529-be2cc300-6630-11eb-9cf7-cce299208054.png)

**Comment by TingluoHuang** [comment]
@ackbyte try `./run.sh --check` and follow the doc it prints out to see whether it can fix your issue.

**Comment by ackbyte** [comment]
@TingluoHuang, `./run.sh --check` was executed. As you see, the output is not related to the issue,
which is described in the initial issue. Connect to the internet is possible. The runner behaviour with the proxy as not as expected, when the proxy is running deep inspection on SSL-traffic.

Is **--skip-cert-validation** or something like that implemented?

![Screenshot 2021-02-03 at 16 37 58](https://user-images.githubusercontent.com/683434/106770543-6301cd00-663e-11eb-89ff-5595cfe335e9.png)

**Comment by TingluoHuang** [comment]
The outputs shows that you have some checks failed. Do you mind check this log and read the help doc?😃

**Comment by ackbyte** [comment]
@TingluoHuang, thank you for your comment. Please provide also a constructive solution or approach. The [Documentation](https://docs.github.com/en/actions/hosting-your-own-runners/using-a-proxy-server-with-self-hosted-runners) provides only a hint how to set proxy, nothing else. Also the `--check` flag for `./run.sh --check` is not documented... `./run.sh --help `does not provide this information.

Bump for SSL issue fix with self signed certificates provided by proxy in the middle.

**Comment by TingluoHuang** [comment]
@ackbyte the error you saw is not coming from the runner. the error is from the `checkout` actions, furthermore, the `checkout` action try to use node.js to download the repo tar.gz via GITHUB API. The cert error is from node.js

**Comment by TingluoHuang** [comment]
you can make node.js to trust your cert via https://github.com/actions/runner/blob/main/docs/checks/sslcert.md#trust-ca-certificate-for-nodejs

**Comment by ackbyte** [comment]
@TingluoHuang, awesome! Thank you very much for pointing me to the node.js part.
