### ISSUE TITLE
Build workflow needs to be simplified 

### ISSUE THREAD

**Issue by Summpot** [actions/runner#974]
I noticed that the build system of this project uses many technologies.
Including [msbuild proj](https://github.com/actions/runner/blob/main/src/dir.proj), [shell scripts](https://github.com/actions/runner/blob/main/src/dev.sh), etc., and they directly call each other interspersed, and there is even a dir.proj used to generate version information.
It is difficult for people to find when they first encounter this project that they need to run msbuild -t:GenerateConstant dir.proj to build this project normally. At the beginning, people must be unlikely to know which program generated BuildConstants.cs .
At the same time, platform-specific codes are everywhere in dev.sh, which makes this system difficult to maintain.
We may be able to use [nbgv](https://github.com/dotnet/Nerdbank.GitVersioning) to manage the version, and use a single cross-platform powershell script as the build script (pwsh is pre-installed in all virtual environments of actions).
@TingluoHuang @ericsciple @thboop

**Comment by hross** [comment]
Completely agree: https://github.com/actions/runner/issues/1023

This is an artifact of history (old netcore did not support certain things, etc, etc). We should clean it up.
