### ISSUE TITLE
[skip ci] skips also non-CI workflows

### ISSUE THREAD

**Issue by pllim** [actions/runner#976]
Hello! This is a direct follow up of #774 and https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/ .

It is very nice that finally having `[ci skip]` in a PR's current commit does not activate the CI for `pull_request`. Unfortunately, it also did not run other things in `.github/workflows` such as the PR labeler and some triage actions (e.g., welcome message) that are unrelated to the CI testing.

How do I tell Actions that some workflows should not respect this new `[skip ci]` rule you have implemented on your server side?

Thank you!

**Comment by chrispat** [comment]
I am not sure we need a specific way to override the rule right now as long as the other events run as expected.

**Comment by pllim** [comment]
@chrispat , can you please clarify your response? My point is that I would expect PR labeler to still work but it does not kick off now if a pull request is opened and that first commit has `[ci skip]` in it.

**Comment by SanderKnape** [comment]
I second this. GitHub Actions is specifically marketed as a workflow runner, not just CI/CD. It doesn't make sense then that `[ci skip]` and such doesn't run *any* workflow anymore. Labelling PRs isn't CI nor CD, it's a workflow.

**Comment by pllim** [comment]
Thanks for the update! What about release workflow that trigger when you push a tag out; is that immune from this feature?

**Comment by astrochun** [comment]
I too was thrown off as previously I had `ci skip` as a check for specific python builds. Now that I have a separate workflow for documentation, I had hoped that `ci skip` would skip these python build actions but still allow run the docs workflow. I suppose I can change my `if` statement

**Comment by chrispat** [comment]
@pllim release events should not be affected.

**Comment by pllim** [comment]
I see that it no longer skips `pull_request_target`. So as far as I am concerned, this is fixed for me. Thanks!

**Comment by pllim** [comment]
Looks like it is skipping everything again...

**Comment by pllim** [comment]
And today it works as intended. 🤷

**Comment by salzig** [comment]
> Skipping all workflows is a bug that is being addressed. It should only skip `pull_request` and `push`. If you want to have a labeler workflow that can't be skipped you can switch to using `pull_request_target` which will always be run.

is that also true for push of tags?
