### ISSUE TITLE
Action does not get triggered for last commit when base branch is changed

### ISSUE THREAD

**Issue by R1j1t** [actions/runner#980]
**Describe the bug**
When the base branch of the PR is changed, action does not get triggered for the last commit in that PR.

**To Reproduce**
1. Create a Pull Request
2. Change the base branch for which actions should be triggered for PR
3. No ci trigger

**Expected behavior**
what I was expecting was actions to be triggered for the last commit in the PR. Wanted to check if it is not the expected behavior.

## Runner Version and Platform
Version of your runner? Public Github

OS of the machine running the runner? OSX/Windows/Linux/... 
NA

## What's not working?
Github action not getting triggered.

## Job Log Output
https://github.com/R1j1t/contextualSpellCheck/pull/49#issuecomment-776754650 link to base branch change in PR.

## Runner and Worker's Diagnostic Logs
NA

**Comment by R1j1t** [comment]
Please let me know if this is the right repository for this issue.

**Comment by thboop** [comment]
Hey @R1j1t , 

The pull request event has a variety of triggers, by default we subscribe to opened, synchronize, or reopened. You can read more about those here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

Changing the base ref is the `edited` action, you can subscribe to those as well by doing

```
name: CI
on:
  pull_request:
    types: [synchronize, opened, reopened, edited]
```
However, `edited` applies to more than just changing the base ref, for example changing the title of the pr will also trigger the edited action. 

You may filter these down using expressions, the github context stores information about why the edited event was triggered, for example:
```
    "event": {
      "action": "edited",
      "changes": {
        "base": {
          "ref": {
            "from": "main"
          },
          "sha": {
            "from": "{some sha here}"
          }
        }
      },
```

For more information on how to filter jobs based on the value of the context, please see [our official docs](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions)

I've brought feedback to the team that we should consider an event for only base ref changes as an enhancement and add it by default, but it's not currently available and I don't have a timeline for when it may be available.

I'm going to close this issue for now, but feel free to reopen it if you have any more questions!

**Comment by R1j1t** [comment]
Thanks @thboop for the detailed explanation. It definitely answers all the question I had. I will check the documentation to learn more about it. I really appreciate the quick response!

**Comment by AllanOricil** [comment]
@thboop help me with this issue 
https://github.community/t/action-not-starting-when-editing-the-title-or-description-of-a-pr/216836

**Comment by michalinacienciala** [comment]
Hi @thboop, the doc you linked (https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request) refers to https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request for more information on activity types. In that doc about webhook events, the `synchronize` activity is described as this:
> **Triggered** when a pull request's head branch is updated. For example, when the head branch is updated from the base branch, when new commits are pushed to the head branch, or **when the base branch is changed**.
Is that fragment of documentation out-of-date?

**Comment by LinusU** [comment]
@thboop has there been any more talks internally about adding this as a default?

It's quite surprising that workflow doesn't get triggered when the base branch is changed with e.g. the following configuration:

```yaml
on:
  pull_request:
    branches:
    - master
```

**Comment by cakeinpanic** [comment]
@michalinacienciala I assume that "base branch is changed" means not that new commits are pushed to master, but `master` is replaced with `dev` or smth ike this

**Comment by fsmanuel** [comment]
@cakeinpanic in my case it happens if you base a PR on another PR and the first PR gets merged. Github changes the base of the second to `main` automatically but github actions is not triggered.

**Comment by angiarao** [comment]
what happens if a base branch is rebased along with new commits? what would be event that would be triggered here? Apologies for asking question on a closed thread.

**Comment by AllanOricil** [comment]
> what happens if a base branch is rebased along with new commits? what would be event that would be triggered here? Apologies for asking question on a closed thread. 

If your workflow is sub to pull_request.edited, then it should be triggered when changing base:HEAD because the base name is just an alias for the commit sha, and the commit sha has changed.

**Comment by angiarao** [comment]
So to confirm, in the below workflow
create pr -> rebase from master -> add new commits -> force push to update the PR
it should trigger `edited` event?

**Comment by AllanOricil** [comment]
> So to confirm, in the below workflow
> create pr -> rebase from master -> add new commits -> force push to update the PR
> it should trigger `edited` event?

You changed your question. You would need a different event. It depends on if you want to trigger on push or pr, when changing your source branch.
