### ISSUE TITLE
hashFiles results in an empty string when called inside composite action

### ISSUE THREAD

**Issue by sisoje** [actions/runner#991]
**Describe the bug**

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by sisoje** [comment]
any news?

**Comment by ericsciple** [comment]
Will investigate soon. Adding this to a list of related work.

**Comment by ericsciple** [comment]
found the bug

**Comment by ericsciple** [comment]
we're starting work in this area next week. Will fix this soon...

**Comment by ericsciple** [comment]
related to https://github.com/actions/runner/pull/1040

**Comment by thboop** [comment]
Should be fixed in the latest runner release
