### ISSUE TITLE
Github Actions self hosted runner not working on RHEL 8

### ISSUE THREAD

**Issue by gautamkrishnar** [actions/runner#997]
**Describe the bug**
Github Actions self hosted runner is not working on RHEL 8 It is stuck while running the config script on the following step:

```
$ ./config.sh --url <repo> --token <Token>

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication
```

**To Reproduce**
1. Run `./config.sh --url <repo> --token <Token>` on a RHEL 8 machine

**Expected behavior**
Config should work fine

## Runner Version and Platform
Version of your runner?
v2.277.1

OS of the machine running the runner? OSX/Windows/Linux/...
Linus (Red Hat Enterprise Linux release 8.3 (Ootpa))

## What's not working?
`./config.sh --url <repo> --token <Token>`

## Job Log Output
n/a

## Runner and Worker's Diagnostic Logs
I cant find a verbose mode to debug this issue on config script to detect the root cause of the problem.

**Comment by TingluoHuang** [comment]
I can't repro this issue on a CentOS:8 docker container.
@gautamkrishnar do you mind run `./bin/installdependencies.sh` before trying to configure the runner to make sure all required dependencies are installed?

There should be a log under the `_diag/` folder for the configuration.

**Comment by gautamkrishnar** [comment]
@TingluoHuang Just tested and this is working fine right now. Not sure what was the issue. Thanks for the reply. Closing this one.
